### ISSUE TITLE
Guest account

### ISSUE THREAD

**Issue by kazk** [codewars/codewars.com#1000]
This one is hard to explain :/

I found a solution by user "guest_laq6ypozxmy" which resembles the random usernames given when training without an account (or logged out.)
![image](https://user-images.githubusercontent.com/639336/27117645-43f82f06-508c-11e7-9304-0bec95f2e8f7.png)

![image](https://user-images.githubusercontent.com/639336/27118387-e9ca8480-508f-11e7-86c3-308fe3562eeb.png)

I assumed that guests' solutions are not saved.

![image](https://user-images.githubusercontent.com/639336/27118045-445c50ce-508e-11e7-90bb-f34d53807b57.png)

So I got curious and visited "guest_laq6ypozxmy"'s profile and got `language cannot be blank (actual = nil`.

![image](https://user-images.githubusercontent.com/639336/27117657-567b492e-508c-11e7-92b6-6288b6dc0747.png)

This is different from accessing non-existent user which gives
`ApplicationController::ResourceNotFoundError` (I don't think this should be shown to the user either.)

I wanted to see what happens when guests visit their profile pages (`/users/guest_*`) and saw something strange. I made a GIF because it's too hard for me to explain this.

![2017-06-13 23 58 16](https://user-images.githubusercontent.com/639336/27120304-e1ba1d7a-5097-11e7-8518-a2eadadbc47f.gif)

- Is listing the guest's solution expected behavior?
- What's going on with guest account's profile page?

**Comment by jhoffner** [comment]
> Is listing the guest's solution expected behavior?

Sort of. Guest users are real user accounts and everything you do gets saved like normal, but guest accounts are removed after a week. I think this data is being denormalized within the database so even after they are deleted their solutions stick around. The solution is more important than who did it. 

> What's going on with guest account's profile page?

Lack of attention testing this flow. This is probably an easy fix.

**Comment by kazk** [comment]
Fixed
