### ISSUE TITLE
Test cases should have their own namespace.

### ISSUE THREAD

**Issue by gtzampanakis** [Codewars/codewars.com#1004]
I was solving https://www.codewars.com/kata/how-many-numbers-iii . I named one of my functions "h". My code passed the basic tests but it was failing each time on the random tests. After a while I figured it out: The testing code had overwritten my "h" function.

This should not be possible. Test code should be in its own namespace.

**Comment by jhoffner** [comment]
I agree but what's done is done. Unless someone feels like changing every challenge in the system and doing it all in a way that doesn't involve taking the site down for days while that happens - this cannot be changed.
