### ISSUE TITLE
Allow "super" power users to fix issues

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#1010]
> One idea is to make it easier to find kata waiting for issues to be fixed along with a reward for fixing the kata. The main issue there is how much of a rabbit hole would it be to reward power users for fixing a kata and do it in a way where they can't just close an issue and get points without actually doing the work.
>
> https://github.com/Codewars/codewars.com/issues/997#issuecomment-308932665 by @jhoffner

I think many power users will fix the kata **without** any rewards. Power users already help authors fix issues without any rewards in terms of Codewars points. Sometimes a power user does more work than the author :|

So I don't think this main issue is an issue. I'd suggest starting from simply allowing certain power users (maybe ~13k+ honor points, top 50) to fix them without rewards. Maybe require at least another power user to check the work before applying the fix to existing kata.
We can discuss about rewarding the power users if this fails.

---

@jhoffner, @Voileexperiments, @10XL, @DonaldKellett, @dinglemouse2250

**Comment by dinglemouse2250** [comment]
I think the activity of the Kata author needs to be taken into account somehow.

* If the author is not active for some time (eg 2+ weeks) then sure, somebody else should be able to step in and fix things.

* But if the author is *active*, then I really would not want for some overly eager power user to jump in and fix my problem while I was sleeping and already planning to fix it the next day!

**Comment by jhoffner** [comment]
This should now be implemented, if anyone wants to test. If an author has been inactive for more than 7 days, and there are active issues, then any user with the ability to coauthor a challenge can edit a published challenge.

**Comment by Voileexperiments** [comment]
Niiiiiice!

Fixing all the katas I listed on #940 now.

**Comment by Voileexperiments** [comment]
I just accidentally resolved all the issues before I managed to *actually* re-submit the kata (you know, those goddamn publish timeout!), and now I can't get the edit to open anymore :(

Is it intended? Are there any ways to make it open for edit again?

**Comment by anter69** [comment]
> Are there any ways to make it open for edit again?

How about creating an issue? 😄

**Comment by Voileexperiments** [comment]
> How about creating an issue? :smile:

I tried, but it didn't work.

I even tried using my alt account to create an issue, and that didn't work either :V

**Comment by Voileexperiments** [comment]
I think the edit requirement is broken:

> If an author has been inactive for more than 7 days, and there are active issues, then any user with the ability to coauthor a challenge can edit a published challenge.

But [this kata](https://www.codewars.com/kata/directions-reduction/javascript) has no issues and the author is very active (it's `g964` after all), and yet I can still edit it without problems. Seems like some katas turn out false negatives while some katas turn out false positives.

**Comment by jhoffner** [comment]
I meant to say if the author has been inactive on that issue. Basically if the oldest issue on the challenge is older than 7 days then edits are allowed.
