### ISSUE TITLE
Kata star status are not updated inside train page

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1011]
Katas I starred appears like this in every page accessible from outside (Description, Solutions, Discourse):

![image](https://user-images.githubusercontent.com/14909989/27491262-3eef838e-5874-11e7-9c23-821f01918b7f.png)

But not in the train page:

![image](https://user-images.githubusercontent.com/14909989/27491273-4891c9ce-5874-11e7-921f-6801fc1a34a4.png)

**Comment by kazk** [comment]
Maybe #763 is similar issue.

**Comment by Voileexperiments** [comment]
@kazk The star experiences the same issue as #921 as well, but that's probably a separate issue in itself.

**Comment by error256** [comment]
I think it's been fixed recently?

**Comment by Blind4Basics** [comment]
Recently to what point? Because I've seen the problem again just some days ago.

**Comment by kazk** [comment]
I removed some unnecessary caching for the trainer recently, so that probably fixed this one.

I think what @Blind4Basics is describing is #763, and is a different issue.
