### ISSUE TITLE
Unable to submit any code in Edge browser

### ISSUE THREAD

**Issue by vereenarcy** [Codewars/codewars.com#1012]
Cannot submit any code in Edge and EE browsers ("Run sample tests" and "submit" buttons). The following error messages appears:
"Failed to communicate with code execution service"
Other browsers (FF, for example work fine)
![codewars](https://user-images.githubusercontent.com/29608520/27511154-130f8a58-5927-11e7-819a-4672cb47d4a4.png)
Screenshot: left windows is FF after "Run sample tests" button pressed, right windows - Edge.

**Comment by kazk** [comment]
Are you still having this issue? I'm unable to reproduce.

![image](https://user-images.githubusercontent.com/639336/32077623-eb3a047a-ba58-11e7-8da0-fb7a954fafac.png)

This is on Windows 10, Microsoft Edge 40.15063.674.0

**Comment by vereenarcy** [comment]
Yes, now it is not reproducible for me also. Closing the issue.

**Comment by SherylHohman** [comment]
Today, I experienced this same issue.  It was working fine earlier today, and days previous.
Windows 10 Pro, IE Edge.

I then downloaded Chrome, and it worked fine.
Retried on IE Edge, still cannot connect.
