### ISSUE TITLE
User Profile > Solutions > Obsolete => Crash

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1013]
View User Profile

Choose "Solutions" tab

In Solutions tab there is choice of "Completed" or "Unfinished" or "Obsolete"

Choose "Obsolete" 

Crashes with following message
* **undefined method `code_challenge_review' for nil:NilClass**

**Comment by error256** [comment]
I've got the same thing today, only in "Completed" instead of "Obsolete". I think it may have happened after I solved a kata in JS and then the JS version of the kata was removed.

**Comment by kazk** [comment]
This should be the same issue as #1627

Used to happen when a language you wrote a solution in was deleted. It should be fixed now.
