### ISSUE TITLE
Kata translation comments are shown on dashboard but the link is not linked to anywhere

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1016]
Example:

![image](https://user-images.githubusercontent.com/14909989/27563725-ed49ea58-5b05-11e7-8b2a-9e5ed5c94d73.png)

The part after "comment on" can be hovered on as usual, but it does not have any links.

**Comment by kazk** [comment]
This is probably duplicate of #68.

**Comment by ice1000** [comment]
WTF
