### ISSUE TITLE
Pusher account over quota.

### ISSUE THREAD

**Issue by aelana** [Codewars/codewars.com#102]
I have noticed in chrome's javascript console this error coming up:

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4004,"message":"Account over quota"}}}
```

I am not sure it is related but right now I am unable to even submit a solution (or maybe it is submitting just not returning) and keep getting `Submission timed out. Please try again.`  This is on a non-computationally, non-resource intensive kata/solution.

**Comment by rapito** [comment]
Same here.
