### ISSUE TITLE
Can somebody please approve my pending translations, or setup a general solution as requested before?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1021]
Title says it all.

After 4 months waiting, I still have pending translations, just as many other codewarriors, due to Kata authors gone missing. Please approve my translations (little work), or setup a general solution as requested before, both by me and by others (little more work).

I'm almost ready to give up on Codewars, I've simply invested too much wasted time due to this issue. Apparantly everything gets priority over this, while the solution is not that hard and would benefit many codewarriors.

**Comment by nomennescio** [comment]
Thank you very much Jake!

**Comment by nomennescio** [comment]
I still have one pending C translation on an abandonded translation, can you also approve that one, or let me know what I can do about it to get it approved?

**Comment by jhoffner** [comment]
Done
