### ISSUE TITLE
I can't run any tests

### ISSUE THREAD

**Issue by chrillefar** [Codewars/codewars.com#1027]
I'm trying to run the sample tests from some simple Katas. It's Java code. I've done a few Katas before, I just started again, and every time i run them I get an error message (look at the bottom of this text). I'm sure there's nothing wrong with my code, I even tried to unlock the solutions and copy paste the top voted solution, and I still get this same error. I have no idea why.

Error: Command failed: javac -verbose -cp /home/codewarrior -d /home/codewarrior -sourcepath /home/codewarrior -cp /usr/local/groovy/lib/junit-4.12.jar:/usr/local/groovy/lib/hamcrest-core-1.3.jar /home/codewarrior/Kata.java /home/codewarrior/SolutionTest.java ./frameworks/java/CwRunListener.java
[parsing started RegularFileObject[/home/codewarrior/Kata.java]]
[parsing completed 36ms]
[parsing started RegularFileObject[/home/codewarrior/SolutionTest.java]]
[parsing completed 8ms]
[parsing started RegularFileObject[./frameworks/java/CwRunListener.java]]
[parsing completed 2ms]
[search path for source files: /home/codewarrior]
[search path for class files: /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar,/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar,/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar,/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar,/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar,/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar,/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar,/usr/lib/jvm/java-8-oracle/jre/classes,/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar,/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar,/usr/local/groovy/lib/junit-4.12.jar,/usr/local/groovy/lib/hamcrest-core-1.3.jar]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/util/Arrays.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Object.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/Test.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/Assert.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/runners/JUnit4.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/runner/notification/Failure.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/runner/notification/RunListener.class)]]
[loading ZipFileIndexFileObject[/usr/local/groovy/lib/junit-4.12.jar(org/junit/runner/Description.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/StringWriter.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/PrintWriter.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Throwable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/String.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/Retention.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/RetentionPolicy.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/Target.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/ElementType.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/annotation/Annotation.class)]]
[checking Kata]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/Serializable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/AutoCloseable.class)]]
/home/codewarrior/Kata.java:8: error: cannot find symbol
        Arrays.sort(mixedArr);
        ^
  symbol:   variable Arrays
  location: class Kata
[checking SolutionTest]
[checking CwRunListener]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Comparable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/CharSequence.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Byte.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Character.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Short.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Long.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Float.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Integer.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Double.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Boolean.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Void.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/util/Locale.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/System.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/PrintStream.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Appendable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/Closeable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/FilterOutputStream.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/OutputStream.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/Flushable.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/Writer.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/io/File.class)]]
[loading ZipFileIndexFileObject[/usr/lib/jvm/java-8-oracle/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Throwable$PrintStreamOrWriter.class)]]
[total 573ms]
1 error

**Comment by chrillefar** [comment]
<img width="1242" alt="screen shot 2017-07-06 at 14 42 46" src="https://user-images.githubusercontent.com/29949482/27911461-69ddb18a-6259-11e7-9907-330ca29ab9a2.png">

**Comment by Voileexperiments** [comment]
```
/home/codewarrior/Kata.java:8: error: cannot find symbol
Arrays.sort(mixedArr);
^
symbol: variable Arrays
location: class Kata
```

You didn't import Arrays before using it, so it's your code's fault.

---

Java code seems to be generate lots of extra error messages compared to, say, C# and JS. Why does that happen?

**Comment by kazk** [comment]
> Java code seems to be generate lots of extra error messages compared to, say, C# and JS. Why does that happen?

The Java runner had a major update recently and maybe that `-verbose` flag was used while developing.

@jhoffner is this verbosity intentional? I think it's difficult to see the error with all that information.
