### ISSUE TITLE
kyu not getting updated after solving problems

### ISSUE THREAD

**Issue by ajityadav83** [Codewars/codewars.com#1029]
i have solved 7 kyu and 6 kyu problems but still it shows 8 kyu on my pro file page.. when it will be updated and how...
i have solved two problems 
sumTwoSmallestNumbers(array) for 7 kyu and function duplicateEncode(word) for 6 kyu

please help

**Comment by jhoffner** [comment]
Welcome to Codewars @ajityadav83. From your profile page you can see your progress towards your next rank. You don't just solve a 7kyu kata and become 7kyu, you need to solve a number of them (around 10) to reach the next rank. If you solve harder kata you will rank up faster to your next rank. 

Though this is no longer how the system works, you can check out [this kata](https://www.codewars.com/kata/codewars-style-ranking-system) which explains the original implementation of the ranking system. The current system is pure math based but the same basic principles of reaching a new rank apply.
