### ISSUE TITLE
Suggestion: put ads on your site and hire more damn programmers to fix your buggy kata!

### ISSUE THREAD

**Issue by Vodkacannon** [Codewars/codewars.com#1030]

**Comment by DonaldKellett** [comment]
> Put ads on your site

I'm pretty sure that Codewars already displays an ad on every user profile page and on the Kata search page (if I remember correctly) - the only way to *not* have ads is by going Red and choosing the correct account settings.

> Hire more d\*\*\* programmers to fix your buggy Kata!

Codewars Kata are *community-contributed* meaning that any Codewars user with an honor score above a (very low) threshold can already author Kata that can potentially become part of the site.  If you've been encountering buggy Kata, chances are that the Kata was authored by an inexperienced Codewars user.  This has nothing to do with the Codewars admins whatsoever so if you find a buggy Kata then leave a suitable comment in the Kata discourse (respectfully) to notify the *Kata author* that his/her Kata is buggy.  If the Kata author is active then he/she can fix the bugs you mentioned in your comment to that Kata.  *Very occasionally*, if the Kata author is no longer active then you can **kindly** ping the site admin, @jhoffner , to notify him about the buggy Kata and he *may* (or may not) then intervene and fix said Kata.

****

Oh, and one last note - not sure what is with this rude, inconsiderate attitude here but if you don't like Codewars then *just find another site to train your programming skills on*!  But trust me, *nothing* you find outside of Codewars (be it Hackerrank, CodinGame or some other similar programming websites) will be as *convenient and natural* - while Codewars uses pure TDD/BDD to directly test for function/method return values (much like what you would do in a typical production environment), every other "similar" site I can find uses some convoluted method of file I/O to pass in the input and test for output respectively which I can never understand.

****

@kazk Would you mind closing this Issue?  Thanks a lot :smile:

**Comment by kazk** [comment]
@Vodkacannon
If you're experiencing an issue that is not related to specific kata, please open an issue including steps to reproduce. Otherwise, please let the kata author know by commenting on the kata discourse as @DonaldKellett suggested.
You can access the dedicated discourse by clicking "Discourse" tab:
![image](https://user-images.githubusercontent.com/639336/27991562-a95c8606-642f-11e7-9065-69f1735b3e8a.png)
