### ISSUE TITLE
persistent XSS via clans name

### ISSUE THREAD

**Issue by lucasduffey** [Codewars/codewars.com#1034]
# repro
* go to https://www.codewars.com/users/edit
* add the following to the "Clan" field: 
`"><script>alert(/clan/)</script>`

**Comment by lucasduffey** [comment]
still unfixed

go to https://www.codewars.com/dashboard to repro

**Comment by lucasduffey** [comment]
I created https://github.com/Codewars/codewars.com/issues/1040 because it doesn't look like this will be reopened

**Comment by jhoffner** [comment]
I wasn't trying to have this be super obvious. It's generally best to report XSS via email.

**Comment by lucasduffey** [comment]
I did - several times to several different locations. I got no reply.

**Comment by jhoffner** [comment]
hmm. OK then, I didn't see anything. You can send it to jake at codewars.com next time. Thanks for letting us know. I have a change ready in preview.codewars.com if you want to test.
