### ISSUE TITLE
XSS in "description" when creating a new kata

### ISSUE THREAD

**Issue by lucasduffey** [Codewars/codewars.com#1036]
# Repro
* go to http://www.codewars.com/kata/new/c
* add `"><script>alert(/desc/)</script>` to `description field`
* it will render automatically

**Comment by lucasduffey** [comment]
it's possible this is just a self-xss, didn't publish it

**Comment by jhoffner** [comment]
Yes this should only be an issue within the editor. If you save it will go away.
