### ISSUE TITLE
Beta kata with no issues and satisfies approval requirements shows "Waiting issues to be resolved"

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1037]
[This kata](https://www.codewars.com/kata/multiplying-numbers-as-strings-part-ii).

---

Could it be that it has to do with open issues that are deleted by the original poster? Because I did that before the kata meets approval requirements.

**Comment by kazk** [comment]
I don't know what happened, but my vote made it approvable. Approved with 3 kyu (power user average).

**Comment by Voileexperiments** [comment]
Hmm, IIRC I've seen it once before that an additional vote beyond the usual threshold is needed to make a kata approvable. Looks like an edge case bug.

**Comment by kazk** [comment]
Before I voted the status was "Waiting issues to be resolved" like you noticed. Navigating to discourse after voting made the status change.

> an additional vote beyond the usual threshold is needed

What do you mean by additional vote?

I guess that one was considered purple?

<table>
<thead>
<tr>
<th>Level</th>
<th>Satisfaction %</th>
<th colspan="4">Required Votes by # of Approved Kata</th>
</tr>

<tr>
<th></th>
<th></th>
<th>&lt;10</th>
<th>&lt;20</th>
<th>&lt;30</th>
<th>30+</th>
</tr>
</thead>

<tbody>
<tr>
<td>White</td>
<td>90+</td>
<td>12</td>
<td>10</td>
<td>8</td>
<td>6</td>
</tr>

<tr>
<td>Yellow</td>
<td>85+</td>
<td>10</td>
<td>8</td>
<td>7</td>
<td>5</td>
</tr>

<tr>
<td>Blue</td>
<td>75+</td>
<td>8</td>
<td>6</td>
<td>5</td>
<td>4</td>
</tr>

<tr>
<td>Purple</td>
<td>70+</td>
<td>5</td>
<td>4</td>
<td>3</td>
<td>3</td>
</tr>
</tbody>
</table>

**Comment by Voileexperiments** [comment]
Yes.

What I mean was that very occasionally a kata will have the required votes and satisfaction rating but is still not available for approval yet (which will then show as "issue waiting to be resolved"). At least IIRC that has happened once before.

**Comment by Rodrigo-Coloma** [comment]
[https://www.codewars.com/kata/652643925c042100247fffc6](This Kata)


How can it be approved?
