### ISSUE TITLE
Java Bug

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1038]
This kata:
<https://www.codewars.com/kata/directions-reduction/java>
was solved by 972 guys but now it is impossible to pass it: many guys (so do I) get:
```
Note: /home/codewarrior/src/main/java/DirReductionTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
though the tests have the same form as in other Java kata.
Furthermore when I click "My solutions" I get : "There are no solutions yet for this kata."... Strange!

**Comment by SteffenVogel79** [comment]
The same problem in my java-katas.

**Comment by dinglemouse2250** [comment]
Ditto. Me also starting to get a few comments about Java Kata which had no problems until now. Stuff like:
```
STDERR: Note: /home/codewarrior/src/main/java/ExampleTests.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.
```

**Comment by jhoffner** [comment]
@SteffenVogel79 and @dinglemouse2250 have you retried the code yet? This should have been resolved last night.

**Comment by dinglemouse2250** [comment]
FYI - I had already modified my Kata code to workaround the problem so I have nothing to re-try.

**Comment by SteffenVogel79** [comment]
It works now. Thanks Jake!
