### ISSUE TITLE
CW code running server is very slow recently

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1039]
I keep encountering these during the last few days:

![image](https://user-images.githubusercontent.com/14909989/28253562-bd68ccf0-6ad7-11e7-92aa-b1adeb42bc2c.png)

![image](https://user-images.githubusercontent.com/14909989/28253568-d77add5e-6ad7-11e7-8568-4bcae542b3ae.png)

Now if it's as infrequent as #993 then I could live with it, but this is not - this can happen more than 50% of the time in some cases. Even worse, if a submission is stuck at "Assigning a server" or "Request received" it could easily take a minute before timeout happens. This is very frustrating and totally wrecks my coding flow :(

**Comment by whateverforever** [comment]
Same here. It's about 7/8ths of the time

**Comment by 10XL** [comment]
has there been a significant increase in traffic?

**Comment by pieter-1983** [comment]
This morning I can't get even submit or attempt the simplest of Kata's. keeps on giving time out errors, very frustrating. (Not red)

**Comment by barnettjoe** [comment]
Same here - repeatedly seeing this one:
> The server timed out running the request. This may be due to an issue with the backend server. Please try again.

**Comment by Dacelonid** [comment]
Same here, for the last couple of hours have been unable to attempt a solution in Java

**Comment by joni3k** [comment]
Same here, have been unable to run any solutions in javascript

**Comment by markaleksander** [comment]
Same issue with Python.

**Comment by whateverforever** [comment]
Still the same issue. Is codewars still maintained?

**Comment by kolysg** [comment]
I'm receiving the same error as well. Hope there's a discussion on how to resolve this. If anyone knows, please forward it to me.

**Comment by Criss-Blake** [comment]
Same here, it always stops responding.

**Comment by razvan-panda** [comment]
Getting a lot of these when using Haskell. Not sure about other languages yet.
But it either runs very fast or it timeouts.
It does not seem to have anything to do with the actual time it would take to run the code.

**Comment by BrianARuff** [comment]
Same problem here... Is there a DDOS attack happening to them or something?

**Comment by MingXingTeam** [comment]
same problem!!!!

**Comment by BrianARuff** [comment]
This site is incredibly every time I use it, and I use it every day. 14 days ago the site was unusable, now it's usable but very irritating to use.

**Comment by alexcampos09** [comment]
Same thing with python. This is happening for over a year, it seems.
Is there a way to solve that? The site is really awesome otherwise.

**Comment by LuiDavinci** [comment]
@kazk what about codewars.com itself? Every Day I go on there and click on Train, it takes ages to load, once on there and clicking submit it takes ages again, the code execution works fast.

I tried every browser with and withoud plugins, and i got a 400mbit connection.

**Comment by kazk** [comment]
@LuiDavinci Sorry about that. We're aware of the performance issues with codewars.com itself. Unfortunately, we don't have the bandwidth at the moment to fix them. We're looking into options to improve incrementally.

**Comment by LuiDavinci** [comment]
@kazk I see. No worries. Have you guys thought about asking for voluntary contributions from users for servers and bandwith, like reddit or maybe through patron or else. Just a thought.
Thank you guys for your work.

**Comment by kazk** [comment]
@LuiDavinci By "we don't have the bandwidth" I meant "we don't have enough time" and not that we have limited network bandwidth. Sorry for the confusion.
