### ISSUE TITLE
Impossible to kumite

### ISSUE THREAD

**Issue by bestwebua** [Codewars/codewars.com#1041]
Impossible to view/edit the translation - **undefined method `name' for nil:NilClass**

>Looks like there was a server error! (500)
>We have taken note of the situation and will be looking into it.
>If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
