### ISSUE TITLE
Cannot open 'Solutions' in my profile

### ISSUE THREAD

**Issue by Marcin-Kulik** [Codewars/codewars.com#1042]
I am using Safari.

Recently very often when I open 'Solutions' in my profile I get:

Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `code_challenge_review' for nil:NilClass

**Comment by ntgv93** [comment]
Solutions stop loading starting page 2. 
users/ntgv09/completed_solutions returns 200 
/users/ntgv09/completed_solutions?page=1 returns 200
/users/ntgv09/completed_solutions?page=2 returns 500.

**Comment by bestwebua** [comment]
The same when kumite.

**Comment by kazk** [comment]
I'm going to close this as resolved. Please let us know if this ever happens again. There're lots of issues reported related to `nil` and they're really difficult to reproduce.

**Comment by Marcin-Kulik** [comment]
Thank you, I will let you know if it happens again.
