### ISSUE TITLE
Unable to delete draft kata without any completions

### ISSUE THREAD

**Issue by chris-rands** [codewars/codewars.com#1043]
I am unable to delete [this kata](https://www.codewars.com/kata/589dcc97b5690457cb00011a/) that I have not yet published. When I click the 'Delete' button and confirm I wish to delete the kata, the deletion never occurs. I am aware there are other related issues on this, but could not see an identical issue, and I was unable to resolve this, please advise, thanks

**Comment by docgunthrop** [comment]
I'm having the same issue with [this](https://www.codewars.com/kata/588da62b5e86e6ea67000082) that's never left Draft.

**Comment by Voileexperiments** [comment]
It seems that katas can't be deleted once a language version is created for the kata, even if it has never been published.

@kazk The delete kata feature looks completely broken. I think either this should be fixed, or if it can't be fixed, remove the delete kata button? It doesn't stop useless katas from cluttering the authored kata list though. Maybe make deletion turning a "permanently hide this kata from everywhere" flag on instead?

**Comment by ohwelpwelp** [comment]
this bug had existed for 3 years!, I having the same problem!

**Comment by dolamroth** [comment]
Please, delete these 2 as well

https://www.codewars.com/kata/5d85374fc5a0d000254850c2
https://www.codewars.com/kata/5d83314ad3b773002113cc0c

**Comment by kazk** [comment]
Looks like there's a bug where Codewars thinks someone had attempted it because the author had previewed the kata (it creates a same record as other user attempting if I remember correctly). I'll look into this sometime soon.

**Comment by DenisDziganchuk** [comment]
Please delete these kata too:
https://www.codewars.com/kata/6046b31b01c6c9001330359a/
https://www.codewars.com/kata/6043e9680e7328001ec2455c/
https://www.codewars.com/kata/603d7c3ad48bac0017a22986/
https://www.codewars.com/kata/603d7c3ad48bac0017a22986/
https://www.codewars.com/kata/6025896a30de66000de95e52/
https://www.codewars.com/kata/6025841dff5c14000ef617e7/
https://www.codewars.com/kata/6025745e1cb14e000ff7f8de/
https://www.codewars.com/kata/6024bd5b7bb453000864da1c/
https://www.codewars.com/kata/60121d0a96a18300265dfefd/
https://www.codewars.com/kata/6011f1d94c1824002bd3803d/
https://www.codewars.com/kata/5fc5865367a01000084ebff7/
https://www.codewars.com/kata/5faf108d7b069e000fe9daef/
https://www.codewars.com/kata/5f7510d00a8695002e10fa30/
https://www.codewars.com/kata/5f4933bececf9e0011a8bc27/
https://www.codewars.com/kata/5f4862404cbed500341e41c9/

**Comment by kazk** [comment]
Whenever a user opens a trainer for a kata `/train`, a new record that references the kata is created. This is configured to prevent the kata from being deleted. When authors preview their kata, the same record is created, and this was preventing deletion.

I made a change to delete the author's record if it's the only one. So, if the kata was never trained by anyone else, you should be able to delete it now. I've tested locally, but please let me know if it still doesn't allow you to delete it. I'll check the database to see if there's any other record referencing it.
