### ISSUE TITLE
browser crashing when opening https://www.codewars.com/trainer/setup

### ISSUE THREAD

**Issue by yuriko192** [Codewars/codewars.com#1046]
so i have this weird problem everytime i try to logon to the webpage [https://www.codewars.com/trainer/setup](url). my browser seems to be crashing no matter what i do. ive tried changing browser, but the result is still the same. ive tried using mozilla, opera, and chrome. but its no use.
![untitled](https://user-images.githubusercontent.com/30367416/28490329-b1538058-6f01-11e7-8bfe-7edcd71d1f53.png)
![untitled1](https://user-images.githubusercontent.com/30367416/28490343-e0f71554-6f01-11e7-95c0-c33d74bd6bf4.png)

**Comment by JimDiGrise** [comment]
i have save problem.
try Firefox and chrome.

**Comment by yuriko192** [comment]
it's fixed already, i upgraded my PC to Win10 and it worked
