### ISSUE TITLE
Thin screen hides buttons

### ISSUE THREAD

**Issue by Deantwo** [Codewars/codewars.com#105]
Using my smartphone to browse CodeWars can be a little hard.
If the screen isn't wide enough to display a button, the button just doesn't appear at all.

![screenshot_2015-06-14-04-17-53](https://cloud.githubusercontent.com/assets/2676134/8146784/8613d4a6-124c-11e5-946e-93393b47ee2b.png)
![screenshot_2015-06-14-04-18-13](https://cloud.githubusercontent.com/assets/2676134/8146785/8c581cb4-124c-11e5-8d20-5d7b0b88e026.png)

As you can see in the above pictures, the **Discourse** button only appears in landscape view. Meanwhile buttons like **Edit Kata** never appear at all.

Kata in the picture: [Highest and Lowest](http://www.codewars.com/kata/554b4ac871d6813a03000035/discuss/java)

**Comment by kazk** [comment]
This will be tracked in #939
