### ISSUE TITLE
cannot attempt Kata

### ISSUE THREAD

**Issue by karmazynow-a** [Codewars/codewars.com#1050]
When I finish my code then choose attempt button nothing happens. 
If I haven’t run sample tests earlier, there’s a message in output: „Your results will be shown here”. 
I tried various Kata, everywhere same issue.

**Comment by netserf** [comment]
Same here. 

The SKIP, UNLOCK SOLUTIONS, and DISCUSS buttons all work, but the RESET, RUN SAMPLE TESTS, and ATTEMPT buttons do not. When I hover over the broken buttons there is no indication that these 3 option are available. When I click on them, nothing happens.

However, when I turn on the Chrome developer tools, I can use these broken buttons.

I've tried this in Chrome 59.0.3071.115.

**Comment by karmazynow-a** [comment]
I'm using mozilla firefox, but I tried codewars using Microsoft Edge and everything worked. 
It would be easier for me working on mozilla though

**Comment by jhoffner** [comment]
@karmazynow-a  @netserf Which systems are you guys on? Firefox and especially Chrome should work correctly. Edge and IE are the last place I would expect the site to function best.

**Comment by netserf** [comment]
@jhoffner As I mentioned earlier, I tried this on Chrome 59.0.3071.115.

I noticed my version of Chrome has updated. It is now Version 60.0.3112.90 (Official Build) (64-bit).

On codewars.com the RUN SAMPLE TESTS and ATTEMPT buttons are working today, but I get these responses from the server: 

> STDERR:
> Process was terminated. It took longer than 12000ms to complete
> SIGKILL
> Process exited prematurely with a SIGKILL signal.
> Server Execution Error:
> The server timed out waiting for the code to finish executing. It is possible that this is due to high server load. It may also be caused by **inefficent** code. Please try your request again.
> 

Obviously not the same issue, so that's progress. Note that "inefficient" is spelled incorrectly.

**Comment by netserf** [comment]
Oh and thank you for looking into the problem. I appreciate the help!

**Comment by Voileexperiments** [comment]
What language are you doing? Haskell is known to be erratic after submission, sometimes it just timeouts for no reasons.

Otherwise when that message appears it's usually because you code is too inefficient.

**Comment by netserf** [comment]
I'm working in python. I was randomly resubmitting old submissions and I've never seen this message in the past.

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.

**Comment by netserf** [comment]
Thanks for the update! I'll check it out when I have a moment.
