### ISSUE TITLE
Can't un-star Kata on preview site

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1051]
Using http://preview.codewars.com

Unable to "un-star" a selected Kata. Clicking on star does nothing. 

But main site seems OK, so is this a new bug soon to be released? 😄

**Comment by ice1000** [comment]
But I can.

**Comment by kazk** [comment]
Issues for the preview site shouldn't be opened here. It's mainly used for testing and verifying the fix.
In this case, using `https` should work. We should always be using `https` and redirect to it, but there's some weird issue preventing us at the moment.
