### ISSUE TITLE
Discuss button disappears when width of window is not wide enough

### ISSUE THREAD

**Issue by puyanwei** [Codewars/codewars.com#1052]
I had recently only realised that I could access the discuss pages because there was a button there! 

The button was not there when I had my window to a thinner width! I am using Chrome, I'm not sure if this bug is happening to other browsers as well.

![screen shot 2017-07-27 at 14 46 51](https://user-images.githubusercontent.com/14803518/28673602-d1606e42-72da-11e7-9b8a-1b8ec3ab3a18.png)

![screen shot 2017-07-27 at 14 47 01](https://user-images.githubusercontent.com/14803518/28673604-d3ac97c0-72da-11e7-89e4-1423bb6ddbef.png)

**Comment by Voileexperiments** [comment]
Yes, this happens for other buttons as well.

e.g If you're using mobile, most of the buttons in user profile page is unreachable.

**Comment by kazk** [comment]
This issue will be tracked on #1214
