### ISSUE TITLE
Number of katas shown in the search result also counts katas from nowhere

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1053]
I only have 8 published purple JS katas (3 2kyus and 5 1kyus) left unsolved.

However, search results say "9 kata found":

![image](https://user-images.githubusercontent.com/14909989/28681996-faffdc94-732d-11e7-8a0e-6360a485d58e.png)

Apparently there is a 8kyu kata that is not shown but is yet still counted:

![image](https://user-images.githubusercontent.com/14909989/28682421-77c95204-732f-11e7-8576-2482bc143df9.png)

![image](https://user-images.githubusercontent.com/14909989/28682400-5dfea8c4-732f-11e7-9b58-78287ea5af81.png)

**Comment by kazk** [comment]
Should be fixed
