### ISSUE TITLE
Kata search tag list applies the wrong filtering if some Sort by options are chosen

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1054]
For example:

![image](https://user-images.githubusercontent.com/14909989/28682475-b019f618-732f-11e7-8089-3616f2f8e4e1.png)

As shown in the picture, the tag list properly shows the tags of the search results.

However, if I choose to sort by Newest/Hardest/Most Completed, then the tag list is broken and shows the tag of almost all of the katas (not all of them, the numbers are still smaller than that when I choose "Progress: All"):

![image](https://user-images.githubusercontent.com/14909989/28682502-cac56e8e-732f-11e7-86e6-f44df67676c4.png)

Sorting by Name/Recently published/Least completed gives *even less* numbers:

![image](https://user-images.githubusercontent.com/14909989/28682703-84f4d5d8-7330-11e7-8a2e-fa8ea11a210d.png)

And sorting by Positive Feedback gives a moderate number:

![image](https://user-images.githubusercontent.com/14909989/28682759-b0b79962-7330-11e7-991b-ab22c9daec40.png)

**Comment by kazk** [comment]
Fixed
