### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by DevGrrrl** [Codewars/codewars.com#1057]
Have tried a couple of Kata this morning (over the past few hours) and keep getting this error whenever i click Run Sample Tests. This has happened on several different Kata: 

Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

When I retry I get the same message.

**Comment by oecampbell** [comment]
I got exactly the same message as above therefore, can't do any Katas

Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by samlasserson** [comment]
Same here - opened up the dev console and saw it's a header access issue, here's the error message:

XMLHttpRequest cannot load https://runner.codewars.com/run. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cr.codewars.com' is therefore not allowed access. The response had HTTP status code 504.

**Comment by AlexaGuk** [comment]
The same all day 
runner.codewars.com/run:1 POST https://runner.codewars.com/run 504 ()
cr.codewars.com/?utm_source=codewars&utm_medium=web&utm_campaign=kata_trainer#theme=dark&congrats=true&pro=false:1 XMLHttpRequest cannot load https://runner.codewars.com/run. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cr.codewars.com' is therefore not allowed access. The response had HTTP status code 504.

**Comment by Feenposhleen** [comment]
Someone missed a CORS header during infra work I suppose. Can't submit/test anything either.

**Comment by VJourdes** [comment]
I got exactly the same message as above therefore, can't do any Katas, since 3 hours

Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by kprintf** [comment]
It's revived

**Comment by patricksile** [comment]
Hey I have been going through the same problem for 2 weeks now and I can tell you it is pretty bad for me, and I don't know what can be done about it @jhoffner please do something. Thanks....

**Comment by iwanttobealight** [comment]
same trouble

**Comment by KLFar** [comment]
i have the same problem over and over.

**Comment by woodywood68** [comment]
Yeah had this problem a few times last week, and then today it's never ending!

**Comment by LarryAtGU** [comment]
samething to me, any ideas?

**Comment by Duduxs** [comment]
same problem here

**Comment by danipreciado** [comment]
same problem

**Comment by kazk** [comment]
It's unrelated to the original issue. https://status.codewars.com/incidents/ymg0y1r172sl

**Comment by Elias-MB** [comment]
Me pasa lo mismo
