### ISSUE TITLE
Cannot run/test Kata

### ISSUE THREAD

**Issue by lawnboyy** [Codewars/codewars.com#1058]
I attempted 2 different kata today and every time I attempt to run the sample tests I receive the following error:

"This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request."

I retried several times with the same results.

**Comment by incik** [comment]
Same here :( Doesn't matter which language I choose, I always end up with this message :(

**Comment by kchwalisz** [comment]
Same here :(

**Comment by ChristianECooper** [comment]
+1

**Comment by chinesedfan** [comment]
Duplicate of #1057. Sad~ No kata can be trained.
