### ISSUE TITLE
Mobile web typing issue

### ISSUE THREAD

**Issue by sihyungkim** [Codewars/codewars.com#1059]
I use Galaxy s7.
Whenever I use your site as a mobile web, 
I creep in whenever I enter a character.

 For example, if I enter
 ' return ',
 ' 

return ' is entered.

**Comment by ShinduHub** [comment]
I have the Same issue and everytime I Press a Key it adds one Line above

**Comment by Voileexperiments** [comment]
That's a known issue of CodeMirror itself (the code editor CW's been using).

A workaround is to request desktop site when doing katas in mobile.

**Comment by kazk** [comment]
CodeMirror was updated to the latest 5.24.4.
If this still happens, please try https://codemirror.net/. Then file an issue on upstream if it's broken there as well because there's nothing we can do in that case.

Please let me know if it works there and it's still broken on Codewars.
