### ISSUE TITLE
Can't accept C++ translation for one of my kata

### ISSUE THREAD

**Issue by mlevesquedion** [Codewars/codewars.com#1060]
I can't access a translation for my kata : "Swapping values (Revamped!)". When I click on the "A new translation for one of your kata has been published" notification, I get the error message below. I also get this error message when I try to access the translation via the kata editor. Is there another way to access the translation, so that I might approve it? Alternatively, is there a way to fix this error?

Error message :
"Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `name' for nil:NilClass"

Thank you for your time.

**Comment by ice1000** [comment]
Have you tried switch from www.codewars.com to preview.codewars.com

**Comment by error256** [comment]
I get this for https://www.codewars.com/kumite/5b95552b875de9a094000274 that is the Scala translation here: https://www.codewars.com/kata/find-divisors-of-a-number/translations

**Comment by error256** [comment]
It still happens for me both on www and preview.

**Comment by kazk** [comment]
@error256 thanks for trying. I was able to find the line that's causing it from the logs.

Apparently that kata used to have C++ and you completed it, but it doesn't anymore so the lookup is failing.

I'll close this when it's deployed.

**Comment by kazk** [comment]
Fix was deployed
