### ISSUE TITLE
New Published Beta Kata is not listed in the Home/Search page

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1062]
I published a new Beta Kata 2 hrs ago but it is still not showing in the Kata Search page. 
https://www.codewars.com/kata/nut-farm

Never seen this before - normally my new Beta Kata are available immediately (??)

**Comment by Voileexperiments** [comment]
That means CW backend server is having problems. Similar problems include not sending notification emails, and not updating new solutions.

**Comment by dinglemouse2250** [comment]
OK - it finally arrived - putting it down to general to back-end problems. Closing this,
