### ISSUE TITLE
Allow power users to approve translations

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1065]
First here are my pending translations(with basic/edge case/random assertions)

https://preview.codewars.com/kumite/59888c7d5ff84a5a4f000047
https://preview.codewars.com/kumite/59889561993576265800002b

I wonder if there could be another privilege that users with more than 6k(or 8k, or whatever you like) can approve translations. Lots of bad authors just leave their Katas alone and no one will approve the translations forever.

I know @jhoffner can approve translations too but I cannot find him. He is away from Gitter.

**Comment by DonaldKellett** [comment]
This idea (of all Power Users being able to approve translations) has been suggested multiple times but never implemented.  It's a pity - there are quite a few good Kata that I'd love to translate into PHP but the fact that the Kata author(s) are no longer active deters me from doing so.  Even then, I currently still have like 50+ published PHP translations in total that haven't been reviewed yet.

**Comment by ice1000** [comment]
> there are quite a few good Kata that I'd love to translate into PHP but the fact that the Kata author(s) are no longer active deters me from doing so

Agreed, I want to translate them into Dart too

**Comment by jhoffner** [comment]
I've been wanting to get to this, I've got a change in place on preview if you want to take a look. There is still not a page for you to view all translations that you are able to approve, however you can now approve translations found within the "Add New" page of a challenge. 

The logic is this.
 
- Are you an admin, the author or established co-author of this challenge? - You can approve
- Are you the author of the translation itself? - You cannot approve
- Are you a power user with co-author privilege, and has either the author been inactive for a month or the translation is over a week old? - You can approve

**Comment by DonaldKellett** [comment]
Thanks, I'll test it out with @ice1000 later :smile:

**Comment by ice1000** [comment]
@DonaldKellett Can you provide a list of your translations? Maybe I can help you too :smiley:

**Comment by kazk** [comment]
@jhoffner
so if the author has been inactive and the translation is old, you can approve your own?
If not, can any of you approve <https://preview.codewars.com/kumite/58b201b0bea2b00888000002?sel=58e1976e3dbe9ac0eb000042>? 

I fixed a broken Go translation 4 months ago and it hasn't been approved. The discourse has many users complaining :(
I clicked "Approve" and got this:
![image](https://user-images.githubusercontent.com/639336/29245367-f542209e-7f8c-11e7-963a-95caeca74ec1.png)

**Comment by kazk** [comment]
Never mind, I just clicked "I'M SURE". It shouldn't cause damage since it's broken anyways. How long does it usually take for the change to apply?

**Comment by kazk** [comment]
@jhoffner 
Getting little off topic, but do I need to edit the code in Kata Editor as well? I fixed a broken translation by forking it 4 months ago and I just approved that. Apparently there's another version in Kata Editor? I thought the translations from Kumite was separate from those entered in Kata Editor.
I'm trying to fix Go translation for https://www.codewars.com/kata/is-this-a-triangle

**Comment by jhoffner** [comment]
> Apparently there's another version in Kata Editor? I thought the translations from Kumite was separate from those entered in Kata Editor.

The cached languages should be namespaced but if this isn't the case we should open another bug

**Comment by jhoffner** [comment]
I deployed a new set of updates which should resolve these issues now.

**Comment by dinglemouse2250** [comment]
I am victim of this change today. 
https://www.codewars.com/kata/fixme-get-full-name/discuss#599e45c7a8b7539835000076

@jhoffner I do not like the logic. While I am an active user I wish to keep full control over approvals of my own Kata.

Me approving somebody else's translation of my Kata should NOT pass on any rights to them to approve  translations while I am still active.

**Comment by docgunthrop** [comment]
Odd that someone was able to approve the translation to @dinglemouse2250 's kata within an hour of posting, as it conflicts with the [Medium post](https://medium.com/@Codewars/latest-updates-new-languages-version-updates-smarter-markdown-and-translation-approval-additions-e1814ce5baab) from last Monday:

> They have this ability only if the kata author has been inactive for a while, or if the translation is over a week old.

So what is the cutoff time that separates `active` from `inactive` status?

**Comment by Voileexperiments** [comment]
Usually that means 7 days.

Nobody has actually *confirmed* that this part of logic for approving translation works though, so it could've been not working all the time. (Just like the "you can't approve your own translation if you're not the kata author" logic, it wasn't working in the first few days.)

**Comment by docgunthrop** [comment]
It looks like @jhoffner has mentioned:

> inactive for a month

So 30 days of inactivity is the official cutoff time?

**Comment by Voileexperiments** [comment]
I don't think that's a good measure, because some authors are active but nevertheless never approves translations to their katas.

**Comment by ice1000** [comment]
@Voileexperiments agreed
