### ISSUE TITLE
Power users able to approve own translation to *any* Kata

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1068]
I just authored a BF translation to the entrance "Multiply" Kata and was able to approve it myself - I don't think that was the intended behavior of the latest update :wink:

**Comment by Voileexperiments** [comment]
Specifically, currently in #1065:

- Are you the author of the translation itself? - You cannot approve

This part is not working :P

**Comment by ice1000** [comment]
@jhoffner seems that the translations approved by the authors are not available now.
But don't worry, Voile/me/Donald never author bad translations.

**Comment by jhoffner** [comment]
There is a display issue that I don't understand how it's even possible but somehow everyone seems to see the approve buttons. If you click them though you should get a error API response. 

One issue with logic is that if you coauthored before it was approved, you also have approval abilities. This should be fixed in preview. I hope to fix the approval display issue tomorrow.

**Comment by ice1000** [comment]
@jhoffner I can't see some approved translations. Have you made them unavailable?

**Comment by Voileexperiments** [comment]
yes, I can't see the buttons anymore either.

**Comment by ice1000** [comment]
Should this issue be closed?

**Comment by Voileexperiments** [comment]
No, because currently there is another bug:

If you've edited the kata after it's approved (using the new post-approval kata editing ability), then you seem to also lost the ability to approve translations to that kata.

**Comment by Voileexperiments** [comment]
Also, sometimes a translation is inaccessible and will give an error if visited.

e.g https://www.codewars.com/kumite/598c47ffe7c0580253000006

**Comment by jhoffner** [comment]
I've deployed some fixes and these issues should be resolved. The previously approved translations should be showing up now. Let me  know if anything got missed.

**Comment by ice1000** [comment]
Get it√

**Comment by g964** [comment]
@jhoffner : I don't understand the rationality behind this new mode of non-approving translations by their author. Are these authors that bad that they need a controler? How do possible approvers know that there are katas to be approved? It seems that authors' life is more and more difficult at CW:-)

**Comment by jhoffner** [comment]
@g964 the original logic for Kata authors should not be affected. If you authored the kata you can approve your own translations or anyone else's. 

This is the logic as it is now:
- Is the translation published? No, can't approve
- is the approving user a site admin or the author of the kata? Yes can approve
- Is the approving user not the translation author, and not the original translation author (if a fork), and the user has the coauthor privilege, and the translation is either a week old or the kata author hasn't been seen in over a month? - Yes you can approve.

Are you not able to approve your own translations?

**Comment by g964** [comment]
Did you see: #1079 ?
I write my translation, validate it, published it BUT I was not able to approve my R **own** translation. No buttons "Approve", "Reject". 
@Voile has to approve it.

**Comment by ice1000** [comment]
Can I get honor by approving my own translation to my own Kata?

**Comment by Udiknedormin** [comment]
What should I do if author of the kata I translated is absent since a long time? Can I somehow notify a moderator?

**Comment by Voileexperiments** [comment]
You can either leave a message on the discussion, or on the CW gitter channel. Usually it's fairly quick to get someone approve the translations :)

**Comment by ice1000** [comment]
@Udiknedormin In Voile's comment, 

> someone

refers to himself :joy:

**Comment by Udiknedormin** [comment]
@ice1000 I'm still rather a newbie on Codewars but I already noticed Voile is pretty active. ;)

**Comment by ice1000** [comment]
Yeah, and I am a silent user :sob:
