### ISSUE TITLE
BF Rank progress still not visible on profile page after official Beta support on main site

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1069]
As can be seen in the screenshot below (and scrolling down on my profile page), even though I just authored and approved a BF translation to the entrance "Multiply" Kata, it still doesn't show up on my rank progress as `BF: 8 kyu / 10%` (or similar):

![2017-08-12 11 19 51](https://user-images.githubusercontent.com/7777884/29241873-1187d672-7fb5-11e7-8b39-3ab55b4e30a4.png)

**Comment by ice1000** [comment]
Me too

**Comment by Voileexperiments** [comment]
It's now visible.

![image](https://user-images.githubusercontent.com/14909989/29243537-bc7594fc-7fd3-11e7-9bd8-5302286aab24.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/29243738-226dbce4-7fd9-11e7-9e74-2a0cc1dceaa7.png)

I'm always the weakest. :sob:
