### ISSUE TITLE
Warning in Rust

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1071]
Since a few days Rust kata have a problem which didn't exist before:

the compiler complains (warning) about function names, which aren't snake case in the test code.

So these kata can't be submitted with success even if the solution is a good one. 
Is it possible to have in the runner a global `#[allow(non_snake_case)]`?

**Comment by kazk** [comment]
I'll look into this. I'd like to go with the compiler flag `-A non_snake_case`.
Can you provide example code that's causing this warning? I'll use it to test.

**Comment by kazk** [comment]
@g964 see https://github.com/Codewars/codewars-runner-cli/pull/499.

I assumed you meant test function like this:
```rust
#[test] fn testAdd() { assert_eq!(add(1, 1), 2); }
```

**Comment by g964** [comment]
You can try with: <https://www.codewars.com/kata/magnet-particules-in-boxes> since I have not yet had time to correct it.

**Comment by kazk** [comment]
Ok, the function causing this warning is `fn doublesPNI(maxk: i32, maxn: i32) -> f64`, the test included in the PR should cover that.

**Comment by g964** [comment]
What is the PR?
Thanks for your help!

**Comment by kazk** [comment]
> What is the PR?

I opened the PR (Pull Request) to fix this. See https://github.com/Codewars/codewars-runner-cli/pull/499
The PR includes the test ([test/runners/rust_spec.js#L464-L475](https://github.com/kazk/codewars-runner-cli/blob/b9812267f82fd51d3f66764283fc368237023a59/test/runners/rust_spec.js#L464-L475)) ensuring `non snake case` is allowed.
```js
    it('should allow non snake case', function(done) {
      runner.run({
        language: 'rust',
        code: 'fn add(x: i32, y: i32) -> i32 { x + y }',
        fixture: `#[test] fn testAdd() { assert_eq!(add(1, 1), 2); }`,
        testFramework: 'rust'
      }, function(buffer) {
        expect(buffer.stdout).to.contain('<PASSED::>');
        expect(buffer.stderr).to.be.empty;
        done();
      });
    });
```

**Comment by g964** [comment]
I tried < https://www.codewars.com/kata/magnet-particules-in-boxes>

but still got:
```
warning: function `doublesPNI` should have a snake case name such as `doubles_pni`, #[warn(non_snake_case)] on by default
  --> src/tests.rs:34:1
```

**Comment by kazk** [comment]
Yeah, I'm just letting you know that I proposed the fix.
Basically, https://github.com/Codewars/codewars-runner-cli/pull/499 needs to be reviewed by @jhoffner and merged to the `master` branch. Then updated `rust-runner` needs to be deployed to the production server.
I can't tell you when this will be.

**Comment by g964** [comment]
OK. Thanks again.

**Comment by kazk** [comment]
@g964
> deployment should be out possibly today, no later than early next week.
> https://github.com/Codewars/codewars-runner-cli/issues/504#issuecomment-323142810
