### ISSUE TITLE
Translations approved by authors themselves are invisible

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1072]
What should we do to those translations?

**Comment by jhoffner** [comment]
Can't imagine how anything that was changed would cause this. I will look into it today. Which translations?

**Comment by ice1000** [comment]
Wait, some translations are visible now. Maybe it's because it takes too long to be visible.

If my translations are still invisible tomorrow, I'll open this issue again.

Closed first.

**Comment by ice1000** [comment]
Just out of topic, when will Kotlin/Scala/Groovy be supported by CW? I can't wait to translate hundreds of Katas into Kotlin :smile:

**Comment by Souzooka** [comment]
I've went through and pushed a lot of my translations which AFAIK had no current issues, and they're all approved but not showing up on the Katas themselves.

One such example is:
https://www.codewars.com/kumite/596cd6b5be1f2fa0ca00008b?sel=596cd6b5be1f2fa0ca00008b

**Comment by ice1000** [comment]
@Souzooka you're facing the same problem. Maybe I didn't express my idea properly, `invisible` means invisible in the Kata's language selection themselves.

**Comment by ice1000** [comment]
Simply wait for about 5\~10 hours and they will be there.
