### ISSUE TITLE
Locked kata can't be fixed - SEQUEL DEPRECATION WARNING 

### ISSUE THREAD

**Issue by sztanozs** [Codewars/codewars.com#1076]
Is it possible to unlock or delete a locked Kata?
I have encountered a few of these where, due to system/module changes, the Kata can't be finished anymore. There are cases where it can be circumvented with specific workarounds, but if the Test case has bugs due to the changed modules it can't be completed anymore.
A good example is:
https://www.codewars.com/kata/sql-basics-simple-where-and-order-by/discuss/sql

**Comment by jhoffner** [comment]
This kata should work fine, but apparently some recent updates have caused a new warning to appear. @kazk the fix here is to either strip out warnings or display them within STDOUT.
