### ISSUE TITLE
Frequent Haskell timeouts in code without loops (again)

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1077]
Issue #813 recoccurred, I added comments to that issue.

> I have this issue reoccurring. Often I have to retry 3-4 times before the outcome does not time out. In most cases the actual runtime is well below 1 second, so way below the 12 seconds timeout. I suspect it has something to do with the compilation process?

---

EDIT: Added the comment from #813

**Comment by kazk** [comment]
@nomennescio I moved this issue to https://github.com/Codewars/codewars-runner-cli/issues/503
