### ISSUE TITLE
R translation published but no "Approve..." buttons

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1079]
I translated to R : <https://preview.codewars.com/kata/56fe17fcc25bf3e19a000292> "Disguised sequences (II)". 
I published it but had no "APPROVE", "REJECT"... buttons. 
In fact the kata is not published and I see no way to re-publish it.

A "Fork" gave the same result.

**Comment by Voileexperiments** [comment]
You can't approve a translation you write yourself anymore.

Anyways, I've just approved the translation.

**Comment by g964** [comment]
> You can't approve a translation you write yourself anymore.
Oh! Why that? I didn't see anything about that! Seems weird... CW makes things to discourage people! How can we know that translations are to be approved?
Anyway, lots of thanks!

**Comment by Voileexperiments** [comment]
From here:

https://github.com/Codewars/codewars.com/issues/1068#issuecomment-322065487

also you can always put a link on gitter channel and you'll get it approved *very* quickly ;-)

**Comment by g964** [comment]
Lots of thanks for your answer. 
Nevertheless I don't understand the rationality behind this new mode of non-approving translations by their author. 
Are these authors that bad that they need a controler? 
How do possible approvers know that there are katas to be approved? I know "gitter channel" but how many CWarriors know it.
It seems that authors' life is more and more difficult at CW:-)

**Comment by jhoffner** [comment]
> You can't approve a translation you write yourself anymore.

This is not supposed to be the case for authors of the kata. I will look into the issue.

**Comment by Voileexperiments** [comment]
@jhoffner in that case it has happened somewhat often: sometimes for some reasons the approve buttons are only visible in preview site and not main site. And in very rare cases the approve buttons don't even appear in preview site.

**Comment by g964** [comment]
This morning I had no "Approve" buttons neither in preview site nor in normal site.

Moreover the rules could be clearer:
- Is the translation published? No, can't approve --> What does that mean? I thought a translation has to be published before being able to be approved, no?
- the user has the coauthor privilege --> What is a coauthor privilege?

**Comment by jhoffner** [comment]
> I thought a translation has to be published before being able to be approved, no? 

That's exactly what this logic is enforcing. If you can approve/reject, the buttons show up. If you can't, the buttons don't.

> What is the coauthor privilege?

The privilege earned at 4000 honor which allows you to contribute directly to other author's kata

> And in very rare cases the approve buttons don't even appear in preview site.

Must be do to caching issues, that might be what happened here.

**Comment by jhoffner** [comment]
The caching issue should be solved.

**Comment by g964** [comment]
I will try later, thanks!
