### ISSUE TITLE
Python version 3.6 not supported

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#1081]
I was attempting the "Geometry Basics: Distance between points in 2D"
 (https://www.codewars.com/kata/geometry-basics-distance-between-points-in-2d/train/python) kata today and ran into this error when clicking "Run Sample Tests" or "Attempt":
![not supported](https://user-images.githubusercontent.com/5090280/29476122-8c64e70c-8430-11e7-8db2-2b0f764a78ba.PNG)

For this particular kata, Python 3.6 appears to be the only version I can select, as the others are greyed out:
![version](https://user-images.githubusercontent.com/5090280/29476175-b452b276-8430-11e7-81ea-32ef7dc776f1.png)

I can reproduce the "python version 3.6 not supported" message on other Python kata that have the 3.6.0 option.

**Comment by Voileexperiments** [comment]
@kazk this can be closed with the new front end finally supporting 3.6 properly.

**Comment by kazk** [comment]
Thanks, this was actually caused by the request payload having number `3.6` as language version (I think). The new runner is little bit nicer and accepts it.
I tried to find the source of this bug (why the language version is **sometimes** given as a number), but eventually gave up.
