### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by fawads1** [Codewars/codewars.com#1083]
I am new to codewars. When ever i try to access dashboard the site crahes.
i would like to know what is the problem ?

**Comment by ice1000** [comment]
Try https://preview.codewars.com

It's all the same but much more stable

**Comment by kazk** [comment]
Are you using Windows? There're some issues reported by Windows users: #1157, #1254
If not, please open a new issue with more information. Closing this because it's old and lacks information.
