### ISSUE TITLE
Something weird with Nim tests

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1087]
@kazk:
Please could you have a look at this kata:

<http://www.codewars.com/kata/growth-of-a-population/train/nim>

Give a **false** solution. 

You will get `Time: ...ms Passed: 51 Failed: 0` even though you failed all the tests.
The only things that can show you that something was wrong is 
- `Test Results:` has a small orange rectangle to its left
- you will never had the `SUBMIT` button.

I think it could happen because of the way I test with my `proc dotest` instead of repeating and repeating `check...`. This way works in other languages.
What do you think of that?

**Comment by kazk** [comment]
Yeah, I just tried with
```nim
proc nbYear*(p0: int, percent: float64, aug: int, p: int): int = 0
```
and got what you describe.

To be honest, I don't know Nim much and I can't tell you exactly why this is happening. I'm guessing this has something to do with `check` being a `macro` unlike other languages. I'll see if I can figure this out when I have some time.

**Comment by g964** [comment]
Thanks for your time!

**Comment by Udiknedormin** [comment]
I my case some of the tests failed (it can be seen when unrolling their results) but they are still marked as passed but there is still the orange rectangle near Test results.

[`check` is indeed a macro](https://github.com/nim-lang/Nim/blob/master/lib/pure/unittest.nim#L473), it invokes `checkpoint` procedure.

**Comment by kazk** [comment]
@Udiknedormin 
We are using [unittest](https://nim-lang.org/docs/unittest.html) module unmodified with our output formatter ([codewars/formatter](https://github.com/Codewars/codewars-runner-cli/blob/3e7e83008c4cf7e39ca79178360d2b9ce5460a8e/frameworks/nim/codewars/formatter.nim)).
Tests are executed like this:

```nim
# tests.nim
import unittest, codewars/formatter
addOutputFormatter(OutputFormatter(newCodewarsOutputFormatter()))
import solution # submitted solution
include fixture # test cases
```

```shell
nim compile \
  --run \
  --define:release \
  --warnings:off \
  --hints:off \
  --verbosity:0 \
  --stackTrace:on \
  --lineTrace:on \
  --checks:on \
  --path:/runner/frameworks/nim \
  tests.nim
```

Do you see anything wrong (misuse) in the following code? This is simplified version of @g964's issue.

```nim
# `foo` is user's solution and `ref_foo` is the author's.
proc dotest(p: int, expected: int) =
  check(foo(p) == expected)

suite "Suite":
  test "Test":
    dotest(1, 2)

suite "Tests":
  for i in 1..50:
    test "Test $1".format(i):
      dotest(i, ref_foo(i))
```

**Comment by kazk** [comment]
I've been trying with local Nim, but getting more confused :(

The following outputs `[OK]` after `Check failed`, reports error and exit code is `1`.

```nim
import unittest
proc multiply*(a, b: int): int = 1 * b
proc dotest(a: int, b: int, p: int) = check(multiply(a, b) == p)
suite "multiply":
  test "multiply(2, 2)":
    dotest(2, 2, 4)
```
```
[Suite] multiply
    multiply.nim(5,59): Check failed: multiply(a, b) == p
    multiply(a, b) was 2
    p was 4
  [OK] multiply(2, 2)
Error: execution of an external program failed: '/Users/kazk/tmp/multiply '
```
```
$ echo $?
1
```

```
$ nim compile \
    --run \
    --define:release \
    --warnings:off \
    --hints:off \
    --verbosity:0 \
    --stackTrace:on \
    --lineTrace:on \
    --checks:on \
    multiply.nim
```



```
$ nim --version
Nim Compiler Version 0.17.0 (2017-05-18) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```

**Comment by kazk** [comment]
@964 I figured this out. I'll try to show you what's going on.

I haven't understood how Nim macros/templates work yet, so I inspected the generated code.
The following is how `unittest` is usually used:
```nim
suite "multiply":
  test "multiply(2, 2)":
    check(multiply(2, 2) == 4)
```
The above code is expanded to (I removed some lines for brevity)
```nim
let testSuiteName = "multiply"
try:
  for formatter in items(formatters): suiteStarted(formatter, "multiply")
  checkpoints = @[]
  var testStatusIMPL = OK
  for formatter in items(formatters): testStarted(formatter, "multiply(2, 2)")
  try:
    block:
      var :c1 = multiply(2, 2)
      if not (:c1 == 4):
        checkpoint("multiply.nim(23,27): Check failed: multiply(2, 2) == 4")
        checkpoint("multiply(2, 2) was " & $ :c1)
        testStatusIMPL = FAILED
        ensureFormattersInitialized()
        for formatter185210 in items(formatters):
          failureOccurred(formatter185210, checkpoints, nil)
        checkpoints = @[]
  except :
    checkpoint("Unhandled exception: " & getCurrentExceptionMsg())
    var stackTrace = getStackTrace(getCurrentException())
    testStatusIMPL = FAILED
    for formatter186010 in items(formatters):
      failureOccurred(formatter186010, checkpoints, stackTrace)
    checkpoints = @[]
  finally:
    if testStatusIMPL == FAILED: programResult += 1
    let testResult = TestResult(suiteName: testSuiteName,
                              testName: "multiply(2, 2)",
                              status: testStatusIMPL)
    testEnded(testResult)
    checkpoints = @[]
finally:
  suiteEnded()
```
As you can see, `testStatusIMPL = FAILED` inside the second `try` sets the status.

Now in your tests, you have something like this:
```nim
proc dotest(a: int, b: int, p: int) = check(multiply(a, b) == p)

suite "multiply":
  test "multiply(2, 2)":
    dotest(2, 2, 4)
```
This becomes
```nim
let testSuiteName = "multiply"
try:
  for formatter in items(formatters): suiteStarted(formatter, "multiply")
  checkpoints = @[]
  var testStatusIMPL = OK
  for formatter in items(formatters): testStarted(formatter, "multiply(2, 2)")
  try:
    dotest(2, 2, 4)
  except :
    checkpoint("Unhandled exception: " & getCurrentExceptionMsg())
    var stackTrace = getStackTrace(getCurrentException())
    testStatusIMPL = FAILED
    for formatter183810 in items(formatters):
      failureOccurred(formatter183810, checkpoints, stackTrace)
    checkpoints = @[]
  finally:
    if testStatusIMPL == FAILED: programResult += 1
    let testResult = TestResult(suiteName: testSuiteName,
                               testName: "multiply(2, 2)",
                               status: testStatusIMPL)
    testEnded(testResult)
    checkpoints = @[]
finally:
  suiteEnded()
```
`dotest` doesn't get expanded because it's a `proc` and `testStatusIMPL` is `OK` because `dotest` doesn't throw.

The orange rectangle is from the exit code being non-zero, indicating some error.

**Comment by kazk** [comment]
For your tests, something like the following should work as expected:
```nim
suite "nbYears random tests":
  for i in 1..50:
    let
      percent =  math.round(float64(10 + random(90))) / 100.0
      p0 = 10000 + random(15000000)
      aug = int(float64(p0) / 200.0)
      k = 5 + random(95)
      p = p0 + k * aug
      sol = nbYear_g964(p0, percent, aug, p)
    test "nbYears($1, $2, $3, $4)".format(p0, percent, aug, p):
      # dotest(p0, percent, aug, p, sol)
      check(nbYear(p0, percent, aug, p) == sol)
```

**Comment by kazk** [comment]
I'm closing this because this can be avoided by using the module properly.

Here's the macro I used above if anyone is interested.
```nim
import macros
macro expandMacros(body: expr): expr =
  template inner(x: expr): expr = x
  result = getAst(inner(body))
  echo result.toStrLit

#[
expandMacros:
  suite "multiply":
    test "multiply(2, 2)":
      check(multiply(2, 2) == 4)
]#
```

**Comment by g964** [comment]
OK. Modified. Tests are no check with tolerance...
**Thanks** again for your great work at CW.

**Comment by kazk** [comment]
@g964 

For your random tests, you shouldn't inline the answers because the failure output will include them.
![image](https://user-images.githubusercontent.com/639336/29752870-d7dbbde6-8b1a-11e7-9122-e038035f98eb.png)

Instead, do like I posted above and you'll see:
![image](https://user-images.githubusercontent.com/639336/29752962-990ffcc4-8b1c-11e7-8273-93bd9044ae40.png)

---

> Tests are no check with tolerance...

Do you mean for floating points?
I think you can do `check(abs(solution(x, y, z) - sol) <= tol)` for absolute difference for example.

> Thanks again for your great work at CW.

No problem, I also learned something new :)
Thanks for all your translations, it helps us a lot fixing issues while the language is in beta.

**Comment by richemslie** [comment]
A large number of these tests were not fixed.

To keep the intent of the what @g694 had, could rewrite the offending part of:

```
proc dotest(fct: proc, s: string, exp: string) =
    echo "s:\n: ", s
    let actual = oper(fct, s)
    echo "Exp:\n", exp
    echo "Got:\n", actual
    echo actual == exp
    assert(actual == exp)
    echo "-"
```
to

```nim
proc logTest(fct: proc, s: string, exp: string): string =
    echo "s:\n: ", s
    result = oper(fct, s)
    echo "Exp:\n", exp
    echo "Got:\n", result
    echo result == exp
    echo "-"

macro doTest(fct: proc, s: string, exp: string): untyped =
   result = quote do:
      check logTest(`fct`, `s`, `exp`) == `exp`
```
