### ISSUE TITLE
CW notification has an 8 hour delay

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1091]
It doesn't occur often, but since yesterday or so I've been receiving notifications about things that happened *8 hours ago*.

It seems that everything is delayed from evaluation - if something is 6 hours ago, and then I do something that will make me eligible to receive notification for that thing, I'll then receive the notification for it 2 hours later.

**Comment by jhoffner** [comment]
Some may still come through late until the queue catches up, but I promoted mail priority so this shouldn't be an issue for new notifications.
