### ISSUE TITLE
Some Errors With Java

### ISSUE THREAD

**Issue by strongrex2001** [Codewars/codewars.com#1092]
When Sign Up and choose Java, I tried for about 6~7 times with the same solution...
I'm sure that it is correct, but the compiler complained unknown error for many times, and I try again and again and finally succeeded...
And the server is so unstable... I always get server errors when doing katas...

**Comment by Voileexperiments** [comment]
Codewars server is in a bad shape at the moment :( Please try again later.

**Comment by Voileexperiments** [comment]
OP has already succeeded registering [a CW account](https://www.codewars.com/users/strongrex2001), so I think this issue can be closed :)

@kazk

**Comment by kazk** [comment]
Thanks @Voileexperiments
