### ISSUE TITLE
MY KATA MISSING?

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1096]
Dear @jhoffner,

Some people have no honour.

My Codewars account has been vandalised.

Some time in the last couple of days many of my Kata have been deleted.

I have no idea of extent of the damage, but AT LEAST the following Java Kata no longer exist:

* https://www.codewars.com/kata/kooka-counter/
* https://www.codewars.com/kata/spaghetti-code-number-1-easy/
* https://www.codewars.com/kata/spaghetti-code-number-2-hard/
* https://www.codewars.com/kata/would-you-believe-dot-dot-dot-talk-like-siegfried/
* https://www.codewars.com/kata/snakes-on-a-plane-number-1-easy/
* https://www.codewars.com/kata/snakes-on-a-plane-number-2-hard/
* https://www.codewars.com/kata/airport-arrivals-slash-departures-number-2/
* https://www.codewars.com/kata/swap-two-numbers/

As Java is my primary language, ALL my Kata have Java versions. I never delete them. So who did?

These deleted Kata represent a loss of countless hours of invested time and energy on my part. 

Not to mention the huge loss of the hundreds of user solutions to those Kata.

You cannot begin to imagine how unhappy and disappointed I am about this.

~~

I am an active user. How did anybody other than me delete MY Kata?

There seems to have been a recent push to grant more privileges to "power users" and they can act against the wishes of even the Kata author. IMO it has overreached without considering unintended consequences, as I recently commented here: https://github.com/Codewars/codewars.com/issues/1065

It only takes one cheating or disgruntled "power user" to damage your entire site and CW reputation.

~~

Please (Please!!) tell me there is some way you can resurrect my deleted Java Kata.

Please tell me you have records which can identify and take action against the dishonorable person who did this.

Please tell me there is some way to prevent this from reoccurring.

~~

I love the idea of Codewars. I have enjoyed authoring Kata for the community for past 18 months.

**However, without assurances this can never happen again I really see no point to continue as a Kata author anymore.**

It is simply not worth the heartache to see so many weeks of my hard work destroyed.

If I can help with any further details please contact me privately.

DM.

**Comment by Voileexperiments** [comment]
I don't think someone vandalized and deleted the language versions, because I've experimented things about deleting a language version with my own katas some time ago, and:

- Even after a language is deleted, the revisions page will still show the changes due to that language (but with `Language - :`). I nuked the Python version of my Round and Round kata at some point because it's just not satisfactory, and I can still see the first Python version's code in the revisions page.
- Similarly, the number of solves will not decrease even when after a language version is deleted (again, observed from my Round and Round kata). Currently every one of them that has JS version only is showing as many solves in total as the amount of solves in JS version. It's as if the Java version have *never existed at all*

This looks more like CW has totally lost the data for the Java versions. In any case, we **really** need @jhoffner to investigate on the issue.

**Comment by Voileexperiments** [comment]
https://www.codewars.com/kata/spaghetti-code-number-2-hard/discuss

Looking at the discourse of this kata, it seems that the JS version was there first, and the Java version was added as a translation? But then it should be visible to power users in the translations page under `closed translations`, which there aren't.

**Comment by dinglemouse2250** [comment]
@Voileexperiments - 
* I hope you are right that no "person" was involved. 
* OTHO if this is bug due to some CW error then my observations may be tip of an iceberg
* FYI - Java is my primary language. I almost **always** write the Java Kata first and then translate it myself to JavaScript.

**Comment by dinglemouse2250** [comment]
This whole issue started when somebody today translated to Java one of my Kata that I was **convinced** I had already done. Only then I searched all my other authored Kata which were not Java and got the above list

But I am beginning to doubt myself now... most of those are old so I cannot be 100% sure did I really write Java versions or not.

And @Voileexperiments says there is no evidence they existed. Ever.

Could I really be that forgetful? That would be the best possible outcome if true.

**Comment by kazk** [comment]
I helped you with
https://www.codewars.com/kata/swap-two-numbers/
and commented on
https://www.codewars.com/kata/snakes-on-a-plane-number-1-easy
https://www.codewars.com/kata/snakes-on-a-plane-number-2-hard
https://www.codewars.com/kata/spaghetti-code-number-1-easy
https://www.codewars.com/kata/airport-arrivals-slash-departures-number-2
and I'm pretty sure all of the above was JavaScript only at the time.
Also none of the discourses mentions Java either, except for the one @Voileexperiments pointed out which is requesting Java.

I don't know about these two though
https://www.codewars.com/kata/kooka-counter/
https://www.codewars.com/kata/would-you-believe-dot-dot-dot-talk-like-siegfried/

> Could I really be that forgetful?

You've authored 40+ and completed more than 1.3k, so I think it's possible that you got some mixed up.
Have you noticed anyone else's Java kata missing? Did your number of completed kata decrease?

**Comment by dinglemouse2250** [comment]
Hello @kazk and @Voileexperiments  - thank you for checking for me

I am going to close this issue because I just don't trust myself anymore!

I think a few planets aligned themselves and so I have leapt to the wrong conclusions
1. There was a cheater who was adjacent to me in the leader-board for several weeks. 
 * So I begin to be suspicious of power users.
2. Then there was problem I had with #1065 last week where CW treated me as inactive and allowed  approvers of my Kata. 
 * So I begin to not trust CW logic to protect me
3. Overnight somebody translated one of my Kata to Java which I really was sure I had already done. 
* So I think how can that happen unless somebody deleted my Java version?
4. Then I find lot of others Kata without Java. 
* Although they are all old so I can't remember 100% did I really author them in Java or not?

~~

Many apologies to everybody for jumping to wrong conclusions. 

Clearly I need to be taking the red pills instead of the blue ones.

**Comment by jhoffner** [comment]
@dinglemouse2250 FYI, the only users who can delete languages on a kata are admins and the original kata author, so you shouldn't have to worry about others deleting your work. Also the approval logic has been updated to fix an issue with inactive authors.
