### ISSUE TITLE
Deleted users are not removed from the leaderboard

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1097]
A follow-up to #1089 .

![image](https://user-images.githubusercontent.com/14909989/29761643-c20c8d46-8bfc-11e7-9c96-8d668fa58c46.png)

![image](https://user-images.githubusercontent.com/14909989/29761653-d3ff0c40-8bfc-11e7-921e-ed8cd4a9ca85.png)

[This user](https://www.codewars.com/users/del-this-account) has already deleted his account, but nevertheless the position is still remained on the leaderboard.

If we're removing cheaters from the leaderboard, maybe we should remove deleted profiles too?

**Comment by kazk** [comment]
Closing as this seems resolved.

**Comment by Voileexperiments** [comment]
@kazk The authored kata/translation leaderboard is not fixed yet: SteffenVogel recently deleted his account and he's still on this leaderboard:

![image](https://user-images.githubusercontent.com/14909989/57393252-4defd400-71f5-11e9-8b31-c6adc9ab6383.png)

**Comment by kazk** [comment]
The method to remove from leaderboard was missing authored kata/translation leaderboard. I'll deploy the fix soon.

**Comment by kazk** [comment]
The fix was just deployed and deleted/banned users from the past was removed from authored kata leaderboard.
