### ISSUE TITLE
Haskell Tab problem

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1098]
The tab problem has not been fixed. 
I republished the kata for which a guy was complaining with the pragma `{-# OPTIONS_GHC -fno-warn-tabs #-}` and it works but all passed solutions have been invalidated!

**Comment by kazk** [comment]
Thanks for reporting.
That's odd :/ I thought I had fixed this in https://github.com/Codewars/codewars-runner-cli/commit/40d3e27ed9328087459d6187f7ba2155575f0af2 with tests including tabs.

![image](https://user-images.githubusercontent.com/639336/29763390-ba86d5ba-8b87-11e7-99a4-72dea4c069f7.png)

[test/runners/haskell_spec.js#L540-L562](https://github.com/Codewars/codewars-runner-cli/blob/3e7e83008c4cf7e39ca79178360d2b9ce5460a8e/test/runners/haskell_spec.js#L540-L562)

Tests are executed with `runhaskell -- -fno-warn-tabs`

---

@jhoffner was `haskell-runner` deployed?

The above test case outputs STDERR in kumite

![image](https://user-images.githubusercontent.com/639336/29763708-1df92ad4-8b89-11e7-9fb0-6dc5e170325a.png)

**Comment by g964** [comment]
The problem was here:
<https://www.codewars.com/kata/easy-wallpaper/discuss#59a3973c76e7c4938400005f>
See @hezhenxing 's post. All previous solutions were invalidated after I published the kata with the fix, weird?

**Comment by kazk** [comment]
This should be fixed in the new runner (for GHC 7.10.3). Also, I just republished it with tabs removed and all of the previous solution is considered valid now.
