### ISSUE TITLE
R Preloaded section

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1099]
The preloaded section doesn't seem to work.

**Comment by kazk** [comment]
Do you have `source("setup.R")` in solution?

This should work.

Preloaded
```R
f <- function(a, b) { a + b }
```
Solution
```R
source("setup.R")
add <- f
```
Tests
```R
test_that("addition using preloaded works", {
  expect_equal(add(1, 1), 2)
})
```

 We need to improve the documentation.

**Comment by g964** [comment]
Thanks, I didn't know that (source("setup.R").

**Comment by kazk** [comment]
Yeah, we need to document that.
