### ISSUE TITLE
Translation to a language does not yield progress in that language

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#110]
I have been closely observing this for a while, and now I am sure that translating a kata to a certain language does not bring you any progress.

But this is not fair! Imagine a language that does not have high-level katas. To get a progress to 1 kyu in that language, one could translate high level katas to that language - but instead he gets zero for his efforts, and anyone else who will use his translated kata will get the progress! Which will result in the situation where the original translator has less progress than anyone else who solved the same pool of katas in the language.

I would also like to note that sometimes translating a simple kata is much more challenging than just solving it, because test case code can be quite complicated!

I know this because my progress in CoffeeScript is stuck at 5 kyu / 90% for a long time, despite me translating a number of 4 kyu katas into CS recently (which got approved).

**Comment by jhoffner** [comment]
This is definitely a bug and I will be looking into this soon (will try to find some time tonight).

**Comment by jhoffner** [comment]
A fix has been deployed.
