### ISSUE TITLE
Minor Content error

### ISSUE THREAD

**Issue by jrountree** [Codewars/codewars.com#1105]
This is merely a content issue on the codewars.com/wiki/Kata page.  Under the last h2 (How Are Kata Created?) within the <p> tags the content that reads "They giving this privilege once they have earned 75+ honor" should read, "They **are given** this privilege..."

Just something that stuck out to me...

**Comment by Voileexperiments** [comment]
Fixed.

@kazk You can close the issue now :)

**Comment by kazk** [comment]
Thanks :)
