### ISSUE TITLE
"View solution" in user comments removes *all* generic type parameters

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1106]
I feel like this is a duplicate and we've talked about this many times before, but...

This also removes *all* generic type parameters. e.g:

C++:
`std::vector<int>`

C#:
`List<string>`

Java:
`Stream<Integer>`

so this issue affects much more solutions than we thought.

**Comment by ice1000** [comment]
Maybe it's because the `<xxx>`s are treated as a html tag.

**Comment by kazk** [comment]
Closing as duplicate of #765.
