### ISSUE TITLE
Score didn't change when Kata kyu changed

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1109]
I just approved this kata: https://preview.codewars.com/kata/one-function-many-arguments-haskell-style

I consider it a 1kyu but I misapproved it into 2kyu (because Voile, lolisa, zuozijian3720, all of them consider this a 1kyu). And my kyu progress turns `31%` from `29%` When I change it into 1kyu and republish, it's still `31%`. Is that expected? I think a 1kyu kata will give me `5%` progress.

**Comment by ice1000** [comment]
Related: #1112

**Comment by ice1000** [comment]
:worried: Anybody here?

**Comment by kazk** [comment]
Closing old issue. This is expected and changing rank is no longer allowed.
It's not ideal, but this will require huge rewrite and won't be fixed in this version.
