### ISSUE TITLE
User profile's Honor percentile needs more significant digits

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1111]
Currently it only has 2 significant digits (0 to 99). This is not enough to resolve the top 3000+ users because of the looooooong tail of  <10 honor users.

StackOverflow and StackExchange has 4 significant digits:

![image](https://user-images.githubusercontent.com/14909989/30008312-ee3b9e76-9150-11e7-9ae6-2217dc3ef313.png)

(also, maybe we can change the leaderboard to only include users with at least some amount of honor, like `16`? This should cut down the long tail by a lot.)

**Comment by kazk** [comment]
I made this change and dropped users with less than 16 honor points from the leaderboard.
Top 15 users have `Top 0.0%` so I might make the minimum go up little bit more later.
