### ISSUE TITLE
CW's honor reward for own published katas does not update after kata rank is updated

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1112]
From my [site events](https://www.codewars.com/users/Voile/site-events):

![image](https://user-images.githubusercontent.com/14909989/30010629-afa4c7a6-9163-11e7-9900-8906d18df7a1.png)

My `Multi Line Task++` kata is ranked `3kyu`  when first approved, then changed to `2kyu` because somebody ranked `6kyu` and made the average rank assessment `3kyu`.

However, the system still counts that as a blue kata when it comes to honor rewards.

If a kata's rank is changed, *all ranks, language ranks and honor* for kata author and all solvers needs to be updated.

(Probably related: #1109)

**Comment by kazk** [comment]
This isn't ideal, but won't be fixed. Changing is rank is no longer allowed.
