### ISSUE TITLE
Translation approval buttons have no effect?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1116]
Hello,

I recently noticed that I see translation Approval and Reject buttons (hoorah!),
but when I tried to approve a translation, and confirmed that I really knew what I was doing,
it seemed like nothing happened, and the translation was not approved.

Is this a known issue, or are there some conditions which were not met? In the latter case, it would help to get an appropriate error message.

**Comment by thetamind** [comment]
Yes, it appears the buttons show even when the action is unavailable.

Duplicate of #1093

**Comment by kazk** [comment]
Closing as duplicate of #1093
