### ISSUE TITLE
Kata editor page does not check if logged in user has at least 75 honor

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1120]
So, someone with as low as 9 honor managed to publish a kata:

https://www.codewars.com/kata/find-the-pivot-element/

![image](https://user-images.githubusercontent.com/14909989/30157048-ceb81296-93f3-11e7-9494-78b8db0db3c2.png)

I investigated into this issue, and immediately found out that https://www.codewars.com/kata/new is not protected at all: users with as low as 2 honor can access this page and create/save/publish katas at will.

**Comment by jhoffner** [comment]
I've got a fix in preview and will be rolling it out to production today.
