### ISSUE TITLE
New translation window is showing the last translation you've visited

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1123]
I'm trying to translate this kata:

https://www.codewars.com/kata/54249c6bf132dcc661000495

And for some reason when I get to the new translation page, the kata page is showing another kata:

![image](https://user-images.githubusercontent.com/14909989/30192942-0c388702-947d-11e7-9dfe-caafc06275ce.png)

However, the description is showing the right kata.

**Comment by Voileexperiments** [comment]
After translating another kata apparently the Kata tab is showing the last kata that you've opened the translation window.

Caching issues?

**Comment by jhoffner** [comment]
Fix is being deployed now
