### ISSUE TITLE
Draft Translation suddenly moved under different Kata??

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1126]
While working on a Java translation for "Expression Transpiler", and being ready to publish,
I noticed that suddenly under the "Kata" tab, a completely different Kata is shown: "Longest Common Subsequence (Performance version)". Even after logging out, and relogging in, this persists.

I can access this from my draft
https://www.codewars.com/kumite/59b2d5f47babd6399b000154/edit

How to change this? I want to publish to the correct Kata

**Comment by nomennescio** [comment]
I just published, and it seems to be OK.

**Comment by nomennescio** [comment]
The same thing happens when creating a new translation.

**Comment by nomennescio** [comment]
The Kata shown is NOT another Kata I already visited, like Voile noticed. It does seem a related issue though.

**Comment by jhoffner** [comment]
yeah this was related to #1123. Fix is being deployed now.
