### ISSUE TITLE
Problem with translation approved by unknown people

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1130]
Kata: <http://www.codewars.com/kata/are-they-the-same>
Yesterday I was informed that @danmbyrd translated  my kata to Scala. I don't know Scala so I waited before approving or rejecting it.
This morning I found an issue because there are errors in the Scala tests! So somebody approved (who is this guy? How can I know who he is?) the kata but I am still active and the translation was old by only one day!
Furthermore it had to be impossible to validate the kata since there is a flaw in the tests.

It seems that these new rules for translations have a major flaw.

**Comment by danmbyrd** [comment]
Hey @g964, I've fixed the tests so that now they should be working. See my comment in codewars about an issue I was having with republishing.

Your issue with the way the translation is approved though still stands.

**Comment by g964** [comment]
Thanks for the fix! But yes: the way the translation is approved still stands.

**Comment by jhoffner** [comment]
I think I might have approved it. I was a bit over-eager to get a few extra scala translations approved to help jump start the content. Admins have the ability to approve anything.

**Comment by g964** [comment]
Shouldn't I have seen your name in the kata below "Details" in the description?

**Comment by Voileexperiments** [comment]
![image](https://user-images.githubusercontent.com/14909989/30470952-5fe1bd18-9a29-11e7-8c91-e0e41da7988f.png)

**Comment by g964** [comment]
I thought Jake was there because *he was the one who approved* the **original**  kata long long ago! His presence there doesn't mean he approved the Scala translation.
