### ISSUE TITLE
I've mysteriously lost approximately 1,000 honor

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1131]
I seem to have lost honor overnight.

As seen on [here](https://www.codewars.com/users/Souzooka/site-events) I should have around 5,400 honor, but on [my profile](https://www.codewars.com/users/Souzooka) I only have 4,434 honor.

I'm not sure what caused this.

**Comment by Souzooka** [comment]
False alarm, must some sort of caching issue, everything seems normal now.

**Comment by fenrirx22** [comment]
Had to resubmit my result like 5 times before it finally worked. Kotlin is kinda broken :(
