### ISSUE TITLE
Saving TypeScript kumite drafts manipulate the reference tags in sample tests

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1132]
When saving and publishing a TypeScript kumite, any reference tags in the sample tests such as:
`/// <reference path="/runner/typings/mocha/index.d.ts" />`
will change to:
`/// <reference path="/runner/typings/mocha/index.d.ts" ></reference>`
which the runner recognizes as invalid syntax.

Edit: Upon further poking, it appears that these lines are changed before the page refreshes after pressing "save." Perhaps it's some sort of client-side problem.

**Comment by g964** [comment]
See #361 (June 2016),  #473  and #593

**Comment by kazk** [comment]
Closing this because those comments are not used anymore and can be removed.
