### ISSUE TITLE
Can't access codewars.com

### ISSUE THREAD

**Issue by jamsna3** [Codewars/codewars.com#1135]
![image](https://user-images.githubusercontent.com/639336/32079655-64ba5aa0-ba60-11e7-82c7-456c2f9663b7.png)
http://prntscr.com/gklcvk

I'm using Chrome. For some reason, I cannot access codewars. Also, I cannot login with my github account whenever there's a chance for me to enter the sign in page. It says: GitHub account is not linked to an existing Codewars user.

![image](https://user-images.githubusercontent.com/639336/32079676-79d4c966-ba60-11e7-9e8b-631391436636.png)

http://prntscr.com/gkldge

---

Edit: inlined images and fixed links

**Comment by TaniKova** [comment]
I have same problem with access start page cpdewars.com in chrome http://clip2net.com/s/3NK5FYn and opera http://clip2net.com/s/3NK5MaE

**Comment by N-Garcia** [comment]
same problem here!

**Comment by N-Garcia** [comment]
On windows 8.1 I got the problem solved installing this UpDate:

December 12, 2017—KB4054519 (Monthly Rollup)
Applies to: Windows 8.1Windows Server 2012 R2 Standard
Improvements and fixes
This security update includes improvements and fixes that were a part of update KB4050946 (released November 27, 2017) and addresses the following issues:

Addresses issue where users of SQL Server Reporting Services may not be able to use the scrollbar in a drop-down list.

Addresses additional issues with updated time zone information.

Security updates to the Microsoft Scripting Engine and Windows Server.
For more information about the resolved security vulnerabilities, see the Security Update Guide.

Thank you!!

**Comment by reesedogg** [comment]
I'm on Windows 10 and getting this issue. Got on yesterday with the linked Github account. Today, I'm getting this:
"GitHub account is not linked to an existing Codewars user."
Tried revoking OAuth in Github for CodeWars and then re-linking. Shows as authorized Github, but CodeWars doesn't recognize

**Comment by kazk** [comment]
The crashing should be fixed now. See #1157

For account issue, please open a new issue if it's still happening.

**Comment by Bernard2030** [comment]
Have an account with code wars linked through Github yet am not able to log in to code wars.

**Comment by YamanSoner** [comment]
I have this same problem. I tried to login with github acc bu got the same message
