### ISSUE TITLE
Changing a published Kata name?

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1136]
I tried changing the name of one of my (already published) Katas to something better.

But doing this completely broke the "favourites" (star list) - gave some sort hideous looking DB error saying that the record no longer existed.

So then I was worried that it would similarly break in everybody else's star list or in any collections which it may have been added to.

So there seemed nothing I could do but change the name back to the original again... 

Is there a risk-free way to change the name of a published Kata?

**Comment by Voileexperiments** [comment]
it probably has something to do with slugs again.

**Comment by kazk** [comment]
I've changed to always use ids when generating kata URLs so changing the name shouldn't break stars/collections anymore.
