### ISSUE TITLE
List of kumites?

### ISSUE THREAD

**Issue by ZEDCWT** [Codewars/codewars.com#1137]
It says `Kumite:8 (8 Started)` on my [profile page](https://www.codewars.com/users/ZED.CWT). I'm 100 percent sure I have not started any kumites, and found nothing under the `Kumite` tab, neither the `Published` part nor the `Drafts` part.
I have also tried checking the `Show My Kumite Only?` but found nothing.
So what are the 8 started kumites on earth? Where can I view them all?
Please dont blame me if I misunderstood something O_o

**Comment by Voileexperiments** [comment]
It's probably #908 again.

**Comment by kazk** [comment]
Closing as duplicate of #908
