### ISSUE TITLE
Kotlin Kumite always timeout

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1139]
https://www.codewars.com/kumite/59be106385beb620e100002a

My translation runs fine locally: 
![image](https://user-images.githubusercontent.com/16398479/30518488-deb3fa0a-9bb1-11e7-9280-716d6be8d15e.png)

But when I try to publish it, I always get this error:

> Process was terminated. It took longer than 23000ms to complete

> Process exited prematurely with a SIGKILL signal.

Is CW down?

**Comment by JsonSong89** [comment]
same for me 。
even one line ： return 1，also this error 
The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.

**Comment by ice1000** [comment]
@JsonSong89 So it must be a bug of CW. @jhoffner

**Comment by jhoffner** [comment]
There is some sort of new issue popping up with the code execution engine. It was having some outage yesterday. I'm working on some improvements and am monitoring the servers in the meantime. Closing for now as the actual outage has been resolved.

Also, @ice1000 - dude... what is going on with all the smudges on that screen? ;)

**Comment by jhoffner** [comment]
Actually, I assumed this was related to the outage. @ice1000 and @JsonSong89 can you both please confirm that it works now?

**Comment by ice1000** [comment]
Still.. Same on preview site. :worried:

**Comment by kazk** [comment]
@ice1000 is this happening to every Kotlin kata? Or this specific translation?

**Comment by JsonSong89** [comment]
@kazk 
 [http://www.codewars.com/kata/two-oldest-ages-1/train/kotlin](http://www.codewars.com/kata/two-oldest-ages-1/train/kotlin)
I keep the default fun body.
![image](https://user-images.githubusercontent.com/4394916/30724604-874ed366-9f71-11e7-9766-e3c9e98aa879.png)

**Comment by JsonSong89** [comment]
Is this problem relevant to area?
the uper and I both in china,and I guess he has used some vpn

**Comment by ice1000** [comment]
@kazk Only one. I've successfully translated some other Katas (like https://www.codewars.com/kata/base91-encoding-and-decoding), and it works fine.

**Comment by ice1000** [comment]
@JsonSong89 No, I'm inside the wall. :trollface:

**Comment by kazk** [comment]
@JsonSong89
Does it *always* timeout? JVM languages have performance issues in general and timeouts happen occasionally.

@ice1000, can you run the translation? I mean does it only timeout when trying publish, or does it also timeout when you simply run?

> My translation runs fine locally

Your local machine is much more powerful for sure, so comparing the time it takes doesn't make much sense. For example, I think the performance will be poor if the code requires decent amount of memory.
If the issue only happens when trying to publish, then root of the issue might be somewhere else.

**Comment by ice1000** [comment]
@kazk it timeout  every time when I try to run it.

> Your local machine is much more powerful for sure

It's not an algorithm Kata for sure, it's a type system Kata, and it takes only 183ms to run.

**Comment by ice1000** [comment]
I've realized what's wrong!

It's actually a compilation error!

**Comment by ice1000** [comment]
Ok, I've fixed it (it's because something's lost when I was pasting my code.

Now I'm sure it works well locally (Kotlin 1.1.4-3), but there's still

> Process exited prematurely with a SIGKILL signal.

**Comment by kazk** [comment]
> It's not an algorithm Kata for sure, it's a type system Kata, and it takes only 183ms to run.

How long does it take to compile from clean state?

On Codewars, even "multiply" kata can take `15429ms` :| This includes the time it took to compile. The execution time is shown in the test result like `Completed in 253ms`. For JVM languages, most of the time is spent to compile.

As far as I know, Kotlin/Scala compilers are not fast, especially for the first time. Subsequent calls are much faster, but Codewars can't take advantage of that with current setup. Also, the amount of resources (CPU, memory) allowed is low.

I understand this is frustrating, but please understand that the language support is still in beta. Feedbacks are always appreciated.

**Comment by ice1000** [comment]
:sob:

**Comment by ice1000** [comment]
But mention, compilation errors are treated as `SIGKILL`. This must be a bug.

**Comment by kazk** [comment]
Compilation errors should show something like this if it happened within the allowed time.
![image](https://user-images.githubusercontent.com/639336/30784673-6e72f34c-a10e-11e7-9c4e-2d5c9bd50622.png)

**Comment by fenrirx22** [comment]
Had to resubmit my result like 5 times before it finally worked. Kotlin is kinda broken :(

**Comment by ice1000** [comment]
:sob:

**Comment by ProwlElement** [comment]
Process exited prematurely with a SIGKILL signal

I am having this same issue as above:
<img width="1422" alt="screen shot 2017-10-20 at 12 00 00" src="https://user-images.githubusercontent.com/9253549/31818031-4affd51c-b58e-11e7-831b-f0a84fae022c.png">

The code is so small surely it is not that causing the issue. Unless I have done something wrong?
Completing using JavaScript.. http://www.codewars.com/kata/bouncing-balls

If anyone can help me understand this that would be great :)
Cheers
