### ISSUE TITLE
Every time "Server Execution Error"

### ISSUE THREAD

**Issue by Illicitus** [Codewars/codewars.com#1143]
Hello, sorry but I have all time next error:
 
Time: 0ms
Server Execution Error:
The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.

Another kata - the same...
And after 30 - 40 minutes system logout me. Why?
My profile name is 'Illicitus'.

**Comment by pprunesquallor** [comment]
Same with me. It's their problem obviously... Too bad, I was just in the mood for some katas. :(

**Comment by Illicitus** [comment]
http://status.codewars.com - 'All Systems Operational - ok'.

**Comment by a1ip** [comment]
The same problem for me: always `Server Execution Error`

**Comment by TheNerdyFeline** [comment]
I am having the same problem, I have tried running both sample tests and full tests and they both give me the
Server Execution Error:
The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
I have also tried refreshing the page, same thing.

**Comment by oskarwaglund** [comment]
I'm getting the same problem. :(

**Comment by carsten-luckmann** [comment]
Same problem occurring again.

**Comment by saran2020** [comment]
Till the time I was trying to solve the kata. Now after I have found the solution Sever error. Really disappointed.

To retain me as your user, move me from 6kyu to 5 😋

**Comment by carsten-luckmann** [comment]
To make the severity clear: I was able to run the sample tests and have been trying to run the full test suite for about half an hour now. This is not fun if it takes longer to submit the kata than to write it.

**Comment by hossfahad** [comment]
I have a collection worth of katas at this point that I could not execute because of server timeouts. Frustrating!

**Comment by beninato8** [comment]
Same issue for me as well

**Comment by wiyadawii** [comment]
I've got the same issue on my profile. Below are error messages that display on my profile.

'Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.@

'language cannot be blank (actual = nil'

**Comment by anter69** [comment]
It's happening today to me too: trying to solve multiple katas in python, using different browsers (Chrome,, IE, FF), connecting from Belgium, Europe. I also tried connecting to the direct site, but didn't help.

**Comment by alex2413** [comment]
From Busan, South Korea: any language, any kata isn't working. stuck on 'Assigning a server...' then timeout.

**Comment by omiceron** [comment]
Same problem. There were some lags today and nothing works by now.

**Comment by TommyJerryMairo** [comment]
Same problem for me with only C++ codes.
In other words, Java code works well.

**Comment by Lishkon** [comment]
No success with Java as well.

**Comment by luuizpaulo** [comment]
The same with Javascript and Python

**Comment by wdkaye** [comment]
Has been occurring constantly since about Nov 22 2017, 10 PM (PST).  Still a problem 12 hours later.  (C++ user here)

**Comment by mirisbowring** [comment]
Any solution yet?

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.
