### ISSUE TITLE
Solidity Code Examples are not displayed

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1144]
I was just starting to write a Solidity translation to [Roman Numerals Encoder](https://www.codewars.com/kata/roman-numerals-encoder/) and noticed that when I added a suitable Solidity code example in the Kata Description, it did not show up:

![2017-09-20 1 00 45](https://user-images.githubusercontent.com/7777884/30627581-bc38e9be-9e03-11e7-992a-442457fb135f.png)

![2017-09-20 1 01 11](https://user-images.githubusercontent.com/7777884/30627586-cb4ef1aa-9e03-11e7-9ded-53a3fdcee9aa.png)

**Comment by kazk** [comment]
Fixed
