### ISSUE TITLE
[Suggestion] Increase Solidity Timeout Limit

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1145]
Currently (I believe that) the Solidity timeout limit is `12000ms` which isn't quite enough because even just compiling the code takes around `6000ms` and Solidity code execution is quite slow.  This makes me reluctant to add too many random tests to a particular Solidity Kata in fear that it would time out easily for non-Red users (and sometimes even Red users).  I would suggest increasing the timeout limit by at least `6000ms`.

**Comment by Dan-Nolan** [comment]
It should be [20 seconds](https://github.com/kazk/codewars-runner-cli/blob/5d2e3c4079116a7cab5e5fa73399168e5de7b660/lib/config.js#L22). This is a good point. As it is, the [https://www.codewars.com/kata/rock-paper-scissors-smart-contract/](Rock, Paper Scissors Smart Contract) solution runs at about 11-12 seconds on Codewars Red. I could see more complex code taking longer.

**Comment by DonaldKellett** [comment]
Cool :+1:  If the timeout limit is already 20 seconds then I think this issue can be safely closed, cheers :smile:

**Comment by Dan-Nolan** [comment]
Sounds good, I just ran a test to see and it does time out after 20 seconds. We'll see if we start to reach this number and then we can adjust it. We might have to write up some Solidity testing best practices after experimenting around a bit!
