### ISSUE TITLE
RankUp suggests kata from lower levels

### ISSUE THREAD

**Issue by carsten-luckmann** [Codewars/codewars.com#1148]
Since today, "RankUp" suggests katas from 8kyu and 7kyu although I am 6kyu, so "RankUp" is supposed to suggest only katas of at least 6kyu.

Tried to log out and log in again but still get suggestions for 8kyu and 7kyu katas.

Worked flawlessly until yesterday.

Username is mazalin

**Comment by carsten-luckmann** [comment]
Just ranked up to 5kyu and still "RankUp" suggests not only 5kyu and higher but also 6kyu down to 8kyu.

**Comment by kazk** [comment]
I don't know exactly how the suggestion work, but completing lower rank kata still increases your score, and let you to rank up. If you want to filter the kata by rank, I'd suggest using the search.

Your profile says you only trained on Elixir so I'm assuming you're only doing Elixir at the moment. There's only 27 kata in Elixir that's 5 kyu and up, compared to 168 of 6 kyu and below. Maybe that's part of the reason you see lower ranks suggested.

![image](https://user-images.githubusercontent.com/639336/30723130-1eca91d6-9eea-11e7-92e6-da02b81c941b.png)

**Comment by carsten-luckmann** [comment]
The documentation states that only katas of your level or a higher level get you points to level up. This also coincides with the behaviour I had observed before. When I was 7kyu, I did not see 8kyu katas anymore, and when I was 6kyu, I did not see 7kyu katas anymore.

This behaviour had changed somewhen when I was 6kyu from one day to the next. Maybe you are right, and it is related to the number of available katas, but since it was a change in behaviour which does not match what I would expect from the documetation, I wanted to report it.

**Comment by kazk** [comment]
> The documentation states that only katas of your level or a higher level get you points to level up.

Which documentation? We need to fix it because this is not true.
The higher ranks are simply worth more points, your rank is determined by the total score you've earned by completing kata and the order of completion doesn't matter.

> when I was 6kyu, I did not see 7kyu katas anymore.

Can you clarify? I might have misunderstood you because this contradicts with the issue you originally reported.

**Comment by carsten-luckmann** [comment]
The contradiction you see is resolved by different behaviour on different days. Until Wednesday, I was only suggested katas at or above my rank (and I saw quite a lot of them). Starting on Thursday, I was suggested a lot of katas below my rank. At that point I created this ticket.

The documentation is on http://www.codewars.com/docs
> Earning Ranks
> You can advance through the ranks by completing kata at or above your rank

**Comment by carsten-luckmann** [comment]
Btw: Today the problem seems to be gone. Currently, I am only suggested 4kyu and 5kyu katas.

I will close the ticket for now.

**Comment by kazk** [comment]
Thanks for clarifying.

That documentation has been outdated for years and shouldn't be accessible from the sidebar.
The newer documentation is <https://github.com/codewars/codewars.com/wiki> which is maintained by the community.

---

@jhoffner

`/docs` should redirect to the wiki and `/about` contains the same lines ("completing kata at or above your rank").
