### ISSUE TITLE
Kata says "5 issues reported" and cannot be approved despite having no unresolved issues

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1149]
I was trying to approve this kata:

https://www.codewars.com/kata/testing-1-2-3/discuss/javascript

But despite having no active issues, it still says "5 issues reported" in the train and search page. It also can't be approved as it says "Issues waiting to be resolved".

**Comment by Souzooka** [comment]
Looking at the inspector, it seems like the comments page is only loading a certain amount of comments, and then selecting "issues", etc. filters out _these_ comments.

It's possible that there are actually 5 open issue comments, but that it is impossible to view the comments because of this.
