### ISSUE TITLE
Automatic translation from JavaScript to CoffeeScript and vice-versa

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#115]
Whenever I write a JS kata, I usually drop the JS code in http://js2.coffee/, clean some left-over variables and call it a day. Similar for CoffeeScript. 

Given that CoffeeScript is essentially JavaScript couldn't you simply automate the translation process for those languages? It feels a little bit strange to translate a kata to CoffeeScript, since that's basically free honor.

**Comment by MMMAAANNN** [comment]
I support this. Earned lots of honour this way though :)

However, sometimes there can be tricks that will pass in JS but won't pass in CS. With some experience with CS translations, I actually do some manual improvements when I translate, not just blindly copy-paste.

**Comment by MMMAAANNN** [comment]
Also, when Python 3 comes online, it can also be used in a similar automated way (provided there exists some way to translate between Python versions automatically).

**Comment by bkaes** [comment]
> I support this. Earned lots of honour this way though :)

Yeah, I've seen your two "CoffeeScript translation kumited" comments and thought "Wait… CS is almost always trivial to translate, why don't we let a PC do that?". 

> However, sometimes there can be tricks that will pass in JS but won't pass in CS. With some experience with CS translations, I actually do some manual improvements when I translate, not just blindly copy-paste.

The automatic CS translation of my recent kata was horrible. I had to improve almost everything. But given that `js2coffee` has a JavaScript implementation and therefore could be used in the kata editor, I think it might be a valid way to add some semi-automatic translation.

> Also, when Python 3 comes online, it can also be used in a similar automated way (provided there exists some way to translate between Python versions automatically).

Python has [a built-in library](https://docs.python.org/2/library/2to3.html) for Python2 to 3. But that's a rather big change and something different. Was there some word that Python3 would be used along Python2? Because many katas aren't Python3 compliant, IIRC.

**Comment by MMMAAANNN** [comment]
Yes, somewhere in CW docs I have seen a statement that Python 3 will be added as a separate language, just like CS is treated as separate language from JS.

**Comment by jhoffner** [comment]
Yeah we thought about adding the support to automatically translation js to coffee. I had the same concerns (that js2coffee doesnt always do a good job) but also to be honest, barely anyone uses Coffee on the site so it never was a high priority for us. We hope to introduce Typescript soon (which will have similar similarity issues) and with that gaining support as well as ES6 being official and Babel on the uprising, it feels like Coffeescript is on its way out from general usage anyway. 

I also wonder how well js2coffee can translate ES6 code to coffee, I'm assuming it can't. We are about to upgrade the JS engine to supporting ES6. Actually it is already upgraded I just need to finish testing and deploying it and we are under the gun on another release. So the fact that we soon won't know if code is ES6 or ES5 also causes additional headaches with doing auto translations.

**Comment by bkaes** [comment]
> I also wonder how well js2coffee can translate ES6 code to coffee, I'm assuming it can't. We are about to upgrade the JS engine to supporting ES6. Actually it is already upgraded I just need to finish testing and deploying it and we are under the gun on another release. So the fact that we soon won't know if code is ES6 or ES5 also causes additional headaches with doing auto translations. 

Slightly unrelated, how will a compiler/library update communicated and/or tested? For example, GHC has seen the AMP and BBP, which probably invalidates some old code (both in tests and solutions).

**Comment by bkaestner** [comment]
> I also wonder how well js2coffee can translate ES6 code to coffee, I'm assuming it can't. 

Well, why don't you simply use `babel` and then _afterwards_ `js2coffee`? That should give more or less valid results.

That being said, I've encountered another ["lazy" translation](http://www.codewars.com/kumite/55e50ab56f037f6ed100001a?sel=55e50ab56f037f6ed100001a) today :/.

**Comment by jhoffner** [comment]
Closing since Coffee is so low priority we are considering taking it out completely.
