### ISSUE TITLE
Unpublishing a Kata - where did the button go?

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1151]
I recently had a need to temporarily take to my published Kata "offline" so I could do some surgery on it without worrying about users working with the pre-fixed old version.

But there was no "Un-Publish" button in the editor!

Where did it go? I am sure there used to be such a button and it was useful.

**Comment by Voileexperiments** [comment]
Your kata is *already approved from beta* so you can't unpublish it.

**Comment by dinglemouse2250** [comment]
> so you can't unpublish it. 

Yes. But why not?

So I am allowed to delete entire contents and re-publish yet I am not allowed to temporally un-publish / re-publish ?? Seems strange to me.

**Comment by kazk** [comment]
Approved kata cannot be unpublished or deleted. You can unpublish if it's still in beta, but you can't delete even if it's in beta if others have solved it.
