### ISSUE TITLE
Request Error/Network Error : but NOT for Sample Tests!

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1155]
For https://www.codewars.com/kata/brainfuck-translator/train/cpp

I can run sample tests run fine, but full tests give error:
"Request Error:
Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request."

After that, I can still run sample tests if I reload the page.
This has been 100% reproducable for the past half hour.

**Comment by nomennescio** [comment]
Note: https://codewars.statuspage.io/ gives 100% operational.

**Comment by nomennescio** [comment]
Might be (indirectly) related to #1143

**Comment by chris-t-w** [comment]
I'm seeing the same thing on the same Kata.

**Comment by nomennescio** [comment]
After one week, still consistently the error can be reproduced

**Comment by nomennescio** [comment]
When removing ALL printing to stdout, I CAN 'Attempt' the code (it times out, but it does run!)
So either this is a strange coincidence, otherwise printing to stdout causes this behaviour.
In the latter case I would also say this is a bug.

**Comment by nomennescio** [comment]
I think I encountered a similar instantation in another Kata. In one run of sample tests I did pass,
but when adapting code and accidentally introducing a non-terminating loop, thereby going beyond the timeout of 12s, I got the same warning:

"Request Error:
Network Error

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request."

Therefore, it seems that this is reported if a previous run was succesful, but the current run did timeout?
In that case the reporting is incorrect, and should report it as a timeout.

**Comment by chris-t-w** [comment]
I had a line in my main function that looked like this:

`std::cout << "source: " << source_code << std::endl;`

With this line present, I was receiving the following error:

> This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

I had a hunch that the input was so large that it was causing issues trying to output it, so I printed just the length of the input instead.

After doing so, I no longer see the error and I can see the results of running the tests. In the second test, it seems that the input string is source: 2222,000 characters long. I suspect trying to print this string resulted in the error.

**Comment by patricksile** [comment]
Hey I have been going through the same problem for 2 weeks now and I can tell you it is pretty bad for me, and I don't know what can be done about it @jhoffner please do something. Thanks....

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.
