### ISSUE TITLE
Error(500) pops up when I try accessing a translation for Kata

### ISSUE THREAD

**Issue by kenkamau** [Codewars/codewars.com#1156]
Two different Kata translation are inaccessible because I get the error message: 
`Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.
If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.
undefined method `name' for nil:NilClass`

I have tried a different browser, still getting this message. The two translations are: 
`"Last digit symmetry" C# Translation`
`"Longest vowel chain" C# Translation`

**Comment by AJFarmar** [comment]
I'm also getting this error. This seems to be a C# translation thing, as the translation I'm trying to access is also in C#. This also breaks the 'make a new translation' link.

The translation is the ["Pull your words together, man!" C# translation](https://www.codewars.com/kata/pull-your-words-together-man/translations).

**Comment by g964** [comment]
Same here, see #1090 (since August 2017) #851 (since March 2017) never fixed.

**Comment by kenkamau** [comment]
Thanks guys. I hope they resolve this quick.

**Comment by kazk** [comment]
Fixed
