### ISSUE TITLE
When forking solution, after save, but before publish, Kata is lost?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1159]
When creating a fork of a Kata solution, and saving it (but not yet published), I cannot seem to retrieve the edited fork after I have closed the tab. How to retrieve?

**Comment by dinglemouse2250** [comment]
I am always careful when translating a Kata to be sure to publish it in the same sitting... because I think I once had same scenario you described where I *saved* several hours translating work (but did not yet *publish* it), and then could not find my way back to it...

**Comment by nomennescio** [comment]
Actually, for these saved translation can be retrieved from the 'Drafts' section of the translations on your Profile page. I'm looking for something similar to Kata forks.

**Comment by nomennescio** [comment]
Found the answer; under your solution, select 'fork', from there a special 'Draft' section show the draft versions.
