### ISSUE TITLE
Typo in notification for 3000 honour achievement

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#116]
'hae' must be 'have'

**Comment by the-zebulan** [comment]
I think this issue is resolved now.

I raised this same issue recently (#389 , sorry for not checking first!) and it was fixed by @jhoffner .

I was just about to raise another typo issue and was checking for duplicates first and came across this issue.

**Comment by kazk** [comment]
This has been fixed, see #389.
