### ISSUE TITLE
Can`t connect to the site

### ISSUE THREAD

**Issue by Serveladik** [Codewars/codewars.com#1161]
Hi!
I just try to connect to the website but unlikely there is an error
"Cant open the page" and i cant even create new account
What to do?
ALready switch browser

**Comment by IgorKurkov** [comment]
Same problem on chrome 61 last version. How to solve? Migrate to ff but its not funny

**Comment by Serveladik** [comment]
Что такое фф?

8 окт. 2017 г. 22:27 пользователь "IgorKurkov" <notifications@github.com>
написал:

**Comment by IgorKurkov** [comment]
Firefox)

**Comment by Serveladik** [comment]
В пизду, я к хрому привык, че я ради сайта должен менять браузер, да и
кстати вроде фесит криво отображается, вроде как
Может аддон кривой

8 окт. 2017 г. 22:35 пользователь "IgorKurkov" <notifications@github.com>
написал:

**Comment by randomd00d** [comment]
Site crashes after loading in both Chrome and FireFox (Windows 7). Tested on multiple Windows 7 computers (same browsers), and always the same error - the site loads very, *very* briefly, and then the tab crashes.

In Safari for Windows (Win 7), the site loads without any problems.

In VirtualBox (Windows 10, Chrome, FireFox), the site loads as well.

**Comment by kazk** [comment]
This should be fixed now. See #1157

**Comment by Serveladik** [comment]
R u retarded?
Look at date
U wrote after half year

пн, 28 янв. 2019 г., 10:09 kazk notifications@github.com:
