### ISSUE TITLE
Show which language you completed specific kata with.

### ISSUE THREAD

**Issue by ColtHands** [codewars/codewars.com#1162]
Something like this, would be helpfull to know which language you used to complete kata.
![Katas](https://i.imgur.com/0pYXCxK.png)

**Comment by anter69** [comment]
There is already such a feature implemented on the `/users/username/completed` page, so it shouldn't be hard to add it to the `/kata` page too:

![image](https://user-images.githubusercontent.com/12795864/31379024-68543bc8-adad-11e7-9c30-89b88f7440d0.png)

**Comment by Haksell** [comment]
Is there any news on that?

It seems like a small change but that would instantly make codewars much more useful for learning new languages. Right now there is no simple way of solving easy puzzles (which I have solved in other languages) when I want to train something new.

I have seen a lot of similar suggestions with no concrete answer.

**Comment by hobovsky** [comment]
There's no such thing in CodeWars directly, but you could give a try to #1758

**Comment by Haksell** [comment]
@hobovsky I did! It kind of works but doesn't seem to update when I solve new ones. Is it linked to the 12 hours schedule of "Next stats refresh" ?

**Comment by hobovsky** [comment]
No, for the time being, the script updates the list of solved kata only when you enter "Solutions" tab in your profile. Better mechanism is under construction, just did not get to finishing it :)

**Comment by Haksell** [comment]
@hobovsky Works great! Skipped that part of the README apparently. Maybe you should put it at the top.
