### ISSUE TITLE
Rank progress only has 2 significant figures if it is >90%

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1164]
Related to #1111.

Ranking progress gets 3 significant digits (up to `0.1%`) only if the rank progress is 90% or above. Otherwise only 2 significant digits (up to `1%`) are shown.

IMO either it should return 2 significant digits at all times, or 3. There is nothing making the rank progress gain *less* precision when it is closer to the next rank.

**Comment by kazk** [comment]
Fixed
