### ISSUE TITLE
Remove non-positive votes from vindictive users or trolls who don't complete a kata?

### ISSUE THREAD

**Issue by docgunthrop** [Codewars/codewars.com#1165]
Last night someone voted "Somewhat Satisfied" on all my published katas (only 3 at the moment) without completing a single one of them. The culprit appears to be either a troll or a vindictive user.

I put a good deal of effort into making my katas polished and high-quality in all aspects (I've even gone so far as actively seeking feedback in the CW gitter channel; fellow power-user @Voileexperiments can attest to this). So far, all of the ones that have had completions (ie. users have solved and ranked) have gotten 100% satisfaction ratings.

At the moment, my katas are still in beta and I'm hoping to get them approved as I'm currently working on publishing more katas. The problem is that if some troll is doing some drive-by voting to stymie approval of my katas, then I'll end up with a bunch of katas that remain stuck in beta.

So what can be done about this kind of situation?

**Comment by Voileexperiments** [comment]
I've put my long reply to #1166.

**Comment by docgunthrop** [comment]
@jhoffner has resolved the issue (refer to #1174 )
