### ISSUE TITLE
[Android] jumping cursor when typing in code area on all android browsers 

### ISSUE THREAD

**Issue by IgorKurkov** [Codewars/codewars.com#1167]
Cursor automatically make "enter" action after each typing of symbol. 
So, how to figure out this?

**Comment by ice1000** [comment]
Write your codes in the search bar and copy+paste

:trollface:

**Comment by IgorKurkov** [comment]
Good joke. But not solved this bug. It may cause because js libs make this effect in chrome for android.

**Comment by kazk** [comment]
CodeMirror was updated to the latest 5.24.4.
If this still happens, please try https://codemirror.net/. Then file an issue on upstream if it's broken there as well because there's nothing we can do in that case.

Please let me know if it works there and it's still broken on Codewars.
