### ISSUE TITLE
Counterintuitive behaviour in case of a network error

### ISSUE THREAD

**Issue by SpaceBison** [Codewars/codewars.com#1169]
When submitting a solution (or running tests), if a network error is encountered, the error message ("This error was caused due to an issue...") is being displayed below the output of the previous execution. Because of this, the network problem is not apparent, at least not until the user scrolls to the bottom. I think that the message should be displayed at the top of the output frame, or even better, in a dialog box.

Also, when a network error occurs, the "Run sample tests" and "Submit" buttons remain inactive and the only option is to retry the previous request via a hyperlink in the error message.

**Comment by kazk** [comment]
Sorry for the lack of response. Please let me know the details if you're still experiencing this.
