### ISSUE TITLE
Problem with the languages for kata displayed in the newsletter

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#117]
As by subject, note that Ruby and Python are not available languages atm:

![image](https://cloud.githubusercontent.com/assets/4815731/8505293/74ce0a72-21e2-11e5-8dde-c9a9fae8d074.png)

There are actually translations of this kata in both Ruby and Python, but they are not approved, so my guess is that your system picks up even not approved translations when creating the newsletter.

**Comment by jhoffner** [comment]
Thanks for letting us know. These emails are manually curated so it was just a human error.
