### ISSUE TITLE
Codewars Red streak/most consecutive days stats acting up again

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#1170]
Issue #945 is happening for me again ... my profile says
![image](https://user-images.githubusercontent.com/2389786/31366805-f207c00a-ad27-11e7-8c9f-519d49d4aa50.png)
even though I had done katas on October 4 in the early afternoon (California time) and evening (and on subsequent days as well). It seems to me that you're on UTC and therefore during daylight savings time here any katas I do after 5pm will be counted for what is for me the following day, but the early-afternoon one should have been counted as October 4.

**Comment by tachyonlabs** [comment]
Yeah, this is still going on ... if I look at my profile https://www.codewars.com/users/tachyonlabs not only did the number of days stop getting updated as above, but there is not the "Current Streak" label and value that there would be if I had not continued to do daily katas, as shown on for example https://www.codewars.com/users/donaldsebleung that I was just looking at.

I'm proud of my Codewars streak and my Duolingo streak, what can I say? :-)

**Comment by tachyonlabs** [comment]
This continued on and on as above, with "Most Number of days" never increasing past 407, but no "Current Streak" value ever appearing beneath it, either. But then within the last month or so, I finally started missing some days, and now I see that I have "Current Streak: 9" below the "Ended On", instead of just the supposed Ended On.

**Comment by tachyonlabs** [comment]
Yay, this seems to have finally been fixed -- my Most Number of days has moved to 584 instead of being stuck on 407, and I finally have a Current Streak label and value displayed below the Ended On.

**Comment by kazk** [comment]
Yeah, I've fixed some bug around there as well. Glad it's fixed for you.
