### ISSUE TITLE
Server Execution Error every time

### ISSUE THREAD

**Issue by PhilDykes** [Codewars/codewars.com#1171]
Today I have received a Server Execution Error every time I run a sample test,

"The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again."

I have tried multiple Katas and the result is no different.

**Comment by alex2413** [comment]
seems lots of people are having same issues rn, including me. Not working for any languages for me. :(

**Comment by BlueFlakes** [comment]
The same to me : p

**Comment by adam-tokarski** [comment]
The same.

**Comment by guilleasz** [comment]
Same here + 5 more friends

**Comment by aidnolan** [comment]
Same here too

**Comment by anter69** [comment]
same here (Belgium, Europe)

see also #1171

**Comment by SimonRi** [comment]
Me too Sweden :(

**Comment by rasmusri** [comment]
I have the problem too. It worked yesterday, though

**Comment by bartrietveld** [comment]
Same here unfortunately :(

**Comment by dianalai** [comment]
Same here :(

**Comment by Dubascudes** [comment]
same here. They claim its working on the status page, but clearly it isn't.

**Comment by jhoffner** [comment]
Yep. Happens every time I go on vacation. Like magic. Seriously - this only happens when I'm not around, smooth sailings otherwise. 

Anyway, it should be fixed now.
