### ISSUE TITLE
Server execution error: The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.

### ISSUE THREAD

**Issue by psychameleon** [Codewars/codewars.com#1173]
Trying to execute "which gas station should I pick" and i keep getting: The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
I use Firefox for developers, i will try another browser as well.
EDIT: same timeout error in Chrome as well.
In firefox developer tab i see :

10:22:46.342 The Ably CDN URL you are using is deprecated because it does not contain a version number. Please see https://support.ably.io/solution/articles/3000063698
ably.min.js:26:9
10:22:51.794 Loading failed for the <script> with source “https://data.gosquared.com/pv?cs=UTF-8&cd=24&la=en-US&sw=1920&sh=1080&dp=1&pu=https%3A%2F%2Fwww.codewars.com%2Fkata%2Fwhich-gas-station-should-i-pick%2Ftrain%2Fpython&pt=Train%3A%20Which%20Gas%20Station%20should%20I%20pick%3F%20%7C%20Codewars&ri=0&ru=-&re=1&vi=6&pv=9&lv=1507792922&vw=1920&vh=1018&dw=1920&dh=1018&st=0&sl=0&tz=-180&rc=1&cb=1&a=GSN-087086-V&id=1d9be3a61d450b20d07a453af8c36751&tv=6.3.1829&rt=1”.

Thanks!

**Comment by g964** [comment]
Servers executing code are down.

**Comment by anter69** [comment]
Confirmed, I have the same issue (as earlier this week)...

**Comment by quicker123456789** [comment]
Two days ago was the same thing with servers. Maybe because the academic year has started at schools...

**Comment by SimonThordal** [comment]
Having the same issue here

**Comment by madmed88** [comment]
Same thing here two days ago and today.

**Comment by psychameleon** [comment]
Is it possible to share processing power? I have a server at home that's powered 24/7, which is idle most of the time running OpenSuse. I would gladly share it if it helps balance the load!

**Comment by rasmusri** [comment]
I have the problem too. It's the same problem as the day before yesterday.

**Comment by ice1000** [comment]
CW is down.

tmp solution: use preview.codewars.com

Works for me
