### ISSUE TITLE
Contributors cannot resolve kata issues

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#118]
Take a look at this kata:
http://www.codewars.com/kata/nth-root-of-a-number/discuss/

It currently has several "unresolved" issues. Except they are already resolved 3 weeks ago. But the warriors who left their comments about issues have not marked them as resolved, and author is probably inactive.

As a contributor, I can edit the kata and improve it (which I did), but I cannot mark issues "resolved"! It looks like kata will remain unapprovable even though no actual issues exist for 3 weeks until Jake personally resolves those rogue issues.

Wouldn't it be more appropriate to let any contributor resolve issues in katas, not just kata's author?

**Comment by GiacomoSorbi** [comment]
I second that idea.

**Comment by bkaes** [comment]
Probably related: #14

**Comment by javatlacati** [comment]
https://codewars.ideas.aha.io/ideas/CW-I-94

**Comment by jhoffner** [comment]
Is this
