### ISSUE TITLE
Site doesnt work in Google chrome

### ISSUE THREAD

**Issue by Serveladik** [Codewars/codewars.com#1181]
The site not opening in google chrome
What to do?>>

**Comment by kazk** [comment]
Closing because there's not enough information. Maybe duplicate of #1157.

**Comment by kabantejay** [comment]
the same problem i have - its just not opens... it shows on 0.5 sec some page elements and then google chrome just show error grey screen - Page Crash

**Comment by kabantejay** [comment]
i am win 7

**Comment by mouchin777** [comment]
same stuff over there

**Comment by kabantejay** [comment]
are you kiddin me?? you answered after several month!!!
and it STILL dont work!

https://pastenow.ru/f047a6a80d0d32d89945579103609ff5

[image: image.png]

ср, 12 сент. 2018 г. в 9:50, mouchin777 <notifications@github.com>:
