### ISSUE TITLE
Site events is no longer accessible

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1187]
I used to be able to view honor breakdown of a user in the site events page, e.g:

https://www.codewars.com/users/Voile/site_events

But it seems that it's no longer accessible.

**Comment by docgunthrop** [comment]
Use a dash/hyphen rather than an underscore.

https://www.codewars.com/users/Voile/site-events

**Comment by Voileexperiments** [comment]
Hmm, looks like my browser history deceived me again.
