### ISSUE TITLE
Previous solutions should also store previous tests

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1188]
Currently, as far as I know, there is no way to see previous tests you have written for a Kata. Since users are encouraged to write their own tests for their solutions, users should also have a way to store and reference these tests if revisiting a Kata at a later time.

**Comment by Voileexperiments** [comment]
All the changes are logged inside Revisions.

Though I agree that the changelogs there are *very* hard to read and understand.

**Comment by kazk** [comment]
Closing as duplicate of #857
