### ISSUE TITLE
Kata gets random tags assigned?

### ISSUE THREAD

**Issue by bkaes** [Codewars/codewars.com#119]
The kata [fix my method](http://www.codewars.com/kata/fix-my-method/discuss#5597b1a5093d85d93300007f) has the tags "bugs" and "methods" set in its editor.

However, the [detail page shows](http://www.codewars.com/kata/fix-my-method/javascript) shows a bunch of additional tags, such as

- Functions
- Object-oriented Programming
- Control Flow
- Basic Language Features
- Fundamentals

How did those tags get assigned?

**Comment by jhoffner** [comment]
The tagging system has some predefined tags and a hierarchy. You can freely type in whatever tag you want into the tag field, but the system reconciles those values towards the pre-defined system tags. Only the system tags show up in the list, often including tags that are mapped as related terms. 

So in this case tagging a kata as "methods" maps to the system "methods" tag, which is considered a basic language feature and a component of object-oriented programming. Typically methods are just functions that are associated to objects, so "Methods" is considered a child of the "Functions" concept.
