### ISSUE TITLE
Lots of  code 429 errors

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1191]
I continuously get
```
Request failed with status code 429
You have gone over your IP based rate limit, please try again in 30 seconds
```
Something new?

**Comment by fris42** [comment]
Same here

**Comment by elanamig** [comment]
In the same boat.  Tried on a different computer - let me submit twice, and then this error again.  Waiting didn't help.  Switching/skipping problems didn't help.  Started today.
