### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1192]
> Request failed with status code 500
> This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

https://www.codewars.com/kata/59eb8739fc3c49b67a00007d/
https://www.codewars.com/kata/59eb80eea95427d81a0000fc/

**Comment by ice1000** [comment]
I wanted to do some small modifications (improving the tests). But I failed.

**Comment by masaguaro** [comment]
Hello I have the same error when dealing with this Kata

[https://www.codewars.com/kata/total-increasing-or-decreasing-numbers-up-to-a-power-of-10/train/python](url)

**Comment by ice1000** [comment]
You just have to wait a few hours
