### ISSUE TITLE
Preloaded Nim doesn't work

### ISSUE THREAD

**Issue by hlaaftana** [Codewars/codewars.com#1193]
Preloaded:

    const X* = "Test"

The following both fail with STDERR: `solution.nim(1, 15) Error: undeclared identifier: 'X'`:

1\. Solution:

    proc a = echo X

Tests:

    a()

2\. Solution:

    discard

Tests:

    echo X

**Comment by kazk** [comment]
`import setup` needs to be added to the solution. See [codewars-runner-cli/documentation/environments/nim](https://github.com/Codewars/codewars-runner-cli/blob/master/documentation/environments/nim.md) for more info.

Some of the languages added long time ago implements "preloaded" code by simply prepending to submitted solution. But this causes confusions like mismatching line numbers in error messages. So the newer languages like Nim are avoiding that. We do need to make the documentation easier to find.
