### ISSUE TITLE
Ads are not disabled for Red users

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1194]
Related: #931 

Since last month or so I've been seeing Carbon ads all over the site, despite that I'm a Red user. I think some checks are not working.

**Comment by jhoffner** [comment]
Is "display ads" checked within your account settings?

**Comment by Voileexperiments** [comment]
Yes. But I don't seem recall such option being there in the first place (or have ever fiddled with it in the past).

**Comment by Voileexperiments** [comment]
By the way, I guess it can be closed since it's intended behaviour?
