### ISSUE TITLE
PHP asort breaks kata solution submission

### ISSUE THREAD

**Issue by stormhaul** [Codewars/codewars.com#1196]
When solving kata, I kept running into problems where my kata would never successfully submit a request and receive an answer. Turns out if I removed any calls to asort() it suddenly could submit requests again. Added it back in didn't work anymore.

**Comment by kazk** [comment]
Isn't this because `asort` works in place? Mutating the input can cause unexpected behaviors.
Closing because this is not Codewars issue, try asking questions on the kata discourse.
