### ISSUE TITLE
Please ban user "Chickenman2017"

### ISSUE THREAD

**Issue by rasmusri** [Codewars/codewars.com#1198]
The user "Chickenman2017" are spamming the "Remove String Spaces" kata with things such as extremely long texts and other unrelated stuff. He has only completed 1 kata.

![screenshot 2017-10-26 at 17 55 31](https://user-images.githubusercontent.com/31729410/32063202-e23178f4-ba76-11e7-9bd5-4c24cca3124f.png)

![screenshot 2017-10-26 at 17 53 36](https://user-images.githubusercontent.com/31729410/32063095-a28bc60a-ba76-11e7-91af-6037974eb2d2.png)

**Comment by jhoffner** [comment]
comments removed
