### ISSUE TITLE
Error 500 when trying to approve a translation

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#120]
See http://www.codewars.com/kata/557b75579b03996942000061/discuss/

This is my kata which was recently approved and had no bugs as far as I remember.

Today g964 added a C# translation, which I approved. After that he did some edits in kata related to his translation on my request.

Later on, g964 added a Java translation. Now when I try to open the Java translation kumite, I get redirected to Error 500 screen. The same Error 500 appears when I try to open a discussion of that kumite (from list of translations, I can see it has 1 discussion inside).

Also, now C# translation has disappeared from kata. I tried to find out why, and therefore went to see revision history - but it yields Error 500 as well!

In addition to that, my (author's) signature disappeared from kata header, just as described in https://github.com/Codewars/codewars.com/issues/46.

**Comment by bkaes** [comment]
> Now when I try to open the Java translation kumite

Hm, I can open the [Java translation](http://www.codewars.com/kumite/5597e6d1e0bc9fb0c9000058?sel=5597e6d1e0bc9fb0c9000058). The [C# translation](http://www.codewars.com/kumite/5597ad19093d857f99000066?sel=5597ad19093d857f99000066) is also still in the list and marked as "approved".

**Comment by MMMAAANNN** [comment]
I am still getting Error 500 on both of them.

**Comment by g964** [comment]
I am still getting Error 500 on both of them too.

**Comment by MMMAAANNN** [comment]
This issue still remains, the kata is still broken as before. However, somehow the Java translation got approved (not by me). The C# translation is still missing. And I still get the 500 error when I try to view the any of the translation kumites or trying to access "Revisions" from the kata editor.
