### ISSUE TITLE
Kata Description/Instructions Best Practices

### ISSUE THREAD

**Issue by jhoffner** [codewars/codewars.com#1200]
The Wiki needs to outline some best practices for creating kata descriptions. Currently the descriptions in kata vary too much and there are a lot that are poorly constructed. These best practices will be within their own "Kata Description Best Practices" page and will succinctly describe expectations. There are some best practices notes listed [on the wiki](https://github.com/Codewars/codewars.com/wiki/Tutorial%3A-Create-Your-First-Kata) but we should encapsulate these into a more formal document specific to writing descriptions. This document will be referenced within the beta process and when creating kata to help guide users towards creating/vetting content on the site.

This issue is being filed not just to mark it as a TODO item but also to get feedback from the community on what aspects should be included within each kata description to help improve content quality. 

To get the conversation started, here are a few sections that I think should be included within every kata:

- - -
### Task Overview
You should always provide an overview of the task, which succinctly encapsulates the expectations. 

```markdown
# Task Overview
For this kata, you will be completing the `combineAll` method. 
It will take multiple arrays and combine their values into one single array.
```

### Usage Examples
You should always provide some basic usage examples to demonstrate how the method would be called. It should always provide documentation on what the output values would be so that candidates can see a working example. For example:

~~~markdown

# Usage Examples
```javascript
 combineAll([1,2], [3], [4]) // => [1,2,3,4]
```

~~~

### Documentation
If there are multiple methods to be completed, then we should provide documentation. We may want to provide documentation even for a single method, if the signature/expectations is not clear without it.

```markdown
# Documentation
## charsStartingAt(val, index)
Receives a string and returns chars as an array, starting at index
- Inputs
  - `val`: string
  - `index`: integer (default = 0)
- Output
  - array<char>

## charsEndingAt(val, index)
Receives a string and returns chars as an array, starting from index 0 and ending at the index specified.
- Inputs
  - `val`: string
  - `index`: integer (default = 0)
- Output
  - array<char>
```

> Note: I'm also working on a markdown format extension that would allow us to plug language specific types into documentation, so for example you could write `@@docType:List<String>` and it would render `Array of Strings` for Javascript and `List<String>` for C#.

### Constraints
We should document the lower/upper bounds of the test, to help identity performance requirements. 

~~~markdown

# Constraints
```
0 ≤ a.length ≤ 105,
-1000 ≤ a[i] ≤ 1000
```

~~~

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1bf4) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
https://docs.codewars.com/authoring/guidelines/description
