### ISSUE TITLE
Output window shrunk on chrome and Edge browsers and will not scroll 

### ISSUE THREAD

**Issue by kieranflynn** [Codewars/codewars.com#1202]
Output window shrunk on chrome and Edge browsers and will not scroll, issue occurring on multiple katas. Refreshing browsers and logging out / back in have not resolved.

**Comment by DonaldKellett** [comment]
I've noticed a similar issue on Safari 11.0 over the past week or so but the only difference is that it is scrollable (at least for this time where I've deliberately tried to reproduce the issue) and it usually disappears after a page refresh:

![2017-10-28 10 46 51](https://user-images.githubusercontent.com/7777884/32130598-e228e10a-bbcd-11e7-854c-3c3415d28693.png)

**Unfortunately this Issue did not go away even after two page refreshes this time.**

**Comment by g964** [comment]
Same: output window is shrunk on Google Chrome and don't scroll.

**Comment by luisgc91** [comment]
Same here as well on Chrome. I can't even scroll.

**Comment by prznowak** [comment]
Same here on Chrome, Opera, Firefox (all up to date) on Windows and on the other computer on Chrome on Linux. Can't scroll at all.

**Comment by Souzooka** [comment]
Yeah, this is definitely happening on Chrome.

I've tried debugging it, but not sure of the exact cause. For some reason, the code window (`document.querySelector("ul.tabs-content")` will get the element) is being set to the appropriate height and then immedately back to "auto" 100s of times a second.

You can actually see the page repeatedly setting the height of this window by pasting this code in your console when the window is open:

```javascript
window.setInterval(function() {
    var elem = document.querySelector("ul.tabs-content");
    if (elem) {
      elem.style.height = "1000px";
    }
  }, 10);
```

It's very weird behavior.

**Comment by prech** [comment]
Chrome user here, have noticed it in versions 62, 63 (Chrome beta) and 64 (Chrome Canary), as well as the latest Opera.

Firefox does indeed seem immune for now

**Comment by jhoffner** [comment]
The issue should be resolved.

**Comment by Souzooka** [comment]
This is still happening.

**Comment by prech** [comment]
> The issue should be resolved.
 
Looks good to me, Chrome 62, including Incognito window, and beta 63 :)
