### ISSUE TITLE
On every Train Kata page: Scroll down continuously bounces to top of page.

### ISSUE THREAD

**Issue by cgregs32** [Codewars/codewars.com#1204]
On Chrome browser, with Mac OS.

On every Train: Kata page, the scroll bar continuously bounces to the top of the page.  This prevents viewing the bottom section of the kata page.

This appears to happen anytime I scroll down to view more details of the kata.  Any scroll down movement will bounce the page back up to the top.

Continuously trying to scroll to the bottom of the page will cause a repeated shaking of the page. As I try to scroll down and the functionality immediately moves me back to the top and prevents access to the lower page content.

This issue is the same for a second computer with Mac OS/ chrome browser.

**Comment by oscar-corredor** [comment]
Additionally CPU usage skyrockets while on the coding playground.

**Comment by mentalplex** [comment]
+1, with the following additional information
The scroll bar works for getting to the end of a description, but won't work to get back to the top.
Interim fix: use the scroll bar to go down, mouse or trackpad gestures to go up.

**Comment by AlvanChow** [comment]
Have the same problem.

Infinite scrolling on the "Instructions" tab, and minimized screen on the "Output" tab. Using Chrome/MacOS

**Comment by BenAttenborough** [comment]
@oscar-corredor I also have skyrocketing CPU usage on the site (chrome on Mac OS). It makes my laptop fan spin up noisily. Not sure if this is a bug per-se, but would be nice to fix. However would it be best to raise this as a separate issue?

**Comment by anssihakkarainen** [comment]
With short inspection it seems that Description element is somehow broken on the page. When description is longer than viewable space, element should include scrollbar and hide extra content below. Now content leaks out of the element:
![train bundesliga 1 spieltag - first match day codewars](https://user-images.githubusercontent.com/33027332/32159545-a6ab2950-bd56-11e7-8cdd-848765c8dad2.png)
 
Browser: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OS: Windows 10

**Comment by BenAttenborough** [comment]
The inspector suggests that overflow-y is set to auto:

![overflow](https://user-images.githubusercontent.com/8101421/32163107-1aba6d00-bd53-11e7-98c3-b5799832c1fb.jpg)

Looks like other divs set overflow to hidden, and then I assume use js to add a scroll bar (try inspecting the tests div).

**Comment by jhoffner** [comment]
Should be resolved now
