### ISSUE TITLE
undefined method `sanatize'

### ISSUE THREAD

**Issue by luisgc91** [Codewars/codewars.com#1205]
Trying to access ... https://www.codewars.com/users/leaderboard/kata

I got this error

undefined method `sanatize' for #<#<Class:0x00557560eb8590>:0x007fb139bb6538>
![captura](https://user-images.githubusercontent.com/7572760/32139654-e97d08f0-bc4f-11e7-8468-5356c73cde0b.JPG)

**Comment by Voileexperiments** [comment]
It seems that you can't access that leaderboard directly. You need to go from https://www.codewars.com/users/leaderboard and then click on the "Completed Kata" tab.

**Comment by luisgc91** [comment]
Previously it was possible to access the leaderboard directly.
