### ISSUE TITLE
When translating a Kata, typing in the description or code window scrolls the description to the top

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1206]
Issue: When translating a Kata, typing in the description or code window scrolls the description to the top

How to reproduce: Create a new Kata translation, scroll the description/Kata specs window to the bottom, and type in the code window.

Temp fix: Replacing `jQuery.style` with a dummy function, e.g. `jQuery.style = () => null`, causes this issue to disappear. The user's scroll position is likely lost when the styles are reset.

Note: This issue is separate from #1202 / #1204 and has been occurring for a while.

**Comment by 10XL** [comment]
Duplicate of https://github.com/Codewars/codewars.com/issues/353

**Comment by kazk** [comment]
Closing as duplicate of #353
