### ISSUE TITLE
undefined method `name' for nil:NilClass when opening a notification

### ISSUE THREAD

**Issue by marrakchino** [Codewars/codewars.com#1212]
When opening the first notification in the list (as shown below), I get this error:

![image](https://user-images.githubusercontent.com/16545838/32441307-4f348972-c2f7-11e7-9e09-84e619fdae93.png)

**Comment by bestwebua** [comment]
undefined method `name' for nil:NilClass, I have the same error too.
![screenshot from 2017-11-07 16-21-26](https://user-images.githubusercontent.com/14002692/32498304-0786fa92-c3d8-11e7-94f6-31628910e5f3.png)

**Comment by kazk** [comment]
Fixed
