### ISSUE TITLE
Ruby translation bug

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1216]
When validating a Ruby translation "STDOUT display" and "output" appear and then disappear *at once* so it is impossible to see the output.

**Comment by jhoffner** [comment]
That output is only for streaming updates only, mostly there to give you feedback while the program runs. The final output should contain all the information you need. 

Are you saying that absolutely no output is being shown?

**Comment by g964** [comment]
The output is being shown less than a fraction of a second and is impossible to see. All disappears except the number of passed tests and success or not. So one can say that no output is being shown.

The kata is <https://www.codewars.com/kumite/5a03059dc9fc0ee94b000081?sel=5a03059dc9fc0ee94b000081>. I validate the translation since it was successful. BTW the author is inactive since at least a month.

**Comment by kazk** [comment]
This is caused by empty string in `Test.describe("")`. Change it to `Test.describe("Bernoulli")` and you should see:

![image](https://user-images.githubusercontent.com/639336/38978731-156ec2ce-436d-11e8-9bf7-afdd12ac0eba.png)

**Comment by kazk** [comment]
I think this is really confusing so I'll look into why this happens and/or disallow empty string.

**Comment by g964** [comment]
Corrected with Test.describe("Bernoulli"), that works, thanks.
Note : it is impossible to test independently "Sample tests".

**Comment by kazk** [comment]
> Note : it is impossible to test independently "Sample tests".

That's reported in #103
