### ISSUE TITLE
Objective-C: Misleading comments in "(Sample) Test Cases" Template Code

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1217]
I've just started my first translation on Objective-C and noticed that the comments say the following:

```obj-c
// TODO: replace with your own tests, these are just how-to examples.
// BDD (Codewars) Spec Example:
// Codewars uses a custom framework for testing code. The basic methods are describe, it, equal and notEqual.
```

However, as per the Wiki (which states that UnitKit is used), the statement "Codewars uses a custom framework for testing code" is not true as it implies that the testing framework used is developed by and unique to CW.

**Comment by kazk** [comment]
This is outdated comment, there's `cw-2` for Objective C that seems no longer used on Codewars.
