### ISSUE TITLE
Objective-C: Add documentation to specify that test methods need to start with "test"

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1219]
This is the current Objective-C test suite code sample:

```objc
  // TODO: replace with your own tests, these are just how-to examples.
  // BDD (Codewars) Spec Example:
  // Codewars uses a custom framework for testing code. The basic methods are describe, it, equal and notEqual.
  @implementation TestSuite
  - (void) testsIfReturnsActual
  {
    UKStringsEqual(@"expected", Solution(@"value"));
    UKStringsNotEqual(@"expected", Solution(@"value"));
  }
@end
```

Apart from the comments provided being **completely** *irrelevant* to Objective-C (I guess they are for JS Mocha?), they should specify that all test methods in UnitKit should start with "test".  This is not 100% apparent in the current code example and took me a while to figure out when I thought that all the test output was somehow hidden.

**Comment by DonaldKellett** [comment]
Also, a few points to consider (these are not compulsory):

1. The indentation in the example test suite is rather weird, consider changing it to the following so it agrees with the indentation style shown in many other Objective-C tutorials and the official Apple documentation:

```objc
@implementation TestSuite
- (void)testsIfReturnsActual
{
  UKStringsEqual(@"expected", Solution(@"value"));
  UKStringsNotEqual(@"expected", Solution(@"value"));
}
@end
```

2. Most example test suites compile/execute correctly, e.g. JS example test suite has something like `Test.assertEquals("actual", "expected")`.  However, ObjC example test suite doesn't compile correctly because `Solution(@"value")` is used in place for `@"actual"` (and `Solution` obviously doesn't exist).  I would recommend replacing the *two* current assertions with **one** `UKStringsEqual(@"expected", @"actual")` assertion.
3. Perhaps clarify that the class containing the test cases *must* be called `TestSuite`?  In many other languages, the name of the class containing the tests can be modified (e.g. in PHP anything extending `TestCase` will do) so it isn't immediately apparent to the ObjC author/translator that the name `TestSuite` cannot be customized.

**Comment by kazk** [comment]
I found the following in [their source](https://github.com/etoile/UnitKit/blob/master/FrameworkSource/UKRunner.h#L47-L59)
```
 * @section Executing Test Methods
 *
 * A test method is a method prefixed with <em>test</em> e.g. -testSometing.
 *
 * For each class marked with UKTest and each test method in this class (this 
 * also includes all the inherited test methods up to the superclass that 
 * conforms to UKTest), UKRunner will create an instance and invoke the test 
 * method, then release the instance, then create a new instance for the next 
 * test method, and so on. For details, see -runTests:onInstance:ofClass:.
 *
 * UKRunner also supports test class methods e.g. +testSomething.
 *
 * The test methods are executed in their alphabetical order.
```

Also, I think for most assertions, the first parameter is the expected one. See https://github.com/etoile/UnitKit/blob/master/FrameworkSource/UKTest.h

**Comment by kazk** [comment]
I just remembered that I made a prototype for new documentation and that one has `// this must start with test`.
![image](https://user-images.githubusercontent.com/639336/32588843-237c67fc-c4c6-11e7-8e5f-aca8d991cc95.png)
https://kazk.github.io/docs.codewars.com/languages/objc/unitkit/

**Comment by kazk** [comment]
I made that page because UnitKit doesn't seem to have a documentation page. We can move that to wiki.

**Comment by kazk** [comment]
Added https://github.com/Codewars/codewars.com/wiki/UnitKit
