### ISSUE TITLE
Run/Attempt buttons not visible on Retina Macbook

### ISSUE THREAD

**Issue by undefinedvalue** [Codewars/codewars.com#1227]
The Reset/Run/Attempt buttons on kata are not visible on a 12-inch Retina MacBook because they overflow off of the page. Zooming out on the page makes them visible. As this was my first time using Codewars, it was frustrating figuring this out since I didn't even know what it was supposed to look like.

I'm running at the system default resolution of 1280x800 (12-inch retina macbook's native screen resolution is 2304 x 1440, but downscales by default).

Here's a screenshot, you can see the top pixels of the buttons.

![ss](https://user-images.githubusercontent.com/5945229/32993125-a67881aa-cd08-11e7-8ff4-1660d4faab63.png)

**Comment by mthorning** [comment]
I'm having this issue on my Dell XPS-13, the height of the screen changes when I go past a certain width - looks like a breakpoint thing.
