### ISSUE TITLE
Failed to communicate with code execution service

### ISSUE THREAD

**Issue by kbsaxena** [Codewars/codewars.com#1229]
Not able to run anything. Same error is shown always "Failed to communicate with code execution service"

**Comment by moealemam** [comment]
omg, 3 days and nothing? Is codewars dead?

**Comment by kazk** [comment]
This must be a separate issue from #1230 because that was caused by some changes from yesterday. We didn't see issues when this one was reported and need more information.

**Comment by Gregor100** [comment]
I always get this error. I just started and that annoys a little bit -.-

**Comment by Voileexperiments** [comment]
As mentioned on #1199 as well:

This seems to happen only when using IE (because I've encounted this many times before). It won't happen if you're using Firefox/Chrome.

**Comment by kazk** [comment]
Closing as duplicate of #1199.

Also, we've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
