### ISSUE TITLE
Request: no 500-completions-lock for katas with unresolved issues

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#123]
Justification:

Currently, if kata reaches 500 completions, its test cases become read-only. However, there are lots of katas that have long-standing issues due to inactivity of author/contributors, and in this case once they reach 500 completions, those issues may become permanent.

**Comment by bkaes** [comment]
Here's my [feature request](http://www.codewars.com/topics/feature-requests) I've submitted three months ago, just in case will be gone (see #130):

> Make tests editable even after 500 warriors have solved them, if and only if the new tests don't invalidate the old solutions.

> # Reason
> ## Better error messages

> Sometimes, a user uses `Test.expect` instead of `Test.assertEquals` or similar. This leads to bad error messages, see [reverse words](http://www.codewars.com/kata/5259b20d6021e9e14c0010d4/discuss#552c8f5ee1989a8fa6000073). The proper test would use `assertEquals` and would not change the semantics of the tests at all.

> Similarly, the arguments are sometimes swapped, e.g. C# uses `expected, actual`, whereas JavaScript/Ruby/Python use `actual, expected`. Translators or kata authors don't notice this all the time, which leads to confusing error messages.

> ### Wrong tests

> Hands down, I've messed up the translation of is [a number prime](http://www.codewars.com/kata/is-a-number-prime), where I accidentally added `abs` to the reference solution. I've added a "bug" note so that people know that they need to use `abs`, but it would be much better if one was able to simply change the tests so that they only take positive numbers into account and/or check for the current behaviour and the correct one, e.g.

> ```haskell 
> it "should work for negative numbers" $
>   property $ \x ->
>     oldProperty x .|. newProperty x
>
> it "should work for random examples" $ 
>   property $ \x ->
>     oldSolutionProperty x .|. newSolutionProperty x
> ```

> Even though this tests still let negative primes pass, they also let _correct_ solutions pass.

> There are other examples where it would be helpful to change the tests afterwards, for example the tree traversal kata, where the built tree is simply wrong in Haskell (the comment mentioning that has more than 20 upvotes).

> ## Implementation

> After a change to a 500+ kata, the test cases become locked and get checked asynchronously against the solutions (we're using the solutions as tests for the new tests). If this fails for a solution A, check whether A passes the old tests. If it does, refuse the new tests. If `A` fails also on the old tests, mark it as non-passing and continue. If all tests pass, notify the kata author, commit the changes, but unlock the tests only after the necessary time for the check has passed twice (e.g. 10 minutes to pass all tests => 30 minutes locked total (10 mins tests + 20 additional)). This test checking should have low-priority compared to other jobs, so it could take much more than the mentioned 10 minutes.

**Comment by GiacomoSorbi** [comment]
+1 or, alternatively, allow users with 5000+ honour to edit it directly or pull an edit for an admin to approve/reject: currently there are like 15 users with 5000+ points and (except the underwritten of course) they are surely more than capable to improve a kata in need.

**Comment by javatlacati** [comment]
migrated! https://codewars.ideas.aha.io/ideas/CW-I-93

**Comment by jhoffner** [comment]
You can now edit any language which itself does not have 500 completions (its been possible for a few days now). Does that satisfy this issue enough to close it?

**Comment by javatlacati** [comment]
Sure as long you please don't close #163 :santa:

**Comment by ericswenson15** [comment]
+1
