### ISSUE TITLE
4 HOURS AND COUNTING... PLEASE FIX

### ISSUE THREAD

**Issue by samibirnbaum** [Codewars/codewars.com#1230]
Time: 0ms
Server Execution Error:
The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
Request Error:
Request failed with status code 500

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by kane1138** [comment]
I've been getting this error all day in multiple browsers and on multiple PCs.

**Comment by thecoolster** [comment]
i used different browsers and different computers as well. A macbook and a windows laptop. Same exact 
error. Please fix this??

**Comment by sularome** [comment]
+1

**Comment by Len512** [comment]
+1

**Comment by SpenceUK** [comment]
Same issue here, I checked the status page and it says there are no errors but this is happening been like this for 4 hours now.

**Comment by calvinchengcc** [comment]
+1

Same issue for me.

**Comment by wadie** [comment]
It's been going for a while now.. weird, it's like no one cares

**Comment by samibirnbaum** [comment]
It would be courtesy of someone just to say "sorry about this we are working on it"

**Comment by nickbullock** [comment]
++

**Comment by raymondedison** [comment]
+1. In case in anybody was thinking it could be an ISP/network issue not codewars': all other sites work fine, same latency I'm used to, no parental/work/school blockers here, and just to be extra sure switched ISPs (from CenturyLink DSL to Verizon hotspot) and got the same issue. Happens when trying to test a kata and kata attempts. Some are succeeding now but much slower than usual. Stalls on **Status: Assigning a server**. Everything else seems fine. Haven't checked kumites.

**Comment by AdamSlodowy** [comment]
++

**Comment by wadie** [comment]
Any good codewars alternative ?

**Comment by novik90** [comment]
`+` Please fix it
![fixthecd](https://user-images.githubusercontent.com/12540891/33186542-50c00094-d09b-11e7-940d-00f004916380.png)

**Comment by moealemam** [comment]
++
I'm trying to show codewars to a friend who just started programming :(

**Comment by wadie** [comment]
#1229

**Comment by novik90** [comment]
it's work

**Comment by kazk** [comment]
I've contacted @jhoffner and we're looking into it.
Sorry about the delay, everyone is off for thanksgiving.

**Comment by kazk** [comment]
We found the possible cause and the fix is being deployed.

**Comment by kazk** [comment]
Closing this as fixed. Seems to be working for the past 2 hours.
