### ISSUE TITLE
Request failed with status code 500 - timeout when testing and submit solutions.

### ISSUE THREAD

**Issue by qblacksheep** [Codewars/codewars.com#1231]
Hello, whole day i have problem with test or submit solution. Every time when i try it i get a timeout error.
Request failed with status code 500. Everyone got this problem or only me? I tried from diffrent PC's with other net connections and still don't working.

**Comment by art-ewantes** [comment]
++
Still have the same problem.

**Comment by moealemam** [comment]
++
same. trying to show a friend who just started programming :(

**Comment by thecoolster** [comment]
main thread is at #1230 check that out as well guys... this is so wierd.. is everyone off for thanksgiving ..... no response at all????

**Comment by lukasowy** [comment]
i have the same problem

**Comment by kazk** [comment]
Closing as duplicate of #1230, I've reached out to @jhoffner and we're looking into it. Sorry about the delay, everyone is off due to thanksgiving.
