### ISSUE TITLE
unknown test condition

### ISSUE THREAD

**Issue by 4knort** [Codewars/codewars.com#1232]
Hello, why can't i see what tests are failing? i just get a messaage something like "test ddin't pass' and thats all
I want to see with what argument the function was called so it failed, I remember long ago there was an opportunity to see this now there is not, why?

**Comment by kazk** [comment]
Test outputs comes from test cases written by kata authors.

> Is the issue you are filing related to a specific kata?
>
> If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Most languages allow inspecting the arguments by printing them (e.g., `console.log(x)`, `print(x)`, `puts x`, etc).
