### ISSUE TITLE
Suggestion: Promote the Weekly Coding Challenge Kata

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1236]
Occasionally (not sure if it is weekly though) I received from Codewars the "**Weekly Coding Challenges**" email. Because these seem to be hand-picked so I guess somebody at CW HQ thinks they represent "cream of the crop" Katas.

So I think they should be published better - to act as more incentive for people to write better quality Katas

**Suggestion 1.** Is there some archive of these somewhere? If not maybe there should be. Or maybe just have CW predefined "Collections" like
* CW Weekly Challenge Newsletter - 2017 Week 1
* CW Weekly Challenge Newsletter - 2017 Week 2
* CW Weekly Challenge Newsletter - 2017 Week 3
* etc

**Suggestion 2.** The chosen Kata should be sortable (Kata Filter = "CW Recommended") and such Kata should be identified in the Kata lists by some little badge/icon . Authors will aspire to getting these badges for their Kata and quality will improve.

**Comment by dinglemouse2250** [comment]
![image](https://user-images.githubusercontent.com/22114719/33245222-e0915b68-d358-11e7-8859-4100d9a38b95.png)

**Comment by Voileexperiments** [comment]
The *real* issue is that usually they're just old katas that may or may not have received new translations recently. So there's nothing new there. (In fact, IIRC some katas have been featured more than once.)

Also, most of them are white/yellow katas. I'd expect more blue/purple katas there to encourage the competent people to tackle them, but currently they're just lackluster. Adding 10k solves to a white kata is not very meaningful.

**Comment by kazk** [comment]
Thanks for the suggestion, but we're not going to add this.

> Because these seem to be hand-picked so I guess somebody at CW HQ thinks they represent "cream of the crop" Katas.

I'm not involved with the newsletter so I don't know exactly how they're picked. But I wouldn't want to treat the list as anything more than "some kata to try this week".

But I like your idea of encouraging authors. I've been thinking of [something similar](https://github.com/Codewars/codewars.com/issues/1626#issuecomment-438400435). I just don't want to use the newsletter as the basis.
