### ISSUE TITLE
Editing approved translations

### ISSUE THREAD

**Issue by mentalplex** [Codewars/codewars.com#1238]
Problem:

Sometimes (inevitably, because everyone/thing is fallible) a translation is approved despite having minor (or sometimes major) errors. Once those errors are discovered by the excellent codewars user base, the only way to fix this is to fork the translation and then have that fixed translation approved (unless I'm missing some ninja method, in which case please enlighten me).  This can take a while. 

Proposal: Streamline the process for editing a previously approved translation. In general, I believe the process for fixing errors should have as little friction as possible.

There are many ways to do this. I think any of them would be satisfactory. The translator is already listed as a contributor to the kata, so perhaps this should give them the ability to directly edit a translation (instead of forking). Or maybe allow any contributor to approve their own translation (much as you can approve your own translation if you're the author of the original kata). Again, many ways to do this, but without knowing the details of the back end, I assume most of them would involve permissions associated with being a contributor (so that the permissions only go into effect AFTER a translation is approved the first time).

**Comment by anter69** [comment]
Currently, when your translation is approved you become a contributor, and you can freely edit the kata - not only your translation, but **everything** (and I think this is not limited to power users). The only downside is that it counts as "forfeit", so you can't get any more advancement from that kata.

I don't know if it was changed after the opening of this issue, but I guess this could be closed. @kazk?

**Comment by kazk** [comment]
> I don't know if it was changed after the opening of this issue

I'm not sure, but I think the "500 solutions rule" was getting in the way. It was removed few months ago.

**Comment by Voileexperiments** [comment]
@kazk However before the 500 solutions rule was removed, there was another bug: trying to bypass it by approving a new translation will result in the new translation not applied to the kata *at all*.

Is this eliminated too after the 500 solutions rule was removed?

**Comment by kazk** [comment]
@Voileexperiments So the workaround: "the only way to fix this is to fork the translation and then have that fixed translation approved" didn't work? Is there issue open for that?

@jhoffner can you let us know what changed?

**Comment by Voileexperiments** [comment]
@kazk I didn't raise an issue about it, but I tried it once before the 500 rule was removed and it wasn't applied to the kata. I can't recall the kata out of my head but it has to do with a translation adding performance requirements when it's not mandated by the kata (and every other language does not have performance requirement).
