### ISSUE TITLE
Error 500 when submitting an attempt for a Kata

### ISSUE THREAD

**Issue by jfbenckhuijsen** [Codewars/codewars.com#1239]
Whenever I try to attempt (button) for the real unit test of the kata i'm working on, I get a Error 500, The details of the error say "Error 500 could not be cloned".

Kata i'm working on is http://www.codewars.com/kata/brainfuck-translator/train/java

Running the sample unit test works fine.

**Comment by DelegatedCore** [comment]
I have the same issue with this kata using Java: https://www.codewars.com/kata/reverse-or-rotate/train/java

**Comment by DelegatedCore** [comment]
The error went away when I removed all System.out.print() from the code.

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.
