### ISSUE TITLE
Clicking progress goes to the wrong url

### ISSUE THREAD

**Issue by flip111** [Codewars/codewars.com#1244]
When i'm here https://www.codewars.com/kata/search/haskell?q=&r%5B%5D=-8&xids=not_completed&beta=false

and select Progress ->

* `Kata i have completed` i go to `https://www.codewars.com/kata/search/haskell?q=&r%5B%5D=-8&xids=not_completed&beta=false`
* `Kata i have not completed` i go to `https://www.codewars.com/kata/search/haskell?q=&r%5B%5D=-8&xids=completed&beta=false`
* `Kata i have not trained on` i go to `https://www.codewars.com/kata/search/haskell?q=&r%5B%5D=-8&xids=played&beta=false`
* `All` i go to `https://www.codewars.com/kata/search/haskell?q=&r%5B%5D=-8&beta=false`

The first two seem wrong. In all cases the actual list with katas does not change (it doesn't matter what i select for progress). Changing kyu level does change the kata list.

i had sort by newest, language haskell and status approved

**Comment by anter69** [comment]
It seems to work correctly, although I agree that the urls are confusing:

**completed:**

![image](https://user-images.githubusercontent.com/12795864/37458433-53c5ca2e-2845-11e8-9231-3781597b3b70.png)

**not completed:**

![image](https://user-images.githubusercontent.com/12795864/37458498-7c39f822-2845-11e8-8b5a-a4eb80fd212f.png)

etc.

@kazk I believe the issue can be closed

**Comment by kazk** [comment]
Thanks @anter69. I'm guessing `xids` stands for e**x**cluded **ids**.
