### ISSUE TITLE
Have no access to "Submit" button

### ISSUE THREAD

**Issue by ezhikov** [Codewars/codewars.com#1249]
Hello.

Steps to reproduce:
1. Get 13 inches full-HD notebook with Windows 10 (with default scaling of 150%).
2. Try to solve kata.
3. Buttons is under the edge of the browser and there is no scroll available.

Reproduced both in Firefox (58.0b10) and Chrome (62.0.3202.94).

[Screenshot](https://screenshots.firefox.com/fWKHRjGxGU3I1Mss/www.codewars.com)

**Comment by vnhnhm** [comment]
It's present since a lot of time. What works is hitting CTRL + S to check if the kata passes the tests, then again CTRL + S to send it. Or clicking as crazy in anywhere near the submit button.

**Comment by error256** [comment]
BTW, scrolling by middle mouse *click* also works.

**Comment by ezhikov** [comment]
@vnhnhm this is still bug, whether there is workaround or not.

**Comment by vnhnhm** [comment]
Did anybody say the opposite @ezhikov?, error256 and I gave possible solutions for users to send their code and not finishing there with the kata already solved but without being able to submit it.

**Comment by ridjis** [comment]
In my case, going to browser fullscreen mode I'm able to see _submit_, _run sample tests_ and other buttons but in console in keeps printing like in screenshot bellow forever
![image](https://user-images.githubusercontent.com/11313640/34080404-9415defe-e33d-11e7-9cab-6e33dd6b6dab.png)

**Comment by tr33m4n** [comment]
This is still an issue in Chrome 63 on OSX... Opening dev tools (Cms + Option + i) shows the buttons

**Comment by mikeyduece** [comment]
I zoomed out to 90% and they showed up

**Comment by kazk** [comment]
This issue will be tracked on #1214
