### ISSUE TITLE
C# System.Numerics

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#125]
After having passed a lot of time to translate a kata in C#, when I try to run it, I get:

Error: Command failed: /tmp/csharp115610-19-3w2og3/code.cs(2,14): error CS0234: The type or namespace name `Numerics' does not exist in the namespace `System'. Are you missing `System.Numerics' assembly reference?

I had added to my solution and tests "using System.Numerics" but nevertheless I got the error above!

Is System.Numerics" installed or not? It is in Framework 4.0

**Comment by YiyangLi** [comment]
System.Numerics is installed in Framework 4.0, but you have to include it in the reference manually, at least in Visual Studio. Yes, it's required to use BigInteger.

**Comment by jhoffner** [comment]
The assembly should now be referenced with the DLL and available for import.
