### ISSUE TITLE
[Feature Request] Swift 4

### ISSUE THREAD

**Issue by jpv123** [Codewars/codewars.com#1250]
Hi, I just started with codewars and noted that swift version is still 3.1.1. I would like to feature request an update to language version to current version 4

Thanks

**Comment by DonaldKellett** [comment]
@jpv123 In that case you should consider making a pull request to the [Codewars Runner CLI](https://github.com/Codewars/codewars-runner-cli), cheers :smiley:

**Comment by kazk** [comment]
@jpv123 we've been working on a new system to replace the current one so don't work on making PR for CLI repo. One of the main reasons behind the rewrite is to support multiple language versions without affecting existing contents. I don't know how soon we can add it, but Swift 4 is planned.

**Comment by kazk** [comment]
Closing this. See https://github.com/Codewars/codewars-runner-cli/issues/554

**Comment by kyzmitch** [comment]
Damn, it is impossible to solve problems if they're connected to Strings manipulation with Swift 3.1.1
