### ISSUE TITLE
Kotlin Translation to a Kata times out on publishing

### ISSUE THREAD

**Issue by lemertens** [Codewars/codewars.com#1253]
Whenever I try to publish the Kotlin translation of my Kata I got a "Publishing time out" even though the "Validate Solution" gives me an all-thumbs-up (Tests passed in 15 to 19 sec).

Tried at different times of the day and for several days now :(

![screenshotkotlin](https://user-images.githubusercontent.com/33123882/33874992-0e84fbfa-df21-11e7-872e-2b55b215c837.png)

**Comment by tachyonlabs** [comment]
I've started doing Kotlin versions of some of my katas, and have been getting some of that. Friday morning I was able to publish one with no problem, but when I tried to publish the next one Friday afternoon, it took many hours of occasionally reclicking Re-Publish before it finally published without timing out. Last night I tried to publish another one with yet more "Publishing Timed Out!
The server timed out while trying to publish your changes.", and I'm still trying this morning. :-(

**Comment by kazk** [comment]
It was also reported as part of unrelated issue (https://github.com/Codewars/codewars.com/issues/1407#issuecomment-385299517).

---

> now it's been sitting there in "Please wait while we publish
We are validating your code and publishing your changes. This shouldn't take too long." mode for 15 minutes or so.

This is a separate bug if you mean it doesn't show "Publishing Timed Out!" :(

---

I've been working on improving Kotlin, so hopefully that helps when it's done. But I think the root of this issue is how the background jobs are scheduled.

**Comment by tachyonlabs** [comment]
Yeah, I was out for a while after posting that, and when I came back a couple of hours later it was still hung on ""Please wait while we publish ...". I closed that window, and started it up again in another, and am back to the timeouts. Anyway, thanks for working on it! I was just at the Google I/O conference, where you heard a lot of Kotlin Kotlin Kotlin all over the place, so it seemed like a good time to start playing with it.

**Comment by kazk** [comment]
@tachyonlabs Kotlin kata should return results much quicker now. `~5s` for minimum test cases. I've also updated the Kotlin version to the latest `1.2.41`.
I still think the background job scheduler needs to be improved, but this should help with frequent timeout when publishing.

**Comment by tachyonlabs** [comment]
Yay, thanks, I was just able to publish my Kotlin version of that third kata of mine mentioned above, with no errors!

**Comment by kazk** [comment]
Cool, thanks for letting me know. I'm glad it worked.
I'm going to close this, but there's also #1408 for increasing publish timeout (or improve background job scheduler) in general.
