### ISSUE TITLE
"Kata" and "Kumite" don't work.

### ISSUE THREAD

**Issue by breadfan** [Codewars/codewars.com#1254]
Hi! "Kata" and "Kumite" sections don't work. Page starts loading, then it's just breaking. 
Tried on two browsers. Anyone knows how to solve this?

**Comment by danielkisov** [comment]
I have the same problem...didn't find any usefull solution. I think it has something to do with my OS (Windows 7). Tried Firefox, Chrome, Opera and Explorer...everywhere the page crashes after I click on Kata or Kumite..

**Comment by gima** [comment]
The Elixir Katas timeout after "Finding servers" or "Executing". Maybe the servers are overloaded.

**Comment by Archangel37** [comment]
same too.. win7x64,  Firefox, Chrome, Opera.. grief =(((

**Comment by Archangel37** [comment]
So, I decided to concretize the case. When I **log out**  [Link](https://www.codewars.com/kata/latest/my-languages) works properly - web page shows elements, I can try to do requests, but they aren't showing smth because I have logged out before. When I try to **log in** the page falls

**Comment by lteacher** [comment]
Same problem on chrome, firefox windows yes, tab crashes accessing kumite, or trying to edit 'training languages'

**Comment by kazk** [comment]
This should be fixed now. See #1157
