### ISSUE TITLE
Page has been rendering weird on Chrome on my Macbook for awhile now

### ISSUE THREAD

**Issue by Dirtier** [Codewars/codewars.com#1256]
<img width="1280" alt="screen shot 2017-12-16 at 1 51 08 am" src="https://user-images.githubusercontent.com/20347349/34068615-ea1a79a8-e203-11e7-9f6b-6e4c0a5cb67d.png">

13" MacBook Pro, Running latest version of Google Chrome. 

I don't think it is specific to Chrome, as it happens on Firefox as well. No matter how I attempt to resize the window or scroll around, I can't access either the 'Test' or 'Run' buttons. I also can't see the reset button, which can often be frustrating. Any ideas as to why this is happening? Everything used to work great, until one day ~a few months ago (not sure of the exact date). 

Apologies if this is formatted correctly, haven't ever reported an issue before. 

Thanks!

**Comment by franzmoro** [comment]
Same happens to me on 13" MacBookPro. I had to resize window with Developer tools to see all the buttons...

**Comment by kazk** [comment]
This issue will be tracked on #1214
