### ISSUE TITLE
Loading kata page error, i can't open https://www.codewars.com/kata/my-languages in any browser,

### ISSUE THREAD

**Issue by hamdiChehdi** [Codewars/codewars.com#1257]
A few things to check first:

Is the issue you are filing related to a specific kata?

If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Is the issue you are filing related to how a specific language behaves when being executed?

If so then it will likely be better to file the issue on our [github.com/Codewars/codewars-runner-cli/issues](https://github.com/Codewars/codewars-runner-cli/issues) repo, which is where we have our open source code execution functionality. You also may want to look into forking that repo and fixing the issue yourself if you have the means.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.

**Comment by Archangel37** [comment]
https://github.com/Codewars/codewars.com/issues/1254 common topic.. We have the same problem on Chrome, FF & Opera browsers, but I decided to install Safari on my PC - it's working. May be it'll be usefull for U. Good luck!

**Comment by Stewart86** [comment]
I have the same problem loading this exact page on Chrome. Is there any resolution to this issue?

**Comment by Srjkaa** [comment]
Same problem. Maybe it have some solution?

**Comment by hamdiChehdi** [comment]
i still see the problem even when i try to open the main page (https://www.codewars.com/)
![codewarloading](https://user-images.githubusercontent.com/34605324/41500368-d1cbb74a-7187-11e8-88d8-ca698ebd2966.PNG)

**Comment by kazk** [comment]
Some Windows users are having issues. Closing as duplicate.
See https://github.com/Codewars/codewars.com/issues/1157
