### ISSUE TITLE
Kumite discourse should have spoiler flag

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1258]
I recently commented some information describing my implementation for a Kumite/fork of one of my Kata solutions. 

If I understand correctly other user cannot see the fork unless they have already solved the Kata, or agree to forfeit.

But the Kumite discourse *does* show up in the dashboard always, so now I have inadvertently revealed some details I would have rather kept secret from people who have not yet solved the Kata.

There should be a way to mark Kumite discourse comments as containing spoilers so it doesn't get splashed all over the dashboard.

**Comment by Voileexperiments** [comment]
In addition: Discourse section of docs and forum section does not implemention spoilers at all.

(Yes, there are people dumb enough to ask help and dump their code there. Go figure.)

**Comment by kazk** [comment]
Closing as duplicate of #821
