### ISSUE TITLE
Persisting network error

### ISSUE THREAD

**Issue by I-am-io** [Codewars/codewars.com#1260]
Whenever I try to do an attempt or sample test on any kata, I get a network error message:

> This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

This happens without fail.

There are also these error messages in my browser console:

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cr.codewars.com' is therefore not allowed access. The response had HTTP status code 403.

> Failed to post {method: "notifyResult", message: {…}, result: Error: Network Error
    at t.exports (https://cr.codewars.com/static/js/vendor.946ea95ea6ab4b61034c…} DOMException: Failed to execute 'postMessage' on 'Window': Error: Network Error could not be cloned.

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). Please open a new issue if you're still experiencing issues.
