### ISSUE TITLE
Disappearing Codewars Red status

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#1261]
I noticed last Sunday -- December 17 -- that I no longer had Codewars Red status. I'm guessing this means that renewal time came up and the credit card I had previously used didn't go through when you tried to renew, but because as far as I can tell I didn't get any notification about this either in email or on Codewars, maybe it's actually just a glitch? 

I sent email to info@codewars.com about this on December 17 as well, but got no reply, so now I'm posting it here.

My account is https://www.codewars.com/users/tachyonlabs

Let me know if I should just wait to see if this resolves, or resubscribe, or ???

**Comment by tachyonlabs** [comment]
Maybe everyone is otherwise busy for the holidays? I'll try emailing info@codewars.com again ...

**Comment by tachyonlabs** [comment]
OK, I'm going to give up on trying to get this straightened out and just resubscribe, with the assumption that if my account has gone for weeks without autorenewing CodeWars Red as it should have done, it won't suddenly remember to autorenew after all so I somehow wind up with two CodeWars Red subscriptions at once. 

However:

1. If someone is a CodeWars Red subscriber and you don't autorenew their subscription, either because the payment doesn't go through or because you have stopped doing autorenewals (or for whatever reason), you should send them an email about this.

2. If info@codewars.com is listed as the contact address/method on your web site, you should actually reply to emails sent to that address about problems with an account.

**Comment by tachyonlabs** [comment]
Stripe says:

> Thanks so much for reaching out to us! I understand how frustrating it can be when you can’t make a payment, especially when it's not your fault. 
> 
> I want to help you get this resolved, but we can’t share any Stripe account information with anyone other than the account owner. I'd recommend reaching out to the company you were trying to make the purchase from and have them reach out to Stripe, so we can look into this. As soon as they do, we’ll get straight to work investigating this. We should hopefully be able to get this whole thing sorted out for you! 
> 
> I'm sure once they contact us we'll be able to get this resolved for you, I'll go ahead and close this case now.

I tried using a debit card, too, but that also got declined. I guess I'll try again tomorrow.

**Comment by kazk** [comment]
@tachyonlabs Sorry for the delay. @jhoffner came back today, but I think he's still trying to catch up from the past few weeks.

**Comment by tachyonlabs** [comment]
@kazk Thanks for the update! It's not exactly super-urgent -- just frustrating, not fatal.

**Comment by tachyonlabs** [comment]
I just made another attempt at resubscribing, using one of the same credit cards that I had tried with yesterday, and this time it worked just fine, and so my Codewars Red is back!

**Comment by jhoffner** [comment]
Thanks for all of the info @tachyonlabs. Codewars doesn't have a full dunning process setup - which is the process used when trying to get new information for canceled/expired credit cards. 

Stripe does have a process of automatically retrying cards, and our system is setup to receive a notification once the card gets successfully processed. I don't think it should be possible to accidentally start two concurrent subscriptions - so I don't think you are at risk of being double charged.

I'm going to close for now. Let me know if I'm missing anything that should constitute me leaving this open as an issue.
