### ISSUE TITLE
Server 500 error: language cannot be blank (actual = nil)

### ISSUE THREAD

**Issue by chyld** [Codewars/codewars.com#1262]
The following person is listed as an ally. When I click that ally, I receive a 500 error, with the error message `language cannot be blank (actual = nil)`.

https://www.codewars.com/users/kfarias

**Comment by DanielRuf** [comment]
Still getting this error when I try to open my profile page.

**Comment by kazk** [comment]
Looks like this happens when the user has not completed any kata.
@DanielRuf can you try solving one (maybe https://www.codewars.com/kata/multiply) and let me know if you can open your profile after that?

**Comment by DanielRuf** [comment]
Seems to work then. So there has to be a check for `null` / undefined.

**Comment by kazk** [comment]
Thanks for confirming.

**Comment by kazk** [comment]
Fix was deployed.
