### ISSUE TITLE
Couldn't unlink Github account. Got 500 error code

### ISSUE THREAD

**Issue by gleb-kosteiko** [Codewars/codewars.com#1264]
When I tried to unlink Github account in my settings I got error like on screenshot bellow. I was able to reproduce it few times.
![image](https://user-images.githubusercontent.com/15192983/34351931-9e1512cc-ea30-11e7-9b97-29cf434d412e.png)

**Comment by gnarmedia** [comment]
I have the same issue, any ideas?

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there with your account information.
