### ISSUE TITLE
Cannot access the codewars website at all!!!!!!!!!

### ISSUE THREAD

**Issue by thecoolster** [Codewars/codewars.com#1265]
Error Message:
Web server is returning an unknown error
There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.
Ray ID: 3d44cf900f8e8046
Your IP address: 
Error reference number: 520
Cloudflare Location: Cape Town

URL at the time:(signing in to GitHub)
https://www.codewars.com/users/auth/github/callback?code=dd208e26375cef2fac79&state=ea4054312fe5f795934037f795c3985272010d0365397eab

cannot access the website and I went to this codewars status website: https://codewars.statuspage.io/
all systems seemed operational.

**Comment by RiccardoMaltese** [comment]
Same exact issue here.

_Web server is returning an unknown error
There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.
Ray ID: 3d4502fb68903e5c
Your IP address: 
Error reference number: 520
Cloudflare Location: Zurich_

Maybe it is related to the Git Hub sign in.

https://www.codewars.com/users/auth/github/callback?code=17cb0a816b52000b908b&state=ea4054312fe5f795934037f795c3985272010d0365397eab

**Comment by thecoolster** [comment]
@RiccardoMaltese I would have thought that but the whole website for me is down. Other websites are working fine. Even the login page says that the website is down for me. :(

**Comment by nikolaysalinder** [comment]
I have the same problem 
Bad gateway
The web server reported a bad gateway error.

Ray ID: 3d455fd84c838607
Your IP address: 94.50.55.254
Error reference number: 502
Cloudflare Location: Stockholm

**Comment by jhoffner** [comment]
Is this still an issue? I notice that everyone reporting is from non-US regions. The site loads fine for me. It may have either corrected itself or perhaps its some sort of CDN/Cloudflare edge issue.

**Comment by nikolaysalinder** [comment]
Now working. Thx

**Comment by RiccardoMaltese** [comment]
Working fine now!
