### ISSUE TITLE
Translation impossible when the original language of a kata has been deleted

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1268]
Hi,

Problem identified with [this kata](https://www.codewars.com/kata/unusual-lex-order/translations) (thanks to @Chrono79 ) and I just reproduced it with [this one](https://www.codewars.com/kata/5a4c0813880385f0740000aa)

Symptoms:

* creation of the kata in one language
* kata published
* translation in another language published
* deletion of the original one
* then, the page used to [add the translation works](https://www.codewars.com/kata/test-kata-creation-for-github-report-only-do-not-try-it/translations), but it isn't possible anymore to actually __make__ the translations (the `translate this kata` button leads to:

```
Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `name' for nil:NilClass
```

Note : the problem fixes itself if someone recreates the original version directly in the edit panel of the kata.

cheers,
B4B

**Comment by g964** [comment]
As far as I know there never was a deleted translation for this kata.

**Comment by FArekkusu** [comment]
It doesn't have to be the original. Writing a translation and deleting it through the kata editor leads to the same problem.

**Comment by kazk** [comment]
Fixed
