### ISSUE TITLE
I can't access codewars.com at all 

### ISSUE THREAD

**Issue by fincat** [Codewars/codewars.com#1269]
I can't open the website, my tab closes every time reposting bug on every browser I have. 
The tab crashes in chrome, webdev version of Firefox, and usual Firefox. I cannot sing up, I cannot log in with my github account - any ideas why? This is happening for over week now. i tried restarting computer, restarting browser, clearing memory and cookies. launching tab in incognito mode, and restoring browsers to their default settings nothing helps 🤔 Any idea what can I do? I tried to report it in codewars Facebook but they simply ignored me.

![codewars](https://user-images.githubusercontent.com/34064398/34573684-3a6cd394-f175-11e7-9057-f73e20e6e6f1.jpg)

**Comment by kazk** [comment]
Are you using Windows? There're some issues reported by Windows users: #1157, #1254

**Comment by fincat** [comment]
yes I have win 8,1. thank you for pointing me in right direction :)

**Comment by kazk** [comment]
Closing as duplicate of #1157

**Comment by N-Garcia** [comment]
On windows 8.1 I got the problem solved installing this UpDate (and I hate Win Updates first time it really helped):

December 12, 2017—KB4054519 (Monthly Rollup)
Applies to: Windows 8.1Windows Server 2012 R2 Standard
Improvements and fixes
This security update includes improvements and fixes that were a part of update KB4050946 (released November 27, 2017) and addresses the following issues:

Addresses issue where users of SQL Server Reporting Services may not be able to use the scrollbar in a drop-down list.

Addresses additional issues with updated time zone information.

Security updates to the Microsoft Scripting Engine and Windows Server.
For more information about the resolved security vulnerabilities, see the Security Update Guide.

Thank you!!
