### ISSUE TITLE
UI hints for completed languages in language dropdown of a kata

### ISSUE THREAD

**Issue by Unihedro** [codewars/codewars.com#1272]
As a request, it would be massively helpful to display more hints with regards to which languages of a kata I have solved. It is frequent where I am grinding easier puzzles and I would like to repeat it for every language on it I know (which often happens to be all of them) but there's no indication to which I've already done so it's difficult to find the next.

A color highlight like a green box instead of the grey in dropdown for instance would already be great.

**Comment by kazk** [comment]
Related: #1162 (similar UI idea, not complete duplicate), #790 (search)
