### ISSUE TITLE
Why site is so slow?

### ISSUE THREAD

**Issue by Silwest** [Codewars/codewars.com#1274]
Guys,

From couple of days site is extremely slow... I cannot submit any solution coz it take more time then app is able to handle ;/

**Comment by Silwest** [comment]
What is more can't even "follow" exercise to have it completed later on:
ApplicationController::ResourceNotFoundError

**Comment by jhoffner** [comment]
My worry is that the underlying patches used for Meltdown/Spectre have slowed our servers or related 3rd party services down. The timeline you give (a coupon of days) would coincide with around the time the patches were applied. 

What are the repo steps for the `ApplicationController::ResourceNotFoundError` error?

**Comment by Silwest** [comment]
It's simple... When you cannot complete given task due to mentioned problems you want to bookmark it to be resolved later on however then the problem occurs.

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.

**Comment by shahul01** [comment]
Its still slow I am trying other competitive programming website, 1 person doesnt count but its too slow so many of them would also find other site
shame bcos it has good community

**Comment by Asadbek-Khudayberganov** [comment]
I can't submit my solution

**Comment by kazk** [comment]
Please open a new issue using the template to provide details.
