### ISSUE TITLE
Error 500 when running sample tests or submitting Kata attempt

### ISSUE THREAD

**Issue by stevemandl** [Codewars/codewars.com#1275]
The issue happens with multiple katas: squareFreePart and findNextSquare to name a couple. I have retried many times on various katas.

Here is the error I am getting:
Server Execution Error:
The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
Request Error:
Request failed with status code 500
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by wadie** [comment]
This has been happening a lot lately. Codewars isn't what it used to be anymore..

**Comment by jfeingoldlink** [comment]
I am also having this issue.

**Comment by jhoffner** [comment]
The public servers sometimes get backed up due to high demand. If you want consistent performance, CW Red will give you that.

**Comment by wadie** [comment]
So I have to pay in order to get consistent performance ?

Thanks, but I'll pass. there are many other alternatives. :+1:

**Comment by romerojp** [comment]
I got CW red, still getting the 500's though.. :(

**Comment by jcunningham77** [comment]
I'm consistently getting this error on Kata:
how-many-numbers-iii

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.
