### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by DPATR** [Codewars/codewars.com#1277]
I have been getting this error consistently this afternoon and unable to submit any tests.  I am working on Kata 7kyu.

However, all users across different levels are having the same problem this week.

Please resolve this!

**Comment by kazk** [comment]
We've [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336). It should be more stable and have much better performance, especially for free users.
Please open a new issue if you're still experiencing issues.
