### ISSUE TITLE
Rank is not increasing.

### ISSUE THREAD

**Issue by Richard-Thompson** [Codewars/codewars.com#1285]
I have been completing katas level 7,6,5 for practice and my overall score hasn't been increasing. i think this is a bug. Please find a link to my [profile page](https://www.codewars.com/users/RichardPT).

Initially it increased by 10 i think after a few days but now it isn't increasing at all.

If you need anything else please let me know.

**Comment by Voileexperiments** [comment]
https://www.codewars.com/users/RichardPT/site-events

You're only missing 6 honor, which comes from the "yellow code challenge completed".

I think it should be recovered once you complete another yellow kata.

**Comment by Richard-Thompson** [comment]
Ok no problem, I wasn't sure if there was a bug or not. Thanks for your help.

**Comment by DanL12186** [comment]
Typically you can get it to update by doing anything that increases points.. including ranking the kata you just completed.

**Comment by anter69** [comment]
@Richard-Thompson If the problem does not reappear, you may close this issue.
