### ISSUE TITLE
Can't see completed solutions

### ISSUE THREAD

**Issue by terrifictor100** [Codewars/codewars.com#1286]
Hello
I want to see a list of my completed solutions so I can share them, but when I click on solutions I keep getting an error 500 message.
Thanks

**Comment by docgunthrop** [comment]
Looks like the Completed Solutions page is still showing an error 500 message with the following:

```
undefined method `code_challenge_review' for nil:NilClass
```

**Comment by docgunthrop** [comment]
Working on my end now.

**Comment by kazk** [comment]
This should be fixed. See #1013 and #1627.

Please let me know if this is still happening.
