### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by DuongNguyen3c13** [Codewars/codewars.com#1288]
Have encountered this problem for about 3 days so I think I'd better ask. This happened with every kata, both when I run sample test or attempt to submit. I've tried with different PCs, and different OSs but it persists:
Output:
Time: 0ms
Request Error:
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by txxia** [comment]
I'm getting the same error for a few days, couldn't attempt some of the katas.

**Comment by txxia** [comment]
This is what I got, in case it helps:
![image](https://user-images.githubusercontent.com/8399710/35475653-353fcfb8-0370-11e8-8f79-bc41691ed6d2.png)

**Comment by anter69** [comment]
@kazk I believe the issue can be closed

**Comment by kazk** [comment]
Thanks @anter69
