### ISSUE TITLE
Go has disappeared

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1290]
https://www.codewars.com/kata/perimeter-of-squares-in-a-rectangle/train/go

When I edit the kata, the Go translation is there but when you want to try it all panels are blank!

**Comment by kazk** [comment]
I think this is because the language version is set to 1.7.x which doesn't exist.


![image](https://user-images.githubusercontent.com/639336/38978014-f394be80-436a-11e8-9f2c-3d74d5c4f574.png)

I'll try updating and see if that resolve this.

**Comment by kazk** [comment]
The original issue is resolved now.

But I see this message :/
> Caution: This kata does not currently have any known supported versions for Go. It may not be completable due to dependencies on out-dated libraries/language versions.

**Comment by Voileexperiments** [comment]
Did you republish the Go version with any changes in either author solution or text fixture so it triggers a re-validation?

**Comment by kazk** [comment]
I republished after adding a blank line and the message is gone :expressionless:
Thanks @Voileexperiments
