### ISSUE TITLE
Satisfaction rating is not calculated correctly

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1292]
See this new kata that has just been retired:

https://www.codewars.com/kata/easy-virtue/javascript

Currently there are 1 `very satisfied`, 1 `somewhat satisfied` and 2 `not satisfied` votes, which I voted for the last choice. However, the satisfaction rating is shown as `0% for 4`. If I change my vote to `somewhat satisfied`, then it becomes `50% of 4`.

And I tested the same thing on this kata:

https://www.codewars.com/kata/dp-edit-distance-part-2/javascript

With 1, 1 and 2 votes on 3 options, the result is 38%, correct as intended.

By the way, if the comment at [here](https://github.com/Codewars/codewars.com/issues/997#issuecomment-308317034) is correct the satisfaction rating should not drop to 0% or below, since everyone's vote has the same satisfaction power?

**Comment by kazk** [comment]
The fix was deployed and data was fixed.
