### ISSUE TITLE
Constant Timeout

### ISSUE THREAD

**Issue by iViscosity** [Codewars/codewars.com#1295]
[Kata Link](https://www.codewars.com/kata/next-smaller-number-with-the-same-digits/train/java)

I'm having issues, because when I run the attempt, it says I pass all the tests but it took longer than 20000 ms to complete. This is strange, because running the exact same test in Eclipse it's finished in 0.000s.
![image](https://user-images.githubusercontent.com/20390370/35467599-af965b3e-02de-11e8-9d7f-f216d8379308.png)

**Comment by kazk** [comment]
Are you getting this when you attempt? You shouldn't be able to run the exact same test locally because those are hidden from you.

> it says I pass all the tests 

The test result in the image says it passed 2 tests (there might be more) and timed out (`Errors: 1`).

**Comment by iViscosity** [comment]
I guess I should say I ran all the "sample tests" locally. This message I'm getting when I attempt, though, yes.

I honestly don't see a way this could be done faster...

**Comment by Voileexperiments** [comment]
Your code timeout because your code is too slow. This is not a kata issue or CW issue.

**Comment by iViscosity** [comment]
After looking through I realize that it is too slow which is why it's timing out, the only issue is I don't know how to make it faster. Thanks for the help, though.
