### ISSUE TITLE
CW leaderboard is showing deactivated profiles

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1296]
This is related to this kata:

https://www.codewars.com/kata/codewars-api/discuss

Some profiles that is showing on the leaderboard page is not accessible anymore (e.g [#223](https://www.codewars.com/users/Blue%20Leaf) and [#410](https://www.codewars.com/users/nedsociety)). Opening one gives `ApplicationController::ResourceNotFoundError`.

**Comment by Voileexperiments** [comment]
I just performed a scan through the 500 users on the leaderboards (using code from [this kata](https://www.codewars.com/kata/codewars-api), of course), and these are profiles that have been deactivated:

- [#133: rollietikes](https://www.codewars.com/users/rollietikes)
- [#141: del-this-account](https://www.codewars.com/users/del-this-account)
- [#253: Blue Leaf](https://www.codewars.com/users/Blue Leaf)
- [#446: MarcosDominguez](https://www.codewars.com/users/MarcosDominguez)
- [#449: nedsociety](https://www.codewars.com/users/nedsociety)

**Comment by kazk** [comment]
This should be fixed now. Banned users are removed from leaderboards.

**Comment by e-mihaylin** [comment]
https://www.codewars.com/users/del-this-account
3 kyu
Leaderboard Position:#4,812

Actual Leaderboard:
Overall:
#178 | 1 dan del-this-account
Completed Kata:
#116 | 1 dan del-this-account

So:
1) Not deleted from leaderboards
2) different user rank info (1 dan | 3 kyu)
3) different position info (4,812 | 178)

**Comment by e-mihaylin** [comment]
Reopen request

**Comment by kazk** [comment]
Fixed a bug that was preventing to remove banned users and removed all deactivated and banned users.
