### ISSUE TITLE
Got honor I shouldn't have

### ISSUE THREAD

**Issue by johandenerad** [codewars/codewars.com#1298]
I unlocked a solution for a kata I was struggling with, then entered one of the correct solutions as I thought it was functionally equivalent to mine. It worked and gave me a load of honor, which I shouldn't have since unlocking solutions should prevent gaining honor for the kata.

Is there a way I can delete the honor I got from this?

**Comment by DonaldKellett** [comment]
@johandenerad Thanks for being honest and honorable about this - this does indeed appear to be a very serious issue with the website and explains the recent influx of cheaters who were able to unfairly gain rank and honor very quickly without cheating the code runner in the first place (don't worry - all such cheaters have their rank and honor reset to `0` permanently once discovered).

@jhoffner @kazk You might *really* want to look into this one carefully - this seems to be a very serious issue and explains why there have been a large number of copycats lately.

**Comment by kazk** [comment]
I'm pretty sure this doesn't happen anymore.
