### ISSUE TITLE
Error citing problem in tests (not code under test)

### ISSUE THREAD

**Issue by ejohnso9** [Codewars/codewars.com#1299]
Trying to train this kata using Python 2.7.6:
https://www.codewars.com/kata/format-a-string-of-names-like-bart-lisa-and-maggie/train/python

When trying to run the sample tests, I am getting error feedback such as:

File "<string>", line 16
    Test.assert_equals(namelist([{'name': 'Bart'},{'name': 'Lisa'},{'name': 'Maggie'},{'name': 'Homer'},{'name': 'Marge'}]), 'Bart, Lisa, Maggie, Homer & Marge',
       ^
SyntaxError: invalid syntax

The file I am testing is only 8 lines long.
That's a complaint about your own test code, not my code.

Don't know if this has any relevance, but I was actually trying to re-do a kata that I had trained without logging in. (Which I wrote a successful solution for and passed all tests just like 10 min prior.) Now, logged in under my account I get the error above, but this must be a problem on your end?

**Comment by ejohnso9** [comment]
For the record, I see that the test code can be modified. However, I reset the kata, did not modify test code, re-pasted my solution, still got same error.

**Comment by ejohnso9** [comment]
Nevermind: this is only an issue in the inaccurate error output. The problem was in my code, but the error is pointing to test code.

**Comment by Voileexperiments** [comment]
For the record, if you have a problem with a specific kata, post in the kata's comment (and unless you can prove that it's the kata's fault, it's not an issue but a question). This repo is for CW-related things, not for specific katas.
