### ISSUE TITLE
Loading indicator never stops

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#13]
The loading indicator in Firefox never stops, regardless of the used operating system (Windows 7, 8, 8.1, Ubuntu 12.04 LTS, 14.04 LTS), except for some occurences (no reloadable elements, e.g. no comments, no solutions, no kumites, …), see attachement.

![issue](https://cloud.githubusercontent.com/assets/6301773/6890929/a6c6d3e8-d6b4-11e4-90ac-316c35c3716e.png)

**EDIT:** Also happens on kumites/kata editor.

**Comment by jhoffner** [comment]
Thanks. This is a pretty ugly bug. It might be caused by a 3rd party analytics library. I'll get some time to take a look hopefully at the end of this week.

**Comment by paul-calvelage** [comment]
I can't reproduce this with Firefox 46 on Windows 10 or Ubuntu 14.04.  Maybe this has been fixed already?
