### ISSUE TITLE
Cannot read old feature requests

### ISSUE THREAD

**Issue by bkaes** [Codewars/codewars.com#130]
I can't read feature-requests older than 3 months. At this point, the feature request forum is basically  worthless for me, as I can't refer to my benchmark and/or flagging request anymore.

@MMMAAANNN just posted #128, which was also handled in that request. 

OT: Should feature request get handled here or in the forums?

**Comment by jhoffner** [comment]
We are going to kill that forum at some point, at this point I would put what you consider high priority feature requests directly here. 

For the next few months at least we are still only going to be focusing on fixing high priority bugs/features and low hanging fruit. By we, I mean me, as the rest of the team is fully dedicated to another related product that we are getting close to completion on. Once we are able to dedicate resources back to CW full-time the plan is to rewrite the front-end and streamline the API. At that point, many of the issues will be cleaned out and we can develop much more rapidly on new features. 

In the meantime code execution service will continue to evolve on a more normal schedule as both services depend on it.

**Comment by bkaes** [comment]
If you still have access to the posts it's probably fine, I just wanted to avoid duplicates here and in the forums. I don't consider the benchmark or flag features "high priority", but something that would be valuable for Codewars.

**Comment by jhoffner** [comment]
I've setup a new ideas portal that has better community features: https://codewars.ideas.aha.io/

**Comment by bkaes** [comment]
Can you dump a list of the (non-resolved) comments somewhere? That way one could start the migration. Also, making feature-request read-only would help tremendously..

**Comment by bkaes** [comment]
Any update on making the feature request forum read-only? Or the dump of the comments?

I'm pretty sure that someone already asked for [MathJax](https://codewars.ideas.aha.io/ideas/CW-I-17) support in February, and that request is currently lost.
