### ISSUE TITLE
Kata revision page flattens all line indents

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1303]
For example, here is a very simple code:

![image](https://user-images.githubusercontent.com/14909989/36010421-5073e046-0d8c-11e8-923c-2d5c52a69f14.png)

In the revision page the diff for the above code is this:

![image](https://user-images.githubusercontent.com/14909989/36010590-2d5336b0-0d8d-11e8-8ebe-d077983787f6.png)

As seen above, all indents are flatted into 1 whitespace.

This is not a correct behaviour by any stretch: there are languages which care about indent (e.g Python and Haskell), and removing indents also messes with code formatting.

**Comment by kazk** [comment]
Fixed
