### ISSUE TITLE
Exit() cheat

### ISSUE THREAD

**Issue by Vokda** [Codewars/codewars.com#1305]
I was trying to solve the Playing on a chessboard kata when I stumbled upon a way to cheat the tests.
The tests could simply be passed by the code:
```
string game(int n)
{
    if(n == 0)
        return "[0]";
    else
        exit(1);
}
```
Obviously this should not be the case. 
The creator of the kata says all the tests are correct so there must be something else that is wrong. 
I have not tried if it works with other katas.

**Comment by DonaldKellett** [comment]
The "early exit" cheat is well known to the maintainers of CW and unfortunately there is no fool-proof way to prevent it from "passing" in every language.  **However**, there are background processes in place for detecting these cheats, and once detected, these cheat solutions are automatically "flagged" by the system and the maintainers of CW notified.  Upon review and confirmation (that it is a runner cheat), the user involved will lose honor and rank progress and repeat offenders will be permanently "banned" (i.e. their rank reset to `8 kyu / 0%` and their honor reset to `0` indefinitely which is final and irreversible).  Therefore, I would **strongly** advise against you trying out the same cheat against other Kata.

@kazk I think this Issue Report can be closed, cheers :smiley:

**Comment by Vokda** [comment]
Ah, ok. I understand. I just wanted to inform you of the cheat.
Thanks for informing me. I'll redo the Kata properly. :)
