### ISSUE TITLE
Run Samples and Attempts buttons bug

### ISSUE THREAD

**Issue by acd37** [Codewars/codewars.com#1307]
Hey folks @ Qualified,

I recently found that I couldn't get Run Samples Tests and Attempt buttons to show—turns out, it's a bug related to screen size. 

See video:
https://drive.google.com/file/d/1QacmJCL30Ro_-awIVW8RthfkpOdRgJsF/view?usp=sharing

**Comment by kazk** [comment]
This issue will be tracked on #1214
