### ISSUE TITLE
my Honor points have decreased

### ISSUE THREAD

**Issue by wiosen** [Codewars/codewars.com#1312]
After solving the last Kata the number of Honors points instead of increasing decreased by about 300, 
what is the point?

**Comment by wiosen** [comment]
when I solved the next two Katas, the number of Honor points returned to the previous state

**Comment by Unihedro** [comment]
http://shouldiblamecaching.com

**Comment by anter69** [comment]
@wiosen There is sometimes a delay between finishing a kata and updating the stats. These days there are (seemingly) some general problems (see #1329) already tracked, so you may close this issue (click "close" at the bottom).
