### ISSUE TITLE
Public Slack Channel

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#132]
The idea here is to use [Slackin](http://rauchg.com/slackin/) to easily setup a Slack channel that anyone can get access to. This would facility realtime discussion and replace a need for IRC. In additional to anyone being able to post, we can also forward all site comments (with preview and links) into the channel.

**Comment by bkaes** [comment]
How about using [Gitter](http://gitter.im) for the public chats? I don't use slack, so I don't really know how hard it is to create a channel correctly, but Gitter easily integrates GitHub auth and can be configured in about 3 minutes, see https://github.com/bkaes/codewars-rules for example. That's probably not a real alternative to slack, but something we could use till it's ready.

By the way, are there statistics how many users created an account via GitHub, and how many used email+password?

**Comment by andrewferk** [comment]
+1 for public chat. I'm down for either one. Personally, I only have experience with Slack and it's incredibly simple. Gitter looks just as simple and has full markdown support, which will probably be awesome. It would be nice if Gitter had a security page similar to (Slack's)[https://slack.com/security].

**Comment by bkaes** [comment]
@andrewferk Do you mean something like https://gitter.zendesk.com/hc/en-us/articles/200876472-Privacy-policy?

**Comment by andrewferk** [comment]
@bkaes yes, thank you.

**Comment by javatlacati** [comment]
This is an alternative to #170 ?

**Comment by bkaestner** [comment]
@javatlacati No. #170 asks to put a link to Gitter on Codewars, whereas this one asks for any kind of real time chat. Gitter filled that requirement roughly a year ago, so this issue can probably get closed.

**Comment by javatlacati** [comment]
was this solved?

**Comment by kazk** [comment]
> this one asks for any kind of real time chat. Gitter filled that requirement roughly a year ago, so this issue can probably get closed.
