### ISSUE TITLE
"Train now" button on collection not working

### ISSUE THREAD

**Issue by dideler** [Codewars/codewars.com#1320]
The *TRAIN NOW* button on a collection doesn't do anything. I'm logged in and trying it on this collection: https://www.codewars.com/collections/reactjs

![image](https://user-images.githubusercontent.com/497458/37087712-0e117b66-21f3-11e8-990c-4f530bb99e3f.png)

Browser info: http://whatsmybrowser.org/b/5FFLT5V

**Comment by dideler** [comment]
Clicking the button gives this error in the console.
```
raven.js:393 Uncaught TypeError: Cannot read property 'name' of undefined
    at h..js-train click (collections-744dc74734c2fdb2230ab6e4cf6f78d6.js:1)
    at HTMLAnchorElement.r (application-cb02b49fd8b1a20d33fd06bebbea9053.js:36)
    at HTMLDivElement.dispatch (application-cb02b49fd8b1a20d33fd06bebbea9053.js:15)
    at HTMLDivElement.m.handle (application-cb02b49fd8b1a20d33fd06bebbea9053.js:15)
    at HTMLDivElement.d (raven.js:389)
```

**Comment by zablotski** [comment]
Same issue,  
`Uncaught TypeError: Cannot read property 'name' of undefined
    at h..js-train click (collections-270a01689919d04d78ead3c2adc9d481.js:1)
    at HTMLAnchorElement.r (application-0aea47f788fba2c3bc21c3158b4338ba.js:28)
    at HTMLDivElement.dispatch (application-0aea47f788fba2c3bc21c3158b4338ba.js:2)
    at HTMLDivElement.m.handle (application-0aea47f788fba2c3bc21c3158b4338ba.js:2)
    at HTMLDivElement.d (raven.js:389)`
Tried on latest Chrome and IE

**Comment by Voileexperiments** [comment]
@kazk There's this in:

```js
            ".js-train click": function() {
                var e;
                return e = this.activeLanguage(),
                this.totalItems() === 1 || this.activeLanguageItems() === this.totalItems() ? this.trainNow(e.id, !1) : App.confirmModal.show({
                    titleHtml: "Which kata do you want to train on?",
                    messageHtml: "You prefer to train on " + e.name + ". Not all kata in this collection are available in that language. Which kata should we add to your training queue?",
                    confirmHtml: "" + e.name + " Kata Only",
                    cancelHtml: "All Kata",
                    confirm: function(t) {
                        return function() {
                            return t.trainNow(e.id, !0)
                        }
                    }(this),
                    cancel: function(t) {
                        return function() {
                            return t.trainNow(e.id, !1)
                        }
                    }(this)
                })
            }
```

(`this` is `App.controller`)

`App.controller.activeLanguage` is defined as

```
function() {
    var e;
    e = $("dd.is-active");
    if (e.length) return {
        id: e.data("language"),
        name: e.text()
    }
}
```

This is a *massive* WTF since it means collections has always been broken if user is not the owner of the collection. If user is owner of the collection:

![image](https://user-images.githubusercontent.com/14909989/54404875-d11e0d80-470f-11e9-8d75-e826004d3918.png)

`dd.active` comes from the language dropdown on the top left:

![image](https://user-images.githubusercontent.com/14909989/54404933-f6ab1700-470f-11e9-86b9-7a2c996c6f24.png)

If user is *not* owner of the collection:

![image](https://user-images.githubusercontent.com/14909989/54404901-e09d5680-470f-11e9-82e0-e6af6ad3e26d.png)

On the other hand, I'm not surprised collections feature is broken like this since it's pretty much like this from the beginning, and there are lots of other bugs in it as well. :trollface:

**Comment by kazk** [comment]
@Voileexperiments Thanks for looking into it.

> This is a massive WTF since it means collections has always been broken if user is not the owner of the collection.

It doesn't look like this is the case though. For Reactjs collection, I don't see the dropdown either, but I can see it on yours. Can yout try https://www.codewars.com/collections/prove-it ? Do you see the languages?

I think the dropdown is missing when there's only one language in the entire collection.

**Comment by Voileexperiments** [comment]
Yes I can see it:

![image](https://user-images.githubusercontent.com/14909989/54405559-fe6bbb00-4711-11e9-8c3b-fd08218574fc.png)

I looked at other random collections and found another one that doesn't have the dropdown, and indeed it has only 1 language (SQL): https://www.codewars.com/collections/sql-60

**Comment by kazk** [comment]
Thanks. I think I found it. It looks like a typo in the view template
```ruby
if languages.many? # more than one languages
```
should be
```ruby
if languages.any?
```

I don't think this condition is necessary to begin with because there has to be at least one language in a collection and also there's no `else` clause. `¯\_(ツ)_/¯`
This should fix the issue.

**Comment by kazk** [comment]
Deployed the fix
