### ISSUE TITLE
kata confusion

### ISSUE THREAD

**Issue by kelihansen** [Codewars/codewars.com#1321]
I had 60 kata, and I completed a yellow [challenge](https://www.codewars.com/kata/find-the-parity-outlier), which I though was worth 8. Now my total kata is displaying as 62, but my breakdown shows 40 + 20. Something isn't adding up.

**Comment by anter69** [comment]
By "kata" I believe you refer to "honor". Anyway, there may be a delay sometimes before the values is updated. If you find that the problem is solved and doesn't reappear, you may close this issue.

**Comment by kazk** [comment]
Closing as duplicate of #1329

**Comment by kelihansen** [comment]
Ugh, yes "honor". Apologies!
