### ISSUE TITLE
Page height on smaller screens.

### ISSUE THREAD

**Issue by mvirbicianskas** [Codewars/codewars.com#1322]
Hello, 

first of all, great work guys! It is such a pleasure to use your product! 

For some time now I noticed that on my mac 13" screen I cannot scroll down to the bottom of the page, see screen:
![image](https://user-images.githubusercontent.com/17020658/37251150-e57dba0c-2512-11e8-9e1f-244d104dba1b.png)

This happens on Chrome, FF and Safari, so I figure this is not something cross-browser related. One thing though - when you're logged out and preview a kata then the buttons appear correctly at the bottom maybe because these buttons appear only when you're logged in:
![image](https://user-images.githubusercontent.com/17020658/37251184-7ee74852-2513-11e8-9fea-b6f87a24c587.png)
Or most probably when these buttons breaks into two lines, then the increased height is not accounted for?
Hope that helps, let me know if you need any more details from me ✌️

**Comment by kazk** [comment]
This issue will be tracked on #1214

**Comment by mvirbicianskas** [comment]
thanks!
