### ISSUE TITLE
UI bug: `ATTEMPT` button dropped off

### ISSUE THREAD

**Issue by jaychsu** [Codewars/codewars.com#1324]
The `ATTEMPT` button dropped off if the browser window in certain width like capture below.

DROP OFF:

![image](https://user-images.githubusercontent.com/6890034/37326053-508979b2-26cb-11e8-8768-fa4ac7913c33.png)

WORK:

![image](https://user-images.githubusercontent.com/6890034/37326043-4235de14-26cb-11e8-994d-c966e25cfca8.png)

**Comment by anter69** [comment]
Same issue as #1322

**Comment by kazk** [comment]
This issue will be tracked on #1214
