### ISSUE TITLE
My solutions not showing in "Solutions section"

### ISSUE THREAD

**Issue by COLONELBIHI** [Codewars/codewars.com#1326]
Hi,
My solutions no longer show up in the "solutions" section even thought i complete katas.
When i click "Compare with my solution" it shows up but it doesnt show up in the solutions.
I have had this problem for 2 days now and have no idea how or why it happened.
Any help ?
Codewars username : COLONELBIHI

**Comment by luochen1990** [comment]
I have the same problem, for 2 days too. And my Honor is not updated during these two days, no matter how many kata I solve...

**Comment by plasticbottle** [comment]
Yep, I got the same problem for https://www.codewars.com/kata/597770e98b4b340e5b000071

It also didn't give any award for completion

**Comment by mcneal** [comment]
I'm facing the same problem: Honor and "My Solutions" don't get updated since yesterday.
Site-events page gets updated.

**Comment by Len512** [comment]
Same here. Neither My Solutions nor Honour are updated.

**Comment by anter69** [comment]
+1

**Comment by luochen1990** [comment]
[Here](https://gist.github.com/luochen1990/c99e51ee8b7233b0d9fef00402f33b66) is a script to prove that I indeed should got more honor in kata-solving than I current have.

**Comment by razvan-panda** [comment]
Same for me: my solutions and honor are not updated since yesterday.
The honor does still change here when solving a solution though: https://www.codewars.com/users/freeman42x/site-events

**Comment by struesdell** [comment]
+1, this is also happening to me.

**Comment by Len512** [comment]
Seems like it's fixed 🎆

**Comment by anter69** [comment]
@kazk I think this is also fixed now.

**Comment by kazk** [comment]
The issue with background processing queue is resolved now (#1329) and I'm assuming this is also fixed. Feel free to let me know if it's not.

**Comment by COLONELBIHI** [comment]
Thanks, it is indeed fixed for now.
