### ISSUE TITLE
Stats stopped updating

### ISSUE THREAD

**Issue by didier91380** [Codewars/codewars.com#1329]
My stats stopped updating for some time now. My user name is didierj.

**Comment by anter69** [comment]
Same issues: #1326 #1330

**Comment by kazk** [comment]
This was caused by the queue for the background jobs being backed up. I've let @jhoffner know about this yesterday and he increased the number of servers processing the jobs. It may take some time to catch up.

**Comment by kazk** [comment]
Closing this as the queue is no longer backed up.
