### ISSUE TITLE
Honor & Total Completed Kata dont updates

### ISSUE THREAD

**Issue by Srjkaa** [Codewars/codewars.com#1330]
Few days ago my stats on codewars stoped to updates. In "Kata" & "Solutions" branches i have smthing about ~154 completed kata, but on main page of my profile have 146 and see how after solution another one kata my honor dont updates. Sorry for bad english but i hope u will understand and help me. Thanks!
Codewars name: srjkaa-

**Comment by kazk** [comment]
Closing as duplicate of #1329
