### ISSUE TITLE
Update rust compiler

### ISSUE THREAD

**Issue by AdamSzopa** [Codewars/codewars.com#1334]
The rust compiler version is quite behind the times: 1.15.1 vs. the current 1.24.1.

A lot of katas depend on text manipulation, and newer version of rust added a lot of helpful methods like: https://doc.rust-lang.org/std/primitive.str.html#method.repeat in 1.16, or:
https://doc.rust-lang.org/std/primitive.str.html#method.to_ascii_uppercase for dealing with upper/lowercase ascii added in 1.23.

Some of the added functionality really makes a difference between a nice, quick kata session and a frustrating experience.

**Comment by kazk** [comment]
See https://github.com/Codewars/codewars-runner-cli/issues/556

The new runner has 1.23, but I'll look into upgrading that to 1.24.
