### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by gtodd876** [Codewars/codewars.com#1335]
Server error while submitting solutions to katas as well as trying to view my previous solutions on my profile page.

![screen shot 2018-03-21 at 6 54 15 pm](https://user-images.githubusercontent.com/28220658/37742029-460bce02-2d3a-11e8-9d79-a9bed6c30b91.png)

![screen shot 2018-03-21 at 7 02 23 pm](https://user-images.githubusercontent.com/28220658/37742070-6ed15a46-2d3a-11e8-9289-be26e8034ccf.png)

**Comment by anter69** [comment]
Same as #1332 so you may close the issue...
