### ISSUE TITLE
Ruby kumite is broken: uninitialized constant Test

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1344]
Well, I didn't really do much, just trying to run Ruby with the default kumite template:

```
# TODO: Replace examples and use TDD development by writing your own tests
# These are some of the methods available:
#   Test.expect(boolean, [optional] message)
#   Test.assert_equals(actual, expected, [optional] message)
#   Test.assert_not_equals(actual, expected, [optional] message)

describe "Solution" do
  it "should test for something" do
    Test.assert_equals("actual", "expected", "This is just an example of how you can write your own TDD tests")
  end
end
```

and it gives `uninitialized constant Test`. Is it something related to the new runner?

**Comment by kazk** [comment]
Do you have Codewars selected for test framework? Having RSpec will throw that error.

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/37955170-b6d8e662-315c-11e8-8eda-3a574b2693ad.png)

**Comment by Voileexperiments** [comment]
Okay, so I managed to figure out what that happened: I select shell before selected Ruby, and so the framework choice goes like:

`Codewars` (JS) -> `Ruby/Rspec` (shell) -> `RSpec 3` (Ruby)

But of course, if you don't choose shell in the process it goes like

`Codewars` (JS) -> `Codewars` (Ruby)

I guess this is some kind of issue?

**Comment by kazk** [comment]
I guess. Consistent default will be better. But I'm going to close this one because the original issue is invalid. Feel free to open a new one for that.
