### ISSUE TITLE
Kata publish validation now always uses non-Red clusters

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1348]
This is a follow-up to #1047 and #1343.

I was trying to figure out why re-publishing changes at the Ruby version of https://www.codewars.com/kata/faberge-easter-eggs-crush-test-linear always timeouts. As it turns out, again, Red users gets a constant 6-8s submit while non-Red users timeouts very frequently (and spends a very long time waiting for a docker container in general). And the only time it managed to be submitted, it invalidated every other solution because presumably they're run on the non-Red clusters, hence all choked by the congestion.

I don't recall this happening before (I've tweaked that kata many times to add anti-cheats) so it should be a relatively recent change.

So this means:
- Red users may get validation timeouts that shouldn't really happen (because the test runs fine in the editor on their end)
- Red users wouldn't know what the kata feels like to non-Red users unless they uses a non-Red account somewhere else and run the tests

**Comment by kazk** [comment]
This shouldn't be happening anymore.
