### ISSUE TITLE
I have Server Execution Errors and Request Errors all the time. 'The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.'  This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

### ISSUE THREAD

**Issue by KLFar** [Codewars/codewars.com#1349]
A few things to check first:

Is the issue you are filing related to a specific kata?

If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Is the issue you are filing related to how a specific language behaves when being executed?

If so then it will likely be better to file the issue on our [github.com/Codewars/codewars-runner-cli/issues](https://github.com/Codewars/codewars-runner-cli/issues) repo, which is where we have our open source code execution functionality. You also may want to look into forking that repo and fixing the issue yourself if you have the means.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.

**Comment by kittyj27** [comment]
I've had this today too, all day

**Comment by kazk** [comment]
Closing this because the outage is resolved now. Sorry for the inconvenience.
