### ISSUE TITLE
MemoryError when I am trying to execute several katas like this: "Count Odd Numbers below n"

### ISSUE THREAD

**Issue by viktor-palchyk** [Codewars/codewars.com#1352]
When I launch my solution, I receive the **MemoryError**.
It happened not only for this Kata.
<img width="951" alt="screen shot 2018-03-28 at 7 23 43 pm" src="https://user-images.githubusercontent.com/4864366/38042843-1751fa62-32be-11e8-9fd6-17dc318ad7cf.png">

**Comment by Voileexperiments** [comment]
Yes because test input has huge n. It's your code's problem, not kata issue (and not even site issue, so you shouldn't be raising an issue here in the first place ;-))

@kazk please close this issue ;-)

**Comment by kazk** [comment]
@viktor-palchyk as @Voileexperiments wrote above, `n` can be huge. Try to solve it differently, without testing all numbers below `n`.

**Comment by viktor-palchyk** [comment]
Okay, thank you for quick answer.
