### ISSUE TITLE
`users/notifications/unread_popups` endpoint takes too long to load

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1354]
I was looking at the network tab for different CW pages, and I noticed this:

![image](https://user-images.githubusercontent.com/14909989/38267883-496d2d78-37af-11e8-8836-cb6cf4c6cb2c.png)

For some reasons the `users/notifications/unread_popups` endpoint takes a long time to load (often even longer than the page itself), and it's also highly dependent on the page you're visited at:

- Dashboard: 0.5s
- Individual solution page: ~2s
- Kata list page: ~10s

**Comment by Voileexperiments** [comment]
The problem: because everything else is blocked until this request is finished, it causes bottleneck in page loading, especially in places where this matter the most (kata list and discourse section).

**Comment by jhoffner** [comment]
While trying to fix the latest server performance issues, I was able to speed this up as well. Shouldn't be an issue anymore.
