### ISSUE TITLE
Test and Submit buttons not displaying correctly on Chromebook

### ISSUE THREAD

**Issue by hammerthyme** [Codewars/codewars.com#1360]
About 70% of the time, my katas do not display the Test or Submit buttons properly - as seen in the attached photo. Usually I can still click the very top of the button (the sliver that is just barely visible), but occasionally even that doesn't work. The remaining 30% of the time, the buttons display as intended. I have logged into my account from a Mac with a Chrome browser and haven't encountered this problem.

I am using an Asus C100P Chromebook - Chrome OS Version 65.0.3325.184
Browsing on Google Chrome Version 65.0.3325.184

I really dig Code Wars so would love to have full functionality! Thanks and keep up the great work! 

![screenshot 2018-04-04 at 21 14 47](https://user-images.githubusercontent.com/35373008/38330612-5a9c822c-3851-11e8-8282-4919bd33e065.png)

**Comment by kazk** [comment]
Closing as duplicate of #1214
