### ISSUE TITLE
Just a normal login... undefined method `uid' for nil:NilClass

### ISSUE THREAD

**Issue by kylebakerio** [Codewars/codewars.com#1361]
codewars.com

github login

do login

wrong password twice, then correct

do 2-factor authentication

get forwarded to site, and see

`undefined method `uid' for nil:NilClass`
and a message about an error happening, being reported, and a request to post here.

So, cheers. :)

**Comment by finetype** [comment]
btw, then tried to go to site--it redirected me to login page again. But then I clicked the github login button, and was instantly transported to my working home page....

**Comment by kazk** [comment]
Closing because I believe this is fixed now. If this is still happening, please open a new issue with your account information.
