### ISSUE TITLE
Republish always fails

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1362]
I'm trying to fix a few existing katas, but they all seem to give this when trying to republish:

![image](https://user-images.githubusercontent.com/14909989/38347427-05f6cf5c-38ce-11e8-8cae-e5ce90c1792d.png)

Even though the tests work perfectly fine on both Red and non-Red.

I tested on at least 2 katas of different languages (Python and Java).

**Comment by kazk** [comment]
Yeah, I got this when trying to add Python 3 to some kata. I also found Python 3.6 sometimes sets version to numeric `3.6` instead of `"3.6"`.

**Comment by anter69** [comment]
I had the same issue today, but switching to the preview server helped.

**Comment by Voileexperiments** [comment]
Apparently preview site is now giving the same issue as well.
