### ISSUE TITLE
"Your clock is behind"

### ISSUE THREAD

**Issue by randomd00d** [Codewars/codewars.com#1363]
I received this message when trying to access the site. Why is this relevant? Does any of the backup code rely on the correct time and date?

**Comment by anter69** [comment]
Is this a warning from CW or your browser?

**Comment by sahilbabbar** [comment]
It is a standard message from Chrome(or any other browser) that you are using. Nothing to do with codewars website.

**Comment by kazk** [comment]
See https://support.google.com/chrome/answer/6098869?hl=en#clock
