### ISSUE TITLE
Default code to imperatively add to all python test cases for kata involving unicodes

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1368]
Hi,

Since the deployment of Bubbler's new framework, some old katas are broken because this line has to be add at the beginning of the test cases part (possibly needed at the beginning of the sample tests too? If unicodes involved)

`# -*- coding: utf-8 -*-`

(Note: I just saw kazk's comment in the "strip comment" kata, but it seems his update didn't work, yesterday)

This line should be added in the default template for translations/kata creation.

Cheers,
B4B

**Comment by kazk** [comment]
Adding `# -*- coding: utf-8 -*-` to any section that uses non-ASCII characters will fix this. I just fixed the "strip comment" kata.

I'm not adding them by default because it might change the behavior.

> For Python 2, an important reason for using non-UTF-8 encodings was that byte string literals would be in the source encoding at run-time, allowing then to output them to a file or render them to the user as-is. With Python 3, all strings will be Unicode strings, so the original encoding of the source will have no impact at run-time.
> https://www.python.org/dev/peps/pep-3120/

I don't know how those used to work on Python 2. As far as I know, it's required. The old runner didn't support the magic comment either because those needs to be in first line and the old runner prepended boilerplate code before preloaded code.

**Comment by kazk** [comment]
These are known to have this issue and I'm going to fix them today.

- [Approximate  Fractions](https://codewars.com/kata/56797325703d8b34a4000014)
- [Are there doubles?](https://codewars.com/kata/56a24b4d9f3671584d000039)
- [Caesar Cipher](https://codewars.com/kata/54b594b6fab5e97c28000f3f)
- [Conway's Game of Life](https://codewars.com/kata/525fbff0594da0665c0003a3)
- [Conway's Game of Life  - Unlimited Edition](https://codewars.com/kata/52423db9add6f6fc39000354)
- [Count words](https://codewars.com/kata/56b3b27cadd4ad275500000c)
- [Domain name validator](https://codewars.com/kata/5893933e1a88084be10001a3)
- [First Variation on Caesar Cipher](https://codewars.com/kata/5508249a98b3234f420000fb)
- [Gray Code](https://codewars.com/kata/5416ce834c2460b4d300042d)
- [Hëävÿ Mëtäl Ümläüts](https://codewars.com/kata/57d4e99bec16701a67000033)
- [Hungarian Cardinal Numerals](https://codewars.com/kata/58008f9897917feeec000a3e)
- [Hungarian Vowel Harmony (easy)](https://codewars.com/kata/57fd696e26b06857eb0011e7)
- [Hungarian Vowel Harmony (harder)](https://codewars.com/kata/57fe5b7108d102fede00137a)
- [Optimal Taxi Fare](https://codewars.com/kata/52f51502053125863c0009d7)
- [Random case](https://codewars.com/kata/57073869924f34185100036d)
- [Rule 30](https://codewars.com/kata/5581e52ac76ffdea700000c1)
- [Temperature converter](https://codewars.com/kata/54ce9497975ca65e1a0008c6)

**Comment by Blind4Basics** [comment]
> I'm not adding them by default because it might change the behavior.

But that should be present in the default template for new katas/translation, right? Or can you handle this on the server side?

**Comment by kazk** [comment]
Closing this because I've fixed them all. Please let me know if there's any that I've missed.
