### ISSUE TITLE
Kata attempt fails if Preloaded code is non-empty but will become empty after trimming

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1370]
How to reproduce the issue: Make a new kata. Put nothing but whitespaces and line breaks in Preloaded so it's not empty but becomes empty after trimming (e.g `'  \n  '.trim()` would become `''`). Then go to the trainer page (it won't work in the kata editor for reasons mentioned later), and try to attempt/run sample tests. This will happen:

![image](https://user-images.githubusercontent.com/14909989/38468033-3158deae-3b73-11e8-97bb-c6c0654889c3.png)

This happens in all languages.

The issue is that in the trainer page the setup and test fixtured code are supposedly encrypted before sent to the client, which is then decrypted at the runner server when user POST them along with their code. However the parts are not encrypted if they'd become empty after trimming. Now, in almost all cases nobody would populate the text fixture with that, but it's not strange for Preloaded code to be like that.

For example, with Preloaded code nothing but whitespaces and line breaks, the POST request to the server looks like this:

![image](https://user-images.githubusercontent.com/14909989/38468039-52d16a4c-3b73-11e8-9c70-c4b826676361.png)

Then I added a digit somewhere in the Preloaded code, and now it works properly:

![image](https://user-images.githubusercontent.com/14909989/38468043-66d93cb8-3b73-11e8-9f37-5f16b40cffe3.png)

Since both setup and test fixture code are not encrypted in the requests inside kata editor page (i.e `ciphered` is an empty array), kata editor doesn't exhibit this problem.

**Comment by DestyNova** [comment]
Nice analysis! :+1:

**Comment by kazk** [comment]
The fix is deployed.
