### ISSUE TITLE
Final Solution is invalid. (r) The solution should pass the provided test cases

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1375]
Kata: https://www.codewars.com/kata/54eb33e5bc1a25440d000891/edit/r

I "VALIDATE SOLUTION" but always get that Final solution is invalid.
Plus: In many languages it is impossible to only test "Example Test Cases". All tests are run.

Sorry: A bad click and I deleted the R translation:-(

**Comment by kazk** [comment]
> Sorry: A bad click and I deleted the R translation:-(

Is this it?
https://www.codewars.com/kumite/599419e7e8129e1427000001?sel=599419e7e8129e1427000001

**Comment by g964** [comment]
Yes

**Comment by kazk** [comment]
Sorry, what is the issue?
That translation gets "Final Solution is invalid. (r) The solution should pass the provided test cases"?

**Comment by g964** [comment]
The issue was that the solution was validated with "VALIDATE SOLUTION" but nevertheless it was impossible to publish it because of "Final Solution is invalid. (r) The solution should pass the provided test cases". Doesn't seem contradictory to you? 

Anyway , now it always give:
```
Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

undefined method `name' for nil:NilClass
```
which already happened with a few other kata. 

So, better to give up in these cases...

**Comment by kazk** [comment]
That's really odd. I can view that page without issues.

**Comment by kazk** [comment]
I don't know why this is happening, but I can copy the code into the kata editor for you.

**Comment by g964** [comment]
It already happens to me, eg:
<https://www.codewars.com/kata/56baeae7022c16dd7400086e/translation/new>
same thing. I already posted about that but I don't remember the #num.
Other people don't have error but I do have!

**Comment by kazk** [comment]
I just recovered R. Can you see it in kata editor?

> Other people don't have error but I do have!

Maybe you translated too many? :stuck_out_tongue:

**Comment by kazk** [comment]
Found the issue you opened before #1090. This might be related to #1268.

**Comment by kazk** [comment]
Can you see https://codewars.com/kumite/599419e7e8129e1427000001?sel=599419e7e8129e1427000001 now? #1268 says it gets fixed after someone else recreates the original in the editor.

**Comment by g964** [comment]
Yes I see it now

**Comment by kazk** [comment]
I'm going to close this because the original issue is resolved. Your other issue is most likely related to #1268.

**Comment by g964** [comment]
I am coming back to my first post:

Kata: https://www.codewars.com/kata/54eb33e5bc1a25440d000891/edit/r

I "VALIDATE SOLUTION" but always get that Final solution is invalid. How is it possible?

**Comment by g964** [comment]
The old solution can be republished but I wanted to modify the "testing" function so that different solutions can be accepted (the new "testing" function would simply verify that the resulting array is in strictly increasing order and that the sum of squares is equal to the square of the given number).
My new testing function:
```
testing <- function(n, expected) {
    actual <- decompose(n)
    cat("actual ", actual, "\n")
    if (all(actual == expected)) {
        success = 0
    } else {
        if (is.null(actual) & n != 0) {
            success = 1
        } else {
            success = 0
            unsrt <- is.unsorted(actual, na.rm = FALSE, strictly = TRUE)
            if (unsrt == TRUE) {
                cat("Result is not correctly ordered")
                success <- success + 1
            } else {
                t <- sum(actual^2) - n * n
                if (t != 0) {
                    cat("Bad sum of squares")
                    success <- success + 1
                }
            }
        }
    }
    expect_equal(success, 0)
}
```
I don't see any error in that function... and I can validate it but when I try to republish I always get:
"Initial Solution is invalid. (r) The code should not pass the kata test cases" whose meaning is mysterious for me.

**Comment by kazk** [comment]
So the error message is different from the original one. I completely missed that.

> "Initial Solution is invalid. (r) The code should **not** pass the kata test cases"

I think this is shown when "Initial Solution" passes the tests. This is not allowed because a user can just submit the given code. Make sure "Initial Solution" is incomplete and fails some tests.

**Comment by kazk** [comment]
That initial solution passes your new `testing`. I just tried on kumite.
Looks like `(all(actual == expected))` is `true` even when solution `return(NULL)`.

**Comment by kazk** [comment]
Maybe use `identical(actual, expected)`?

**Comment by kazk** [comment]
I don't know R much, but `cat(all(NULL == c(1, 2, 3)), "\n")` prints `TRUE`, so `all(actual == expected)` in the new `testing` is not doing what you intended.

**Comment by g964** [comment]
Same result:-(
With 
```
whatever <- function (n) {
  return c(0)
}
```
When in old "testing" or new "testing" I print "actual" and "expected" I get the same result as if I was running the "good" decompose function so - but I can be wrong - I think the tests are always running the complete solution. If they were running function "whatever" I should print c(0) ie "0" for "actual" and not the same as expected.

**Comment by kazk** [comment]
Same result with what?
Are you doing "VALIDATE SOLUTION" in Kata Editor? That **only** runs "Complete Solution" if I remember correctly.


The following will fail the initial solution.
```r
testing <- function(n, expected) {
    actual <- decompose(n)
    cat("actual ", actual, "\n")
    if (identical(actual, expected)) {
    # if (all(actual == expected)) { # always TRUE
        success = 0
    } else {
        if (is.null(actual) & n != 0) {
            success = 1
        } else {
            success = 0
            unsrt <- is.unsorted(actual, na.rm = FALSE, strictly = TRUE)
            if (unsrt == TRUE) {
                cat("Result is not correctly ordered")
                success <- success + 1
            } else {
                t <- sum(actual^2) - n * n
                if (t != 0) {
                    cat("Bad sum of squares")
                    success <- success + 1
                }
            }
        }
    }
    expect_equal(success, 0)
}
```

**Comment by g964** [comment]
> Are you doing "VALIDATE SOLUTION" in Kata Editor? That only runs "Complete Solution" if I remember correctly.
Yes I "VALIDATE" in the kata editor. 
I am not sure that here it only runs "Complete solution" (though it should) since I validate the "whatever function" too ...
It validates: `testing(50, c(1,3,5,8,490))` whereas the result should be ` c(1,3,5,8,49)`
I am afraid I will have to delete the R translation until I find something better!
Nevertheless I was able to republish it and we will see. Thank you so much again for your time!!!

**Comment by kazk** [comment]
When you **validate** in the kata editor, it

1. runs the "Complete Solution" with "Test Cases" to make sure it passes

It doesn't care about "Initial Solution" or "Example Test Cases" (I don't know why). So you it won't say "decompose" is not found.

When you **re-publish**, it
1. runs "Complete Solution" with "Test Cases" to make sure it passes
2. runs "Complete Solution" with "Example Test Cases" to make sure it passes
3. runs "Initial Solution" with "Test Cases" to make sure it fails

You were getting that "Initial Solution is invalid. (r) The code should not pass the kata test cases" because of 3.

The kata editor is really confusing and needs to be fixed eventually, but I hope my explanation is clear.
