### ISSUE TITLE
My honor just went from 479 to 79!

### ISSUE THREAD

**Issue by joebandenburg** [Codewars/codewars.com#138]
http://www.codewars.com/users/joebandenburg

I am rank 2 kyu, half way towards 1 kyu. I just completed a 4 kyu problem and upon completion my honor dropped by 400 points. Did I do something very dishonorable?

**Comment by joebandenburg** [comment]
In the "Allies" table on the home page my correct honor (493) is displayed along with my correct position in that table.

**Comment by adam-tokarski** [comment]
Maybe it was some g'glitch? Actually system shows that you have 493 honor points. Take look at http://www.codewars.com/users/joebandenburg/site-events.

**Comment by joebandenburg** [comment]
@adam-tokarski Good spot. It seems to have been an issue with my session. My honor is now displayed correctly after I signed out and back in again.

I'll leave this issue open as there is clearly a bug lurking somewhere.
