### ISSUE TITLE
Can no longer login into my account

### ISSUE THREAD

**Issue by vanilsonbr** [Codewars/codewars.com#1382]
Yesterday I joined CodeWars because I friend of mine said it is awesome to learn new languages and train algorithms.
I remember inserting my email (vanilson.nogueira@gmail.com), username (Unmei) and password. I remember all 3 of them.
Today, when I tried to login, it says my email does not exist! I tried countless times to login, but no luck.
Here's the account user I created yesterday: https://www.codewars.com/users/Unmei/
It is not linked to the GitHub.
Thing to notice: when I try to create another account with the same username, it says the username is already taken, but not the email.

Thanks

**Comment by winraar** [comment]
Update: I mashed my credentials into the form a few times and continued to get the 'incorrect username/password' error. However, after doing that for some time and navigating to my public profile, I saw that I was suddenly logged in. It was like even though I was entering correct credentials I was always given an incorrect error that the credentials weren't right but it logged me in anyway without redirecting me to the dashboard. 

Once I was in I tried to check my Account Settings, but I'm always redirected to [the sign in page](https://www.codewars.com/users/sign_in), and am met with the same ['incorrect email/password' errors](https://cl.ly/0f3g0W2c3Q1r) when I try to sign in there (but I'm not logged out in my previous tab or if I press back if it's the same tab). If I click on Training Settings from the previous menu, I get sent to [another 500 error page that indicates that one of your controllers is busted](https://cl.ly/0d1Y370q462Y). Yikes

**Comment by kazk** [comment]
@vanilsonbr sorry for the late response. I just checked the database and the email has a typo. You entered `gmai.com` when you signed up.
You should be able to login using that and change your email to the correct one.

@winraar the email associated with Codewars user named `winraar` ends with `@mailchimp.com`.

**Comment by leoferaderonugraha** [comment]
Hi, recently I can no longer login into my account with github. I tried to reset my password, but it says `not found`.
I tried to reset my password with email `leoferaderonugraha@gmail.com`

On github login error:

> Unknown GitHub user @leoferaderonugraha. Sign up or link your account first.


Here's the link to my profile:
https://www.codewars.com/users/leoferaderonugraha

**Comment by Exoticinurs** [comment]
Same problem as @leoferaderonugraha ... When I try to log in it says:

    Unknown GitHub user @Exoticinurs. Sign up or link your account first.

My account is named Exoticinurs tho..?

**Comment by hobovsky** [comment]
> Same problem as @leoferaderonugraha ... When I try to log in it says:
> 
> ```
> Unknown GitHub user @Exoticinurs. Sign up or link your account first.
> ```
> 
> My account is named Exoticinurs tho..?

I left you a couple of points to follow on Discord  where you initially asked for help, but I guess you missed my message.
