### ISSUE TITLE
[GitHub Wiki] Code Example at NASM docs contain misleading comments

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1384]
In [the code example for the NASM documentation](https://github.com/Codewars/codewars.com/wiki/Language-NASM#test-frameworks), the comments suggest that register `esi` corresponds to the first argument passed to the C function and `edi` the second but in reality the opposite is true.  I've confirmed this when playing with the ["Multiply" Kata in NASM](https://www.codewars.com/kata/multiply/nasm) and [the "Understanding Calling Conventions" section of this NASM tutorial](http://cs.lmu.edu/~ray/notes/nasmtutorial/) also confirms this.

**Comment by DonaldKellett** [comment]
Resolved

**Comment by kazk** [comment]
Thanks! I'll fix the example kata as well.
