### ISSUE TITLE
Haskell "validate solution" not working

### ISSUE THREAD

**Issue by KacperKorban** [Codewars/codewars.com#1386]
My user name is KacperKorban, i created a new kata, then wrote solution and test cases in Haskell. They weren't working, so i used the "insert example" button and realized that the template is not working too. It doesn't even show my descriptions. It just shows four lines: "Time: 1066ms", "Test Results:", "Tests" and "Completed in 0.0890ms". Other languages work just fine.

**Comment by kazk** [comment]
Do you have GHC 8.2 selected? The format have changed between 7.10.3 and 8.2. See [the docs](https://github.com/Codewars/codewars.com/wiki/Language-Haskell).

Your test should look something like this:

```haskell
module ExampleSpec where

import Test.Hspec
import Example

spec :: Spec
spec = do
    describe "add" $ do
        it "adds Nums" $ do
            (add 1 1) `shouldBe` (2 :: Integer)
```

I think the example inserted is for 7.10.

**Comment by kazk** [comment]
I'm going to close this, but feel free to let me know if you're still having trouble.

**Comment by KacperKorban** [comment]
Working now, Thanks :)
