### ISSUE TITLE
API often requires token reset

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#139]
[Copied from [here](https://github.com/Codewars/codewars-api-docs/issues/3)]
I have been experiencing some problems using the Codewars API key; it seems to expire after about an hour meaning that I cannot make any authenticated requests until I refresh my account settings page. Once refreshed, the API key remains exactly the same and the authenticated requests are successful.

**Comment by jhoffner** [comment]
I am deploying the fix for this now.

**Comment by nofootnotes** [comment]
That's great, thanks so much for this!
