### ISSUE TITLE
Trainer page rapidly switches between `layout: h` and `layout: v` if aspect ratio is smaller than 9:16

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1397]
How to reproduce: Resize the browser window at trainer page so that aspect ratio is below 9:16, or open a trainer page with most mobile phones.

There used to be a `layout: v` mode which puts the right panel (solution and example tests window) below the description panel. However during the course of #1214 (at least as far as I can remember) this bug is also introduced, so basically we're forced to request the desktop site (to disable aspect ratio checking) if we want to use the trainer page on mobile.

**Comment by kazk** [comment]
Fixed
