### ISSUE TITLE
Deleting an issue comment doesn't resolve the issue

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#14]
If one adds a issue (via comment), and then deletes the comment, the issue doesn't get resolved, see http://www.codewars.com/kata/last-digit-of-a-huge-number/discuss#55191fcacd82ff070f00078b. 

Luckily, I can still click on the unhappy smiley to remove my issue, but I'll leave it for now.

**Comment by jhoffner** [comment]
This isn't so much a bug but more a redesign that is needed. Originally users were able to mark a kata as having an issue without commenting - the commenting feature was tacked on after the fact. Its a very good point though and I will look into trying to refactor how the issue tracking works. This is likely going to remain a low priority for the time being though.

**Comment by kazk** [comment]
@bkaestner Is this resolved now? Commenting with "Issue" label doesn't automatically set satisfaction vote to unsatisfied anymore, see #716.
