### ISSUE TITLE
Consecutive strings

### ISSUE THREAD

**Issue by titilomt** [Codewars/codewars.com#1401]
Sup Guys, in this problem we got a issue in the "in's" if i got the problem correctly we should print the n words that repeat in my strarr but the strarr in any case got anything repeating at all. Again if I'm missing something sorry 'bout that.

Ty all.

**Comment by Voileexperiments** [comment]
This is a kata issue, not site issue. Go post it in the kata comments.

In the meantime, you should also post it as a question and organize your sentence so someone else *actually* has chance to understand what you're talking about.

@kazk please close the issue ;-)
