### ISSUE TITLE
Mandatory use of HTTPS (SSL) on CW

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1405]
Currently both http://www.codewars.com and https://www.codewars.com are valid and perfectly usable.

Since it's already 2018, shouldn't we mandate the use of HTTPS and not HTTP?

**Comment by kazk** [comment]
> There is an issue with this not working on http. We don't force https on all pages due to some users having issues with iframes with the kata editor. For now the workaround should be to use https.
> https://github.com/Codewars/codewars.com/issues/552#issuecomment-243616335

The comment is from August 2016 so maybe it's fixed?

**Comment by Voileexperiments** [comment]
@kazk By the way, IIRC the only people who has used iframe was myjinxin2015 to implement a kata series list lookup (T.T.T. series) widget and to embed the non-golf version of a kata in the golf version.

**Comment by kazk** [comment]
I've made Codewars always use HTTPS. I'll revert it if we have any issues increased.
