### ISSUE TITLE
Can't republish Scala version of https://www.codewars.com/kata/bagels

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1407]
I tried to republish the Scala version of https://www.codewars.com/kata/bagels for a few days already (to update the tests to new Scala code and also patch an obvious cheese), but I never have been able to republish successfully at all, and I've tried it for a few days already.

**Comment by kazk** [comment]
Can you try discarding local edits and try again? There was some issues with how backend was set up and it might be still using that.

**Comment by Voileexperiments** [comment]
Yes, it's always publish timeout.

**Comment by kazk** [comment]
> only the author solution should be valid

why?

**Comment by Voileexperiments** [comment]
Because that's how the original Java version works (and why it's `4kyu`, not `7/6kyu`): you can't just duck type the bagel and pass the test. There's a translation fork there 4 months ago that removes the cheese.

**Comment by kazk** [comment]
OK, I didn't know that those solution was supposed to be rejected.

**Comment by kazk** [comment]
> Then for the actual tests more code to handle the infinite loop problem is needed.

Can you elaborate on this? So you need something more than the test case you posted above?

Republishing runs

- complete solution with test cases
- complete solution with example test cases
- initial solution with test cases

So if example test is lacking the code to handle infinite loop, then republish will time out.

**Comment by Voileexperiments** [comment]
> So if example test is lacking the code to handle infinite loop, then republish will time out.

Oh, so that explains why it always times out.

The problem is this: reflection is needed to patch the boolean values back to what they should be, but the appearance of reflection code alone gives away the solution. So the sample tests needs to be set up to *not* reveal this part (which would lead to timeout, of course, but it's inevitable).

Anyways, I just republished with sample tests as same as the actual tests, then remove the relevant part in the sample tests (changing the sample test alone doesn't trigger re-validation). I'm not sure if this issue should be closed though.

**Comment by kazk** [comment]
Nice workaround. Thanks for you help!

**Comment by kazk** [comment]
I'm going to close this and open a new issue about increasing the timeout for publishing.

**Comment by Voileexperiments** [comment]
@kazk after a week I'm still unable to republish the Kotlin version.

**Comment by kazk** [comment]
How long does "validate solution" take?
If I remember correctly, the timeout is 50s and 3 combinations run sequentially (single background job, instead of 3 jobs). I also don't know how background jobs are scheduled.

**Comment by Voileexperiments** [comment]
Compilation takes ~10s. After that there's almost no computations in use code and tests anyway, so it should be ~10s per run.

**Comment by kazk** [comment]
Maybe the background job scheduling is getting in the way. Like pause ~10s pause ~10s pause ~10s.
I really don't know at the moment. I wish I knew more about Codewars internals.
