### ISSUE TITLE
Ranking of Solutions to Kata by runtime/memory consumption?

### ISSUE THREAD

**Issue by mukesh610** [Codewars/codewars.com#1409]
The title says it all, but to be more clear,

- Solutions to Kata must have new ranking categories (runtime, and memory consumption)
- We must be able to list solutions by *least runtime* and *least memory consumption* (This would help learners on best practices, in addition to the best practices upvote)
- The runtime and memory consumption may be calculated during submission of final solution to the Kata.

My reason for requesting this is that the existing best practices upvote counter seems flawed, as people seem to upvote inefficient one-liners as best practice, but tend to neglect long but efficient snippets.

**Comment by Voileexperiments** [comment]
> as people seem to upvote inefficient one-liners as best practice

If you're putting *that* as the premise of your argument than what you're suggesting is not going to lead to what you want to see, I'm afraid (#1390 and #1391). Code length, *actual* readability and efficiency are completely different metrics. Not to mention the most efficient code is often low-level cod e which is also hard to read (unless it's Haskell), so I'll happily take that as you're advocating for such code.

Also, this is a duplicate issue. e.g #777, #959
