### ISSUE TITLE
No notification/email on kata translation

### ISSUE THREAD

**Issue by bkaes** [Codewars/codewars.com#141]
I was pretty sure that there was already an issue for this, but apparently I was wrong.

A kata author doesn't get a notification if the kata gets translated. While translators get their "approval notification" (which is nice), the "translation approval pending" is far more important. 

Even better, provide a listing of all current pending approvals somewhere.

Currently, many [users](http://www.codewars.com/kata/558fa34727c2d274c10000ae/discuss#55ae43621d37d1302500007a) provide a comment to notify the author and link to the tutorial in the wiki. That's rather cumbersome.

**Comment by GiacomoSorbi** [comment]
Not sure if related, but I didn't get any notification at all in the past 1-2 days, then this morning I got them all with interests.

**Comment by bkaes** [comment]
@GiacomoSorbi Probably not, since the emails are the same as the notifications you get on the site itself. This issue addresses the missing notifications for translations in general. Maybe it's worth to create a new issue for that? 

(By the way, I also got two emails today in the morning instead of one yesterday and one today)

**Comment by GiacomoSorbi** [comment]
Ok, I will create a separate issue if this happens again: it could be just a planned stop&reactivate of the mail notifier.

**Comment by jhoffner** [comment]
I am deploying notifications updates now which should solve these issues.
