### ISSUE TITLE
Invalid javascript Version: "javascript" 

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1412]
> Javascript version doesn't get loaded while editing a translation, please see https://codewars.com/kumite/5adfc43a36257f285700000e/edit

>> Invalid javascript Version: "javascript"

The language version is set to "javascript".

https://github.com/Codewars/codewars-runner-cli/issues/606#issuecomment-384121961

**Comment by kazk** [comment]
Closing as duplicate of #1134.
