### ISSUE TITLE
How should quasi-duplicate JS katas concerning arrows get handled?

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#142]
The recent announcement of ES6 support and therefore arrow notation lead to a bunch of new katas like [Take an Arrow to the knee, Functionally](http://www.codewars.com/kata/559f3123e66a7204f000009f/discuss#55af4166b2c59b78cd0000f2). Those katas don't provide additional content compared to the one that didn't ask for arrows.

For example, the early versions of [Sum with Arrows](http://www.codewars.com/kata/sum-with-arrows/) could be solved with any solution of [Use reduce() to calculate the sum of the values in an array](http://www.codewars.com/kata/532b4057484b0e58e8000766), which made it clearly a duplicate. Matt has changed the kata so that one has to provide a string instead of a function, which kind of resolves this issue, but some other katas are basically duplicates.

Also, the "arrow" notation is mostly used as a shorthand lambda notation. It cannot get translated properly into other languages for the same reason it cannot get tested in JS properly: lambdas and functions are often indistinguishable. There's (almost) no difference between `sum = \a x -> a + x`, `sum = (+)` and `sum a x = a+ x` in Haskell or `sum = lambda x,y: x+y` and `def sum:…` in Python.

So, how should one handle the "use-an-arrow-to-solve-this-kata!" katas?

**Comment by GiacomoSorbi** [comment]
To be honest, at least in JS one could also use the .toString() method on a function and see if "=>" was used; cheatable because you could just put it into a comment, but still better than nothing (and if you are that decent to come up with such a plan to cheat the tester, you probably don't need it at all).

**Comment by bkaes** [comment]
> To be honest, at least in JS one could also use the .toString() method on a function and see if "=>" was used; 

You can't. Check the discussion in the linked kata "Sum of Arrows". The transpiler processes the source before it gets handed to node. Try it yourself:

```javascript
var test_func = arr => arr.map( a => a + 1)
console.log(test_func.toString())
// console output:
// function test_func(arr) {
//     return arr.map(function (a) {
//         return a + 1;
//     });
// }
```

**Comment by GiacomoSorbi** [comment]
Oh, didn't know about the priority of the transpiler as I tried with other mock functions: thanks for letting me know!

**Comment by kazk** [comment]
Closing old issue.
I believe users are now more strict about duplicates and doesn't allow kata like this to be approved anymore.
