### ISSUE TITLE
UX improvement request: check whether I'm logged in before I start a kata

### ISSUE THREAD

**Issue by gelisam** [Codewars/codewars.com#1424]
Due to a long-standing issue (#1), we sometimes get logged out while using the site. I understand that this is a difficult bug to fix, and so here is a mitigation which I think would help a lot in the mean time.

For the third time now, I have completed a kata, passed the local test, passed the final test, clicked "submit final"... and was directed to a page telling me that I "have not earned access to this kata's solution", because I am logged out. This is especially frustrating because my profile icon was visible during all that time, and so incorrectly assumed that I was still logged in.

Having this error occur after I have invested time solving a kata is the worst possible time at which this could occur. It would be much less infuriating if the error occurred before I started the kata. Since the error always occurs when I click on the "submit final" button, I'm pretty sure I was already logged out at the time I started the kata, I just didn't know it yet. So my UX improvement is: **when clicking on the "next kata" button, check if I am logged in**, and if not, ask me to log in or hide my profile picture from the top-right to let me know that I am no longer logged in. This way, I can log in before attempting the kata, no harm done.

A few notes about my workflow, in case it is relevant: I use github for authentication, and I work on katas from the same tab for about an hour every day. I stop after completing a kata, not in the middle of one. So my session probably expires during the night, and then on the next day I start the next kata and the UI incorrectly makes me think that I am still logged in. I will try to remember to refresh the page every morning from now on, but for the sake of other users, I think this small UX improvement might be quite welcome.

**Comment by Voileexperiments** [comment]
related(?): #1379

**Comment by kazk** [comment]
Closing because #1 is fixed. Checking if you're logged in before you start a kata didn't help much because it used to log you out while you're solving or when you submit for some unknown reason. This shouldn't be happening anymore. Please let me know if it is.
