### ISSUE TITLE
std::stable_partition doesn't work as expected 

### ISSUE THREAD

**Issue by seroza** [Codewars/codewars.com#1428]
language: c++

code:
    std::string someText("This is a test!");
    std::stable_partition(someText.begin(), someText.end(), [&](auto elem)
                  {
                      std::cout << elem;
                      return false;
                  });
    std::cout << std::endl;

expected output:
This is a test!

actual output:
T!tset a si sih

**Comment by kazk** [comment]
I don't think the iteration order is specified for. Clang 3.8 doesn't visit elements in order. But GCC 7.1 does.
You can try them on http://en.cppreference.com/w/cpp/algorithm/stable_partition

Closing because this is not Codewars issue.
