### ISSUE TITLE
Unable to Sign Up with github

### ISSUE THREAD

**Issue by alajfit** [Codewars/codewars.com#1433]
Steps to reproduce: 
1. Click Sign Up
2. Click JavaScript
3. Complete task
4. Click **Link Your Github Account**

Error: Failed to connect account

**Comment by kazk** [comment]
Closing stale issue. Please let me know if this is still happening.

**Comment by Haydenroborr** [comment]
I had the same problem. Did anyone find the solution?

**Comment by kazk** [comment]
@Haydenroborr can you open a new issue with your information?
