### ISSUE TITLE
Operation to show solutions/fixture and forfeit kata is suspectible to CSRF

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1434]
Currently anyone can forfeit a kata very easily as long as they access pages related to a kata with `?show-solutions=1` or `?show-fixtures=1` in their query string.

I could already imagine someone linking a kata with them in the query string (or even worse, `<iframe>` it as a big AoE attack; iframe has never been disabled in the kata comments rendering) just to troll other users by making them forfeiting a kata without even noticing they did.

These operations should act in the same vein as every other existing operations right now: they ought to have CSRF token validation and should always originate from the same page the operation is performed.

**Comment by Dobatymo** [comment]
If that is true (I don't really want to test that), this is serious. How come nobody replied in 2 weeks?

**Comment by Voileexperiments** [comment]
@Dobatymo Because they're too busy :( I actually had reported 2 even more severe issues privately and they seem to be still here.

**Comment by kazk** [comment]
Forgot to close this. This has been fixed. But might have caused #1552.
