### ISSUE TITLE
Fortran hightlight.js issue: number before underscore disappears

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1436]
In the kata "Color choice", <https://www.codewars.com/kata/55be10de92aad5ef28000023/edit/fortran> is well written but when published some given numbers with the terminator `_ikind` are eaten: for example `1_ikind` becomes `_ikind` or `CALL testing(6_ikind, 4, 2)` becomes `CALL testing(_ikind, 4, 2)` hence possible errors for those who pass the kata. 
Nevertheless it is possible that the problem is only "on the screen"
See @Phil157 post.

**Comment by kazk** [comment]
Weird.

Show Kata Test Cases:
![image](https://user-images.githubusercontent.com/639336/40223470-02483fea-5a38-11e8-9314-57b5877d7d77.png)

Kata Editor:
![image](https://user-images.githubusercontent.com/639336/40223441-ecf11b80-5a37-11e8-931f-3a6673d37a96.png)

**Comment by g964** [comment]
Thanks!

**Comment by g964** [comment]
Same problem with this Fortran kata:
<https://www.codewars.com/kata/tank-truck/discuss/fortran>
In M_PI=3.1415.... the "1" has disappeared... See @Phil157 post; solutions and tests cases.

**Comment by kazk** [comment]
I think this is [highlight.js](https://highlightjs.org/) issue.
See https://github.com/isagalaev/highlight.js/issues/1566 about the number before the underscore disappearing.

**Comment by g964** [comment]
OK for "1_ikind" becoming "_ikind" but what for "M_PI = 3.14159265358979323846_ikind" becoming "M_PI = 3.4159265358979323846_ikind".? The number that disappears is not before the underscore. What to do? Stop writing Fortran translation?:-)

**Comment by kazk** [comment]
@g964 I'm just saying that highlight.js has a similar issue reported and needs to be fixed there.

> The number that disappears is not before the underscore

I can imagine that it's still a related issue.

> What to do? Stop writing Fortran translation?:-)

Please keep it constructive, I'm just trying to help here.

**Comment by g964** [comment]
OK and thanks for your help!

**Comment by yyyc514** [comment]
Can anyone confirm this is still a real issue or provide a jsfiddle?

Sample you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by kazk** [comment]
@yyyc514 Thanks for reaching out. It's still an issue with the latest version and I've posted forked jsfiddle on https://github.com/highlightjs/highlight.js/issues/1566 .

**Comment by kazk** [comment]
Just updated highlightjs to 9.16.2 and this seems fixed. Thanks @yyyc514 :)

![image](https://user-images.githubusercontent.com/639336/68986508-dc609600-07d4-11ea-939d-12fefd4b259e.png)
Highlighting is not correct, but the number is there. I think the coloring issue is tracked at https://github.com/highlightjs/highlight.js/issues/1723

I'll update again when it gets fixed.

**Comment by yyyc514** [comment]
@kazk Yep, data loss bug was fixed, grammar is still off.

Glad to help.
