### ISSUE TITLE
Kata issue ?

### ISSUE THREAD

**Issue by Muhammad-Salman-Sheikh** [Codewars/codewars.com#1437]
Unable to submit or run tests. 

I was trying to solve kata but keep running into the error when I click on `attempt` or `run some tests` button : 

    The webpage at https://cr.codewars.com/?utm_source=codewars&utm_medium=web&utm_campaign=kata_trainer#theme=dark&congrats=true&pro=false might be temporarily down or it may have moved permanently to a new web address.

Is there something wrong with my net or code-wars. Found this issue on any kata I tried to run today

**Comment by kazk** [comment]
Can you describe what kind of error you're getting? There's no issue on our end as far as I can tell.

**Comment by kazk** [comment]
I'm going to close this, but feel free to comment for additional information. I'll reopen depending on that.
