### ISSUE TITLE
Output matches expected output, but test is NOT passed

### ISSUE THREAD

**Issue by rdowd003** [Codewars/codewars.com#1439]
<img width="504" alt="screen shot 2018-05-19 at 6 25 51 pm" src="https://user-images.githubusercontent.com/39447892/40274485-6aed3462-5b94-11e8-9ec8-b336a62085c5.png">

As title described. 

Prompt asks: Implement a function likes :: [String] -> String, which must take in input array, containing the names of people who like an item. 

Code:
def likes(names):
    #your code here
    if len(names) == 0:
        print str('no one likes this')
    elif len(names) > 0 and len(names) < 4:
        if len(names) == 1:
            print names[0], 'likes this'
        elif len(names) == 2:
            print names[0], 'and', names[1], 'like this'
        else:
            print names[0],',', names[1],', and', names[2], 'like this'
    else:
        x = len(names)-2
        y=str(x)
        a=names[0]
        b=names[1]
        print ('%s, %s and %s others like this' % (a,b,y))

**Comment by 10XL** [comment]
You're printing when you should be returning a value. The tests fail because your function returns None.
