### ISSUE TITLE
Example test cases not updated when kata is re-published

### ISSUE THREAD

**Issue by SteveRuble** [Codewars/codewars.com#144]
I have authored a kata (http://www.codewars.com/kata/count-the-islands/train) with a typo in the example test cases. When I fix the typo and re-publish the kata, the example test cases don't get updated in the trainer. (If I re-open the editor, the changes appear to be updated, but the trainer cases are the same.)

Changes to the final test cases show up in the "discourse" view, and changes to the kata description show up as well, so for now I've just added an explanation of the problem with the example test cases to the kata description.

**Comment by bkaes** [comment]
>When I fix the typo and re-publish the kata, the example test cases don't get updated in the trainer. 

Probably related to #106. It's still showing your _personal_ tests. You need to solve the kata to have the trainer reload the example tests.

**Comment by SteveRuble** [comment]
Yep, that's was the problem.
