### ISSUE TITLE
CW's Markdown engine is inaccurate

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1441]
Most basic example:

```
1. foobar
    - abc
    - def
```

should be rendered as:

1. foobar
    - abc
    - def

but in CW Markdown it's not rendered properly:

![image](https://user-images.githubusercontent.com/14909989/40416100-0505d06e-5eaf-11e8-8b2c-4f8139b8a435.png)

**Comment by anter69** [comment]
Just remove the leading spaces and it works as intended:

![image](https://user-images.githubusercontent.com/12795864/40643471-905ae742-6320-11e8-8527-f23619f529c3.png)

**Comment by Voileexperiments** [comment]
I don't think that's "work as intended": basically every Markdown engine in every other site would render that properly. Besides there are more cases where the rendering just breaks:

![image](https://user-images.githubusercontent.com/14909989/40644168-e9fcace8-6354-11e8-8e89-b7cab788bd23.png)
![image](https://user-images.githubusercontent.com/14909989/40644182-f3a6ae74-6354-11e8-9b5f-3012c085a2c2.png)
![image](https://user-images.githubusercontent.com/14909989/40644194-ff8e13ee-6354-11e8-87bd-90a1fd186f9c.png)
![image](https://user-images.githubusercontent.com/14909989/40644241-229c12f0-6355-11e8-97ad-078912894883.png)
![image](https://user-images.githubusercontent.com/14909989/40644254-2d95a43c-6355-11e8-94ad-b74f392e01ff.png)
(also, note that syntax lighting is broken in the third case)

CW's Markdown redering engine is just slightly less broken than StackOverflow's one. It seems that only Github's is up to the task to handle the need to make nested lists for really organized formatting properly.

**Comment by kazk** [comment]
Preview and actual is still inconsistent (#1640), but I believe this one can be closed. The server side engine now uses CommonMark with GitHub extension and it should be very similar to GitHub comments.
