### ISSUE TITLE
Unable to approve a translation: nilClass error

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1445]
kata: <https://www.codewars.com/kata/phone-directory/discuss>
See posts from @Helge801 and my answers.

**Comment by kazk** [comment]
When do you get this error? When you click approve? Can you open that translation?

**Comment by kazk** [comment]
Related #851

**Comment by g964** [comment]
It happens when I click Helge801 link: <http://www.codewars.com/kumite/5b073097c3323a829e000127?sel=5b073097c3323a829e000127>or if I click "Add new" and then "Translate this kata".

**Comment by tlong123** [comment]
I have been encountering the same issue - trying to approve a translation either from a link in a comment on:
https://www.codewars.com/kata/escape-with-your-booty/discuss 
or through the add new language drop down box. The link generated for the translation is:
https://www.codewars.com/kumite/5bf32c270934aac6410004a9 
and when clicked goes to a server error(500) page with description "undefined method `name' for nil:NilClass"

**Comment by kazk** [comment]
I can't reproduce, the link works for me.

@tlong123 did you delete a language like described in #1268?

**Comment by tlong123** [comment]
@kazk I haven't not deleted any languages, I had this same issue with a python translation by another user on the same kata

**Comment by kazk** [comment]
@g964 This should be the same issue as #851. Can you try again and let me know if anything changed?

@tlong123 can you try again?

@error256 can you check if the issue in your [comment](https://github.com/Codewars/codewars.com/issues/1060#issuecomment-419743774) is still happening?

**Comment by kazk** [comment]
Fixed
