### ISSUE TITLE
5xx: Server Error 

### ISSUE THREAD

**Issue by LondonJim** [Codewars/codewars.com#1446]
Sometimes it logs in, sometimes it doesn't load at all. Very slow when logged in and then error screen appears. Has been happening the last couple of days, seems to be worse today. Constant errors below.

![server_error1](https://user-images.githubusercontent.com/39761427/40710794-8a1bc3fc-63f1-11e8-8c2e-2cb8727e52c8.jpg)

![server_error2](https://user-images.githubusercontent.com/39761427/40710802-8ea2b1c4-63f1-11e8-83e7-785a82cca270.jpg)

**Comment by bestwebua** [comment]
The same.
