### ISSUE TITLE
Error occured when logged in the dashboard. Photo attached

### ISSUE THREAD

**Issue by ghusimushi** [Codewars/codewars.com#1449]
![screenshot 2018-06-01 04 48 40](https://user-images.githubusercontent.com/23281601/40812357-461f7ef2-6557-11e8-9c85-62cb9e057a61.png)

**Comment by Voileexperiments** [comment]
Basically #1446

**Comment by Kaelinator** [comment]
I've been getting the same result!

**Comment by blarosen95** [comment]
I only recently came back to codewars after being gone for a bit over a year and I notice this and just long page loading times in general, perhaps it's more of a Cloudflare problem than a codewars issue?

**Comment by Kush131** [comment]
I have also experienced the same type of issues. Began last night for me and have continued ever since.

**Comment by kazk** [comment]
We're having some performance issue with the database. @jhoffner is working on it. 
Sorry for the inconvenience.
