### ISSUE TITLE
Html special characters not escaped in unittest output

### ISSUE THREAD

**Issue by danamlund** [Codewars/codewars.com#145]
Not escaping html special characters can lead to failed unittests being shown as `expected: but was:`. When you use a html debugger you see that the message actually says `expected: <foo[]> but was: <foo[bar]>`. However, `<foo[]>` is parsed as an html tag and not shown.

I have only tested this with java.
The following test-case reproduces the example used above.

``` java
import org.junit.Test;
import org.junit.Assert;

public class UnitTestHtmlEscapeTest {
  @Test
  public void testHtmlEscape() {
    Assert.assertEquals("foo", "foobar");
  }
```

I made a temporary kata that shows this bug.
http://www.codewars.com/kata/55b1da58e96f8279800000bf/train/java

**Comment by bkaes** [comment]
Could you edit your issue description and add backticks around your code? E.g. ``` `expected:…but was…` ```. GitHub strips unknown/invalid HTML tags.

**Comment by Drako** [comment]
This does not only affect unit testing. I wrote a C++ Kumite with templates. Sadly when publishing it everything between < and > is hidden. Also includes are hidden, so
#include <iostream>
just becomes
#include
etc.

**Comment by jhoffner** [comment]
See #844 for more details. @danamlund you can go to http://preview.codewars.com/kata/55b1da58e96f8279800000bf/train/java to test. Note that it still doesn't work until you take the HTML out of the message, then the auto-detection will detect no HTML and render correctly.

**Comment by danamlund** [comment]
Fix verified.
