### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by csrunner20** [Codewars/codewars.com#1450]
The page isn't opening live.  It takes a ton of time to load and then loads a snapshot of the page instead.

Sample of the output given: 
`This page (https://www.codewars.com/users/auth/github/callback?code=271520aacc1a8c177cf8&state=26f6b114c8cf39bb8f14732f7daca40496d418d64cbffc6e) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert `

Steps:
1. go to codewars.com
2. Click log in
3. Wait forever for a bar to come up that says the page isn't live.

I just got on yesterday, smoothly and quickly, no problem.  Last night, I was having this same issue, but I didn't think much of it due to a poor internet connection.  But today connected to a strong internet connection, I'm having the same issues

I attached the screenshot of the problem.
![screenshot from 2018-06-01 10-50-40](https://user-images.githubusercontent.com/30871646/40853060-f3a3d974-6589-11e8-9ec7-8f931cd229e4.png)

**Comment by dbear1000** [comment]
Same Here 

"There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed."

Error reference number: 520
Cloudflare Location: London

**Comment by cheesegits** [comment]
> Looks like there was a server error! (500)
> We have taken note of the situation and will be looking into it.
> 
> If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.
> 
> ApplicationController::AccessDeniedError

**Comment by helloimlaura** [comment]
I was also getting the server error (500) up until a few minutes ago. It may be fixed.

**Comment by tarekgabarin** [comment]
Just checked, and the site is still not working.

**Comment by kazk** [comment]
We're having some issues with the database. @jhoffner is currently working on it. Sorry for the inconvenience.
