### ISSUE TITLE
I complete two katas but they don't mark as completed

### ISSUE THREAD

**Issue by wKich** [Codewars/codewars.com#1451]
<img width="908" alt="screen shot 2018-06-02 at 14 45 46" src="https://user-images.githubusercontent.com/6397708/40873119-d196009c-6673-11e8-9f7a-f6e5a7740ea9.png">
<img width="760" alt="screen shot 2018-06-02 at 14 46 49" src="https://user-images.githubusercontent.com/6397708/40873120-d1ba37a0-6673-11e8-86f0-ba34b4973491.png">

**Comment by Len512** [comment]
+1

**Comment by kazk** [comment]
This should be fixed. I'm assuming this was about kata not marked as completed on search result page. Please let me know if I'm mistaking or if this is still happening.
