### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by Jo-Hunter** [Codewars/codewars.com#1453]
Tried to sign up today.

Did not try to link my github account.

However, I tried to sign up twice with Java then tried PHP once.

All times got this message:

> Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.
Request ran for longer than 45000ms
"

FYI.

**Comment by Paradoxial-Name** [comment]
Already opened in #1452

**Comment by kazk** [comment]
Sorry for the late response. This issue will be tracked at #1516

**Comment by wodomierz** [comment]
I have a server error ;/
