### ISSUE TITLE
notif messed up

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1454]
Codewars seems to be an issue, notification bug.

So what is happening is that it keeps telling me that I have 5-6 unread notifications even though not only have I replied to those but even moved way on in some (number keeps increasing).

It won't go away.
- I tried closing the tab and checking in new tab
- I tried hovering over it till it goes away then reloading
- I tried hovering over it till it goes away then closing and opening a new tab
- I tried closing all tabs (and the browser) and then reopening 
- I tried signing out and then signing in again

---

So as you can see by now I am stuck with 20 or so notifs that I definitely don't want. I would appreciate if someone could explain what is wrong.

**Comment by FArekkusu** [comment]
The thing disappears over time but it happened to me as well a few times already. Whenever you try to open another codewars page the closed notifications reappear, popups about translation being forked reappears everywhere as well.
64-bit Windows 7, using Google Chrome (in case this matters).

**Comment by Paradoxial-Name** [comment]
@DonaldKellett : using FireFox dev edition, 64 bit Window 10.

@FArekkusu : Well it bothered me for hours but yeah it did disappear, but every time I get a new notif it starts again, kindly annoying.
