### ISSUE TITLE
issue on issues 

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1455]
So browsing the list of issues that are currently open, I came across some really good ones that need to be dealt with but haven't been dealt with yet (for reasons I can't understand)

The list of issues is growing exponentially long (this is 495th open issue), I highly suggest closing some solved issues and solving others. 

There are issues that are 4-5 years old and are just clogging up the list while some haven't been solved to date even though they are this old ? 

---

Might wanna check into that

**Comment by DonaldKellett** [comment]
AFAIK the official CW team is understaffed so it may take some time to resolve an issue, not to mention that people often post duplicate issues or issues about specific Kata (though such issues are often closed once discovered).
