### ISSUE TITLE
BF grammar error

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1456]
# Grammar problem : 
Okay, this is not an issue but here is the problem : 

> Error: Out of range! Youwanted to '<' below the first cell.

In case you still didn't spot the mistake 

Error: Out of range!<b>Youwanted<b> to '<' below the first cell.

Yeah you used `Youwanted` instead of `You wanted` to.

Happens when you use `<` to move out of the first cell,

# Sample program : 

The following program will output the above mentioned error : 

    <

Yep that's it.

**Comment by DonaldKellett** [comment]
This is a [third party](https://packages.ubuntu.com/source/trusty/bf) issue so not much can be done on our end to fix it.

****

cc @kazk

**Comment by kazk** [comment]
Closing this as the message comes directly from the interpreter.
