### ISSUE TITLE
300 honor requirement for creating a kata is not working apparently

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1457]
e.g https://www.codewars.com/kata/5b14b543828fab157c000006/discuss#5b14b6a94ac15887880000b6, a kata published by a user with ~150 honor (and then retracted after getting 3 issues and 1 solve).

There was also another occurrence a few days ago where a user with ~270 honor managed to publish a kata.

So apparently the 300 honor requirement is not quite working. I haven't go and test all the routes yet, but I guess this means some routes are still open and you can create and publish new katas from them.

**Comment by Paradoxial-Name** [comment]
@Voileexperiments : That is not the only problem.

 see #1461 among others.

**Comment by Blind4Basics** [comment]
#1532

**Comment by kazk** [comment]
This was caused by permission to convert kumite to kata was not checked properly (#1532). The fix is currently deploying.
