### ISSUE TITLE
Broken tests in Python translation of a kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#146]
A week ago I posted in the feedback part:

"Something is broken in the Python translation of my kata "Directions Reduction". I don't remember who was the translator but there are bad indentations in the "solution" for the random test cases hence sometimes Codewarriors see their tests pass, sometimes they don't. I can't any more edit the kata: more than 500 Codewarriors!"

A few guys are complaining, they can't pass the kata!
kata: http://www.codewars.com/kata/directions-reduction/python

**Comment by jhoffner** [comment]
I'm closing as it seems (based off of the coment thread) that this was just an issue with the code warrior's solution.

**Comment by g964** [comment]
Hi,
You closed the issue but look at the Python kata, you'll see that the code in Complete solution and the "solution" in the tests are different. Bad indentations in the def dirReducTest(arr):, the copy and paste was certainly not well done.
http://www.codewars.com/kata/550f22f4d758534c1100025a/edit/python

def dirReduc(arr):
    import re

    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        #print(ss)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        #print(ss)
        if ss == s:
            nd = False
        else:
            s = ss
    if s != "":
        return s.split(",")
    else:
        return []

def dirReducTest(arr):
    import re
    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        if ss == s:
            nd = False
        else:
            s = ss
        if s != "":
            return s.split(",")
        else:
            return []

Compare the 4 last lines. Wasn'it your translation?-)

**Comment by g964** [comment]
Hi,
You closed the issue but look at the Python kata, you'll see that the code in Complete solution and the "solution" in the tests are different. Bad indentations in the def dirReducTest(arr):, the copy and paste was certainly not well done.
http://www.codewars.com/kata/550f22f4d758534c1100025a/edit/python

def dirReduc(arr):
    import re

    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        #print(ss)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        #print(ss)
        if ss == s:
            nd = False
        else:
            s = ss
    if s != "":
        return s.split(",")
    else:
        return []

def dirReducTest(arr):
    import re
    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        if ss == s:
            nd = False
        else:
            s = ss
        if s != "":
            return s.split(",")
        else:
            return []

Compare the 4 last lines. Wasn'it your translation?-)

**Comment by bkaes** [comment]
@g964 You've posted the same comment twice, both times with bad formatting. Delete one of the comments and edit the other one. By the way, you can notify Jake with `@jhoffner`. Just handle it with care, don't spam.

**Comment by g964** [comment]
I deleted #146 and I keep this one where I don't see any bad formatting; it is not the same comment but  just a remainder of the old one plus a copy of the two functions.
How are you managing all these posts? You never sleep?-)

**Comment by bkaes** [comment]
@g964 Err, did you post your comment on the correct thread? Neither #146 nor #149 are deleted. Or did you want to say that you deleted the comments on #146?

>  How are you managing all these posts?

That's actually rather easy, I check whether there's been any activity [on gitter](https://gitter.im/Codewars/codewars.com) (see the sidebar). Writing posts like "Needs more tests" or quoting something doesn't take long at all. All in all, I spent roughly less than 1h on Codewars related stuff per day, if I even do anything CW related that day.
