### ISSUE TITLE
Power user problems 

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1460]
While most of the time CW community stays human, sometimes it so happens that users go off a bit and start becoming a pain. 

New users that join are mostly the big problem, they open issues without knowing other things like : 
- suggestion
- Question

can be opened. and some power user closes closes the issue telling them that this isn't an issue. 

At this point two problems rise : 

- Power users tone becomes a little unfriendly (especially true for some power users) and they suggest in a less than friendly way to someone who is more than likely unaware of the system.
- The new user if they are child (in general) and some really unreasonable adult start a debate which doesn't end well, since the person on the other end can trash talk equally well (in some cases even better)

The problem on general like this. 

While most power users and are friendly (I like these ones 😄) e.g : 
- Myjinxin2015 (whom I haven't seen raise a single issue in a long time)
- ZED.CWT who for the most time does an excellent job of remaining neutral and friendly 

Some users are a bit of a problem , users like voile and Blind4basics who comment on a ton of kata's sometimes their comments can become less than friendly (Note for @VoileExperiments :  Please don't start yelling 😃 ) 

which is less than welcoming (in case of voile it ends with a down vote on every Kata (s)he will solve made by you for the next month or so (this part is from experience) 

maybe enforce a stricter policy on be nice 

like SO has. Although unlike SO I suggest you actually implement that, they still seem to have trouble on that end :)

# Note : 

Please don't be offended

**Comment by AnvShx** [comment]
I agree on the issue about some power users, especially Voile. His behavior borders on abuse, in a lot of cases.

**Comment by Voileexperiments** [comment]
@Paradoxial-Name @AnvShx This repo is about CW, not about any particular user. If you don't like me and want to get rid of me, go open an issue in this repo with a clear title of "ban Voile from CW", provided with clear reasons why you think banning me from CW would be better (the more detailed the better, obviously). There's no point playing hide and seek in residual issues posting snarky comments. If you want to advocate for something, be straight and honest.

Also, @Paradoxial-Name, we all know you're @Muhammad-Salman-Sheikh aka `no one` aka `___i`. You don't need to be so roundabout just to express your grudge against me and @Blind4Basics. You're not being honest with yourself.

**Comment by Blind4Basics** [comment]
Just reading this... Very interesting.......

**Comment by raulbc777** [comment]
@Paradoxial-Name You mentioned two users that are making a great work for our community. I don't agree. My respect for Voile and Blind4Basics
