### ISSUE TITLE
Unable to approve translation

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1466]
^ Simple as that, I can't approve translations. 

And no I have enough honor to approve translations. When I try to approve a translation it does absolutely nothing.

On a side note I am unable to reject translations too 😢 (not that I need to do that) 

🙍‍♂️ 😦 ☹️ 

Hopefully that can be fixed.

**Comment by anter69** [comment]
@kazk Same as #1389, so it could be closed.

**Comment by Paradoxial-Name** [comment]
@anter69 : No need, I wan't aware that there was an existing issue. Why isn't it solved. 

Nonetheless closed this myself.
