### ISSUE TITLE
BF interpreter 

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1467]
I'm curious what kind of BrainF**k interpreter CW is using since it doesn't seem to support half of what I would like to do in it ?

The favorite error it has is that I tried to : 

> Out of range! Youwanted to '<' below the first cell.

Even when it works on all other editors and I know that it is valid BF code. 

So the question is what is wrong with your interpreter and why the hell does it keep giving me that error ?

**Comment by kazk** [comment]
Package: https://packages.ubuntu.com/xenial/bf
Manpages: http://manpages.ubuntu.com/manpages/xenial/man1/bf.1.html
Command: `bf -c29999 solution-file`

> LIMITATIONS
>       It's not allowed to '<' below the first cell.
>
>       It's not allowed to '>' beyond the last cell.

**Comment by Paradoxial-Name** [comment]
@Kazk : Thanks for the info.
