### ISSUE TITLE
Ctrl/Cmd+S Submits Solution, Should Run Tests 

### ISSUE THREAD

**Issue by Swivelgames** [codewars/codewars.com#1469]
Myself and a number of others are becoming increasingly frustrated with the association of Ctrl/Cmd+S with an "Attempt". The reason is because we've all developed the habit of saving after each major change before testing the code (Notice: _Testing_).

A full attempt is frustrating because we'd like to finish the Kata without running a full attempt. The unfortunate effect of this is that it's undoing the habit of hitting Ctrl/Cmd+S when in other editors.

I understand this might not be true for everyone, but is it possible to change the keyboard shortcut to instead invoke "Run Sample Tests"? An "Attempt" should be more deliberate than the natural / muscle-memory response to code changes, which is to Ctrl/Cmd+S

**Comment by nickhallph** [comment]
Yes please.

**Comment by Synnux** [comment]
Seriously, the last three Kata's I've completed, I've hit Ctrl+S out of muscle memory and lost my ability to get full points. I don't want to have to do all my code in the console out of fear of accidentally submitting my attempt. It defeats the purpose of having tests in the first place. Smh.

Even switching the shortcut to run the tests instead of submit would be fine.

**Comment by Voileexperiments** [comment]
For the record, running sample tests will save a copy of the current code and sample tests too, so really only a rebind is necessary.

**Comment by Swivelgames** [comment]
@Voileexperiments Precisely :)

**Comment by Swivelgames** [comment]
Anything new on this? :/

**Comment by actually-reb** [comment]
I also find this frustrating

**Comment by megalepozy** [comment]
My current solution is to select the EMACS option which make ctrl+s do a search.

I don't know but hope that it keep being selected for next kata's as well...

Honestly I would love an ability to revoke ctrl+s or redirect it to Test instead as I just failed "my first attempt" out of mistake and honestly it's pissing me off a little...

**Comment by kazk** [comment]
I'll change `Ctrl/Cmd-S` to run sample tests.

**Comment by kazk** [comment]
Deployed
