### ISSUE TITLE
No honor points gained by upvotes on solution

### ISSUE THREAD

**Issue by woucka** [Codewars/codewars.com#147]
Based on the short explanation of honor in the [about section](http://www.codewars.com/about) of the website, honor can be gained through "crafting great solutions".

![solution-honor-about](https://cloud.githubusercontent.com/assets/13423494/8894874/45672444-33c6-11e5-9a21-7def5c6d5ebb.PNG)

More specifically, it has been [stated](http://www.codewars.com/topics/ranking-and-honor) by one of the codewars team members that whenever someone marks one of your solutions as "best practices" or "clever", you should receive 1 honor point.

![solution-honor-1](https://cloud.githubusercontent.com/assets/13423494/8894876/6a201700-33c6-11e5-84d4-897963cf7a4c.PNG)

![solution-honor-2](https://cloud.githubusercontent.com/assets/13423494/8894877/6efc61ac-33c6-11e5-82f3-94040402c4e9.PNG)

Based on this information, plus the fact that there is a bar named "solutions" as part of the honor breakdown chart on my profile, I presume that this is indeed part of the site's functionality: 1 click on either "best practices" or "clever" for someone's solution should yield 1 honor point for this person.

However, while I have submitted at least one solution that has been grouped together with solutions that have received upvotes for "best practices" and "clever", I have not received any honor points for this.

![solution](https://cloud.githubusercontent.com/assets/13423494/8895024/9cb10bde-33cb-11e5-863b-7eb78b753aa0.PNG)

![honor-breakdown](https://cloud.githubusercontent.com/assets/13423494/8895027/a7ba18ae-33cb-11e5-8564-bf5b3204a1af.PNG)

![site-events](https://cloud.githubusercontent.com/assets/13423494/8895028/abb1cb78-33cb-11e5-98dc-24a939a86354.PNG)

(Note: I posted this solution approximately two days ago. I have also logged out, made sure no cookies were saved in my browser, and logged back in. Nothing changed.)

I suspect that this issue stems from the fact that these upvotes had already been given to this solution before my own solution was posted and grouped together with it. I presume this is unintended; hence, this bug report.

**Comment by jhoffner** [comment]
Thanks for the long explanation @woucka. Unfortunately this behavior is working as intended. It wasn't always this way, but some less honorable users found a pretty easy way to earn honor, by creating two accounts. They would use the one account to solve the kata, then find the specific solution with the most upvotes/momentum and then just copy that solution into their second account and stick around for the free ride. 

One user did it so often that they were in the top 10 until we realized what was happening, so now the original poster gets credit only. I admit its not an ideal solution. There are a number of improvemnts that can be made to try to make solution up-voting more balanced. Its something I hope to visit as a large rework later this year.

**Comment by woucka** [comment]
Ah, I see.

I agree it's not an ideal solution, but it's still better than giving free reign to cheaters. It must have been a tough decision, but I believe you made the right call.

Thanks for taking the time to clarify the issue; I appreciate it.
