### ISSUE TITLE
Please add a bad words filter

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1474]
Perhaps related to #1440 I've  seen a lot of profanity and insulting words in the site, perhaps you can do something simple like using https://github.com/web-mech/badwords

**Comment by FArekkusu** [comment]
~~A bunch of pro-friendliness users from SO as moderators~~

IMO, it should stay as it is. As @docgunthrop says, often profanity =/= insults, and if somebody still dares to go as far as express hatred towards other users, it can be reported to the staff (at least I think I've read somewhere that we can) and handled appropriately.
