### ISSUE TITLE
Unread notification does not clean up even after reading them

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1475]
This means I have 1 unread notification:

![image](https://user-images.githubusercontent.com/14909989/41140981-dd495d2c-6b22-11e8-93a2-0fe1aa8a1c00.png)

which is normal, and when I read the notification and the `1` disappears. However, when I refresh the page, the `1` is shown again, which should not happen at all.

**Comment by Paradoxial-Name** [comment]
@Voileexperiments already asked #1454

**Comment by Chrono79** [comment]
The other is already closed.

**Comment by DanL12186** [comment]
This happens every time without fail; I think it popped up ~2-3 months ago.

**Comment by kazk** [comment]
This is fixed.
