### ISSUE TITLE
translation doing double time

### ISSUE THREAD

**Issue by Paradoxial-Name** [Codewars/codewars.com#1477]
What the title says :)

I'm seeing translations in both drafts and closed page, which should be okay but the problem is the same translations that some translations that were published (and should only be in closed) are appearing in the drafts section too. And I seem to have extra translations due to that, most of which seems aren't approved. 

Which obviously can't be right since I just checked and they are still there ?

**Comment by kazk** [comment]
Please let me know if this is unresolved. Also, please include your Codewars username.
