### ISSUE TITLE
Object.values() does not seem to be supported within the editor

### ISSUE THREAD

**Issue by maddoxnelson** [Codewars/codewars.com#1479]
(Obligatory: I'm new here, if I'm in the wrong place, be nice :) )

This is the Kata: https://www.codewars.com/kata/5966847f4025872c7d00015b/train/javascript

This is what I've written, and this is the error:

<img width="1054" alt="pic 2018-06-11 at 7 28 41 am" src="https://user-images.githubusercontent.com/4610199/41229213-247731a6-6d49-11e8-8f3a-d312d0fbb9c0.png">

I copied the syntax pretty much exactly from this article: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

`Object.keys()` works great. CanIUse.com seems to indicate widespread support for Object.values(): https://caniuse.com/#search=object.values

This alternative implementation of the same code works fine, but isn't as clean as Object.values(): 
```
let valIWant = '';

Object.keys(numLib).forEach((key) => {
    if (numLib[key] === avg){
      valIWant = key
    }
```

Near as I can tell, it is not specific to this Kata.

**Comment by Paradoxial-Name** [comment]
This isn't an issue, this is you not getting your version history and their added features right.

Node v6 doesn't support `Object.values` , The support for that was added beginning in Node v7. 

---

> The alternate code you mentioned is not as clean as `Object.values` : dunno about that.

But it does look stupid and overly lengthy. Here is a better way to do it : 

      objKeysMap = Object.keys(obj).map(k => obj[k])

**Comment by kazk** [comment]
Use Node 8 if you need `Object.values`. If the kata doesn't have it, let the author and contributors know by commenting on the kata discourse page.
