### ISSUE TITLE
typo at http://www.codewars.com/users/USERNAME/allies

### ISSUE THREAD

**Issue by ChrisDillinger** [Codewars/codewars.com#148]
"why" should be "when"

**Comment by bkaes** [comment]
While we're at it:
``` diff
- You do not have any allies yet. Users become your ally why you both follow each other.
+ You do not have any allies yet. A user becomes your ally when you both follow each other.
```

**Comment by paul-calvelage** [comment]
Mine says 
> You do not have any allies yet. Users become your ally **whenheroku** you both follow each other.

So there are two problems:

1. the plural/singular mismatch between "Users" and "ally" (not a big deal)
2. the word "whenheroku"?  I have no idea where the extra "heroku" is coming from.

![screen](https://cloud.githubusercontent.com/assets/5090280/14327026/8447f87c-fbfe-11e5-8131-f81e2b0b076f.PNG)

**Comment by kazk** [comment]
This should be fixed now.
