### ISSUE TITLE
Landing page does not load (500 server error)

### ISSUE THREAD

**Issue by dinoboy197** [Codewars/codewars.com#1480]
I just signed up for a Corewars account after passing the Java skills test. Once I filled in my github profile, username, and password, I was taken to a page which said server error. I get this no matter how many times I refreshed the page.

See screenshot:

![image](https://user-images.githubusercontent.com/631178/41322642-c81cebe6-6e45-11e8-9108-65e215bae404.png)

**Comment by JackTaylorKudos** [comment]
I also get this today when trying to sign up.

**Comment by cchung100m** [comment]
me, too. I also get the error message today.

**Comment by dnorth87** [comment]
I had the same problem just now.

**Comment by BasicsCoding** [comment]
got this problem too when trying to sign up

**Comment by CodaBae** [comment]
me too

**Comment by kazk** [comment]
Sorry for the late response. This issue will be tracked at #1516
