### ISSUE TITLE
Scala : disable warnings

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1481]
In a Scala translation I get:
```
Time: 7720ms Passed: 2 Failed: 0 Errors: 1
Test Results:
 RotationsTest
 should pass basic tests
 should pass random tests **** containAllRots
Completed in 52ms
STDERR:
warning: there were 12 deprecation warnings (since 2.12.0); re-run with -deprecation for details
one warning found
```
The problem is double:
I can't see the warning because I can't run with `-deprecation`...
I can't disable the deprecation warnings

**Comment by kazk** [comment]
This shouldn't be a problem anymore as we're no longer treating stderr as error. Let me know if this is still happening.
We might add `-deprecation` flag later if that doesn't affect performance.

**Comment by g964** [comment]
Thanks! Seems to work now: no warnings.
