### ISSUE TITLE
Looks like there was a server error! (500)

### ISSUE THREAD

**Issue by ronrand** [Codewars/codewars.com#1482]
A few things to check first:

Is the issue you are filing related to a specific kata?

If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Is the issue you are filing related to how a specific language behaves when being executed?

If so then it will likely be better to file the issue on our [github.com/Codewars/codewars-runner-cli/issues](https://github.com/Codewars/codewars-runner-cli/issues) repo, which is where we have our open source code execution functionality. You also may want to look into forking that repo and fixing the issue yourself if you have the means.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.

**Comment by Paradoxial-Name** [comment]
What is the issue about ? You have not posted anything just the preloaded text.

**Comment by dthompsonza** [comment]
I get the above error on signup or trying to view my profile...

Url: https://www.codewars.com/users/username-redacted

> Looks like there was a server error! (500)
> We have taken note of the situation and will be looking into it.
> 
> If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.
> 
> ApplicationController::ResourceNotFoundError

**Comment by fakeharxy** [comment]
I get this also when trying to sign up. It doesn't create my user and crashes with a server error.

**Comment by dthompsonza** [comment]
I just tried signing up again and it worked after that.

**Comment by kazk** [comment]
Sorry for the late response. If this issue is about server error after signing up, it will be tracked at #1516
