### ISSUE TITLE
Can't press buttons

### ISSUE THREAD

**Issue by AirHunter007** [Codewars/codewars.com#1483]
So, i can't press buttons "Sumbit" and "Run Test", because they are in the right down corner (look at the screenshot).
![screenshot_1](https://user-images.githubusercontent.com/40275729/41434394-08798f28-7035-11e8-8c59-d8457af22cd1.png)

**Comment by error256** [comment]
Duplicate: https://github.com/Codewars/codewars.com/issues/1214
Workarounds, choose one: change window size, change scale, scroll down by middle mouse click, use keyboard shortcuts.
But yeah, this bug exists for almost a year, maybe even a year :(

**Comment by AirHunter007** [comment]
It worked! Thank you man!!!!!  You best! :-)

**Comment by kazk** [comment]
Closing as duplicate of #1214.
