### ISSUE TITLE
Running kata or seeing unlock solution

### ISSUE THREAD

**Issue by mehran5454** [Codewars/codewars.com#1484]
each time I run one kata, it surprises me
sometimes I cannot see "discuss" and "unlock solution" bottoms and sometimes I cannot see  "run sample" and "attend".
Is it possible someone explains to me how can I work with this site? It is really frustrating that couldn't find a simple document to show How should use the site

**Comment by anter69** [comment]
@kazk seem to be a duplicate of #1214

**Comment by kazk** [comment]
Closing as duplicate of #1214
