### ISSUE TITLE
PHPUnit Warnings

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1486]
I got this when trying a PHP translation:
```
Time: 937ms Passed: 3 Failed: 0
Test Results:
 Log
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.
 FTestCases
 Warning
 testBasics
 testRandom
```
Unfortunately the "Warning" gives no infos. Is it possible to suppress the warnings or to force it to give details?

**Comment by kazk** [comment]
Can you post the link to the translation? Or the code that can reproduce this?

**Comment by g964** [comment]
It happened with 2 translations. Can I reproduce one here?

**Comment by kazk** [comment]
PHPUnit treats functions starting with `test` a test case. https://github.com/Codewars/codewars-runner-cli/issues/231

So change `testing` to something that doesn't start with `test` (like `_testing`) and it won't show up.

![image](https://user-images.githubusercontent.com/639336/41898036-c792554c-78dd-11e8-9ace-43b3c9495b98.png)

**Comment by g964** [comment]
Thanks, it works.
