### ISSUE TITLE
Attempting to expand failed tests does nothing

### ISSUE THREAD

**Issue by AlexAlt** [Codewars/codewars.com#1487]
Language: Ruby, Kata: Scramblies (and others)

After hitting the "attempt" button, I have additional test failures, and an error. However, when I try to select the failed test in the top bar, it only collapses or expands the red/green list. When I try to hit the 'i' icon next to the failed test, nothing happens. There is one failure in the console after hitting "attempt", trying to access this URL `blob:https://www.codewars.com/00c562b4-f3d6-44b8-bfa8-f7f241ef73a0`

**Comment by AlexAlt** [comment]
Ah, so is it a feature to not be able to see the assertion? I guess my issue is that all of my sample tests pass, but the "Attempt" tests are failing, and I cannot see what they are so I can fix my code.

**Comment by kazk** [comment]
No, it's not a feature of Codewars (we're not hiding assertions).

The test output is based on the tests that authors wrote so the output may not contain useful information if the tests are written that way.
For example, the author could've written tests like the following
```ruby
describe("scramble") do
  it("returns true given 'rkqodlw' and 'world'") do
    Test.assert_equals(scramble('rkqodlw', 'world'), true)
  end
end
```
then you'll see
![image](https://user-images.githubusercontent.com/639336/41877625-e00dc6da-7886-11e8-91ab-78f5963616c1.png)

---

For debugging, you can print the input in most languages. For Ruby, you can do `puts s1`.
