### ISSUE TITLE
Broken tests in Python translation of a kata #146, closed but there is a real problem

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#149]
Hi,
You closed the issue but look at the Python kata, you'll see that the code in `Complete solution` and the "solution" in the tests are different. Bad indentations in the `def dirReducTest(arr):`, the copy and paste was certainly not well done.
http://www.codewars.com/kata/550f22f4d758534c1100025a/edit/python

```
def dirReduc(arr):
    import re
    
    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        #print(ss)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        #print(ss)
        if ss == s:
            nd = False
        else:
            s = ss
    if s != "":
        return s.split(",")
    else:
        return []
```
```
def dirReducTest(arr):
    import re
    s = ",".join(arr)
    nd = True
    while nd:
        ss = re.sub(r"NORTH,SOUTH|SOUTH,NORTH|EAST,WEST|WEST,EAST", "", s)
        ss = re.sub(r"^,|,$", "",ss)
        ss = re.sub(",,", ",",ss)
        if ss == s:
            nd = False
        else:
            s = ss
        if s != "":
            return s.split(",")
        else:
            return []
```
Compare the 4 last lines. Wasn'it your translation?-)

**Comment by bkaes** [comment]
You can still comment on closed issues and continue the discussion. Consider deleting this one and commenting on #146.

**Comment by g964** [comment]
I thought I deleted my comments in #146. I can't delete the whole #146. I keep this one where it seems the code is correctly formatted:-)

**Comment by jhoffner** [comment]
I updated the kata
