### ISSUE TITLE
How to approve pending translations?

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1499]
With the new system of translation approvals, it is now possible to get your translation approved if the author has "abandoned" the Kata. However, as you cannot approve your own translation, the only way I know of to publicly request approval is by posting to the 'Discussion' section of the Kata. Unfortunately, that shifts the issue from getting author approval to getting approval of some sufficiently high ranked people to look at that Discussion section.

How to handle this more generically?

**Comment by anter69** [comment]
Go to https://gitter.im/Codewars/codewars.com/kata-authoring-help and ask someone to review and approve your translation.

**Comment by nomennescio** [comment]
Well, I'll give it a try

**Comment by nomennescio** [comment]
Unfortunately, I have not been very lucky yet in getting someone to review and approve at gitter.
