### ISSUE TITLE
HTML special chars gets applied one time too often in dashboard kata excerpt

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#15]
I don't know the Ruby equivalent of [`htmlspecialchars`](http://php.net/manual/en/function.htmlspecialchars.php), but it gets applied to often, since ampersands (`&`) are encoded in the kata excerpt on the dash board, see screenshot.

![escaping](https://cloud.githubusercontent.com/assets/6301773/6895011/a475b876-d6db-11e4-9df0-3ede2fa9abbe.png)

The source code shows that `>` has been encoded as `&amp;gt;` which indicates that it was already encoded as `&gt;`, but the ampersand got encoded _again_:

``` html
<div class="markdown"><p>Say we have a function of this type:</p>
<pre><code class="lang-haskell"><span class="hljs-title">f</span> :: <span class="hljs-type">Ord</span> a =&amp;gt; a -&amp;gt; <span class="hljs-type">Either</span> b ([a], [b] -&amp;gt; b)</code></pre>
```

**Comment by bkaestner** [comment]
@jhoffner Any progress on this one?

**Comment by paul-calvelage** [comment]
I can confirm this bug.  When I read "encoded *again*" it reminded me of the double UTF-8 encoding bug in #307.  It seems far fetched, but I wonder if they are related somehow?
![home](https://cloud.githubusercontent.com/assets/5090280/15615422/3ad8d50e-240c-11e6-964e-ad60b44481ce.PNG)
![kata](https://cloud.githubusercontent.com/assets/5090280/15615424/3d39b674-240c-11e6-9d71-246745424437.PNG)

**Comment by paul-calvelage** [comment]
I also get extra escapes in the Title field when I fork a solution
![fork](https://cloud.githubusercontent.com/assets/5090280/15650568/828a96e8-2647-11e6-805c-e3ba3f960a68.png)
