### ISSUE TITLE
Massive connection issues with the Codewars site.

### ISSUE THREAD

**Issue by Glinkis** [Codewars/codewars.com#1502]
I'm having massive issues with the Codewars website.

I keep getting timeouts, disconnects, and every network request takes at least 20 seconds to complete.

<img width="512" alt="screen shot 2018-07-03 at 13 31 02" src="https://user-images.githubusercontent.com/8037927/42217424-6e6019bc-7ec5-11e8-926c-7a8115ba7983.png">

And once every 30 seconds or so, I get a popup with:
```
There was a server issue while sending the request. Please try again.
```

My own connection is fine, and work without issues on any other site.

**Comment by justyna95** [comment]
Me too. The Same thing happens...

**Comment by nomennescio** [comment]
#metoo

**Comment by abloom12** [comment]
Same issue here, this site has always dragged ass for me.

**Comment by RRadziejewski** [comment]
SOmething is wrong i encountered problems yesterday and same scenario tooday.

**Comment by BlaG0o** [comment]
I'm experiencing the same issue as well. From time to time it comes back, but just for a minute or so.

**Comment by Glinkis** [comment]
The worst issues seem to be fixed, but I'm still having a _very_ slow experience.
So I'm not this should be closed yet.

**Comment by wakenmeng** [comment]
Still got 500 Server Error

**Comment by RRadziejewski** [comment]
5xx: Server Error , what's going on ?

**Comment by Ancharca** [comment]
error with code runner. said this problem is with time of frame loading 

<img width="485" height="416" alt="Image" src="https://github.com/user-attachments/assets/bec4aa5d-31e6-4f61-83aa-70580c4380a6" />
