### ISSUE TITLE
"add to Collection" isn't working anymore (for now)

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1504]
Hi,

I just tried to add a kata to a collection and the panel doesn't show up, either using the icon (under the name of the kata) or the link "add to collections" in the discourse or the solutions pages.

**Comment by Blind4Basics** [comment]
well, working again... x) (might be the same kind of bug than the one about the comments: sometimes, it's not possible to open the comments under solutions, for no apparent reason...)

**Comment by dinglemouse2250** [comment]
Every time I create a new Kata I add it to my own collection.

But clicking the collection icon *never* works from the Kata Search page.

It only works if I do
a) click on the Kata (as if I was doing to do it)
b) refresh the page and 
c) then click on the collection icon
