### ISSUE TITLE
Cannot submit Katas

### ISSUE THREAD

**Issue by nickdbush** [Codewars/codewars.com#1506]
This is the second kata now that I've completed. I have run the sample tests and they pass. I have pressed "attempt", and the tests pass too. However, the submit button does not appear and therefore I cannot complete the kata.

https://www.codewars.com/kata/find-the-nth-digit-of-a-number/train/cpp

![image](https://user-images.githubusercontent.com/10998201/42325238-83900d1c-805d-11e8-8b7c-d1019cdf5462.png)

A similar thing happened with https://www.codewars.com/kata/two-to-one/train/cpp, but the output pane for the sample tests is empty (even when the script outputs something to the console). The screenshot below is after having clicked "attempt".

![image](https://user-images.githubusercontent.com/10998201/42325452-399254bc-805e-11e8-85a3-6ee58606a5fd.png)

This could just be me being incompetent, I don't know,

**Comment by FArekkusu** [comment]
Your code is wrong. This is a problem with C++ assertions (probably present in some other languages) - your code gets rejected because it can't pass the tests, but **there's no message about it**.

**Comment by nickdbush** [comment]
I thought I was going mad! Thanks for the info, I assumed something like that was the case but for the life of me I couldn't find anything on the internet about such a case.
