### ISSUE TITLE
Server Error(500) When trying to sign up

### ISSUE THREAD

**Issue by KenKariuki** [Codewars/codewars.com#1507]
I have been trying to sign up for codewars for the last two days with no success..I get an error message - Looks like a server error.Check the screenshot

![screenshot from 2018-07-07 08-43-55](https://user-images.githubusercontent.com/31533546/42407290-f7c95868-81c1-11e8-9b45-7a56eccd53c2.png)

**Comment by saih02** [comment]
Same problem

**Comment by richClubb** [comment]
I actually managed to sign in yesterday. I'm not sure if the server proceedure is just taking too long under certain circumstances and kicking people out.

**Comment by CubedDavid** [comment]
Same problem. I have tried at regular intervals over the last month to sign up. Nothing seems to be getting fixed.

**Comment by pdizzle** [comment]
Getting same error 7/17 10:10a MDT

**Comment by laboro18** [comment]
I am also facing this issue, seems like many others are as well: #1482 #1480 #1453 
Its been 6 weeks since this issue was first raised, what is happening?

**Comment by pdizzle** [comment]
I was able to successfully sign in/register later in the day.. perhaps server load?

**Comment by KenKariuki** [comment]
I was also able to successfully register a few days ago..Seems a problem in the server sometimes maybe
