### ISSUE TITLE
Execution Timed Out

### ISSUE THREAD

**Issue by khoucem** [Codewars/codewars.com#1509]
I'm new to coding , i'm currently learning c# , but i'm facing this issue ( I don't know if my code is the source of the problem or not ) , my code (as i think ) works pretty fine in visual studio 2017 .
kata name : Factorial decomposition . 
Here is my code : 
`
               using System;
               using System.Numerics;

               class FactDecomp
                { 
                public static string Decomp(int n)
	        {
                  BigInteger fn = factorial(n);
		string primeNumbersMethod ="";
                for (BigInteger i = 2;i<= fn;i++)
                {
                    int p = 0 ;
                    if (prime(i))
                    {
                        while (fn % i == 0)
                        {
                            p += 1;
                            
                            fn = fn / i;
                        }
                        string c = Convert.ToString(i);
                        string cp = Convert.ToString(p);
                        if ( p == 1)
                        {
                            primeNumbersMethod += ( c + " * " );
                        }
                        else if ( p == 0)
                        {
                            primeNumbersMethod += "";
                        }
                        else 
                        {
                            primeNumbersMethod += (c + "^" + cp + " * " );
                        }
                        
                    }
                } 
                return primeNumbersMethod.Remove(primeNumbersMethod.Length - 3);
	}
                    public static BigInteger factorial (BigInteger num)
                    {
                     BigInteger Factorial = 1;
                     for ( BigInteger k = 1; k<= num; k++)
                     {
                    Factorial *= k;
                   }
                    return Factorial;
                 }
                public static bool prime (BigInteger nu )
               {
                bool primeBool = true;
                for (BigInteger j=2;j<nu;j++)
                {
                    if (nu == 2)
                    {
                        primeBool = true;
                        break;
                    }
                    if (nu % j == 0)
                    {
                        primeBool = false;
                        break;
                    }
                    else
                        primeBool = true;

                }
                return primeBool;
            }
            }`

the problem starts after i ad this line 
`return primeNumbersMethod.Remove(primeNumbersMethod.Length - 3);` 

Please don't tell me that the web site has this issue , as i starting to like it .

thanks for your time .

**Comment by kazk** [comment]
Please open kata specific issue/question on [the kata discourse page](https://www.codewars.com/kata/factorial-decomposition/discuss/csharp). There're accepted solutions with C# for that kata that finishes under 2s, so this is not the issue of our service.
