### ISSUE TITLE
Post Sign Up - Consistent Server 500 Error

### ISSUE THREAD

**Issue by laboro18** [Codewars/codewars.com#1512]
![1png](https://user-images.githubusercontent.com/39576902/42914741-8df9da5e-8b2e-11e8-8102-5105b31ae49a.png)

I have been trying to sign up for more than 3 days now. Consistently getting this server 500 error.

This is not a new issue, indeed I made an earlier [comment ](https://github.com/Codewars/codewars.com/issues/1507#issuecomment-405794082)but the owner of that issue decided to close the issue. Many others have faced this or are facing this as well: #1507 #1482 #1480 #1453 #1450 #1358 

Its been 6 weeks since this issue was first raised, what is happening?

**Comment by kazk** [comment]
Sorry for the late response. This issue will be tracked at #1516
