### ISSUE TITLE
Cannot delete my own kata

### ISSUE THREAD

**Issue by vlukyanets** [Codewars/codewars.com#1513]
![image](https://user-images.githubusercontent.com/7885242/42987607-81167aca-8c02-11e8-9bb3-74de34bb4bed.png)

1. I created new kata
2. Made some changes, saved it
3. Try to delete

ER: Kata is deleted
AR: Kata deleting process is stuck

**Comment by FiveCrayFish973** [comment]
CW server is usually too slow, try again a bit later and it ought to work out.

**Comment by vlukyanets** [comment]
I tried five times, but always deleting process is stucked on the end of progress bar.
Could you find more information in server logs?

**Comment by vlukyanets** [comment]
I didn't published my kata, just save

**Comment by kazk** [comment]
Closing as duplicate of #1043
