### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by epangar** [Codewars/codewars.com#1515]
I'm trying to solve this kata using Javascript:

https://www.codewars.com/kata/are-they-the-same

Whenever I press "Attempt" I get an error:

++++++++++
Network Error
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
++++++++++

This has been happening to me with this particular kata for some time now. How should I proceed? I opened an issue in the kata's discourse, but it's not a problem of the kata.

EDIT: after trying again I opened the Google Chrome console and apparently it's getting a 502 error.

**Comment by kazk** [comment]
I'll look into this, but I don't see any major problems reported.

> This has been happening to me with this particular kata for some time now.

It might be that your solution for this kata is crashing in unusual way that's not handled well by our service. I'll see if I can reproduce this.

**Comment by kazk** [comment]
Are you solving with JavaScript? The tests for JavaScript is leaking global variables and that might be causing some infinite loop if your solution also leaked the same variable. That doesn't explain the server returning 502, but it might be the cause of unusual crash that's not handled well.

Does this happen with the sample tests as well?

**Comment by epangar** [comment]
I'm using Javascript, and the sample tests are passed successfully. 

I don't use global variables. This is the code i'm trying:

`function comp(array1,array2){
  //your code here
  
  var obj = {}
  var obj2= {}

  for (i=0;i<array1.length;i++){
    obj[array1[i].toString()]=Math.pow(array1[i],2);
    obj2[array2[i].toString()]=array2[i]
  }
  
  for(key in obj){
    if(obj.key!==obj2.key){
      return false
    }
  }

  return true  
}`

**Comment by epangar** [comment]
It worked fine. Thank you! :)

**Comment by kazk** [comment]
Thanks for confirming. I'll try to look into the root cause and see if I can prevent this from happening.

**Comment by kazk** [comment]
The root cause was identified and the fix was deployed.
