### ISSUE TITLE
Suggestion: Count Lines of Code?

### ISSUE THREAD

**Issue by gennadiryan** [Codewars/codewars.com#1517]
When solving kata codewarriors often do one of two things: they solve the kata using clever, quick methods resulting in very short programs (code golf), or when this is impractical they opt to take up plenty of space with indentation and comments in order to create a clearly readable and maintainable piece of code. Either way, it would be interesting to see, for each kata, a figure for average lines of code used to solve (broken down by language, of course).

**Comment by Voileexperiments** [comment]
What *exactly* do you want to achieve by that? For almost all languages newlines are cosmetic and arbitrary. People can add as many as them as they want. That's like counting how many variables are instantiated/assigned for a solution: it's a metric that makes completely no sense at all.

Also, are you trying to imply *again* that "clever, quick methods = code golf" and "clever, quick methods is the opposite of readable and maintainable"? No, it doesn't work this way. Short code are upvoted for a good reason: they're concise, and hence readable and maintainable.

**Comment by Voileexperiments** [comment]
It still has the same problem: the quality of code has not much to do with the length/number of lines of the code. In fact you can't even say so for comments: you could have a whole page of comment that is useless and unhelpful; meanwhile, some people are advocating for self-documenting code which allegedly does not need any comments (which I strongly doubt this idea, but, well, such stance exists, so...). You *could* say that informative code often has informative, comprehensive comments, but it's just at best an "often", and is far from having anything but a very slight correlation.

At the end of the day, if you're adding a metric, it ought to be *useful*. Dumping a million metrics is far from extracting the key *features* of the code.

**Comment by gennadiryan** [comment]
Well, being less involved in codewars than yourself I'll defer to your judgement that it probably wouldn't add much to the platform, especially since this idea hasn't gotten much attention otherwise.
