### ISSUE TITLE
Getting "Uh oh! Something went wrong! (500) Error" whenever trying to translate my kata (See Details) 

### ISSUE THREAD

**Issue by DivyanshBatham** [Codewars/codewars.com#152]
Whenever I try to translate my kata (<A HREF="http://www.codewars.com/kata/complete-the-pattern-number-1/translations">Complete The Pattern #1</A>) or try to approve a translation I get the '500' Error. I first saw this when Azuaron submitted Haskell translation, and I tried to approve it (about 3 weeks ago).

**Comment by MMMAAANNN** [comment]
This is similar to issue https://github.com/Codewars/codewars.com/issues/120
