### ISSUE TITLE
Math support request (question)

### ISSUE THREAD

**Issue by FiveCrayFish973** [Codewars/codewars.com#1521]
Does CW have any support for MathJax or other such related things ? If they do can you inform me (or give a link) explaining how it works. If not can we add it to the ( already extremely long and boring) list of stuff that CW can add in the (near or far) future. I'd help a lot since creating Math related Kata's becomes a pain.

**Comment by kazk** [comment]
I don't think there is. @jhoffner correct me if I'm wrong.
I'll close this and label #1527 as feature request.
