### ISSUE TITLE
500 error for URL http://www.codewars.com/kata/find-nth-digit-of-a-number

### ISSUE THREAD

**Issue by john12321** [Codewars/codewars.com#1522]
I got this message when I followed an external link to this kata
_Looks like there was a server error! (500)_
followed by this message 
_Problem: Document(s) not found for class CodeChallenge with id(s) find-nth-digit-of-a-number. Summary: When calling CodeChallenge.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): find-nth-digit-of-a-number ... (1 total) and the following ids were not found: find-nth-digit-of-a-number. Resolution: Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples._

__

**Comment by john12321** [comment]
Hi,
It was a link provided as part of my Northcoders pre-course. I'll let them
know it needs updating. Cheers, John

**Comment by kazk** [comment]
Thanks :)
