### ISSUE TITLE
NASM code blocks fail to appear on description

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1523]
It's been quite a few months since NASM first appeared on Codewars but NASM code blocks are still not shown to NASM solvers when I mark them as such, e.g.:

<pre><code>```nasm
global add
section .text
add:
  mov eax, edi
  add esi
  ret
```</code></pre>

I've definitely tried `asm` as well but it doesn't show up for NASM solvers either. @kazk Do you happen to have any idea what I should mark a code block with to make it available for NASM solvers or is it not possible yet?

**Comment by kazk** [comment]
Fixed
