### ISSUE TITLE
Add math typesetting support in descriptions

### ISSUE THREAD

**Issue by FiveCrayFish973** [codewars/codewars.com#1527]
So I'm fond of making Kata's that are related to Math/Physics/Chemistry.(honestly I can't believe no one has opened an issue about this) 

Can we kindly have support for Latex / MathJax or a similar utility in order to make creation of above mentioned Kata's a whole lot easier. 

I will be awaiting a response from the dev team on whether it is feasible or not

tagging for attention @jhoffner , @kazk

**Comment by FiveCrayFish973** [comment]
@kazk thanks, for taking the time to take a look. It'd be really great if it could be done

**Comment by FiveCrayFish973** [comment]
@kazk thanks, for taking the time to take a look. It'd be really great if it could be done

**Comment by DonaldKellett** [comment]
I'd like to second this feature request. Now that we have Lean support on Codewars and a significant portion of Lean users are pure mathematicians, we'd like to author more theorem-proving Kata more suited to their tastes, and that sometimes means using mathematical notation familiar to them in the Kata description (as opposed to, say, ASCII workarounds). But it's currently rather difficult to do so in a pleasant manner; for example, in [Mathematical Analysis - Limits of Sequences \#1](https://www.codewars.com/kata/5e997f77ea84170016600045), I've had to typeset the mathematical notation in an external editor, take a screenshot of the rendered output, post the images on imgur and paste the links in the description ... which just looks horrible. Adding MathJax support or similar would probably make typesetting mathematics in Kata descriptions much easier and produce a much more pleasant visual output.

**Comment by kazk** [comment]
@DonaldKellett Yeah, I was thinking the same. I did experiment with [KaTex](https://katex.org/) some time ago and it was pretty easy to add support using Markdown code block:

````
```katex
```
````
or maybe
````
```math
```
````

This will work for places where the client side library is used to render the markdown like kata descriptions, but it'll just show the TeX markup anywhere else.

**Comment by DonaldKellett** [comment]
Would it be possible to display math inline though using built-in KaTeX / MathJax support or similar? See the revised Kata description for [Mathematical Analysis - Limits of Sequences \#1](https://www.codewars.com/kata/5e997f77ea84170016600045) for an example (I achieved that effect for now by generating MathML code from [the MathJax website](https://www.mathjax.org) and copy-pasting the output into the Kata description).

**Comment by kazk** [comment]
MathML is not supported by Chrome. See https://caniuse.com/#feat=mathml

For inline Math typeset, we'll need some way to detect it.
I think I've seen some Markdown extension that does it with `$`:
````markdown
`$ math $`
````

**Comment by kazk** [comment]
I'll go with `math` code block and code span starting and ending with `$`.

````markdown
# KaTeX Example

Suppose `$ x_n \leq l \leq y_n $` and `$ \lim_{n\to\infty} (x_n - y_n) = 0 $`,
prove that `$ \lim_{n\to\infty} x_n = \lim_{n\to\infty} y_n = l $`.


```math
x_n \leq l \leq y_n
```

```math
\lim_{n\to\infty} (x_n - y_n) = 0
```

```math
\lim_{n\to\infty} x_n = \lim_{n\to\infty} y_n = l
```
````

![image](https://user-images.githubusercontent.com/639336/79712499-d8eba200-827f-11ea-9ada-1b507799edf0.png)

**Comment by kazk** [comment]
Deployed. @DonaldKellett Let me know if you find any issues. It's currently only for the kata description and not comments.

**Comment by DonaldKellett** [comment]
Thanks for implementing KaTeX support, I've updated my 4 analysis Kata to use KaTeX instead and it's working like a charm ❤️

**Comment by pglutz** [comment]
@kazk Does this also work for kumite? I was trying to write a kumite with some latex in the description and it didn't seem to work (both inline and display mode).

**Comment by kazk** [comment]
No, it only works for kata descriptions at the moment. Anywhere else, the markdown is rendered on the server and doesn't handle this syntax. This will probably change in the future, but not anytime soon.

**Comment by pglutz** [comment]
Okay, thanks for letting me know.
