### ISSUE TITLE
Unable to re-publish a java translation of a kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#153]
I have written a modification of the tests of the java translation I made of:

http://www.codewars.com/kata/5509609d1dbf20a324000714/

I was able to re-edit it but there is no way to obtain its re-publication. For hours I get:
"Please wait while we publish
We are validating your code and publishing your changes. This shouldn't take too long."

**Comment by bkaes** [comment]
Did you try the following yet?

1. Copy your code/changes to notepad or some other location.
2. Refresh the page (ignore the cache if possible; Ctrl+Shift+R or another combination should do it)
3. Paste your changes and try to publish again.
4. If it still fails, try about 5 minutes later.

**Comment by g964** [comment]
It worked, thanks again!

**Comment by bkaes** [comment]
I should probably add tricks like this to the guide. _And_ file an issue.
