### ISSUE TITLE
Cryptic occasionall error on refresh

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#1535]
I've seen it mentioned on chat by another user, now encountered it by myself:

syntax error, unexpected modifier_rescue, expecting ')' ...miter(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:20: syntax error, unexpected ')', expecting tSTRING_DEND ...(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:21: unknown regexp option - b /codewars/app/views/users/stats/_progress.html.slim:24: syntax error, unexpected keyword_end, expecting tSTRING_DEND ...er.safe_concat(("</div>")); end; @output_buffer.safe_concat(... ... ^ /codewars/app/views/users/stats/_progress.html.slim:60: syntax error, unexpected keyword_ensure, expecting tSTRING_DEND /codewars/app/views/users/stats/_progress.html.slim:62: syntax error, unexpected keyword_end, expecting tSTRING_DEND

It comes together with HTTP 500 page, and encountered it when refreshing main profile page. I am not able to reproduce it consistently.

**Comment by FiveCrayFish973** [comment]
Your is far more interesting. I got : 

> The operation: #<Moped::Protocol::Command @length=83 @request_id=12285 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="codewars-production.$cmd" @skip=0 @limit=-1 @selector={:getlasterror=>1, :safe=>true} @fields=nil> failed with error nil

**Comment by DanL12186** [comment]
This just happened to me as well trying to duplicate it. It also coincided with getting logged out, unsure if that's related; when I tried again there was no issue (this time I wasn't logged out).

**Comment by FArekkusu** [comment]
This happens very often for me both trying to open my profile, and other users' profiles.

**Comment by dz4485** [comment]
Reproduces here. 
Screenshot: Attached here:
![capture](https://user-images.githubusercontent.com/6724669/44620969-aa4cd680-a8a6-11e8-8bba-5a42ace8a357.PNG)

Text: /codewars/app/views/users/stats/_progress.html.slim:20: syntax error, unexpected modifier_rescue, expecting ')' ...miter(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:20: syntax error, unexpected ')', expecting tSTRING_DEND ...(user.honor_ranking rescue '?')}"))).to_s)); ... ^ /codewars/app/views/users/stats/_progress.html.slim:21: unknown regexp option - b /codewars/app/views/users/stats/_progress.html.slim:24: syntax error, unexpected keyword_end, expecting tSTRING_DEND ...er.safe_concat(("</div>")); end; @output_buffer.safe_concat(... ... ^ /codewars/app/views/users/stats/_progress.html.slim:60: syntax error, unexpected keyword_ensure, expecting tSTRING_DEND /codewars/app/views/users/stats/_progress.html.slim:62: syntax error, unexpected keyword_end, expecting tSTRING_DEND

**Comment by kazk** [comment]
This is fixed now.
