### ISSUE TITLE
Connection breaks down after a while

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#154]
The WebSocket connection will break down after some time. This leads to "Failure to connect to server" messages. A page refresh fixes it.

I suspect this to be the source of errors like #153 or "Unknown error".

**Comment by coryallegory** [comment]
I have experienced this a couple times today, didn't catch on that it was a simple refresh fixing it. The red icon at the top left appears to keep spinning even once the error output returns

**Comment by itsgreggreg** [comment]
Happens to me all the time. Usually a refresh fixes it, sometimes it doesn't.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
