### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by pharesdiego** [Codewars/codewars.com#1544]
I saw this error while trying to access my profile and other's profile
![error 505](https://user-images.githubusercontent.com/22730222/44531026-c6d9ea80-a6bd-11e8-9aba-8f8c8796ed61.png)

I'm not able to reproduce the issue, it just happens sometimes but it has been happening frequently since yesterday (at least to me)

**Comment by hobovsky** [comment]
https://github.com/Codewars/codewars.com/issues/1535

**Comment by kazk** [comment]
Closing as duplicate of #1535
