### ISSUE TITLE
How to use the preloaded section with Typescript?

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1548]
Do we have to import something and what?

**Comment by kazk** [comment]
Preloaded is concatenated with solution so you shouldn't need to do anything.
I don't like it, but I had to keep it like that for backwards compatibility :(

**Comment by g964** [comment]
When I put my testing function (which is rather long) in Preloaded section I get:
```
/runner/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
spec.ts (14,9): Cannot find name 'testing'. (2304)
...
```

**Comment by kazk** [comment]
@g964 are you exporting it?

**Comment by g964** [comment]
Now at last it works. I am very sorry to abuse your kindness! Thanks a lot once more!
