### ISSUE TITLE
Retired Katas can not be solved still show up under not completed Katas

### ISSUE THREAD

**Issue by Darnor** [Codewars/codewars.com#155]
When I was looking for Katas I haven't completed I found the following:

http://www.codewars.com/kata/greetings/java

It's retired but you can still try to train on it. Problem is you're unable to ever complete it because you can't do a "Submit Final".

I think you should still be able to complete them just without them giving you any honor. Or else just unlock the solution and don't let it show up under "Kata I have not completed" (Using the approved and beta filter).

**Comment by GiacomoSorbi** [comment]
I think I submitted a similar report a long while ago: +1.

**Comment by kazk** [comment]
Closing as duplicate of #1565 which also mentions draft kata.
