### ISSUE TITLE
Can be logged out while doing kata - enfuriating.

### ISSUE THREAD

**Issue by AndreasFVangen** [Codewars/codewars.com#1551]
I were logged out of the website while completing a kata. The main issue is that I were not warned when delivering and were brought to a "PLEASE LOGIN TO LOOK AT KATAS" -> WHICH led to every single fucking bit of code I made being just removed, gone. This is beyond enfuriating, if it weren't for this site being actively used in my course I would have went through the trouble and blacklist the site so I'd fucking remember to never come back.

I'm *slightly* angry. But I'll try to do my best at giving info to relive this shithole so you can do something about it if you wish. My pc went to sleep mode once while doing it(Has happened before and were no problem at all those times.) and that's about it for any oddities that might have caused it.

**Comment by DanL12186** [comment]
You still get credit even if you're logged out after you submit the kata. Your code is saved in solutions.

**Comment by FiveCrayFish973** [comment]
Note to users who are polite, plz do not read my comment. thanks.

Next time you feel like being an ass hole kindly go back to your room and scream all you want and then when you are done (judging by the trash you wrote) come back and write a sane comment. 

Hope you enjoyed reading my comment (you seem to have enjoyed writing that trash). I did my best not to act like you (as you can see I failed)

A sane comment if you learned your lesson : 

It won't matter, you earn honor even if you get logged out and your solution is saved and you will have lost nothing.
