### ISSUE TITLE
My progresses have been resetted

### ISSUE THREAD

**Issue by raktian** [Codewars/codewars.com#1554]
This morning my rank was 6 kyu. Now is 8 kyu and it seems like my account has been resetted cause i've also received the tutorial messages that appear when a new account is created. How is it possible?

**Comment by FiveCrayFish973** [comment]
@raktian can you give a link to your account ?

**Comment by raktian** [comment]
https://www.codewars.com/users/raktiab

**Comment by FiveCrayFish973** [comment]
@raktian you sure this is your account, it shows complete reset ? You should check if you had used some other email to create account and now used another thus creating a new account. In the mean time. 

@kazk plz take a look at this. Could be potentially serious.

**Comment by raktian** [comment]
@FiveCrayFish973 I'm sure, that's the only account i've ever created on codewars

**Comment by jhoffner** [comment]
@raktian when did you sign up? This info will help us debug.

**Comment by raktian** [comment]
@jhoffner August 23

**Comment by jhoffner** [comment]
@raktian can you send me the link to your profile?

**Comment by raktian** [comment]
@jhoffner https://www.codewars.com/users/Raktian now i notice that the username is different but this morning i logged in with the same email and pw and it brought me to this account https://www.codewars.com/users/raktiab
