### ISSUE TITLE
Code assigned to temporary-looking user name

### ISSUE THREAD

**Issue by tom-mur** [Codewars/codewars.com#1555]
Hi,

I submitted a solution to kata [Blaine is a pain](https://www.codewars.com/kata/59b47ff18bcb77a4d1000076) and encountered a site error that logged me out.

I logged-in again, and saw that the Solution box on the training page was blank. I populated it again, and submitted successfully.

Browsing the recent solutions I confirmed that my new submission was visible; however **my previous submission is also visible** and assigned to [a new user "guest_w944pcclo5u"](https://www.codewars.com/users/guest_w944pcclo5u).

Obviously no harm done and easy to clean up but it maybe hints at some database weirdness.

Thanks
tommur

**Comment by kazk** [comment]
Thanks for taking the time to report this. There shouldn't be a problem since solutions associated with `guest_xxxx` users are deleted after certain period of time along with the user.
