### ISSUE TITLE
Update Terms of Conditions to ban users with more than one free account at any given time

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1558]
@jhoffner @kazk 

Currently, certain cheaters such as "no one" are known to possess at least 3-5 alt accounts ( @Blind4Basics @Voileexperiments @docgunthrop @DanL12186 feel free to provide objective proof of this in the comments to support this claim, if any ), *presumably* to forfeit Kata on those accounts so that other's solutions can be copy-pasted and submitted on the main account.  And while there seems to be a rule that Codewarriors can't forfeit Kata more than one above his/her rank, I wouldn't rely on it considering how Codewars has a habit of over-reliance on client-side validation.

The proposal - follow in the footsteps of well-known organizations such as GitHub and Facebook and add a rule to the Terms of Conditions stating that anyone confirmed to possess **more than 1 free account** at any given time are immediately ban-worthy, no questions asked.  The reason?  *Why on earth* would *anyone* need more than 1 free account for normal CW usage?  And if someone loves CW enough to open an alt just to test the site for bugs and report them (which *some* power users openly admit to do) then that person must also love CW enough to pay for Codewars Red on his/her main account.

**Comment by FArekkusu** [comment]
You've completed many katas and/or editted them through the editor (fixing description, bugs, absence of tests, whatever) and want to complete them in another language being able to filter the katas correctly and possibly gaining `%` in said language? - Sorry, you're banned.
You've found a bug in CW system but can't verify it from your main account (#1532)? - Sorry, you're banned.
You've messed up the authentication process (#1554) and accidentally created a new account? - Sorry, you're banned.

1) There're quite a few reasons why a user may need an alt account, cheating is only one of them.
2) Enforcing users to but CW Red is not securing their safety, it's discrimination. Firstly, an example: in theory I have an alt account which I used to verify a CW bug, on practice it was created through 10-minute mail and I have zero idea what the credentials are, effectively making that alt **inaccessible** to me. So *in your opinion* do I have just one account and it's fine, or two accounts and I'm actually one of the villains? Secondly, CW Red was never designed to divide the users into "elite" w/ subscription and "plebeians" w/o subsription (this happens in well-known Twitch community, so do we have to follow in their footsteps as well?). Are there users who would like to have the subsription but can't afford/buy it (#1317)? Yes. Are there users who, on the other hand, find this subscription waste of money? Also yes. Should CW Red be used to filter "good" people from "bad" people? I think you can guess my opinion.
3) What if a cheater buys CW Red subsription himself/herself? How can you be so sure that a mischievous user won't register a legit account w/ a subscription which they're planning to use, and create an alt to simply "boost" the progress on the main one?
4) You **can't** catch all of them this way. The user may modify the solution so it's doesn't get grouped up with the others, they may never participate in any discussions from the alt account to not get recognized by somebody (for example, `__i` is using the same speech patterns as `no one` so it's quite obvious this is the same person), they can use VPN to change their IP while using the alt account so in case the admins decide to scan the database for duplicate user IP's, they'll get no results.

**Comment by error256** [comment]
There's no way to reliably detect this. Whatever the method, it will require more manual checks than cathing cheaters like now and will probably still cause troubles for some legitimate users. The most stubborn cheaters that it's supposed to stop won't care and it will be a point of (dis)honor for them to keep going.

**Comment by kazk** [comment]
Thanks for the suggestion, but we're not going to do this.
I don't think this is effective approach. Even if it is to some extent, I don't think it's worth the trouble.
