### ISSUE TITLE
500 error when i view my completed kata

### ISSUE THREAD

**Issue by anoshkin** [Codewars/codewars.com#1559]
My name - axel_n

Error details:
The operation: #<Moped::Protocol::Command @length=83 @request_id=529 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="codewars-production.$cmd" @skip=0 @limit=-1 @selector={:getlasterror=>1, :safe=>true} @fields=nil> failed with error nil

**Comment by hobovsky** [comment]
Also mentioned by @FiveCrayFish973 here: https://github.com/Codewars/codewars.com/issues/1535#issuecomment-414457178

**Comment by kazk** [comment]
Closing as duplicate of #1535
