### ISSUE TITLE
Hidden comment (spoiler) still available to see at dashboard page.

### ISSUE THREAD

**Issue by adam-tokarski** [Codewars/codewars.com#156]
It may be matter of cache, but I saw comment in dashboard that I recognized as spoiler. I flagged it so, and is now hidden: 
![image](https://cloud.githubusercontent.com/assets/10441317/9032771/443219c4-39c2-11e5-8bc2-d57580b16b04.png)

but at main page still is available to see:

![image](https://cloud.githubusercontent.com/assets/10441317/9032780/606f7078-39c2-11e5-86cf-ce0432f1d63c.png)

**Comment by adam-tokarski** [comment]
Ok, nevermind, it is hidden now. Sorry for bother you!

**Comment by MMMAAANNN** [comment]
This is some kind of caching issue. I've seen similar thing many times, it takes a minute to actually hide the spoiler content.
