### ISSUE TITLE
бля

### ISSUE THREAD

**Issue by eturin** [Codewars/codewars.com#1560]
A few things to check first:

Is the issue you are filing related to a specific kata?

If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Is the issue you are filing related to how a specific language behaves when being executed?

If so then it will likely be better to file the issue on our [github.com/Codewars/codewars-runner-cli/issues](https://github.com/Codewars/codewars-runner-cli/issues) repo, which is where we have our open source code execution functionality. You also may want to look into forking that repo and fixing the issue yourself if you have the means.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.

Никуя не робит уже давно на хроме. Че за нах?
![aliens_vs_predator_predator_1](https://user-images.githubusercontent.com/16459628/44903026-26667480-ad14-11e8-88fa-355591f3a9f6.jpg)

**Comment by FArekkusu** [comment]
This guy is only saying "CW is working badly on Google Chrome for a long time already".

@kazk, you should probably close this one.

**Comment by kazk** [comment]
Thanks @FArekkusu.

@eturin sorry for the inconvenience. If you're using Windows, maybe comments in #1157 can help.
