### ISSUE TITLE
can't reach a validation page

### ISSUE THREAD

**Issue by AnaMilten** [Codewars/codewars.com#1568]
Hi,

2 days ago I trained on a kata (vowel count) and passed it but i was unlogged.
When i logged, i tried to pass it again but it was "already submitted" and all i could do was to skip or to read the solution...
But on my profile the kata isn't validate.
So i can't validate the kata because it's validated but my profile said it's not !
Please help me ! I

**Comment by MignonGakuba** [comment]
hai

**Comment by kazk** [comment]
Sorry, I couldn't understand the issue. In general, you should be able to submit the same solution again, but you might not get honor points if you read the solution before completing.
