### ISSUE TITLE
Honor points awarded even after viewing solutions

### ISSUE THREAD

**Issue by Crackeshwar** [Codewars/codewars.com#1569]
Hi,
I viewed the solutions to the below mentioned Kata, and when I completed my solution I still got Honor points. I think there is a bug, admin please take a look.
https://www.codewars.com/kata/consecutive-strings/csharp

**Comment by Crackeshwar** [comment]
Sorry for the late reply, my username is Gorgoroth...

**Comment by Crackeshwar** [comment]
Sorry for the late reply.. my username is Gorgoroth

**Comment by kazk** [comment]
I think it's correct. You've completed `84` kata and got points for `83`. It's also in the database that you're not eligible to get points on that kata because you saw solutions.
Maybe the displayed honor points was outdated and submitting triggered an update.
