### ISSUE TITLE
Wonky screen 

### ISSUE THREAD

**Issue by bkoken** [codewars/codewars.com#1572]
Hey guys. Is CodeWars not really meant for iOS? Just have impossible time doing any ‘training’ once I hit the ‘train’ tab. That part of screen goes mental on me and can’t do anything. I wish there was an iOS app but there isn’t. Am I missing a setting somewhere? Thanks very much

Bruce Koken
8th kyu

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c0q) by [Unito](https://www.unito.io)

**Comment by Voileexperiments** [comment]
Is this #1397 ?

**Comment by kazk** [comment]
Thanks
