### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by e-mihaylin** [Codewars/codewars.com#1574]
Bunch of related problems:
1) Every day (I quess every 24 hours) I am logged off the platform.
For example: I can log in at 10am, be online due to 18pm, and next day I'll be logged of at 10am.
May be a feature, not a bug - but better to reroll auth to avoid such problems.

2) Then I press log in button, do the auth (via github).
And I have other codewars tabs in browser.
If I refresh any (not authed, expired) -> I'll have all of them exprired.
Bugs not all the time, but very often.

3) If I was working on kata, I can be logged off after succesfull submit.
If I log in and then use browser back button (to kata solutions) -> I am logged off.

4) When I finally get to the kata solutions/my solution (after that auth mess)
I have 'There are no solutions yet for this kata' instead of my solution (which was submitted correctly)
But in my profile/completed_solutions everything is ok (and the honor comes with some dely)

5) Sometimes it just logs me off on code submit during daily session.
(Logged in at 11, logged off on code submit at 16 with successfull submit 5 minutes before)

**Comment by e-mihaylin** [comment]
No feedback yet?

**Comment by FiveCrayFish973** [comment]
@e-mihaylin possibly because these are all recorded issues and CW team as far I can tell has done nothing to fix it whatsoever (issue also opened by me a couple of months ago, still to be fixed)

**Comment by FiveCrayFish973** [comment]
@e-mihaylin possibly because these are all recorded issues and CW team as far I can tell has done nothing to fix it whatsoever (issue also opened by me a couple of months ago, still to be fixed)

**Comment by FiveCrayFish973** [comment]
@e-mihaylin possibly because these are all recorded issues and CW team as far I can tell has done nothing to fix it whatsoever (issue also opened by me a couple of months ago, still to be fixed)

**Comment by Voileexperiments** [comment]
Well, there's #1, so...

**Comment by FiveCrayFish973** [comment]
@Voileexperiments ... yeah, forgot that was still around.

**Comment by FiveCrayFish973** [comment]
@Voileexperiments ... yeah, forgot that was still around.

**Comment by e-mihaylin** [comment]
Moved the details to https://github.com/Codewars/codewars.com/issues/1
Close as duplicate then.
