### ISSUE TITLE
Account lapsed or something, can't log in?

### ISSUE THREAD

**Issue by feminaprovita** [Codewars/codewars.com#1576]
I created my codewars account back in July, but only poked around for like 5m thereafter before I got derailed by other coding sites... Now I want to dive back in, but can't log in!

- When I try to sign in with github, it tells me there's no user associated with that account.
- When I try to create a new account with github and the same email address and username, it throws an error (screenshot below).
- When I try to create a new account with github and a different email address but the same username, it tells me that username is already taken.

This tells me that my account isn't really lost, just...disconnected or something.

I'm pretty attached to having my same username on all the websites. How can I get back into my account?

<img width="536" alt="screen shot 2018-09-27 at 6 44 54 pm" src="https://user-images.githubusercontent.com/40221833/46180702-d71e5000-c28f-11e8-8275-9a4fd4f9124d.png">

**Comment by danielelectronics** [comment]
I just discovered Codewars today and was really excited to try it, but I have been getting this while trying to create my account all day. My Cloudflare Location was Atlanta. Between the website being down and the C initiation challenge being misleading (you can multiply an int and a referenced char pointer in C no problem) I am really disappointed in Codewars so far.

**Comment by feminaprovita** [comment]
Resetting my password did it! Thank you!

I was 100% certain I'd registered with github, but maybe it got separated when I revoked and tried to reauthorize my github account earlier today? Or maybe my memory is playing tricks on me, I guess. In any case, _thank you!!_
