### ISSUE TITLE
C# version in the UI (v7.3) doesn't match the actual version (v7.0)

### ISSUE THREAD

**Issue by SerGreen** [Codewars/codewars.com#1577]
In the dropdown selector of language version there's C# 7.3, but the code actually is being compiled with 7.0 version, and if you use a feature from 7.1+ version (e.g. `default` keyword), you get an error:  
>`error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.`  
  
To reproduce:  

1. Open any C# Kata (e.g. "[Sum of positive](https://www.codewars.com/kata/sum-of-positive)")  
1. Select `7.3` language version  
1. Enter code: `int a = default;`  
1. Run

***
![2018-09-28_032113](https://user-images.githubusercontent.com/4000373/46181448-81b56380-c2ce-11e8-8b60-694eafdcb558.png)
![2018-09-28_032050](https://user-images.githubusercontent.com/4000373/46181453-8aa63500-c2ce-11e8-80d6-457a32730208.png)

**Comment by kazk** [comment]
Thanks for reporting.
We're using .Net Core 2.1.302 so it should have C# 7.3. I'll look into it.

**Comment by SerGreen** [comment]
When i create a new project in Visual Studio it's set to language version 7.0 by deafault, even though i have 7.3 installed. So in order to change it i have to go and manually do `Project properties > Build > Advanced... > Language version > C# 7.3`. Maybe this issue is related to this too.

**Comment by kazk** [comment]
The fix is deployed :)
