### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by AlbinTheander** [Codewars/codewars.com#158]
Got this in my messages list:

translation missing: en.models.code_snippet_translation_published_notification.single.heading.kata_coauthor
15 hours ago

**Comment by MMMAAANNN** [comment]
I have a similar cryptic message about "missing translation" in my notifications.

**Comment by MMMAAANNN** [comment]
```<a href="/kumite/55c07d5823a6850b2800006a" data-notification-ids="55c354797fe3cc6b3a0001df">translation missing: en.models.code_snippet_translation_published_notification.single.heading.kata_coauthor</a>```

**Comment by jhoffner** [comment]
Thanks. This should be fixed now
