### ISSUE TITLE
[C++]: Operator modulo just pretends to be himself when operating on vector::size_t.

### ISSUE THREAD

**Issue by czarny247** [Codewars/codewars.com#1586]
Found while writing solution to kata: https://www.codewars.com/kata/digital-cypher/discuss/cpp

It seems like a strange behavior of C++ compiler...

It seems to work incorrectly only if the modulo operator is used like 'vector::size_t % vector::size_t'.
When I cast both left and right operands to integer, it works just fine.

![modulol](https://user-images.githubusercontent.com/7014909/46600602-ee103e00-caea-11e8-967a-2e5744a8128d.PNG)

**Comment by error256** [comment]
`1 % digits.size() == 1`
`numbers.size() - 1 % digits.size() == numbers.size() - 1`

**Comment by czarny247** [comment]
@error256 Now I see 🤦‍♂️
