### ISSUE TITLE
Question: Is it possible/allowed to load jQuery in javascript katas?

### ISSUE THREAD

**Issue by plasticbottle** [Codewars/codewars.com#1588]
See title.

**Comment by Voileexperiments** [comment]
No. JS uses Node which is not browser JS. If you want to do DOM-related stuff please use `cheerio` which is already available (just do `require('cheerio')`). (`jsdom` is deprecated.)

Also for code runner environment related things you should raise an issue at https://github.com/Codewars/codewars-runner-cli instead.

**Comment by plasticbottle** [comment]
Thanks for the answer! :)
