### ISSUE TITLE
Icon file causing some paths to not not load. Returns "Aw, Snap!" or "Can't open this page"

### ISSUE THREAD

**Issue by pbaveja** [Codewars/codewars.com#1589]
Issues definitely found on paths:
- https://www.codewars.com/kata/latest/my-languages
- https://www.codewars.com/dashboard
- https://www.codewars.com/kata/name-of-kata

**I think I figured out the issue. It lies in the icon file 'icomoon' that's requested.**
All pages load after blocking that request. But, as expected, most icons do not load within the page.

And also, this issue doesn't always come up, it's only after browsing codewars for a while, it suddenly pops up.

I'm running win7, x64.

**Comment by kazk** [comment]
Thanks. The font files were updated. See #1157
