### ISSUE TITLE
JS bug: character pointer is off

### ISSUE THREAD

**Issue by glithc** [Codewars/codewars.com#159]
The pointer that shows the place of a syntax error occurrence when solving a kata with javascript is off. It's a minor issue but sometimes slows debugging process down.

**Comment by bkaes** [comment]
Could this be related to #17? Could you please add a screenshot?

**Comment by glithc** [comment]
Here's the screenshot. As I said the pointer is off (always to the left as far as I recall)
![bug](https://cloud.githubusercontent.com/assets/10927853/9240069/57085e62-4162-11e5-9a68-eb2d039195d8.png)
Sure, those two problems could be related in some way. Although I didn't notice any spacing problems with the editor itself, just the node's output. I'm on Ubuntu 15.04 and the browser is Chrome version 44, if that helps.

**Comment by bkaes** [comment]
Found the problem. The `white-space: pre` is fine, but the font isn't monospaced at all. `console-failed` inherits the font of `body`. Use a proper monospaced font and it should be fine.

**Comment by bkaestner** [comment]
Any update here? One could squash this and #55 with a quick fix:

``` css
div.console-failed { font-family: monospace; }
```

**Comment by g964** [comment]
@jhoffner :
Sorry for repeating myself but issues about white spaces is a real pain! Yeah! I know. Avoid strings... But it is not always possible:-)
I'm one with lots of issues about gauging white spaces in some katas (see example above by JTorr).
Why doesn't Codewars use constantly a monospace family font for outputs? It would be more convenient for anyone, no need for "nice" font here!

**Comment by jhoffner** [comment]
Fixed/Deployed. BTW this part of the code is opened sourced so feel free to make contributions to it. https://github.com/Codewars/output.codewars/blob/master/public/css/app.css
