### ISSUE TITLE
Configuring a global webhook.

### ISSUE THREAD

**Issue by reivhax** [Codewars/codewars.com#1590]
The webhook documentation [here](https://dev.codewars.com/#webhooks) states that there is an option to set a webhook to recieve global events but I can't find the option in the user edit page. I configured a webhook on my profile anyway, but then I only get notifications when I perform an action like updating the webook.
`{'action': 'updated', 'webhook': {'id': '5bbf57409b84f4d598000117'}}`
Can you please clarify this info and update the documentation or the profile page accordingly.

**Comment by kazk** [comment]
Global wehook was removed due to privacy concerns. The docs needs to be updated.
