### ISSUE TITLE
I can't access a kata that I authored

### ISSUE THREAD

**Issue by raulbc777** [Codewars/codewars.com#1591]
The kata Approximate Fractions (https://www.codewars.com/kata/approximate-fractions) should be improved and fixed. I did the editions and saw a strange behaviour: the changes were not saved. I try to enter like any user to it and the languages available to solve it and example tests do not appear. First time that I see this bug.

**Comment by kazk** [comment]
Hey @raulbc777, thanks for reporting.

> I try to enter like any user to it and the languages available to solve it and example tests do not appear.

Does it look like #1323?
