### ISSUE TITLE
Missing language error message

### ISSUE THREAD

**Issue by luismartinezs** [Codewars/codewars.com#1595]
Regarding this kata "http://www.codewars.com/kata/paginationhelper" but may be a general issue.

There seems to be some issue with browser-server communication:

I emptied the test and code areas, I added some unambiguously correct code (JS) and all the time get the same error when trying to run sample tests:

Test Results:
Missing language

Server Execution Error:
Missing language

Request Error:
Request failed with status code 422
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by kazk** [comment]
I just tried it and it works as expected. Can you see what's in the request payload?

![image](https://user-images.githubusercontent.com/639336/46921369-42199780-cfaf-11e8-9a31-53fda45c15d6.png)

It should contain `language` set to `javascript`.

**Comment by luismartinezs** [comment]
@kazk It works for me now, too.
I accessed it from the link I posted above, and the problem looks different now. In the "Solution" window there was no code at all when I first tried it, now there is some structure premade.

I guess there's no issue then

Closing

**Comment by nayres** [comment]
It may also mean that you are signed out!

**Comment by seanhelvey** [comment]
I ran into this issue on a different kata "[The Lift](https://www.codewars.com/kata/the-lift/train/javascript)", and refreshing the page fixed it.
