### ISSUE TITLE
Honor points not updating

### ISSUE THREAD

**Issue by okthenko** [Codewars/codewars.com#1596]
I haven't been receiving the right number of honor for completed kata/leveling up
My profile shows I have completed 10 white and 5 yellow kata, and I am on 6kyu. 

According to the documentation I found, this means I should have at least 10*2 + 5*8 + 20 + 30 = 110 honor, but I'm currently only on 74 (in particular I didn't get any points for decreasing kyu to 6)

Any help with this will be much appreciated as I need the points to prove proficiency for an interview. Thanks

koldham15
Windows 10
Firefox Quantum

**Comment by kazk** [comment]
You do have `110` points. Your profile should get updated once the background job processes it.

**Comment by kazk** [comment]
Looks like your account is not scheduled to refresh the stats.

**Comment by kazk** [comment]
Your profile shows `110` now.
