### ISSUE TITLE
My total score dropped significantly

### ISSUE THREAD

**Issue by kolinsol** [Codewars/codewars.com#1600]
I haven't used the site for a while
Today i decided to solve some katas
Before that i had ~4700 point
after i submitted two katas my score became 3118

if it helps
i completed:
Salesman's Travel in Elixir (6 kyu)
Lottery Ticket in Elixir (6 kyu)

- Codewars username verrchu
- OS: macOS
- Browser: Chrome
- Browser Version: 69.0.3497.100

**Comment by kolinsol** [comment]
well my points came back
but the situation was quite strange

**Comment by kimhakheng** [comment]
I also face the same problem. What should I do?

**Comment by Blind4Basics** [comment]
@kimhakheng : that's you? https://www.codewars.com/users/5ede49972f92f5002da8f8d6 (Zin II)

**Comment by kimhakheng** [comment]
yes yes

**Comment by Blind4Basics** [comment]
si you didn't earn those points in the first palce and they just got removed.

**Comment by kimhakheng** [comment]
i'm not sure I can understand

**Comment by XRFXLP** [comment]
You must've cheated on some katas.

**Comment by kazk** [comment]
@kimhakheng This old issue has nothing to do with you. Your solutions were simply flagged for plagiarism (as #2272) and it's not a bug.
