### ISSUE TITLE
Please update the OCaml version 

### ISSUE THREAD

**Issue by abhi18av** [Codewars/codewars.com#1603]
Hello everyone 

I noticed that the ocaml version you are using is really old, the current version is 4.07 

Could you please try and upgrade the version?

**Comment by Voileexperiments** [comment]
Please raise issues about the languages at the neighbour repo https://github.com/Codewars/codewars-runner-cli/issues ;-)

**Comment by kazk** [comment]
Moved to https://github.com/Codewars/codewars-runner-cli/issues/646
