### ISSUE TITLE
Kata is listed as one in Beta despite being approved

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1604]
[This kata](https://www.codewars.com/kata/silent-import) has been approved a couple days ago, but it doesn't appear among katas filtered by `Status: Approved`, and can only be found in Beta section.

![image](https://user-images.githubusercontent.com/31668662/47270953-bdfd7c00-d57b-11e8-8535-ac53b39f2aac.png)

**Comment by kazk** [comment]
I see some errors updating Elasticsearch index. This is probably related to that.

**Comment by Voileexperiments** [comment]
Another kata is suffering from this issue:

https://www.codewars.com/kata/simple-fun-number-397-the-distance-between-two-points-in-a-navigational-map

**Comment by FArekkusu** [comment]
Just ran into another one: https://www.codewars.com/kata/count-squares-in-the-chess-board

**Comment by kazk** [comment]
Closing because I don't think this is happening anymore after Elasticsearch upgrade. Please let me know if you see this again.
