### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by e-mihaylin** [Codewars/codewars.com#1607]
#### Describe the bug
Read/seen notification does not mark as read/seen

#### To Reproduce

1. Get 1 notification
2. Read it
3. Refresh page
4. 1 unread again

#### Expected Behavior

It should be marked as read when we read it.

#### Screenshots

Sorry, no.

#### Contexts

Please complete the following information:

- Codewars username (if account related): [e-mihaylin] // think it is not account related
- OS: [win 7]
- Browser: [chrome]
- Browser Version: [all last versions last year]

**Comment by FArekkusu** [comment]
Duplicate of #1475.

**Comment by e-mihaylin** [comment]
Duplicate
