### ISSUE TITLE
I can't sign up, I get a 5xx error

### ISSUE THREAD

**Issue by BruceJi7** [Codewars/codewars.com#1609]
#### Describe the bug

undefined method `[]' for nil:NilClass

When I try to sign up, via the python initiation trial, I get this error. 

#### To Reproduce

Go on website.
Click python
Click Join
Wait a long time for the website to load - longer than I waited last week (sorry I didn't sign up then :( )
Submit the answer to the trial
Get this error.

#### Expected Behavior

I expect a signup box. I tried a few times and did get a sign up box one time but when I filled that in and submitted it, I got the error again.

#### Screenshots

Do you know what, I was trying to get a screenshot and I managed to sign up. I'll submit this anyway because it might point to some weird-ass issue hiding somewhere.

#### Contexts

Please complete the following information:

- Codewars username (if account related):  No account yet :(
- OS: Windows 7 Home Premium K
- Browser: Chrome
- Browser Version: 69.0.3497.100 (Official Build) (64-bit)

**Comment by kazk** [comment]
This should be fixed now.
