### ISSUE TITLE
Missing [Submit Final] step

### ISSUE THREAD

**Issue by adam-tokarski** [Codewars/codewars.com#161]
At http://www.codewars.com/kata/55c3b11f72c16bb59c00006c Kata I posted solution that passed Tests and first Submit Steps. All tests successfully passed, and even is "Excellent! You may take your time to refactor/comment your solution. Submit when ready." green message, but [Submit] button stuck at, hmm, [Submit], and doesn't want to change to [Submit Final]. 

I've tried at Chrome (even at Incognito Mode), where I usually post solutions from, at Firefox, even at Internet Explorer. Always the same. To be sure I tried to submit other Kata and it worked as expected. Problem is only with that one.

**Comment by jhoffner** [comment]
Thats because this is a draft kata. It would need to be published first. How did you come across this?

**Comment by adam-tokarski** [comment]
To be honest I don't know. I think it was found by Kata list, however can't find it now. Is it possible to back Kata to draw, when was published?

**Comment by bkaes** [comment]
> Is it possible to back Kata to draft, when was published?

As long as it wasn't approved, yes. You can un-publish beta katas.

**Comment by adam-tokarski** [comment]
Thanks, that was just unpublished Kata.
