### ISSUE TITLE
Syncing with GitHub

### ISSUE THREAD

**Issue by SabahatPK** [Codewars/codewars.com#1611]
#### Describe the bug
I am pretty sure this is not the right place to ask this question but I have searched everywhere (Forum, Wiki, Github, etc) and have not been able to find an answer. 

I linked up CodeWars to my GitHub account when I first registered with CodeWars. I am no GitHub expert but I thought that my solutions on CodeWars would be syncing up/saving on GitHub. I see, of course, that they are not. 

Can someone tell me what I need to do to get CodeWars' solutions to save to GitHub? I created a repo but do not understand how I can link it to CodeWars in order for it to save my solutions.

If everyone is uploading solutions to GitHub manually, then ignore my question. (But also let me know!)

#### To Reproduce

1. Complete a Kata successfully. 

#### Expected Behavior
1. Solution is saved in GitHub.

#### Contexts

- username: SabahatPK
- OS: Windows 10 Pro
- Browser: Chrome
- Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by kazk** [comment]
We do not sync solutions to GitHub. Also, uploading to GitHub manually is **strongly discouraged** because this will allow new users to easily look up the solution.
