### ISSUE TITLE
Please add Dart 2

### ISSUE THREAD

**Issue by nickmeinhold** [Codewars/codewars.com#1616]
#### Is your feature request related to a problem? Please describe.
Dart 2 had significant changes to the language.

#### Describe the solution you'd like
Add the option of being able to use version 2 for Dart. 

#### Describe alternatives you've considered
Using Dart 1 here means learning an outdated language. 

#### Additional context
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

**Comment by kazk** [comment]
Please reopen this in https://github.com/Codewars/codewars-runner-cli as a template for language issue mentioned. It has a template for new language version request.
