### ISSUE TITLE
Weight of its Contents: Haskell translation broken

### ISSUE THREAD

**Issue by bkaes** [Codewars/codewars.com#162]
There's an error in one of my old translations, [Weight of its Contents](http://www.codewars.com/kata/53921994d8f00b93df000bea/edit/haskell). Below is a small fix. One needs to make sure that `i` is positive, and that the "larger"/"smaller" string isn't `show`n.

```diff
     it "should work for random contents" $ do
       property $ 
         forAll (arbitrary `suchThat` (>0)) $ \s ->
-        forAll (arbitrary `suchThat` (\i -> i `rem` (s+1) == 0)) $ \i ->        
+        forAll (arbitrary `suchThat` (\i -> i `rem` (s+1) == 0 && i > 0)) $ \i ->        
         forAll (elements ["larger","smaller"]) $ \l ->
-          let str    = show s ++ " times " ++ show l
+          let str    = show s ++ " times " ++ l
           in contentWeight i str `shouldBe` solution i str      
```
This should fix the negative values for `i` and the `xx times \"smaller\"` issue. See also #123.

**Comment by jhoffner** [comment]
It should be fixed now. 

BTW I'm making a note to create a new privilage that allows power users to make edits beyond the 500 attempts threshold. This limitation is getting old.
