### ISSUE TITLE
550 5.7.1 Exceed Sending Limit (monthly)

### ISSUE THREAD

**Issue by vjandrea** [Codewars/codewars.com#1621]
#### Describe the bug
Tried to subscribe, got a 500 error, detail shows **550 5.7.1 Exceed Sending Limit (monthly)**

#### To Reproduce

1. Go to 'https://www.codewars.com/landing?language=python'
2. Link GitHub account
3. Fill email field
4. Submit

#### Expected Behavior

See my dashboard or a welcome msg

#### Screenshots

![image](https://user-images.githubusercontent.com/639336/48152278-48322980-e278-11e8-9f49-720f4d673ec7.png)

https://snag.gy/a7ufTG.jpg

#### Contexts

Please complete the following information:

- Codewars username (if account related): @vjandrea
- OS: Win7Pro ITA
- Browser: Firefox
- Browser Version: 63.0.1 (64 bit)

**Comment by kazk** [comment]
Thanks for reporting this. We had reached the limit of the email delivery service and didn't notice this until seeing this issue.
We've upgraded the plan so it should be working now. Please try again.
