### ISSUE TITLE
Upvoting system for well-commented code

### ISSUE THREAD

**Issue by CosmicStresshead** [Codewars/codewars.com#1629]
It would make me very happy if there were some way to reward well-commented code when up-voting solutions.

Along with the 'Best Practices' and 'Clever' up-voting options we have currently, it might be useful to include a 'Well-Commented' one as well.  Commenting code is often cited as a very important element of best practice but is just as often ignored when appraising someone's solution to a problem.  It strikes me that most kata solutions here that have been up-voted as Best Practices are not commented at all.  

This is fine for the most part and I don't think code is being wrongfully up-voted, but I think having a way to 'reward' well-commented solutions would both highlight and reinforce its importance for both writers and appraisers of code here.

I had considered suggesting merely including a reminder to consider commented code before up-voting for Best Practises.  However, I do feel that there is enough of a distinction between well-commented and well-balanced code to warrant appraising these aspects separately.  I wouldn't want to detract from the merits of well written-code for the sake of just one aspect, especially a less universally appreciated one.

I wonder what anyone else thinks?  I was a little surprised that this doesn't seem to have come up before.

**Comment by FArekkusu** [comment]
It's very unprobable that CW will receive any updates, as it's constantly in half-broken state, and adding new features right now is nearly impossible.

___

"Well-commented" is a vary vague criteria. What does "well-commented" mean? Shortly explaining the main points to provide some understanding what's happening? Explaining said points thoroughly so the user knows what you're doing, how you're doing, and why you're doing something? Commenting every line of code? It can't be implemented properly, as it's hard to tell what "well-commented" stands for.

And, of course, some people may abuse these features by getting many upvotes from naive users because "there're comments for people who are not programmers with 100 years of experience" (yes, there're people who complain about different stuff because "they are new to programming and don't understand *something*").

**Comment by hobovsky** [comment]
Also remember that currently quite popular approach is that the best comments are the ones which do not have to be written. With this approach only "documentation comments" which describe things like function contract, requirements on parameters and guarantees on return values etc. are considered useful. All kinds of 'explanatory' comments (or even all comments, in opinion of some people) are considered a code smell, or just harmful - they explain what should not have to be explained, they do not age well, it's highly probable that a comment sooner or later becomes a lie.

I do not want to discuss pros nor cons, if there should be comments or not, etc. I just want to point out, like also FArekkusu did in one of his points, that 'well commented' is so undefinable that I would consider it not worth of a feature/difficult to implement reliably.

**Comment by CosmicStresshead** [comment]
Again some fair comments, and thank you.  I'm not really going to argue against your points here except to say that in the case of the typically quite short solutions required by the katas, commenting would really be used as a measure to explain code that doesn't read well but that the writer couldn't find a more elegant way of putting.  If that were the stated use of commenting in the context of this site, I don't think that the different philosophies would come into play.  The voting system would become one where users can help sort the quality of the answers solutions to a kata based on an extra criteria, where it would be impossible/difficult to do so programmatically.  You're making a good case against the implementation of such a system though.  I'll have to find some other way to further my fiendish comment-awareness agenda :P 

With regard to your rightly pointing out the vastly differing schools of thought on the subject, in practice this is partly influenced by the agreed-upon practices of the team the developer is part of, particularly in corporate settings where there are layers of oversight.  Maybe I'm suggesting introducing a small-scale standard of our own to follow within the CodeWars community, where we all agree what constitutes good commenting on an internal andor a per solution basis.  But I can see I'm hopelessly naive here, I may come back to this comment is a year or so and wretch in disgust at myself.

Thanks, guys.
