### ISSUE TITLE
New power user privilege to allow edits beyond 500 attempts

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#163]
Its time.

**Comment by bkaes** [comment]
While we're at it, does this result in a scenario described by @GiacomoSorbi in  #123?

> +1 or, alternatively, allow users with 5000+ honour to edit it directly or pull an edit for an admin to approve/reject: currently there are like 15 users with 5000+ points and (except the underwritten of course) they are surely more than capable to improve a kata in need.

I'm not sure about the amount of honour, but I guess the original kata author should also be able to edit the kata if he reached a certain amount:

Honour| Privelege
---------|------------
2500+| Edit _your own_ kata even after 500+ solutions have been submitted
5000+| Edit _other_ katas even after 500+ solutions have been submitted

The actual honour amount is up to you, but this enables lower-honour kata authors to act without delay if no power user notices their trouble.

**Comment by GiacomoSorbi** [comment]
Not sure about this has been/will be actually implemented, but bkaes-senpai idea on the required honor is quite neat and I hope we are headed toward that direction.

**Comment by jhoffner** [comment]
With the recent 500 limit per-language change I'm no longer sure that this change is needed. I'm sure there are a few edge cases where it would still be useful, but those cases are likely due to this being an issue for so long on older kata. Newer kata really shouldn't get to this point now that the restrictions are language independent.
