### ISSUE TITLE
Vim mode - Insert mode next line with right key

### ISSUE THREAD

**Issue by diogo98s** [Codewars/codewars.com#1638]
#### Describe the bug
While on Vim insert mode, we are able to go to the next line by going to the end of the current one.
Real Vim doesn't let that happen.

#### To Reproduce

1. Go to a random Kata
2. Select `VIM` in the top right corner
3. Click on the text area to start writing
4. Press down i to go into Vim's insert mode
5. Press the right arrow key to go to the end of the current line and notice it changing to the next line.

#### Expected Behavior

It should stay in the same line, when pressing the right arrow in the end of the current line.

**Comment by kazk** [comment]
Closing because this is not Codewars issue or CodeMirror's.
CodeMirror's Vim keybindings behaves exactly like base CodeMirror when in insert mode. See this mentioned in https://codemirror.net/demo/vim.html
