### ISSUE TITLE
kata publication is going wrong, sometimes...

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1639]
Hi,

See here: https://www.codewars.com/kata/unknown-math-symbols/discuss/java

We got another user who's publishing his homework so that we can solve them for him. The question is: how could he even publish the kata, since the solution of the author is doing nothing? My guess is that it comes from a kumite converted to a kata. So this would need to be more secure, to avoid this kind of shit post... If that's the way he did it...

cheers

**Comment by Voileexperiments** [comment]
@Blind4Basics because kata publish never performs validation. It's a very old bug that I reported recently: #1369

Also I've retired the kata. Maybe close this and keep track at #1369?
