### ISSUE TITLE
CW's Markdown engine gives inconsistent results between preview and actual result

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1640]
An extension to #1441.

I'm not sure how is this even possible, but CW's Markdown engine apparently gives different results in "preview my comment" mode and in actual render, which I've encountered at least several times. One of the simplest examples is this:

```
~~should be striked~~next to correct text
```

In Github:
> ~~should be striked~~next to correct text

In CW preview mode (correct):
![image](https://user-images.githubusercontent.com/14909989/49193461-18c79600-f3ba-11e8-8c89-6736774c8a48.png)

In CW actual render (incorrect):
![image](https://user-images.githubusercontent.com/14909989/49193478-2715b200-f3ba-11e8-8541-2107a1b58a29.png)

**Comment by Voileexperiments** [comment]
Related: #1617

**Comment by kazk** [comment]
> I'm not sure how is this even possible

I think the preview uses a client side engine Marked and the actual one is by a server side engine.
Markdown implementation was all over the place before CommonMark and it's from those days.

**Comment by kazk** [comment]
This will be fixed with the huge updates I've been working on for the past month. The Markdown engine on the server side will be Common Mark.

#1441 is not fixed and seems to be a styling issue

**Comment by Blind4Basics** [comment]
there are still troubles with the comment markdown :/

the preview is correct, but not what's shown in the actual posted comment:

![image](https://user-images.githubusercontent.com/32236948/50736207-d7958380-11ba-11e9-8a3c-734833fbd628.png)

Using simple ticks works properly, tho:

![image](https://user-images.githubusercontent.com/32236948/50736215-f431bb80-11ba-11e9-95ee-c32e9697109c.png)

**Comment by kazk** [comment]
How many spaces are there for the second level?

In this case, I think the preview is wrong.
The following
```
1. 1
2. 2
3. 3
  1. 3.a
  2. 3.b
```
is
![image](https://user-images.githubusercontent.com/639336/50741612-66eb6880-11b4-11e9-8d72-aa64591d9f7e.png)

on GitHub comment.

If you indent the second level with 4 spaces, you should get

![image](https://user-images.githubusercontent.com/639336/50741601-17a53800-11b4-11e9-95d7-2eb5bb9c4539.png)


---

Markdown preview uses a different engine on the client side so the best I can do is to find options to make it agree with the server side. And I haven't looked into this yet.

**Comment by Blind4Basics** [comment]
I used indentations with 2 whitespaces

**Comment by kazk** [comment]
I've updated to the latest version of marked. They're still working on becoming fully compatible with CommonMark spec, but it should be much better than the version we were using.
