### ISSUE TITLE
Complete kata per language

### ISSUE THREAD

**Issue by toastyblast** [codewars/codewars.com#1641]
#### Is your feature request related to a problem? Please describe.
I know several languages and would like to refresh myself on each. Thus, I like to do kata(s) in each language, to remind myself of the differences between each language. However, there is no marking with a Kata for in what languages I have completed it, nor do you seem to get honour after completing a kata once in one language. Completing it with a different language you haven't completed it in afterwards does not give extra honour.

#### Describe the solution you'd like
I'd like to see clear UI elements on what languages I've completed a kata in. Additionally, I'd love to see you get honour for each first completion with a new language on a kata. So for instance, if I finished a kata with C++ once, I'd get honour. Then, the first time I complete the same kata, only now in Java, I'd once again get some honour.

#### Describe alternatives you've considered
An alternative to seeing what languages you've solved a Kata in could also be to allow us to sort on the language we completed a kata in, and only show those we've completed in that language (or the other way around, and filter out the kata we have completed in that language).

**Comment by hobovsky** [comment]
> Completing it with a different language you haven't completed it in afterwards does not give extra honour.

You get no Honor points, but you are still rewarded with "language progress":

![image](https://user-images.githubusercontent.com/23709795/49225636-e7b08b00-f3e4-11e8-936a-3353a60409c6.png)

If you complete a kata in more than one language, your C++/Java/Ruby/Whatever rank increases for each solution.

When it comes to visualisation/filtering of completed versions, it's +1 from me.

**Comment by azwarners** [comment]
Maybe instead of putting checkmarks next to the kata name they could put it next to the languages completed in. For example, if you completed in JavaScript, Java, and Python:
![completedkata](https://user-images.githubusercontent.com/5873707/52926487-376f6600-32f3-11e9-8d76-5ddb50944c27.png)
That way we'd know where we are without having to click inside and view solutions.

**Comment by hobovsky** [comment]
If anyone would be interested in such feature, you can give [this script](https://pastebin.com/eUYf5XP5) a try.

**Comment by azwarners** [comment]
hobovsky, that script is amazing! I haven't had a whole lot of time to play with it yet, but so far it seems to do exactly what I thought was missing from Codewars. All of my completed languages are greyed/fuzzed out now. Nobody wants to learn only one programming language in life. I hope you can find a way to make this highly visible for everyone. I think the vast majority of users on Codewars would find this useful. Major kudos to you!
![hobovskyscript](https://user-images.githubusercontent.com/5873707/53389775-d4fb1300-394d-11e9-8cf4-d5008e9286b6.png)

**Comment by hobovsky** [comment]
Thanks, and have fun!

Also, do not forget about the other feature:

![image](https://user-images.githubusercontent.com/23709795/53396172-1ae2c600-39a4-11e9-971c-39cc18ddc6fa.png)

**Comment by Len512** [comment]
Thank you for this! Makes it very easy to practice a kata in multiple languages ;)

**Comment by hobovsky** [comment]
@Len512 I am glad you like it, just remember to check [its repo](https://github.com/hobovsky/polyglot) for updates, or use recently added auto-update feature (and let me know if it works for you ;) ).

Thanks, and have fun!

**Comment by agilvarry** [comment]
Just popping to +1 this suggestion. I've tried the script @hobovsky made and it doesn't seem to work for me, may be that I've done something wrong in setting it up. In any case this would be an amazing feature for codewars.

**Comment by hobovsky** [comment]
@agilvarry we might try to sort issues with the script out if you catch me on gitter. Drop me a PM and maybe we can get it working.

Cheers!

**Comment by hobovsky** [comment]
@azwarners I can confirm, it still works.

**Comment by Len512** [comment]
I used this script today after some time: 
- I update the solutions tab
- I select the filters on the left: language: Kotlin, status : both, progress: Kata I have completed 
- I select "Show Katas i haven't solved in Kotlin"

![Screen Shot 2020-12-01 at 13 41 57](https://user-images.githubusercontent.com/25386785/100742689-7f358380-33db-11eb-8078-fc6aac88cc97.png)

The results contain kata which I have completed in Kotlin and sometimes even fails to "fade out" the language logo. For example, the Bouncing Balls kata in the screenshot, I have completed this in 4 languages. 

Is there a step I'm missing? I must admit I haven't used this in some time now.

**Comment by hobovsky** [comment]
The script is not related to Codewars in any way so let's not discuss its issues here, because it's offtopic. I think it would be good to use the issue board in its own repo: https://github.com/hobovsky/polyglot/issues

About the problem, I havent looked into any issues for a long time, and CW experienced some updates recently, so indeed something could break. I will check after work.

Would you please re-raise the issue on Polyglot board? Thanks, and glad you still like it!

**Comment by Len512** [comment]
Sure, sorry for raising it here, my bad, I just followed the link from a notification I received blindly :/
