### ISSUE TITLE
Add new comment type: "Duplicate"

### ISSUE THREAD

**Issue by bkaestner** [codewars/codewars.com#165]
Previously on [gitter](https://gitter.im/Codewars/codewars.com?at=55ccb5189b45e15c42640af1).

Create a new comment type "Duplicate", that can only get resolved by a moderator or admin.

**Comment by kazk** [comment]
> So, about duplicate katas. Some authors simply resolve the "is duplicate" issue, for example [here](http://www.codewars.com/kata/55a891dfaf48a4d93000008a/discuss). Should one re-open the issue on Codewars, write an issue on GitHub, notify you here, or notify the staff via intercom?

I don't think a special label for duplicates is necessary with more strict requirements with mods being able to unpublish them.

Also, ideas like

- https://github.com/codewars/codewars.com/discussions/2600
- https://github.com/codewars/codewars.com/discussions/2598

are planned, and more generally useful.
