### ISSUE TITLE
Groovy Katas are not listed in my profile

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1651]
#### Describe the bug
I have solved several katas for Groovy language but it's still missing on the progress chart

#### To Reproduce

1. Solve a Groovy Kata
2. Go to profile
3. the Groovy statistics is not shown

#### Expected Behavior

It should be listed too.

#### Screenshots

As you can see I have completed groovy Katas
<img width="960" alt="groovy cw 2" src="https://user-images.githubusercontent.com/1063901/50260796-3099a500-03cf-11e9-89ea-05e0e09eaca1.png">

But progress is not taken into account on my profile
<img width="801" alt="groovy cw 1" src="https://user-images.githubusercontent.com/1063901/50260803-35f6ef80-03cf-11e9-970f-afbc1b97b917.png">

**Comment by kazk** [comment]
Doesn't it say it refreshes in 10 hours?
![image](https://user-images.githubusercontent.com/639336/50261428-60da4700-03c1-11e9-92a5-3bf4b487f217.png)

**Comment by kazk** [comment]
Is this on preview only or both?

**Comment by Voileexperiments** [comment]
Is Groovy a beta language? Because IIRC beta languages aren't shown there, which happened too when BF was just out and it was beta.

**Comment by kazk** [comment]
I have Groovy in both www and preview. If @javatlacati solved first Groovy kata few hours ago, it's possible that it's not shown yet.

**Comment by kazk** [comment]
So I guess it doesn't show if you only completed beta kata. I'm guessing this is because the progress can't be calculated.
