### ISSUE TITLE
Unable to access my profile

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1657]
Always getting
```
5xx: Server Error
This doesn't happen often, but it looks like something is broken. Hitting the back button and trying again might be your best bet. If that doesn't work you can head back to the homepage.

There might be more information on our status page.
```

**Comment by kazk** [comment]
I deployed the major update last night and profiles of users with lots of data associated (power users like you) seems to be slow and timeouts.

Are you having trouble loading other pages?

**Comment by kazk** [comment]
I don't know why yet, but your profile page is extremely slow. Much slower than any other power users.

**Comment by g964** [comment]
In fact it is impossible to access. I always get a 5xx error.

**Comment by kazk** [comment]
Can you access other pages?

**Comment by g964** [comment]
Yes I can and even other profiles (myjinxin2015 or Voile) but not (A.Partridge's or jamad's profiles).
Moreover I don't receive anymore notifications of posts since yesterday.

**Comment by kazk** [comment]
Yeah, I some timeout errors reported on your page and jamad's.
Sorry about that.

I don't know what's the exact cause yet, but I've been working on fixing one of the major performance issues so I hope that helps.

**Comment by g964** [comment]
I can see some posts for me on the "dashboard" but I can't answer. When I try it always goes on and on but never succeeds.

**Comment by g964** [comment]
Sorry to bother you but still unable to access my profile and don't get posts notifications:-(

**Comment by kazk** [comment]
Sorry. I'll be back tomorrow and will try to fix it.

Notification is a new bug introduced with the update and affects everyone. See #1663.

**Comment by kazk** [comment]
I just deployed a new release that makes loading your profile slightly faster. I'm still looking into it.

**Comment by kazk** [comment]
I just deployed a fix for this. Can you try and let me know if it helped?

**Comment by g964** [comment]
For now it works, hope it will last;-) Thanks you a lot!

**Comment by kazk** [comment]
Cool, I'll close this then. Please let me know if it starts again.

I'm going to start optimizing stuff so hopefully that helps too.
