### ISSUE TITLE
Unable to log into Codewars due to 5xx

### ISSUE THREAD

**Issue by aytrack** [Codewars/codewars.com#1661]
Hi, Since yesterday, when I tried to log into Codewares, I always reported the following error.![image](https://user-images.githubusercontent.com/10184437/50539969-15474a80-0bc4-11e9-9f86-ab1dd5af0a39.png)
 It seems to have been fixed in [#814](https://github.com/Codewars/codewars.com/issues/814).
My username is `aytrack`. Whether I am logging in with github or logging in with the codewars account(Password has been modified), always the same error page.

How can I solve this problem?

**Comment by kazk** [comment]
Can you try logging in using GitHub within Incognito (Chrome) or Private (Firefox) and let me know what happens?

**Comment by kazk** [comment]
I just deployed a fix for possibly related issue: #1662. Can you try logging in again?

**Comment by aytrack** [comment]
Now i can successfully log into with both github and codewars account.

Before this report, i did the same things as nwayve reported in [#1662](https://github.com/Codewars/codewars.com/issues/1662) and change my codewars account password.I didn't have his issue in the 4th step.it's always the error I reported above.

Thank you.

**Comment by kazk** [comment]
Great. Thanks for letting me know :)

**Comment by aytrack** [comment]
I am so sad to tell you that my account can not be log into codewars again with  the same problem,

**Comment by kazk** [comment]
That's really odd. Nothing changed on our end.

Can you describe what happened (or what you did) after you were able to log in?

**Comment by aytrack** [comment]
I remeber i did  the following things but i am not really sure.

1. Using github link log into codewars ,and login with codewars accout in "Incognito" mode (Chrome).
2. Do the same thing on firefox.
3. Close chrome and open again. login github, open a new tab to open codewars.com, then i meet the 5xx error.

**Comment by kazk** [comment]
I just looked in the logs and it looks like you're logged in successfully. I've found two records about 30 minutes before and after [your comment](https://github.com/Codewars/codewars.com/issues/1661#issuecomment-450570401).

After logging in, were you redirected to `/dashboard`? Or did you get this 500 error before redirection?

Your last sign in timestamp is `2018-12-31 14:27:38 (UTC)` (just before your last comment) so the error might be caused by something else.

**Comment by aytrack** [comment]
I got this 500 error before redirection to `/dashboard`.
I just tried it again, now I can successully open each page and no 500 error in Incognito mode.
But when i not in incognito mode, it was normal at the beginning, and I encountered this error when I visited several pages.
Clean the browser cache, I cloud use again, and after visited serveral pages, the error is coming again.
My chrome vesion is 71.0.3578.80 (64bit), win10 platform
That's really odd.

**Comment by kazk** [comment]
Looks like it's unrelated to logging in then.

So

1. When in Incognito, Codewars works as expected.
2. When not in Incognito, Codewars works when cache is cleared, but you start to get the error after visiting several pages.

Am I understanding correctly?

Can you answer these questions?

- Do you have any extension installed? If so, can you try disabling them and see if it makes any difference?
- Do you see any error messages in console?
- Can you describe how the error happens? Do you get the error instantly? Or does it feel like it timed out (loading takes forever and then shows this error)?

**Comment by aytrack** [comment]
I am sorry that I have not responded to you before. I have not encountered this problem now.

**Comment by kazk** [comment]
Great, thanks for letting me know.
