### ISSUE TITLE
Github Login Error

### ISSUE THREAD

**Issue by nwayve** [Codewars/codewars.com#1662]
#### Describe the bug
When clicking on Github login, and being logged into Github already, I'm redirected to /users/auth/github/callback?code={auth_code} and it's a 500 error.

#### To Reproduce

1. Clear browser cache
2. Open a browser in its version of "Incognito" mode for Chrome. (I've tried Firefox and Chrome)
3. Go to www.codewars.com and click on the Github Login link
4. Being incognito, this should redirect to the Github login page.  Login.
5. After a successful login, get redirected back to www.codewars.com/users/auth/github/callback?code={auth_code} and see the 500 error message displayed in the screenshot below.  Message:

_"authenticable_salt returned nil for the User model. In order to use rememberable, you must ensure a password is always set or have a remember_token column in your model or implement your own rememberable_value in the model with custom logic."_

#### Expected Behavior

To be successfully logged in to codewars after authenticating with Github.

#### Screenshots

![image](https://user-images.githubusercontent.com/1729221/50540690-18a6eb80-0b5c-11e9-98a1-704c6e6ce1e0.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): nwayve
- OS: Windows 10
- Browser: Chrome v71.0.3578.98
- Browser: Firefox Quantum v64.0

**Comment by kazk** [comment]
Sorry for the inconvenience. And thanks so much for all the information.

I’ll look into this today.
