### ISSUE TITLE
Current Streak 

### ISSUE THREAD

**Issue by KPH3082** [Codewars/codewars.com#1671]
I log on everyday and make sure I do at least one Kata. Yesterday I did the same thing but today my current streak is back to 0. I can look on my solutions and it says 1 day ago on a 7 Kyu Kata so my streak should still be going. I know it is silly but this has happened once before and I'm proud of my streaks. I would one day like to use it as a asset to show off to potential employers.

**Comment by kazk** [comment]
Closing because it's not 0 anymore. The job queue had some outage last night and maybe that caused the weirdness.
