### ISSUE TITLE
Description was not updated with a translation approval

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1675]
Yesterday I wrote a [translation](https://www.codewars.com/kumite/5c377c2d1d55cb38a1a4a8c3?sel=5c377c2d1d55cb38a1a4a8c3) which was eventually approved. I have modified the description (restructured it, added "code" and "if:language" blocks, added a note to resolve description-related issues) but it was never updated<sup>1</sup>. The last revision happened 2 months ago (so it was not reverted by somebody), and no other translations were approved since then (so it was not rewritten).

<sup>1</sup>: Unfortunately, I didn't check whether the description was updated right after the approval, so there's also a possibility that the changes *were* made, but got reverted later.

___

Description included with translation:
![image](https://user-images.githubusercontent.com/31668662/51050278-e88a2e80-15d8-11e9-848d-515d9d776a32.png)

Current description:
![image](https://user-images.githubusercontent.com/31668662/51050475-a01f4080-15d9-11e9-984f-afbad72227e3.png)

**Comment by error256** [comment]
https://www.codewars.com/kata/dna-to-rna-conversion
Crystal and Go translations were approved, but the description wasn't updated in either case. Normally, they couldn't even be approved together due to the concurrent description update.

**Comment by kazk** [comment]
This should be fixed now.
Descriptions for affected kata needs to be fixed manually. I considered writing a script, but Codewars doesn't handle conflicts well and I wasn't confident enough. Sorry.

**Comment by kazk** [comment]
Here's a list of kata (34) and translations (36) that's possibly affected. I'll try fixing them when I can.

- [Sort Numbers](https://codewars.com/kata/5174a4c0f2769dd8b1000003)
    - [typescript](https://codewars.com/kumite/5c38e3fdf38f942aaefdaa4e)
- [String ends with?](https://codewars.com/kata/51f2d1cafc9c0f745c00037d)
    - [typescript](https://codewars.com/kumite/5c389c2323e1fc330921a155)
- [Function 1 - hello world](https://codewars.com/kata/523b4ff7adca849afe000035)
    - [c](https://codewars.com/kumite/5c1f6725dd392c18fd000079)
- [The observed PIN](https://codewars.com/kata/5263c6999e0f40dee200059d)
    - [csharp](https://codewars.com/kumite/5c290acbf30ec270c7556daf)
- [Collatz](https://codewars.com/kata/5286b2e162056fd0cb000c20)
    - [java](https://codewars.com/kumite/59adade4589d2acd7e000128)
- [First non-repeating character](https://codewars.com/kata/52bc74d4ac05d0945d00054e)
    - [ocaml](https://codewars.com/kumite/5ba57c3d80824ae52d00008d)
- [Goldbach's Conjecture](https://codewars.com/kata/537ba77315ddd92659000fec)
    - [elixir](https://codewars.com/kumite/5c26bf9afb855b3e554b18e1)
- [Tick Toward](https://codewars.com/kata/54bd06539f075cece0000feb)
    - [python](https://codewars.com/kumite/5c377c2d1d55cb38a1a4a8c3)
- [Square into Squares. Protect trees!](https://codewars.com/kata/54eb33e5bc1a25440d000891)
    - [go](https://codewars.com/kumite/5c38ad00b3d83132ae8e7a69)
- [Some Egyptian fractions](https://codewars.com/kata/54f8693ea58bce689100065f)
    - [go](https://codewars.com/kumite/5c376b81d8281872200f4199)
- [Irreducible Sum of Rationals](https://codewars.com/kata/5517fcb0236c8826940003c9)
    - [go](https://codewars.com/kumite/5c34acd1fdcefd7f2271c95e)
- [Playing with digits](https://codewars.com/kata/5552101f47fc5178b1000050)
    - [nasm](https://codewars.com/kumite/5bf997cbe50d1bf74700016a)
- [DNA to RNA Conversion](https://codewars.com/kata/5556282156230d0e5e000089)
    - [crystal](https://codewars.com/kumite/5b75638ef71e5d32be000026)
    - [go](https://codewars.com/kumite/5bd11546f7c9796a950000af)
- [Fluent Calculator](https://codewars.com/kata/5578a806350dae5b05000021)
    - [csharp](https://codewars.com/kumite/5c137e7c4e8f18cb0c000507)
- [Grasshopper - Check for factor](https://codewars.com/kata/55cbc3586671f6aa070000fb)
    - [csharp](https://codewars.com/kumite/564edf1a08e467b06000008d)
- [80's Kids #2: Help ALF Find His Spaceship](https://codewars.com/kata/5660aa3d5e011dfd6e000063)
    - [cpp](https://codewars.com/kumite/5adfe4329c54af345f000083)
- [80's Kids #5: You Can't Do That on Television](https://codewars.com/kata/5667525f0f157f7a0a000004)
    - [cpp](https://codewars.com/kumite/5ae1406cda49363316000086)
- [L1: Set Alarm](https://codewars.com/kata/568dcc3c7f12767a62000038)
    - [java](https://codewars.com/kumite/568e0bbe15d457528800004b)
    - [c](https://codewars.com/kumite/5c337987d35dda64d5f96d3b)
- [Looking for a benefactor](https://codewars.com/kata/569b5cec755dd3534d00000f)
    - [go](https://codewars.com/kumite/5c2b306aeb9aa933bb14d05f)
- [Consecutive strings](https://codewars.com/kata/56a5d994ac971f1ac500003e)
    - [nim](https://codewars.com/kumite/5c3da61170cd973eefe60a4f)
- [Get length of the list recursively](https://codewars.com/kata/57a83e447cb1f32de80000d5)
    - [c](https://codewars.com/kumite/5c1bea45ba76f4432200035f)
- [Framed Reflection](https://codewars.com/kata/581331293788bc1702001fa6)
    - [c](https://codewars.com/kumite/5c34caf4348b3e68346edcb9)
- [Fun with lists: map](https://codewars.com/kata/58259d9062cfb45e1a00006b)
    - [csharp](https://codewars.com/kumite/586c46eb3f36755f3800017b)
- [Thinkful - String Drills: Repeater](https://codewars.com/kata/585a1a227cb58d8d740001c3)
    - [typescript](https://codewars.com/kumite/5c3794f5d35dda7af8f96e2a)
- [Closest and Smallest](https://codewars.com/kata/5868b2de442e3fb2bb000119)
    - [go](https://codewars.com/kumite/5c24f5d245bf9ddf8400004a)
- [CamelCase Method](https://codewars.com/kata/587731fda577b3d1b0001196)
    - [rust](https://codewars.com/kumite/5c2553da7f74a25323000072)
- [Find the Integral](https://codewars.com/kata/59811fd8a070625d4c000013)
    - [python](https://codewars.com/kumite/5b41565adfb4297874000010)
- [Errors : histogram](https://codewars.com/kata/59f44c7bd4b36946fd000052)
    - [javascript](https://codewars.com/kumite/5c3c36bc857cd700136e1907)
- [Find nth Digit In a Infinite Addition Result](https://codewars.com/kata/59f6e1af3640ce12510000ad)
    - [java](https://codewars.com/kumite/5c320a4e2862484c0ddf4c0b)
- [Student's Final Grade](https://codewars.com/kata/5ad0d8356165e63c140014d4)
    - [csharp](https://codewars.com/kumite/5af8e44d86d0758ffb000073)
- [Toddler sum](https://codewars.com/kata/5c12e9bcf114c2d8dd0019ff)
    - [kotlin](https://codewars.com/kumite/5c1443fc85e9ff87a70002cb)
- [Music Fun #1 - Major Scale](https://codewars.com/kata/5c1b25bc85042749e9000043)
    - [c](https://codewars.com/kumite/5c2c7e274939c837a4393b9b)
- [Artificial Rain](https://codewars.com/kata/5c1bb3d8e514df60b1000242)
    - [ruby](https://codewars.com/kumite/5c390b8c75936723513c539a)
- [How to find a marriage partner](https://codewars.com/kata/5c1cc1b187817977c2000109)
    - [kotlin](https://codewars.com/kumite/5c3dddb1b7beb03d6946d2c7)
