### ISSUE TITLE
CSS3 published kumites are not being listed

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars.com#1678]
#### Describe the bug
Perhaps related to #284, I creatd a [sample CSS3 kumite](https://www.codewars.com/kumite/5c3bafcacba5116cc8567929/edit) but it's not listed in the [Kumite page](https://www.codewars.com/kumite)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c6p) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Closing because CSS kumite is not supported.
Adding support for CSS+HTML is tracked by https://github.com/codewars/runner/issues/21
