### ISSUE TITLE
This week's Weekly Coding Challenge email forgot to fill in the template

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1681]
The Weekly Coding Challenge email just sent to me had this title:

![image](https://user-images.githubusercontent.com/14909989/51195837-d71e8a80-1928-11e9-860d-6486107d57ec.png)

Pretty sure it's not intended ;-)

**Comment by kazk** [comment]
Closing because it's out of this repository's scope. I'll let them know.
