### ISSUE TITLE
[PureScript] Example Test Cases contain an invalid link

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1682]
The Example Test Cases for PureScript which show up during the kata translation process contains a link to a (as of 16/01/2019) non-existent GitHub Pages site: https://owickstrom.github.io/purescript-spec/ .  Consider removing the link or replacing it with another link.

**Comment by kazk** [comment]
Yeah, they moved to https://purescript-spec.github.io/purescript-spec

**Comment by kazk** [comment]
Fixed
