### ISSUE TITLE
PureScript code blocks not supported in kata description

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1684]
When authoring a Kata translation and attempting to add a corresponding language block for PureScript by using three backticks followed by the `purescript` keyword, e.g.

```purescript
dnaToRna "GCAT" -- => "GCAU"
```

... it fails to display in the Kata description:

![screenshot 2019-01-16 at 19 07 46](https://user-images.githubusercontent.com/7777884/51245230-07fece00-19c2-11e9-9ab9-10da661425bf.png)

**Comment by kazk** [comment]
Fixed
