### ISSUE TITLE
Show test input please

### ISSUE THREAD

**Issue by robert-dzikowski** [Codewars/codewars.com#1687]
#### Is your feature request related to a problem? Please describe.
I'm always frustrated when I see failed tests but I can't reproduce them because test input isn't shown.

#### Describe the solution you'd like
I want to see test input for at least failed tests.

#### Additional context
![image](https://user-images.githubusercontent.com/12864860/51401706-c6019380-1b4b-11e9-9fcf-92f171ca7407.png)

**Comment by FArekkusu** [comment]
And, of course, you did not try printing the inputs yourself, did you?

**Comment by robert-dzikowski** [comment]
How can I do this?

**Comment by robert-dzikowski** [comment]
Yes I can do this, but it should be an option in codewars.

**Comment by kazk** [comment]
The test output is based on the test cases written by the kata authors and we don't control that.

See https://github.com/Codewars/codewars.com/issues/568#issuecomment-369006490

**Comment by KarmaBlackshaw** [comment]
![image](https://user-images.githubusercontent.com/40014179/69689943-39c5e280-1105-11ea-912d-22e8a50a4337.png)

**Comment by KarmaBlackshaw** [comment]
I know we cannot rewrite the test inputs of the author but how can I atleast see what were the inputted values?

**Comment by Steffan153** [comment]
Print the input?

**Comment by KarmaBlackshaw** [comment]
yes sir. It took me long enough of what input went wrong.

**Comment by yongduek** [comment]
You can just print out the input of the function, which does not cause a failure of your solution. This must be one thing different from other ordinary OJ systems which ask you to print out the result. Instead, here you just return your solution, but you can print anything out  during the procedure.

**Comment by LanPodder** [comment]
some katas make that impossible. there is a kata for instance, in which you return a regex which is then used in tests, but you do not get the input thus you cant print it

**Comment by kazk** [comment]
Please let the kata author know by commenting on the discussion page.

**Comment by mraa022** [comment]
yeah, they should add that future

**Comment by edisonpebojots** [comment]
Hello ladies and gentlemen. Am I wrong or the random test case is wrong?

**Comment by samyak0101** [comment]
> And, of course, you did not try printing the inputs yourself, did you?

How do you do this? Please help. I'm asking in python for example. How do I print the test inputs?

**Comment by K-D521** [comment]
`def function(inputs):
           print(inputs)
`?

**Comment by curiousgay** [comment]
@FArekkusu @kazk in Haskell there is no way to print input to functions because printing is a side effect, so using it will cause a type error at compile time, for example, the function's signature is `isPrime :: Int -> Bool`, but using print inside it will turn it into `isPrime :: Int -> IO Bool`

**Comment by kazk** [comment]
@curiousgay Use `Debug.Trace`

**Comment by Sebastianbc** [comment]
Just print the parameter right after the function definition. For python3 just use print(parameter).
