### ISSUE TITLE
submit button repeated failures

### ISSUE THREAD

**Issue by melanoman** [Codewars/codewars.com#169]
dozens of failures over a couple hours trying to upload an answer to millionth fib number problem.

Previous solution had an infinite loop due to bad argument order in a call. I haven't been able to run a fixed solution.  The "run tests" button works fine on it, and it answers a large test case quickly.

**Comment by melanoman** [comment]
And yes, I checked the status page.  It reports no problems.

**Comment by melanoman** [comment]
I went back and did an 8kyu problem and it submitted just fine. The problem seems to be specific to my solution. It's recursive, but should not go more than a two-digit number of stack frames.  It works in "run Tests" for values over 1M, but fails in "submit"

**Comment by melanoman** [comment]
(problem is in the 3kyu section)

**Comment by kazk** [comment]
Closing because this is most likely due to inefficient solution.
Use [the kata discourse](https://www.codewars.com/kata/the-millionth-fibonacci-kata/discuss) for kata specific issues/questions.

**Comment by melanoman** [comment]
When I run the exact same code now, it works fine. Your diagnosis was wrong. This is likely a duplicate of a problem that was fixed during the intervening years since I reported it.

**Comment by kazk** [comment]
> Your diagnosis was wrong.

Sorry, I misunderstood your comment.

> The problem seems to be specific to my solution.
