### ISSUE TITLE
GitHub profile avatars are not shown on dashboard

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1690]
e.g on kata comments:

![image](https://user-images.githubusercontent.com/14909989/51453772-48709a00-1d7c-11e9-86f7-ed41c0f375ae.png)

But on dashboard:

![image](https://user-images.githubusercontent.com/14909989/51453792-57574c80-1d7c-11e9-82de-0999a223e1de.png)

This appears to only happen for a tiny portion of users.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c7a) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
This is because some parts of Codewars only checks user's avatar image from GitHub and some parts check all GitHub,Twitter,Facebook before using the fallback image.

This user has Facebook linked and not GitHub so I'm assuming the image is from Facebook.

Don't ask me why.

**Comment by VanessaGreene** [comment]
@Voileexperiments Is this issue still present? If so I'd be happy to reopen this issue.
