### ISSUE TITLE
Can't see solution for specific Kata

### ISSUE THREAD

**Issue by Encrobaser** [Codewars/codewars.com#1696]
Yeah so I just solved the following Kata:

https://www.codewars.com/kata/balanced-number-special-numbers-series-number-1/java

But I cannot see the solutions, any at all (my solution is visible on my profile):

![what](https://user-images.githubusercontent.com/47091179/51807740-3f575f80-228b-11e9-855e-25f33c62cfc3.png)

It also still says train on the right upper hand side. 

I am really clueless what to do. Thanks for the help in forward!

**Comment by hobovsky** [comment]
#1683

**Comment by kazk** [comment]
Closing as duplicate of #1683
