### ISSUE TITLE
Make `/kata/beta` more discoverable

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1698]
So I found that this endpoint has "Estimated Rank" and "Beta Status" shown under the katas (not sure if it's a recently added feature or not):
https://www.codewars.com/kata/beta

![image](https://user-images.githubusercontent.com/14909989/51817711-ceee2400-2306-11e9-98a6-1c61094e45b3.png)

But the typical endpoints that users will stumble on does not have them shown:
https://www.codewars.com/kata/search/?beta=true
https://www.codewars.com/kata/search/?q=&beta=true
https://www.codewars.com/kata/latest/?beta=true

**Comment by kazk** [comment]
I **didn't know about this**, but it seems to be working as intended. `/kata/beta` lists all beta kata with status and an estimated rank.
Other ones are search results.

**Comment by Voileexperiments** [comment]
Yeah, but to be honest `/kata/beta` is infinitely more useful than the other pages with the beta status and estimated rank shown along with the entries. I think they should be displayed along with search result entries of beta katas by default.

**Comment by kazk** [comment]
I've made a change so that the detailed beta status is always shown.
