### ISSUE TITLE
CamingoCode isn't completely monospaced

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#17]
I'm not sure whether this is a problem with CamingoCode, gecko's font rendering (FF 33 and higher on Windows 7, 8, 8.1, Ubuntu 12.04, 14.04) or the syntax highlighter + custom stylesheets, but the code isn't completely monospaced. You'll notice this in Haskell often, since people try to align the code manually, like:

``` haskell
-- http://www.codewars.com/kata/reviews/55169d3a891547bedd000681/groups/551856df048fd53df1000004
module Codewars.Kata.Spinning where

spinWords :: String -> String
spinWords = unwords . map rev . words
  where
    rev w | 4 < length w = reverse w
          | otherwise    = w
```

However, the results aren't that nice:
### [Example 1](http://www.codewars.com/kata/reviews/55169d3a891547bedd000681/groups/551856df048fd53df1000004)

![hello-kata](https://cloud.githubusercontent.com/assets/6301773/6915905/5fa48c96-d798-11e4-8328-4d84a8660655.png)
### [Example 2](http://www.codewars.com/kata/reviews/523b4ff7adca849afe000038/groups/5450c8422433c33ce7001005)

![spin-kata](https://cloud.githubusercontent.com/assets/6301773/6915904/5fa3afce-d798-11e4-9057-6265dcc57b74.png)

**Comment by bkaes** [comment]
I just noticed that the issue vanishes if one removes the `font-face: bold` rule, which also explains why the issue doesn't happen in the usual code editor.
