### ISSUE TITLE
Add Gitter chat link to new documentation homepage

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#170]
https://gitter.im/Codewars/codewars.com

**Comment by javatlacati** [comment]
migrated: https://codewars.ideas.aha.io/ideas/CW-I-97 please close :)

**Comment by javatlacati** [comment]
since Aha is no loger in use should it be reopened?

**Comment by jhoffner** [comment]
I believe we do link from the forum/docs. Though it's not the most super obvious thing in the world. Might be a good thing. If Gitter blew up with too many people cheating it might just become a lot of noise.

**Comment by jhoffner** [comment]
@kazk when we think through the documentation styling and home page design we should take this into consideration.

**Comment by kazk** [comment]
Added to wiki.
