### ISSUE TITLE
Trainer page cannot be scrolled in vertical layout (<768px)

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1700]
![image](https://user-images.githubusercontent.com/14909989/51821945-b2a5b380-2315-11e9-9fee-2a48856cf733.png)

Without scrolling in vertical layout, the page is completely unusable.

Vertical layout is also the (mostly likely) default view for mobiles, so this also means mobile view is currently broken.

Fix: add `overflow-y: overlay;` to `#app`

**Comment by kazk** [comment]
This is fixed. Some of the CW layouts are controlled by JS and it still doesn't look great, but it should be usable now.
