### ISSUE TITLE
Kumite page caches its results

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1701]
Related to #992.

Sometimes the kumites shown on the kumite page is recent:

![image](https://user-images.githubusercontent.com/14909989/51823356-247ffc00-231a-11e9-8bf0-a146d21acbe6.png)

But sometimes they're from the (stale) cache:

![image](https://user-images.githubusercontent.com/14909989/51823341-1cc05780-231a-11e9-8267-ec25ee312e81.png)

**Comment by kazk** [comment]
This should be fixed. Please let me know if this happens again.
