### ISSUE TITLE
Publishing a kata sometimes returns an uninitialized page

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1702]
A fully initialized kata editor page should be this:

![image](https://user-images.githubusercontent.com/14909989/51824974-b7bb3080-231e-11e9-9792-8adb7810a272.png)

However, after re-publishing sometimes an uninitialized page is returned:

![image](https://user-images.githubusercontent.com/14909989/51824948-a114d980-231e-11e9-8a7a-7c99519df4b2.png)

Performing a diff on the html page returned by both occasions shows these differences:

- Language versions are not hidden, so all of them are shown (from 20041219 to 2.4/ES3)
- Description is not rendered
- All 5 editors (preloaded, initial code, example tests, actual tests, author solution) is not initialized with content, and `text-editor-container` class is missing

There's also this error from the console:

![image](https://user-images.githubusercontent.com/14909989/51826509-32d21600-2322-11e9-835e-af3d84f7ad54.png)

`App.controller.options` has `reinit = true`, so this probably means that *something* called the init to fail. Indeed when I run `App.controller.init()` again the same error occurs, with a much simpler stack trace:

![image](https://user-images.githubusercontent.com/14909989/51826970-4af66500-2323-11e9-834d-2efbee93473e.png)

**Comment by kazk** [comment]
Fixed when #2056 was closed.
