### ISSUE TITLE
Manually(?) retired katas are still listed in the kata list

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1703]
The katas which were retired due to their satisfaction rating being too low "manually" (with a script, or through revalidation) after the discussion at https://github.com/Codewars/codewars.com/issues/1672#issuecomment-457953084 can still be found by searching.

![image](https://user-images.githubusercontent.com/31668662/51858166-b26cde80-233c-11e9-9229-b1f14a9135da.png)

**Comment by kazk** [comment]
Thanks for reporting this.

Those were auto-retired, but scripted after updating the condition. Maybe the search index didn't get updated.

**Comment by Blind4Basics** [comment]
It may happen in the list of suggested katas too, under the description of another kata:

![image](https://user-images.githubusercontent.com/32236948/53438577-7b9fec00-3a00-11e9-8432-9c9c203f27b1.png)

**Comment by kazk** [comment]
I just updated the search index for all of the retired kata so this should be fixed.
