### ISSUE TITLE
Approved translation doesn't appear in the kata

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#1707]
https://www.codewars.com/kumite/5c3e25c697146234e8c5b4ec?sel=5c3e25c697146234e8c5b4ec
This translation was approved 14 hours ago, but it has not appeared in the kata.

**Comment by kazk** [comment]
Weird. The kata doesn't have C# data and I don't see any failed job for this.

**Comment by virgesmith** [comment]
I have a similar issue - I did a rust translation of this: https://www.codewars.com/kumite/5c6ae2c8a425fc51d0e20674?sel=5c6ae2c8a425fc51d0e20674. The OP has not been active in years, and it allowed me to self-approve, so I did. But it hasn't appeared.

**Comment by error256** [comment]
It happened again: https://www.codewars.com/kumite/5cb88dd889b1c50024aa24f7?sel=5cb8f93a8a40f70013da61c1

**Comment by kazk** [comment]
I think this is the same as #1793. https://github.com/Codewars/codewars.com/issues/1793#issuecomment-482893334 is what I think is happening. Forking and approving again seems to work for now.

I'll close this one as duplicate.
