### ISSUE TITLE
New API endpoint to get katas

### ISSUE THREAD

**Issue by darthzyklus** [codewars/codewars.com#1708]
I'm trying to make a telegram bot to get a number of katas from codewars but there is no such endpoint .

#### Description about the solution I'd like
It would be great if exist an endpoint like /api/v1/code-challenges/ to get a certain number of katas. Also It would be awesome if your can paginate the results or filter them with query parameters like language and kyu.

**Comment by kazk** [comment]
Closing as a duplicate of #2302 (This was filed before, but that one has more info.)
