### ISSUE TITLE
Translation into a language does not advance a progress in that language

### ISSUE THREAD

**Issue by MMMAAANNN** [codewars/codewars.com#171]
Kata: http://www.codewars.com/kata/whitespace-interpreter

I have translated this 2 kyu kata into Python. I specifically avoided editing the kata directly before my translation was approved to make sure this translation will help me progress in Python.

Before the translation was accepted, my progress in Python was 2 kyu - 0 %.

Now that the translation got accepted (but previously forked by kata author because of the "mismatched description" bug), I approved the kata.

Unfortunately, my progress in Python remained the same - 2 kyu, 0 %.

I think this is not fair for the translators. This a second translation of a 2 kyu kata (first was http://www.codewars.com/kata/ascii85-encoding-and-decoding/) which I translated to Python and which did not add a single point to my progress in the language (the first one was probably due to the old bug where my translated solution actually appeared under original kata author's name). It appears that those who translated katas into a certain language are underpriviliged compared to those who will simply use the translation afterwards - and it makes it really hard to earn a 1 kyu in a language by doing translations.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c7k) by [Unito](https://www.unito.io)

**Comment by GiacomoSorbi** [comment]
+1

**Comment by hilary** [comment]
:+1:
