### ISSUE TITLE
Kata Search Page unable to display Kata most of the time

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1716]
I logged in to Codewars today (04/02/2019) at 1320 GMT +8 and when I tried to search for Kata in https://codewars.com/kata/ , the Kata search page responded with "There are no items to display":

![screenshot 2019-02-04 at 13 20 19](https://user-images.githubusercontent.com/7777884/52191699-0289fa80-2881-11e9-9d25-23c8a6f444e5.png)

I double-checked my trainer setup to see if my list of chosen languages were empty somehow but everything seemed perfectly normal - all my usual selected languages were highlighted:

![screenshot 2019-02-04 at 13 23 34](https://user-images.githubusercontent.com/7777884/52191748-39601080-2881-11e9-927d-96bdeae43367.png)

I then tried to filter Kata search results with a few random languages with the same (empty) result:

PureScript: 
![screenshot 2019-02-04 at 13 25 04](https://user-images.githubusercontent.com/7777884/52191803-817f3300-2881-11e9-9573-60bf8f25ba18.png)

Haskell: 
![screenshot 2019-02-04 at 13 25 20](https://user-images.githubusercontent.com/7777884/52191815-8a700480-2881-11e9-9c3d-c686ffd691eb.png)

Java: 
![screenshot 2019-02-04 at 13 26 17](https://user-images.githubusercontent.com/7777884/52191826-94920300-2881-11e9-8151-744f4c158a1b.png)

JavaScript:
![screenshot 2019-02-04 at 13 26 27](https://user-images.githubusercontent.com/7777884/52191835-9d82d480-2881-11e9-84df-f2df5dba8349.png)

Incidentally, I also tried to filter Kata by rank (JavaScript Kata, `6 kyu` only) to no avail: 
![screenshot 2019-02-04 at 13 27 13](https://user-images.githubusercontent.com/7777884/52191855-b25f6800-2881-11e9-8e40-6679f0d93fe5.png)

Filtering by keywords ("Peano", I was trying to find Kata on Peano arithmetic to translate into PureScript) doesn't work either:

![screenshot 2019-02-04 at 13 45 23](https://user-images.githubusercontent.com/7777884/52192157-4b42b300-2883-11e9-82b1-ac0983e5a991.png)

****

UPDATE: I just performed a simple "Inspect Element" and found the following console errors and warnings.  Perhaps they're somehow related to this issue?

![screenshot 2019-02-04 at 13 49 22](https://user-images.githubusercontent.com/7777884/52192244-d754da80-2883-11e9-8f95-bf7379c57c2b.png)
![screenshot 2019-02-04 at 13 49 30](https://user-images.githubusercontent.com/7777884/52192245-d754da80-2883-11e9-9dca-1fb4a24bc07d.png)

**Comment by DonaldKellett** [comment]
Some extra information that may or may not be relevant:

Operating System: macOS Mojave (v10.14.2)
Browser Version: Safari v12.0.2

**Comment by chadcodes0** [comment]
Can confirm, kata page not loading. Where there's normally a list of kata it only says "There are no items to display" as posted above.

**Comment by kazk** [comment]
The Elasticsearch service was down. It should be fixed now.
