### ISSUE TITLE
Do we want (or need) to update legacy-version-only katas to work in new versions?

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1720]
This applies to the languages with multiples versions on CW, whose legacy and new versions are incompatible with each other. My main concern is **Haskell**; if my understanding is correct, **Rust** also applies. I believe CW has a plan to drop the hacky legacy versions at some point, then all of the contents in this status are rightout broken or unusable.

Here, the main topic is a "yes/no" question; "how" should be discussed later.

---

The rest is about the current situation of Haskell.

I have solved every single *white-level* Haskell kata/translation, which is almost half of all Haskell katas/translations (600s out of 1300s at the time of writing). Unfortunately, to my impression, most of them were written just for Haskell 7, even the ones that can be easily edited to run in 8.

I've also seen a translation that's only 6 months old but still uses the legacy style. I can't blame them because Haskell 8 runner was introduced so recently (~10 months ago). But still, I think new contents should be written in new style, and having the majority written in legacy style is very bad situation for that.

**Comment by kazk** [comment]
Yes.

We don't want to wrap Hspec/HUnit and maintain a patched `hspec` function :| We'll figure out how to do `hidden` together.

For Rust, I created [List of Rust 1.15 Kata to update](https://github.com/Codewars/codewars.com/wiki/List-of-Rust-1.15-Kata-To-Update) earlier today. I can do similar for Haskell.

**Comment by kazk** [comment]
Created [List of Haskell Kata to Update](https://github.com/Codewars/codewars.com/wiki/List-of-Haskell-Kata-to-Update)
