### ISSUE TITLE
[Bug] Ability to see the source code of tests

### ISSUE THREAD

**Issue by sjx233** [Codewars/codewars.com#1721]
#### Describe the bug

One can see the source code of tests (may contain the solution) by accessing the file system.

#### To Reproduce

1. Go to the training page of any kata.
2. Set the language to JavaScript (for example).
3. Add this line:
    ```javascript
    console.log(require("fs").readFileSync("/home/codewarrior/index.js").toString());
    ```
4. Click on [Attempt].
5. <details>
      <summary>The source code appears in the Log section.</summary>

      ```javascript
      require("/runner/frameworks/javascript/cw-2");
      var assert = require("assert");
      Test.handleError(function() {
        /* Preloaded */;
        /* Solution */

        ;(function() {
          var Test = global.Test, describe = global.describe, it = global.it, before = global.before, after = global.after;
          /* Test Cases */;
        })();
      });
      ```

    </details>

#### Expected Behavior

Any attempt to access the FS should throw or do nothing.

#### Contexts

- OS: macOS
- Browser: Safari
- Browser Version: 12.0.2

**Comment by Voileexperiments** [comment]
> Any attempt to access the FS should throw or do nothing

This is not possible because it's the only way to read user solution code (in `/home/codewarrior/solution.txt`) in text fixture. Permission for individual files should be configurable though.

**Comment by kazk** [comment]
This is not a bug
