### ISSUE TITLE
Kata editing permission is not thoroughly documented and UI is not consistent

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1723]
#### Describe the bug

At 4000 honor, a user is supposed to get a power to contribute to others' katas. For approved katas though, the permission seems to vary from one kata to another. Also, a kata is sometimes editable even when it doesn't show "edit kata" button in the UI.

#### To Reproduce

1. Take an account with barely above 4K honor
2. Solve a kata, such as [6kyu Squares in a Rectangle](https://www.codewars.com/kata/squares-in-a-rectangle/haskell) or [6kyu String Character Frequency](https://www.codewars.com/kata/string-character-frequency/haskell)
3. Move to description or discussion page. "Edit kata" button is not there, for both of them.
4. Manually move into the editor page at `/kata/(kata_title)/edit/(language_name)`
5. For the first one, I get a simple error message "You do not have permissions to view this page". On the other hand, I could successfully edit the second and even republish.

Notably, both katas have Haskell versions as translations with <10 solves, and ~300 solves as whole kata. Also, both authors are active (last seen Feb 2019). The only difference is that the first hasn't got any issues yet. I remember that a kata is unlocked to community when it has a dangling issue for a week - is it still correct?

For the UI, ~~my rough guess is that "Edit kata" gets hidden if the kata has "allow contributor" disabled, and it doesn't check for the "unlocked" status.~~ Looking at [this one](https://www.codewars.com/kata/a-rule-of-divisibility-by-7/haskell), it already has "allow contributor" enabled but still doesn't show the "edit kata" button.

#### Contexts

- OS: Windows 8.1
- Browser: Chrome
- Browser Version: 71.0.3578.98

**Comment by LesnyRumcajs** [comment]
I can confirm this also happens on:
###
    * OS: Linux Fedora 29
    * Browser: Firefox
    * Browser Version: 64.0.2 (64-bit)

**Comment by kazk** [comment]
I just looked at the code. For approved kata, "Edit Kata" is shown to authors and users with enough honor to approve kata (6000). This doesn't make any sense :(

I'll change this to show if you have enough honor to coauthor (4000).

**Comment by Bubbler-4** [comment]
@kazk Good, I can see the UI part is fixed. Can you confirm this part in the OP?

> I remember that a kata is unlocked to community when it has a **dangling issue for a week** - is it still correct?

**Comment by kazk** [comment]
Yeah, I deployed that fix like 30 minutes ago.

For "dangling issue for a week", I'm still looking. I don't think I touched it since I inherited so it should be the same as before.

**Comment by kazk** [comment]
@Bubbler-4 For approved kata, you can edit if

1. You authored it
2. You coauthored it in the past
3. You have enough honor points to be a coauthor and there's unresolved issue/suggestion for over a week

So unresolved issue/suggestion is needed in order to become a _new_ coauthor. For beta kata, this restriction doesn't apply.

I'll add this to the documentation.

**Comment by kazk** [comment]
Added to the bottom of [Privileges](https://github.com/Codewars/codewars.com/wiki/Privileges)
