### ISSUE TITLE
Individual language progress not gained upon approval of translation

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#1724]
I authored PureScript translations to [Isomorphism (`3 kyu`)](https://www.codewars.com/kata/5922543bf9c15705d0000020/) and [Algebraic Isomorphism (`2 kyu`)](
https://www.codewars.com/kata/5917f22dd2563a36a200009c/discuss#5c6163a35a40bc2a019ece77) 5 days ago and they were both approved in the past hour or two but my PureScript rank progress didn't move an inch - it remained at exactly `5 kyu`/`10%`.  However, I am certain that Codewars has at least partially registered both translation approvals because my honor leaped from `58274` to `58606`.

Just to clarify, I have _not_ been a past contributor to either Kata and I have never visited the edit panel nor viewed solution forks / translations of others so I fail to see how I have forfeited my eligibility to gain individual language rank progress in either/both Kata.

kazk Perhaps there is a bug in the system which you could track down?  Your help would much be appreciated :smile:

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c87) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
For both of them, your PureScript solution has `points_eligible: false`. I'll try to find out why.

**Comment by FArekkusu** [comment]
Encountered the same issue but with solving a kata. I've completed the recently-approved Java version of [this task](https://www.codewars.com/kata/54ce4c6804fcc440a1000ecb) but my rank stayed at the same level - `5 kyu / 88 %`. I don't remember whether I 100% did *not* access the editor, but I'm fairly sure this never happened, as no issues were raised, hence I didn't need to fix/edit anything.

**Comment by FArekkusu** [comment]
Encountered the same issue but with solving a kata. I've completed the recently-approved Java version of [this task](https://www.codewars.com/kata/54ce4c6804fcc440a1000ecb), and C version if [this task](https://www.codewars.com/kata/the-observed-pin) but my rank stayed at the same level - `5 kyu / 88 %`, and `4 kyu / 31 %`, accordingly. For some reason, I can view the solutions in any of the available languages as if I forfeited the kata (definitely did not happen) or accessed the kata editor (not "definitely" but I'm fairly sure this never happened as well).

**Comment by kazk** [comment]
@FArekkusu 

> I've completed the recently-approved Java version of [this task](https://www.codewars.com/kata/54ce4c6804fcc440a1000ecb), and C version if [this task](https://www.codewars.com/kata/the-observed-pin) but my rank stayed at the same level

The job queue is currently backed up. So this might be just not processed yet.

You're listed as a contributor for both of them. So that might be the cause of the other two.

> accessed the kata editor (not "definitely" but I'm fairly sure this never happened as well)

This was fixed few days ago to show it to users who can edit the kata. You can see it because you've contributed in the past (or at least Codewars thinks you did).

**Comment by Blind4Basics** [comment]
> This was fixed few days ago to show it to users who can edit the kata. You can see it because you've contributed in the past (or at least Codewars thinks you did).

Mmmmh... meaning that, if I understand correctly:

* I translate a kata
* the translation gets approved, so I become a contributor to that kata
* but I never entered the edit panel
* and I still will see the solutions in any languages?

Meaning, that will forfeit other languages as soon as a translation is posted, right? Or, if still eligible, the contributor wouldn't have any idea that he still is eligible, seeing solutions in any language.

?

**Comment by kazk** [comment]
@Blind4Basics 
The only change was to make "Edit Kata" link to **show** if you can edit the kata. See https://github.com/Codewars/codewars.com/issues/1723#issuecomment-462466847

I didn't change anything else.

**Comment by FArekkusu** [comment]
@kazk speaking of the first kata: I'm writing a translation of it right now, and for some reason I can see the original Haskell version despite never even attempting it. Something is definitely wrong here.

**Comment by kazk** [comment]
@FArekkusu Thanks for the screenshot. I had no idea what you meant without it.

According to the data, you haven't attempted, but you've seen Haskell solutions.

**Comment by kazk** [comment]
> For some reason, I can view the solutions in any of the available languages as if I forfeited the kata (definitely did not happen)

Did you open Haskell's solution page when you observed this? If so, that's why it's showing you Haskell translation.

I don't know what made you forfeit yet.

**Comment by FArekkusu** [comment]
I opened the Haskell solutions page today (some time before I've left a comment here) to check whether solutions were visible to me, i.e. whether I "forfeited" it. I'm not sure if I'd seen it earlier, but even in that case, it should have been locked for me as I haven't completed the Haskell version before opening the solutions page.

**Comment by kazk** [comment]
> it should have been locked for me as I haven't completed the Haskell version before opening the solutions page.

You were already a contributor right? I'm looking at the code related this and it seems like it's _not locked if you're a contributor_. Once you open that page, it creates a record that you saw solutions for that language.

I'm still trying to get my head around it so I might be wrong. It's surprisingly complicated like always and it's all over the place.

**Comment by FArekkusu** [comment]
Yep, in both cases I was already a contributor when I solved the kata in a new available language.

**Comment by kazk** [comment]
@FArekkusu I think #1163 is what you experienced. So I guess it's been like this since at least October 2017.

**Comment by DonaldKellett** [comment]
@kazk Any progress on the original issue?  I'd also like to reclaim my lost (PureScript rank) progress on those two translations if possible - after all, I didn't author them for nothing :wink:

**Comment by kazk** [comment]
I'll post something if I find something. I'm sorry but this isn't highest priority.

Just to be clear, you're getting progress from other translations of kata that you never contributed before right?

**Comment by DonaldKellett** [comment]
> Just to be clear, you're getting progress from other translations of kata that you never contributed before right?

I think this bug(?) might have happened on one or two more Kata around the time I posted this Issue but it/they were like `5 kyu`s so I didn't pay much attention to them.

****

@kazk I do appreciate all the hard work you have put in to actively maintain and improve the quality of Codewars over the past year or so so feel free to take as much time as you need on this one :smile:

**Comment by nomennescio** [comment]
Seems awfully similar to #841
