### ISSUE TITLE
Translation fork to add a language version is not applied to the kata when approved

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1725]
#### Describe the bug

On a kata written by g964, I forked a Haskell translation and got it approved by g964 himself, but the test cases didn't change at all. It happened twice today, [here](https://www.codewars.com/kata/1-slash-n-cycle/haskell) and [here](https://www.codewars.com/kata/a-rule-of-divisibility-by-13/haskell).

#### To Reproduce

1. Pick an approved kata, where the author has also written some translations (marked as "Approved")
2. Pick one of the translations and make a fork **that enables a new version of that language**
3. Get it approved by the original author
4. The new fork is **not** live; you can still see the test suite in the old translation.

**Comment by kazk** [comment]
Does this work when it's not by the kata author?

> 3\. Get it approved by the original author

Approver doesn't seem to affect this because I just approved "A small difference" and it's having the same issue.

**Comment by Bubbler-4** [comment]
I just listed all the things the two occasions have in common; didn't have a chance to identify which one is the cause.

**Comment by kazk** [comment]
This is happening because the language version of the fork is not in the "supported versions" of the language for the kata which is obvious because we're trying to add it :man_facepalming: 

I guess we can't do this through fork unless I can find some workaround.

**Comment by virgesmith** [comment]
I'm also having this problem with a [translation](https://www.codewars.com/kumite/5c6ae2c8a425fc51d0e20674) that's seemingly stuck in limbo - approved but not visible. 

I notice that when you click on https://www.codewars.com/kata/matrix-determinant/forks/rust the selected language is ruby, not rust, and there are no translations

**Comment by Bubbler-4** [comment]
@virgesmith This thread is about the issue where e.g. you already have a translation approved with Haskell 7 only, then you try to approve its fork that has Haskell 8 enabled. I think yours is different because you don't have any approved Rust translation in the first place.

**Comment by kazk** [comment]
This should be fixed now. Those that failed before the fix needs to be forked and approved again.
