### ISSUE TITLE
Wrong selector to toggle rank assessment

### ISSUE THREAD

**Issue by ZEDCWT** [Codewars/codewars.com#1736]
#### To Reproduce
+ Rank any beta kata
+ After responsed, click any `<li>` element of kyu description, like `Defining a simple function (i.e. hello world)`, `Fixing basic syntax issues`, ...
+ Then the rank assessment would be toggled off

#### Fix
Correct the `.assessment-ranks li click` selector in `application.js`

**Comment by kazk** [comment]
Most likely a duplicate of #283 if I'm understanding correctly, but I'll close this when I fix it

**Comment by kazk** [comment]
Fixed
