### ISSUE TITLE
Power users' satisfaction votes count that many times to author's honor?

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1737]
#### Describe the bug

[One Line Task [Haskell]: 100 times...](https://www.codewars.com/kata/5c6cabe8ea8d326d7e216029) has 4 satisfaction votes, but it counts as 13 on the "site-events" page. Similarly, [One Line Task [Haskell]: Weak Primality Test](https://www.codewars.com/kata/one-line-task-haskell-weak-primality-test/haskell) has two votes, but 8 on "site-events". For the latter, the two votes are from Voile and ZED, so I'm pretty sure the x4 power counts *literally* as four votes per user, which gives 8 honor per vote to the kata author (in this case, me).

I have no idea if this is by design or a bug, but it's quite an unexpected behavior (at least to me).

Also, I wonder if votes *after* approval doesn't get weighted like that? I guess all the users who solved "100 times" are power users (at least the six visible ones are), but then the count of 13 doesn't make sense unless the statement is true. If so, it's inconsistent behavior, at least.

Name | Count | Honor Earned
-- | -- | --
Authored code challenge up voted"One Line Task [Haskell]: 100 times..." | 13 | 26
Authored code challenge up voted"One Line Task [Haskell]: Weak Primality Test" | 8 | 16

**Comment by Voileexperiments** [comment]
Does the total add up to your amount of honor though?

**Comment by Bubbler-4** [comment]
Yes, the total is correct, and it's consistent with the profile page.

**Comment by jhoffner** [comment]
It's by design
