### ISSUE TITLE
[PHP] time out problem during tests (after attempt)

### ISSUE THREAD

**Issue by keyball** [Codewars/codewars.com#1738]
#### Describe the bug
I tried to "commit" several katas with the button "attempt". I'd got always "Execution Timed Out (12000 ms)". The basic tests work perfectly. The code execution on a local machine (even with a complex example) was not higher as 4600ms

#### To Reproduce

1. Go to 'https://www.codewars.com/kata/561e9c843a2ef5a40c0000a4/train/php'
2. Enter the code
`
function isPrime($n)
{
    for ($i = 2; $i < $n; $i++) {
        if ($n % $i === 0) {
            return false;
        }
    }

    return true;
}

function gap($g, $m, $n)
{
    $result = [];

    for ($i = $m; $i <= $n; $i++) {
        if (!isPrime($i)) {
            continue;
        }

        $hasPrimes = false;

        $nextPossiblePrime = $i + $g;

        if ($nextPossiblePrime <= $n && isPrime($nextPossiblePrime)) {

            for ($j = ($i+1); $j < $nextPossiblePrime; $j++) {
                if (isPrime($j) ) {
                    $hasPrimes = true;
                    break;
                }
            }

            if ($hasPrimes === false) {
                return [$i, $nextPossiblePrime];
            }

        }
    }

    return null;
}`
3. Click on  'RUN SAMPLE TESTS' button
4. See the correct response
5. Click on 'ATTEMPT' button

#### Expected Behavior

The code should pass the tests without a timeout. On my local server I used this example to check the time:

`$s = microtime(true);
print_r(gap(2, 3, 50));
print_r(gap(4, 100, 110));
print_r(gap(6, 100, 110));
print_r(gap(8, 300, 400));
print_r(gap(10, 300, 400));
print_r(gap(18, 400, 430));
print_r(gap(10, 10000000, 100000000));
$e = microtime(true);

echo (($e-$s) * 1000) . 'ms' . PHP_EOL;`

And I'd got these results:
`array(2) {
  [0]=>
  int(3)
  [1]=>
  int(5)
}
array(2) {
  [0]=>
  int(103)
  [1]=>
  int(107)
}
NULL
array(2) {
  [0]=>
  int(359)
  [1]=>
  int(367)
}
array(2) {
  [0]=>
  int(337)
  [1]=>
  int(347)
}
NULL
array(2) {
  [0]=>
  int(10000261)
  [1]=>
  int(10000271)
}
Time spent for processing: 4508.2459449768ms`

As You can see, the example was pretty complex (print_r(gap(10, 10000000, 100000000));) and it took about 4,5 seconds to process on an i7-7700hq with the Windows version of PHP 7.3 interpreter

#### Screenshots

![obraz](https://user-images.githubusercontent.com/241064/53146908-2ac66880-35a6-11e9-98c4-7457ab9d0e3f.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related):  keyball
- OS: Windows 10
- Browser: Firefox Nightly
- Browser Version: 67.0

**Comment by kazk** [comment]
Not Codewars issue.
Try improving your solution. Your solution is much slower (about x4) compared to the accepted answer I tried.

**Comment by kazk** [comment]
PHP version of this kata has 10 fixed tests and 50 random tests. The largest basic test case is `gap(2, 10000000, 11000000)`.

**Comment by y21** [comment]
A bit late but I'm having the same issue now and I'm pretty sure my code is efficient enough.<br/>
Kata: [Powers of 3](https://www.codewars.com/kata/powers-of-3/train/c)<br/>
Language: C<br/>
Used code (to reproduce): <br/>
```c
#include <math.h>
int largest_power(long long n) {
    if (n == 1) return -1;
    for (long long i = n; i > 0; --i) {
        if (pow(3,i) < n) {
          return i;
        }
    }
}
```

I ran this code locally in a loop (5000 times, which is obviously much more than the amount of tests) and it took about 10 seconds (worth mentioning that this was on my Raspberry Pi)<br/>
![2019-10-20-145740_1138x777_scrot](https://user-images.githubusercontent.com/30553356/67159802-fdef6e80-f349-11e9-93e5-a92a63bd3002.png)
As you can see, all tests were fine but it's just timing out everytime I press "attempt".  I don't know if there is a bug in my code that causes an infinite loop but as I mentioned above, it works perfectly fine on my machine. The basic tests worked fine as well.

**Comment by FArekkusu** [comment]
@y21 please, use kata discourse for such questions. Your code is inefficient, and if you test it with something like `n = 1,000,000,000` you will see it yourself.

**Comment by y21** [comment]
Thanks for your answer and alright, will use that instead for the next time. I was just curious as to why that would time out even though all tests have passed and almost the same code does not time out in JavaScript. But I see now, seems to be inefficient to do it that way.
