### ISSUE TITLE
Forked translations

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#174]
Partially related to #83, I was wondering in case user A makes a translation, then user B forks it and finally author C approves that. I doubt one gets honor just for being the author, but not sure who takes the loot among A and B.

I am asking not much because I fear for my own score (I won't bleed for losing a few tens points), but as it has happened a lot in the recent past (mostly in kata by matt c, as he used to fix them editing the description before approving pending translations), I would find it a little unfair.

On the other hand, if user A's original translation was pretty poor, currently the only way to submit another one is to fork the A's work and then write your own: doesn't matter if you change it all, you still have to start as a fork: in that case, would be quite fair that B took the price, of course.

So, in few words, I wonder how CW is currently handling it and how it could be fixed (maybe author deciding it and involved users getting notified could be the best solution?).

Oh, on a side note: it looks like Gaurang's forks [here](http://www.codewars.com/kata/find-all-possible-number-combos-that-sum-to-a-number/) today were correctly notified both to me and @bkaes-senpai. Previous works forked by matt c were not. Unless forking notification has been fixed recently, I wonder about that too: if my work was lacking and it needed a fork, I would like to know it for sure :)

**Comment by jhoffner** [comment]
This is a good question (probably would have been better asked in a gitter channel but here works). As of now the original translator gets credit. Its not perfectly fair in all cases, but it would be pretty hard to devise a system that would be. If we could come up with a more fair system I imagine it would entail a huge amount of redesign and work, probably involving some sort of user voting or something. 

Yes the notification system was improved I believe last week (maybe 2 weeks ago? I can't gauge time anymore). You shoud be receiving notifications about all forks (which was always the case, but there were a few bugs causing failed deliveries).
