### ISSUE TITLE
can't submit an answer

### ISSUE THREAD

**Issue by juanda3111** [Codewars/codewars.com#1743]
I completed the "Search for a substring within a string", pass every test, and every seems to be ok , but I can't see the submit button.  
![bildschirmfoto von 2019-02-25 14-17-26](https://user-images.githubusercontent.com/34226466/53363664-1ddda800-390b-11e9-97ac-72cab7c680ca.png)

**Comment by kazk** [comment]
You can't submit on "Draft" kata.
