### ISSUE TITLE
Kata search page returns cached result

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1745]
Related: #992 

Kata search page returns cached result that is chosen randomly as well:

![image](https://user-images.githubusercontent.com/14909989/53624416-30255200-3c3b-11e9-8b37-85dedcdcc8ee.png)

![image](https://user-images.githubusercontent.com/14909989/53624420-34ea0600-3c3b-11e9-883e-01160a204f1b.png)

This happens in both https://www.codewars.com/kata/beta and https://www.codewars.com/kata/search/?q=&beta=true

**Comment by kazk** [comment]
This should be the same issue as #992 which was fixed.
