### ISSUE TITLE
Invalid solutions are always not fully initialized

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1747]
![image](https://user-images.githubusercontent.com/14909989/53694846-378d5c80-3def-11e9-9027-76b2d83e83f4.png)

It's impossible to perform the regular operations on them.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1c9h) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
I thought this was already reported, but I couldn't find one about invalid issue. I think this also happens to valid solutions towards the end of a large list.

Similar issue: #953

**Comment by anter69** [comment]
> I think this also happens to valid solutions towards the end of a large list.

Sometimes the comments don't load for normal solutions too, but a page refresh usually fixes it. However, with invalid solutions it **never** works: maybe it has to do something with the fact that they are hidden by default, and so the details are probably not loaded for them? And when you click to view them, the loading doesn't restart?

**Comment by kazk** [comment]
Closing because invalidated solutions are shown differently now
