### ISSUE TITLE
CodeMirror Markdown syntax highlighting breaks if `<[a-z]` is encountered

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1749]
![image](https://user-images.githubusercontent.com/14909989/53695158-044ccc80-3df3-11e9-8d2b-ae4c4a893149.png)

It also means HTML(XML) will never be able to be highlighted, while also breaking the entire highlight flow.

Is it related to #765?

**Comment by kazk** [comment]
I guess [xml mode needs to be loaded](https://codemirror.net/mode/markdown/).

Shouldn't be related to #765 because that's [highlight.js](https://highlightjs.org/) if I remember correctly and the letters around angle brackets disappears in that case.

**Comment by kazk** [comment]
Fixed

![image](https://user-images.githubusercontent.com/639336/53705424-36e9cb80-3dd9-11e9-882c-a0f90bf4a6a1.png)
