### ISSUE TITLE
Code is not sanitized properly

### ISSUE THREAD

**Issue by samczsun** [Codewars/codewars.com#175]
Using undocumented features and reflection, it is possible to fuzz one test case and force the remaining test cases to pass. 

See here:
![codewars](https://cloud.githubusercontent.com/assets/10292550/9530281/d1c9a80c-4ccc-11e5-94c6-d74f5d5ccf51.png)

A possible solution would be to enforce a SecurityManager on each running case

**Comment by samczsun** [comment]
It would appear that code is not sanitized in general, so I have updated this issue to reflect that.

Javascript is also not handled properly, leading to illegitimate solutions
![codewarsjs](https://cloud.githubusercontent.com/assets/10292550/9534374/fb40850c-4ce5-11e5-8f3c-1d6a76d666a4.png)

There is also a critical Java bug that I suggest you fix immediately. However, I do not think it is safe for me to say it here, so let's arrange some other secure way of communicating when you have time.

**Comment by samczsun** [comment]
![codewarsruby](https://cloud.githubusercontent.com/assets/10292550/9535562/9e6985ee-4cf0-11e5-8c5a-dab202a7440d.png)

Ruby suffers from the same problem that JavaScript does

**Comment by kazk** [comment]
I'm sorry that no one responded for nearly 3 years.

Bypassing tests like this has been always possible and it will be.
For Codewars, we simply rely on the community to report cheaters and repeated offenders are banned by the admins.
