### ISSUE TITLE
Rewarded Twice

### ISSUE THREAD

**Issue by jarch24** [Codewars/codewars.com#1750]
Hi,
The Kata **Answer the students' questions!** 6Kyu awarded me points twice, on the first go when i attempted the problem all went well but after i refactored the code and submitted again the  connection broke but somehow points were rewarded and it showed the solution have been withheld as you have not finished the kata, i attempted with the same code and on the second go all went well but i was awarded points again. Please look into it. My username **Gorgoroth**

Regards

**Comment by FArekkusu** [comment]
Duplicate of #1592.

**Comment by jarch24** [comment]
Agreed it is a duplicate of #1592 , should I close this issue ? Please also suggest what needs to be done on my end in regards to the reward points.

**Comment by kazk** [comment]
Closing as a duplicate of #1592.

@jarch24 there's nothing to be done on your end. The points will be eventually get fixed when the bug is fixed which needs a huge data fix.
