### ISSUE TITLE
'Fiddle' gem shouldn't be available in Ruby

### ISSUE THREAD

**Issue by EricDuminil** [Codewars/codewars.com#1756]
It's possible to use:

`require 'fiddle'`

in Ruby Katas, even though [fiddle](https://github.com/ruby/fiddle) Gem probably isn't necessary for any Kata. I couldn't find any `fiddle` reference either in Codewars sourcecode.

`fiddle` gives low-level access to Ruby objects and can be used to [unfreeze a frozen object](https://stackoverflow.com/a/35633368/6419007).

For example, `Test` class can be re-opened in order to modify `Test.assert_equals`. Here's an example for the [Sudoku Solver](https://www.codewars.com/users/eric_duminil/completed_solutions).

**Comment by kazk** [comment]
There's many ways to cheat if you try. We only try to prevent those that can be done accidentally.

Repeated offenders are reported by the community and are often banned. See our [Code of Conduct](https://github.com/Codewars/codewars.com/wiki/Community-Code-of-Conduct).

**Comment by EricDuminil** [comment]
@kazk  Sorry for the extra work, I only wanted to understand how the `Test` class works and didn't want to submit these hacks as being solutions. I understand if my account is being closed, I'd really appreciate if a moderator could simply delete the fake solutions, though.
Keep up the good work!

**Comment by kazk** [comment]
@EricDuminil No problem. Your account is not going to be closed because I don't think you've abused it yet, but please don't do it anymore.
