### ISSUE TITLE
Pagination control - Showing page numbers

### ISSUE THREAD

**Issue by bigtone1284** [Codewars/codewars.com#1757]
Please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue.
https://www.codewars.com/kata/pagination-control-showing-page-numbers/train/javascript

I don't understand the expected output to this problem.

Specifically in this instance:

Another example:

Total pages: 36
Current page: 1
Items before and after: 5
Expected [1 (always) 2,3,4,5,6 (5 before) ,7, (center) 8,9,10,11,12, (5 after) 36] (always)

If the total pages is 36, the current page is 1, and the items before and after is 5...how does it make sense to have a solution of `[1, 2,3,4,5,6,7,8,9,10,11,12, 36]`?

How does inserting 11 numbers after 1 make sense here? It seems rather arbitrary to me.  

I think this is either a bug OR the concept of "the center" needs to be better explain.  Right now the solutions to this problem seem arbitrary.  

Code could be written to solve this problem base on what the tests assert, but really the instructions don't explain this specific case.

**Comment by kazk** [comment]
> **Please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue.**
