### ISSUE TITLE
[Shameless show-off] Polyglot - Userscript for CodeWars

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#1758]
Hello all,

Recently I've created a Tampermonkey Userscript which would help me with some issues which were particularly annoying for me, especially addressing issues #790, #1162, #1272, #1641 and indirectly #727, #752. It seems to work for me and does not blow up for the other user (thanks for testing, B4B!), so maybe someone else would also find it useful. Feel free to use it, or to completely ignore it ;)

You can find the script in [this repo](https://github.com/hobovsky/polyglot).

Small summary of features:

1. Solved languages are marked:
![image](https://user-images.githubusercontent.com/23709795/54123489-36b48600-4400-11e9-8d41-8deec3259474.png)

2. Filtering by "Solved/not solved in [language]":
![image](https://user-images.githubusercontent.com/23709795/54123650-8bf09780-4400-11e9-9e66-9930d5f29bf0.png)

3. Access to site events page:
![image](https://user-images.githubusercontent.com/23709795/54123684-9f036780-4400-11e9-8e12-5a73aeeb74f1.png)

4. IDs resolved to links in site events:
![image](https://user-images.githubusercontent.com/23709795/54123731-c5c19e00-4400-11e9-8e71-ef63269110f8.png)

5. Copy code to clipboard
![image](https://user-images.githubusercontent.com/23709795/54124041-8e072600-4401-11e9-8efb-4b00352dfee8.png)

6. Solutions are tabbed by language
![image](https://user-images.githubusercontent.com/23709795/54124157-d0306780-4401-11e9-88d4-dd28b82080bc.png)

7. Spoler flags are always displayed, so it's more difficult to accidentally flag/unflag a comment.

Hopefully, some/all of the features will be one day incorporated into CodeWars website itself. If anyone of you finds the script useful, then great. If not, well, you probably are not annoyed by these issues, so that's also great!

Have fun, and keep on CodeWarrioring!

**Comment by kazk** [comment]
Closing because this is not an issue.

Also, can you not provide easy access to site events? It's not made to be accessed by average user or opened frequently and [it's a performance hog](https://github.com/Codewars/codewars.com/issues/113#issuecomment-118150572) according to Jake.

**Comment by hobovsky** [comment]
> Closing because this is not an issue.

Well, I hoped you would at least mark the thread as feature suggestion(s)  ;)

> Also, can you not provide easy access to site events? It's not made to be accessed by average user or opened frequently and [it's a performance hog](https://github.com/Codewars/codewars.com/issues/113#issuecomment-118150572) according to Jake.

Sure thing, I did not realize that in full extent because, quite frankly, site events page was the thing I've learned on my very first day when joined CW and I thought it's some of a *really* common CW knowledge. Would not it be better just to remove it completely, then?
Would you want me to remove the feature no. 4 too (resolution of site event IDs into links), or can it stay for people who already know? Please mind that resolved links are *persisted* by the script so it would not grind through DB too much, but you're the boss, so I remove it if you request so!

Cheers!

**Comment by kazk** [comment]
> Well, I hoped you would at least mark the thread as feature suggestion(s) ;)

If you want to request features not already done, then please fill out the issue template provided for each so it can be tracked independently. I don't think 3 and 4 will happen though.

> Sure thing, I did not realize that in full extent because, quite frankly, site events page was the thing I've learned on my very first day when joined CW and I thought it's some of a really common CW knowledge.

I'm sure there's users who doesn't know about it, installs your script because they want filtering by language, then finds "Site events" link. I don't have the time to review the script and I have no idea how popular this script is or will be.
Just opening `/site-events` does many database queries because it's not optimized. I can remove it or optimize it, but it's extra work with low priority.

> Would you want me to remove the feature no. 4 too (resolution of site event IDs into links), or can it stay for people who already know? Please mind that resolved links are persisted by the script so it would not grind through DB too much, but you're the boss, so I remove it if you request so!

I don't really care at this point. I'll do something if it's clearly affecting performance.

**Comment by hobovsky** [comment]
Okay, so I removed all functionalities related to site events. We can live without it, I think.

Regards!

**Comment by HanaBenami** [comment]
Hi, Should it works? 
Looks like it has no effect ....

**Comment by hobovsky** [comment]
It works for me, but I might miss something... Catch me on Codewars Discord, and we will try to see what's your problem.

**Comment by kazk** [comment]
@hobovsky Do you want to post a current version on https://github.com/codewars/codewars.com/discussions/categories/show-and-tell?

**Comment by hobovsky** [comment]
Well, I hoped to gradually remove features from the script as they get added to  Codewars itself :) but sure, I will put something there.

**Comment by hobovsky** [comment]
Posted here: https://github.com/codewars/codewars.com/discussions/2377
