### ISSUE TITLE
Adding prototype methods doesn't work in CoffeeScript

### ISSUE THREAD

**Issue by piorad** [Codewars/codewars.com#176]
I'm attempting to translate a kata into CoffeeScript. The way I want to do it requires that I add a method to the Date class. I can't seem to get it to work, but the CS code copy/pasted into the interpreter on coffeescript.org works fine.

```
Date::custom_function = ->
  console.log 'custom_function'

d = new Date(2015, 7, 15)
d.custom_function()
```

gives an error

```
TypeError: Object Sat Aug 15 2015 00:00:00 GMT+0000 has no method 'custom_function' at .:18:5 at .:30:3 
```

The problem also happens if I do `Date.prototype.custom_function = ->` instead of the :: notation.

**Comment by kazk** [comment]
Closing this because it seems to be fixed.

![image](https://cloud.githubusercontent.com/assets/639336/24484463/3424c554-14b3-11e7-8696-634de6ec9983.png)

**Comment by brendanvos** [comment]
@kazk Looks like you forgot to close

**Comment by kazk** [comment]
Thanks :)
