### ISSUE TITLE
"Waiting for issues to be resolved" while all issues are resolved

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1760]
#### Describe the bug

https://www.codewars.com/kata/list-concatenation-is-injective-prove-it/

Look at the discourse. The only issue was resolved, while the status says "Waiting for issues to be resolved".

#### To Reproduce

Look.

#### Expected Behavior

Display "Tesing & feedbacks needed" or "Awaiting moderator approval".

#### Screenshots

![2019-03-12 07-04-12 的屏幕截图](https://user-images.githubusercontent.com/16398479/54195480-26021f80-4495-11e9-8bc1-9f450c475559.png)

**Comment by kazk** [comment]
Transferred because this is Codewars issue and closing as duplicate of #1088. Looks like you can force refresh by removing your vote and voting again.
