### ISSUE TITLE
Cannot see author of my Kata

### ISSUE THREAD

**Issue by ice1000** [Codewars/codewars.com#1761]
#### Describe the bug

Kata author name disappear

#### To Reproduce

Open https://www.codewars.com/kata/my-languages with account ice1000

#### Expected Behavior

See my name

#### Screenshots

![image](https://user-images.githubusercontent.com/16398479/54245362-ec69fc80-4506-11e9-8ab2-af8702039fbe.png)

**Comment by kazk** [comment]
Closing as duplicate of #443
