### ISSUE TITLE
Add an input method for Unicode / LaTeX characters in code editor

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1762]
#### Is your feature request related to a problem? Please describe.

With the recent addition of Agda, we're getting more needs to enter Unicode characters as part of the code, not just string literals in other languages (which often can be entered as escape sequences instead). Certain symbols (e.g. `≡` for equality proofs) must be copy-pasted many times while coding, which is uncomfortable at least. If we can enter LaTeX characters easily, it might help commenting the solutions for math-oriented katas too.

#### Describe the solution you'd like / alternatives you've considered

There are several alternatives:

* Emacs editor mode.
  * Reason to do so: Several online coding sites (e.g. Hackerrank) support Vim / Emacs mode already, and Emacs is also a common editor of choice for Agda.
  * Reason not to do so: IIRC you need a plugin for Agda support in Emacs, which may be hard to integrate with online Emacs editor.
* Support for LaTeX symbols only.
  * There can be several possible ways to implement this
    * e.g. backslash + symbol name + space/tab -> convert to the corresponding symbol. (The space/tab is the trigger)
  * Reason to do so: It should be less heavy to implement than full Emacs mode.
  * Reason not to do so: It may interfere with other usages of backslash, e.g. escape sequences or Haskell's lambda. To solve this, we need a toggle option visible in the editor.
* Other options?
  * Probably something similar to the [language bar for golfing languages](https://abrudz.github.io/lb/)? Notably, Brachylog one has several common Agda symbols including `≡`, `⊥` (bottom or Empty), `ℕ` (Nat), `ℤ` (Int), `⟨⟩` (proof notations), `ˡ` and `ʳ` (superscript for left/right parts respectively), but no `→`. And the input shortcuts don't work in code editor, so we need a CW-internal method for that.

**Comment by kazk** [comment]
I'd like to have Agda mode for CodeMirror that does proper highlighting and allows inputting similar to the official agda-mode. Maybe we can build the input on top of https://github.com/ejgallego/CodeMirror-TeX-input

This can be another open source project.

**Comment by Bubbler-4** [comment]
Probably we can start working from [Haskell highlighter](https://github.com/codemirror/CodeMirror/blob/master/mode/haskell/haskell.js), since Agda and Haskell share many syntax elements (comments, string literal, pragmas)...

... just that the Haskell one itself needs several improvements (especially char literals).

**Comment by Bubbler-4** [comment]
Quickly wrote an [Agda highlighter for CodeMirror](https://hackmd.io/mqkbr2DXQ6-rxz9CKo5rLg), but didn't test it. Didn't bother to highlight plain names since virtually everything in Agda (except keywords) is a plain name, and almost every "built-in" requires at least an import.

**Comment by kazk** [comment]
Looks decent

![image](https://user-images.githubusercontent.com/639336/54259602-92c3fb00-4523-11e9-8aa1-de15e3ff5bbf.png)

You can open this HTML and tweak it if you want. Just a minimal version of their demo page.
```html
<!doctype html>
<head>
<title>CodeMirror: Agda mode</title>
<meta charset="utf-8"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.44.0/codemirror.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.44.0/theme/base16-dark.min.css">
<style>.CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}</style>
</head>

<body>
<article>

<h2>Agda mode</h2>
<form>
<textarea id="code" name="code">
{-# OPTIONS --safe #-}
module Example where
open import Agda.Builtin.Equality

_⇆_ : {A : Set} {a b c : A} → a ≡ b → b ≡ c → a ≡ c
refl ⇆ refl = refl
</textarea>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.44.0/codemirror.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.44.0/addon/mode/simple.min.js"></script>
<script>
let floatRegex =
  /-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?(?=[.;{}()@"\s]|$)/u
let integerRegex = /-?(?:0|[1-9]\d*|0x[0-9A-Fa-f]+)(?=[.;{}()@"\s]|$)/u

let keywordsRegex = new RegExp(
  "(?:[_=|→:?\\\\λ∀]|\\.{2,3}|abstract|codata|coinductive|constructor|" +
  "data|do|eta-equality|field|forall|hiding|import|in|inductive|" +
  "infix|infixl|infixr|instance|let|macro|module|mutual|no-eta-equality|" +
  "open|overlap|pattern|postulate|primitive|private|public|quote|" +
  "quoteContext|quoteGoal|quoteTerm|record|renaming|rewrite|" +
  "syntax|tactic|unquote|unquoteDecl|unquoteDef|using|where|with|" +
  "Set(?:\\d+|[₀₁₂₃₄₅₆₇₈₉]+)?)(?=[.;{}()@\"\\s])", 'u'
)

let escapeDec = "0|[1-9]\\d*"
let escapeHex = "x(?:0|[1-9A-Fa-f][0-9A-Fa-f]*)"
let escapeCode =
  "[abtnvf&\\\\'\"]|NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|" +
  "SO|SI|DLE|DC[1-4]|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL"
let escapeChar = new RegExp(
  '\\\\(?:' + escapeDec + '|' + escapeHex + '|' + escapeCode + ')', 'u'
)

let startState = [
  // comments, pragmas, holes
  {regex: /\{-#.*?#-\}/u, token: "meta"},
  {regex: /\{-/u, token: "comment", push: "comment"},
  {regex: /\{!/u, token: "keyword", push: "hole"},
  {regex: /--.*/u, token: "comment"},
  
  // literals
  {regex: floatRegex, token: "number"},
  {regex: integerRegex, token: "integer"},
  {regex: /'/u, token: "string", push: "charLit"},
  {regex: /"/u, token: "string", push: "strLit"},
  
  // keywords & qualified names
  {regex: keywordsRegex, token: "keyword"},
  {regex: /[^\s.;{}()@"]+\./u, token: "qualifier"},
  {regex: /[^\s.;{}()@"]+/u, token: null}
]

let commentState = [
  {regex: /\{-/u, token: "comment", push: "comment"},
  {regex: /-\}/u, token: "comment", pop: true},
  {regex: /./u, token: "comment"}
]

let holeState = [
  {regex: /\{!/u, token: "keyword", push: "hole"},
  {regex: /!\}/u, token: "keyword", pop: true},
  {regex: /./u, token: "comment"}
]

let charLitState = [
  {regex: /'/u, token: "string error", pop: true},
  {regex: /[^'\\]/u, token: "string", next: "charLitEnd"},
  {regex: escapeChar, token: "string", next: "charLitEnd"},
  {regex: /.*?'/, token: "string error", pop: true}
]

let charLitEndState = [
  {regex: /'/u, token: "string", pop: true},
  {regex: /./u, token: "string error"},
  {regex: /[^]/u, token: "string error", pop: true}
]

let stringState = [
  {regex: /"/u, token: "string", pop: true},
  {regex: /[^"\\]/u, token: "string"},
  {regex: escapeChar, token: "string"}
]

CodeMirror.defineSimpleMode("agda", {
  start: startState,
  comment: commentState,
  hole: holeState,
  charLit: charLitState,
  charLitEnd: charLitEndState,
  strLit: stringState
});
CodeMirror.defineMIME("text/x-agda", "agda");
</script>

<script>
  const editor = CodeMirror.fromTextArea(document.getElementById("code"), {
    mode: "agda",
    lineNumbers: true,
    matchBrackets: true,
    theme: "base16-dark"
  });
</script>

<p><strong>MIME types defined:</strong> <code>text/x-agda</code>.</p>
</article>
</body>
```

**Comment by Bubbler-4** [comment]
Fixed some small bugs (missing keyword `->`, slightly refined string/char literal errors). Looks like it works as I intended. Updated the code in the [HackMD document](https://hackmd.io/mqkbr2DXQ6-rxz9CKo5rLg).

**Comment by kazk** [comment]
I've been playing with Agda input.

![agda-input2](https://user-images.githubusercontent.com/639336/54261857-0d901480-452a-11e9-942e-8913fadd961d.gif)

Modified CodeMirror-TeX-input and using translation from `agda-input.el`. I _think_ I found a way to only enable this in certain modes so it shouldn't affect other languages.

**Comment by Bubbler-4** [comment]
@kazk Btw, which range of characters are you planning to support? I guess it should be at least [these common characters](https://agda.readthedocs.io/en/latest/tools/emacs-mode.html#show-me-some-commonly-used-characters) plus `ℤ` (I'd be happy to have more math symbols though).

**Comment by kazk** [comment]
I haven't decided yet. Yeah, I'd like to support commonly used ones at least. I guess we can start from those and some extra. Supporting all of [agda-input.el](https://github.com/agda/agda/blob/6f3046e081ebfa40793c3a064e53bdbd83c82dcf/src/data/emacs-mode/agda-input.el#L191-L1058) will be too much. ~20KB of extra JS just for the translation table.

I'm planning to create a new repository for this soon.

**Comment by Bubbler-4** [comment]
Looking at the file, I'm guessing some TeX sequences (such as `\top`, `\bot`, `\eta` and `\pi`) come from somewhere else. Do you know where they are?

**Comment by kazk** [comment]
I created https://github.com/Codewars/codemirror-agda with initial version.

I've included JS version of translation map from `agda-input.el` in [src/translations.js](https://github.com/Codewars/codemirror-agda/blob/master/src/translations.js) and it's mostly commented out. You can uncomment commonly used ones that I missed and add some from TeX input.

There's also a bug that I couldn't figure out. Some of the characters are not recognized in completion. `\(` won't work for example.

I tried creating [a demo page](https://codewars.github.io/codemirror-agda/) using GitHub pages, but it's failing to load the script :( I guess only `docs/` is deployed so loading `../dist/agda.js` is not possible.

For now, you can clone the repository, run `python -m http.server 8080` then open `localhost:8080/docs` to see it.

**Comment by Bubbler-4** [comment]
[Here's an edit to the full JS file for the demo page.](https://hackmd.io/mqkbr2DXQ6-rxz9CKo5rLg#Code)

List of changes:

* Tried to make the non-working keys work. The changes are inside `CodeMirror.defineInitHook`, not `createHint`.
  * Added key bindings for non-working keys to `addKeyMap`
  * Set `completeSingle` option to `false` (if true, conversion is applied right away if there's only one option, which was a bit surprising to me, and I think it didn't happen before adding other key bindings)
* `toTable`: Sorted the key bindings, so the relevant key bindings come first.
* `translations`
  * Added a binding for `\neg -> ¬` and a few Greek symbols (`\eta` `\pi` `\Pi`)
  * Commented out long lists of symbols e.g. equality symbols, arrows and parentheses.
  * Uncommented blackboard bold letters for `CHNPQRZ` which represent well-defined number sets, and all sub/superscripts. Also uncommented `\qed`.

**Comment by kazk** [comment]
Can you open a PR?

**Comment by kazk** [comment]
I think `addKeyMap` will be global and mess with other modes, but I'm not sure.

**Comment by Bubbler-4** [comment]
PR submitted. For the `addKeyMap` problem, can we do something like this on CW?

```js
if (the selected language is Agda) {
  CodeMirror.defineInitHook(...);
}
```

**Comment by kazk** [comment]
Thanks, I'll take a look at it later.

No, because we don't know the mode until much later. I think we can add key maps when the mode is set to `agda` and remove them if the mode changes, but I need to look into how CodeMirror works.

**Comment by kazk** [comment]
I was able to make it work without adding key map for those extra characters. I've also updated the demo page so we can switch between Haskell mode and make sure the completion only happens in Agda mode.

![image](https://user-images.githubusercontent.com/639336/54470155-79f45900-4760-11e9-9ae6-a8b0ace79d3b.png)

**Comment by kazk** [comment]
Finally got it working on staging.
![agda-input-staging](https://user-images.githubusercontent.com/639336/54473314-2fd89b00-4793-11e9-87bc-00356bc4b1fc.gif)

I had to update the packages that Codewars was using for managing assets because it was too old and crashed on arrow functions :roll_eyes:

I'll deploy to preview/production sometime over the weekend and close this when I do.

**Comment by kazk** [comment]
Deployed
