### ISSUE TITLE
Searching 1&2 kyu katas in C throws HTTP500

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [Codewars/codewars.com#1763]
#### Describe the bug
The url: https://www.codewars.com/kata/search/c?q=&r%5B%5D=-2&r%5B%5D=-1&beta=false
That was supposed to show katas in C with 1 and 2 kyu (approved). But it's tossing 500 Internal Server Error.

#### To Reproduce

1. Go to Kata.
2. Mark 1&2 kyu.
3. Select C language.
4. HTTP500 happens.

#### Expected Behavior

1&2 kyu challenges for C.

#### Screenshots

![obraz](https://user-images.githubusercontent.com/27734421/54361867-374f5580-4668-11e9-97e9-f92502b46bfc.png)

#### Contexts

- Codewars username: Not important
- OS: Not important
- Browser: Not important
- Browser Version: Not important

**Comment by kazk** [comment]
Fixed
