### ISSUE TITLE
Got only 2 honor points for completing 4kyu kata

### ISSUE THREAD

**Issue by alexmaksimchuk** [Codewars/codewars.com#1764]
Hi!

I completed the 'Next bigger number with the same digits' 4kyu kata a couple of days ago and only got 2 honor points for awarded (instead of 32). Kata is marked as 'completed' in my account, but shows up at the 'site-event' page as a White kata instead of Blue.

#### Screenshots

![InkedScreenshot_2019-03-14 alexmaksimchuk Codewars_LI](https://user-images.githubusercontent.com/47334285/54379212-038d2380-469a-11e9-84c8-cff075fb76c8.jpg)
![Screenshot_2019-03-14 Codewars](https://user-images.githubusercontent.com/47334285/54379262-1e5f9800-469a-11e9-9b44-73065c1723c9.png)

#### Contexts

- Codewars username: alexmaksimchuk [https://www.codewars.com/users/alexmaksimchuk] (linked with GitHub account)
- OS: Windows 10
- Browser: firefox
- Browser Version: 65.0.2

Can you please look into this situation?

Thank you in advance.

Best regards,
alexmaksimchuk

**Comment by kazk** [comment]
I've fixed your data

**Comment by alexmaksimchuk** [comment]
> 
> 
> I've fixed your data

Thank you
