### ISSUE TITLE
Unknown Server Error

### ISSUE THREAD

**Issue by ScottWorks** [Codewars/codewars.com#1765]
#### Describe the bug
Today I have not been able to login, I keep recieving `Unknown Server Error` instead of the webpage. 

#### To Reproduce

1. Go to 'codewars.com'
2. Click on 'Login'
3. Text displays `Unknown Server Error`

Any help would be appreciated, thanks.

**Comment by kazk** [comment]
What's your username?

**Comment by ScottWorks** [comment]
@kazk thanks for responding, it is scottworks

**Comment by kazk** [comment]
Can you try again? There was an issue with one kata we just fixed that was crashing pages for some users. You have that kata bookmarked so maybe that was causing it.

**Comment by ScottWorks** [comment]
It's working, thank you!

**Comment by kazk** [comment]
Great, thanks for confirming :)

**Comment by hilzmax** [comment]
I also get "Unknown Server Error".
My codewars username is "txtsxm".
Please help.

**Comment by kazk** [comment]
@hilzmax Please open a new issue with more information.
