### ISSUE TITLE
Kata search broken

### ISSUE THREAD

**Issue by JomoPipi** [Codewars/codewars.com#1766]
If you search 1 kyu kata in agda, you only find one of them (List concatenation is injective? Prove it!)

But if you search for all 1 kyu kata, you can see that 2 of them are in adga.

![cwissue2](https://user-images.githubusercontent.com/39433859/54472394-2ea07180-4785-11e9-9d23-987b1a29f165.JPG)

![cwissue](https://user-images.githubusercontent.com/39433859/54472386-04e74a80-4785-11e9-8f3c-32d86ff1e5a6.JPG)

**Comment by kazk** [comment]
Maybe the search index was outdated. This seems to work now. Please let me know if this happens again.
