### ISSUE TITLE
New kata locked?

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#177]
I wrote a new kata:<http://www.codewars.com/kata/55e6a979c09039f09a00008c> I cannot publish a translation, I can't delete it or unpublished it. Everything is locked. Help, please!

**Comment by GiacomoSorbi** [comment]
It happened to me too. A lot.

Translations "lost" because you thought were saved, among other things...

If this can help Jake and the others to debug, when I press the save or publish button the CW logo rotates for only a brief moment before stopping altogether.

**Comment by g964** [comment]
@GiacomoSorbi
I had a bad week!
First unable to change a kata by re-editing it, then unable to delete it.
Second: unable to translate one of my kata in several languages with the "+" button, at last I edited it but lost all honor I could have had by translating... not important but irritating.
Third: in a translation of one of my kata in CS, lots of errors with 'errors: expected "bla bla" got: the exact same blabla' !
In the same kata I wanted to publish the Clojure version; I could save and validate but when I push 'publish', nothing happens, the 'publish' button got transparent and nothing else but translation lost anew...

**Comment by jhoffner** [comment]
This is related to #178 and the fix has been verified for translations. Are you having issues creating a new kata as well?

**Comment by g964** [comment]
I can't say if I can create new kata since then because I have not tried yet. But I can say that I can't delete kata:
<http://www.codewars.com/kata/55e6a979c09039f09a00008c>
which is now completely obsolete; I replaced it with a new one.
