### ISSUE TITLE
500 on Kata-Filter page

### ISSUE THREAD

**Issue by Vittel** [Codewars/codewars.com#1770]
#### Describe the bug
![image](https://user-images.githubusercontent.com/1927076/54489680-1b89c080-48af-11e9-8476-5dc39744a9a0.png)

#### To Reproduce

~~1. Go to '...'~~
![image](https://user-images.githubusercontent.com/1927076/54489709-57248a80-48af-11e9-9c35-838d1672bc5e.png)
~~3. Scroll down to '....'~~

Earlier i was on that page without an arror. 
I was opening 18 katas at a time and then closing the filter-view.
After solving all 18 Katas i came back and got this error.

#### Expected Behavior

no error.

#### Screenshots

see above.

#### Contexts

Please complete the following information:

- Codewars username: seidchr
- OS: win 10
- Browser: chrome
- Browser Version: 72.0.3626.121 (Offizieller Build) (64-Bit)

**Comment by kazk** [comment]
Can you refresh and see if that helps?
If not, can you open https://www.codewars.com/kata/my-languages on another tab?

Also, what do you have selected for filters?

**Comment by m-karcz** [comment]
I have same error, it prompts before selecting any filter(just clicking "Kata").

**Comment by kazk** [comment]
I can't reproduce, but I've just released a possible fix.

@Vittel @m-karcz can you try again?

**Comment by m-karcz** [comment]
@kazk it works right now

**Comment by kazk** [comment]
Cool, thanks for confirming. I optimized this last night and I guess I excluded some attributes accidentally. It's odd that I didn't get this error while testing but I'm glad it's fixed.

**Comment by Vittel** [comment]
Not bad !
It was working again yesterday. I really like such pretty much instant fixes 😁
Even though i would say you shouldn't work so much on the weekends 😉
