### ISSUE TITLE
Sort by hardest not works

### ISSUE THREAD

**Issue by luochen1990** [Codewars/codewars.com#1773]
#### Describe the bug

Sort by hardest not works, and I find that the URL arguments looks like `order_by=rank_id+desc`, which seems not correct.

#### To Reproduce

1. Go to 'https://www.codewars.com/kata/search/my-languages?q=&beta=false&order_by=rank_id+desc'
2. See error

#### Expected Behavior

1kyu are sorted before 4kyu.

#### Screenshots

![image](https://user-images.githubusercontent.com/2309868/54604434-ade1be00-4a81-11e9-8965-63894f22c936.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): luochen1990
- OS: Win 10
- Browser: Chrome
- Browser Version: 72.0.3626.121 (64bit)

**Comment by ZEDCWT** [comment]
It seems that the some part of the searching system is not working properly for some reason
This is what i got for accessing https://www.codewars.com/kata
![A](https://user-images.githubusercontent.com/7867810/54614762-ea201900-4a97-11e9-8863-281fb95fd7ef.png)
And let's scroll down a little bit
![B](https://user-images.githubusercontent.com/7867810/54614806-f906cb80-4a97-11e9-8a8b-912652a5db97.png)
You can see there are few newly added beta katas

But lets ask for https://www.codewars.com/kata?xids=completed&beta=true
![C](https://user-images.githubusercontent.com/7867810/54614911-28b5d380-4a98-11e9-9434-d76c8bd6b2fc.png)

Umm.. nope, these betas are too old.
So it seems that the indexing is not updating correctly or some other bugs that i cannot imagine triggered...

**Comment by kazk** [comment]
For the original issue of the rank out of order, the data on Elasticsearch may be outdated. Looks like some of the kata used to be ranked higher.

I'll try reindexing and look into the other issue. I did optimize this recently and I'm pretty sure I didn't change the search rules, but I might have caused something.

**Comment by kazk** [comment]
I found a bug that was introduced by the optimization. The order within a page was not kept. I'll deploy the fix today.

I'm not sure if this will fix the issue of the beta kata.

**Comment by kazk** [comment]
Deployed the fix. It also fixed the issue @ZEDCWT found as well.
