### ISSUE TITLE
Flash success for updated profile displayed again after being closed (on the forum view)

### ISSUE THREAD

**Issue by Lodi2244** [codewars/codewars.com#1774]
#### Describe the bug
Not a bug per se just a front glitch. After editing my profile infos and clicking update I get a flash "You updated your account successfully" I close it and click the link to forum in the sidebar and the flash pop's again on the forum page

#### To Reproduce

1. Go to 'Account Settings'
2. Click on 'Update'
3. Close the flash success tab
4. Click 'Forum'
5. See error

#### Expected Behavior

The flash shouldn't pop again on an other view

#### Contexts

Please complete the following information:

- Codewars username (if account related): Lodi2244
- OS: MacOs 10.12.6
- Browser: Safari & Chrome (tested in both)
- Browser Version: Safari 12.0.3 - Chrome 72.0.3626.121

**Comment by kazk** [comment]
Fixed
