### ISSUE TITLE
Syntax highlighting in string interpolation

### ISSUE THREAD

**Issue by xavierguihot** [Codewars/codewars.com#1775]
At least in my languages (Scala, Python), `string interpolation` is highlighted as a simple string which makes the reading of some solutions of the "solutions" page quite difficult.

And yet `string interpolation` is usually considered the preferred way of building a `String` nowadays in these languages. 

By `string interpolation`, I mean this kind of things (here in Scala):

```scala
val hello = "Hello"
val world = "World"
s"$hello $world!"
```

**Comment by kazk** [comment]
We're using highlight.js for syntax highlighting the solutions. There's not much we can do.

Is it highlighted correctly in the editor? I'm considering to replace highghlight.js with CodeMirror so we have consistent look so that might help.

**Comment by xavierguihot** [comment]
It's correctly highlighted in the editor for Python, but not for Scala.

**Comment by kazk** [comment]
If it's not highlighted on their [demo page](https://codemirror.net/mode/clike/scala.html) either, then there's nothing we can do.

You can let them know by opening an issue on [their repository](https://github.com/codemirror/CodeMirror) or open a PR fixing it. If it gets fixed upstream, I'll update the version we're using it.

**Comment by xavierguihot** [comment]
Ok, I'll open an issue on their repository, thanks.

**Comment by kazk** [comment]
Closing as I've opened #1778 to track replacing highlight.js with CodeMirror.
