### ISSUE TITLE
Solução invalida aceita

### ISSUE THREAD

**Issue by paulosfjunior** [Codewars/codewars.com#1776]
Quando colocado a solução abaixo em javascript o codigo aceita, mesmo não estando correto.

console.log("<PASSED::>");
return;

**Comment by paulosfjunior** [comment]
Em um dos que eu respondi vi esta resposta, testei em um outro kata e ele passou, porem quando testei não sabia que ele ja gravava, registrou como concluido pra mim com essa solução mas eu estava apenas testando para abrir o ISSUE

**Comment by paulosfjunior** [comment]
O Codigo abaixo tambem passa como valido sendo que não esta valido.

const solution = Test.expect(true);
process.reallyExit();;

**Comment by hobovsky** [comment]
#1615. I wonder how many tests you need to do to get yourself banned :)

**Comment by paulosfjunior** [comment]
Eu não sabia que passava, quando testei o code achei que ele validava antes de enviar o codigo.
Quando coloquei pra validar o codewars ja marcou como kata realizado, não tinha me atentado que ele faz isso antes de eu colocar 'submit'... o segundo eu vi mas nao testei...
