### ISSUE TITLE
Clicking "Publish" when translating a kata doesn't seem to do anything

### ISSUE THREAD

**Issue by MarkPearl** [Codewars/codewars.com#178]
Hi, this is the first time I have done a kata translation so I hope I am not missing something obvious.

I did the C# translation for the [repeatit kata](http://www.codewars.com/kata/557af9418895e44de7000053) however when I click publish, I get a response that the kata is being saved, but cannot tell from there what the next steps are or if it is actually being published.

Going to my profile page under the Kata Translations section it doesn't list the kata (I've checked all three sections, Published, Closed & Draft).

Have I missed something in this process, or how do I tell what the status of this translation is?

**Comment by em-12** [comment]
I've also had this problem, trying to translate the [GPS Navigation](http://www.codewars.com/kata/5244ab738978478c1800002e) kata into Python. It's also the first time I've either authored or translated anything.

I've tried on Firefox and Chrome, neither work.

**Comment by jhoffner** [comment]
The fix for this has been verified.
