### ISSUE TITLE
average satisfaction rate is acting weird

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1785]
Hi,

I just got a new completion on my [FMC2](https://www.codewars.com/kata/full-metal-chemist-number-2-parse-me-dot-dot-dot/) beta kata and... encountering a weird calculation of the satisfaction rate:

![image](https://user-images.githubusercontent.com/32236948/55176979-7d390d00-5182-11e9-9462-62100667e8e4.png)

On the 5 "very satisfied", 3 are from valid users, the two last must be from the different accounts of the cheater of the last few days, I guess (tho, they appeared only recently, not just after they cheated it, so... not sure). So it seems that the votes of the cheaters are showing up in the stats but aren't actually used for the calculations:

`100*3/4 = 75%` -> there it's consistent.

# Suggestion:

remove the related votes from the counts too

(... or count them in the average, so that the kata can go out of beta... The not satisfied vote is from Voile, in his most passive-aggressive move, using his alter account... not really a valid vote, so... x) )

**Comment by kazk** [comment]
The number of votes shown was outdated. It's now
![image](https://user-images.githubusercontent.com/639336/55180906-c5870980-5147-11e9-9efe-5f5368dd8a77.png)
