### ISSUE TITLE
"Sing up" button covered `#monitor` block

### ISSUE THREAD

**Issue by dean992008** [Codewars/codewars.com#1786]
#### Describe the bug
Not possible press "sign up" on Homepage

#### To Reproduce

1. Move mouse to "sing up" button and try press 

#### Expected Behavior

Button "sing up" possible press.

#### Screenshots

![d6a9a3644d](https://user-images.githubusercontent.com/11517379/55235336-fe051100-5235-11e9-9b86-ef34853d3138.jpg)

Please complete the following information:

- Browser: Google Chrome
- Browser Version:  73.0.3683.86

**Comment by FArekkusu** [comment]
Fixed values are used for calculating the element width, and position for some reason. If you zoom in, you should be able to press it at least.

**Comment by kazk** [comment]
Fixed
