### ISSUE TITLE
create a "comprehensive list of kata to retire" accessible through the wiki

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1787]
hi,

we already have something about troubles with the runner, duplicates, ... But that one is really lacking, imo. We could list there the katas that are beyond hope of restoration and/or are without any interest. That would be a starting point for the day we'll be able to purge the data base.

cheers

Note: close to the topic: https://github.com/Codewars/codewars.com/issues/940 The katas discussed there could be in that list.

**Comment by Blind4Basics** [comment]
mmm... Maybe that would be too close to the list of duplicates? thing is: some of them aren't duplicates. Maybe just change a bit the name of the list of duplicates, rather?

**Comment by kazk** [comment]
If you want to maintain a separate list, you can [create a page](https://github.com/Codewars/codewars.com/wiki/_new) and [add it to the sidebar](https://github.com/Codewars/codewars.com/wiki/_Sidebar/_edit).

**Comment by Blind4Basics** [comment]
:+1:
