### ISSUE TITLE
Cant choose language for certain kata

### ISSUE THREAD

**Issue by antonkolosok** [Codewars/codewars.com#1788]
#### Describe the bug
Cant choose language for kata "Decode the Morse code, for real"
https://www.codewars.com/kata/decode-the-morse-code-for-real/train/java

#### To Reproduce

1. Go to kata https://www.codewars.com/kata/decode-the-morse-code-for-real/train/java
2. Select language from dropdown menu
3. Observe the bug

#### Expected Behavior

Select chosen language

#### Contexts

- Anton Kolosok
- OS: Win 10
- Browser: chrome
- Browser Version: 73.0.3683.86

**Comment by hobovsky** [comment]
I can confirm this strange behavior, on kata details page when I select any language it always reverts back to Python, and in trainer no language is selected, and all editors are empty.

**Comment by kazk** [comment]
Thanks for reporting. This kata had some data corrupted few weeks ago causing the page to crash. Maybe something similar is happening again.

**Comment by kazk** [comment]
Looks like https://www.codewars.com/kata/who-is-going-to-pay-for-the-wall/ has the same issue.
Both kata had comments removed recently because of spamming and corrupted data.

**Comment by cnramey** [comment]
> 
> 
> Looks like https://www.codewars.com/kata/who-is-going-to-pay-for-the-wall/ has the same issue.
> Both kata had comments removed recently because of spamming and corrupted data.

Can confirm this problem with https://www.codewars.com/kata/who-is-going-to-pay-for-the-wall/ , when I attempt to select JavaScript as a language it resets it back to Ruby.

**Comment by dagolinuxoid** [comment]
Soon it will be the only remaining approved kata from 8kyu that I didn't solve (because of the issue).

**Comment by Chrono79** [comment]
I republished https://www.codewars.com/kata/who-is-going-to-pay-for-the-wall/ and it seems #1801 was born in the process?

**Comment by kazk** [comment]
@Chrono79 it's not your fault. Codewars is just broken :( Can you tell me what you changed? Revisions page doesn't show anything useful.

**Comment by Chrono79** [comment]
That's the weird part, at first I didn't change anything, only republished (to see if that could make the kata work again). After I discovered the kata wasn't working, I've added some text to the kata description stating the kata wasn't working anymore.

**Comment by kazk** [comment]
Fixed
