### ISSUE TITLE
Something broken in Coffeescript

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#179]
A result among a lot of others:

```
Testing :
It should work with random inputs - Expected: [[6601,13398],[7574,12873]], instead got: [[6601,13398],[7574,12873]]
```

**Comment by g964** [comment]
Now this kata

<http://www.codewars.com/kata/55e86e212fce2aae75000060>

works with the Clojure translation but not with the Coffeescript one.
Example among lots of others:
Random tests
Testing :
It should work with random inputs - Expected: [[2482,18964],[8306,17228]], instead got: [[2482,18964],[8306,17228]].

I suppressed the random tests and without them it worked.

**Comment by g964** [comment]
I must had that I got no "honor" with that Coffeescript translation...

**Comment by bkaestner** [comment]
> I suppressed the random tests and without them it worked.

Could you add the random tests here? This sounds like you've used `assertEquals` instead of `assertSimilar`, to be honest.

**Comment by g964** [comment]
Yes now I know. Twice I forgot to use assertSimilar:-( my bad!


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
