### ISSUE TITLE
corrupted data again? (FMC2)

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1791]
Hi kazk,

I believe there might be a DB trouble behind this:

* kata: [Full Metal Chemist #2: parse me...](https://www.codewars.com/kata/5a529cced8e145207e000010)
* in the [lists](https://www.codewars.com/kata/search/?q=metal+chemist&r%5B%5D=-1), I see this message below it: "Status:Waiting for issues to be resolved"
* tho, there isn't any issue opened (or even suggestion) in the [discourse](https://www.codewars.com/kata/full-metal-chemist-number-2-parse-me-dot-dot-dot/discuss/).

Since some comments of the last cheater/hater where removed from the discourse (possibly posted as an issue, I'm not sure anymore), I suspect there might be a problem lying under. 
Could you check, please?

thx,
B4B

**Comment by Blind4Basics** [comment]
(note: if so, that means the other betas where he posted will surely suffer of the same problem)

(I cannot edit my previous message, from the place where I'm posting...)

**Comment by kazk** [comment]
Full Metal Chemist 2 is fixed. Maybe removing a comment didn't trigger updating the status.
I might just run a script to update all betas.

**Comment by kazk** [comment]
Updated the state of all beta kata just in case.

**Comment by Blind4Basics** [comment]
Thank you! :)

**Comment by Voileexperiments** [comment]
> Maybe removing a comment didn't trigger updating the status.

Yes it has always been the case. It turns out that I haven't raised an issue about this particular behaviour yet because similar ones exists, like #1088 and #1470.
