### ISSUE TITLE
Clojure kumite try to use "Codewars" test framework

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#1792]
Clojure kumite sometimes have Codewars framework selected instead of Clojure Test.
It happens in kumite when Clojure is the initially selected language (the last used language or created from https://www.codewars.com/kumite/new?language=clojure). It doesn't happen if a different language is initially selected and then switched to Clojure.

When it happens, Clojure Test is in the dropdown, but nothing happens when it's selected.
Kumite example: https://www.codewars.com/kumite/5cacb923d7f22c00229765f7 (publishing is unavailable).
![image](https://user-images.githubusercontent.com/5375100/55816323-8f4f6f80-5ae1-11e9-99da-05715a9c43a5.png)
at the same time:
![image](https://user-images.githubusercontent.com/5375100/55816355-9f674f00-5ae1-11e9-8f7c-26b319c47f00.png)

**Comment by error256** [comment]
https://www.codewars.com/assets/bundles/code_snippets-2de09186e9bff4df90a63b3612efd3e3226e3c17a4f7f2fc4ddabcf045d68f05.js
Somewhere in `setTestFramework`:
```javascript
let t=$(`dd[data-framework=${e}]`);
```
If quotes are added around `${e}`, everything works.

**Comment by kazk** [comment]
Thanks! The test framework identifier for Clojure contains a period (`clojure.test`) so finding an element fails and falls back to the first test framework found.

**Comment by kazk** [comment]
Fixed
