### ISSUE TITLE
Adding Metaprogramming as an topic in Katas

### ISSUE THREAD

**Issue by Ankit-rana** [Codewars/codewars.com#1795]
#### Is your feature request related to a problem? Please describe.
I always start with 8kyu and 7kyu on codewars whenever i want to learn new topics in a language. Recently i decided to learn Rust where i found out that Macro's are heavily used which are a means of metaprogramming. At this point metaprogramming is not shown as tag in Katas which makes it hard to search a Kata based on meta-programming 

#### Describe the solution you'd like
It would be great if we can have metaprogramming under tag in Katas. Eventually people will start adding it as tag to their new Kata. 

#### Describe alternatives you've considered
No Alternative solution that i can think of.

#### Additional context
N/A

**Comment by Voileexperiments** [comment]
Isn't there already an existing tag `metaprogramming`?

**Comment by Ankit-rana** [comment]
@Voileexperiments 
Thanks for pointing me that out. I can see now that it exists as an API but it does not appear in GUI Kata page under Tags in left tab.

**Comment by kazk** [comment]
Closing because it's already there.

> it does not appear in GUI Kata page under Tags in left tab.

Only the top 50 tags are shown.

Tags are a mess so I'd like to clean up eventually.
