### ISSUE TITLE
Blatant RACISM on codewars.

### ISSUE THREAD

**Issue by ExtraLime** [Codewars/codewars.com#1799]
I don't know where else to report this issue. But there is a blatantly racist answer to a kata i just did....WTF. And apparently it's been up for more than a year. Personally, I find this 100% appalling, and it needs to be removed. 
![image](https://user-images.githubusercontent.com/37124296/56462110-351c9d00-6372-11e9-94b2-28178da58732.png)
How is this still on the site?
Can be seen on the solutions in python to this kata
https://www.codewars.com/kata/526571aae218b8ee490006f4/train/python

**Comment by kazk** [comment]
Thanks for reporting. The solution is removed.
