### ISSUE TITLE
Kata search is broken

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1801]
![image](https://user-images.githubusercontent.com/31668662/56522346-fabc2700-654e-11e9-804b-fd06025c3a72.png)

**Comment by Chrono79** [comment]
Kata search for all katas except 8 kyu ones.

https://www.codewars.com/kata/search/?q=&r%5B%5D=-7&r%5B%5D=-6&r%5B%5D=-5&r%5B%5D=-4&r%5B%5D=-3&r%5B%5D=-2&r%5B%5D=-1

I think there is an 8 kyu broken kata, [this one](https://www.codewars.com/kata/who-is-going-to-pay-for-the-wall/) causing this problem.

**Comment by Autumn-Chrysanthemum** [comment]
+1 Can't click on Kata menu item

**Comment by kazk** [comment]
Sorry for the delay. Yesterday was a holiday. I'll try fixing this as soon as possible.

@Chrono79 thanks. Looks like that kata is causing it.

**Comment by kazk** [comment]
The search should work now because I just removed the problematic kata from the search index. I haven't figured out the actual problem yet.

**Comment by kazk** [comment]
Closing as the main issue is resolved. The data of the kata that caused this is really messed up, but it shouldn't affect anything else.
