### ISSUE TITLE
nil can't be coerced into Integer

### ISSUE THREAD

**Issue by Neuly** [Codewars/codewars.com#1802]
#### Describe the bug
I am not able to open the page, where I can search for katas. I always get the error message 500 and the message: nil can't be coerced into Integer

#### To Reproduce

1. Go to 'https://www.codewars.com/kata/latest/my-languages'
2. The internal Server error appears

I think this error is dependent on my user, due to the fact that a friend of mine can open this page without any problems.

#### Expected Behavior

Seeing the page to search and choose katas.

#### Contexts

Please complete the following information:

- Codewars username: Neuly
- OS: Win 7
- Browser: IE 11, Chrome 73.0.3683.103

**Comment by ivanji** [comment]
Same here. Tested on different browsers.

**Comment by hobovsky** [comment]
You're 10 hours late: #1801 ;)

**Comment by mosleymos** [comment]
Same here. Can't search any kata.

**Comment by alzca1** [comment]
It happens the same to me.

**Comment by robert-dopieralski** [comment]
same here

**Comment by IShadowmaNI** [comment]
same here actually...

**Comment by EricsonWillians** [comment]
Same here! :)

**Comment by dankgen-tobias** [comment]
Same for me, too!

**Comment by brudolce** [comment]
yup, same issue here

**Comment by Chrono79** [comment]
Temporary workaround:

https://www.codewars.com/kata/search/?q=&r%5B%5D=-7&r%5B%5D=-6&r%5B%5D=-5&r%5B%5D=-4&r%5B%5D=-3&r%5B%5D=-2&r%5B%5D=-1

will get you all katas except 8 kyu ones.

**Comment by nomennescio** [comment]
Same issue. Chrome browser.

**Comment by kazk** [comment]
Closing as duplicate of #1801
