### ISSUE TITLE
Server error when trying to reach kata/latest/my-languages

### ISSUE THREAD

**Issue by dankgen-tobias** [Codewars/codewars.com#1803]
#### Describe the bug
I worked on a solution for a kata called "Next bigger number with same digits". My solution worked, but was too slow. Since I'm always working together with a friend (Username: Bergi) he gave me his solution and I submitted it. Then the server error popped up and since then I am not able to reach the site https://www.codewars.com/kata/latest/my-languages.  So when I klick on "Kata" on the menu on the left, the page loads for half a second and then there comes an error message: "Looks like there was a server error! (500)". I deleted my cookies on chrome and also tried it with Microsoft Edge.

For my friend everything still works fine.

I've also tried to complete a different kata, but I still get the error when I click on "Katas".

#### To Reproduce

1. Go to https://www.codewars.com/kata/latest/my-languages
2. See error

#### Expected Behavior
Usually the page with the katas should appear

#### Screenshots
![Annotation](https://user-images.githubusercontent.com/49884593/56582848-829a4380-65d8-11e9-957b-612bcc0eb31d.png)

#### Contexts

- Codewars username (if account related): [e.g., Tobias97]
- OS: [e.g. Windows 10.0.17763]
- Browser: [e.g. chrome 73.0.3683.103 (Official Build) (64-bit), Microsoft Edge]

**Comment by Chrono79** [comment]
#1801 and #1802 are the same. Don't open another issue if it's the same problem.

**Comment by dankgen-tobias** [comment]
> #1801 and #1802 are the same. Don't open another issue if it's the same problem.

Oupsie, my bad. Didn't see those two.
/closed
