### ISSUE TITLE
Case sensitivity when changing username

### ISSUE THREAD

**Issue by davidweisscode** [Codewars/codewars.com#1804]
#### Username in other capitalization not available
When updating username in account settings to a new one, **using different capitalization of letters**, an error pops up informing the user that this username is not available.

#### To Reproduce

1. Go to account settings area
2. Change username "JohnDoe" to "johndoe"
3. Scroll down and press Update button
4. See error in red

#### Changing the username in account settings
User should be able to change capitalization of their username.

#### Contexts
- Browser: Chrome

**Comment by kazk** [comment]
Fixed
