### ISSUE TITLE
Mistakenly awarded kata for a 1 kyu problem (BECOME IMMORTAL)

### ISSUE THREAD

**Issue by krishpycreme** [Codewars/codewars.com#1805]
This isn't as much of a bug as me being stupid but still please hear me out. I run the account "krishp" on codewars and I was looking at some of the 1 kyu python problems. I searched for a solution online to try to see how someone could solve it and I ran it in the code editor. I didn't realize that you get honor just for solving all the test cases and I thought you just got it once you press submit. 
Anyway, I ended up getting like 200+ honor for "solving" that kata and now my rank is inflated. Is there a way I could have like 200 kata removed from my account and go back to 6 kyu?

**Comment by kazk** [comment]
Done. Please use "Unlock Solutions" button next time.

**Comment by krishpycreme** [comment]
Mr. Kazk,

I love you man. Thank you so much!

Regards,
Krish
