### ISSUE TITLE
Cannot "properly" log in

### ISSUE THREAD

**Issue by wthit56** [Codewars/codewars.com#181]
On most pages, I seem to not be logged in. When I click the "log in" button, and log in using my Github account, it all goes through instantly, and goes to the home page, showing me as being signed in. But then, when I try to go to pretty much any other page (search, or any kata), it shows me as not being logged in. And so, I cannot train on any kata on the site.

On a rare occasion, I get a 500 error when I go to a kata.

I have tried removing all codewars cookies, but nothing changed. I am using Google Chrome 45.0.2454.85 dev-m.

**Comment by bbugh** [comment]
This is probably caused by #166 *Redirect from codewars.com to www.codewars.com or vice versa*. If I force codewars to use www.codewars.com, I no longer get the logged out/can't train issues.

**Comment by brendanvos** [comment]
If it was indeed related to #166 this may be fixed as #166 has been closed.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
