### ISSUE TITLE
PHP: die passed in code makes succeeds every test

### ISSUE THREAD

**Issue by andreknieriem** [Codewars/codewars.com#1811]
Hey I just saw some 
```
die('<PASSED::>');
```
 in the solutions and tried one of my own. It seems you can pass every kata with this. Can you block this?

**Comment by DonaldKellett** [comment]
As mentioned in a reply to a comment of yours just a few days ago, this is commonly known as the early-exit cheat which cannot be reliably prevented in most languages.  Instead, those found to abuse this cheat repeatedly on Kata (especially blue/purple ones but not limited to them) are permanently banned, i.e. with rank set to `8 kyu`, honor set to `0` and no way of editing/deleting the offending account.

**Comment by andreknieriem** [comment]
Ok. Is it possible to remove my test for kata https://www.codewars.com/kata/multiplying-numbers-as-strings/solutions/php? Would be great as this was only a test. My username is typhoch2.Thanks

**Comment by kazk** [comment]
Marked as cheat. Please don't do this anymore.

I'll try to spend some time soon to fix the cheat detection that's been failing to do this automatically.
