### ISSUE TITLE
Unable to post an Issue on a Kata

### ISSUE THREAD

**Issue by linovifian** [Codewars/codewars.com#1814]
#### Describe the bug
I am unable to post an Issue in [this kata](https://www.codewars.com/kata/tribonacci-sequence/) 

#### To Reproduce
Whenever I try to click, POST the loading bar appears for a second and then disappears again. 
The textarea stays open and I can press POST as much as I want.

![image](https://user-images.githubusercontent.com/33651022/57386669-1f520900-71b5-11e9-9ad0-2125dc95e81d.png)

I can see from the developper console that I seem to have no access to this resource:
![image](https://user-images.githubusercontent.com/33651022/57386186-24fb1f00-71b4-11e9-9b9d-10ceaff4acd9.png)

I thought that I was unable to post anything because I have not completed it in any language. So I submitted a solution in Java, but still wasn't able to post a comment.

The text I entered:

> Not sure what the assertion logic is doing. My last print statement before i return the DoubleArray is: 
`Result: [1.2219787059623188, 7.958071682121853, 10.172098571448887, 19.35214895953306, 37.4823192131038, 67.00656674408575, 123.8410349167226, 228.32992087391216, 419.17752253472054, 771.3484783253552, 1418.855921733988, 2609.381922594064, 4799.5863226534075, 8827.82416698146, 16236.792412228931]`
then I get an error:
`It should work with random inputs too: arrays first differed at element [0]; expected:<1.2219787059623188> but was:<2609.381922594064>`
But as seen from the println, the first element is `1.2219787059623188` and only the twelfth element is `2609.381922594064`

**Maybe** it's the markup that's causing the error?

#### Expected Behavior
I can post an Issue.

#### Contexts
- OS: Windows 10
- Browser: Chrome 74.0.3729.131 (Official Build) (64-bit)

#### Screenshots
The URL it is accessing:
![image](https://user-images.githubusercontent.com/33651022/57386582-f29df180-71b4-11e9-9c09-abc53c973d26.png)

**Comment by kazk** [comment]
What's your username?

**Comment by linovifian** [comment]
linov

**Comment by linovifian** [comment]
After going through my emails I saw an unread confirmation mail in my spam folder. 

Seems that was the issue, that my account was not confirmed.

Though on the UI it is not really clear that I should confirm my account. (as there is no error) which should still be fixed.

- No user guidance to confirm the account
- No error that I am not allowed to comment

**Comment by dmikester1** [comment]
I agree with linovifian here.  There should be some sort of error that pops up and says "you are not allowed to comment because you have not verified your email, please do that first."  As it is now, the red line just goes across and nothing happens.  Appears to be a bug, kind of is, kind of isn't.
