### ISSUE TITLE
Blocked users list are carried on even after user deactivated their profile

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1815]
SteffenVogel deactivated his account recently, which caused his katas to become disowned.

However, [the guest account](https://www.codewars.com/users/user5036852) that was associated with it is still blocking lots of power users (which means they can't edit the kata or comment due to #1365), presumably because user block checks are done by checking whether the uuids of all users that have blocked current user contains the kata author's uuid, and the user uuid doesn't change after deactivating the account. Effectively this means that they're blocked from the katas forever (which is another reason why this is a bad idea in the first place).

**Comment by kazk** [comment]
Fixed
