### ISSUE TITLE
Cannot submit any solution

### ISSUE THREAD

**Issue by krishrpatel** [Codewars/codewars.com#1816]
I was trying to submit a solution to a g964 kata and it kept timing out. I tried even just returning the number that was given and it still timed out. I went to other katas and told it to return very simple things such as 1 or the number and it still kept timing out. I can't submit any solution or test anything. 
Ex:
def doSomething(n):
   return n
...This would result in a timeout in multiple katas that I tested. I tested this using a variety of different katas ranging from 6 kyu to 8 kyu.

**Comment by kazk** [comment]
Does sample tests work?

**Comment by krishpycreme** [comment]
Nothing shows up.

**Comment by krishpycreme** [comment]
I restarted my computer and my internet and it still is like that. I am not sure why.

**Comment by kazk** [comment]
> I tested this using a variety of different katas ranging from 6 kyu to 8 kyu.

Can you provide one example kata you tried, including the language?
