### ISSUE TITLE
Can't submit, servers busy

### ISSUE THREAD

**Issue by Vontei** [Codewars/codewars.com#182]
Hello,

I have not been able to submit any any answers since last night,
```
Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated.
```

Just a heads up.

**Comment by jhoffner** [comment]
I'm currently investigating a couple of major issues, although code execution is running fine for me. Is there any other information you may be able to provide?

**Comment by Vontei** [comment]
I just sat back down and when I refreshed, logged out, and logged back in about 50% of my submissions work. I just need to refresh once or twice. Perhaps its local to my machine.
