### ISSUE TITLE
Racist nickname and Yumite

### ISSUE THREAD

**Issue by Jaune9** [Codewars/codewars.com#1824]
First time reporting, I don't know if I'm doing it right so don't hesitate to teach me the way to do it better.

The user named youremeo or dieniggerdie made a yumite called nigger.

You should see proofs below :

![image](https://user-images.githubusercontent.com/47558505/58027713-8b1f6480-7b19-11e9-8486-c04a7d526719.png)

![image](https://user-images.githubusercontent.com/47558505/58027659-6aefa580-7b19-11e9-934d-f8b355a6ac0b.png)

**Comment by kazk** [comment]
Thanks for reporting. Kumite deleted and username changed.
