### ISSUE TITLE
4 Kyu Kata - "Human readable duration format" completed, received only 1 honor point

### ISSUE THREAD

**Issue by qetennyson** [Codewars/codewars.com#1825]
I completed this kata today as a 5 Kyu member, and received only 1 honor.

![Screen Shot 2019-05-22 at 2 40 05 PM](https://user-images.githubusercontent.com/16693523/58199926-93a1a780-7c9f-11e9-86b1-90f1579c70cc.png)

I would say that the Kata is slightly overranked at 4 Kyu, but would definitely be at least a 6 from the string construction perspective.  With that said, the problem is still advertised at 4 Kyu.  Secondly, even a 5/6 Kyu problem awards far more honor for me than 1.

Mistakenly, I raised an issue with the Kata itself, and a more senior member recommended I create an issue here.

Thank you!

**Comment by jhoffner** [comment]
Honor sometimes takes a while to catch up, because of how the system runs things in the background. Closing for now since this has likely corrected itself by now. Please confirm. 

As for the ranking being too high/low, that is appropriate to be discussed within the kata itself, as a suggestion.

**Comment by qetennyson** [comment]
Sorry I'm just now having a chance to get back to this, but it never corrected itself.  Not a big deal, I raised the issue simply because I saw several other folks mention it in the Kata discourse.
