### ISSUE TITLE
Server Errors

### ISSUE THREAD

**Issue by spencerpomme** [Codewars/codewars.com#1828]
#### To Reproduce

Just visit the site then you get this error.

#### Expected Behavior

It should be expected that the site can be visited.
#### Screenshots

![image](https://user-images.githubusercontent.com/10029658/58390993-6e79b400-8066-11e9-9d60-ed9255f24e67.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): I don't think it is account related
- OS: [e.g. macOS] Windows 10
- Browser: [e.g. chrome, safari] chrome
- Browser Version:   74.0.3729.169

**Comment by kazk** [comment]
The Redis service we use seems to be down. See https://status.codewars.com/ for updates.

**Comment by kazk** [comment]
Fixed

**Comment by spencerpomme** [comment]
Cool
