### ISSUE TITLE
Access to warriors solution

### ISSUE THREAD

**Issue by adam-tokarski** [Codewars/codewars.com#183]
Wouldn't be wonderful sometimes to get direct access to warrior solution? I mean, sometimes Kata's conditions is to not use certain built-in function or to avoid the simplest way to achieve something. For example, one of my Kata is to create own version of strings split function, but there is no way to control if one didn't use the built-in method, in fact. 

So I thought that maybe could be here some additional panel (by analogy to preloaded section: postloaded? postprocessed?), or - and this would be better - given some magical string with text of users solutions at test cases section. 

Think about it. Limit of use some functions? Possible. Kata with constraint "no more than 3 lines" - why not?

**Comment by kazk** [comment]
Submitted solution is written to `/home/codewarrior/solution.txt` so you can read that file in tests.
You can also use `/workspace/solution.txt` (`/workspace` is symlink of `/home/codewarrior`).
