### ISSUE TITLE
Would be nice if Array.prototype.flat() worked.

### ISSUE THREAD

**Issue by ElizabethS5** [Codewars/codewars.com#1830]

**Comment by Voileexperiments** [comment]
It's only available [since Node 11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Browser_compatibility) while the newest LTS Node is Node 10 (and CW uses LTS versions). Not much that can be done.

Besides, it's really an issue for the runner repo.
