### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by kraut74** [Codewars/codewars.com#1832]
Hi,

I made today a new account on codewars, and after playing around a little bit on it, I closed the browser without logging out. After a while I wanted to log back in, but couldn't. The login page keeps throwing me 'Invalid email or password.' error. I am certain that I am using the correct email and password. Also, I did not get any confirmation mail on my email account which I used to create the account on codewars. After trying to resend the confirmation instructions, the page said that my email was not found. The same happens if I try to reset my password. 

The email address which I used to create the account is: shadow74074@yahoo.com
The username is: kraut74

I appreciate the help. Thank you.

**Comment by kazk** [comment]
Looks like you created your account with gmail. `shadow74074` at gmail.
