### ISSUE TITLE
Most Recent Language Trained Change Even Before The Kata Is Completed

### ISSUE THREAD

**Issue by EULIR** [Codewars/codewars.com#1835]
#### Describe the bug
I tried to solve a Kata but I selected the wrong language. I haven't written any code and clicked nowhere. However, this language automatically appears on the `most recent` column on my profile. Does it make more sense if one completes a Kata in a certain language and then this language appears on the profile? 

#### To Reproduce
1. enter a Kata
2. train this Kata in a new language
3. write no code
4. go back to profile page and see `most recent trained` column

#### Expected Behavior
Most recent trained language shown to be the most recent language users use to actually **solve** a Kata

**Comment by kazk** [comment]
This is working as intended.

> 2\. train this Kata in a new language

So most recently "trained" language is updated. Trained doesn't mean completed. Once you start a kata in the language, your current language is updated to the language. This information is also used in other places like choosing the language for a kata when you open a url without language included.
