### ISSUE TITLE
'Valid Braces' Kata incorrect unit tests. (JAVA 11) 

### ISSUE THREAD

**Issue by davvies** [Codewars/codewars.com#1836]
After doing problem within an IDE (and extensive debugging), the logic was working within my program. The kata has two unit tests, both of which passed when running the 'run sample test', however, when clicking on the 'attempt' button, it said the tests had failed, even though it was literally the same tests as before (that passed), is there something wrong with the attempt button for this kata. I also saw someone else having the same issue on the discussion board for this same problem.

**Comment by hobovsky** [comment]
You should raise this issue in kata discourse [here](https://www.codewars.com/kata/valid-braces/discuss/java), and not here on github board. This board is used for general CodeWars issues, and not problems related to specific kata.

**Comment by davvies** [comment]
> You should raise this issue in kata discourse [here](https://www.codewars.com/kata/valid-braces/discuss/java), and not here on github board. This board is used for general CodeWars issues, and not problems related to specific kata.

The other person with such issue was redirected to the git, under the command that it was 'not an issue'.

**Comment by Chrono79** [comment]
Not the same problem:

>i ran the attemp button again, and every test was passed but i can't see any submit final button.

He can't see the submit final, only attempt, if you see some tests marked as failed, then you have to make your code pass those before seeing it as submit final.

**Comment by davvies** [comment]
> Not the same problem:
> 
> > i ran the attemp button again, and every test was passed but i can't see any submit final button.
> 
> He can't see the submit final, only attempt, if you see some tests marked as failed, then you have to make your code pass those before seeing it as submit final.
> 
> > even though it was literally the same tests as before (that passed)
> 
> No, they're different, there are more tests when clicking attempt, print the input and see it for yourself.

AHHH GOD DAMN, IT WAS A SILLY MISTAKE! thanks for the clear up! :)
