### ISSUE TITLE
'Find the smallest' Kata - missing crucial test case (Python)

### ISSUE THREAD

**Issue by miecio190** [Codewars/codewars.com#1837]
Link to Kata: [Find the smallest](https://www.codewars.com/kata/573992c724fc289553000e95)
Crucial test case with number that has increasing digits is missing. Examples input:
- 123456789
- 12589

My conclussion was that many solutions might stack on this test case. I have tried to add this test case to already existing test cases. Unfortunately, the currently existing fork failed the test case.

I have made following updates:
1. Added the test case:
testing(123456789, [123456798, 7, 8]);
2. 
Adjusted the fork from:
`
def smallest(n):
    s, mem = str(n), [-1, -1, -1]
    tmp, l = s, len(s)
    for i in range(l):
        c = s[i]
        str1 = s[:i] + s[i + 1:]
        for j in range(0, l):
            str2 = str1[:j] + c + str1[j:]
            if (str2 < tmp):
                tmp = str2
                mem = [int(tmp), i, j]
    return mem
`
To:
`
def smallest(n):
    s = str(n)
    mem = [int(s[:-2] + s[-1] + s[-2]), len(s)-2, len(s)-1]
    tmp, l = s, len(s)
    for i in range(l):
        c = s[i]
        str1 = s[:i] + s[i + 1:]
        for j in range(0, l):
            str2 = str1[:j] + c + str1[j:]
            if (str2 < tmp):
                tmp = str2
                mem = [int(tmp), i, j]
    return mem
`

PS. I have never done it before, so any clues would be helpful.

**Comment by miecio190** [comment]
Similar test case shall be added in other languages.

**Comment by Blind4Basics** [comment]
> Please, verify my work.

how?

* no link to the kata
* no actual description of what you did (precise enough) => what does "the fork failed" mean? the solution of the author didn't pass the test? Then update it. Or the tests ran fine but the publication of the fork failed? In that last case, that's a cw issue. Otherwise, there no issue here.

**Comment by miecio190** [comment]
I have updated initial post with the information you have asked. Still, I do not know how to insert code in readable way.

Please, don't be unpleasant and show some empathy. I have never contributed to any Kata before. I have never used github before. This is all new to me.

**Comment by Blind4Basics** [comment]
> Please, don't be unpleasant and show some empathy.

x)
well, I answered on the same tone than you posted, I believe? ;)

Seems to me you have to discuss that with g964: seems to me it's rather a kata issue (missing edge case in the tests). Let's see if you both can sort it out through the kata discourse. If ok there, don't forget to resolve here.

cheers.

**Comment by g964** [comment]
Could be closed.

**Comment by Voileexperiments** [comment]
This repo is not for issues with individual katas. Go to kata discourse for that.

**Comment by kazk** [comment]
Hi @miecio190, please open kata issues on [kata discussion page](https://www.codewars.com/kata/find-the-smallest/discuss/python). To post readable code, see [markdown formatting](https://github.com/Codewars/codewars.com/wiki/Markdown-Formatting). Markdown is used both on Codewars and GitHub.
