### ISSUE TITLE
Kata trainer's buttons become inaccessible in certain conditions

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#1839]
#### Describe the bug

Some of the buttons become inaccessible in certain conditions.

- Using a screen with certain resolutions: 1280xH
- When Unlock Solution button is displayed
- When the number on Discuss button is 100 or more
- When submit button is Submit Final

This is a subset of #1214.

#### To Reproduce

1. Go to a kata with 100 or more comments that you haven't solved
2. Solve the kata and attempt so submit button shows "Submit Final" instead of "Attempt" 

#### Expected Behavior

Buttons should remain accessible. At least the submit final button.

#### Screenshots

Please comment with screenshots if you run into this.

**Comment by error256** [comment]
It's **100** or more comments after the last fix.
1280x1024 screen, 1280x896 page, seems to happen at 1280xAnything:
![image](https://user-images.githubusercontent.com/5375100/59225258-c1537f80-8bbf-11e9-8340-49ba7d55358f.png)

**Comment by kazk** [comment]
This should be fixed. I also fixed the issue that was forcing to use `overflow: hidden` that made those buttons unreachable.

It's not perfect, but should be better.
