### ISSUE TITLE
Can't re-publish changes to kata that cause previous solutions to infinite loop.

### ISSUE THREAD

**Issue by marc-goodman** [Codewars/codewars.com#184]
When you make changes to a published kata that cause one or more previously correct submissions to infinite loop, the re-publish process hangs.  For example, let's say a solution to a kata was:

``` javascript
function(n) {
  while(n != 0)
    n--;
  return n;
}
```

And the tests were all testing with positive n. Then, let's say you change the test set to also try passing in -1 for n. Now, the above solution which passed before starts hanging (ignore overflow/underflow for the sake of argument). The republish process apparently doesn't time out the validation checks on previous submissions, and will hang, leaving you in "Please wait while we republish..."

Suggested solution: Use a timeout when re-validating previous solutions. This could either be the original 6 seconds, or you could be generous and increase the timeout to, say, 12 seconds.

I ran into this bug when trying to re-publish this kata:

http://www.codewars.com/kata/program-hangs

**Comment by kazk** [comment]
Closing old issue. Please open a new issue if this problem is still there.
