### ISSUE TITLE
My gitter room "Activity" panel is stale info

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#1841]
The ACTIVITY panel (showing CW Issues etc) is stale information last updated several months ago.

Everything else on the page seems OK - Just the ACTIVITY is wrong.

If it is some noob setting I have accidentally enabled/.disabled I can't find it... please advise.

![image](https://user-images.githubusercontent.com/22114719/59323710-207bd600-8d1f-11e9-96c4-682dd2d67ecb.png)

Env: Chrome browser.

**Comment by FArekkusu** [comment]
It is like this for everybody. It seems moving issues between repositories causes this (both times this happened right after an issue was moved from `codewars` to `codewars-runner-cli`).

**Comment by dinglemouse2250** [comment]
> It is like this for everybody. 

That's good to know. Thanks. I thought I'd accidentally botched some unknown setting.

**Comment by kazk** [comment]
It was using deprecated GitHub services and I updated to use Webhooks. This comment should show.

**Comment by kazk** [comment]
Closing as fixed
