### ISSUE TITLE
Run Sample Tests fails with Internal Server Error, retry does not solve.

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1842]
Similar to earlier reports, running Sample Tests on multiple katas gives an Internal Server Error. Retrying by submitting a new request does not solve the issue. This issue has been reported before, and is probably of a temporary nature.

**Comment by nomennescio** [comment]
When trying to do the exact same thing on preview.codewars.com, I see no issue at all. This is clearly server related.

**Comment by gbochmann** [comment]
I'm also affected by this issue.

**Comment by Christoph-Harms** [comment]
+1, also affected by this. Seems to occur on all katas in all languages (...that I checked).

**Comment by nickproud** [comment]
Can confirm that this is also affecting me

**Comment by nickproud** [comment]
Also tried preview.codewars.com and that is working as expected

**Comment by sudhz5588** [comment]
I am also affected by the same issue

**Comment by kazk** [comment]
The outage was caused by Redis service going down. I'm deploying the changes right now so it should go back up soon. See https://status.codewars.com/

**Comment by kazk** [comment]
The runner service should be back. Sorry it took some time to notice. It's 3 AM :sleepy:
