### ISSUE TITLE
Ruby tests: Max Buffer Size Reached (1.5 MiB)

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1848]
In a Ruby translation of a kata I have very long arrays. Ruby tests display lots of:
```
Test Passed: Value == [... long array of elements...]
```
so the max buffer size is reached. Is it possible to prevent Ruby tests to display all this?

**Comment by g964** [comment]
Solved.

**Comment by mazenadel19** [comment]
for anyone who comes across this in the future, 
the error is because you left printing statement (mostly inside a loop) when attempting your solution, removing it shall solve the problem

**Comment by Blind4Basics** [comment]
see https://docs.codewars.com/training/troubleshooting/#maxbuffer
