### ISSUE TITLE
Add Apache Commons Lang 3 support

### ISSUE THREAD

**Issue by ValeriyKoloytanov** [Codewars/codewars.com#1849]
**JAVA** For some katas more eye-candy solutions can be achieved using  ArrayUtils and  StringUtils classes. Can this library be added on server so we can import it in  compiler?

**Comment by error256** [comment]
I think it's been available here for years, it's just not documented.

**Comment by kazk** [comment]
`org.apache.commons:commons-lang3:3.8.1` is available for Java 11.

**Comment by kazk** [comment]
I've updated [the wiki page](https://github.com/Codewars/codewars.com/wiki/Language-Java). There's more, but others are dependencies of those or exists for Qualified.
