### ISSUE TITLE
undefined method `permissible?' for nil:NilClass.

### ISSUE THREAD

**Issue by ggorlen** [codewars/codewars.com#1851]
#### Describe the bug
Upon loading the [Tower Defense: Risk Analysis](https://www.codewars.com/kata/5a57faad880385f3b60000d0) kata description, I got a ```undefined method `permissible?' for nil:NilClass```. It worked fine upon reloading the page.

#### To Reproduce

Not sure what the trigger was, unfortunately. I opened 7-8 katas from the [my-languages](https://www.codewars.com/kata/my-languages) page in new tabs, then flipped through them sequentially and noticed this one failure.

#### Expected Behavior

The page should have loaded normally.

#### Screenshots

![permissible](https://user-images.githubusercontent.com/17895165/59949777-03cf5480-9429-11e9-9c6b-ec1e797cd122.png)

#### Contexts

- Codewars username: ggorlen
- OS: Windows 10
- Browser: Chrome
- Browser Version: 75.0.3770.90 (Official Build) (64-bit)

**Comment by Steffan153** [comment]
It happens every once a while with anything, then a refresh fixes it. :wink:

**Comment by kazk** [comment]
This (`nil` error with `permissible?`) should be fixed.
