### ISSUE TITLE
I cant post comment on kata...

### ISSUE THREAD

**Issue by kuldeepgajera** [Codewars/codewars.com#1858]
#### Contexts

Please complete the following information:

- Codewars username (if account related): [e.g., jhoffner]
- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Comment by kazk** [comment]
Have you confirmed your email address? Someone had similar issue https://github.com/Codewars/codewars.com/issues/1814#issuecomment-490755232

**Comment by kuldeepgajera** [comment]
Thanks solved..;)
