### ISSUE TITLE
golang strings.ReplaceAll is undefined

### ISSUE THREAD

**Issue by mightyco** [Codewars/codewars.com#1861]
Example code:

```
package kata

import (
	"fmt"
	"strings"
)

func Catalog(s string, article string) string {
  fmt.Println(strings.ReplaceAll("oink oink oink", "oink", "moo"))
  return "hi"
}
```

Expected result: Test fails but prints "moo moo moo".

Actual result: BUILD fails with STDERR:
# codewarrior/kata
./solution.go:10:15: undefined: strings.ReplaceAll

This works on play.golang.org (with the exception that the package/function is "main").

![image](https://user-images.githubusercontent.com/49200320/60460351-59a9b680-9bf8-11e9-99a8-74449e1db8e0.png)

![image](https://user-images.githubusercontent.com/49200320/60460371-67f7d280-9bf8-11e9-8f8b-54eb8020f6d9.png)

**Comment by kazk** [comment]
That's because Codewars uses Go 1.10 as it says next the language name. `ReplaceAll` was added in 1.12.

You can request a new version by opening an issue on https://github.com/Codewars/codewars-runner-cli
