### ISSUE TITLE
Criterion C test framework does not support logging messages

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1864]
According to the [Criterion documentation](https://criterion.readthedocs.io/en/master/logging.html) it should be possible to generate logging output. The mentioned functions are however not supported on the Codewars platform. The only alternative is to use the stdio functions, but these interfere with test framework interpretation.

**Comment by kazk** [comment]
Closing as duplicate of https://github.com/Codewars/codewars-runner-cli/issues/596
