### ISSUE TITLE
5xx Server Error

### ISSUE THREAD

**Issue by bdoremus** [Codewars/codewars.com#1867]
#### Describe the bug
When trying to load any webpage in the codewars.com domain, I get a 5xx server error.

#### To Reproduce
Navigate to codewars.com from any browser.

#### Expected Behavior
Page load.

#### Screenshots
<img width="855" alt="5xx Server Error" src="https://user-images.githubusercontent.com/25072197/60731055-c6c49100-9f03-11e9-977e-52b00d5d1751.png">

#### Contexts

Please complete the following information:

- Codewars username (if account related): n/a
- OS: macOS
- Browser: chrome, safari
- Browser Version: Chrome v74, Safari 12.1

**Comment by 1991sig** [comment]
Same for me

* Codewars username (if account related): n/a
* OS: macOS
* Browser: Safari, Firefox Quantum
* Browser Version: Safari 12.1.1, Firefox Quantum 67.0.4 (64-bit)

**Comment by ddradovanovic** [comment]
Same here. 

- Codewars username (if account related): n/a
- OS: macOS
- Browser: chrome
- Browser Version: Chrome Version 75.0.3770.100

**Comment by steffsas** [comment]
Same here.

Codewars username (if account related): n/a
OS: Windows 10
Browser: chrome
Browser Version: Chrome Version 75.0.3770.100

**Comment by BorisPro** [comment]
Same, wrote #1868 

    Codewars username (if account related): BananaTrader (hopefully - i have to guess)
    OS: Windows 10
    Browser: Firefox
    Browser Version: Firefox 67.0.4

Login name is myOnlineIdentity@...de

**Comment by bdoremus** [comment]
Appears resolved.
