### ISSUE TITLE
Unable to post comments or reply

### ISSUE THREAD

**Issue by abdulmoeezali7** [Codewars/codewars.com#1869]
Hi,

I've been facing this issue right from the very start when i created my account. I am unable to post comments on Codewars. The 'Post' button seems to not register the click. Moreover, the red bar on top of the browser (for displaying progress) moves like it should depicting that it's posting my comment but nothing happens. 
while the problem persists, I am unable to post comments or get guidance from the community. Similarly, I am unable to reply.

Please resolve this issue.

**Comment by Voileexperiments** [comment]
This is #1814.

**Comment by abdulmoeezali7** [comment]
Thank you. The problem was resolved after confirmation of account. This however needs to be specifically mentioned on the UI of the website.
No error was generated saying that I am not allowed to comment.
