### ISSUE TITLE
Missing community guidelines

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#187]
I just noticed that Codewars doesn't have any community guidelines/rules. This is usual standard practice on community driven sites. They contain something like
- don't harass other users
- don't post things with certain content
- don't pose as moderators
- be nice to each other
- don't spam
- …

While Codewars is a friendly place, something like this probably won't hurt. After all, you don't want users to complain if you (temporarily) ban them for something.

**Comment by g964** [comment]
I totally agree with that!!!

**Comment by bkaestner** [comment]
So, what about comments like [this](http://www.codewars.com/kata/559f44187fa851efad000087/discuss#563b97a95e9952bbd500009d)?

> shit wording

This isn't the first two-word insulting yet invalid issue I've seen.

**Comment by kazk** [comment]
https://github.com/Codewars/codewars.com/wiki/Community-Code-of-Conduct
