### ISSUE TITLE
Hi, I'm unable to post comments on kata. when I press post, nothing happens, no matter how many time I press it. What should I do?

### ISSUE THREAD

**Issue by Jaccobtw** [Codewars/codewars.com#1871]
#### Describe the bug
I can't comment on kata
#### To Reproduce

Go to a kata
try to comment
watch nothing happen

#### Expected Behavior

I should be able to post a comment

#### Contexts

Please complete the following information:

- Codewars username : Jaccobtw
- OS: Windows 10
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Comment by Steffan153** [comment]
Which browser and version are you using?
If you're on Chrome, press Ctrl+Shift+I, go to network tab, try to post a comment, and post the results here.

I cannot reproduce this problem, and most people can comment on stuff.  🤔

**Comment by Jaccobtw** [comment]
success: false, message: "You do not have access to this resource"}
message: "You do not have access to this resource"
success: false

**Comment by Jaccobtw** [comment]
Is it because I'm not upgraded to red?

**Comment by DonaldKellett** [comment]
@Jaccobtw Perhaps you could try checking your mailbox and/or spam folder to see if you received an email from Codewars asking you to confirm your account.

**Comment by Jaccobtw** [comment]
It worked! Thank you

**Comment by Voileexperiments** [comment]
This is #1814.
