### ISSUE TITLE
Ability to edit kata as a contributor

### ISSUE THREAD

**Issue by Steffan153** [Codewars/codewars.com#1873]
#### Describe the bug
As of today (with 1,193 honor), I can edit katas if I have contributed to them. I thought you had to be 4,000 honor to be able to edit any kata, but now I see the edit button for all katas I have contributed to (i.e. have an approved translation of mine).

#### To Reproduce

1. Go to a kata you've contributed to
2. See the edit kata button even if you don't have 4k honor

#### Expected Behavior

To not see the edit button if you don't have 4k honor.

#### Screenshots

![DeepinScreenshot_select-area_20190709155943](https://user-images.githubusercontent.com/40404519/60926084-a62d6b80-a262-11e9-8180-0bd84dbf590a.png)
![DeepinScreenshot_select-area_20190709155951](https://user-images.githubusercontent.com/40404519/60926089-aaf21f80-a262-11e9-8aa9-67d7da80214c.png)

#### Contexts

- Codewars username: Steffan153
- OS: Manjaro Linux
- Browser: Chrome
- Browser Version: 75

**Comment by kazk** [comment]
You can edit the kata if you had contributed in the past. See https://github.com/Codewars/codewars.com/wiki/Privileges

**Comment by Steffan153** [comment]
But, like I said I'm not 4k honor yet.

**Comment by kazk** [comment]
Honor doesn't matter for a kata once you're a contributor of it. That page is confusing so I'll try rewording it.

**Comment by Steffan153** [comment]
Yeah, I didn't quite understand it and I thought this was a bug.

**Comment by kazk** [comment]
> * You have coauthored the kata in the past, or
> * You **have enough honor points to be a coauthor** and there's unresolved issue/suggestion for over a week

"have enough honor points to be a coauthor" (4000) is not needed for the first clause. It's easier to understand if you read it like code:

```
can_edit = coauthored || (have_enough_honor && have_unresolved_issues_suggestions)
```

because `coauthored` (edited) is `true`, the second one doesn't matter.

**Comment by Steffan153** [comment]
Yes, that code makes it clearer. I did understand thanks to your above comments though, but the code makes it even clearer.

**Comment by kazk** [comment]
I've updated the wiki page. Hopefully it's more clear.
