### ISSUE TITLE
A kata has -1 not-satisfied votes

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1876]
[This kata](https://www.codewars.com/kata/count-the-number-of-reservations/) has a wrong number of votes, and the number of not-satisfied votes is somehow `-1`. Apart from being incorrect, this also influences the satisfaction rating which is "boosted" as if it had 1 more `very satisfied` vote than it actually has.

![image](https://user-images.githubusercontent.com/31668662/61243580-f3bd4300-a750-11e9-9a48-e2d09545cc03.png)

![image](https://user-images.githubusercontent.com/31668662/61243529-d7210b00-a750-11e9-8267-ee76464b22f9.png)

**Comment by kazk** [comment]
Probably caused by some race conditions when removing a vote. Fixed the data.
