### ISSUE TITLE
I can't post in the discourse

### ISSUE THREAD

**Issue by asdf334** [Codewars/codewars.com#1877]
Whenever I try to post, I go to discourse on some kata and I press the button "POST". However, it doesn't do anything. Doesn't even react.

1. Go to any kata
2. Click on 'Discourse'
3. Attempt to post

- Codewars username (if account related): asdf334
- OS: Windows 7 (is that what it means)
- Browser: Chrome
- Browser Version: 76

**Comment by asdf334** [comment]
BTW asking this cuz i need to know how to make random tests in my kata. it's kinda confusing for me cuz u know.. first kata

**Comment by asdf334** [comment]
hello? anyone pls

**Comment by asdf334** [comment]
also is it because i dont have enough honor, i have 410 ish

**Comment by asdf334** [comment]
over 400 though

**Comment by asdf334** [comment]
oh nvm the kata works but i still cant psot

**Comment by asdf334** [comment]
the red load bar flashes

**Comment by asdf334** [comment]
but it doens't do anything so i cant post

**Comment by asdf334** [comment]
OMG a user reported an issue and i want to ask how to fix BUT I CANT POST!!! NOOOO

**Comment by asdf334** [comment]
NVM it works now; confirmed account. CW I would like it if you notified someone to confirm their account if their tried posting and it didnt work

**Comment by Bubbler-4** [comment]
This is a known issue #1814 .

**Comment by kazk** [comment]
The check to require confirmed email was added to reduce the risk of getting spammed. The warning not showing is related to a general Codewars bug where the error from the server is not handled well on the frontend. It'll be fixed when that's fixed.
