### ISSUE TITLE
Problem with JS tests

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#188]
I'm trying to translate a kata in JS. When I validate I get:
```
Basic tests
... - Expected: [1,12,0,4,6,1], instead got: [1,12,0,4,6,1]
... - Expected: [2,14,3], instead got: [2,14,3]
... - Expected: [-10,14,12,0], instead got: [-10,14,12,0]
... - Expected: [12,1], instead got: [12,1]
... - Expected: [4,-4,4,10,30,1], instead got: [4,-4,4,10,30,1]
... - Expected: [5,3], instead got: [5,3]
... - Expected: [1,-1,-2,2,3,-3,4,-4], instead got: [1,-1,-2,2,3,-3,4,-4]
```

"Expected" and "get" are exactly the same but the tests don't succeed.

**Comment by marc-goodman** [comment]
Two different arrays in JavaScript are not == even though they have the same contents. Try using assertSimilar instead of assertEquals.

**Comment by g964** [comment]
Yes, you are right! I knew that but I had forgotten!
