### ISSUE TITLE
Upgrading default Haskell version

### ISSUE THREAD

**Issue by agraboso** [Codewars/codewars.com#1882]
#### Describe the bug
I just hit 4000 honor, which gave me kata editing privileges. Seeing as there are many Haskell katas that are stuck in v7 because of tests, I set out to contribute upgrading them according to the guidelines in [this page](https://github.com/Codewars/codewars.com/wiki/List-of-Haskell-Kata-to-Update).

I successfully edited the tests for the [8-ball setup validation kata](https://www.codewars.com/kata/58fa711d9fd13e2da9000f8a), and republished it. However, when I tried changing the default Haskell version to v8, I received an error message saying

> Default Version is not a supported version 

#### To Reproduce

Edit the [8-ball setup validation kata](https://www.codewars.com/kata/58fa711d9fd13e2da9000f8a) and try changing the Haskell version from GHC 7.10.3 to GHC 8.2.

#### Expected Behavior

The kata should be republished using GHC 8.2.

#### Screenshots

N/A

#### Contexts

- Codewars username: agraboso
- OS: macOS
- Browser: Firefox
- Browser Version: 67

**Comment by kazk** [comment]
I think this is the same issue as https://github.com/Codewars/codewars.com/issues/869

You should be able to workaround this bug by doing what I described in #869. Making some insignificant change after switching the default version and before republishing.
Can you try that and let me know if that works?

I'll try to figure out the cause of it when I get a chance.

**Comment by agraboso** [comment]
Worked like a charm. Thanks!
