### ISSUE TITLE
You can select two options on sortBy field on the solutions page

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars.com#1885]
#### Describe the bug

You can select two mutually excluding options on sortBy field on the solutions page

#### To Reproduce

1. Go to Solutions page
2. Click on 'My solutions'
3. Click again on all solutions

This happenes to me while taking the screenshots for issue #1884

#### Expected Behavior

You should be capable to select only one option when sorting

#### Screenshots

![image](https://user-images.githubusercontent.com/1063901/61772281-7bd9c300-adb7-11e9-9d96-2ec5386641f6.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): javatlacati
- OS: Windows 10 Home
- Browser: Chrome
- Browser Version: Versión 75.0.3770.142 (Build oficial) (64 bits)

**Comment by Blind4Basics** [comment]
are you sure that the two fields are actually applying? Doesn't seems so to me. I've seen that very often (it's absolutely not new) and it feels to me like it's only a display bug: the applied filter is "newest", but the "best practices" one stay in red while it shouldn't.

**Comment by Steffan153** [comment]
The equivalent of this in frameworks would be that "Best Practices" was not marked as an "exact active" link. 

> it feels to me like it's only a display bug

Yep, it's just that best practices always remains to _display_ as active, but it isn't truly active.
