### ISSUE TITLE
You can post comments in the future

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1886]
#### Describe the bug
As atonishing it might sound... you can post a comment in a future time from the present. (Space time continous in danger?)

#### To Reproduce

1. Go to any Kata
2. Go to discussion
3. Post a comment
4. See how it's in the future from the past

#### Expected Behavior

Server time should not be in the future, I think it should be shown with timezone i.e. PCT

#### Screenshots

![image](https://user-images.githubusercontent.com/1063901/61774347-4c798500-adbc-11e9-899f-2f05cbb70405.png)

**Comment by Steffan153** [comment]
I've never seen this. It always says soon for several seconds, but this makes no sense. :confused:

**Comment by javatlacati** [comment]
Server is in the future dude!

**Comment by error256** [comment]
I've never seen this either; just posted a comment now and there's still nothing like this. Any details?

**Comment by Steffan153** [comment]
Maybe it's your timezone. Is all time stuff correct on your computer?

**Comment by kazk** [comment]
@javatlacati does this happen to you consistently? This is processed on the client side so I think the clock on your computer is off.

That text is displayed using seconds since the unix epoch (stored in `data-text-time` attribute) and comparing that to the time your browser returns.

**Comment by kazk** [comment]
Closing, but let me know if it still happens after correcting the clock or anyone else experiences this.
