### ISSUE TITLE
Dart translation tests fail after editing until you unpublish

### ISSUE THREAD

**Issue by Steffan153** [Codewars/codewars.com#1888]
#### Describe the bug
When you create a Dart translation, publish it, then edit it, and run the tests it gives a strange error:
```
Failed to load "test/solution_test.dart":
'file:///home/codewarrior/dart/test/solution_test.dart': error: line 6 pos 9: semicolon expected
  import "package:test/test.dart";
        ^
```
Also, un-publishing the Kumite seems to fix it. 
#### To Reproduce

1. Create a Dart translation
2. Save & publish it
3. Click edit
4. Run tests
5. See error 

#### Expected Behavior

The tests should succeed without errors.

#### Screenshots

![](https://i.imgur.com/QzBB4Sl.png)

#### Contexts

- Codewars username: Steffan153
- OS: Manjaro Linux
- Browser: Chrome
- Browser Version: 75.0.3770.142

**Comment by error256** [comment]
Did the Dart version get reset to 1.23? Looks like #690 maybe...

**Comment by Steffan153** [comment]
I can't see the version after it's published. But when I fork and change it to the older version the same problem happens, so that's likely.

**Comment by kazk** [comment]
Most likely the same issue as #690. Keeping this open for now until I get more info.

**Comment by Steffan153** [comment]
Well, what info do you need? It looks like the version thing, yes.

**Comment by kazk** [comment]
I meant I need to look into it when I get a chance. I'll ask you if I have anything specific.

**Comment by kazk** [comment]
Deployed the fix. If this still happens, please let me know by commenting on #690.
