### ISSUE TITLE
Can run tests, can't submit. "Failed to send to server. Check your internet connection." Connection stable.

### ISSUE THREAD

**Issue by LordKahra** [Codewars/codewars.com#189]
I've been having an issue with submitting the solution to any problems. I keep receiving the same error about failing to send to the server. This issue happens in IE, Firefox and Chrome, and on an Android tablet using Chrome. This issue happens with multiple kata. I can run tests without issues.

**Comment by CharlonTank** [comment]
same issue on Chrome

**Comment by paultopia** [comment]
I'm having this issue on Safari as well.

**Comment by s2k** [comment]
Similar situation here (OS X 10.11.4 on Safari & Chrome). 
Reloading the page _sometimes_ helps, but right now it's just not working at all.

**Comment by hades31** [comment]
Facing this issue on chrome and firefox.

**Comment by jhoffner** [comment]
The issue was just resolved with a DNS setting update. It may take a few minutes before it propagates.

**Comment by Stuj79** [comment]
I am having this issue at the moment - I am able to run tests (which are passed) but when I hit submit I get "unknown error" and a message flashes up saying "failed to send to server. Check your internet connection" - my connection is fine.

Any idea how to resolve this issue? Many thanks
