### ISSUE TITLE
Language skills not updated after approved translation

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#1893]
After having an approved Forth translation, Forth is not shown in my trained languages, nor language proficiency. This might be related to #841

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1d2h) by [Unito](https://www.unito.io)

**Comment by nomennescio** [comment]
After explicitly training on the same Kata, my Most Recent changed to Forth, but the number of languages trained did not increase, nor was it listed in my Rank Breakdown

**Comment by nomennescio** [comment]
And mysteriously, my solution does not show up in the Solutions tab of the Kata

**Comment by nomennescio** [comment]
.. this might be due to the delay in stats calculation

Similarly, when forking an existing Forth solution, no stats are updated.

**Comment by nomennescio** [comment]
No, after the global stats calculation, this error persists

**Comment by nomennescio** [comment]
Only after solving a 8 Kye Forth Kata, my language skills were updated to include Forth.

**Comment by FArekkusu** [comment]
If you translate, edit, or (if I'm not mistaking) forfeit a kata at some point, you will not progress in any of the languages which become available in the future. Are you sure you've never edited any of the kata versions before?

**Comment by error256** [comment]
But isn't progress normally counted _for translations_ regardless of having edited the kata?..

**Comment by Steffan153** [comment]
> If you translate

But when I translate a Kata in a language (and it gets approved), I do rank up sometimes, as @error256 said.

**Comment by FArekkusu** [comment]
You definitely won't progress from completing new versions. The whole system is such a mess I don't remember/know how it works. You definitely lose progression-from-completion eligibility but I'm not really sure about progression-from-translating.

**Comment by nomennescio** [comment]
I think the awarding of honor points does indeed work, but this is about language skills/proficiency. Apparently it is messed up. Hence this bug report.

**Comment by nomennescio** [comment]
Did more Forth translations, which were approved, but not a single one added to my Forth proficiency.

**Comment by Steffan153** [comment]
@nomennescio It might be a bug in the Forth language in CW then (if you have earned rank in other languages from translations)...

**Comment by kazk** [comment]
Fixed
