### ISSUE TITLE
Forth kata list is not up to date

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1898]
See title.

**Comment by FArekkusu** [comment]
> See title.

Could you *actually* explain what your problem is? When filtering by `Language: Forth` I can see both katas which support it.

**Comment by g964** [comment]
Yes, but it should be 3 for the moment: the two you can see + <https://www.codewars.com/kata/56fe17fcc25bf3e19a000292>.

**Comment by g964** [comment]
Now 4; the preceding ones + <https://www.codewars.com/kata/567501aec64b81e252000003/> but this last is too recent to be on the list.

**Comment by g964** [comment]
I re-edit and now they appear.
