### ISSUE TITLE
Can't sign up with github account

### ISSUE THREAD

**Issue by or** [Codewars/codewars.com#19]
The authorization on github's side worked, but then coming back only yields "Failed to connect account" if I click on "Link Your GitHub Account" again.

Could it be the length of my account? Maybe codewars has a minimum >= 3?

**Comment by jhoffner** [comment]
Yeah the minimum length is currently set to 3. I'm trying to remember if there was a specific reason why we set that.

**Comment by dbjranger** [comment]
jhoffner,

Is there an issue with signing up for code wars?

**Comment by RisnD21** [comment]
still cant sign up, everytime I 
[ press "enlist", the site just refresh, and turn out I need to re-insert email address ] <--- loop

**Comment by dantb** [comment]
I'm having exactly the same problem as @RisnD21 

Does anyone have a solution for this? (Using google chrome if that matters)

**Comment by Shin8** [comment]
Same here. The page just refreshes, the form is still there with the data but nothing happens.

**Comment by risto987** [comment]
+1 
It just refresh, you can't sing up.

**Comment by Shin8** [comment]
I was able to create an account with some help! I was trying to create it with firefox but nothing worked, but it finally did when I tried it with Google Chrome.

**Comment by risto987** [comment]
I also switch the browser, on Chrome doesn't work but on Mozilla it work!

**Comment by sevo1** [comment]
doesn't work for me in chrome, safari, firefox
