### ISSUE TITLE
Different language version is used from what's selected for unfinished solution

### ISSUE THREAD

**Issue by error256** [codewars/codewars.com#1909]
I had an unfinished solution in an older version of Rust (not sure if it was 1.33 or 1.25). When I reopened it, the selector showed 1.36, but the tests were executed in some older version until I reselected 1.36, then everything worked correctly.
A couple of days ago I had the same issue with Elixir. There was only 1.9 in the UI, but the tests were executed in an older version, I think 1.2 because `chunk_every` didn't work. When I reselected 1.9, everything worked.

**Comment by kazk** [comment]
This should be fixed now.

**Comment by error256** [comment]
It happened again. After opening an old unfinished solution, by switching from Ruby "2.5.0" (which actually is 2.5.4) to "3.0.0" I got 2.3.6. After reloading the page it became 3.0.0.
