### ISSUE TITLE
Introduction JS kata broken

### ISSUE THREAD

**Issue by MartinMuzatko** [Codewars/codewars.com#191]
When trying to get into codewars, I get the following error in this kata:
http://www.codewars.com/?language=javascript

Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated.

**Comment by kazk** [comment]
I closed this because it's been a long time and things have changed a lot. If you're having the same issue, please open a new issue with some details.
