### ISSUE TITLE
500 error instead of kata

### ISSUE THREAD

**Issue by pavel-voronin** [Codewars/codewars.com#1912]
#### Describe the bug

I got 500 error trying to open specific kata page OR searching this kata in library.

#### To Reproduce

1. Go to https://www.codewars.com/kata/decode-the-morse-code-for-real
2. Get 500 error

OR

1. Go to Library
2. Search "Morse"
3. Get 500 error

#### Expected Behavior

I can read my solved kata solution and other warriors solutions.

#### Contexts

- Codewars username (if account related): pavel-voronin
- Kata is solved

**Comment by kazk** [comment]
Thanks, some data for this specific kata seems corrupted.

**Comment by kazk** [comment]
Fixed
