### ISSUE TITLE
Test suite of this kata is wrong

### ISSUE THREAD

**Issue by qamar2** [Codewars/codewars.com#1913]
The test suite of the following Kata is wrong:
[](https://www.codewars.com/kata/common-denominators/train/scala)
https://www.codewars.com/kata/common-denominators/train/scala
It says:

Testing: [(69, 130), (87, 1310), (30, 40)]
Actual: (36156,68120)(4524,68120)(51090,68120)
Expect: (18078,34060)(2262,34060)(25545,34060)

But 34060 is not a common denominator because: 34060 / 40 = 851.5

**Comment by Voileexperiments** [comment]
This repo is not for questions/issues about individual katas. They should be raised at the kata's discourse.

Also you're wrong. Read the task again.
