### ISSUE TITLE
Provide ABAP as new programming language

### ISSUE THREAD

**Issue by steffenschloenvoigt** [Codewars/codewars.com#1915]
It would be great to have some Katas also available for ABAP so that those enterprise developers can train and prove their knowledge, too.

**Comment by DonaldKellett** [comment]
You should raise a language request at https://github.com/Codewars/codewars-runner-cli instead.

**Comment by steffenschloenvoigt** [comment]
Thanks. I just created https://github.com/Codewars/codewars-runner-cli/issues/763
