### ISSUE TITLE
Language version exists after a translation but does not show up when filtered by language in kata search

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1917]
I wrote and approved the Forth translation [to my kata](https://www.codewars.com/kata/become-immortal/forth) around 3 hours ago.

The kata search page shows that the kata has a Forth version: 
![image](https://user-images.githubusercontent.com/14909989/63573050-ec425280-c5b6-11e9-9b3b-fb6ec3046e5f.png)

But filtering by language Forth only does not show the result:
![image](https://user-images.githubusercontent.com/14909989/63573078-fcf2c880-c5b6-11e9-8e52-492108817c53.png)

Is there some kind of caching? Or is it related to #1730 again?

**Comment by kazk** [comment]
Looks like the search index failed to update for some reason. I just updated and it appears now.
