### ISSUE TITLE
You can edit a kata that you don't have enough rank to forfeit and haven't solved

### ISSUE THREAD

**Issue by Steffan153** [codewars/codewars.com#1919]
#### Describe the bug
On a kata that you don't have enough rank to forfeit, you can still edit the kata (=> forfeit through the edit button, or even actually edit it).

e.g. I'm 3 kyu, so if I wanted to see the solution to a 1kyu then the edit button will give me the solution :trollface:

#### To Reproduce

1. Go to a kata you don't have enough rank to forfeit (and you haven't solved it)
2. Click on Edit Kata
3. Muhahaha, there's the solution.

#### Expected Behavior

You can't edit a kata you haven't solved and don't have enough rank to forfeit.

#### Screenshots

![DeepinScreenshot_select-area_20190823083022](https://user-images.githubusercontent.com/40404519/63600429-cac67400-c580-11e9-8971-0525f929a2bb.png)

**Comment by kazk** [comment]
Fixed
