### ISSUE TITLE
Output formatting with Clojure "testing" marco

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#192]
When the "testing" macro is used, success/failure messages become gray rather than green/red.
![testing](https://cloud.githubusercontent.com/assets/5375100/10372529/dfbba56a-6df0-11e5-9687-dd3eb118d995.png)

**Comment by kazk** [comment]
@error256 Do you have any code that I can try to see how the output looks like now?

**Comment by error256** [comment]
https://www.codewars.com/kumite/5615305c349c0a7634000108?sel=5ae2dfbf8a29a0a3f40000fd
It works correctly now.
