### ISSUE TITLE
Language NASM page should including information on input/output format

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1922]
https://github.com/Codewars/codewars.com/wiki/Language-NASM

I'm looking at this and there are no information how are inputs/outputs handled. Which registers contain the input arguments? What is their layout? `edi`, `esi`, then...? What if there are more than 4 arguments? Are they stored on the stack? How big is the stack? Similarly, where should the output be stored?

There is an example but it's not illustrative, and it is not sufficient as definition.

**Comment by kazk** [comment]
I just fixed the example to use 64 bit registers. For more information, see https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI and https://wiki.osdev.org/System_V_ABI#x86-64 .

**Comment by kazk** [comment]
I found a nice tutorial series https://github.com/0xAX/asm . It uses NASM on Linux so it should be very similar. The first one is https://0xax.github.io/asm_1/

I don't think there's anything specific to the runner, but let me know if you need more information.

**Comment by error256** [comment]
I think the ABI doesn't guarantee that higher bits of 32-bit operands in 64-bit registers are zeros, although C compilers usually do so. It doesn't affect the result in the wiki addition example, but in general 32-bit registers should be used for ints.

**Comment by kazk** [comment]
Thanks, I reverted and added comment. Feel free to add anything helpful on that page.
