### ISSUE TITLE
Minimum satisfaction percent for white and yellow kata was reverted to old value

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1924]
[This kata](https://www.codewars.com/kata/alphabetical-addition) is at 84% satisfaction rate with >30 votes. However it still shows `Beta Status: Testing & feedback needed`. Hasn't the satisfaction rate requirement for white/yellow katas lowered to 80% since a long time ago?

**Comment by Voileexperiments** [comment]
> so it needs at least 85% rating from 10 users

That's the old requirement I'm talking about. It was changed to 80% at some point because requiring 90% for white katas means it's hopeless for white katas to get approved. Did it change back to the old criteria again?

**Comment by kazk** [comment]
This was reverted and the beta status for existing kata are updated. I've also fixed the documentation.

**Comment by Voileexperiments** [comment]
@kazk 

> Do you remember where it was discussed?

Just found it: https://github.com/Codewars/codewars.com/issues/1174#issuecomment-337033106
