### ISSUE TITLE
Option unavailable to update payment information in Account Settings

### ISSUE THREAD

**Issue by docgunthrop** [codewars/codewars.com#1926]
At the moment, there isn't a way to update payment information (for Codewars Red) in the Account Settings page on the Codewars website. If a user gets an updated credit card, for example, they wouldn't be able to update that if they wanted to renew.

**Comment by benpitman** [comment]
I'm giving this a bump because in order to find out which back account I subscribed with, and the amount that is withdrawn, I had to trawl through the transaction history over three cards for the past six months. Quite annoying.

**Comment by kazk** [comment]
I'm looking into updating Stripe integration so I'll look into this as well.

**Comment by benpitman** [comment]
Sweet, thank you.

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/83681330-1d64a000-a597-11ea-8c1e-669d5c9d358c.png)

You can get to this new subscription management page from Account Settings. Clicking UPDATE will take you to Stripe Checkout and you can securely update your payment method there.
