### ISSUE TITLE
Unable to post an Issue on a Kata

### ISSUE THREAD

**Issue by solaristhesun** [Codewars/codewars.com#1930]
#### Describe the bug
I'm unable to post an issue on a kata. From previously reports I learned that this might be related to not confirming the email address. I also don't have any email to confirm. I don't remember if I confirmed anything or not.

#### To Reproduce
Post issue on kata.

#### Expected Behavior
Issue gets posted.

#### Screenshots
n/a

#### Contexts

Please complete the following information:

- username: solaristhesun
- OS: Linux
- Browser: Chrome
- Browser Version: 75

**Comment by Voileexperiments** [comment]
It's a known issue (#1814). You need to check for confirmation email at the email address specified by your account information.

**Comment by solaristhesun** [comment]
There is no email from codewars in my mailbox.

**Comment by DonaldKellett** [comment]
@solaristhesun Maybe try checking your spam folder?

**Comment by solaristhesun** [comment]
I already did that before opening this issue. There is no email from codewars in my mailbox (including the spam folder).

**Comment by kazk** [comment]
@solaristhesun I just added a button to resend confirmation email in account settings if the user haven't confirmed their email. This should be shown for your account because your email is not confirmed. Can you try it?

![image](https://user-images.githubusercontent.com/639336/64304320-4e4c7180-cf40-11e9-954c-3f48dc299e7e.png)

**Comment by solaristhesun** [comment]
Thanks kazk. It works.

**Comment by kazk** [comment]
Thanks for confirming :)

**Comment by Manuel-heav** [comment]
I am having the same error, but my email is already confirmed

**Comment by kazk** [comment]
@Manuel-heav What's your Codewars username? Also, which kata?
