### ISSUE TITLE
Add option for re-sending confirmation email for unverified Codewars accounts

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1931]
On top of the suggestion made by various Codewarriors in #1814 to show a relevant error message asking the Codewarrior to confirm his/her email address if a comment cannot be posted due to an unverified email address, perhaps we could also add an option (e.g. some sort of button in "Account Settings" or similar) for such Codewarriors to re-send a confirmation email in case it was accidentally deleted or the email failed to send for whatever reason (which is what I suspect might've happened in #1930 )?

**Comment by kazk** [comment]
The error message not showing up is caused by the general issue where the error is not handled well by the front end so it'll get fixed when that's fixed.

I'll add a button to resend confirmation email in account settings.
