### ISSUE TITLE
Comment upvote/downvote buttons are misplaced

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1933]
The comment upvote and downvote buttons are misplace on all pages. Yesterday everything was right, and a few hours ago when I was using a PC with a different screen it looked normal too.

![image](https://user-images.githubusercontent.com/31668662/64284129-89ab6800-cf61-11e9-871b-3bfd59e7fca3.png)

**Comment by kazk** [comment]
I can't reproduce it and I can't think of any cause. Nothing was deployed in the past few hours. The last deployment was about 20 hours ago.

**Comment by FArekkusu** [comment]
It *looks like* there's not enough space for the downvote button or something. When I remove the vertical bar in HTML, the arrow returns to its original place, and when I set the `li` width to a higher value like `100px` it rearranges correctly.

**Comment by kazk** [comment]
> Could it be that an HTML template was modified by somebody or automatically during the deployment?

I don't think so, the change was just adding Factor language (just adds few files to support it, CSS file was modified only to add the language icon and it's in separate file) and I don't see how that can break comments.

If it was the deployment, you should've experienced this earlier (you wrote few hours ago it was fine). Also, I can't reproduce it like I wrote above.

Anyone else having this problem? If so, I can try clearing the cache and see if it changes anything.

**Comment by kazk** [comment]
@error256 @Voileexperiments @DonaldKellett @Steffan153 (anyone else that was active the past few days) are you experiencing this issue?

**Comment by Steffan153** [comment]
Everything has been fine for me.

**Comment by DonaldKellett** [comment]
> @error256 @Voileexperiments @DonaldKellett @Steffan153 (anyone else that was active the past few days) are you experiencing this issue?

Just randomly checked the Discourse section of three Kata; no anomalies found.

**Comment by error256** [comment]
I haven't seen this either.

**Comment by g964** [comment]
I have this problem (downvote button below; with Google Chrome).

**Comment by FArekkusu** [comment]
Just checked using the other computer I mentioned - the problem is present here as well. It could be that I visited CodeWars at some point yesterday but didn't check any comment sections, and didn't notice the issue.

> I have this problem (downvote button below; with Google Chrome)

I'm using Google Chrome as well.

**Comment by Steffan153** [comment]
Now I can reproduce
![DeepinScreenshot_select-area_20190906212805](https://user-images.githubusercontent.com/40404519/64469349-b8eee000-d0ed-11e9-9660-2bccec2e58a9.png)

**Comment by Steffan153** [comment]
Workaround:
In https://www.codewars.com/assets/application-3d144953095aa7f00da44d58ed9237ee147f3c022c0439e61d19c1191c45e713.css:
In `.comments .voter`, `margin-right` should be `0` instead of `-4px`.

**Comment by kazk** [comment]
Thanks, I'll do that. Hopefully this doesn't break anything else. I still have no idea what caused this.

**Comment by kazk** [comment]
Deployed the fix

**Comment by Steffan153** [comment]
Nice! All good now :smile:
