### ISSUE TITLE
undefined method `username' for nil:NilClass

### ISSUE THREAD

**Issue by lostbearlabs** [Codewars/codewars.com#1937]
#### Describe the bug
The server returns 500 with the message 
```
Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

--------

undefined method `username' for nil:NilClass
```
when trying to view a page.

#### To Reproduce

I have seen this multiple times today trying to view the URL https://www.codewars.com/kata/55e2adece53b4cdcb900006c/train/haskell while logged in.

Since it referenced username, I tried logging out and back in;  it made no difference.

#### Expected Behavior

The kata should be displayed.

#### Contexts

- Codewars username (if account related): lostbearlabs
- OS: macOS
- Browser: safari
- Browser Version: 12.1.2

**Comment by andrew-qio** [comment]
Similar to #1934
