### ISSUE TITLE
JS: Array.fill() not working

### ISSUE THREAD

**Issue by scheffield** [Codewars/codewars.com#194]
Hi,

the following code works using `babel-node` on my local machine:

```
var largeArray = Array(1000).fill(0);
```

But on codewars this seems to create an array filled with `undefined`.

**Comment by shershen08** [comment]
I am gettting ```TypeError: Object ... has no method 'fill'```

**Comment by GiacomoSorbi** [comment]
Not the best workaround, maybe, but try this one instead:

```
new Array(1001).join("a").split("").map(a=>0);
```

**Comment by caycek** [comment]
is this still supposed to be happening?? The above helps, but it would be really cool to use fill instead.

**Comment by javatlacati** [comment]
@jhoffner  this doesn't has to be on the [codewars runner cli](https://github.com/Codewars/codewars-runner-cli) repo as issue?

**Comment by kazk** [comment]
Confirmed this using Node v0.10.33/Babel, but closing because Node v6 is available now.
We should also start looking into removing Node v0.10.x as it reached end-of-life status on 2016-10-31. [nodejs/LTS](https://github.com/nodejs/LTS).
