### ISSUE TITLE
Can't post any comment

### ISSUE THREAD

**Issue by mercenarychaos** [Codewars/codewars.com#1940]
#### Describe the bug
I can't post any comment, be it spoiler or not, a reply or not, ...
Clicking the button makes the loading bar appear for a second then nothing happens.

When I check the console, I see:
NS_ERROR_NOT_INITIALIZED: vendor.a9cf4ba8.js:1
    m vendor.a9cf4ba8.js:1
    sentryWrapped helpers.ts:85
thrown everytime I move my mouse.

I tried firefox and chrome on windows 7 and android 9.
I've had the problem since the beginning but never really bothered commenting before so I didn't take the time to make an issue.

#### To Reproduce
"Click the reply button"
I'm guessing reproducing it would be difficult.

#### Expected Behavior
I was expecting to be able to post comments.

#### Screenshots
![Capture](https://user-images.githubusercontent.com/16540115/64874077-a115df80-d64a-11e9-8155-eb231193e5b5.PNG)

#### Contexts

- Codewars username: MercenaryChaos
- OS: Windows 7 / Android 9
- Browser: Firefox / Chrome
- Browser Version: Firefox 69.0 / Chrome 77.0.3865.73

**Comment by Steffan153** [comment]
This issue has already been raised many times. This means you have not confirmed your email address.

**Comment by mercenarychaos** [comment]
Okay thanks.
The few issues like this I found were closed without solution.
