### ISSUE TITLE
Training Setup - Save unresponsive

### ISSUE THREAD

**Issue by andrewtuplin** [Codewars/codewars.com#1941]
#### Describe the bug
https://www.codewars.com/trainer/setup

When I enter this screen, I have two languages selected: C# and JavaScript. When I change these options and press the save button, nothing happens (tested in both Chrome and Edge browsers). 

#### To Reproduce

1. Go to https://www.codewars.com/trainer/setup
2. Click on Any Language Icon 
3. Scroll down to 'Save
4. See error: Nothing happens. 

#### Expected Behavior

Changed language options have been saved. 

#### Contexts

Please complete the following information:

- Codewars username (if account related): Tups
- OS: Windows 10
- Browser: Chrome, Edge
- Browser Version: Chrome: 76.0.3809.132

**Comment by kazk** [comment]
I can't reproduce with Chrome and Firefox. If this problem is still happening, can you check if anything is shown in the console? If any requests are made, can you check what the response looks like?
