### ISSUE TITLE
Users who have not solved a beta kata should not be able to approve the kata

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1945]
Related to #1944, because apparently I found that this user was just straight out approving katas *without even solving it*. Yup, not even submitted a solution for the kata. That endpoint returns `{"success":true,"solution":null,"completed":false}`.

Obviously this is a very, *very*, **very** bad idea.

**Comment by Steffan153** [comment]
This is the outcome of https://github.com/Codewars/codewars.com/issues/1919 :wink:

**Comment by kazk** [comment]
Fixed
