### ISSUE TITLE
Enable usage of external libraries

### ISSUE THREAD

**Issue by monterinio** [Codewars/codewars.com#1946]
**Summary**
Enable option to choose/switch between different set of libraries for a given language.

**Motivation**
There are many prime libraries out there in the Web. Learning them is not an easy journey for every developer, no matter how experienced he/she is. Codewars introduces a great way to learn  intricacies of a language by solving different kind of computational/algorithmic problems.  However, basic in-build language libraries are often not enough, especially when working in commercial projects. Let's extend Codewars functionality to let developers learn libraries by actually using them.

**Description**
In the near of a language and its version dropdown introduce a button to select libraries which API should be accessible in a given Kata. For Java that could be: apache commons, google guava, vavr.io etc., for Javascript that could be: Lodash, ... etc.

This request does not intend to provide access to every possible library which exists. First and foremost, available libraries should provide **utility functions for common programming tasks**. Usage of all other libraries is strongly discouraged.

Second selection factor could be a popularity of a library, just to avoid usage of all legacy, not supported or not popular ones.

**Non-Goals**

- usage of frameworks,

- usage of ORMs,

- usage of logging libraries,

**Comment by kazk** [comment]
You can request packages for each language by opening an issue on https://github.com/Codewars/codewars-runner-cli . There's a template for package request. It can be added if the request is reasonable or there's enough demand.

You can already use lodash in JavaScript, some Apache commons and Guava in Java. See the wiki pages for installed packages.

We don't have any plans to add drop down, but the authors can restrict access to some libraries to some extent by inspecting the solution file.
