### ISSUE TITLE
Failed to connect account using Github

### ISSUE THREAD

**Issue by giovannixdev** [Codewars/codewars.com#1947]
I am trying to sign up using my GitHub account and when I click "Link your GitHub account" I receive this error 
Failed to connect account

Steps to reproduce:

Click Sign Up
Click JavaScript
Complete task
Click Link Your Github Account
Failed to connect account

I tried to find a solution using different browsers (Chrome, Firefox, and Safari) and I also went to GitHub settings and I revoked codewars as Authorized OAuth Apps a few times and I tried the steps above again and No luck. 
Could someone @ codewars reset my account (my GitHub @giovannixdev) "maybe something got stuck half the way during the creation of my new account" using my GitHub username?

**Comment by kazk** [comment]
Did you sign up in July? https://www.codewars.com/users/giovannixdev
Can you try signing in instead of signing up?

**Comment by giovannixdev** [comment]
Hi @kazk, I can't signing in either. I get this message 
GitHub account is not linked to an existing Codewars user.
Could you reset my account to start from scratch?

**Comment by kazk** [comment]
I don't have the time to look into the data issue right now, but you should be able to send an email to reset password and log in using that. Can you try that first and let me know?
Once you're logged in, you should be able to reset GitHub account in settings.

If this doesn't work, I'll try looking into it later.

**Comment by giovannixdev** [comment]
I sent 2 email's already to info@codewars.com with all the information and screenshots and I have been waiting for a response for weeks. 
I don't need to reset the password. My issue is that I can't signing in using my GitHub account. At this point please delete my account when you are available so I can create a new account using my Github account. Thanks!

**Comment by kazk** [comment]
I'm sorry no one responded, but I have no access to that email. Issues are tracked here.

> I don't need to reset the password. My issue is that I can't signing in using my GitHub account.

I asked you to try it because you should be able to re-link GitHub account yourself after logging in with the password reset email. From there, you should be able to log in using GitHub account.

If you decide to try it, post a comment here with the results. Otherwise, I'll delete your account and close this issue later when I can.

**Comment by giovannixdev** [comment]
Hi, @kazk I have tried that too and no luck. Yes please delete my account when you are available so I can create a new one with my github account. Thank you very much!

**Comment by kazk** [comment]
Deleted the account
