### ISSUE TITLE
Cannot post a question for kata "sum-of-digits-slash-digital-root" 

### ISSUE THREAD

**Issue by SilvercutYaz** [Codewars/codewars.com#1950]
It tries to load, the red loading bar gets to 1/4 of the way and then it freezes and stops.

Is there any reason for this?

Thanks

**Comment by hobovsky** [comment]
Maybe #1814  / #1930 ?

**Comment by Steffan153** [comment]
See the threads @hobovsky mentioned.
(i.e. go to your account settings and check if your email is confirmed :wink:)

**Comment by kazk** [comment]
Please confirm your email by going to Account Settings.
