### ISSUE TITLE
Solution fork is always locked to the test suite when it was first created

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1951]
Forking a solution creates a "phantom kumite" (#908), which is already weird in the first place. But the real issue is, trying to fork the same solution the next time will always use the one created in the past instead of creating a new one, effectively locking it from updated test suite from the user. It also potentially locks users from accessing test preloaded code since forking a solution is the only way to view it at the moment (#1585), and not every user can edit the kata to see it (especially if kata is not open for "edit by contributors").

**Comment by kazk** [comment]
This was fixed earlier this year.
