### ISSUE TITLE
Unable to View Run Output - Swift

### ISSUE THREAD

**Issue by codeman869** [Codewars/codewars.com#1954]
#### Describe the bug

I have authored a swift translation for a kata and am unable to view the run output. Here is a link to the [kumite](https://www.codewars.com/kumite/5d966330dcf4d60025470eb5?sel=5d966330dcf4d60025470eb5). I am able to view the run output for other translations of the same kata [Example Here](https://www.codewars.com/kumite/5bbb36e2528b2992c500007a?sel=5bbb36e2528b2992c500007a). I have tried recreating the translation a few times and I still cannot see any output when clicking this link. Code for solution & testing works in an online REPL and I have no issues running the code and seeing the expected output when I am editing the translation.

#### To Reproduce

Navigate to the translation and near the bottom of the page, click "View Run Output" link.

#### Expected Behavior

Output from running the tests

#### Screenshots

Here is the output when run from the Edit Kumite screen

![swift-kumite](https://user-images.githubusercontent.com/10450602/66346902-071f1b00-e908-11e9-97d3-49a716f58d1c.png)

**Comment by kazk** [comment]
Something is really weird :( You have 4 copies and are all in `draft` state.

- https://www.codewars.com/kumite/5d966330dcf4d60025470eb5?sel=5d966330dcf4d60025470eb5
- https://www.codewars.com/kumite/5d9b5c90ad5cec80e70c6226?sel=5d9b5c90ad5cec80e70c6226
- https://www.codewars.com/kumite/5d9b6dac2aec73001a006d61?sel=5d9b6dac2aec73001a006d61
- https://www.codewars.com/kumite/5d9b84f6e0aad7000e543dd8?sel=5d9b84f6e0aad7000e543dd8

**Comment by Steffan153** [comment]
@kazk: When I created a Swift translation myself, it worked fine. But when @codeman869 did it, it did the same thing, also when forking mine. :confused: Could it be an account issue?

**Comment by kazk** [comment]
@Steffan153 Maybe it's account related if this happens again for some other translation.

@codeman869 Can you tell me the steps you took when forking @Steffan153's translation? Did you change something, click Save, and then click _Publish_? If you did click Publish, can you try again and tell me what happens (e.g., does it show any error or does it show anything in console)?

"View Test Output" does nothing when the translation is not published (should probably hide that to avoid confusion).

**Comment by codeman869** [comment]
@kazk it looks like an issue with my ability to publish when I use this browser (Firefox Developer Edition) - I have some custom settings turned on which may cause this that didn't occur to me at the time. I was able to get it to work by publishing on a base installation of Chrome. I think we can close this out for now.
