### ISSUE TITLE
undefined method `username' for nil:NilClass

### ISSUE THREAD

**Issue by akharkhonov** [Codewars/codewars.com#1956]
Link: https://www.codewars.com/kata/55e2adece53b4cdcb900006c/train/haskell

Message: undefined method `username' for nil:NilClass
![Screen Shot 2019-10-17 at 3 03 34 PM](https://user-images.githubusercontent.com/47464417/67007083-4eb75b00-f0ef-11e9-8193-5baa42172647.png)

**Comment by kazk** [comment]
This should be fixed.
