### ISSUE TITLE
Markdown for links display incorrectly in Kata Description

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1958]
I'm currently authoring the description for a new Kata and just stumbled upon what looks like a Markdown bug.

Markdown code:

```markdown
If you enjoyed this Kata, don't forget to check out the following Kata collections/series as well:

- [Verified Sorting Algorithms](https://www.codewars.com/collections/verified-sorting-algorithms)
- [Program Verification](https://www.codewars.com/collections/program-verification) (author: [@monadius](https://www.codewars.com/users/monadius))
- [Verified algorithms](https://www.codewars.com/collections/5d0e575208985f000f6e5671) (author: [@dramforever](https://www.codewars.com/users/dramforever))
```

Expected output:

<p>If you enjoyed this Kata, don't forget to check out the following Kata collections/series as well:</p>

<ul>
  <li><a href="https://www.codewars.com/collections/verified-sorting-algorithms">Verified Sorting Algorithms</a></li>
  <li><a href="https://www.codewars.com/collections/program-verification">Program Verification</a> (author: <a href="https://www.codewars.com/users/monadius">@monadius</a>)</li>
  <li><a href="https://www.codewars.com/collections/5d0e575208985f000f6e5671">Verified algorithms</a> (author: <a href="https://www.codewars.com/users/dramforever">@dramforever</a>)</li>
</ul>

Actual output (at least in the description preview provided in the Kata Editor):

![螢幕截圖 2019-10-19 14 00 37](https://user-images.githubusercontent.com/7777884/67138615-d9779180-f278-11e9-83ba-2a87981ca4f5.png)

**Comment by kazk** [comment]
Looks like the parser is mistaking

```markdown
[Program Verification](https://www.codewars.com/collections/program-verification) (author: [@monadius](https://www.codewars.com/users/monadius))
```
as
```markdown
[Program Verification](https://www.codewars.com/collections/program-verification) (author: [@monadius](https://www.codewars.com/users/monadius))
 --------------------  ---------------------------------------------------------- -------------------------------------------------------------
     Link Text                          Link Destination                                                Link Title
```

I'll try updating the commonmark package.

For now, you can workaround by adding a backslash to the last parenthesis.
```markdown

[Program Verification](https://www.codewars.com/collections/program-verification) (author: [@monadius](https://www.codewars.com/users/monadius)\)
```

**Comment by kazk** [comment]
Fixed by updating the markdown package.
