### ISSUE TITLE
problem in "Easy SQL: Convert to Hexadecimal"

### ISSUE THREAD

**Issue by rzp789** [Codewars/codewars.com#1960]
The game doesn't understand the function "hex(N)" it tells me this function doesn't function with an integer and the same with "convert()", that's it's a real problem to resolve.
https://www.codewars.com/kata/easy-sql-convert-to-hexadecimal/discuss

**Comment by FArekkusu** [comment]
You do realize that there're different RDBMS which have different functions with different names, and the code written for MySQL(?) on your computer may not work in PostgreSQL on CW?

**Comment by kazk** [comment]
The linked kata is for Postgres and `HEX` doesn't exist in Postgres.
