### ISSUE TITLE
Sum of Digits

### ISSUE THREAD

**Issue by rostaryms** [Codewars/codewars.com#1961]
I'm trying to write a function that given an integer, sums the digits of that integer, then sums the digits of that number, and repeats this cycle until the remaining number is a single digit number. The function then returns the single digit number. Does anyone know why this code isn't working? Thanks!

`def digital_root(n):
    new_num = n
    #for integ in n:
    #    new_num += integ
    numstr = str(new_num)   
    while len(numstr) > 1:
        num_place = new_num
        int_sum = 0
        for integ in num_place
            int_sum += integ
        new_num = int_sum
        numstr = str(new_num)
    
    return new_num`

**Comment by rostaryms** [comment]
Not sure why the code is like that but here it is together:


def digital_root(n):
    new_num = n
    #for integ in n:
    #    new_num += integ
    numstr = str(new_num)   
    while len(numstr) > 1:
        num_place = new_num
        int_sum = 0
        for integ in num_place
            int_sum += integ
        new_num = int_sum
        numstr = str(new_num)
    
    return new_num

**Comment by kazk** [comment]
Please use the discuss page for the kata.

When you post your code, use Markdwon

````
```python
def digital_root(n):
    return n
```
````
which will be rendered like
```python
def digital_root(n):
    return n
```

and don't forget to mark the comment as having a spoiler.
