### ISSUE TITLE
Edits are ignored in kata editor

### ISSUE THREAD

**Issue by mvhv0** [Codewars/codewars.com#1962]
What i did:

- published a kata
- edited kata function name and re-published it

expected:
   - name changed on initial and example tabs

actual: 
   - in editor name changed on all tabs as expected
   - on actual kata: name changed on examples, but stays intact on initial tab
     so it seems there is at least two different versions of kata saved on site
   - and now i cannot edit test cases too with same issues

link to a specific kata i try to publish:
https://www.codewars.com/kata/zombie-apocalypse-the-last-number-standing/

**Comment by FArekkusu** [comment]
Have you tried to reset the trainer?

**Comment by kazk** [comment]
You probably have the previous version saved as work in progress solution. The correct function `survivor` should show if you reset.

**Comment by mvhv0** [comment]
Yep, "reset" did work. Sorry for fuss.
