### ISSUE TITLE
Subscription Failure

### ISSUE THREAD

**Issue by Fibonaccios** [Codewars/codewars.com#1965]
Wanted to subscribe for Codewars Red but i was getting this error:
Subscription failure: Invalid string: {"id"=>"to...=>"false"}; must be at most 500 characters

**Comment by kazk** [comment]
I just deployed a fix. Can you try again?

**Comment by Fibonaccios** [comment]
Thanks kazk, I was able to subscribe this time.
I am learning so much for free from codewars and I wanted somehow to
contribute.
The bad thing is that I am addicted to it now and I need  to focus on my
university a bit hahah.(Uni stuff so so boring)
Thanks for your assistance and have a good day.

Leo

**Comment by Fibonaccios** [comment]
Resolved
