### ISSUE TITLE
Can't comment on kata solutions - {"message":"You do not have access to this resource"}

### ISSUE THREAD

**Issue by rasnick** [Codewars/codewars.com#1967]
#### Describe the bug
After solving a kata, a page with different kata solution methods appear. I try to add a comment to any of them but the comment is not posted. From the network tab I see the message "You do not have access to this resource".
[Privileges wiki](https://github.com/Codewars/codewars.com/wiki/Privileges) shows no "Comment" privilege, so I expect to be able to comment (I have 43 honor).

#### To Reproduce

1. Solve a kata, get a redirect to [kata solution page](https://www.codewars.com/kata/5388f0e00b24c5635e000fc6/solutions/javascript)
2. Click on comment icon to post a new comment.
3. Type the comment and press on ```POST``` button
4. Loading bar appears at the top of the site. Loading bar completes and nothing happens on the UI. From the Network tab I get {"success":false,"message":"You do not have access to this resource"} 

#### Expected Behavior

I would expect the comment to be posted. But it seems like I don't have permission to do so.

#### Screenshots

![image](https://i.imgur.com/7GtqIHv.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): rasnick
- OS: Windows 10 1903
- Browser: Firefox
- Browser Version: 70.0.1 (64-bit)

**Comment by DonaldKellett** [comment]
Probably because you haven't confirmed your email ( #1814 ).  Try going to your Account Settings to resend the confirmation email and confirm your account.

**Comment by rasnick** [comment]
That was indeed the issue. Didn't know I wasn't confirmed. Probably want to prompt the message (if email is not confirmed) as an alert/warning message somewhere else more frequently visited.
Thanks.
