### ISSUE TITLE
Complete some tests using magic methods

### ISSUE THREAD

**Issue by Neranss** [Codewars/codewars.com#1972]
Please open an issue at [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli/issues) repository.
For example:
In The Millionth Fibonacci Kata use:
class Eq:
    def __eq__(self, _):
        return True
    def __add__(self, _):
        return self
    def __mul__(self, _):
        return self
    def __div__(self, _):
        return self

def fib(n):
    return Eq()

**Comment by DonaldKellett** [comment]
Looks like a typical monkey-patching cheat to me.  Note that Codewars admins are well aware of the existence of such cheats but do not attempt to prevent them all from passing. Instead, cheaters found to abuse such cheats in Kata will have their solutions marked as cheat and their rank/honor deducted accordingly. Repeat offenders may simply be banned permanently, i.e. their rank set to `8 kyu` and honor set to `0` with no way of renaming/deleting the offending account.

Please refrain from submitting (or even trying out!) such cheats on any other Kata you may encounter in the future if you do not wish to be banned. In general, you should *never* attempt to interfere with any testing framework used on Codewars, nor should you try to terminate test execution prematurely.

**Comment by hobovsky** [comment]
#1970
