### ISSUE TITLE
The kata failed to load. Please try reloading the page.

### ISSUE THREAD

**Issue by copperwye** [Codewars/codewars.com#1973]
#### Describe the bug
For for four days now, I get for every Python kata that I try to train on the message: "The kata failed to load. Please try reloading the page.". I tried chrome and firefox browser as well as different Windows 10 Computer. All with the same negative effect.

#### To Reproduce

Load untrained Python kata and press the >TRAIN button.

#### Expected Behavior

Open the kata in train mode.

#### Screenshots

![kata_failed_to_load](https://user-images.githubusercontent.com/25419449/68697777-d0c86180-057f-11ea-8e7b-121b4a40e4a1.png)

#### Contexts

Please complete the following information:

- Codewars username: CopperWye
- OS: Win10
- Browser:  Chrome: 78.0.3904.97 and Firefox 70.0.1
- Browser Version: see above

**Comment by kazk** [comment]
Can you try after clearing cookies and disabling any extensions?

> For for four days now, I get for every Python kata that I try to train on the message: "The kata failed to load. Please try reloading the page.".

Looks like you were able to submit solution for `Data mining #2` 2 days ago. Did you do anything different?

Do you see anything in console?

**Comment by copperwye** [comment]
The Data mining #2 kata was already opened in training mode a few days before. 
Clearing the cache did not have any effect.
After your suggestion, I found this with the browser developer tools:

Request URL: https://www.codewars.com/users/notifications/unread_popups
Request Method: POST
Status Code: 200 
Remote Address: 104.26.12.79:443
Referrer Policy: strict-origin-when-cross-origin
alt-svc: clear
cache-control: no-cache
cf-cache-status: DYNAMIC
cf-ray: 534dc234d979d417-BUD
content-encoding: br
content-type: text/html; charset=utf-8
date: Wed, 13 Nov 2019 03:46:26 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
referrer-policy: strict-origin-when-cross-origin
server: cloudflare
set-cookie: _session_id=98c47949b852b77d9e1271c387a4f967; path=/; expires=Sat, 16 Nov 2019 03:46:26 -0000; HttpOnly
status: 200
via: 1.1 google
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-rack-cache: invalidate, pass
x-request-id: 0201b33e-5d1d-4023-af84-b722880d8b9f
x-runtime: 0.033549
x-xss-protection: 1; mode=block
:authority: www.codewars.com
:method: POST
:path: /users/notifications/unread_popups
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU4OGUyMTEzMmM3YTI5MjgwNTAwMDBhMiIsImV4cCI6MTU3NDQ4MDc0OH0.skUWv3h6x2LTIA28tRs0ELQAKC0W7u8dDUqITM69s2M
content-length: 243
content-type: application/x-www-form-urlencoded; charset=UTF-8
cookie: __cfduid=d82f599e3daa60d3e5b23f73228d5556e1573616139; _ga=GA1.2.1881604368.1573616139; _gid=GA1.2.674260053.1573616139; gs_v_GSN-087086-V=; remember_user_token=BAhbCFsGSSIdNTg4ZTIxMTMyYzdhMjkyODA1MDAwMGEyBjoGRVRJIhlEaU5GbjY3VWRSc0hHUWlNd254ZgY7AEZJIhcxNTczNjE2MTQ5LjQ3MjMyMDMGOwBG--ab990d16cf6a7868e1ac1ae71105ced232d0c35e; _session_id=98c47949b852b77d9e1271c387a4f967; intercom-session-x27gw54w=MnRzbEJXOEs4bkh1bEFlRjQzM1dRdWZsc2NRQVVHYmwvaDRDK1ZyWFgyekpyUDg5cDY5TXNWZFpmR1FiUDFPcS0teVdXbkFkMW9KR205WDZFREhZU1hodz09--2a2698f1d57f9967c715494e4d6abf33bb444b50; _gat=1; gs_u_GSN-087086-V=30727f4589e177c960510e395520f651:2567:11443:1573616766661
origin: https://www.codewars.com
referer: https://www.codewars.com/kata/simple-interactive-interpreter/train/python
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
x-csrf-token: PzlsMvg++zxnK0TsQetJPUgcmDEoNGSzM8grEVTs2GL4c5SwVgivs8LoMITlODTD2HUOfkegOag0e5Rfp0kRFA==
x-requested-with: XMLHttpRequest
href: https://www.codewars.com/kata/simple-interactive-interpreter/train/python
data[controllerName]: code_challenges
data[errors][0][reason]: Strategy invalid value
data[errors][0][fields][]: strategy

**Comment by kazk** [comment]
Thanks. I think I found the cause.

To confirm, can you try changing the `strategy` on the dashboard ("Fundamentals" in the following screenshot) and try loading some challenge?
![image](https://user-images.githubusercontent.com/639336/68734320-d7aaa080-058e-11ea-848e-56f621d395d9.png)

**Comment by kazk** [comment]
Deployed the fix. Please let me know if this continues to happen.

**Comment by copperwye** [comment]
Your suggestion and the fix worked. I can go to training again :-)
Thank you @kazk!
