### ISSUE TITLE
the compiler does not let me generate the anwser 

### ISSUE THREAD

**Issue by SzymonOzog** [Codewars/codewars.com#1976]
#### Describe the bug
Although the code works just fine in Visual studio(without the additional push_back/pop_back lines)  the compiler somehow dodges the anwser by either adding or removing 2 positions of the vector. The screenshots show exacly how the anwser changes. Kata: https://www.codewars.com/kata/55466989aeecab5aac00003e/train/cpp 
![Capture](https://user-images.githubusercontent.com/36889102/69220238-ca844780-0b74-11ea-9168-b93d5009e566.PNG)
![Capture2](https://user-images.githubusercontent.com/36889102/69220236-c9ebb100-0b74-11ea-9bba-0532a384e0f8.PNG)
![Capture3](https://user-images.githubusercontent.com/36889102/69220237-c9ebb100-0b74-11ea-9042-638277a95b35.PNG)

- OS: [Windows 10]
- Browser: [Chrome]
- Browser Version: [78.0.3904.97]

**Comment by DonaldKellett** [comment]
Kata-specific questions, suggestions and/or issues should be posted in the Discourse section of the Kata in question (i.e. https://www.codewars.com/kata/55466989aeecab5aac00003e/discuss/ in your case) - this repo is for general site issues.

Anyway, in your specific case (as shown in the screenshots), using a variable (`int a`) without first explicitly initializing its value is [undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior) - *some* compilers (e.g. the compiler you are using on your local machine) *might* initialize it to `0` for you but in general, it will just probably contain some garbage value from the last time that memory location was accessed.

**Comment by SzymonOzog** [comment]
Yup, but in VS I don't need to push back another variable to the vector it returns {3,2,1,1} in codewars compiler it returns {3,2,1} and if i try to force it to push another 1 in there (no matter if push_back(a) or push_back(1)) it adds the value twice making it {3,2,1,1,1}

**Comment by hobovsky** [comment]
I just solved the kata in C++ and encountered no problems with it. I checked tests and things seem to be fine.
There's a bug in your solution, add following test case to sample tests and see:
`testequal(SqInRect::sqInRect(3, 5), {3, 2, 1, 1});`

**Comment by SzymonOzog** [comment]
Ok looking at the code now I can see there was an error, but still why did anwser.push_back(a) add two ones to the vector instead of just one?

**Comment by hobovsky** [comment]
`push_back` at line 23 added the value to the vector only once. The other one was not added in this line, but in another (buggy) one.

**Comment by SzymonOzog** [comment]
yet without `push_back` the function returns {3,2,1}

**Comment by hobovsky** [comment]
I think that you are mixing up test results for different test cases. The behaviors described by you as "with `push_back`" and "without `push_back`" are two different tests of your function. You can see that when you add following line in the very beginning of your solution:

`std::cout << lng << " " << wdth << "\n"`;

and check which variant triggers error for what inputs.

**Comment by FArekkusu** [comment]
@SzymonOzog if you don't know what your code is doing, print some message after every line of code, and investigate it from there. And close the issue, it's obviously a problem on your side.
