### ISSUE TITLE
Targetted kata downvoting

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1977]
[Somebody](https://www.codewars.com/users/sneak_attack/completed) went next level: they forfeited(?) all the katas I've authored which are currently in Beta, "completed" them by copy-pasting other solutions to get access to rank/difficult assessment, and then downvoted them:
* [Present JSON data the SQL way
](https://www.codewars.com/kata/present-json-data-the-sql-way/solutions/sql) - [copy-paste](https://www.codewars.com/kata/reviews/5daf550d3a099b000164ff8b/groups/5dd62ae0203d5a00012ede55) of [my solution](https://www.codewars.com/kata/reviews/5daf550d3a099b000164ff8b/groups/5db05bd73a099b0001e2f196)
* [Socialist distribution (performance edition)](https://www.codewars.com/kata/socialist-distribution-performance-edition/solutions/python) - [copy-paste](https://www.codewars.com/kata/reviews/5dd09cb2014ee400015b1d38/groups/5dd6364c0466110001996079) of [lechevalier's solution](https://www.codewars.com/kata/reviews/5dd09cb2014ee400015b1d38/groups/5dd42a44c36e9400019479c8)
* [Total items belonging to the categories on all tree levels](https://www.codewars.com/kata/total-items-belonging-to-the-categories-on-all-tree-levels/solutions/sql) - [copy-paste](https://www.codewars.com/kata/reviews/5da4a997e1cd9d000184bd13/groups/5dcd7b42be0cc40001416104) of zvyta's solution (submitted without changes)
* [Analyzing the sales by product and date](https://www.codewars.com/kata/analyzing-the-sales-by-product-and-date/solutions/sql) - [copy-paste](https://www.codewars.com/kata/reviews/5dac90631944dd0001d4c181/groups/5dbbf9184396c60001f7c6fd) of zvyta's solution (identical again)
* [Readable Specification Pattern](https://www.codewars.com/kata/readable-specification-pattern/solutions/python) - [copy-paste](https://www.codewars.com/kata/reviews/5dc43c128488b800013e5648/groups/5dd65618203d5a00012ee815) of [my solution](https://www.codewars.com/kata/reviews/5dc43c128488b800013e5648/groups/5dc43c128488b800013e564a)
* [Maximize travelled distance](https://www.codewars.com/kata/maximize-travelled-distance/solutions/python) - [copy-paste](https://www.codewars.com/kata/reviews/5c99d5e15ff5590001fc9b42/groups/5d9478fe41c4c00001e90993) of saranya maddikiri's solution (submitted with no changes)

**Comment by FArekkusu** [comment]
@kazk if it's not possible to find the real offender, could you at least revert the damage they've done with this fake account?

**Comment by kazk** [comment]
Removed the votes by this user.
