### ISSUE TITLE
Collapsible list for test cases red, even though all tests passed

### ISSUE THREAD

**Issue by samsamson33** [Codewars/codewars.com#1982]
#### Describe the bug
After solving [a kata](https://www.codewars.com/kata/mod4-regex), the arrow to collapse/expand the list of test cases appeared red. However, the were no errors listed, and I was allowed to click the "Submit final" and continue on to the solutions.

#### Expected Behavior

The arrow should appear green when all tests have passed.

#### Screenshots
![image](https://user-images.githubusercontent.com/35579293/70184543-06132b80-16b6-11ea-92f2-d5ed7ea0e3b0.png)

#### Contexts

- Codewars username: Samsamson33
- OS: Windows 10 Home
- Browser: Firefox Developer Edition
- Browser Version: 72.0b2

**Comment by SavioVolceroKiera** [comment]
This is a problem with the kata's test suite rather than with the site as a whole.

**Comment by error256** [comment]
That happens when `it`s are nested instead of `describe`s.

**Comment by Blind4Basics** [comment]
this actually happens when a it block doesn't contain any assertion it-self. You can nest them otherwise, afaik.

**Comment by kazk** [comment]
Fixed the tests to avoid nesting `it`.
Both of you are correct. Nesting `it` doesn't make the test case red at the moment with Mocha (Node 10), but I'd recommend not doing it. Empty `it` should make it red and also fail the test.
