### ISSUE TITLE
Server Error 500 when clicking See Next Kata

### ISSUE THREAD

**Issue by mrbunnyman** [Codewars/codewars.com#1983]
#### Describe the bug
See attachment. Looks like there was a server error 500 on the site. This occurred after I completed a Kata and clicked on See Next Kata. When I refreshed the window, it returned me to the same page displaying the same error. Please resolve. Thank you so much!
#### Expected Behavior

I expected to click on See Next Kata and go to another page with a new kata to train under.

#### Contexts

Please complete the following information:

- Codewars username (if account related): [e.g., jhoffner] => mrbunnyman
<img width="1392" alt="Screen Shot 2019-12-06 at 2 00 27 PM" src="https://user-images.githubusercontent.com/53240659/70352703-582c8c00-1831-11ea-99fb-165cfd6fe279.png">
<img width="1392" alt="Screen Shot 2019-12-06 at 12 23 22 PM" src="https://user-images.githubusercontent.com/53240659/70352705-582c8c00-1831-11ea-8cb9-533f9207b2fd.png">

- OS: [e.g. macOS] => macOS
- Browser: [e.g. chrome, safari] => Chrome
- Browser Version: [e.g. 22] => Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by FArekkusu** [comment]
`Next kata` button leads to `codewars.com/trainer` :thinking:

**Comment by kazk** [comment]
I've made some changes to fix this. Can you try again?

`/trainer` or `/trainer/:language` is correct. It redirects to the next kata in queue of the user. The server error happened because of some data issue when dequeuing a kata.

**Comment by mrbunnyman** [comment]
Thank you!
