### ISSUE TITLE
Multiple copies of Agda in translation language drop-down

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#1984]
When translating a kata you can see 2 "Agda" entries in the drop-down of available languages.

![image](https://user-images.githubusercontent.com/31668662/70390777-d9715380-19d6-11ea-9e77-4962e87dbcb0.png)

This doesn't happen in the kata editor or normal kumite, though.

**Comment by Steffan153** [comment]
Actually it's not just "Agda", the default language selected (sometimes different, I think it has to do with your most recently trained language) appears twice.

**Comment by kazk** [comment]
Fixed
