### ISSUE TITLE
Execution Timed Out (16000 ms)

### ISSUE THREAD

**Issue by peterpan21** [Codewars/codewars.com#1985]
The tests for the kata were successful. I click attempt and get the following error: "Execution Timed Out (16000 ms)". Happened yesterday, still happens today.

Any suggestions?

/edit: Chrome and macOs

**Comment by DonaldKellett** [comment]
Sounds like a Kata-specific question to me. Note that Kata-specific questions/suggestions/issues should be raised in the Discourse section of the Kata affected.

In your particular situation, your solution is probably not efficient enough to pass the Kata, even though the logic may be correct (e.g. using a naïve recursive solution to compute Fibonacci numbers instead of dynamic programming). Try coming up with a more efficient solution.

**Comment by peterpan21** [comment]
[it's not about my solution, sadly](https://www.codewars.com/kata/build-a-pile-of-cubes/train/java)

**Comment by DonaldKellett** [comment]
Would you mind posting the link to the Kata here (but not to the trainer page)?

**Comment by peterpan21** [comment]
<img width="1607" alt="Screenshot 2019-12-11 at 14 26 40" src="https://user-images.githubusercontent.com/6628527/70625218-4298d700-1c22-11ea-87da-2290e0220611.png">

here's the [link](https://www.codewars.com/kata/build-a-pile-of-cubes/train/java) to the kata

**Comment by peterpan21** [comment]
for me, from the screenshot it doesn't look like it's kata-related though. :/

**Comment by DonaldKellett** [comment]
> for me, from the screenshot it doesn't look like it's kata-related though. :/

> #### Why did my code time out?
> 
> Our servers are configured to only allow a certain amount of time for your code to execute ... **>> Most of the time though this issue is caused by inefficient algorithms. <<**

Your screenshot indicates that your solution has a loop-in-loop. For this Kata, you should be able to solve it using a single loop (or perhaps even without loops if you get clever with algebra).

**Comment by peterpan21** [comment]
alright, thanks. i'll try again.. :D

**Comment by Chrono79** [comment]
Just so you know, when there is a timeout or an exception, normally it'll show it passed all tests until that point, that doesn't mean your code has passed all the tests of the suite.

**Comment by kazk** [comment]
Closing as invalid. Thanks @DonaldKellett @Chrono79 for helping.
