### ISSUE TITLE
Revalidating solutions individually per power-user request

### ISSUE THREAD

**Issue by Chrono79** [codewars/codewars.com#1986]
#### Is your feature request related to a problem? Please describe.
As solutions revalidation doesn't seem to work as intended, or we don't know why sometimes it works and sometimes it doesn't, in the Solutions tab there are invalid solutions that were valid at some point but don't work anymore. The problem is some people see those solutions after forfeiting the kata and feel cheated. Also, showing invalid solutions as still valid is confusing.

#### Describe the solution you'd like
My suggestion is giving power-users (so moderators don't need to worry about this, and it isn't abused if used with responsibility) the possibility to execute an individual solution revalidation with a link or a button, so it doesn't take too much resources from the server, and an invalid solution is marked as such. Being something made manually, you can measure it, set a cool-down time or a limit per time period.

#### Describe alternatives you've considered
Giving more priority to solutions revalidation? If it takes down the server, then it's not an option, that's why I suggest a less resources consuming way.

#### Additional context
I've already mentioned this problem here: https://github.com/Codewars/codewars.com/issues/1347#issuecomment-482131580
That one was marked as invalid at some point after more than 7 months.

These two are still marked as valid:
https://www.codewars.com/kata/reviews/52774a314c2333f0a700068b/groups/5577e334c0374aed4a000066#5df129f7c6ba5100280ec8cc
https://www.codewars.com/kata/reviews/5556198001231dce9a000132/groups/5729f8b6ca1f7011fe0009e9#5df0fa5bc6ba51001b108352

**Comment by hobovsky** [comment]
For reference, see [here](https://www.codewars.com/kata/5262119038c0985a5b00029f/discuss#5dde277e9f5af1002c19e78a).

**Comment by kazk** [comment]
Admins already have this actually (just invalidated those two), so it shouldn't be difficult to enable it for some users.

In general, I've been thinking about allowing some users to do more so that the community can manage itself (and less work for me :)). I wouldn't want it to be based on honor points though. I'll probably pick some users that are known to be responsible at first.

I'm currently focused on refactoring to make Codewars' code maintainable, so I'll look into this and what's causing revalidation to not work as expected when I get there.

**Comment by Chrono79** [comment]
There is an issue open about a wrong solution here and tests are ok but the solutions isn't marked as invalid yet: https://www.codewars.com/kata/5276c18121e20900c0000235/discuss#5e9f9be1afe7c2001a9b9724

**Comment by kazk** [comment]
Done. I'll be working on this (delegating more to the community) during this quarter.

**Comment by kazk** [comment]
Done. Selected users have this option now.
