### ISSUE TITLE
GitHub account is not linked to an existing Codewars user.

### ISSUE THREAD

**Issue by Goodron1981** [Codewars/codewars.com#1987]
#### Describe the bug
I am logged into the https://www.codewars.com/users/sign_in resource on my gadget account, but there is an error "GitHub account is not linked to an existing Codewars user."
 
#### To Reproduce

1. Go to 'https://www.codewars.com/users/sign_in'
2. Click on 'Git hub login'
3. I enter the account information and confirm
4. See error "GitHub account is not linked to an existing Codewars user."

#### Expected Behavior

Successful authorization

#### Screenshots

![image](https://user-images.githubusercontent.com/15790171/70711458-4bed7680-1cea-11ea-8c74-4f4ae4fd4846.png)

#### Contexts

Please complete the following information:

- Codewars username Goodron1981
- OS: Ubuntu
- Browser: chrome
- Browser Version: 78.0.3904.97

**Comment by Goodron1981** [comment]
I click Sign up
Then click to my favorite language
Completed the task.
Finished autorization.

**Comment by prince24j** [comment]
Currently I am facing the same issue. Is there any legit way to fix this issue?

**Comment by VladimirBalaur** [comment]
I keep facing the same issue.
Is there anything to do regarding it?

**Comment by tazheeb-shamsi** [comment]
Facing same issue

**Comment by ShadowStar03161622** [comment]
Had the same issue, but solved it. Just go into sign up, then press link github account and then it works! Hope this helps!

**Comment by Exoticinurs** [comment]
Same Issue here... Help me please

**Comment by ShadowStar0316** [comment]
Sure! First, go into codewars, and if you are already logged in, log out. Then, press join. You will see a link your github account button. Press that. You don't need to do the stuff underneath that button. Then, it should work.
