### ISSUE TITLE
"Forgot Password" 

### ISSUE THREAD

**Issue by MakeSureAndShow** [Codewars/codewars.com#1992]
It's been 2 years since I last touched codewars. After re-going through initialization, my email address is already there, so I decided to go to forgot password, only to find out that it redirects me to the initialization section again "you have already signed in" but clearly I didn't. Perhaps this is due to my github account being linked.

**Comment by kazk** [comment]
> Perhaps this is due to my github account being linked.

Can you sign in with your GitHub account?

What's your Codewars username?
