### ISSUE TITLE
Inconsistent UI for problem webpage

### ISSUE THREAD

**Issue by ganeshtata** [Codewars/codewars.com#1994]
#### Describe the bug
The web page colour seems to be changing whenever I scroll down the page of any problem.

#### To Reproduce

Go to any problem and scroll down. 

#### Screenshots

![image](https://user-images.githubusercontent.com/23188723/71484679-a67eea80-2833-11ea-93fa-666fd0756876.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): ganeshtata
- OS: Ubuntu 16
- Browser: firefox
- Browser Version:72.0b10

**Comment by FArekkusu** [comment]
Did this appear not long ago? Does the issue persist in older Firefox versions, or other browsers? Are there any errors in the console or anything weird happening with CSS? Without this information the issue is as good as "something bad, please fix".

**Comment by ganeshtata** [comment]
> Are there any errors in the console or anything weird happening with CSS? 

@FArekkusu I am not really sure as to what you mean by "anything weird happening with CSS". I am not very familiar with CSS. I see this in the console -
![image](https://user-images.githubusercontent.com/23188723/71485657-2909a900-2838-11ea-9652-4217c90dfe14.png)

**Comment by kazk** [comment]
@ganeshtata Can you try in Incognito/Private Window with all extensions disabled? Also, is there anything logged in console?

Some extensions are known to cause issues like #1979.

**Comment by ganeshtata** [comment]
@kazk Thank you for the suggestions! It was a problem with one of my extensions - https://addons.mozilla.org/en-US/firefox/addon/night-mode-pro-w/. 
Thank you! Closing this issue.
