### ISSUE TITLE
500-solutions lock should not prevent kata authors from editing the tests

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#1995]
For example, [this kata](https://www.codewars.com/kata/5727bb0fe81185ae62000ae3) has some issues, but the author can't do anything because 500+ people have already completed it in the language in question.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1dc7) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Not really. I'll close this because kata can be fixed by forking and approving the fix.
