### ISSUE TITLE
"You must have at least 100 honor before you can give your rank assessment"

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#20]
**Type:** Enhancement
**TL;DR**: Fix or drop the "you can't rank" message for the kata author.

---

Apparently, there's something wrong with my current honor, since I'm greeted with the following message on my own kata:

> You must have at least 100 honor before you can give your rank assessment.

See the following screenshot for a proof:

![cannot-vote](https://cloud.githubusercontent.com/assets/6301773/6973452/38407274-d98b-11e4-8277-69eed691fe57.png)

I guess something along the following should be a little bit more appropriate ;)
##### Message for normal user with less than 100 honor

> You must have at least 100 honor before you can give your rank assessment.
##### Message for normal author (or just drop the message)

>  Kata authors cannot vote on their own katas. Instead, change the field "estimated rank" in the [kata editor](link-to-kata-editor).

**Comment by smiks** [comment]
I also have this message (for a long time already) [my kata in beta].

How difficult do you think this kata is?
You must have at least 100 honor before you can give your rank assessment.

I have 2.5k+ honor now and I still have this message.

**Comment by adri326** [comment]
Still there, four years later

![Imgur](https://i.imgur.com/xUyr5IK.png)

**Comment by kazk** [comment]
This should now show "Authors cannot assess rank on their own kata. Set the "Estimated Rank" field in the kata editor instead."
