### ISSUE TITLE
Missing language: Ruby

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#2003]
#### Describe the bug

I can't train myself for Ruby, and If I run the sample test I got the message 

> Missing language

#### To Reproduce

Open the Kata `Classic Hello World` for the language Ruby or simply go to the link https://www.codewars.com/kata/classic-hello-world/train/ruby

#### Expected Behavior

Trainer for Ruby should work

#### Screenshots

[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/1063901/71861003-61bc4480-30ba-11ea-8108-ce8c44011b18.png)

**Comment by kazk** [comment]
Looks like #1323. The error message changed since then, but it's both missing the language.

**Comment by kazk** [comment]
Can you try in Incognito/Private Window with all extensions disabled?

**Comment by kazk** [comment]
I've fixed some data issue. Please let me know if this still happens.

**Comment by javatlacati** [comment]
Tried with incognito mode and all extensions disabled and still happends

![image](https://user-images.githubusercontent.com/1063901/72655070-30fcca80-3958-11ea-84da-afed162cd6de.png)

**Comment by javatlacati** [comment]
FYI: If I try the link without logging in it works.

**Comment by kazk** [comment]
There was another corrupted data in `csharp` that was causing the document to fail update. Can you try again?

**Comment by javatlacati** [comment]
Fixed. Thanks.
