### ISSUE TITLE
Javascript lacks BigInt function

### ISSUE THREAD

**Issue by Haggr** [Codewars/codewars.com#2004]
BigInt is a built-in object that provides the functionality of representing and operating on numbers that are too big to do so safely. (Larger than 2^53 - 1)

There are primarily two ways to declare such numbers: by appending a "n" at the end of the number or using the BigInt() function. Codewars provides the first one but the second one is lacking and it is a BIG problem because the only way to convert a string consisting of digits or a number variable to BigInt is the BigInt() function.

The lack of this function limits the solvability of many problems and forces the users to find complicated workarounds. Check the following link for information on BigInt.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

An attempt to use the function produces the following error: ReferenceError: BigInt is not defined

**Comment by kazk** [comment]
`BigInt()` is supported on Node 10.x. Make sure the kata you're solving has Node 10 enabled and you have selected it.
