### ISSUE TITLE
Please include more details in single solution page's title 

### ISSUE THREAD

**Issue by dbtx** [codewars/codewars.com#2006]
When I follow and then bookmark the "Link" item on another warrior's solution, the destination page title only indicates what the kata's title is, e.g.
"Kata Solution: Title of kata here | Codewars"

As new bookmark titles default to the page title, it will be good to have all the immediately relevant info already in the title:
"[name]'s solution to [problem] ([lang]) | Codewars"
or
"[problem] : [lang] solution by [name] | Codewars"

We can edit the bookmark title to include whatever info we want, but re-entering it manually is tedious.

**Comment by hobovsky** [comment]
+1 on adding some more details on a solution page visible when you haven't solved the kata.

Mods cannot see contents of solution pages if they haven't completed the related kata, what makes it difficult to follow reports from users even if a reporter provides a link to the problematic solution. Having displayed at least submitters' names would make it easier to investigate such reports.
