### ISSUE TITLE
Code inside kumites cannot be executed

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#2008]
Whatever language and language version I choose, the code in kumites cannot be executed: the `Run` button is grayed out and unresponsive, saying "we can't run the selected language". The `Save` is also grayed out but it actually works.

![image](https://user-images.githubusercontent.com/31668662/72469505-33d8ad80-37e8-11ea-96a9-c54df46ba543.png)

A few minutes ago I could not switch languages at all getting stuff like `Python - Node v8.1.3`, but this doesn't happen anymore.

**Comment by kazk** [comment]
Deployed the fix. Reload the page and try again. I've confirmed the fix, but please let me know if it's still broken for you.
