### ISSUE TITLE
Results in Codewars and browser differs

### ISSUE THREAD

**Issue by ytorn** [Codewars/codewars.com#2009]
I'm really sorry if this is not a right place to ask this, but I have faced a situation, when the same code returns different results in Codewars and in browser console. So in Codewars i have a wrong result but when I compare expected result with the return of same code in browser, they are exactly the same. Can you please help me with this or at least explain what's going on?

**Comment by kazk** [comment]
Codewars uses Node.js to test your solution and it can behave differently from your browser. Another reason might be that your solution has side effects that causes the result to change depending on how it's called (globals, mutating the input, etc).

That's all I can say without any specific examples.

**Comment by ytorn** [comment]
Here is an example, would be great if you can check it and tell what's
wrong.

I have tried to write a sorting function for a group of arrays, which sorts
them by columns sequentially (in descending order the first column, than,
if there are some equal results, the second column and so on). In browser
it works good, but not in codewars unfortunately.

// arr - array with arrays to sort; n - quantity of columns to sort;
let sorting = function(arr, n) {
    for (let i = n - 1; i >= 0; i--) {
    arr = arr.sort((a, b) => b[i] - a[i]);
    }
    return arr;
   };

Thanks in advance.

пт, 17 січ. 2020 о 21:17 kazk <notifications@github.com> пише:

**Comment by kazk** [comment]
The function sorts the array by element at `n - 1`, then sorts again by element at `n - 2`, ..., then sorts again by element at `0`. Each step is done separately so it relies on the `sort` being stable (maintains relative order when equal). JavaScript standard doesn't require the sort to be stable and many implementations only does stable sort when the number of elements is low. That's probably why it _seems_ correct when you test in your browser with small inputs and it behaves differently when tested against larger inputs. Try to find a way to do this without relying on the sort being stable.

Also, changing the input `arr` can cause issues depending on how the test is set up.

This is not the right place to ask questions for solutions so please use the discussion page for the kata in the future.

**Comment by ytorn** [comment]
Sorry for disturbing you here with this question and thank you very much
for your answer, I appreciate it.

пн, 20 січ. 2020 о 22:41 kazk <notifications@github.com> пише:
