### ISSUE TITLE
Use official logo for Agda

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#2014]
So it seems that Agda has recently (as of 23/12/2019) created [its own official logo](https://commons.wikimedia.org/wiki/File:Agda%27s_official_logo.svg). Perhaps we could replace our current Agda logo with that sometime, just so that Agda challenges look more familiar to new Codewarriors specializing in Agda?

<sup><sub>Also, is that yet <em>another</em> logo of a chicken? :thonking: </sub></sup>

**Comment by SavioVolceroKiera** [comment]
From wikipedia:
> Agda is named after the Swedish song "Hönan Agda" (...)  that is about a hen named Agda. This alludes to the naming of Coq.

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/73041326-f4c2e180-3e11-11ea-9405-b6d3065668ad.png)

![image](https://user-images.githubusercontent.com/639336/73041295-c9d88d80-3e11-11ea-84ef-99da71cea2d5.png)

![image](https://user-images.githubusercontent.com/639336/73041428-479c9900-3e12-11ea-9174-5b047d3260ae.png)

![image](https://user-images.githubusercontent.com/639336/73041415-3c496d80-3e12-11ea-9183-6858622ddf45.png)

I'll close this when it's deployed.
