### ISSUE TITLE
Failed test assertions in Node 10.x gives wrong error code

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#2016]
Consider this block:

```js
describe("Solution", function() {
  it("should test for something", function() {
    Test.fail();
  });
  it("should test for something", function() {
    Test.fail();
  });
  it("should test for something", function() {
    Test.fail();
  });
});
```

Node 10.x gives `Error Code : 3`

![image](https://user-images.githubusercontent.com/14909989/73141003-25c53f80-40ba-11ea-8b9f-d4a84aa13a9c.png)

In fact Node 10.x gives `Error Code` equal to the number of failed `it` blocks. This behaviour is different from other JS versions and even other language versions, which always gives `Error Code: 1` when any failed test assertions occur regardless of how many `describe`/`it` blocks are involved.

**Comment by kazk** [comment]
The exit code comes from Mocha. They set the exit code to the number of test cases it failed :|
