### ISSUE TITLE
Comments under kumites are not visible sometimes

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2018]
Sometimes comments left under kumites are not visible (some weird caching applied maybe?). It first happened a couple weeks ago with a translation, but now it happened again with a [regular kumite](https://www.codewars.com/kumite/5e32ded00189d8002ee59860?sel=5e33122b5aa9c9001021df7c). In that earlier case only my comments disappeared, but now other users' comments disappear too.

2 comments are missing:

1. I left a comment under a kumite
2. I jumped to it from the dashboard and see this:
![image](https://user-images.githubusercontent.com/31668662/73475464-159eb000-4399-11ea-98e7-61d7a24e727e.png)
3. Then I pressed the "Rooted by: Invert Pitch Set" link and see this:
![image](https://user-images.githubusercontent.com/31668662/73475628-66aea400-4399-11ea-8fdd-90f7d1ef8a6e.png)

A comment and an upvote are missing:

1. A user left a comment under my fork
2. I jumped to it from the dashboard and see this:
![image](https://user-images.githubusercontent.com/31668662/73476090-492e0a00-439a-11ea-8ac4-17f546df9be2.png)
3. Then I pressed the "Rooted by: Invert Pitch Set" link and see this:
![image](https://user-images.githubusercontent.com/31668662/73476123-59de8000-439a-11ea-9120-cdaa1354580d.png)

**Comment by kazk** [comment]
Yeah, looks like it's showing some outdated version when kumite is displayed as a descendant.

For kumite with id `5e330aaef020860010a1a4fc`. Only 4 comments are shown when it's displayed as descendant of `5e32ded00189d8002ee59860` (https://www.codewars.com/kumite/5e32ded00189d8002ee59860?sel=5e330aaef020860010a1a4fc).
![image](https://user-images.githubusercontent.com/639336/73584766-a1731380-444f-11ea-8452-a8daded97d5a.png)

But showing it as a root (https://www.codewars.com/kumite/5e330aaef020860010a1a4fc), shows 6 comments.
![image](https://user-images.githubusercontent.com/639336/73584774-b94a9780-444f-11ea-9f02-529201bcebed.png)
