### ISSUE TITLE
Signup ignores clan field if you connect to Github

### ISSUE THREAD

**Issue by ajburke** [Codewars/codewars.com#202]
Hi there.

I signed up for Code Wars today and noticed that I automatically had people from my old company added as allies. The steps I took to make this happen were

1.Start signup login after going through C# check
2.Connect to GitHub Account
3.Noticed my clan was set to my company on my github account
4.Empties out clan field due to my github account not having the company up to date
5. Fill out rest of signup
6. Click signup
7. Select C# and Javascript on first page to select Katas

This dumped me out to my profile where it said I had all the members of my clan automatically added as allies. As I had set the clan field to nothing I expected no allies, but I see that my old coworkers were added. My clan field was set to "Unknown" on my profile

**Comment by jhoffner** [comment]
There is not much we can do about this. The idea is to automatically set your clan as a way of promoting the feature and making it easier to use. In some edge cases like this one the use case is not desired. All you need to do though is just remove your clan and the allies should go away.
