### ISSUE TITLE
Sign Out button sends to 404 Error

### ISSUE THREAD

**Issue by xDjAlchatraz** [Codewars/codewars.com#2023]
When clicking the "SIgn out" button  you are sent to "https://www.codewars.com/users/sign_out" where you are greeted by a 404 Error saying the page does not exist.

Steps : 
1. Hover over your icon/score menu
2. Click "Sign out"

**Comment by kazk** [comment]
I cannot reproduce.

Please complete the following information:

- Codewars username:
- OS:
- Browser:
- Browser Version:

 Is JavaScript enabled? Can you try with any extensions disabled?
