### ISSUE TITLE
Timeout when running tests

### ISSUE THREAD

**Issue by jamiecajka** [Codewars/codewars.com#2024]
I keep getting timeout errors (Execution Timed Out (12000 ms)) when running tests for javascript. I'm using chrome. I verified that the code works fine in my external text editor, so it's not the code.

**Comment by kazk** [comment]
Please use discussion page of the kata to ask questions. You can post your solution with spoiler flag there.

> I verified that the code works fine in my external text editor, so it's not the code.

This is not possible because you don't have access to the tests used when submitting until you have successfully completed.
