### ISSUE TITLE
The filter in the collection section are not working

### ISSUE THREAD

**Issue by marcosjbarroso82** [Codewars/codewars.com#2027]
#### Describe the bug
None of the filter for collections are working. Not the text search, order of filter by owner

#### To Reproduce

1. Go to 'https://www.codewars.com/collections'
2. change any filter

#### Expected Behavior

I can see that an ajax request to https://www.codewars.com/collections is being made. But in the preview of the response I see all the collections without filters again. So I guess that is not that the UI is not being update. It's the request that is bringing the wrong results.
Also, despite that the request if GET I don't see any filters in the url

- OS: Linux Mint
- Browser: Chrome
- Browser Version: 78.0.3904.87 (Official Build) (64-bit)

**Comment by kazk** [comment]
Fixed. Refresh the page and try again.
