### ISSUE TITLE
User profile page social media links vulnerable to persistent XSS

### ISSUE THREAD

**Issue by seisvelas** [Codewars/codewars.com#2028]
#### Describe the bug

By updating the LinkedIn link on a profile to a `javascript:` URL, a user can execute arbitrary JavaScript code on the browser of whoever clicks their LinkedIn link. 

#### To Reproduce

1. Login to Codewars
2. Browse to Account Settings -> SOCIAL
3. Change LinkedIn URL to javascript:console.log("or whatever code you want")
4. Browse to profile and click link
5. New window opens and code executes

#### Expected Behavior

Ideally, links would only go to linkedin. This could be done by restricting the links users submit to valid LinkedIn links, or by forcing users to submit a username or account ID and letting CodeWars generate the link to their LinkedIn page.

If that is not an option, then only `http://` and `https://` prefixed links should be accepted (although this still opens up a phishing vector by linking to a fake LinkedIn mockup page).

At the very least, `javascript:` psuedoprotocol links should be disallowed.

#### Contexts

**Codewars username**: seisvelas
**OS**: BlackArch Linux
**Browser**: Firefox 72 (also tested on Chromium)

**Comment by seisvelas** [comment]
I just noticed that basically this same vulnerability was disclosed about three years ago by @lucasduffey via the following Issues:

https://github.com/Codewars/codewars.com/issues/1032
https://github.com/Codewars/codewars.com/issues/1033

Perhaps the old issue was fixed and has since been recoded to be vulnerable again. It is hard to tell since that Issue was closed with no discussion. In any case, I hope this helps!

**Comment by kazk** [comment]
Thanks for letting us know.

Looks like the fix applied when it was first reported 3 years ago does not actually fix the issue :(
I'll try to deploy the fix as soon as possible.

If you happen to find another security issue, please email us instead.

**Comment by kazk** [comment]
Deployed the fix. Only the link with `https?` should be displayed now.
