### ISSUE TITLE
Kumite search doesn't work

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#2029]
https://www.codewars.com/kumite
None of the filters works: text search, my kumite only, by language.

**Comment by DonaldKellett** [comment]
Can confirm - sometimes when I try to select Coq-only kumites to see if anyone has authored a new Coq Kumite, the page refreshes but then the kumites listed don't change at all.

**Comment by bdw429s** [comment]
I noticed this too.  No matter what I do on that page, I cannot affect the results.  Language filter, text filter, "my kumite" checkbox... nothing.  Checking the network tab, all I see is an HTTP get to the /kumite page with no query string so it doesn't even seem that my search criteria are being passed.

**Comment by kazk** [comment]
Found the cause. Sorry, I had accidentally removed `return` statement that was actually necessary when getting rid of CoffeeScript and cleaning up the code generated from its implicit returns. I thought I had tested this, but I guess I didn't cover this. It's been broken for few weeks :(

**Comment by bdw429s** [comment]
Hah, the old "missing return statement" of doom.  Good times ;)

**Comment by kazk** [comment]
Fixed. Please refresh the page and try again.
