### ISSUE TITLE
Searching for katas of multiple difficulties results in a wrong number of katas listed

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#2031]
Filtering katas by difficulty you can see that there're [39](https://www.codewars.com/kata/search/?q=&r%5B%5D=-1&beta=false) `1 kyu` katas, and [64](https://www.codewars.com/kata/search/?q=&r%5B%5D=-2&beta=false) `2 kyu` katas. If you search for katas in a [2-1 kyu difficulty range](https://www.codewars.com/kata/search/?q=&r%5B%5D=-2&r%5B%5D=-1&beta=false), there will be only 39 katas listed - the same amount as the number of katas of the highest difficulty in the selected range. Using other combinatations has the same result: 39 katas with any minimum difficulty and `1 kyu` maximum difficulty, 64 katas with any minimum difficulty and `2 kyu` maximum difficulty etc.

**Comment by kazk** [comment]
Is this #936?

**Comment by FArekkusu** [comment]
Yes. GitHub did not suggest that issue as a possible duplicate :(
