### ISSUE TITLE
i cannot use numpy in python 3.6

### ISSUE THREAD

**Issue by GorgiC** [Codewars/codewars.com#2033]
on python 3.6 i'm able to import numpy but I cant use it, it always results in:

Don't import sys or a module that depends on it.

 STDERR
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    test.assert_equals(alphametics(inp),out)
  File "/home/codewarrior/solution.py", line 13, in alphametics
    dis = np.array([np.array(x) for x in neword])
AttributeError: 'NoneType' object has no attribute 'array'

**Comment by sa-vo-ki** [comment]
Which kata is it? It seems that author of the kata made it not possible to import modules, also in future ask first in kata's discourse before creating an issue here.

**Comment by kazk** [comment]
Please use the kata discussion page.
