### ISSUE TITLE
Horizontal lines in text are not displayed anymore

### ISSUE THREAD

**Issue by anter69** [Codewars/codewars.com#2034]
A really minor issue: it looks like that horizontal lines in text are not displayed anymore (earlier they were). It doesn't matter if I use markdown or html, they are invisible:

![image](https://user-images.githubusercontent.com/12795864/74521602-e7cd7580-4f19-11ea-8b3a-3c405b23ff69.png)

**Comment by DonaldKellett** [comment]
Can confirm - there is supposed to be a horizontal rule between the second last paragraph and last paragraph in [my latest comment](https://www.codewars.com/kata/5c36e827348b3e15a56edcbf/discuss#5e44d0e276551c0017e06984).

**Comment by error256** [comment]
It looks like there are 2 problems:
* `---` doesn't do anything;
* `<hr>` actually is there, but its style is wrong, so it's invisible.

**Comment by anter69** [comment]
> `---` doesn't do anything;

`---` in markdown supposed to translate to `<hr>` in html, and it did until some time ago.

**Comment by kazk** [comment]
Fixed

**Comment by anter69** [comment]
Wow, that was quick! :-)
