### ISSUE TITLE
Count bits in integer for GOLANG issue

### ISSUE THREAD

**Issue by emalgamatedsoy** [Codewars/codewars.com#2035]
While participating in the kata : 
https://www.codewars.com/kata/526571aae218b8ee490006f4/train/go

There were errors regarding data types.

package kata

func CountBits(n uint) uint {
        for 
        { 
            count := n & 1
            n >>= 1
            if(n == 0){
               return count
            }
        }
}

This solution will retrieve the correct result, but will result in an error; as an unsigned integer does not equal an integer.
The issue is that you can not cast an unsigned integer to an integer while performing low-level maniuplations like this; as the assignment operator for the instruction :
count := n & 1 
Does not support a casting from a uint to int, even though both are the same size (either 32 or 64 bit). Can someone look into this? For now I'll complete my answer in python.

Thanks,
--Patrick McSherry

**Comment by kazk** [comment]
Please use the discussion page for any issues/questions for a kata. https://www.codewars.com/kata/526571aae218b8ee490006f4/discuss
