### ISSUE TITLE
[UI] Bookmarking kata outputs concatenation of old and new count.

### ISSUE THREAD

**Issue by sa-vo-ki** [Codewars/codewars.com#2046]
As title says, here's demonstration:

![sth](https://user-images.githubusercontent.com/55797790/75459243-60ebb480-597f-11ea-91ad-96d52eec922e.gif)

Seems to be a side effect of recent changes as I don't recall this happening before.

**OS**: Windows 7 64-bit
**Browser**: Firefox 73.0.1 64-bit

**Comment by kazk** [comment]
Fixed
