### ISSUE TITLE
impossible to mark a comment with the spoiler flag

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2048]
Hi

#### Describe the bug
trying to set the flag results in an error message (shown in a red bar, at the bottom of the screen:

> Resulting document after update is larger than 16777216 (17419) (on cw-production-shard-00-01-us6nm.gcp.mongodb.net:27017, attempt 1) (on cw-production-shard-00-01-us6nm.gcp.mongodb.net:27017, attempt 1)

the message isn't flagged after that, ofc.

#### To Reproduce
* [this solution](https://www.codewars.com/kata/reviews/5266876c8f4bf2da9b000365/groups/564ab2ff633fa181490000b7)
* go to the bottom, deploy the last thread
* happened when I wanted to flag the second message of swampslop

#### Expected Behavior
Clear enough, I guess... x)

#### Screenshots
![image](https://user-images.githubusercontent.com/32236948/75607127-27888580-5af4-11ea-8cad-b1f5f99740a9.png)

#### Contexts
- Codewars username Blind4Basics
- OS: Windows 7
- Browser: FF
- Browser Version: 73.0.1 (64-bits)

Cheers

**Comment by kazk** [comment]
Yeah, this is a known issue. Some of the documents have reached MongoDB's document size limit.

Any data that's expected to grow over time, especially without limit (e.g., solution groups, comments, etc.), shouldn't be stored as embedded documents, but it is :(

There's no easy way to fix properly. We need to do a major data migration that changes how some of the data is stored.

**Comment by mhombach** [comment]
@kazk From the beginning on, you have to keep in mind, what limitations are coming with using a NoSQL database. If you need help with changing the existing datastructure, feel free to reply here and tell me, how i can contact you.

**Comment by kazk** [comment]
This shouldn't be happening anymore, at least for a while. I didn't do a complete fix so it's going to come back eventually, but it should buy some time.

**Comment by Blind4Basics** [comment]
@kazk: can you check if the kata below is also affected by this? (and can you rework the document to gain some space?)
https://www.codewars.com/kata/563fbac924106b8bf7000046/solutions/javascript

cheers
