### ISSUE TITLE
Solution is submitted without pushing the final submit button

### ISSUE THREAD

**Issue by lajuma** [Codewars/codewars.com#2049]
#### Describe the bug

A solution should only be accepted after explicitly pushing the final submit button.

Reason: When trying to run solutions from others to check eg. their performance, I do not want to submit these solutions, but this happens sometimes.

#### To Reproduce

1. Go to a kata of your choice
2. Paste a solution to the editor, which will work
3. Click on Attempt
4. Wait for tests to complete and the green Submit button to appear
5. Then click Reset and confirm in the dialog
6. Then check in solutions, if the solutions is in there, even if not submitted.

#### Expected Behavior

Solutions should not be submitted if not clicking explicitly on the green Submit Button.

**Comment by kazk** [comment]
> Reason: When trying to run solutions from others to check eg. their performance, I do not want to submit these solutions, but this happens sometimes.

Don't do this. If you want to try, use the `fork` feature available when looking at other's solutions.

> Solutions should not be submitted if not clicking explicitly on the green Submit Button.

It's not submitted. Your solution is only visible in your profile's solution page.

---

In the forum, you wrote:

> Is there a way to remove a solution completely? I think there should be a possibility to remove a solution, and of course also the points that come with it.
> The reason why I'm asking: Lately I tried a solution from someone else just to check the performance and they are submitted even without pushing the submit button. I'll report this as bug as well,

You shouldn't have earned points if you were trying other's solution *after* completing the challenge. Don't *try* other's solutions before completing it yourself. That's considered plagiarism. If you can't figure out yourself, there's also an option to give up and unlock solutions.

Earning points when passing tests, before "Submit" is already reported. #1104

**Comment by lajuma** [comment]
Just to make that clear: I never wanted to submit others solutions and I only try others solutions after submitting myself to compare my solution against others – as you are only able to see solutions after doing it yourself (did not know about the solution unlock until now). I do know what plagiarism is and that was the original point, why I wrote this request: To delete what was not mine, but submitted by accident.
