### ISSUE TITLE
Leaderboard should use "competition ranking" for ties

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2050]
Hi,

Not sure it's intended, a bug, or just undocumented, but I just faced that situation (in the overall leaderboard):

![image](https://user-images.githubusercontent.com/32236948/75623839-a215db80-5bae-11ea-9f7f-166246967182.png)

1. Ties aren't resolved. -> then we both should be rank 7
1. Ties are resolved, but silently/by chance (like, there could be a secondary key, ordering by name) -> we both should be 7
1. Ties are actually resolved as expected, but it's not documented anywhere. ->maybe add something somewhere about that?
1. nobody cares? x) (not kidding: that's not really important...)

Cheers

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1deb) by [Unito](https://www.unito.io)

**Comment by Steffan153** [comment]
![Screenshot_20200303_200453](https://user-images.githubusercontent.com/40404519/75837468-8cf5a400-5d8a-11ea-821f-a205a4758c25.png)
This time I have a lower kyu than emgerdon, yet I'm higher in the leaderboard. Dunno...

**Comment by kazk** [comment]
We use [leaderboard](https://github.com/agoragames/leaderboard) gem and use the default style without tie breaks. 

> Default: The Leaderboard class uses the default Redis sorted set ordering, whereby different members having the same score are ordered lexicographically. As per the Redis documentation on Redis sorted sets, "The lexicographic ordering used is binary, it compares strings as array of bytes."
>
> https://github.com/agoragames/leaderboard#alternate-leaderboard-types

So I _think_ the order is determined by the `user_id`.

I don't think this was *chosen* though. Probably just used the default without thinking about ties.

The gem provides the following options:
**Default** (current)
```
| member     | score | rank |
-----------------------------
| member_1   | 50    | 1    |
| member_2   | 50    | 2    |
| member_3   | 30    | 3    |
| member_4   | 30    | 4    |
| member_5   | 10    | 5    |
```
**Tie ranking**
```
| member     | score | rank |
-----------------------------
| member_1   | 50    | 1    |
| member_2   | 50    | 1    |
| member_3   | 30    | 2    |
| member_4   | 30    | 2    |
| member_5   | 10    | 3    |
```
**Competition ranking**
```
| member     | score | rank |
-----------------------------
| member_1   | 50    | 1    |
| member_2   | 50    | 1    |
| member_3   | 30    | 3    |
| member_4   | 30    | 3    |
| member_5   | 10    | 5    |
```

We can change to the last one. I hope I don't need to rebuild the leaderboard.

**Comment by Voileexperiments** [comment]
> So I *think* the order is determined by the `user_id`.

Does that mean the order is determined by registration time? Since IIRC it's the mongoDB ID, which is a random string appended to the hex timestamp.

**Comment by kazk** [comment]
Deployed

![image](https://user-images.githubusercontent.com/639336/207436802-e2bb8105-db94-455e-a4fc-9a829c1376bf.png)

Descending lexicographical order of the user id is used to determine the order when tied ([`zrevrange`](https://redis.io/commands/zrevrange/)), so newer users are shown above.
