### ISSUE TITLE
Add a "maintainable" code alongside "clever" and "best practices"

### ISSUE THREAD

**Issue by exhuma** [codewars/codewars.com#2052]
#### Is your feature request related to a problem? Please describe.

Looking at the solutions of most kata, I realise that quite often obfuscated one-liners bubble up to the top because they are "clever" and/or use an obscure language feature to enable this one-liner.

While it is true that these can be considered "clever" those solutions are often much harder to maintain in larger projects. Often a less efficient, more verbose solution is preferred.

Unfortunately, CodeWars does not have a way to recognize more maintainable solutions.

#### Describe the solution you'd like

Currently there are only two kinds of upvotes in the system ("clever" and "best practices"). A new type "maintainable" (or something along those lines) would be a nice addition.

#### Describe alternatives you've considered

I was thinking about also allowing "downvotes", or the possibility to "challenge/flag" a given solution. I rejected the "downvotes" option as this is clearly a design-decision by CodeWars and that's fine.

The "challenge/flag" option would still be nice, but more work to implement. The way I imagine this is that a solution could be connected to a discussion thread which is either open, resolved positively (challenge accepted), or resolved negatively (challenge rejected). If a challenge was accepted (via voting?) The solution would be flagged as a non-optimal solution. If the challenge was rejected, the solution would not be flagged in any way. While the challenge is open for discussion, the solution would be flagged as "challenged".

The "challenge" solution could provide an immensively valuable learning resource when looking at the discussion. It would also help weed out solutions which the community deems to be "bad practice". Obviously, the person who submitted the "bad" solution should not be punished in any way, maybe it would even make sense to hide the username of whomever submitted a solution which has been successfully challenged to avoid name-calling and to prevent users feeling reluctant to submit solutions which they don't feel confident about.

#### Additional context

I am using CodeWars for two reasons: Hone my skills in languages I know, and learn new languages.  While looking at solutions of languages I know, I often see really ugly solutions that, while they solve the problem, I would absolutely reject in a code-review in a professional setting. The main reason bein maintainability of the code when working in a team. Obviously, some performance-critical sections sometimes need ugly code, but, especially for a learning resource like CodeWars, this should be kept the exception.

Especially when learning new languages, I am in the position that I don't trust the solutions of CodeWars anymore because of this. Even though they sometimes have a high "best practices" score, they are sometimes really badly written.

**Comment by sa-vo-ki** [comment]
See the point is Codewars is supposed to be community driven, and what you see in solutions tab is already the result of community votes, so additional system, would be redundant and not change anything. If you feel strong about certain solutions comment on them and let others know this that way. Also Codewars is by no means solitary tool for education on given topics and shouldn't be perceived that way.

**Comment by kazk** [comment]
We're aware of the problems with current "Best Practices"/"Clever" votes, but I don't think adding "Maintainable" will fix anything.

We'll do some experiments to improve the situation in the future.

**Comment by exhuma** [comment]
Thank you @kazk for adding an update in this. I have to admit that I was a bit disappointed by the reply from @sa-vo-ki as it fails to address the issue. But maybe my post could have been a bit clearer too.

I'm happy to hear that you identified an issue and are working on it.

Keep up the good work. CodeWars really *is* an amazing service!
