### ISSUE TITLE
Re-publishing a kata messes up the edit page view until reloading

### ISSUE THREAD

**Issue by Steffan153** [Codewars/codewars.com#2056]
![image](https://user-images.githubusercontent.com/40404519/76111142-5b0c5980-5fa5-11ea-839e-aecc00c5f177.png)

After re-publishing a kata, it messes up the view (above) until I refresh the page. This is an old bug, I know, but still.

**Comment by kazk** [comment]
This was happening when there was an error while reloading the page after republish. I fixed the main cause, but please let me know if this happens again and include the link to the kata.
