### ISSUE TITLE
changing the width of the "skill ranking" box (user profile)

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2057]
Since the update of the display of the overall/by language ranks using decimals, the box isn't anymore large enough and most of the stats are using 2 lines (even "python" is too long x) ).

So I'm thinking the margin on the left could be used to extend the width of that box:

![image](https://user-images.githubusercontent.com/32236948/76115478-7d739680-5fe8-11ea-9082-95568c96dc2f.png)

Cheers

**Comment by Blind4Basics** [comment]
(actually, there is room on the right too, between the text and the slider)

**Comment by FArekkusu** [comment]
This could be browser- or screen size-specific. Using Chrome and a monitor with 1680x1050 resolution the progress-list `div` has a constant size of `207.25 x 200` which is enough regardless of how many characters are there per line.

**Comment by Blind4Basics** [comment]
browser, then: my screen is 2560x1440. Unless, screen format related?

**Comment by sa-vo-ki** [comment]
not related to screen format, changing container height helps with text wrapping, but extending width to 250px (is there reason not to?) makes everything fit nicely

**Comment by kazk** [comment]
I've increased the width.

**Comment by Blind4Basics** [comment]
that's better, but that leads to new problems, when the window becomes narrow ;o

![image](https://user-images.githubusercontent.com/32236948/81425282-9408ac00-9157-11ea-8997-f403fa6cd13b.png)
