### ISSUE TITLE
Font-family for solutions overriden by browser defaults

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#2061]
In Firefox:
![Solution code with the default bold font](https://user-images.githubusercontent.com/5375100/76501357-09971b00-643a-11ea-9b05-ce565220a62f.png)
![Computed styles: monospace for code](https://user-images.githubusercontent.com/5375100/76501525-51b63d80-643a-11ea-8b16-2e0150d0246e.png)
As a result, the default font is too bold.

**Comment by FArekkusu** [comment]
The code is in bold on kata solutions pages only. Solutions listed in users' profiles are not in bold, but it looks like their font size is greater than before.

**Comment by FArekkusu** [comment]
Font size for code shown under `View Solution` button is also very small now:

![image](https://user-images.githubusercontent.com/31668662/76513736-66f19300-645f-11ea-8a47-1bc3cd3e1581.png)

**Comment by kazk** [comment]
Fixed
