### ISSUE TITLE
<hr> elements are hard to see under the "Past Solutions" tab

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#2064]
![image](https://user-images.githubusercontent.com/31668662/76572449-c9c84600-64c2-11ea-862a-8f3ce63586cd.png)

And it's a lot worse when there're many lines of code per solution.

**Comment by kazk** [comment]
Improved styling and enabled syntax highlight.

![image](https://user-images.githubusercontent.com/639336/76577037-40445400-6481-11ea-87b5-aedcb256d243.png)

![image](https://user-images.githubusercontent.com/639336/76576946-f65b6e00-6480-11ea-9bd7-a5bff5e956f8.png)
