### ISSUE TITLE
Reply button not working

### ISSUE THREAD

**Issue by JessicF** [Codewars/codewars.com#2066]
Trying to press reply to a comment, and the reply button doesn't appear to do anything.

Codewars Username: sesqui
OS: Windows 10
Browser: Chrome 80.0.3987.132

**Comment by Steffan153** [comment]
Your account isn't confirmed (duplicate issue btw). Go to account settings and you should see a button to confirm it.

**Comment by g964** [comment]
I think my account is confirmed but since yesterday same thing happens, sometimes it works if you refresh the page sometimes not... Sometimes it is even impossible to display recent comments.
Browsers: Chrome, Firefox

**Comment by kazk** [comment]
@g964 

> since yesterday

That's strange because I didn't deploy on that day. I think your issue is different from OP. Can you open a new issue with screenshots and also include any console outputs?

**Comment by g964** [comment]
It is difficult to see on a screenshot that nothing happens when I push the reply button:-)
On the console I get:
```
Mixed Content: The page at 'https://www.codewars.com/kata/573992c724fc289553000e95/discuss#5e70d92e2510980023085f56' was loaded over HTTPS, but requested an insecure image 'http://graph.facebook.com/10208077457917885/picture?type=square'. This content should also be served over HTTPS.
```

**Comment by kazk** [comment]
You've been posting comments so it's clearly a separate issue. I opened #2070 for you. Please add any details like which kata it happened on.
