### ISSUE TITLE
Allies tab not working.

### ISSUE THREAD

**Issue by VFDan** [Codewars/codewars.com#2068]
#### Describe the bug
The allies tab is about 25% of the normal width.

#### To Reproduce

1.  Look at your allies tab.

#### Expected Behavior

Just the standard allies tab, full width.

#### Screenshots

![image](https://user-images.githubusercontent.com/44413950/76801727-93cddf00-67ac-11ea-807e-7a3bc6c675cc.png)

#### Contexts

Please complete the following information:

- OS: Windows 10
- Browser: Firefox
- Browser Version: 74

Also tested on:

- OS: Windows 10
- Browser: Chrome
- Browser Version: 80

**Comment by kazk** [comment]
I can't reproduce. What's shown in your next challenge section? There's a known issue where `<style>` in kata description affects how dashboard is rendered.

**Comment by kazk** [comment]
Also, this is on the dashboard right? Not Allies "tab" in your profile.

**Comment by VFDan** [comment]
Yes, on the dashboard.

**Comment by VFDan** [comment]
I pressed the `Skip` button and it worked, so it must've been that.

**Comment by kazk** [comment]
Thanks. Closing as duplicate of #1664.
