### ISSUE TITLE
Typos in CW Terms of Service

### ISSUE THREAD

**Issue by ggorlen** [Codewars/codewars.com#2069]
#### Typo 1

https://www.codewars.com/about/terms-of-service > Limitation of Liability

has a typo:

> any ubject matter 

intent was probably:

> any subject matter

#### Typo 2

https://www.codewars.com/about/terms-of-service > Copyright Infringement

>  visitor ho may infringe

intent was probably:

>  visitor who may infringe

#### Typo 3

https://www.codewars.com/about/terms-of-service > Responsibility of Website Visitors

>  responsible for that materials content

intent was probably:

>  responsible for that materials' content

#### Note

This bug report does not constitute legal advice or endorse changes to a legal document.

**Comment by kazk** [comment]
Fixed. Thanks Greg.
