### ISSUE TITLE
Solutions access withheld

### ISSUE THREAD

**Issue by salvolds** [Codewars/codewars.com#2073]
#### Describe the bug
Cannot access to solutions for kata already solved by me

#### To Reproduce

1. Go to 'View profile'->Solutions
2. Click over the already solved Kata "Multiples of 3 or 5"
3. When the Kata page is open, click over 'Solutions'
4. See error: "Solutions have been withheld
Since you have not yet solved this kata we have hidden the solutions from you. If you choose to view the solutions you will forfeit your eligibility to earn honor/rank progress for this kata."

#### Expected Behavior

Solutions shown

#### Screenshots

![image](https://user-images.githubusercontent.com/59929058/76976421-38c6f400-6934-11ea-9ebf-bd3fb39a5878.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): salvolds
- OS: Windows 10
- Browser: chrome
- Browser Version: 80.0.3987.132

**Comment by FArekkusu** [comment]
You completed the kata in PowerShell, and trying to view the C solutions. Of course, it won't work.

**Comment by salvolds** [comment]
Got it, thanks
