### ISSUE TITLE
NASM and its katas do not respect the C calling conventions 

### ISSUE THREAD

**Issue by Vyber90** [Codewars/codewars.com#2074]
I think so (https://en.wikipedia.org/wiki/X86_calling_conventions) because in its katas, saving the base pointer is not compulsory for the programmer, and the place where the arguments will be loaded from may vary between challenges (in some the parameters are in registers, in others are saved into the stack). 
This inconsistent behaviour could lead to an unhealthy habit while programming assembler, while being a suffering when the developer does not know what to read from.
Furthermore, the programmer could write code that is not legal in terms of universality while _serious-programming_.

**Comment by hobovsky** [comment]
NASM kata use [Linux 64-bit calling convention](https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI), and this behavior is indirectly documented on [CodeWard wiki](https://github.com/Codewars/codewars.com/wiki/Language-NASM)

**Comment by Vyber90** [comment]
> NASM kata use [Linux 64-bit calling convention](https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI), and this behavior is indirectly documented on [CodeWars wiki](https://github.com/Codewars/codewars.com/wiki/Language-NASM)

What exact convention are we speaking about? I have never been told about this, and this could lead to a misunderstanding of the code as well.

**Comment by Vyber90** [comment]
Is there any warranty on this? I mean, does every kata use this convention compulsorily?

**Comment by hobovsky** [comment]
We are speaking the one described in linked Wikipedia page as `System V AMD64 ABI` calling convention. For 64 bit programs, there is much fewer calling conventions on most of the platforms, and unlike for 32 bit platforms, you do not have to be concerned with differences between `cdecl`, `stdcall`, etc. These have no direct equivalents on 64 bit platforms, and all function calls compiled with GCC targeting 64 bit Linux use the convention I mentioned.

Things might get different when your 64bit code would call external 32bit code, but it's not the case with CodeWars kata. At least that's how I got it. Also note I do not do assembly coding professionally, and everything I said above is probably just a simplification for needs of CW kata. Or maybe just flat wrong :)

**Comment by Vyber90** [comment]
Roger that. That is all the information I asked for, and thank you, hobovsky. Hopefully I will not make any trouble again. Good afternoon!
