### ISSUE TITLE
Share on twitter button on ranked up notification does not work

### ISSUE THREAD

**Issue by shoheihagiwara** [codewars/codewars.com#2075]
#### Describe the bug
When I ranked up, a ranked up notification popped up on the right down corner of the page. The notification had a share-on-twitter button in it. When I clicked the button, looking at its HTML, it was supposed to open a new window and show a new tweet with the content `I'm now a 4 kyū blue belt on @codewars! Come join me #codewarriors!. codewars.com/r/HVMZaA`. However, it just opened my Twitter home page.
Looking at the code, the intended URL was "https://twitter.com/intent/tweet?text=I%27m%20now%20a%204%20ky%C5%AB%20blue%20belt%20on%20%40codewars!%20Come%20join%20me%20%23codewarriors!.%20codewars.com%2Fr%2FHVMZaA"?

#### To Reproduce

1. Player ranks up
2. Rank up notification pops up.
3. Click on Twitter button in the notification.
4. Expected: New window with a new tweet with the text `I'm now a [number] kyū [color] belt on @codewars! Come join me #codewarriors!. codewars.com/r/HVMZaA` gets shown.
Actual: New window with the player's Twitter home page gets shown.

#### Expected Behavior
A new window with a new tweet with the text `I'm now a [number] kyū [color] belt on @codewars! Come join me #codewarriors!. codewars.com/r/HVMZaA` opens.

#### Screenshots
![screen shot](https://user-images.githubusercontent.com/8368127/77810792-cabfc100-70d9-11ea-979e-4a6cdad16035.PNG)

#### Contexts

Please complete the following information:

- Codewars username (if account related): [e.g., jhoffner] shoheihagiwara
- OS: [e.g. macOS] Windows 10 Home Edition
- Browser: [e.g. chrome, safari] Chrome
- Browser Version: [e.g. 22] 80.0.3987.149（Official Build） （64 ビット）

**Comment by kazk** [comment]
Thanks for all the details.
I updated the URL.

**Comment by shoheihagiwara** [comment]
Thank you for the prompt action!
Glad I could help.
