### ISSUE TITLE
[Preview] Solution and Sample Tests editor not displaying properly

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#2076]
#### Describe the bug

On the [preview site](https://preview.codewars.com/) only, when I train on a language in any Kata, the Solution and Sample Test editors have an abnormally low height, and their heights cannot be adjusted except for going fullscreen.

Note that I have only tested this as a guest, though I would not expect being logged in / out to make a difference in the UI.

#### To Reproduce

1. Go to the Kata search page
2. Click on any language icon on any Kata to train on it
3. If the trainer looks normal to you, try switching to a different language

#### Expected Behavior

The Solution / Sample Test editors should display normally.

#### Screenshots

![螢幕截圖 2020-03-28 14 49 43](https://user-images.githubusercontent.com/7777884/77817143-8ea15600-7103-11ea-94b6-8f66669bb65d.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): N/A
- OS: macOS Catalina 10.15.3
- Browser: Safari
- Browser Version: 13.0.5

**Comment by kazk** [comment]
I wasn't able to reproduce using Firefox/Chrome, only Safari.

The main difference between the preview and the production is jQuery version. I'll look into it.

**Comment by kazk** [comment]
Fixed
