### ISSUE TITLE
[UI] Opening browser console docked at the bottom on trainer's page ruins the layout.

### ISSUE THREAD

**Issue by sa-vo-ki** [codewars/codewars.com#2077]
As title says. Happens both in Firefox and Chrome (didn't test other browsers).

#### Screenshots:
![tada](https://user-images.githubusercontent.com/55797790/77844502-adf1bf00-71a7-11ea-8aec-b2dc3c9d5af7.JPG)
![tada2](https://user-images.githubusercontent.com/55797790/77844507-b34f0980-71a7-11ea-9b9a-842a7641683e.JPG)

- OS: Windows 7
- Browsers: Firefox 74.0 , Chrome 80.0.3987.149

**Comment by kazk** [comment]
Fixed
