### ISSUE TITLE
Buying a car KATA

### ISSUE THREAD

**Issue by AymanAtallahAhmed** [codewars/codewars.com#2078]
Please open an issue at [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli/issues) repository.

kata: Buying a Car
language: swift

in Buying a Care Kata the code does not compile and show this message 
"  main.swift:13:70: error: cannot convert value of type 'Int' to expected argument type 'Double'
        let act: (Int, Int) = nbMonths(startPriceOld, startPriceNew, savingPerMonth, percentLossByMonth)
                                                                     ^~~~~~~~~~~~~~
        Double(       ) "
 although it runs well in xcode playground with all cases without problems

**Comment by kazk** [comment]
Please use the kata discussion page for kata issues/questions.
