### ISSUE TITLE
katas aren't being shown in the browser

### ISSUE THREAD

**Issue by f-lyp3** [codewars/codewars.com#2079]
Can't see any kata, no matters what browser I use keep facing dark-gray rectangle instead of the kata

1. I Go to 'https://www.codewars.com/dashboard'
and all is shown is a dark-gray rectangle instead of the kata itself

![codewars](https://user-images.githubusercontent.com/60755982/77918416-c63f0800-7293-11ea-8f7f-e2470493d455.png)

- f.lyp3
- OS: Ubuntu 16.04 lts
- Browser: chrome, opera, firefox

**Comment by FArekkusu** [comment]
You should check the browser console for errors and mention them here (if there're any), and see whether turning off some browser extensions helps as they can affect the HTML.

**Comment by sa-vo-ki** [comment]
You can hover over vertical bar on the left side and click `Kata` there. It takes you to the page where you can browse all available katas.

**Comment by kazk** [comment]
@f-lyp3 I deployed a possible fix, can you try again and let me know? If it's not fixed, can you check if there's any errors in console?

**Comment by f-lyp3** [comment]
@kazk it's working again! seems like you fixed it, thank you
