### ISSUE TITLE
Make dark mode optional

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2081]
> Original [feature request](https://www.codewars.com/topics/5235fedb397cbfd6aa0000ea#5e83587b07a8d20029a7a3bc) on CW forum.

The light/dark mode switch in the trainer disappeared with one of the recent changes.

**Comment by kazk** [comment]
I had removed it temporarily because it's been buggy/broken for years and increases the cost of change. I'm planning to add it back after cleaning things up.

**Comment by kazk** [comment]
For some context, there was `no theme` (incomplete, light background), `dark theme` (default), `inverted theme` (buggy, enabled through light mode button), and `light theme` (?) for some reason and it was just a mess. Everything except `dark theme` seemed incomplete and overlapping.

When adding the theme switch back, I'll probably make it enable/disable dark theme (enabled by default, but also respects user's OS settings).

**Comment by seth-noaa** [comment]
> (enabled by default, but also respects user's OS settings).

As long as there is some option to override. I like the OSX dark menu bar, but have anything where I need to write text set to light. Terminals, Pycharm...

Thanks

**Comment by rtn2020** [comment]
Any updates?) Im looking light theme..

**Comment by kazk** [comment]
No, I'll close this issue when it's added back.

**Comment by kazk** [comment]
Deployed the new site wide theme switch. You can switch between dark/light using the moon/sun icon at the top.

I'm sure there's some things I overlooked and it's not the prettiest, but it should be usable. Please open issues if you find anything unreadable or if you have suggestions for improvements.

**Comment by FArekkusu** [comment]
The code highlighting is poor in the light mode IMO. Using the dark mode, you can clearly see how different stuff is highlighted in purple (keywords), orange (function/class names and numbers), blue (methods), dark gray (comments), light gray (built-in function), and green (strings). With light mode, though, everything looks light-grayish with the original color mixed in a little:

![image](https://user-images.githubusercontent.com/31668662/83003677-52ad4300-a017-11ea-8e7f-81e7e09c6b23.png)

**Comment by FArekkusu** [comment]
I found a few other inconsistencies, or things that don't look very good IMO and could be improved. I wasn't sure whether to open a separate issue, and decided to list everything here.

The issue symbol is too bright compared to other symbols:

![image](https://user-images.githubusercontent.com/31668662/83056358-eace1b00-a05d-11ea-9199-787c891f86c6.png)

The shadows under cards are hard to see in dark mode, and look quite weird because of how they blend in with the background and the cards themselves:

![image](https://user-images.githubusercontent.com/31668662/83056640-747de880-a05e-11ea-9d23-c74c29f606d6.png)

Pressed drop-downs don't retain highlight in light mode (in both cases I clicked on the `Progress` button, and moved the cursor to the `Status` button):

![image](https://user-images.githubusercontent.com/31668662/83057185-4056f780-a05f-11ea-8814-bdb5a7322ed7.png)

The "ads via Carbon" message is illegible in light mode:

![image](https://user-images.githubusercontent.com/31668662/83057680-ee62a180-a05f-11ea-9ec2-73e49ffcad9e.png)

**Comment by kazk** [comment]
@FArekkusu Thanks!

> I found a few other inconsistencies, or things that don't look very good IMO and could be improved. I wasn't sure whether to open a separate issue, and decided to list everything here.

Having separate issues are better since it's much easier to keep track.

**Comment by kazk** [comment]
> The code highlighting is poor in the light mode IMO.

Yeah, the light mode have colors washed out. I'll try adjusting them to stand out little more.

> The issue symbol is too bright compared to other symbols:

Codewars was/is using opacity a lot to adjust appearance and it was one of the pain points when adding light theme. This one has `opacity: .75` to make it appear lighter on dark. I'll adjust both dark and light modes.

> The shadows under cards are hard to see in dark mode, and look quite weird because of how they blend in with the background and the cards themselves

Yeah, the card was necessary to make the search result look decent in light mode. The original just listed the results on the background and that didn't work on light mode since it made the list of kata look unimportant when it's the main content.
I'll try adjusting the dark mode.

> Pressed drop-downs don't retain highlight in light mode

Can you elaborate on this? Do you mean the background of "All" should match the background of "Approved"?

> The "ads via Carbon" message is illegible in light mode:

I had overlooked this. It should be trivial to fix.

**Comment by FArekkusu** [comment]
> Can you elaborate on this? Do you mean the background of "All" should match the background of "Approved"?

Yes, to some extent. The drop-down button is black when the cursor is hovering over it, and it remains darkened after you click on it - the color isn't the same, but it's clear that the button is in focus. In light mode, on the other hand, the button goes back to the "default" white color.

**Comment by kazk** [comment]
Fixed "the issue symbol is too bright compared to other symbols" by changing the icon. The original was just too thin.

Fixed "Pressed drop-downs don't retain highlight in light mode".

Fixed illegible "ads via Carbon".

For syntax highlighting, I'll need some time to experiment. I'm considering to open source the theme so users can contribute.

For shadows in dark mode, I think the dark mode needs to be revamped. It currently has darker surfaces on top of a lighter background so it looks weird with the shadow.

**Comment by FArekkusu** [comment]
I've just noticed that pre-processor direcrives in C/C++ are in purple which is hardly readable in dark mode (ealier it was gray, I believe). A similar thing could be happening in other languages too.

![image](https://user-images.githubusercontent.com/31668662/83242427-11e33480-a1a5-11ea-8871-91db2e48cb04.png)

**Comment by FArekkusu** [comment]
> Please open new issues if you find anything else

I forgot that you asked to open separate issues yesterday, and listed new found problems together with the older ones :(

I'll open new ones if I notice anything else.
