### ISSUE TITLE
"My Drafts" in Kumite view contains drafts by other user

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2082]
Hi,

#### Describe the bug
I created a fork, but messed it up and realized it only after trying to publish it. Since it's impossible to delete them (yet?), I unpublished it, but it's still visible from any user, apparently:

https://www.codewars.com/kumite/5e836fab4ea9dd003327165b?sel=5e836fab4ea9dd003327165b

just in case:
![image](https://user-images.githubusercontent.com/32236948/78061601-bc99cb00-738d-11ea-9338-842cc23e8ee0.png)

#### To Reproduce
* create a fork
* publish it
* unpublish it
* go to the forks page

![image](https://user-images.githubusercontent.com/32236948/78061828-17cbbd80-738e-11ea-8f04-a4ec0f61705f.png)

#### Expected Behavior
A draft should be private.

cheers

**Comment by kazk** [comment]
I don't think it's visible from any user. The viewer needs to have the kata completed or forfeited. If you mean any user _that completed/forfeited_, then I'll need to look into it more.

As far as I know, drafts are allowed to be shared by providing URLs like draft challenges. So others can still view it if they know the exact URL, but I don't know why it's shown under "My Drafts" for them.

**Comment by Blind4Basics** [comment]
rowcased and Steaffan posted telling they can see my draft (denoted as "my drafts" even if it's clearly not theirs). Steffan posted a screenshot in the thread: https://www.codewars.com/kumite/5e836fab4ea9dd003327165b?sel=5e836fab4ea9dd003327165b

**Comment by Blind4Basics** [comment]
ok, it's hard to find, but visible from any of those users. Proceed as follow:

* fork the existing solution: https://www.codewars.com/kata/reviews/5e83605bed1f800001da74ff/groups/5e8366d6ed1f800001da7cf3
* go to the ancestor panel and click on the link
* there it is.

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/78064802-204cd580-7347-11ea-99f3-7da3b9b3909c.png)

`mrtp0` probably got there originally from a notification.

Showing up under "My Drafts" is definitely a bug.

**Comment by kazk** [comment]
This seems like another caching issue :( The cache key doesn't contain the viewer so it's showing the same cached content for all users.

**Comment by kazk** [comment]
Fixed

**Comment by Steffan153** [comment]
Cant see it now, so it's working now.
