### ISSUE TITLE
Lean Kata not showing up in Kata search by language

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#2083]
Lean versions are currently available for [Multiply](https://www.codewars.com/kata/50654ddff44f800200000004/lean), [Theorem proving hello world](https://www.codewars.com/kata/5c879811bc562909bf65c8e6/lean) and [Multiples of 3, you say?](https://www.codewars.com/kata/5cc47f8c4b8fea001de6d226/lean); however, when I [search Kata by language = Lean](https://www.codewars.com/kata/search/lean?q=), the only Kata that is displayed is Multiply. Furthermore, I've noticed that Multiply got bumped after accepting a Lean translation but not the other two.

**Comment by kazk** [comment]
Codewar's search index sometimes fails to update. I just manually triggered reindexing for those and it's now showing up.
