### ISSUE TITLE
Kumite has wrong ancestor in editing window.

### ISSUE THREAD

**Issue by OrdoFlammae** [codewars/codewars.com#2093]
#### Describe the bug
I forked a Kumite from [Convert Field to Coordinate](https://www.codewars.com/kumite/5e8fbe562a52a5001eeb00a0?sel=5e8fbe562a52a5001eeb00a0). However, when I look at the ancestors tab in the editing window, the ancestor is [C++ Simple Calculator](https://www.codewars.com/kumite/5e7fe8cde914cc001a1bbdae?sel=5e7fe8cde914cc001a1bbdae). I'm not sure what's going on.

#### To Reproduce

Steps to reproduce the behavior (I'm not sure how often this happens):

1. Fork a Kumite
2. Go to Ancestor tab in the editing window.

#### Expected Behavior

I expected to see the [Convert Field to Coordinate](https://www.codewars.com/kumite/5e8fbe562a52a5001eeb00a0?sel=5e8fbe562a52a5001eeb00a0) in the ancestors tab.

#### Screenshots

Here's my bug displayed in the Kumite editing window.
![kumite-bug](https://user-images.githubusercontent.com/30962639/78955914-56582b00-7aa6-11ea-91ff-a371d7d4bf54.png)

#### Contexts

Please complete the following information:

- Codewars username (if account related): OrdoFlammae
- OS: Linux Mint
- Browser: Firefox
- Browser Version: 74.0 (64-bit)

**Comment by kazk** [comment]
That's weird. I just forked yours and I see correct ancestors.

![image](https://user-images.githubusercontent.com/639336/78956306-ba72f300-7a96-11ea-96f2-d5a94ced5770.png)

Maybe another caching issue.

**Comment by error256** [comment]
I looked at several kumite of mine and all of them have the same "C++ Simple Calculator" in Ancestors too. For instance: https://www.codewars.com/kumite/5ddd5a4d8cf7ed00324bb5e0
