### ISSUE TITLE
Unexpected translation showing up after approval!?

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2095]
Hi,

I just approved [Knights attack](https://www.codewars.com/kata/58e6d83e19af2cb8840000b5), after having totally reworked it in python... afaik (I tend to doubt my memory, but still...!?) there was only a python version of the kata before approval, then, what surprise was it to see a ruby version available... x/

This one is ofc compliant with the original version of the kata (meaning it's pretty "bad" and pretty easy) while the reworked version has nothing in common... :/

As I'm not the author, I cannot nuke the ruby version (even if it's a risky operation), but I really don't want to translate the python version: there are needed stuff for it that ruby doesn't provide.

So, first thing first:
1. is there a way to see the date of the approval of this translation? (to see if I need glasses before I continue approving kata... because if it was there before, well... I just made shit...)
1. IF it wasn't there before, seems there as been strange things at stake, during the publishin/approval process... :/ 
1. is it possible to purely remove that language?

Sorry...
B4B

Note: the ruby version has no completions at all, and was written by the original author. I made it uncompletable for now.

**Comment by Blind4Basics** [comment]
ok, I'm currently trying to actually implement the equivalent in ruby. For now, it seems ok/compatible with the required contraints. Might be I can resolve the problem just by doing that damn translation.

I'll keep you posted.

**Comment by Steffan153** [comment]
On the revisions page:
![image](https://user-images.githubusercontent.com/40404519/79007128-c5ba3300-7b17-11ea-81d4-4bde929cca41.png)

**Comment by error256** [comment]
The revisions page doesn't usually show translation approval, it shows as if the whole block was added when it's first edited directly afterward.

**Comment by kazk** [comment]
Yeah, the revisions are mostly useless and misleading.

Ruby translation was approved 3 years ago (2017-04-08). It's by the author of the kata.

https://www.codewars.com/kumite/58e84390742a457f57000041?sel=58e84390742a457f57000041

![image](https://user-images.githubusercontent.com/639336/79014046-e8037f00-7b1e-11ea-8d35-8ac27ca075d4.png)

**Comment by Blind4Basics** [comment]
okay, so I really need glasses... :(

**Comment by Blind4Basics** [comment]
ruby version updated.
