### ISSUE TITLE
OUTPUT OF THE  PROGRAM IS SAME BUT PROGRAM FAILS IN ATTEMPT

### ISSUE THREAD

**Issue by rammm04** [codewars/codewars.com#2097]
![Untitled1](https://user-images.githubusercontent.com/53853045/79250215-fa254a80-7e9b-11ea-9f62-d611dd76e3f4.png)
Please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue.
OUTPUT OF THE  PROGRAM IS SAME BUT PROGRAM FAILS IN ATTEMPTS. ANY SUGGEST

**Comment by kazk** [comment]
You need to `return` not `print`. Please use the kata discussion page to ask questions.
