### ISSUE TITLE
all katas testes give some error or everyone. 

### ISSUE THREAD

**Issue by JormanWell** [codewars/codewars.com#2099]
Hi everbody.

I'm a begginer programmer, learning Python. 
I can pass anyone of katas because all of them give tests failure, and it is not true.
In my external ide looks good. For exemple.

**<Sum of Digits / Digital Root>** [https://www.codewars.com/kata/541c8630095125aba6000c00](url)

`def digital_root(n):
     num1 = str(n)
    
        num2 = []
    
        for i in num1:
            num2 += i
                       
        for i in range(0, len(num2)):
            num2[i] = int(num2[i])
            
        num3 = 0
        for i in range(0, len(num2)):
            num3 += num2[i]
        if num3 >= 10:
            n = num3
            digital_root(n)
        else:
            return num3
        print(num3)
`
**<Replace With Alphabet Position>**  [https://www.codewars.com/kata/546f922b54af40e1e90001da/train/python](url)

`from string import ascii_lowercase

alphabet = ascii_lowercase

def alphabet_position(text):
    string_letters = ""
    for i in text:
        if i.isalpha():
            string_letters = ''.join([string_letters, i])
            
    
    string_letters = string_letters.lower()
    
    
    str_list_letters = []
    for l in string_letters:
        str_list_letters += l
    
    
    
    lenght_alphabet = list(range(len(alphabet)))
    
    dict_alphabet = {}
    
    for letters in lenght_alphabet:
        dict_alphabet[alphabet[letters]] = str(letters + 1)
    str_final = "" 
    for i in str_list_letters:
        str_final += dict_alphabet[i] + " "
        #print(dict_alphabet[i], end=" ")
    return str_final.replace(" "," ")`
 
For the last kata, 

![Screenshot 2020-04-15 10 38 17](https://user-images.githubusercontent.com/46009399/79323001-8ae44080-7f05-11ea-9a96-d206576aba47.png)
            
Thanks

**Comment by FArekkusu** [comment]
> I can pass anyone of katas because all of them give tests failure, and it is not true. In my external ide looks good.

Your code can't "look good" in the IDE, and fail tests on CW, it's either correct, or not. For instance, the recursion in your first example is wrong, and the returned value in your second example is also wrong.

If you're having a problem with some kata, ask a question in the kata discourse instead.

**Comment by kazk** [comment]
Please use the discussion page for each kata.
