### ISSUE TITLE
Java / JUnit: some test failures are ignored, probably due to NullPointerException in CwRunListener.formatMessage

### ISSUE THREAD

**Issue by jcsahnwaldt** [Codewars/codewars.com#21]
If a test method throws an exception with a null message, the error is ignored and the test passes. Many exceptions thrown by the VM, e.g. NullPointerException or StackOverflowError, have a null message.

I think the bug is in [CwRunListener.java](/entrefuse/cdr/blob/master/jvm-runner/src/java/codewars/java/CwRunListener.java). ```CwRunListener.formatMessage()``` should probably return an empty string if the argument is null. Currently, it throws a NullPointerException.

Here's ```CwRunListener.testFailure()``` and ```CwRunListener.formatMessage()```:

```
public void testFailure(Failure failure)
{
  failed = true;
  System.out.println(String.format("<FAILED::>%s<:LF:>", formatMessage(failure.getMessage())));
}

private static String formatMessage(String s)
{
  return s.replaceAll("\n", "<:LF:>");
}
```

When the message is null, ```formatMessage()``` throws a NullPointerException, which flies right through ```testFailure()```, so the ```<FAILED::>``` message doesn't get written. I guess the Codewars testing framework ignores the ```failed = true``` field, only checks what's written to System.out, doesn't see a ```<FAILED::>``` message, and marks the test as successful.

**Comment by jcsahnwaldt** [comment]
Here's a workaround.

Let's say you want to test that the method ```Bar.foo()``` returns the correct value ```baz```. Currently, your tests may look like this:

```
assertEquals(baz, Bar.foo());
```

To make sure that the tests fail when ```Bar.foo()``` throws an exception, change your test to something like this:

```
Foo found;
try {
  found = Bar.foo();
}
catch (Throwable e) {
  // see https://github.com/Codewars/codewars.com/issues/21
  throw new AssertionError("exception during test: "+e, e);
}
assertEquals(baz, found);
```

**Comment by Darnor** [comment]
As of today this bug is still persists and can lead to solutions passing even thought they shouldn't due to a NullPointerException.

Example Katas:
- http://www.codewars.com/kata/help-the-fruit-guy/java
- http://www.codewars.com/kata/simplexer/java
- http://www.codewars.com/kata/pascals-triangle-number-2/java

**Comment by Darnor** [comment]
It seems that it's not only NullPointerExceptions that cause this to happen.

When I tried to solve the Kata (Finding Neo (NC-17)) my solution passed the first and caused a StackOverflowError for the rest of the tests which then were skipped and caused me to pass the Kata with a broken solution.
Here's the Kata:
- http://www.codewars.com/kata/finding-neo-nc-17/java

**Comment by jhoffner** [comment]
I fix was deployed for the NullPointer issue. Please verify. I still need to investigate further on the StackOverflow error.

**Comment by Darnor** [comment]
Just checked with the Katas I mentioned. Everything's working correct now. Also my solution with the StackOverflowError doesn't pass anymore. Thank you very much for fixing this.

**Comment by jhoffner** [comment]
Great. Thanks for testing.
