### ISSUE TITLE
Revision page item timestamp needs to show the year

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2100]
When I look at revisions I see this:

![image](https://user-images.githubusercontent.com/14909989/79560020-5d4ff080-80d9-11ea-9dc9-632d71bb84bc.png)

Okay, but on which *year* was this edit done? Given raulbc777's long existence it could be anything from 2015 to 2020, and I wouldn't be able to tell.

**Comment by kazk** [comment]
Done. I also cleaned up a little bit to make it easier to tell what changed.
