### ISSUE TITLE
Most recent authored collections not showing up on my profile

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#2101]
I've recently authored two new collections: [Incidence Geometry](https://www.codewars.com/collections/incidence-geometry) and [Mathematical Analysis](https://www.codewars.com/collections/mathematical-analysis), but neither of them are showing up [on my profile](https://www.codewars.com/users/donaldsebleung/authored_collections). The latter one has just been authored now so I do not expect it to be updated immediately, but the former has already been authored around 2 weeks ago.

**Comment by kazk** [comment]
Done. It was only showing the first 20 collections. I also made it to show newer ones first.
