### ISSUE TITLE
"Mark as having spoiler content" doesn't work

### ISSUE THREAD

**Issue by Haksell** [codewars/codewars.com#2104]
#### Describe the bug
Whether I comment on a solution or reply to someone else, the "Mark as having spoiler content" doesn't work.
I can still flag something as spoiler afterwards tough, so not a big problem once you know about it.

#### To Reproduce
Steps to reproduce the behaviour:
1. Comment on solution.
2. Check "Mark as having spoiler content".
3. Realize that it was useless.

#### Contexts
Please complete the following information:
- Codewars username : Haksell
- OS: macOS Catalina 10.15.3
- Browser: Google Chrome
- Browser Version: 80.0.3987.149
I tried disabling browser extensions and the problem remains.

**Comment by FArekkusu** [comment]
Just tried it myself, and the spoiler option doesn't work. The request payload is `{markdown: "Test", masked: true, label: null}`, so the server must be handling this incorrectly.

**Comment by kazk** [comment]
Fixed

**Comment by Voileexperiments** [comment]
@kazk now there's a related bug: when I edit a spoilered comment the "Mark as having spoiler content" checkbox isn't checked by default, so after editing the comment becomes un-spoilered again.

**Comment by kazk** [comment]
@Voileexperiments Thanks, it seems like that's been broken for a while. It's a regression from when I updated jQuery. I'll comment here when the fix is deployed.

**Comment by kazk** [comment]
Fixed the checkbox

**Comment by Voileexperiments** [comment]
@kazk Another regression discovered: After posting a comment (for me it was an issue) marked as spoilers the spoilers checkbox isn't reset to initial, unchecked state.

**Comment by kazk** [comment]
Fixed the another regression.
