### ISSUE TITLE
comment coding-solution, while email is not verified

### ISSUE THREAD

**Issue by mhombach** [codewars/codewars.com#2107]
If you are writing a comment to someon's coding-solution, while your email isn't yet verified, hitting the apply/send-comment button seems dummy. He is clickable but nothing happens. There should be some message that informs the user about the need to verify the email adress.
Though it's frustrating that you are able to type in a long comment, but then fail at sending it.
Also, the http-response from this button-press returns a 200 code, but internally it contains an error.
Since this is an error, the http response 200 is wrong.

**Comment by kazk** [comment]
Fixed
