### ISSUE TITLE
Account Settings > Codewars Labs > Enable Kumite Button Does Not Work

### ISSUE THREAD

**Issue by shivo904** [Codewars/codewars.com#211]
I ran into an issue when I was trying to enable kumite on my account. I found that the enable button is blocked on all major browsers. Here is the error that I get in the console:

```
Mixed Content: The page at 'https://www.codewars.com/users/edit' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.codewars.com/user/feature'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by omegahm** [comment]
I also get this in Chrome Version 47.0.2526.73 (64-bit)

![screen shot 2015-12-08 at 20 26 02](https://cloud.githubusercontent.com/assets/178448/11665907/01f0d848-9dea-11e5-8fbb-c2a3d3b12731.png)

**Comment by kazk** [comment]
Closing this as this button no longer exists.
