### ISSUE TITLE
Can't put a hyphen in bold in Markdown

### ISSUE THREAD

**Issue by Haksell** [codewars/codewars.com#2110]
#### Describe the bug
When trying to write "non-" in bold, like so `**non-**`, the stars and text appear as they are written.

I thought I was missing a feature of Markdown but after testing it on two online editors (https://stackedit.io and https://dillinger.io/), it seems there should be no problem to display that in bold.

The problem only appears when the hyphen is the last character.

#### Screenshots
<img width="741" alt="codewars-hyphen" src="https://user-images.githubusercontent.com/33573717/80031541-2408ed80-84ea-11ea-8215-511a2d586c30.png">

#### Contexts
Please complete the following information:
- Codewars username : Haksell
- OS: macOS Catalina 10.15.3
- Browser: Google Chrome
- Browser Version: 80.0.3987.149

**Comment by kazk** [comment]
Codewars uses libraries adhering to CommonMark.
I don't think it allows what you're trying to do.

https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis

It doesn't work on GitHub as well.

**non-**repeating

The preview might not match what's actually rendered for comments, but that's because of the difference between client side and server side libraries and it's already reported.

**Comment by Haksell** [comment]
I don't see where in the link you've given it talks about hyphens in bold.

But anyway, that's not a big problem and you can't do much about it so I'm closing the issue.

**Comment by kazk** [comment]
> A **right-flanking delimiter run** is a delimiter run that is (a) not preceded by Unicode whitespace, and (b) not preceded by a punctuation character, or followed by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

> A double `**` can close strong emphasis iff it is part of a right-flanking delimiter run.

So `**` in `**non-**repeating` does not close strong emphasis because `**` is preceded by `-` (punctuation) and followed by `r` (not whitespace/punctuation).
