### ISSUE TITLE
Make "Show kata description" and "Show kata test cases" collapsible

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2113]
**Discourse** and **Solutions** tabs contain two sections: _"Show kata description"_ and _"Show kata test cases"_, which are quite useful when, for example, investigating an issue raised by a user. Unfortunately, once expanded, these sections cannot be collapsed again, what makes it very easy to get lost when scrolling back and forth between the discourse post and tests or description.

I think it would be nice to have these sections collapsible after once expanded.

I've already added such functionality in my user script (#1758), but after one of CW updates it  stopped working (https://github.com/hobovsky/polyglot/issues/13) and I think it would be nice to have it directly on CodeWars anyway.

Thanks!

**Comment by kazk** [comment]
Done

**Comment by hobovsky** [comment]
Thanks!
