### ISSUE TITLE
Incorrect tooltip for "Run" button in kumite

### ISSUE THREAD

**Issue by error256** [codewars/codewars.com#2114]
The tooltip for the "Run" button in kumite says "Shortcut: Cmd/Cntrl + ' ", but in fact it is Ctrl+S/Ctrl+Enter.
![Tooltip: "Test your solution using your test fixture as the measurement for success. Shortcut: Cmd/Cntrl + '"](https://user-images.githubusercontent.com/5375100/80593701-2949c900-8a11-11ea-95e4-b3195ec73e88.png)

**Comment by kazk** [comment]
Fixed
