### ISSUE TITLE
"Toggle TDD Mode" tooltip in kumite doesn't disappear

### ISSUE THREAD

**Issue by error256** [codewars/codewars.com#2115]
After the "Toggle TDD Mode" button on a kumite page is clicked, the tooltip doesn't disappear. After several clicks there can be multiple tooltips:
![Multiple "Toggle TDD Mode" tooltips](https://user-images.githubusercontent.com/5375100/80594265-37e4b000-8a12-11ea-9522-e2125e162fbc.png)

**Comment by kazk** [comment]
Fixed
