### ISSUE TITLE
JavaScript environment is outdated

### ISSUE THREAD

**Issue by victorperin** [codewars/codewars.com#2116]
The JS is only using NodeJS 10.x version, without babel support, so, I can't use new language features like:
- Object.fromEntries
- Array.flatMap
- String.matchAll
- Promise.allSettled
- Instance class fields

And a lot of other features. (more on that on [Node Green](https://node.green/) website)

This is preventing me from using codewars to train skills on JS.

**Comment by kazk** [comment]
Please open a new language version request on https://github.com/codewars/codewars-runner-cli following the template.
