### ISSUE TITLE
Add org.clojure/core.match to Clojure execution environment

### ISSUE THREAD

**Issue by andrey-kuznetsov** [codewars/codewars.com#2118]
Consider adding `org.clojure/core.match` dependency to Clojure execution environment. This will allow kata users to employ pattern matching which is implemented in separate namespace, not in `clojure.core`.

**Comment by Steffan153** [comment]
belongs in codewars-runner-cli

**Comment by andrey-kuznetsov** [comment]
@Steffan153, how can one use it?
`(ns my-ns (:require [clojure.core.match :as m]))` causes
```
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/core/match__init.class or clojure/core/match.clj on classpath., compiling:(/home/codewarrior/./test.clj:2:1)
```

**Comment by DonaldKellett** [comment]
@andrey-kuznetsov He meant that you should request for `org.clojure/core.match` package by opening an issue at https://github.com/Codewars/codewars-runner-cli instead.

**Comment by andrey-kuznetsov** [comment]
@DonaldKellett, @Steffan153, thanks, got it.
