### ISSUE TITLE
"Unknown Server Error" while logged in

### ISSUE THREAD

**Issue by phantamanta44** [codewars/codewars.com#2123]
#### Describe the bug
Attempting to load any codewars page while logged in leads to a 500 error and a blank page with the text "Unknown Server Error". Opening codewars in an incognito window does not cause this behaviour until I log in on that window.

#### To Reproduce

1. Log into codewars.

#### Expected Behavior

Codewars loads normally.

#### Contexts

- Codewars username (if account related): phantamanta44 (via github login)
- OS: windows
- Browser: opera gx
- Browser Version: 67.0.3575.130

**Comment by phantamanta44** [comment]
it might be worth noting that this occurred after I received two emails about kata updates; in particular, they are:
* [Generator Functions](https://www.codewars.com/kata/59e7c7e5fc3c49d93f0000d3/)
* [One-Semicolon Stream Zipping](https://www.codewars.com/kata/59ea2372772999e9fa001b25/)

**Comment by kazk** [comment]
Thanks for the info. It looks like the notification data associated with your account got corrupted. I'm looking into it now and will keep you updated.

**Comment by kazk** [comment]
I removed the corrupted data. Can you try again?

**Comment by phantamanta44** [comment]
I can successfully log in now. thanks!
