### ISSUE TITLE
No submit, then no attempt result

### ISSUE THREAD

**Issue by expyth** [codewars/codewars.com#2125]
#### Describe the bug
There is no submit button to solve a kata that I didn't finish yesterday

#### To Reproduce

1. Attempt to solve a kata with a fail attempt
2. Close website
3. Next day, go back to the same kata (click try again on top right)
4. Fix kata solution and click "Attempt" with a PASS on all 
5. No Submit button to submit the solution  #BUG #1
6. Browse website
7. Go back to same kata
8. Click Attempt on saved solution - Fail (Execution Timed Out) <-- server not configured
p.s. kata is "Best Stock Profit in Single Sale"

#### Expected Behavior

1. Attempt to solve a kata with a fail attempt
2. Close website
3. Next day, go back to the same kata (click try again on top right)
4. Fix kata solution and click "Attempt"
5. Submit appears, and able to unlock solutions

#### Screenshots
Will submit if needed

#### Contexts

Please complete the following information:

- OS: Win7 x64
- Browser: Firefox
- Browser Version: 76.0 (64-bit)

**Comment by FArekkusu** [comment]
> Fail (Execution Timed Out)

That kata has performance tests. How do you know you're not timing out due to your solution being inefficient?

**Comment by expyth** [comment]
I was kind of contemplating whether that's on me or the website. The only reason I wasn't sure was because on my 2nd visit to the kata, I passed all tests but I didn't get the Submit button.

**Comment by expyth** [comment]
No issue for now
