### ISSUE TITLE
Revisions/translations pages for drafts are accessible only through the endpoints

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2127]
When the kata is in a draft state, the only thing you can do is `Preview` it (see how it looks in the trainer). If one wishes to access the revisions (or translations) page, they have to go to `https://www.codewars.com/kata/{kata_id}/revisions` page directly, compared to simply pressing a button how it's done in the published-kata editor.

**Comment by kazk** [comment]
Done
