### ISSUE TITLE
Rank of users based on a highest streak

### ISSUE THREAD

**Issue by kocalka** [codewars/codewars.com#2128]
I want to see a list of top 500 users with a highest streak.

Similar to list of users with a highest honor. Maybe a filter button or sort type based on rank/streak to add is enough.

Reason: Streak is very motivational after you pass some target. I am at 360 days streak at the moment and it is clear that I want to continue at least until 365 days. So I will code even if I have not enough time or wish to do it some day due to fact I want to keep that long streak.

**Comment by kazk** [comment]
Congrats for reaching 360 days. I believe completing at least one kata _every single day_ is a great way of improving ourselves. Even if it's a trivial 8 kyu kata on some days, the point is to practice everyday. It definitely adds up.

That being said, I don't think the consecutive days streak should have a leaderboard. I think it should be a competition against ourselves and the number on the profile is enough for that. Also, we only track the streak of Red users so this leaderboard will be missing majority of the users.
We have plans to introduce achievement badges so maybe we can have a `1 year streak` badge that you can show off.

---

If you need some competition, I have 848 days streak which unfortunately stopped last year when I mistakenly thought I had already completed a kata that day when I only fixed a kata :( I believe there are other users with more than a year streak, but haven't checked.
