### ISSUE TITLE
Fork kata solution to my personal Github

### ISSUE THREAD

**Issue by avg0043** [codewars/codewars.com#2129]
Hi,

Does it possible to fork my kata solution to my personal Github?
When I click in "fork" option inside my solution, it redirects me to the the code editor and I dont' see any option to be able to send the fork to my github account.

Thanks!

**Comment by kazk** [comment]
No, it's not possible to copy a solution into your GitHub account. Fork on Codewars allows you to create a fork (derived code) within Codewars in a form of a Kumite.
