### ISSUE TITLE
Viewing the unfinished Kata of another user

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#2131]
Currently, when I view the profile of another user, the UI allows me to select and view his / her "Completed" and "Authored" Kata, e.g. this is what I see when I view my own profile when logged out:

![螢幕截圖 2020-05-12 12 27 59](https://user-images.githubusercontent.com/7777884/81638567-25279d80-944c-11ea-9a45-b422c7cf55cf.png)

However, outside of the UI, I can view the "Unfinished" Kata of another user, e.g. https://www.codewars.com/users/donaldsebleung/unfinished/ .

Since the UI does not make this option available when I am not logged in as that user, I suppose the "Unfinished" tab is intended to be kept private to the user; therefore, the server should check whether the user is logged in (as himself / herself) before displaying the content on every access. Alternatively, if the "Unfinished" tab is intended to be publicly viewable then it should be reflected in the UI as well.

**Comment by kazk** [comment]
Fixed. Thanks for Reporting.
