### ISSUE TITLE
Loophole in making every solution a success

### ISSUE THREAD

**Issue by Marnixvw** [codewars/codewars.com#2136]
Working with students, some students of mine were able to give a 'correct' solution, while the code was completely incorrect. To my surprise they included a class 'ValueCheck' extending the 'TestCase', whereby the default ValueCheck is overwritten. 

Thereby, no matter what your answer is, there is ALWAYS a good answer. A bad 'hack' or loophole in giving the 'solutions'. See the image below:

<img width="1223" alt="overwrite-TestCase" src="https://user-images.githubusercontent.com/62702162/81937560-111ea000-95f4-11ea-9b74-08579d61c611.png">

**Comment by kazk** [comment]
Yes, there are multiple ways to do similar in most of the languages because our challenges are based on unit tests.
We do not try to prevent every possible ways to cheat since it's endless. These solutions will eventually get flagged as cheat and repeated offenders will be banned.

**Comment by Marnixvw** [comment]
Okay, thank you very much!
