### ISSUE TITLE
A kata that I authored isn't listed anymore in my authored katas...

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2138]
#### Describe the bug
I authored ["Break the pieces (evilized edition)"](https://www.codewars.com/kata/591f3a2a6368b6658800020e):

info is in the page related to the kata...:
![image](https://user-images.githubusercontent.com/32236948/82115343-8ad49c00-9762-11ea-9ffe-0a3e4a6b1432.png)

...but not in my profile anymore (but the count of authored katas is correct: 8 instead of 7):
![image](https://user-images.githubusercontent.com/32236948/82115317-5b259400-9762-11ea-88c6-ee4b26653bcd.png)

#### To Reproduce

go there: https://www.codewars.com/users/Blind4Basics/authored

#### Expected Behavior

Every authored katas should be visible

#### Contexts

in any case...: FF 76.0.1 / Win 7-64 bits

cheers

**Comment by Blind4Basics** [comment]
That kata reappeared in page. Clsoing or you prefer to keep it opened?

**Comment by kazk** [comment]
I'll close it until it happens again.
Maybe it was some caching issue. I have no idea.
