### ISSUE TITLE
add more languages

### ISSUE THREAD

**Issue by Future23365** [codewars/codewars.com#2139]
Please open an issue at [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli/issues) repository.
I want to add HTML and CSS challenges。
and I want to have chinese description。Otherwise, I have to improve my English。^_^

**Comment by kazk** [comment]
Hi, please read the issue template next time. For CSS, the request already exists at https://github.com/codewars/codewars-runner-cli/issues/172

We don't have any plans to internationalize kata descriptions at the moment.
