### ISSUE TITLE
Web request error

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2142]
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

I keep getting the above error message for the whole day! And pressing the retry request does nothing! 

For every kata and for every language, when I try to submit answer or to test my answer the message appears!

Had changed pc, browser, clear cache, log in and out of my acc; checked internet connection;nothing fixed since afternoon(was fine this morning)
 
Hope this can be fixed as soon as possible! Best regards~~

- Codewars username (if account related): ejini战神
- OS: Windows
- Browser: Chrome
- Browser Version: Version 81.0.4044.138

**Comment by kazk** [comment]
Is this still happening? If so, could you check the developer tools' network tab and see what the response is?
"For every kata and for every language" is very unusual.

**Comment by ejini6969** [comment]
Everything is fine now! Thanks!
