### ISSUE TITLE
Code spans inside other inline markup rendered as blocks

### ISSUE THREAD

**Issue by mjpieters** [codewars/codewars.com#2144]
#### Describe the bug

When nesting inline Markdown elements, code spans are rendered as block elements instead of inline, because the codewars CSS stylesheet rules applies `display: block` to *all* `<code>` elements inside the `class="markdown"` container, with an override for `.markdown p > code` (direct descendant) to special-case inline code spans.

#### To Reproduce

In a Discourse post, enter

```markdown
Here are some inline code examples, using CommonMark-valid markdown:

- Not nested: `a programming language keyword`
- Inside emphasis: *emphasising `a programming language keyword`*
- Inside bold: **strongly worded remark about `a programming language keyword`**
- Combining all 3: *Please* see the *__[documentation on `a programming language keyword`](https://example.com)__*
```

These currently render as:

<img width="265" alt="Banners_and_Alerts_and_Codewars_-_Kata_Retrospective__Metaclasses_-_Simple_Django_Models___Codewars" src="https://user-images.githubusercontent.com/46775/82662973-b950ec00-9c26-11ea-9186-48dcf467151d.png">

For each example, except for the first, the inline code span `a programming language keyword` is rendered as if it was a code block. Simulating the result in GFM inside a blockquote, the above renders as:

> - Not nested: `a programming language keyword`
> - Inside emphasis: *emphasising
    ```a programming language keyword```*
> - Inside bold: **strongly worded remark about
    ```a programming language keyword```**
> - Combining all 3: *Please* see the *__[documentation on 
    ```a programming language keyword```
    ](https://example.com)__*

#### Expected Behavior

Inline code spans should render as inline blocks; e.g. here on GitHub, the above (placed in a block quote) renders as:

> - Not nested: `a programming language keyword`
> - Inside emphasis: *emphasising `a programming language keyword`*
> - Inside bold: **strongly worded remark about `a programming language keyword`**
> - Combining all 3: *Please* see the *__[documentation on `a programming language keyword`](https://example.com)__*

#### Contexts

- OS: macOS
- Browser: Firefox, Chrome and Safari
- Browser Version: FF: 76, Chrome: 81, Safari: 13

**Comment by mjpieters** [comment]
Proposed fix:

- Change `.markdown p > code` to `.markdown p code`
- Optionally:
  - remove the `display: inline;` rule from `.markdown p code`
  - move the `padding: 10px;` CSS markup from `.markdown code` to `.markdown pre code`

```diff
 }
 .markdown code {
   font-family: "CamingoCode-Regular", monospace;
-  display: block;
-  padding: 10px;
   margin-bottom: 15px;
   font-weight: normal;
   overflow-x: auto;
@@ -3346,6 +3344,8 @@
   padding: 0.25em 0.5em;
 }
 .markdown pre code {
+  display: block;
+  padding: 10px;
   margin-top: 0;
   background-color: #222;
 }
@@ -3355,8 +3355,7 @@
 .markdown p:last-child {
   margin-bottom: 0;
 }
-.markdown p > code {
-  display: inline;
+.markdown p code {
   padding: 3.33333px;
   border-radius: 3px;
   border: 1px solid rgba(255, 255, 255, 0.125);
```

In CommonMark, code blocks are always rendered as `<pre><code>...</code><pre>` elements, inline code spans as `<p> (|<em>|<strong>|a)* <code>`, so it is much better to anchor CSS rules for code blocks to the `pre code` combo. You could even consider using `.markdown pre > code` to make the rule even more specific (although I can't think of a situation where CommonMark would ever output `<pre> (other elements) <code>` HTML.

**Comment by kazk** [comment]
@mjpieters Thanks for all the details! I just deployed the fix.
