### ISSUE TITLE
Can't create account or link to github

### ISSUE THREAD

**Issue by dataminer-x** [codewars/codewars.com#2146]
#### Describe the bug
I'm unable to create an account and get a server error. I'm also unable to link with my github account and get a 500 error.
#### To Reproduce

1. Go to 'create account'
2. Enter credentials
3. See error

**Comment by kazk** [comment]
Can you provide your browser information? I see some errors related to this and it's only from users using Android phones.

**Comment by mjpieters** [comment]
There have been a lot of issues with GitHub over the past 24 hours, not with CodeWars. Do check https://www.githubstatus.com/ to correlate 500 errors you saw.

**Comment by dataminer-x** [comment]
Using chrome or DuckDuckGo on an Android phone.

Chrome is: 81.0.4044.138
Ddg is: 5.54.0

I will try again in my desktop later.
