### ISSUE TITLE
Golang - Test data passed to challenger's function isn't consistent (?)

### ISSUE THREAD

**Issue by jmacwhyte** [codewars/codewars.com#2147]
#### Describe the bug
Although I've only seen this with one Kata, it doesn't appear to be caused by bugs in the Kata code, so I'm posting it here.

I'm doing https://www.codewars.com/kata/55983863da40caa2c900004e in Go. It appears the test data being piped into my function isn't the same as what is being sent to the console.

The author's test starts as such, with `NextBigger()` being the challenger's (my) function. `n` is a random int value:

    It(sprintf("Testing for %d", n),func() {
        user := NextBigger(n)
    ...

In my function, the very first line is:

    func NextBigger(n int) int {
        fmt.Printf("Input: %d\n", n)
    ...

When I run it, the console shows:

    Testing for 6072801
    Input: 761

Please let me know if I'm missing something.

#### To Reproduce

1. Go to 'https://www.codewars.com/kata/55983863da40caa2c900004e'
2. Start the training for Go, import("fmt") and in your function add `fmt.Printf("Input: %d\n", n)`
3. Run the tests and view the console output.

#### Expected Behavior

What is printed to the console by the test should also be sent to my function.

#### Contexts

Please complete the following information:

- OS: MacOS Catalina
- Browser: Chrome 81.0.4044.138

**Comment by kazk** [comment]
This is caused by a bug in the author's tests.

Basic tests looks like the following:
```go
	Context("Basic tests -- Small numbers",func() {
		fixed_small := [...][]int{
			[]int{12,21},
			[]int{513,531},
			[]int{2017,2071},
			[]int{414,441},
			[]int{144,414},
			[]int{8,-1},// extra edge case
		}
		for _,v := range fixed_small {
			It(sprintf("Testing for %d",v[0]),func() {
				user := NextBigger(v[0])
				Expect(user).To(Equal(v[1]))})}
	})
```
This causes the last pair `[]{8, -1}` to be passed to the user's solution every time.

To fix this, the values can be captured inside the loop first:
```go
		for _,v := range fixed_small {
			input := v[0]
			expected := v[1]
			It(sprintf("Testing for %d", input),func() {
				user := NextBigger(input)
				Expect(user).To(Equal(expected))})}
		})
```
I've fixed the kata. The same bug was there in the sample tests that you can see as well.

> Although I've only seen this with one Kata, it doesn't appear to be caused by bugs in the Kata code, so I'm posting it here.

Kata related issues are almost always caused by a bug in the kata or solution, especially for languages we've supported for years. So please use the kata discussion page first.

**Comment by jmacwhyte** [comment]
@kazk Thank you! I took a look at the Kata discussion page first, but since many people had reported problems and there were no replies for quite some time, I assumed it wouldn't get any attention there.

If you don't mind, could you briefly explain why the final value gets passed in every time in your first example? Is it because the anonymous function isn't actually run until the very end, and by that time `v` has been updated to point to the most recent (last) value?

Thanks for your time ;)

**Comment by kazk** [comment]
> I took a look at the Kata discussion page first, but since many people had reported problems and there were no replies for quite some time, I assumed it wouldn't get any attention there.

You might not, but this repository is not for kata issues.
I'd love to help if I had unlimited time and energy (or when I happen to have some time), but I cannot let users start asking for help here for each kata issue. Kata on Codewars are created and maintained by the community. Unfortunately not many of them are willing to fix their work :(

> Is it because the anonymous function isn't actually run until the very end, and by that time v has been updated to point to the most recent (last) value?

Yeah, exactly. `v` is a shared reference and it gets updated on each iteration. By the time the function is called, `v` points to the last one.
This is a very common mistake in Go and you can find many articles explaining it better than I can if you search, e.g. `golang loop closure`.

**Comment by jmacwhyte** [comment]
@kazk It makes perfect sense! I just didn't realize the anonymous functions would run later. Thanks for taking the time to explain it to me. And if I had known this was a problem with the test code itself I wouldn't have posted here :)

Take care!
