### ISSUE TITLE
"Submission timed out" even for trivial solutions

### ISSUE THREAD

**Issue by Jakub-CZ** [Codewars/codewars.com#215]
["The Millionth Fibonacci Kata" in Java](http://www.codewars.com/kata/53d40c1e2f13e331fc000c26/java) always returns:
"Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated."
- This issue lasts for several months now, but only for this kata AFAIK.
- I know this might be more of an issue with the kata itself, but the author is not responding for months.
- **Even solutions that just return a constant (return BigInteger.ZERO;) time out when submitted.**
- My test cases pass fine, so it must be something wrong with the author's test cases.

**Comment by bkaestner** [comment]
https://github.com/Codewars/codewars.com/wiki/Error-messages:-Submission-timed-out

**Comment by Jakub-CZ** [comment]
But is it really the case, when the user test cases pass, while the author's ones don't?

**Comment by bkaestner** [comment]
Yes.

**Comment by khuong291** [comment]
@bkaestner Hi. I would like to know when Swift will be able on Codewars? :horse:

**Comment by bkaestner** [comment]
@khuong291, you're asking the wrong guy. In the wrong thread. In the wrong repository. You can [ask here](https://github.com/Codewars/codewars-runner/issues/new).

**Comment by khuong291** [comment]
Ok.

**Comment by kazk** [comment]
Apparently `jvm-runner` had some issues in 2015 which seems to be resolved now. See #169.
Please let me know if this isn't fixed.
