### ISSUE TITLE
I'm getting a white screen on the output page and it just shows red or green depending on the solution

### ISSUE THREAD

**Issue by higreenogre** [codewars/codewars.com#2151]
Until yesterday it was fine but the time I switched to my other windows guest account and came back this error popped up and there is no way of seeing the test outputs

**Comment by kazk** [comment]
I'm not sure what you mean by white screen on the output page. Can you post a screenshot?

**Comment by higreenogre** [comment]
![Capture](https://user-images.githubusercontent.com/65718319/82981812-e3772500-9ffd-11ea-9771-844aae445b14.PNG)

**Comment by higreenogre** [comment]
![Capture](https://user-images.githubusercontent.com/65718319/82981851-f4279b00-9ffd-11ea-94a5-2ed6f3438edb.PNG)

**Comment by higreenogre** [comment]
![Capture](https://user-images.githubusercontent.com/65718319/82981971-3c46bd80-9ffe-11ea-92f3-237f94d63dc8.jpg)

**Comment by higreenogre** [comment]
![Capture](https://user-images.githubusercontent.com/65718319/82982366-1cfc6000-9fff-11ea-9208-51de63c4f79e.jpg)

**Comment by higreenogre** [comment]
not white, more grey

**Comment by kazk** [comment]
Do you see any errors in console (Developer Tools)?

**Comment by higreenogre** [comment]
okay I'm not exactly sure what I did but it seemed to be fixed. I'll tell you what I did do tho, I copied the url and opened it on microsoft edge and it seemed to work perfectly fine on it and it was some internal issue in chrome and then in  the console it showed some error and idk I refreshed the page and it seemd fine. sorry to bother but I'm bamboozled myself by what that has just transpired.
