### ISSUE TITLE
Typo in the Tips pop-up

### ISSUE THREAD

**Issue by grimmer-std** [codewars/codewars.com#2152]
#### Describe the bug
There is a typo in the first tips screen you get after starting your first "real" kata.

#### To Reproduce

1. Create new account.
2. Set it up.
3. Click on "Train" button.
4. See the typo.

#### Screenshots

![typo__first_tip_codewars](https://user-images.githubusercontent.com/12690999/83032854-a4b19100-a036-11ea-8a6b-b3e913f6ac25.PNG)

#### Contexts

Please complete the following information:

- Browser: Chrome
- Browser Version: 81 64 bit

**Comment by kazk** [comment]
Fixed. Thanks for reporting!
