### ISSUE TITLE
The buttons of the "replace in code" menu are too small

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2156]
After the UI update, the button styling in "Replace" menu (`Ctrl + H`) got worse. Instead of big buttons with readable text and gray background we've got this:

![image](https://user-images.githubusercontent.com/31668662/83300473-bcd50c00-a200-11ea-9958-ce7acf3a17bf.png)

**Comment by kazk** [comment]
I have no idea where that comes from.
I've never seen it before and `Ctrl+H` opens my browser history.

**Comment by kikkomans** [comment]
Shortcut works but editor has to be focused.

**Comment by kazk** [comment]
I had the editor focused. I tried again with same result.

Are you guys on macOS? I'm on Linux so it might be conflicting with the browser shortcuts.

**Comment by kikkomans** [comment]
I'm also on linux with latest firefox, but that maybe because I'm on local keyboard layout.

**Comment by kazk** [comment]
OK, I got it now. This doesn't work when you have Vim mode on.

**Comment by kazk** [comment]
Fixed
