### ISSUE TITLE
The color of `.cm-meta` is too dark on dark theme

### ISSUE THREAD

**Issue by kazk** [codewars/codewars.com#2158]
> I've just noticed that pre-processor direcrives in C/C++ are in purple which is hardly readable in dark mode (ealier it was gray, I believe). A similar thing could be happening in other languages too.
>
> ![image](https://user-images.githubusercontent.com/31668662/83242427-11e33480-a1a5-11ea-8871-91db2e48cb04.png)
>
> Edit: same thing with decorators in Python
>
> reported by @FArekkusu  https://github.com/codewars/codewars.com/issues/2081#issuecomment-635864784

**Comment by kikkomans** [comment]
Same is true for spread operator in JS

![cw](https://user-images.githubusercontent.com/64275515/83325073-df4f3f80-a269-11ea-9fd4-781c015b0138.png)

**Comment by kazk** [comment]
I don't understand why that's a `cm-meta` and not `cm-operator` :(

I'll revert `.cm-meta` back to unstyled on dark theme early this week. Previously the dark theme didn't have the color set for `cm-meta`, but the light theme did and I added the color without thinking too much when I was unifying the rules.

**Comment by kazk** [comment]
Deployed
