### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by rcfroggatt786** [codewars/codewars.com#2160]
I found on the 'forks' page the following text: "Looks like no one has yet to fork an existing solution:"
This is a double negative which implies everyone has forked a solution. Alternative wording: 'no one has forked an existing solution yet'
link example:
https://www.codewars.com/kata/53697be005f803751e0015aa/forks/c
user name:
rcfroggatt786

**Comment by kazk** [comment]
Fixed

**Comment by rcfroggatt786** [comment]
Thanks.
