### ISSUE TITLE
"-->" character sequence is highlighted as a comment in some languages

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2164]
In JavaScript and Typescript (maybe some other languages too) code that comes after `-->` character sequence is highlighted as a comment ([this can be seen in this kata for example](https://www.codewars.com/kata/54521e9ec8e60bc4de000d6c)):

![image](https://user-images.githubusercontent.com/31668662/83905503-733d7180-a76a-11ea-883b-0e69b62f2884.png)

**Comment by kazk** [comment]
It's reproducible on https://codemirror.net/mode/javascript so it's a bug in CodeMirror.
![image](https://user-images.githubusercontent.com/639336/83922276-e1674180-a734-11ea-94e7-22e37be8cff8.png)

So please let them know instead. I'll update the version when the fix is published.

**Comment by kazk** [comment]
Updated CodeMirror
