### ISSUE TITLE
There are no items to display

### ISSUE THREAD

**Issue by telbarNick** [codewars/codewars.com#2165]
When I try to search some kata, I most of the time get this message - "There are no items to display".

![image_2020-06-07_18-36-24](https://user-images.githubusercontent.com/66550270/83973275-ede2ca00-a8ed-11ea-8022-5142af9930b5.png)

- telbar
- Windows 10
- Google Chrome
- 83.0.4103.61

**Comment by FArekkusu** [comment]
Maybe you have no languages selected in your [training setup](https://www.codewars.com/trainer/setup)?
