### ISSUE TITLE
Markdown Tables Generator doesn't work anymore

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2167]
For example see <https://www.codewars.com/kata/5772382d509c65de7e000982>.

 index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
 - |-|
  *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8
---------------------------------------------------------------------------

index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
 - |-|
  *u*|8|8|10|9|10|11|11|12|12|12|12|...
  
is not displayed as a table but as something unreadable.

**Comment by kazk** [comment]
It doesn't look like a valid syntax at all so I'm surprised that it ever worked.
I [tried with various versions of the markdown library we use](https://marked.js.org/demo/?text=Be%20u(n)%20a%20sequence%20defined%20by%20u(1)%20%3D%20u(2)%20%3D%201%20and%20by%20the%20table%20below%20up%20to%20u(23)%3A%0A%0A%20index%7C**1**%20%7C**2**%7C**3!**%7C**4!**%7C**5**%7C**6**%7C**7**%7C**%3F8**%7C**9**%7C**10**%7C**11**%7C**12**%7C%0A%20-%20%7C-%7C%0A%20%20*u*%7C1%7C1%7C%5B2%5D%7C%5B3%5D%7C3%7C(4)%7C(5)%7C%3F5%7C6%7C6%7C6%7C8%0A---------------------------------------------------------------------------%0A%0Aindex%7C**%3F%3F13**%20%7C**14**%7C**15**%7C**16**%7C**17**%7C**18**%7C**19**%7C**20**%7C**21**%7C**22**%7C**23**%7C...%7C%0A%20-%20%7C-%7C%0A%20%20*u*%7C8%7C8%7C10%7C9%7C10%7C11%7C11%7C12%7C12%7C12%7C12%7C...%0A%20%20%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.8.2), but I can't find a version that creates a table out of this syntax.

As you can see it also doesn't work here on GitHub either. We use [Marked](https://marked.js.org/#/README.md) with GitHub Flavored Markdown enabled.

---

Is the following what you want?

|index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8|

---------------------------------------------------------------------------

|index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| *u*|8|8|10|9|10|11|11|12|12|12|12|...|

---

If so,

```
 index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
 - |-|
  *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8
---------------------------------------------------------------------------

index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
 - |-|
  *u*|8|8|10|9|10|11|11|12|12|12|12|...
```

Remove `- |-|` (?) in between the rows:
```
index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
  *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8

---------------------------------------------------------------------------

index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
  *u*|8|8|10|9|10|11|11|12|12|12|12|...
```

Add `|` to both sides:
```markdown
|index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
| *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8|

---------------------------------------------------------------------------

|index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
| *u*|8|8|10|9|10|11|11|12|12|12|12|...|
```

Add separator between the header and the row (each cell must have at least 3 `-`):
```markdown
|index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8|

---------------------------------------------------------------------------

|index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| *u*|8|8|10|9|10|11|11|12|12|12|12|...|
```

See https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

**Comment by g964** [comment]
I think my paste was bad in my first post. In the kata description it is:

Be u(n) a sequence defined by u(1) = u(2) = 1 and by the table below up to u(23):

 index|**1** |**2**|**3!**|**4!**|**5**|**6**|**7**|**?8**|**9**|**10**|**11**|**12**|
 - |-|
  *u*|1|1|[2]|[3]|3|(4)|(5)|?5|6|6|6|8
---------------------------------------------------------------------------

index|**??13** |**14**|**15**|**16**|**17**|**18**|**19**|**20**|**21**|**22**|**23**|...|
 - |-|
  *u*|8|8|10|9|10|11|11|12|12|12|12|...

Anyway I can assure you it worked and nobody said something about it until today.
I am so sorry I have taken much of your time with a bad paste (only excuse : you could have taken a look at the kata description :-)
Excuses and thanks

**Comment by g964** [comment]
I think the "*" have disappeared when I pasted the table here. Anyway I can assure you that it worked and nobody complained until today. I tried it - taken from the present kata description - at <https://markdown-here.com/livedemo.html> and it works there.
I am so sorry from having taken so much of your time (only excuse : you could have had a look at the kata itself:-)
Excuses and thanks!

**Comment by kazk** [comment]
> Anyway I can assure you it worked and nobody said something about it until today.
> I am so sorry I have taken much of your time with a bad paste

No need to apologize. It probably did work 4 years ago, but I simply couldn't reproduce it now.

> (only excuse : you could have taken a look at the kata description :-)

I did. I was surprised that it worked in the past and thought you pasted incorrectly. See the demo page I included in my comment, I copied the text from the kata description.

> I think the "*" have disappeared when I pasted the table here.

That's because it's rendered as markdown and `**bold**` make it **bold**.
I can look see the original text too:

![image](https://user-images.githubusercontent.com/639336/84191718-c60a7800-aa4d-11ea-9bf8-fa290103094b.png)

What you posted looks the same as the kata description and what you originally posted.

**Comment by g964** [comment]
OK. I think the issue can be closed.

**Comment by kazk** [comment]
> I tried it - taken from the present kata description - at https://markdown-here.com/livedemo.html and it works there.

Markdown Here seems to use super old version of Marked so that makes sense. Codewars probably used that version many years ago when you created this kata.

**Comment by g964** [comment]
Well, I am too old too!
