### ISSUE TITLE
SyntaxError when deleting a kata

### ISSUE THREAD

**Issue by ggorlen** [codewars/codewars.com#2174]
#### Describe the bug
`Uncaught SyntaxError: Unexpected identifier` is thrown when attempting to delete a new kata (unsaved or saved). Response object is `{success: false, message: "resource not found", status: 404}` although the headers show:

Request URL: https://www.codewars.com/kata/new/destroy
Request Method: DELETE
Status Code: 200 

#### To Reproduce

1. Go to `https://www.codewars.com/kata/new`
2. Make some edits to the code area
3. Click on `[Delete]`
4. Click `[Yes]`
5. Nothing will happen on the page--open console to see the error.

#### Expected Behavior

I expected kata to be deleted, see a confirmation message and to be redirected to another page.

#### Screenshots

![cw](https://user-images.githubusercontent.com/17895165/84537096-f2b7cd00-aca3-11ea-868e-8b11d13bdfee.gif)

#### Contexts

Please complete the following information:

- Codewars username: ggorlen
- OS: Windows 10
- Browser: Chrome
- Browser Version: Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by kazk** [comment]
I can't reproduce this for saved kata. It shouldn't make a request to ` https://www.codewars.com/kata/new/destroy` when it's saved and have an id.

The delete button shouldn't be shown when it's not saved so I'll fix that.

**Comment by ggorlen** [comment]
Thanks for looking into it! I was able to repro it again on a saved challenge following the steps above--I hit `[Save]` after adding some gibberish text. But the first time I click `[Delete]`, nothing happens either on the page or the console. After a second click, though, I get the error. Let me know if there's any other info I can add to help.

**Comment by kazk** [comment]
Thanks, that helps a lot. I still couldn't reproduce locally, but was able to reproduce this on production...

> But the first time I click `[Delete]`, nothing happens either on the page or the console.

I think the issue is here, but I'm not sure what's going on yet.

Paths should look like the following:

1. New Kata: `/kata/new/:language`
    a. Deleting here is invalid operation so I'll hide Delete button before save
2. After Save: `/kata/:kata_id/edit/:language`
3. After Delete: `/kata/new/:language` (should also show a message about successful deletion)
    a. Same as 1 so it's invalid to delete here

So I'm guessing something is messed up between 2 and 3 so you're seeing the page stuck in step 2, but it's actually in step 3.

**Comment by kazk** [comment]
Looks like some clean up task done after deleting a kata is taking too long. I'll try optimizing or moving that to a worker.

**Comment by kazk** [comment]
Fixed. Thanks for Reporting.
