### ISSUE TITLE
Lean solution page broken

### ISSUE THREAD

**Issue by Steffan153** [codewars/codewars.com#2175]
https://www.codewars.com/kata/5cfd36be4c60c3001b8fb38a/solutions/coq works fine, but when you switch to Lean (only solution), it goes to a strange error: https://i.imgur.com/qc7rnsw.mp4
The sun in this part is funny: https://i.imgur.com/jIOZFGJ.png

**Comment by kazk** [comment]
Fixed. Thanks for reporting.
