### ISSUE TITLE
Warn users before forfeiting all languages on editing

### ISSUE THREAD

**Issue by falcowinkler** [codewars/codewars.com#2176]
#### Is your feature request related to a problem? Please describe.
Clicking the edit button forfeits / unlocks a kata completely on all languages without warning. This is problematic because it is easy to click that button by accident (it's right next to the collect button). It might also be problematic because users might believe that they are just forfeiting the language they want to edit.

#### Describe the solution you'd like
A simple banner that warns about forfeiting the kata completely. Another improvement would be to have the editor just forfeit the languages that you are actually editing.

#### Describe alternatives you've considered
Perhaps it is not as annoying for other users, so a "don't show again" checkbox could make sense.
Another idea would be to tell users to explicitly forfeit the languages they want to edit on the solution page, so it is only possible to edit already solved katas.

**Comment by FArekkusu** [comment]
Duplicate of #1957

**Comment by falcowinkler** [comment]
👍 closed as duplicate of #1957
