### ISSUE TITLE
Ordered lists are rendered incorrectly

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2177]
After a recent update the ordered lists are rendered incorrectly in comments and descriptions: the left padding is applied, but the numbers are not shown anymore.

Here's how a comment looks when editing:

![image](https://user-images.githubusercontent.com/31668662/84593457-1b32f900-ae55-11ea-8a21-2a12ab48f20e.png)

And here's how it looks after publishing:

![image](https://user-images.githubusercontent.com/31668662/84593490-2d149c00-ae55-11ea-95e9-ebfe215be517.png)

**Comment by kazk** [comment]
Fixed. Thanks for reporting.
