### ISSUE TITLE
Broken kata

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2181]
The katas listed below are broken: empty languages-dropdown, no initial solution, stub sample tests, the kata is not being added to my `Unfinished` list, and `Train` button is displayed instead of `Train again` on the details/discourse pages.

- [x] [Easter egg list in ReactJS](https://www.codewars.com/kata/5a95947f4a6b342636000173)
- [x] [Truncate paragraph using higher-order component in React JS](https://www.codewars.com/kata/5a667bf8e6be382ecd000102)
- [x] [Use recompose's withProps to transform the supplied props to a React component](https://www.codewars.com/kata/5ab109168d28f650b700013b)

**Comment by kazk** [comment]
Thanks for reporting. For some reason, these didn't show up when I checked for kata that's Node 6 only before removing Node 6.

I'll fix these using some hack to use the React 16 environment used on Qualified.
