### ISSUE TITLE
Can not see Output results

### ISSUE THREAD

**Issue by gitriyad** [codewars/codewars.com#2184]
I can not see any output result only red and green background appears. I submit a screenshot please check and give me a suggestion.
![Capture](https://user-images.githubusercontent.com/62800128/85800109-314c8d80-b762-11ea-8859-69b2016099c2.PNG)

**Comment by kazk** [comment]
Please use the issue template next time to provide all the relevant information.

Do you see any error in the console?
Can you reproduce it with the browser extensions disabled? (Try to open the page in Private/Incognito window).

**Comment by hobovsky** [comment]
The issue resurfaces from time to time, recently reported again on Gitter:

> hi guys, I am doing tasks on codewars and before everything was fine, the tests passed, but now there is some bug and when trying to pass the test in the "Output" window, just a gray screen appears, maybe someone has already encountered a similar problem, thanks in advance `http://prntscr.com/u1hxgq`

But still, no details on it.

**Comment by MichaelNeikovych** [comment]
if it helps to anyone - I disabled the browser extension "ADGUARD" and the tests started to display

**Comment by NikitaPolchik** [comment]
My solution:
I started to delete extensions one by one installed on my browser(chrome). Each time I refreshed the page on the codewars website. That way I was able to find malfunctioning extension that meses up the website. I reinstalled all extensions back, except the broken one. All good so far.
By the way even at the end of 2024 this bug still persists.

**Comment by ChaoticGoodBarbarian** [comment]
So what extension caused this? Got the same problem on linux, deleted all my extensions, and it didn't help at all. Works fine on my windows laptop btw...

**Comment by NikitaPolchik** [comment]
> So what extension caused this? Got the same problem on linux, deleted all my extensions, and it didn't help at all. Works fine on my windows laptop btw...

I'm using win 11, cannot tell anything about linux. I don't remember the extension's exact name but it was "VPN something". Like "FreeVPN", "RangeVPN", "GimmeADollarVPN"...

**Comment by ChaoticGoodBarbarian** [comment]
Deleted Urban VPN extension and all got good. Thank you! I wonder what is the problem between VPN extensions and codewars
