### ISSUE TITLE
Enable autoCloseBrackets and smartIndent

### ISSUE THREAD

**Issue by Manish-Giri** [codewars/codewars.com#2189]
#### Describe the bug

I used to solve problems on Codewars frequently till last year. Today when I returned, I found several features missing - opening brackets/braces aren't closed automatically, code on a new line isn't automatically indented to the correct level, and so on.

If I remember correctly, these features were there before. Have they been removed now?

#### To Reproduce

Steps to reproduce the behavior (some examples):

1. Type `{`, closing `}` is not inserted.
2. Press enter after writing a for loop - `(for let i = 0; i < arr; i++)`, cursor is still at the very beginning of next line, not indented.

Please complete the following information:

- OS: Windows 10
- Browser: Microsoft Edge Chromium
- Browser Version: 83.0.478.58 (Official build) (64-bit)

**Comment by kazk** [comment]
> If I remember correctly, these features were there before. Have they been removed now?

No, `autoCloseBrackets` was never set and `smartIndent` is `false` since at least 7 years ago.

I'll enable these on next deploy. I need to update CodeMirror for a bug fix that was released too.

**Comment by kazk** [comment]
Deployed

**Comment by FArekkusu** [comment]
It looks like auto-indent always inserts 2 spaces even though in some languages (Python, Rust, maybe more) pressing `tab` inserts 4 spaces instead. @kazk could auto-indent be tweaked to make these consistent?

**Comment by kazk** [comment]
Setting `indentUnit` to the `tabSize` should work. I'll let you know when the fix is deployed.

**Comment by kazk** [comment]
Deployed

**Comment by Blind4Basics** [comment]
![image](https://user-images.githubusercontent.com/32236948/86517094-60c85d80-be26-11ea-8855-856dfbc7d85c.png)

The auto-indentation is currently not keeping the indentation that was introduced by the user. In the picture above, I'd expect the "pointer" to be aligned with the definition of `j`, or at least, consistent with the last parentheses or brackets opening.

doable?

**Comment by kazk** [comment]
@Blind4Basics Can you open a new issue instead? This is about enabling it. I don't know if CodeMirror can do that, but we can look into it.

**Comment by Blind4Basics** [comment]
:+1:
