### ISSUE TITLE
"<String>" becomes invisible

### ISSUE THREAD

**Issue by 842Mono** [Codewars/codewars.com#219]
Whenever I type "<String>" it disappears! Even in comments! I don't think it's a browser issue coz I've tried google chrome and ffox. Maybe there's something I don't get.

Anyway look at this screenshot: https://drive.google.com/file/d/0B0f0nmVh2CHdMXFPZTRTWXBwRDA/view?usp=sharing

**Comment by 842Mono** [comment]
oh look! even here on github! In between the "" there should be < String >. It just disappears

**Comment by bkaestner** [comment]
@842Mono That's called HTML. See section [4.1.3 of the codex](https://bkaestner.github.io/codewars-rules/#think-of-the-html). Make sure to use `&lt;String&gt;` (results in &lt;String&gt;).

**Comment by kazk** [comment]
See #844 for recent updates.
