### ISSUE TITLE
Ranked points wasn't added.

### ISSUE THREAD

**Issue by SubtRose** [codewars/codewars.com#2193]
#### Describe the bug
I had 5th rank and 99,8% overall progress. After i have decided one kata, but rank wasn't upped. Please, need help, losing points for such kata is a pity!

#### Info
- My codewars username: SubtRose
- Soluted kata: https://www.codewars.com/kata/5265b0885fda8eac5900093b

**Comment by kazk** [comment]
Fixed. For unknown reason, it was marked as ineligible for points.
