### ISSUE TITLE
Cannot test solution on Firefox (Ubuntu 18.04 LTS) 

### ISSUE THREAD

**Issue by krishrpatel** [codewars/codewars.com#2195]
#### Describe the bug
I opened multiple katas and tried submitting solutions by clicking test and/or attempt. Doing this resulting in nothing but a black output screen. I restarted my computer and this problem still persists. I checked on google chrome and everything works as normal. 

#### To Reproduce

1. Use Ubuntu 18.04 LTS
2. Use firefox
3. Go to a codewars kata
4. Try to submit a solution (even just by typing return)
5. Be greeted with a blank output screen in which nothing changes. 

#### Expected Behavior
I should be able to view the result of my code and which test cases I got right. 

#### Screenshots
![image](https://user-images.githubusercontent.com/13796805/86982217-bd918400-c156-11ea-9b07-725617ee1d01.png)
![image](https://user-images.githubusercontent.com/13796805/86982268-da2dbc00-c156-11ea-9a66-1cbbd4b5e521.png)

#### Contexts

Please complete the following information:

- Username: krishp
- OS: Ubuntu 18.04
- Browser: Firefox
- Browser Version: 78.0.1

**Comment by kazk** [comment]
Codewars should support Firefox well (I use it).

Do you have any extensions enabled? Can you try in Private window?

**Comment by krishrpatel** [comment]
Hmm. After taking your advice I realized that there is a problem with my adblock. For some reason it blocks the output screen. This is weird as I have used codewars many times before and this never happened with this adblock extension. Anyway, thank you for your time.
