### ISSUE TITLE
Dashboard disfigured by a comment!

### ISSUE THREAD

**Issue by CoderAlan24** [codewars/codewars.com#2197]
![Screenshot_20200710-223802_Chrome](https://user-images.githubusercontent.com/59861270/87180429-25ce9a00-c2fe-11ea-9da3-573184d158ab.jpg)
#### Many a times when my pc is off, I use my mobile for codewars! I use the site as desktop mode on chrome! This is an issue I faced today. A comment disfigured my dashboard. I know this a silly thing to report as the site isn't meant for mobile users but I felt like it should be taken care of!

- OS: [Android (Pie)]
- Browser: [Chrome(Lastest Version available on Googleplaytore)]

**Comment by kazk** [comment]
Fixed
