### ISSUE TITLE
The background of the code block is cut off on the dashboard if they are too wide

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2204]
Comment in the discourse section:

![image](https://user-images.githubusercontent.com/31668662/87705312-64ed6700-c7a6-11ea-9d56-31bfc5c4a52c.png)

And the same comment on the dashboard:

![image](https://user-images.githubusercontent.com/31668662/87705611-d5948380-c7a6-11ea-8a50-8e69bc95aa82.png)

**Comment by kazk** [comment]
This comment used HTML `<pre></pre>` to wrap the entire message. It works as expected if Markdown code fences are used.

Not sure if I should add `overflow-x: auto` to `.markdown pre` because that can affect unexpected parts.

**Comment by kazk** [comment]
Fixed
