### ISSUE TITLE
Just out of curious, what language & tools does codewars use to write the platform itself?

### ISSUE THREAD

**Issue by kuchaguangjie** [codewars/codewars.com#2206]

**Comment by DonaldKellett** [comment]
Probably Ruby on Rails and some form of SQL as far as I know, but don't take my word for it.

Anyway, for casual questions such as this one, I would recommend dropping by our [Gitter channel](https://gitter.im/Codewars/codewars.com) instead of opening a dedicated issue.

**Comment by kazk** [comment]
Backend: Ruby on Rails with MongoDB, Redis, Elastic Search
Frontend: jQuery (I'd like to start rewriting with SSR Vue)
