### ISSUE TITLE
Bad image link on landing

### ISSUE THREAD

**Issue by ggorlen** [codewars/codewars.com#2208]
#### Describe the bug
An image of a person on the landing page appears to be broken. https://pbs.twimg.com/profile_images/555136810431418370/jWfngZ-t_bigger.jpeg

#### To Reproduce

1. Go to `codewars.com` when not logged in so you're not redirected to the dashboard.
2. Scroll down to 'Kevin Granger'.
3. See broken image.

#### Screenshots

![badimg](https://user-images.githubusercontent.com/17895165/88077956-bbed9600-cb30-11ea-9ffa-0e0ddb52ac10.png)

**Comment by Blind4Basics** [comment]
* landing page==? the dashboard?
* who's that person? An allies of yours? yourself?
* a direct link to his profile might be more useful (I couldn't find him, actually)

**Comment by ggorlen** [comment]
@Blind4Basics Maybe my terminology is off, but the CW homepage (https://www.codewars.com -- visit it when you're not logged in so you aren't redirected to the dashboard) has basically a single call to action, so I'd call it a landing page. Maybe "homepage" is a better term, but no, it's not the dashboard. 

I have no idea who the person is and I don't know if they have a profile at all on Codewars (I'd assume so since they endorsed it, but it may be a username totally unrelated to their twitter handle or real name).

**Comment by hobovsky** [comment]
@Blind4Basics landing page is the page displayed to a user entering http://codewars.com, i.e. the main page, before you log in. Missing image is an avatar on one of appraisal tweets, I believe.

![image](https://user-images.githubusercontent.com/23709795/88080883-f599bd80-cb7f-11ea-8c8c-d7d78fb55399.png)

**Comment by Blind4Basics** [comment]
oh, ok. As I'm always logged in... x)

**Comment by kazk** [comment]
Fixed
