### ISSUE TITLE
Solution is neither appearing on solution page nor under the "My Solution" tab.

### ISSUE THREAD

**Issue by K-D521** [codewars/codewars.com#2210]
I encountered this bug 3-4th time

sequence: 
 - complete solution of kata and don;t submit solution
 - go to any other tab of codewars and refresh
 - then submit and whoaaa solution's gone..

then i tried to change few things on my solution and submit and "Submitting your final solution..." is keep appearing but it is not accepting my solution.

**Comment by kazk** [comment]
> go to any other tab of codewars and refresh

I don't think this is related unless I'm misunderstanding something. The way solutions page works have multiple issues and this is one of them.

Closing as a duplicate of already reported issues. See issues with labels [issues/solution-grouping](https://github.com/codewars/codewars.com/labels/issues%2Fsolution-grouping) and [issues/solution-not-shown](https://github.com/codewars/codewars.com/labels/issue%2Fsolution-not-shown).
