### ISSUE TITLE
Completed kata still listed as Unfinished

### ISSUE THREAD

**Issue by DenSel86** [codewars/codewars.com#2211]
#### Describe the bug

Why my profile has unfinished kata 'Directions Reduction' in PHP ?
I have 3 finished solutions of this kata, which are attempted and submited (my first solution was about one or two years old).
My profile is dselivanov86.

#### To Reproduce

1. I do kata 'Directions Reduction' in PHP. Press button 'Test', then 'Attempt', then 'Submit'. The browser redirects me to the solutions page.
2. I click 'View Profile', click Tab 'Kata', then 'Unfinished'.
3. Kata 'Directions Reduction' is still unfinished.

#### Screenshots

![image](https://user-images.githubusercontent.com/30651116/88535202-370fea00-d012-11ea-8bbe-36738ebfc84e.png)

![image](https://user-images.githubusercontent.com/30651116/88534756-6d009e80-d011-11ea-8329-51ca3d8a74df.png)

#### Contexts

- Codewars username (if account related): dselivanov86
- OS: Windows 7
- Browser: chrome
- Browser Version: 84.0.4147.89

**Comment by Blind4Basics** [comment]
Hi,

1. Plz don't post the solutions like that => remove the image, please
2. duplicate issue (#1966), so this post should been the one you originally posted on the original issue (which is still opened) ;)

Closing here. Please add the related (pruned) info in the other thread, thx.

cheers
