### ISSUE TITLE
Inline code borders overlap

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2214]
If there's an inline code right below another inline code, their borders will overlap:

![image](https://user-images.githubusercontent.com/31668662/88899902-4fbd1180-d257-11ea-97e0-dfdfddd3459a.png)

**Comment by kazk** [comment]
It doesn't overlap on my browser.

Firefox

![image](https://user-images.githubusercontent.com/639336/88956893-e804c780-d252-11ea-9a50-fac4e5b707c5.png)

Chromium

![image](https://user-images.githubusercontent.com/639336/88957037-200c0a80-d253-11ea-8079-6eebf2697226.png)

**Comment by kazk** [comment]
I'll decrease the vertical padding.

**Comment by kazk** [comment]
I wasn't able to reproduce, but I've decreased the vertical padding.
Please let me know if it's still overlapping.
