### ISSUE TITLE
Disabled comment section on solution page after a new update.

### ISSUE THREAD

**Issue by K-D521** [codewars/codewars.com#2215]
Why commenting on solution page is not working anymore!!

_**This is after new update**_ and only happening to newly created kata;s.

**Comment by kazk** [comment]
Can you provide more information? Which kata? What do you see?

The recent update was only CSS changes.

**Comment by K-D521** [comment]
Holy Moly!

**it;s working now.**
it was not working yesterday; i also confirmed this issue with B4B.
Sorry for interruption.

**Comment by K-D521** [comment]
@kazk 

It is working sometimes and sometimes not

see yourself : https://vimeo.com/443583253

**Comment by kazk** [comment]
Thanks for the video. I've never seen that before.
Anything in console?
