### ISSUE TITLE
Provide a way to link to a specific message in kata or solution's discourses

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2217]
## Currently

The only way to get a link to a specific message in the discourse is to go thourgh the links provided in the dashboard, or in the profile of a user, in the discouses section.
The means it's close to impossible to get that kind of link for old messages.

## Solution I'd like

Provide a button (like the `Link` one we can find on the solutions) giving the correct end point to target that message.

## Additional context

(note: that #2060 still happens from time to time)

**Comment by FArekkusu** [comment]
> The means it's close to impossible to get that kind of link for old messages

You can get the message id through HTML, but this is very cumbersome.

**Comment by hobovsky** [comment]
#2060 happens for me always.

**Comment by Blind4Basics** [comment]
> #2060 happens for me always.

even from the links in the dashboard?? :o: Maybe the browser enters the game, here?

**Comment by kazk** [comment]
You can now get the link on the time:

![image](https://user-images.githubusercontent.com/639336/89236970-e4e93e80-d5a6-11ea-91f7-8f84ca126e37.png)

**Comment by Blind4Basics** [comment]
cool, thx :)
