### ISSUE TITLE
Output window is EMPTY and is red and green !

### ISSUE THREAD

**Issue by Faousto007** [codewars/codewars.com#2221]
Good day! My IDEA solves this kata, but codewars shows nothing in output. Why?

I'm using 

import java.util.Arrays;
import java.util.Collections;
import java.util.stream.Stream;

in my code, but, i dont think that its the reason.

![kataissue1](https://user-images.githubusercontent.com/69185296/89257530-0a218f80-d62f-11ea-8934-d10850e3303c.jpg)

**Comment by Blind4Basics** [comment]
Hi,

That's not the place for this kind of issue. Here it is about problem with the website itself. You should ask in the discourse section of this kata instead.

Some readings that might help you at some point: https://github.com/codewars/codewars.com/wiki/Troubleshooting-your-solution

cheers

**Comment by Faousto007** [comment]
I see, thank you! I will look in another place.
 cheers
