### ISSUE TITLE
"Vasya and Drinks" is a copy from another site and needs to be retired

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2223]
As stated here: https://github.com/codewars/codewars.com/wiki/List-of-kata-which-are-potentially-plagiarized-or-copied-from-other-sites-without-proper-credit

Kata [Vasya and Drinks](https://www.codewars.com/kata/5555f47156d55fba5c000143):
   - Copy of [Drinks](https://codeforces.com/problemset/problem/200/B) problem from Codeforces
   - Still in beta
   - probably has to be retired

**Comment by hobovsky** [comment]
Also  [Johny and Trees](https://www.codewars.com/kata/552a79d9bbaaf41f99000fcf)
   - Copy of [Pashmak and Garden](https://codeforces.com/problemset/problem/459/A) problem from Codeforces, with very minor edits
   - Still in beta
   - probably has to be retired

**Comment by kazk** [comment]
Retired both. Can you keep track of the retired kata on that page as well? Maybe create a "Retired" section at the bottom and move them there retaining the information.

I'll probably introduce some kind of penalty later. This user is ranked 29th because of the copied challenges.
