### ISSUE TITLE
Discourses take long time to load on mobile devices

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2230]
When I am browsing CW on some of my mobile devices, discourses of every type (kata discourse, solution and translation comments, forums, etc.) with many posts take a very long time to show up. It does not seem to be a problem with transfer or volume of data, because progress bars go very quick in the beginning, but after that whole tab stops and the more posts is there, the longer the discourse takes to show up, often to the point the screen goes dark because of inactivity, and when it light it up, some browsers load the page again, repeating the process all over. It seems that some kind of DOM operations takes up significant amount of time. Delay seems to be linear wrt amount of posts, and when there's less than 200-300, things are somewhat OK. But for longer ones, I need a lot of patience.

I am not really sure if the problem is related to the amount of posts themselves, or maybe formatted code blocks cause the delay, or something else. My mobile devices are also not really performant, my phone is old LG D605, and tablet is Huawei MediaPad T3, but other websites and forums do not experience such problems, and long discourses load noticeably slower also on my PC.

**Comment by FArekkusu** [comment]
It's probably DOM manipulation. Every comment thread consists of a few dozen HTML elements, ignoring the comment's content which can be arbitrarily complex. Multiply that by a few hundred comments, and you get a 10-15 seconds wait (including the request which fetches lots of data).

**Comment by kazk** [comment]
This was improved by the rewrite.
