### ISSUE TITLE
Frequent HTTP 500s on TEST and ATTEMPT

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2231]
Since recently (yesterday or so) users seem to experience server errors when submitting their code: 
![image](https://user-images.githubusercontent.com/23709795/90385494-87172500-e083-11ea-9e6b-a8ba0e0e30d0.png)

Errors do not appear consistently, but are quite frequent. In my case, I'd say every second submit ends up failing. There's more users experiencing it, but I do not know any common pattern (like submitted language or something)

![image](https://user-images.githubusercontent.com/23709795/90385855-fee54f80-e083-11ea-94e4-14b6fbf60c20.png)

**Comment by andre-dasilva** [comment]
I do get this quit often too, since recently. I do most stuff with python, but i don't see a common pattern as well

**Comment by kazk** [comment]
Thanks for reporting. Some of the runner VMs ran out of the disks space. I'm deploying the fix right now.

**Comment by kazk** [comment]
Fixed
