### ISSUE TITLE
Roman Numerals Encoder 

### ISSUE THREAD

**Issue by Yeyvo** [codewars/codewars.com#2234]
hey, in [this kata](https://www.codewars.com/kata/51b62bf6a9c58071c600001b/) i put this code  https://pastebin.com/qsx2k1EX  but i keep having those errors https://prnt.sc/u4meuq ,my code works perfectly in C::B

**Comment by Blind4Basics** [comment]
Hi,

this repo is about codewars in a general meaning, not about problems while solving a kata. The discourse page of that kata is made for this kind of thing. But for instance, before going to raise an issue there, begin with [reading this](https://github.com/codewars/codewars.com/wiki/Troubleshooting-your-solution). If not enough, post in the discourse of the kata, but use the question label, not the issue one.

Cheers
