### ISSUE TITLE
Show all test data for failed tests

### ISSUE THREAD

**Issue by dkallen78** [codewars/codewars.com#2238]
#### Is your feature request related to a problem? Please describe.

I'm always frustrated when I'm trying to debug a challenge and the test data is incomplete. I'm working on "Split By Value" and for the tests I got wrong I am only given one of the two parameters, making it impossible to debug what isn't working in my code.

#### Describe the solution you'd like
Show all inputs that go into the tests. If a test requires two parameters to check, show both of the parameters in the output box along with the correct output and the faulty output.

#### Describe alternatives you've considered
In this case there is no alternative, w/out knowing the first parameter, I can't figure out why the code isn't working because I can't replicate the issue w/ missing data

#### Additional context
none

**Comment by DonaldKellett** [comment]
As mentioned in the Gitter chat, you can inspect the inputs to your function by printing them to the console, e.g. for JavaScript:

```javascript
function solutionUnderTest(arg1, arg2, ..., argn) {
  console.log(`Argument 1: ${arg1}`);
  console.log(`Argument 2: ${arg2}`);
  ...
  console.log(`Argument n: ${argn}`);
  // Do your usual stuff here
}
```

**Comment by dkallen78** [comment]
I wasn't aware before hand, but it's good to know. Thank you!
