### ISSUE TITLE
Lost all progress on Kata

### ISSUE THREAD

**Issue by jclmnop** [codewars/codewars.com#2239]
#### Describe the bug
Spent a while working on a Kata, after restarting my browser my entire solution is gone. Navigating to unfinished Kata and selecting it there takes me to the Kata page with a "train again" button. 

#### To Reproduce

1. Go to a Kata
2. Type out a solution
3. Restart browser
4. Kata is gone

#### Expected Behavior

Because there's an unfinished Kata section, I expected my unfinished solution to be saved here. I also remember it being saved in past Kata. 

#### Contexts

Please complete the following information:

- Codewars username (if account related): jclmnop
- OS: MacOS Mojave
- Browser: FireFox
- Browser Version: 80.0.1 (20200831163820)

**Comment by Blind4Basics** [comment]
Hi,

I guess you never ran the example tests or the full test suite? ("test" or "attempt" buttons) If so, that's "normal". To save your code, you have to send it to the server.

**Comment by jclmnop** [comment]
You are 100% correct. I wasn't aware that that's the only time it's saved. 

Well, now I know.

**Comment by hobovsky** [comment]
Using IDE to write your solution generally helps to prevent such situations, and helps with other things too.

**Comment by jclmnop** [comment]
Luckily I'd written the most difficult part in my IDE, because I wanted to test it separately.
