### ISSUE TITLE
HTML sanitization of program output

### ISSUE THREAD

**Issue by 1b8** [Codewars/codewars.com#224]
It appears that output printed by code is not sanitized for HTML. This means you can use the following (JavaScript):
```js
console.log('<a href="https://www.google.com">Google</a>');
```
to put a link into the output box:
![output](https://cloud.githubusercontent.com/assets/13689923/12151746/8af6eac8-b515-11e5-88d7-963cdf083f46.png)

**Comment by jhoffner** [comment]
This is by design. We use the same sandboxing as sites such as plnkr.co and codepen. We actually encourage kata creators to use HTML to create rich output - but very few rarely do.
