### ISSUE TITLE
Comments flagged as spoilers are visible

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2244]
For some reason I can see comments flagged as spoilers on [this discourse page](https://www.codewars.com/kata/5819c6c05d2358a3dc000096/discuss/csharp) even though I haven't replied to them, and haven't completed the kata. The issue persisted after reopening and reloading the page.

![image](https://user-images.githubusercontent.com/31668662/94348977-4e3a7a80-0049-11eb-9a76-0f731c18b45a.png)

I checked the comments under a few other katas I haven't completed, but everything worked correctly there.

Edit: as was suggested on gitter, accessing the editor could be the reason for this. I *really* doubt that I did, but that's probably the only explanation other than something being broken, so it should be checked as well.

**Comment by kazk** [comment]
According to the data, you viewed solutions at `2019-01-28 10:24:43 UTC` and that's why spoiler is not hidden from you.
