### ISSUE TITLE
When create Kata's test case, how to check whether a solution's source code contain string?

### ISSUE THREAD

**Issue by kuchaguangjie** [codewars/codewars.com#2249]
When creating a kata for `Java`, I don't want the user to use `BigInteger`, so how can I check that, and fail it if it's used.

**Comment by hobovsky** [comment]
It's very, very, _very_ difficult. The best idea would be to create the kata in a language which does not support big integers natively, for example C, or C++. It is possible to restrict java solutions, but it's **difficult**.

I used such technique in one of my translations, I will try to find it.

**Comment by hobovsky** [comment]
Here's kumite which presents one way of restricting used classes: https://www.codewars.com/kumite/5eb28dd1f323aa001eec971c?sel=5eb28dd1f323aa001eec971c

**Comment by hobovsky** [comment]
My solution for checking if source code does not contain forbidden words:

```java
  private static final String SOLUTION_PATH = "/home/codewarrior/solution.txt";
  private static final Set<String> DISALLOWED_STRINGS = new HashSet<>(Arrays.asList("reflection", "biginteger", "bigdecimal", "runtime", "process", "script"));
  @Test
  public void restrictedApisTest() {
    
    Pattern p = Pattern.compile("(?:^|[^\\\\])(?:\\\\{2})*+\\\\u+([\\da-fA-F]{4})"); 
    UnaryOperator<String> unescape = s-> {
      Matcher m = p.matcher(s);
      StringBuffer sb = new StringBuffer();
      while(m.find()) {
        String seq = m.group(1);
        char c = (char)Integer.parseInt(seq, 16);
        m.appendReplacement(sb, "");
        sb.append(c);
      }
      m.appendTail(sb);
      return sb.toString();
    };
    
    try(FileReader fr = new FileReader(SOLUTION_PATH);
        BufferedReader reader = new BufferedReader(fr)) {
        
        Optional<String> incorrectLine = reader.lines().map(unescape).filter(l -> { String line = l.toLowerCase(); return DISALLOWED_STRINGS.stream().anyMatch(d -> line.contains(d));}).findAny();
        if(incorrectLine.isPresent()) {
          String disallowedWord = DISALLOWED_STRINGS.stream().filter(word -> incorrectLine.get().toLowerCase().contains(word)).findAny().get();
          Assert.fail(String.format("Not allowed string [%s] found in line [%s]", disallowedWord, incorrectLine.get()));
        }     
        
      } catch(Exception ex) {
        ex.printStackTrace();
        Assert.fail("Test for disallowed APIs failed with an exception. Please raise a kata issue and provide the exception stack trace.");
      }
  }
```

It seemed to work for me back then, but I am pretty sure some sneaky solutions can pass it, because I definitely missed some possibilities of obfuscating the code or calling APIs some other way.

Bottom line generally is: it's heavily discouraged to create kata with language restrictions, because such restrictions are very difficult to enforce reliably.

**Comment by kuchaguangjie** [comment]
@hobovsky Thanks, the code does look difficult.
Maybe it's proper for codewars to provide an easy way to let the kata creator to get the source of solution as string in the `Preloaded` step? I'm not sure.

**Comment by hobovsky** [comment]
You did not understand: even if code of solution is available as string, it is not enough. BigInteger name can be escaped (heard of unicode escape sequences in source code?), escape sequences can be escaped, BigInteger can be called by reflection, or external program can be called (for example Python REPL). 

**IT IS DIFFICULT** to check if user used BigInteger **EVEN IF YOU SEE THE CODE**.

Don;t do that. Don't create such kata.

**Comment by kuchaguangjie** [comment]
@hobovsky Yep, you are right, if I create such a kata that hope to avoid such language feature, I would then just **suggest** the user not to use that to keep the fun, while give the kata a proper rank which will still be suitable even if they use it.
