### ISSUE TITLE
Counting CPU cycles as the objective ranking of users solutions

### ISSUE THREAD

**Issue by tsedii** [codewars/codewars.com#2257]
The CodeWars is a fantastic platform for growing developer's skills. 

But very much lacking the objective ranking criteria for users' solutions. 

It would help adequately assess the quality of the code of all users' solutions.

May be it will be possible to sort code by efficiency, through counting the total number of CPU cycles and instructions retired during the execution other users' solutions as was discribed in 
[https://stackoverflow.com/questions/42568557/how-to-count-the-total-number-of-cpu-cycles-and-instructions-retired-during](url)

**Comment by kazk** [comment]
Please read the similar discussion: #959
