### ISSUE TITLE
Not really a bug, rather kind of a "hack"

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2258]
The title of my kata <https://www.codewars.com/kata/5a057ec846d843c81a0000ad/discuss#5f9580772599610017d5e6fb>
has been modified to an insult by a guy named "n0pd" (1 dan in one month).

**Comment by kazk** [comment]
:(

The user deleted their account. The kata was editable by users with privilege to coauthor because one [suggestion](https://www.codewars.com/kata/5a057ec846d843c81a0000ad/discuss/shell#5c61e1a58303580008540944) has been open for 2 years.
