### ISSUE TITLE
Don't split the community

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#226]
I see some problems with the current approach for feature requests, bug reports and other discussions. There are currently three (four?) places where feature requests get posted:
- the old [feature request forum](http://www.codewars.com/topics/feature-requests)
- the new [ideas](https://codewars.ideas.aha.io/) (which apparently isn't known that well, see last post in feature request vs last post in ideas)
- this issue tracker (see #123, #113 or #114 for example)
- the [codewars-runner tracker](https://github.com/Codewars/codewars-runner/issues).

This produces an unnecessary split in the community, and makes it hard for you to know the current needs. From a usability point of view, the old feature request forum is bad. There's no search, old posts are unavailable and it's hard to track the status of the request. Tracking the request seems much easier on ideas, but requires an additional account, and the communication on ideas has been… low. 

The GitHub tracker doesn't provide voting (except for :+1: or :-1:), but the response time (either via an actual response or a label) is (subjectively) faster, which isn't a bad thing either. Still, it's an external site, so it doesn't generate any more page views (but also doesn't put any load on the forums).

And the codewars runner tracker,… well, let's forget about that one for a while.

So however you decide, make sure that the other ones get read-only (or in case of GitHub closed with a reference to the correct place). Otherwise the same requests will be put at different places to different times.

**Comment by CrazyMerlyn** [comment]
:+1:

**Comment by jhoffner** [comment]
Closing since GitHub is the only recommended place to log issues now.
