### ISSUE TITLE
Impossible to approve a translation of one of my kata done by somebody else

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2261]
Kata: <https://www.codewars.com/kumite/5d6944de7a60ba0017081f9d?sel=5d6944de7a60ba0017081f9d>
C translation by @rowcased of the kata "Bonuses".

I tried to approve it with Chrome, Firefox, Edge but nothing happens after I have clicked "approve" and "I am sure".

**Comment by kazk** [comment]
It has some merge conflict. It wasn't showing the error (#2262), but I just deployed the fix.
