### ISSUE TITLE
Reason why translation cannot be approved is not displayed

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2262]
I think it used to work some time ago, and for some reason stopped: when user attempts to approve a translation which cannot be approved, they are presented the "are you sure" confirmation dialog, and after confirming, nothing happens. UI does not display any hint why translation cannot be approved. But still, browser seems to receive the response from server why it's not possible.

**To Reproduce**
1. Go to any pending translation which cannot be approved because kata author is active, or there's description merge conflict
2. Click "approve", confirm
3. Observe how nothing happens

**Expected behavior**
UI should display some kind of feedback, potentially utilizing response returned from the server.
Even better, "Approve" button could be dimmed and reason could be displayed right away, if translation cannot be approved.

**Screenshots**

Answer from the server visible in browser tools:

![image](https://user-images.githubusercontent.com/23709795/97641103-6fc0c480-1a42-11eb-8222-68cf4f91d65d.png)

-------

No feedback in UI:

![image](https://user-images.githubusercontent.com/23709795/97641056-53248c80-1a42-11eb-9f37-55c264862889.png)

------

Example translation which cannot be approved: https://www.codewars.com/kumite/551ef26c402803c7f5000446?sel=551ef26c402803c7f5000446

#2261 _could_ be related, but @g964 claims he does not see any error in browser console, so it might be something else.

**Comment by kazk** [comment]
Fixed
