### ISSUE TITLE
How to know how many hours I spent in codewars?

### ISSUE THREAD

**Issue by mrdulin** [codewars/codewars.com#2264]
**Is your feature request related to a problem? Please describe.**

I want to know how many hours I spent in codewars.

**Describe the solution you'd like**

Add information about how many hours I spent on a personal profile.

**Describe alternatives you've considered**

1. I don’t want to use the browser’s webpage online time statistics extension
2. Provide an API to query the time statistics is fine too.

**Comment by kazk** [comment]
We don't know either and have no plan to start tracking.
