### ISSUE TITLE
hi, im wondering about the points system, i finished a kata ,kyu 5 and got some points, i think befor solving it i had 2163 or 2153 and then after i solved it i had 2171 but then it got down to 2165, does anyone know if it is a bug or what is it? also some times when i solve some katas lets say kyu 7, i get 2 points and sometimes its 3, this is how its suppose to be? is it a bug? thanks for any respond![short description of the bug]

### ISSUE THREAD

**Issue by davidsimonfeldman** [codewars/codewars.com#2266]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
Please reopen using the issue template properly (replace sections inside `[]` and fill in the details).
