### ISSUE TITLE
'Failed to connect to the runner' or 'Failed to update the output theme' error messages.

### ISSUE THREAD

**Issue by dkadyrko** [codewars/codewars.com#2269]
**Describe the bug**
There are 2 error messages appears while trying to run test for RUBY language:
* Failed to connect to the runner
* Failed to update the output theme

**To Reproduce**
Right after opening or reloading page get 'Failed to update the output theme' message.
Clicking on TEST/ATTEMPT buttons shows 'Failed to connect to the runner' error message.

**Expected behavior**
No errors when click on TEST/ATTEMPT buttons

**Screenshots**
![Error](https://user-images.githubusercontent.com/36742052/99028631-744ea800-252d-11eb-8b24-4cee987fbda3.png)

**Browser**

- OS: macOS Catalina Version 10.15.6 
- Chrome - Version 86.0.4240.193 (Official Build) (x86_64)
- Safari - Version 13.1.2 (15609.3.5.1.3)

**Comment by kazk** [comment]
Thanks for reporting. I'm reverting the most recent deployment for now. I'll let you know when that's complete.

**Comment by dkadyrko** [comment]
You are very welcome! :D

**Comment by kazk** [comment]
Reverted the change so it shouldn't be happening anymore. I'll look into the cause.

**Comment by dkadyrko** [comment]
Thanks. Works for me now. Have a great day/night.
