### ISSUE TITLE
Still Java

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#227]
Since a few days I have been unable to publish Java translations. I always get:

> Failed to parse java class in code:
>import static org.junit.Assert.*;
>import org.junit.Test; ... etc...

It happens with different Java programs, even the simplest ones, whereas they work fine in Eclipse. Am I becoming dumb or is CW having problems with Java?

**Comment by bkaestner** [comment]
Please use appropriate issue titles. For example, "Failed to parse java class in translation" gives much more information to the maintainer than "Still Java".

**Comment by jhoffner** [comment]
Its probably CW having issues with Java. I'm in the middle of trying to push a big Strive release out but I'll take a look after that. Our Java support is actually implemented in Clojure, but we no longer have anyone on staff who knows clojure, so hopefully its not something with that. If so, I may need to call on you guys for some help.

**Comment by g964** [comment]
@bkaes : "Still Java" because I already posted many times about Java... see #209, #64 and so on. As you can see it was sufficient to have an answer from Jake:-) It's a real pain to try to write something in Java at CW, you never know if you can publish or re-publish.
@jhoffner : a big thank to take account of this problem!

**Comment by g964** [comment]
The problem of publishing a Java kata seems to have disappeared. I don't get anymore:
> Failed to parse java class in code
and I can publish.
But the problem of **re**-publishing a kata as noted in #209 is still there.
