### ISSUE TITLE
Server hangs upon publishing or saving translation

### ISSUE THREAD

**Issue by imjasonmiller** [codewars/codewars.com#2270]
**Describe the bug**
Attempting to save or publish a translation results in the server hanging on "Your results will be shown here."

**To Reproduce**
1.  https://www.codewars.com/kumite/5f464e0301e9c60029a9c14c?sel=5f464e0301e9c60029a9c14c
2.  https://www.codewars.com/kumite/5fade57c83d56000283f3d7c?sel=5fade57c83d56000283f3d7c

**Expected behavior**
The tests run and the translation is published.

**Screenshots**
![image](https://user-images.githubusercontent.com/12190184/99124113-daa4fa80-2601-11eb-86ad-f4b4d3171bc7.png)

**Browser**
Firefox Developer Edition 83.0b10 (64-bit)
Arch Linux 5.9.8-arch1-1

**Comment by kazk** [comment]
Thanks for reporting! The server is not hanging, but Codewars is not making request to the runner. I should

**Comment by imjasonmiller** [comment]
Great, glad it wasn't me! The thought of perhaps having submitted too many translations in a short period of time crept in :-)

If you need more information do let me know.

Have a great evening!

**Comment by kazk** [comment]
Deployed the fix
