### ISSUE TITLE
My total score dropped significantly

### ISSUE THREAD

**Issue by yuriDkLevchuk** [codewars/codewars.com#2272]
After being absent a few days, I completed two katas (Gerrymander Solver and Simple string expansion in Python) and by next morning I found that my score dropped by nearly 1000 pts, from over 4590+ to 3745, also lowering my rating from 1kyu to 2kyu. Here is my page: https://www.codewars.com/users/YuriL1967. I wonder what was the reason for the drop, and whether it was a bug or deliberate. It seems to be very similar to the issue from 2018 described here: https://github.com/Codewars/codewars.com/issues/1600.

**Comment by XRFXLP** [comment]
> I wonder what was the reason for the drop, and whether it was a bug or deliberate

It was deliberate.

**Comment by yuriDkLevchuk** [comment]
OK, thanks for letting me know.
