### ISSUE TITLE
copy/paste isssue- i code it on a different platform

### ISSUE THREAD

**Issue by GilCaplan** [codewars/codewars.com#2274]
Hi. the bug seems to not let me copy/paste any of the code from where I solve the question(solution) and where the sample tests are located. could have to do with the vim/emac options- not sure

https://www.codewars.com/kata/5a8d2bf60025e9163c0000bc/train/java
here is where I'm doing my current code.
I expected to be able to copy the text and paste it in eclipse and vice versa to work on my code.

Microsoft edge

thanks

**Comment by FArekkusu** [comment]
> the bug seems to not let me copy/paste any of the code

How are you doing the copy/paste?

> could have to do with the vim/emac options- not sure

So is Vim/Emacs mode active or not? If one of them is on, and you're trying to do `ctrl + c`/`ctrl + v`, then it wouldn't be surprising for these shortcuts to not work.

**Comment by GilCaplan** [comment]
ok. thanks

**Comment by GilCaplan** [comment]
Hi, figured it out. yes. sorry if i caused any issues
have a good day
