### ISSUE TITLE
[short description of the bug]

### ISSUE THREAD

**Issue by arendarczyk** [codewars/codewars.com#2280]
**Describe the bug**
One way works the other one doesn't

**To Reproduce**
```
data.map(([age, handicap]) => {
    if(age>54 && handicap>7)
      {
      return 'Senior';
      }
    else
      {
      return 'Open';
        }
  })
```

**Expected behavior**
completing the task

**Screenshots**
![unknown](https://user-images.githubusercontent.com/47572255/100671963-8ddf5480-3361-11eb-889f-42f9f23dfa0c.png)

**Browser**
google chrome

**Comment by kazk** [comment]
Please use the discussion page on Codewars to ask questions about kata.

Your solution is missing `return` inside the function.

**Comment by hobovsky** [comment]
Kata specific questions should be asked in kata discussion page: https://www.codewars.com/kata/5502c9e7b3216ec63c0001aa/discuss

Your code (the one on the screenshot) is not valid. The two functions, "działa" and "nie działa", are not equivalent.

The code you posted above works as expected.
