### ISSUE TITLE
Save search result as Collection

### ISSUE THREAD

**Issue by Nikolaiko** [codewars/codewars.com#2283]
**Is your feature request related to a problem? Please describe.**
I want to form list of kata's with same properties (all 1kyu kata's for Kotlin) and save it as collection. And be able return to this collection after few days and share it with friends. Right now I need to perform search every time when I need those kata's.

**Describe the solution you'd like**
I want to perform search (for example all 8 kyu for Swift language) and save all kata's as new collection.

**Describe alternatives you've considered**
At least I want button for each kata in search result to add it to existing collection.

**Comment by kazk** [comment]
> Right now I need to perform search every time when I need those kata's.

Why not just share <https://www.codewars.com/kata/search/swift?q=&r[]=-8&beta=false>?

This will be also up to date unlike a snapshot saved to a collection.

**Comment by Nikolaiko** [comment]
Because sharing it's just a one part, not most important one. Main thing is that I want to select kata's using search filter and then train them day by day. Right now I need to perform search everyday and select next task. I don't want to go to search set needed filters everytime.

You gave an idea that I can save link to search results, and return to those results every day. I will try this out it definetly easier. Thanks.

But still I think saving search results as collection can be more intuitive way.

**Comment by XRFXLP** [comment]
>  Right now I need to perform search everyday

If you don't wanna search everyday, you can bookmark the page.

**Comment by kazk** [comment]
Closing because collections are for you to curate and not for storing a search result. If I add this feature, someone will make a collection of 9K+ kata. Of course, I can add arbitrary limits, but that will end up being unintuitive. Codewars has enough of these unintuitive features that was added because it was possible.

> Because sharing it's just a one part, not most important one. Main thing is that I want to select kata's using search filter and then train them day by day. 

Providing quick access to the last search will make more sense. Or few private saved search where you can name them.
