### ISSUE TITLE
Error 400 cant use the site

### ISSUE THREAD

**Issue by Headshot56** [codewars/codewars.com#2285]
When I created my account I selected python as my language. I passed the test and linked my github. When I pressed enlist it says error400 and it makes me do the process again.

**Comment by kazk** [comment]
I don't see any drop in the number of signups so it should be something on your end. And I cannot help much with the amount of information you provided.
Please try again without any extension enabled and/or using Incognito/Private mode. If that doesn't work, please reopen using the issue template and attach screenshots.
