### ISSUE TITLE
Add an optional 'editorial' page for Kata creators to explain solution

### ISSUE THREAD

**Issue by JoJo10Smith** [codewars/codewars.com#2286]
**Is your feature request related to a problem? Please describe.**
I often review the solutions provided by other users but rarely is there an explanation of the algorithm used and an analysis of the problem. I find it frustrating as someone who wants to expand my knowledge of algorithms to not have a 'proper' explanation of the solution and instead have to deal with solutions that are often hard to understand since they have been coded in as few lines as possible.

**Describe the solution you'd like**

There could be an editorial page where the Kata creator (potentially even translators) could give an editorial of the problem and explain in detail the data structures/ algorithms used to solve the problem. This is similar to how Codeforces stream the solutions once a competition is done for users to understand how a potential solution was thought of.

**Describe alternatives you've considered**
I have googled many questions after I have solved them to find out the algorithm that was used and how to correctly/ efficiently solve the problem but would really appreciate it if this was added to the page where other user solutions have been added.

**Additional context**
Example: looking at the Kata: https://www.codewars.com/kata/54521e9ec8e60bc4de000d6c/train/python
I knew what the solution was since I have seen a similar problem but for someone that hasn't a description of the algorithm used to solve this problem would then help them quickly identify the solutions to other similar problems.

My Example Editorial:
1) Description of the Algorithm (Kadane's Algorithm)
2) Pages where the user can read more (Wikipedia, personal blog etc)
3) Solution walk-through in their language (Translators could receive additional honor for adding their solution code with an explaination)

I strongly believe this would be a great feature to add and would help new people learn more algorithms. Kata creators and translators already have the solution code (when they create the solution) all they would need to do is add comments/ explanations of their code so it is more understandable

![Capture](https://user-images.githubusercontent.com/64989097/102528892-30d7e400-406d-11eb-8d38-8a4776c0dc10.JPG)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1drt) by [Unito](https://www.unito.io)

**Comment by FArekkusu** [comment]
Even if such page existed, you can't force people to explain their solutions. And even if they want to do so, they can always put comments in their code, or on the solution-page. Both options are available to everybody, and not just authors/translators.

Also, never post solutions in the discourse. The spoiler flag can be worked around easily - you're only giving away the code.

**Comment by anter69** [comment]
> ...they can always put comments in their code, or on the solution-page. Both options are available to everybody, and not just authors/translators.
> Also, never post solutions in the discourse. The spoiler flag can be worked around easily - you're only giving away the code.

That is basically the existing solution for this "issue":
* explain your code using comments and you'll even get some upvotes, because people like that (for a reason);
* if you want to explain someone else's code, write a comment below the solution, and upvote that solution so that people will see it;
* if you want to give language-independent hints (e.g. an algorithm) you can do so in the general discourse, although pointing out the correct algo may spoil the fun (for some); and yes, never post solutions
