### ISSUE TITLE
Completed a kata but still haven't received honor/rank progress after five days

### ISSUE THREAD

**Issue by matthewmoppett** [codewars/codewars.com#2289]
I successfully completed the kata ([Symbolic differentiation of prefix expressions](https://www.codewars.com/kata/584daf7215ac503d5a0001ae)) in Rust about five days ago. The kata is not in beta, as far as I can see. The completed kata is showing up on my profile, and I've rated it, but my honor has not advanced at all (currently 4,123), and neither has my rank in Rust (3 kyu, 83.9% of the way towards the next level).

My solution is available [here:](https://www.codewars.com/kata/reviews/5d09d4eb9bde34000148231a/groups/5fd9f3966aabc20001856af8)

**Comment by hobovsky** [comment]
Records show that you've unlocked solutions and forfeited the kata, what makes you not eligible for points anymore.

**Comment by matthewmoppett** [comment]
Oh... and that happened before I submitted my first solution? Would you mind telling me when it happened? I suppose I must have done it by accident, since I can't remember doing it. What a pity. 

I just checked with an 8-kyu kata, and there is a warning when you click on "unlock solutions" -- I can't remember seeing such a warning with this particular kata. Oh well. Thanks for your response, anyway.

**Comment by XRFXLP** [comment]
or:  
You might've clicked on `Edit` by mistake while clicking on `TRAIN|TRAIN AGAIN` because they lie in vicinity in the description.
or intentionally clicked on `Edit` just to see what happens.

**Comment by hobovsky** [comment]
Unfortunately, it's not possible to check when _exactly_ you clicked the "unlock solutions" button. I can see it took you ~5 days to solve, so you had to unlock somewhere in between, before submitting your final answer.

Also as @XRFXLP says (and I forgot to mention, thanks for reminding): entering the kata editor also forfeits the kata. Maybe that's what you did?

**Comment by matthewmoppett** [comment]
@XRFXLP & @hobovsky: thanks, I think that must have been it -- I clicked "edit" just to see what it would to, basically.I just checked with another 8-kyu kata, and there was no warning given. It think it would be a good idea to guard that button with a warning that you're about to forfeit the kata.
