### ISSUE TITLE
Update CodeMirrror to fix matching brackets issues for Perl

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2291]
**Describe the bug**
Curly `{` and square `[` parentheses are not properly matched in the editor

**Screenshots**
Curly and square parenthesis:
![image](https://user-images.githubusercontent.com/23459568/102962812-9fa1bb00-450d-11eb-8e6e-440132c8b218.png)
![image](https://user-images.githubusercontent.com/23459568/102962828-a9c3b980-450d-11eb-885a-afcdc708f062.png)
![image](https://user-images.githubusercontent.com/23459568/102962847-b1835e00-450d-11eb-93df-55748571cc72.png)

But it works for round parentheses `()`:
![image](https://user-images.githubusercontent.com/23459568/102962916-d8419480-450d-11eb-9df4-71b9557d0a7f.png)

**To Reproduce**
Train on any kata with Perl translation, say: https://www.codewars.com/kata/5fde1ea66ba4060008ea5bd9/train/perl

**Browser**
Tried on Mozilla Firefox 84 and Brave Version 1.18.75 Chromium: 87.0.4280.101

**Comment by kazk** [comment]
Codewars doesn't do anything special, so it should be CodeMirror's bug in match brackets addon.

**Comment by kazk** [comment]
It seems like some quirk.

```perl
package Solution;

sub burner {
    my ($c, $h, $o) = @_;
    return [$water, $co2, $methane ];
}

1;
```
Adding a space before `]` fixes it. Definitely not a Codewars bug.

**Comment by XRFXLP** [comment]
I don't know anything about code runners, but am I right if I assume that for some languages codewars "imports" coderunner from somewhere else? 

If that's the case then this issue doesn't belong here.

**Comment by kazk** [comment]
No, this has nothing to do with the code runner which is why I transferred to this main repo. The code runner is a backend service that accepts some code and responds with the result and has nothing to do with the editor you see on Codewars.

The editor we use is [CodeMirror](https://codemirror.net/) ([code](https://github.com/codemirror/CodeMirror)) and the matching brackets are highlighted by [addon/edit/matchbrackets.js](https://github.com/codemirror/CodeMirror/blob/master/addon/edit/matchbrackets.js). For Perl, we use their [Perl mode](https://github.com/codemirror/CodeMirror/blob/master/mode/perl/perl.js).

**Comment by XRFXLP** [comment]
Someone from codemirror repo has fixed this from their side in [this](https://travis-ci.org/github/codemirror/CodeMirror/builds/751211133) build.

Not sure whether one needs to update from CW side, or it'll be automatically updated in few hours.

**Comment by kazk** [comment]
Thanks! I’ll update when they release the next version.

**Comment by kazk** [comment]
I'll keep this open as a reminder.

**Comment by kazk** [comment]
Deployed

**Comment by XRFXLP** [comment]
I don't think opening a dedicated issue would be a good idea, but julia had a similar problem:
https://github.com/codemirror/CodeMirror/issues/6609

which is fixed now.

**Comment by kazk** [comment]
Thanks.
Can you open a new issue? I need to update it after they release a new version (https://github.com/codemirror/CodeMirror/releases) and I'm sure I'll forget.
