### ISSUE TITLE
Please rerank PaperFold

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/codewars.com#2299]
Please rerank [Paperfold](https://www.codewars.com/kata/the-paperfold-sequence/). I am getting sick and tired of people complaining it's too hard for a `7`. Also, they're correct.

I don't know _why_ approver decided to rank it `7` when the average ranking was `6`, but I am _still_ dealing with frustrated users on a regular basis, and I would like that to STOP. I don't f\*cking care how it will f\*ck up the platform - leaving it like this does too.

Please rerank to `6 kyu`.

**Comment by kazk** [comment]
Pushed back to beta.

**Comment by Blind4Basics** [comment]
reapproved at 6

**Comment by JohanWiltink** [comment]
Thanks guys.
