### ISSUE TITLE
Indicator for retired katas

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#230]
At the moment, retired katas don't have any indicator that they're retired beside "(retired)". One can still submit the solution to test against the hidden test cases, but that's it.

I think there should be some hint that you won't get honour for solving this kata.

**Comment by jhoffner** [comment]
I large issue of this bug is that they are still searchable within the catalog. Sometimes the index doesn't get properly updated.

**Comment by jhoffner** [comment]
BTW the kyu badge should say "retired". Does it not? 

I'm working on fixing the index issue now

**Comment by bkaestner** [comment]
> BTW the kyu badge should say "retired". Does it not? 

No, still says [7 kyu](http://www.codewars.com/kata/prime):

![prime](https://cloud.githubusercontent.com/assets/6301773/12347142/610b8a6a-bb5b-11e5-8ee2-f5d449651453.PNG)

**Comment by Voileexperiments** [comment]
Is this still valid? I don't think it is, right?

**Comment by bkaestner** [comment]
It's still valid, Voile. You can still [attempt the prime kata](www.codewars.com/kata/prime), but you can never completely submit your solution and get honour for that. The only indicator is `(retired)`.

**Comment by kazk** [comment]
@jhoffner was this Prime kata retired differently from now?

**Comment by kazk** [comment]
Fixed
