### ISSUE TITLE
Issue with with dynamic generating regular expressions

### ISSUE THREAD

**Issue by JaoodxD** [codewars/codewars.com#2300]
There is an issue with replacing the text inside regular expression to create the new one.
Lets say I have
` rx1 = /\d+ [ */ ] \d+/`
 to find multiplications and divisions at first. Right now It's ok.
After it I tried just to replace `[*/]` with` [+-]` 
i.e. `rx2 = new RegExp( rx1.source.replace("[*/]", "[+-]"));`
inside first regular expression to find additions and substractions.
On the local machine everything works as expected, unlike the result of this system's interpreter.

![image](https://user-images.githubusercontent.com/39469154/104428238-4b7e7980-5595-11eb-84f0-df27323e9443.png)
![image](https://user-images.githubusercontent.com/39469154/104428527-a617d580-5595-11eb-914a-56cb7c199954.png)

**Comment by kazk** [comment]
Please use the kata discussion page. This issue tracker is not for questions about the kata.

"this system's interpreter" is Node.js. Your screenshots have different `rx1`s: `[*/]` vs `[*\/]`.

**Comment by JaoodxD** [comment]
> Please use the kata discussion page. This issue tracker is not for questions about the kata.
> 
> "this system's interpreter" is Node.js. Your screenshots have different `rx1`s: `[*/]` vs `[*\/]`.

Code is identical, when result is not. I even tried to upgrade `[*/]` to `[*\/]` but the result stayed the same.

**Comment by kazk** [comment]
> I even tried to upgrade `[*/]` to `[*\/]` but the result stayed the same.

That's because those **are the same**. Just try `'[*/]' === '[*\/]'`. Need `\\` in strings.

> Code is identical, when result is not.

If you still think so, use the kata discussion page to post your solution with a spoiler flag and ask for help.

**Comment by JaoodxD** [comment]
> That's because those **are the same** (just to be clear, my comment was about the regular expression `rx1` and not the string you're using). Just try `'[*/]' === '[*\/]'`. Need `\\` in strings.

Ty for tip, I'll try it.
