### ISSUE TITLE
API request with CORS?

### ISSUE THREAD

**Issue by mn113** [codewars/codewars.com#2301]
Are there any plans to enable CORS on the Codewars API server, meaning that I could successfully query its endpoints from an AJAX request within the browser, rather than using curl or Postman?

Alternatively, JSONP? The docs don't suggest that it is supported.

What are other people using to build apps based on this API?

**Comment by JohnnyBEdge** [comment]
Thanks kazk. I'd just like to add a small feature to my personal website
that on a button click would fetch and display my most recent Codewars
statistics.

*John Martin*
239.503.9678

**Comment by Steffan153** [comment]
As a workaround, you could use https://cors-everywhere.herokuapp.com/ for the moment.

**Comment by JohnnyBEdge** [comment]
Thank you! I had yet to find a solution, but this worked

*John Martin*
239.503.9678

**Comment by kazk** [comment]
Deployed
