### ISSUE TITLE
Fetching all my complete kata solutions

### ISSUE THREAD

**Issue by sprajagopal** [codewars/codewars.com#2304]
There needs to be a convenient way to fetch all of an user's kata solutions. Users need their own code for their archival and quick search purposes. Codewars does not provide a great UI for this. An API is necessary for this to process to be seamless.

**Comment by Kischy** [comment]
I would like this feature. Maybe one should be able to export all his/her solutions to files or export them to a private github repo.

**Comment by kazk** [comment]
Closing as a duplicate (subset) of #2305.
