### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by khaled-ah-awad** [codewars/codewars.com#2307]
I can't go to the website https://www.codewars.com or any page in it .. I tried to sign up, but I only see the error below
It works in my phone well, but it's not open in all browsers in my computer.

1. The first picture from https://www.codewars.com
2.  The second picture from https://www.codewars.com/join
![error404](https://user-images.githubusercontent.com/72554620/104918432-6ab64600-599d-11eb-9feb-545a4571431f.png)
![error-404](https://user-images.githubusercontent.com/72554620/104918438-6be77300-599d-11eb-829b-b30c04968a7c.png)

**Comment by Steffan153** [comment]
Are you behind a proxy/firewall maybe?

**Comment by khaled-ah-awad** [comment]
I don't use a proxy, I turn off the firewall protection in windows 10 and the issue is still occur with me ! @Steffan153

**Comment by Steffan153** [comment]
Does it work in [incognito mode](https://www.lifewire.com/browsing-incognito-445990)?

**Comment by khaled-ah-awad** [comment]
Yes , it works now .. @Steffan153  Thank you a lot :)
if you know what was the problem, I want to fix it.

**Comment by Steffan153** [comment]
Try disabling your extensions one by one and see if any fix it.

**Comment by kazk** [comment]
Closing, but feel free to keep commenting.

**Comment by khaled-ah-awad** [comment]
I think the problem was with the extensions, I downloaded another browser and it works now
thank you very much :)
