### ISSUE TITLE
Opening JavaScript solutions page for "Create phone Number" results in Internal Server Error

### ISSUE THREAD

**Issue by SallyH3** [codewars/codewars.com#2310]
**Describe the bug**

Internal server error after submitting solution for 6kyu Create phone Number kata.

**To Reproduce**
Got solution, clicked attempt, clicked submit, receive internal server error.

**Expected behavior**
Be redirected to solutions page.

**Screenshots**
<img width="1164" alt="Screen Shot 2021-01-21 at 7 26 30 PM" src="https://user-images.githubusercontent.com/40863560/105437714-cc391780-5c1e-11eb-9570-a3978cac3f10.png">

**Browser**
Brave

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
Thanks for reporting. I noticed this error happening yesterday, and it's caused by some corrupted data in the JavaScript solutions for this kata. I haven't been able to narrow it down yet.

**Comment by kazk** [comment]
Fixed
