### ISSUE TITLE
Zozonacci kata with "Allow Contributors" is not editable

### ISSUE THREAD

**Issue by suic86** [codewars/codewars.com#2311]
XRFXLP reported that he can't see the Edit on the [Zozonacci](https://www.codewars.com/kata/5b7c80094a6aca207000004d)

![XRFXLP screenshot](https://i.imgur.com/Mlbb4bB.png)

But contributors are allowed:

![Screenshot 2021-01-23 at 13 42 10](https://user-images.githubusercontent.com/11985251/105578580-9bbdbe80-5d81-11eb-9d78-be680095e281.png)

**Comment by Blind4Basics** [comment]
I believe it's just because there were no issue or suggestion opened for more than 7 days already.

I can see the edit button, on my side (but I'm already a contributor)

**Comment by XRFXLP** [comment]
@Blind4Basics I don't think that can be bcause if that's true then "Allow contributor" option would be redundant.

I thought one have to wait 7 days if-and-only-if "Allow contributors" option is unselected.

**Comment by Blind4Basics** [comment]
not sure anymore... (we should document that too)

**Comment by suic86** [comment]
@Blind4Basics and @XRFXLP: I'm confused by this... I thought that after certain number of points one can edit any "Allow contributors" kata.

**Comment by Blind4Basics** [comment]
> I'm confused by this...

that makes two of us.... x)

**Comment by Steffan153** [comment]
I think the thing about the suggestions and issues always applies, and maybe the "Allow Contributors" was only for the beta stage...?

**Comment by FArekkusu** [comment]
The `Allow contributors` checkmark allows/disallows access to the editor to other users while the kata is still in beta (the `Edit/Approve` button is not affected by this, obviously). In any other case the kata **must** have a pending suggestion/issue.
