### ISSUE TITLE
Unicode symbols / emojis in Kata titles

### ISSUE THREAD

**Issue by AlexPuts** [codewars/codewars.com#2314]
I'm always frustrated when see those. 
As for me those give unfair highlight to user's katas, and in the long run this can lead to a situation, when every kata will have a unicode emoji / icon in it's title.
I suggest to filter out such characters from kata title field. (To preserve the existing clean interface style). 

![image](https://user-images.githubusercontent.com/13510424/106551707-dca69780-6526-11eb-8d3b-03818c0c4c75.png)

**Comment by kazk** [comment]
Yeah, I _personally_ hate them as well.

> As for me those give unfair highlight to user's katas, and in the long run this can lead to a situation, when every kata will have a unicode emoji / icon in it's title.

Interesting. It's just annoying and ugly to me. I doubt this will become common.

> I suggest to filter out such characters from kata title field.

I'd rather let users change the actual title because it's not that often and may not be decorative.

**Comment by hobovsky** [comment]
> in the long run this can lead to a situation, when every kata will have a unicode emoji / icon in it's title.

I don't think it would happen with current way how reviews are done. It's ugly, but it's not _yet_ a problem. I am pretty sure reviewers won't let to introduce too much visual clutter this way.


> As for me those give unfair highlight to user's katas

I do not get this point though. Since kata do not compete one with each other, what would their advantage be?

**Comment by AlexPuts** [comment]
> I do not get this point though. Since kata do not compete one with each other, what would their advantage be?
In terms of gamification they compete, because author receives points for completions by users (with some conditions).

Anyways, I get the point, that we will have to rely on reviewers and their common sense.

Thanks for the comments.
