### ISSUE TITLE
Keyboard shortcuts don't work as expected with Hungarian keyboard layout

### ISSUE THREAD

**Issue by myrddral** [codewars/codewars.com#2316]
**Describe the bug**
Regularly used keyboard shortcuts don't work, such as alt+ ' . ' for ' ; ' and shift + alt + x for ' > '. It seems codewars use a different keyboard layout than default.

**To Reproduce**
Any time I want to type a ' ; ' in a Kata, it comments out my actual line of code.

**Expected behavior**
Type a ' ; ' when using the system default layout, like in any other program.

**Screenshots**

**Browser**
Google Chrome Version 88.0.4324.96 (Official Build) (x86_64)

- OS: macOS

**Additional context**
I am using Hungarian keyboard layout.

**Comment by kazk** [comment]
Can you try typing on https://codemirror.net/ ? Not just `;` and `>`, but anything that involves `Alt`. I'd appreciate if you can give me a list.

On Codewars, `Cmd + .` is mapped to commenting out code block on macOS, but not `Alt + .`.

**Comment by myrddral** [comment]
Hey, sorry for the late reply. I must close this, as I cannot reproduce it anymore ever since I have reinstalled macOS. It's working fine now.
