### ISSUE TITLE
Bad line numer where an issue has occurred

### ISSUE THREAD

**Issue by Sadelarus** [codewars/codewars.com#2317]
**Describe the bug**
When a compiler runs into an issue in the code wrong line number is displayed in diagnostic messages!

**To Reproduce**
You can do it yourself! Any wrong code and you can see it! Thanks a lot for another kind of shirty soft! 

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
Hi, it's a known technical dept and depends on the language and language version. Please open a new issue for the language at https://github.com/codewars/runner if it's not already there.
