### ISSUE TITLE
Hitting escape in VIM mode deselects input in solution field.

### ISSUE THREAD

**Issue by macimiri** [codewars/codewars.com#2318]
**Describe the bug**
When in VIM mode, one presses 'i' to enter insert mode. When exiting insert mode to go back to normal mode, pressing 'escape' removes the text cursor from the solution field entirely. The mouse must be clicked into the solution box to show the cursor, now in normal mode.

**To Reproduce**
This behavior occurs on every kata. Select VIM mode, enter insert mode by pressing 'i' and exit insert mode by pressing 'escape'. The text cursor will disappear.

**Expected behavior**
When in insert mode and 'escape' is pressed, the thin insert mode cursor should go back to a thick normal mode cursor.

**Browser**
- OS: Windows 10 (20H2)
- Browser: Vivaldi (based on Chrome)
- Version: 3.5.2115.87

**Comment by kazk** [comment]
I can't reproduce this. Escape keeps the focus on the editor and a green cursor appears.

Do you have any extensions enabled? Can you try again without them?

**Comment by macimiri** [comment]
I do have a few extensions, such as lastpass and ublock. I tried in an incognito window of Vivaldi (with extensions disabled), and I still experienced the issue.

I tried with a new MS Edge browser window and I did not experience the issue. Perhaps there's a problem with my Vivaldi browser that's causing the behavior.

**Comment by vlecoq-v** [comment]
I had the same issue and it was caused by vimium browser extension a situation fairly common for vim users I guess.

Solution:
add `esc` as a disabled pattern for codewars.com

**Comment by kazk** [comment]
Closing because it's possibly caused by extensions and another user confirmed the same behavior on CodeMirror's demo which means it's not our bug (https://github.com/codewars/codewars.com/issues/2744#issuecomment-1177051944).

**Comment by wylie102** [comment]
> Solution: add `esc` as a disabled pattern for codewars.com

Hi, can I ask how you actually do this? The only way I can find is to leave the "keys" box blank so that it disables every key. I've tried combinations of `esc` `Esc` `"esc"` `"Esc"` `<esc>` `<Esc>` `<escape>` and `<Escape>`, and none of them seem to do anything. Looking through the vimium docs I don't see any reference to the correct notation to use for it either.

How did you manage to do it?

**Comment by SebastienPingal** [comment]
I have the same issue here. It happens even if I disable my Vimium extension.
