### ISSUE TITLE
Cannot post comments to solutions.

### ISSUE THREAD

**Issue by RavenJe-dev** [codewars/codewars.com#2320]
**Describe the bug**
Cannot post comments to solutions.

**To Reproduce**
Just try to comment something.

**Expected behavior**
The comment should be posted.

**Screenshots**
![Screenshot 2021-02-13 185652](https://user-images.githubusercontent.com/55483499/107858692-4ed38200-6e2d-11eb-8abb-d25be779c7db.png)

**Browser**
Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)

- OS: Windows 10
- Chrome
- Version 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
When I press POST nothing happens. I checked the console as well, nothing. My account is verified.

**Comment by Blind4Basics** [comment]
Hi,

It's a known problem, and for now it's an unsolvable one, unfrotunately.
[See explanation here](https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658)

related: #2048, #2255 and some others.

Can you just give the link to the related kata, to be sure it's the same problem, plz?

cheers

**Comment by RavenJe-dev** [comment]
Sure [Link Kata](https://www.codewars.com/kata/54ba84be607a92aa900000f1)

**Comment by Blind4Basics** [comment]
yeah, that's it: too much data/completions... I'm closing here as it's a duplicate.

thanks for reporting.
