### ISSUE TITLE
Javascript curly braces {} cursor place after enter is incorrect

### ISSUE THREAD

**Issue by mickeysox** [codewars/codewars.com#2321]
When opening a curly brace, editor will add the closing, as expected.  

After you hit enter, a new line is created, but the cursor is placed at the closing brace

vscode would look like this for example (| for cursor)
````
for (let a in b) {
    |
}
````

this is what happens on codewars.com

```
for (let a in b) {

|}
```

This is related too https://github.com/codewars/codewars.com/issues/2189

Thanks

**Comment by Steffan153** [comment]
Must be a pretty new bug because I don't remember it being like this before. I can reproduce tho.

**Comment by kazk** [comment]
I've been really busy with Qualified side so haven't touched Codewars in a while.
CodeMirror was last updated 26 days ago. https://github.com/codewars/codewars.com/issues/2291#issuecomment-764015124

**Comment by kazk** [comment]
Looks like https://github.com/codemirror/CodeMirror/releases/tag/5.59.2 fixes it.

> [closebrackets addon](https://codemirror.net/doc/manual.html#addon_closebrackets): Fix a regression in the behavior of pressing enter between brackets.

**Comment by mickeysox** [comment]
> Looks like https://github.com/codemirror/CodeMirror/releases/tag/5.59.2 fixes it.
> 
> > [closebrackets addon](https://codemirror.net/doc/manual.html#addon_closebrackets): Fix a regression in the behavior of pressing enter between brackets.

Great 😊 any idea when that fix will propagate through?

**Comment by kazk** [comment]
Soon. Either tonight or tomorrow.

**Comment by mickeysox** [comment]
Thank you for the quick turn around :)

**Comment by kazk** [comment]
Deployed
