### ISSUE TITLE
Update of 4x4 skyscrapers from the edit panel is impossible

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2326]
* kata: https://www.codewars.com/kata/5671d975d81d6c1c87000022/

The tests contains a big flaw allowing to bypass them. I wanted to update it to node 12. I did the update, then hit republish, and the 2 times, I got this in return:
![image](https://user-images.githubusercontent.com/32236948/109138066-426af580-775a-11eb-89f4-7e4b2cde9849.png)

* `Edit` button is visible
* "allow contributors" is checked
* I can make modifications in the edit panel
* tests are running fine after modifications
* republishing is impossible: I systematically land on the message above (note: even if I try to republish wihtout any modification)

Not sure if it's "mod" related or not...

**Comment by kazk** [comment]
Ugh. This is because some users messed with the ranks a while ago. You should see that the rank is blank when you open the editor. Republishing that will move the kata back to beta, and you're not allowed to do that.

**Comment by Blind4Basics** [comment]
thanx Voile again, I guess... :o

Problem is: 4 kyu isn't in the available ranks... :/ Can you trick the votes so that 4 kyu appears? (there are "a lot" of kata with problems related to this. Like around 10, I believe)

**Comment by kazk** [comment]
> Problem is: 4 kyu isn't in the available ranks... :/ 

Yeah, that's why it becomes blank. A workaround you can do is to add 4 kyu in the HTML and submit it (like how Voile was doing). You should be able to republish as long as the rank doesn't change.

I'll need to find these and either fix the data or make them exceptions and bypass the validation.

**Comment by Blind4Basics** [comment]
O...m...g... XD
I didn't even know that could work that way. Done, thx. Do we keep this opened?

**Comment by kazk** [comment]
Yeah, let's keep this open because I'm sure I'll forget about this.

**Comment by Blind4Basics** [comment]
I actually talk about this problem in another of my older issues. Maybe we should rather create a dedicated issue where all kata involved in this problem are stored? (possibly with the work around available for maintainers?)

**Comment by kazk** [comment]
Yeah, that's better.

**Comment by Blind4Basics** [comment]
ok, i'll start a new dedicated issue (my old issue is about something else, actually x ) )

**Comment by Blind4Basics** [comment]
I'm actually wondering where to put what...

* the workaround: I believe to would be better to not put it in the open. Might give more ideas to people who don't need them => I'll open a separate issue in the "issue" private repo to archive the modus operandi
* list of kata...: since it's a "list" shouldn't I create a list in the wiki rather than a dedicated issue?

**Comment by Blind4Basics** [comment]
done, closing here.
