### ISSUE TITLE
Incorrect syntax highlight for function name in C language

### ISSUE THREAD

**Issue by AlexPuts** [codewars/codewars.com#2327]
Syntax is incorrectly highlighted for type uint64_t / int64_t if it's name is present in the function (used as part of the function and not as a type)

Regular **orange color highlight was expected**, but **got gray color highlight** (used for types).

![image](https://user-images.githubusercontent.com/13510424/109214073-6feb8980-77c2-11eb-881b-c1224abb4f10.png)

**Comment by kazk** [comment]
It's reproducible on <https://codemirror.net/mode/clike>.
![image](https://user-images.githubusercontent.com/639336/109370531-93134900-7855-11eb-821d-ad1cb5fcaf29.png)

Please open a bug report at https://github.com/codemirror/codemirror.
I'll update when it's fixed.
