### ISSUE TITLE
Inconsistent tab width

### ISSUE THREAD

**Issue by Vort** [Codewars/codewars.com#233]
Tab character have different widths in editor and in solutions section.
Because of this, solution, which looks good in editor, gets bad formatting after it is published.

Screenshot:
![cw_tab_bug](https://cloud.githubusercontent.com/assets/1242858/12475218/0f96be6a-c02a-11e5-833e-e48318285a02.png)

**Comment by kazk** [comment]
This was fixed by using CodeMirror to do the syntax highlighting.
