### ISSUE TITLE
Whitespace interpreter

### ISSUE THREAD

**Issue by VictorFouquet** [codewars/codewars.com#2330]
Hey there, it seems there is a bug with the test suite for the Whitespace interpreter Kata (https://www.codewars.com/kata/52dc4688eca89d0f820004c6/train/javascript)  :

I was implementing the "control flow" functions, trying to solve the first test inside the "Testing conditional and unconditional jump functionality" unit.
Adding console.log() in my control flow code block, I "successfully" passed the kata, though I had not even implemented the jump if negative function.
I was quite surprised to see that I had passed all tests, though only 77 tests were displayed green as passed.
In console I could see a huge list of logs, switching between "Flow" and "call" (the flags I was logging for debugging purposes)

When I commented these two console.log(), I hit "RangeError: Maximum call stack size exceeded", this time obviously no longer passing the full tests set. Uncommenting them makes the Kata passing successfully back.

**Comment by VictorFouquet** [comment]
![Screenshot from 2021-02-27 21-12-49](https://user-images.githubusercontent.com/52054823/109399074-d696b180-7940-11eb-9be3-cc3be9bce4e0.png)
![Screenshot from 2021-02-27 21-14-43](https://user-images.githubusercontent.com/52054823/109399075-dac2cf00-7940-11eb-993b-c2c5e6bc68d8.png)
Two screenshots of the succeeding and failing cases, only lines changes being the commented/uncommented lines at l.74, l.82

**Comment by Steffan153** [comment]
Please use the kata discourse to report issues about kata instead of this issue board.

**Comment by hobovsky** [comment]
Steffan it's not a problem about the kata, it's some problem with the runner and how it reacts to the filled/overflown buffer.

**Comment by FArekkusu** [comment]
This is an old issue, but idk how to find it. As @hobovsky said overflowing the buffer in an infinite loop/recursion **may** lead to test execution being aborted. The runner's output then will be checked for successes/failures as if everything was normal, and you can complete the kata as long as you have passed at least 1 test, and haven't failed any.

**Comment by kazk** [comment]
See https://github.com/codewars/codewars-runner-cli/issues/637

The solution is to fix the kata by updating to a newer version of Node that doesn't use the old broken test framework.
