### ISSUE TITLE
Crystal: Inconsistent behaviour between codemirror and codewars trainer

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2331]
(Assuming that CodeMirror is being used for crystal programming language)

On codewars, some keywords are highlighted incorrectly(It seems ruby syntax highlighter is being used) for crystal, but the behaviour is not reproducible in codemirrors editor.

For example: `and`, `or` and `not` are not keywords in crystal ( and not also not in the list of [keywords](https://github.com/codemirror/CodeMirror/blob/master/mode/crystal/crystal.js#L30) in crystal mode of codemirror) but are being highlighted as that of other keywords.

On codewars: 
(which is exactly the same as that of ruby syntax highlighter)

![image](https://user-images.githubusercontent.com/23459568/109600770-a9feb780-7b43-11eb-8536-5281a2494d0d.png)

On [codemirror editor](https://codemirror.net/mode/crystal/index.html):

![image](https://user-images.githubusercontent.com/23459568/109600805-bf73e180-7b43-11eb-8caa-5a556db0f15c.png)

**Comment by kazk** [comment]
Thanks for reporting this. I'm guessing Crystal mode didn't exist when Codewars first added Crystal (before I took over).
I'll update it.

**Comment by kazk** [comment]
Deployed
