### ISSUE TITLE
Update CodeMirrror to fix matching brackets issues for Julia

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2332]
For details, see: https://github.com/codemirror/CodeMirror/issues/6609

**Comment by kazk** [comment]
Deployed

**Comment by XRFXLP** [comment]
@kazk There are some similar issues with syntax highlighting in the Reason programming language, but I don't know which code editor is being used for that, can you please provide the same information?  
 I can't find any information on [old feature request page](https://www.codewars.com/topics/feature-requests) or language request in runner repository, and there is no [Reason mode at CodeMirror](https://codemirror.net/mode/).

I'm asking this to avoid opening issue in the wrong repository.https://codemirror.net/mode/

**Comment by kazk** [comment]
There's no repo/package for Reason mode. We're currently using a file copied from https://github.com/Sketch-sh/sketch-sh/blob/ab095e9ed1e217a5a86528fec9cefb2458504acb/client/src_editor/reason-mode.js

Maybe you can let them know if the issue can be reproduced on their site: https://sketch.sh/

I wonder if they can make a separate NPM package out of it. If not, we can make one and maintain it.
