### ISSUE TITLE
C code in text fixtures is being highlighted as that of NASM

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2333]
In sample tests and in `fixture.c`, the C code is highlighted as that of NASM:

Actual behaviour:

![image](https://user-images.githubusercontent.com/23459568/109621964-98c4a380-7b61-11eb-842e-cb183af076ab.png)

Expected behaviour
![image](https://user-images.githubusercontent.com/23459568/109621672-4aafa000-7b61-11eb-985f-a7e7cea8aca2.png)

**Comment by kazk** [comment]
Deployed the fix.
