### ISSUE TITLE
Please comment on the kata instead

### ISSUE THREAD

**Issue by Baglan05** [codewars/codewars.com#2335]
Your goal in this kata is to implement a difference function, which subtracts one list from another and returns the result.

It should remove all values from list a, which are present in list b.
array_diff([1,2],[1]) == [2]

If a value is present in b, all of its occurrences must be removed from the other:

array_diff([1,2,2,2,3],[2]) == [1,3]

**Comment by XRFXLP** [comment]
Do you want to create a kata or what?

**Comment by Blind4Basics** [comment]
@Baglan05 : if you need help on a kata, post in its discourse seciton, please.

Closing as... I don't see how it could be relevant here.

Cheers
