### ISSUE TITLE
Hide a posted solution from other users

### ISSUE THREAD

**Issue by darkeclipz** [codewars/codewars.com#2336]
**Is your feature request related to a problem? Please describe.**
I wrote a Sudoku solver, and used it solve most of the Sudoku related problems. However, all my progress from them got removed... (and restored already). One of the remarks was that this spoils the harder problems with a "too efficient" solution posted in earlier problems. I come from Project Euler, where I'm used to have a giant toolkit to solve stuff...

**Describe the solution you'd like**
Be able to hide my solution, in the case I think that this solution can be used to solve harder problems.

**Describe alternatives you've considered**
Write simpler solutions...

**Comment by Blind4Basics** [comment]
Hi (again ;) ),

It's already available, but only to moderators (I actually already hid your solutions).
This won't be made available to other users for obvious reasons... ;o
