### ISSUE TITLE
Unable to sign up for a user name that is not in use

### ISSUE THREAD

**Issue by saoud** [codewars/codewars.com#2337]
I tried signing up with the user name saoud but it will not allow me 

**To Reproduce**
https://www.codewars.com/users/saoud
There is no user there

**Expected behavior**
I would expect there to be a user there if I can not get the user name.

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**
![Screen Shot 2021-03-09 at 12 00 28 AM](https://user-images.githubusercontent.com/415685/110437666-799aaa00-806a-11eb-9000-b0158b5e8e42.png)

**Comment by kazk** [comment]
The uniqueness of the username is case-insensitive (but look up is not). The username is taken: https://www.codewars.com/users/Saoud
