### ISSUE TITLE
Submit button never is enabled

### ISSUE THREAD

**Issue by kfreter** [Codewars/codewars.com#234]
I've gone through several Katas only to have the submit button not be enabled.  All the local tests pass.  At this point the only option is to abandon the work already done.  Very frustrating.

**Comment by slmueller** [comment]
Similar/Same issue: After passing the local tests and submitting, the message "Failed to send to server. Check your internet Connection" flashed up for a second. Afterwards the submit button was inactive and the Output window read "Waiting for results...". This happened for different katas, on different days, and after reloading each kata several times.

Finally I switched from Internet Explorer to Chrome and it's working now.

**Comment by codybousc** [comment]
I'm having the same issue on Safari. I'm only using Safari, because I was having a separate submission issue with codewars while using Chrome.

**Comment by shlomitArgov** [comment]
This is happening to me on the Sign Up page on Chrome, Firefox and IE.

**Comment by jhoffner** [comment]
I migrated our system over to AWS yesterday and am still working through a few kinks. The landing page should be fixed now (though there are other issues still in progress, so once you sign up the experience still may not yet be smooth)

**Comment by kazk** [comment]
Closing because it's been a long time and a lot have changed. Please open a new issue if you're still having similar issues.

We've [replaced the code execution service](https://github.com/Codewars/codewars.com/issues/1336) and it should be more stable.
