### ISSUE TITLE
Unable to publish translation for `Make a window` kata

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2341]
When I click `Publish`, the translation still stays in draft mode for this particular kata only (And same when I click publish agn & agn) ~~However I'm able to publish translation to other katas.

I think it's related to the backend cache thing :)

![image](https://user-images.githubusercontent.com/65498235/111017412-4c455780-83ee-11eb-89bf-1ba412281c37.png)
![image](https://user-images.githubusercontent.com/65498235/111017449-a34b2c80-83ee-11eb-9cec-e42032d5b5ed.png)

**Comment by kazk** [comment]
Let me know if this is still happening.
