### ISSUE TITLE
No "new kata" button

### ISSUE THREAD

**Issue by rushknight** [codewars/codewars.com#2343]
I wanted to make a new kata.
So, I searched the site for "new kata" button,
but I couldn't find it(I once made a kata before I authorized my account).
Why?
Image:
<img src = "https://i.ibb.co/0K7xfjL/2021-03-16-140959.png">

**Comment by Blind4Basics** [comment]
> I wanted to make a new kata.

You won't.
You're a copycat, and your privileges have been removed. Your account is to be banished.
