### ISSUE TITLE
Cannot login using github

### ISSUE THREAD

**Issue by dzakimubarok** [codewars/codewars.com#2344]
I cannot login using github account

![image](https://user-images.githubusercontent.com/49614559/111285461-bfabcb00-8673-11eb-8339-ddb3d8122c72.png)

I am using Chrome

- OS: Windows
- Browser: chrome
- Version 89

**Comment by kazk** [comment]
https://www.codewars.com/users/dzakimubarok is not associated with any GitHub account. You can log in with your password and link your account from Account Settings.

**Comment by dzakimubarok** [comment]
sorry but I haven't set any password, so how can I login? Thank you.

**Comment by kazk** [comment]
Click "Forgot your password?" and enter your email address.

**Comment by dzakimubarok** [comment]
sorry i havent set email and passeword. i only signed in with gith hub account and all of sudden i cant log in using my github account thx

**Comment by kazk** [comment]
It should be the same email as your GitHub account.
