### ISSUE TITLE
code does not work correctly on codewars 

### ISSUE THREAD

**Issue by Yurk-do** [codewars/codewars.com#2346]
code does not work correctly on codewars (when using vscode, the code works correct
![Inkedvscode_LI](https://user-images.githubusercontent.com/64039182/111597479-403b0a80-87df-11eb-8007-5981d88e2272.jpg)
![Training on Guess the Sequence Codewars_LI](https://user-images.githubusercontent.com/64039182/111597484-4204ce00-87df-11eb-8ec9-3b3e4b4c4546.jpg)

function sequence(x) {
let result = [];
    let numberCycle = 0;
    if (x < 10) {
        do {numberCycle += 1
            result.push(numberCycle)
        }
        while(numberCycle < x)
    }   
    else {
        let cycle = Math.floor(x/10);
        do {numberCycle += 1;
            let count1 = numberCycle * 10 - 1;
            let count2 = count1 + 10;
            result.push(numberCycle);
     do {count1 += 1;
                result.push(count1)}
          while(count1 < count2 && count1 < x)
     }
        while (numberCycle < cycle)
        const finalNumber = Math.ceil(result[result.length - 1] / 10) < 9 ? 9 : Math.ceil(result[result.length - 1] / 10);
      do {
            cycle += 1;
            result.push(cycle)
} while (cycle < finalNumber)
    }
return result;}
console.log(sequence(91));

**Comment by Blind4Basics** [comment]
Hi,

for things like that, use the discourse section of the kata.

But note there is no use to open an issue there either: you apparently didn't get that the red line above is your output (hence is the very same as in vscode) while the second line is what you should have returned.

take a look [here](https://github.com/codewars/codewars.com/wiki/Troubleshooting-your-solution), and if still needing help after that, post a _question_ on the kata discourse.

Cheers
