### ISSUE TITLE
Author of the original translation is associated with a solution group of forked translation

### ISSUE THREAD

**Issue by dolamroth** [codewars/codewars.com#2355]
Hello.

I have created a Python translation for "Point in Polygon" kata: https://www.codewars.com/kata/reviews/607154f73ff3410001f1dc4f
The respective translation, which is approved on 2021-04-10: https://www.codewars.com/kumite/6055d774808f270013744ba6?sel=6055d774808f270013744ba6

However, another user (dimm667) is shown instead of me as the author of original solution: https://www.codewars.com/kata/reviews/607154f73ff3410001f1dc4f/groups/607154fb3ff3410001f1dc54
My nickname is not shown, even if I resubmit the solution.

**Comment by dolamroth** [comment]
Note: it appears due to the fact, that I made a fork of dimm667's translation (which is 6 years old and deprecated). However, his translation (which was never approved in the first place) is deprecated now.

Please, change the author of solution to me.

**Comment by kazk** [comment]
I changed the associated user, but I need to fix other references.

Next time, reject and create a new translation if it's significantly different (almost completely rewritten). Otherwise, the original author should get the credit. Approved or not is irrelevant.

**Comment by dolamroth** [comment]
Ok, thank you.

I was dumbfounded by the fact, that I could not create a new Python translation from scratch (without forking), when there was already pending one. But I didn't think about rejecting it.

Maybe, it would be worth to mention in the docs? Or allow parallel translations in one language?
