### ISSUE TITLE
Comment POST request send but comment not shown

### ISSUE THREAD

**Issue by glgoose** [codewars/codewars.com#2358]
Behavior: when clicking POST button to comment it visually does nothing on the website i.e. it doesn't post a comment

Upon inspection a POST request does get send with the comment in the request body but in the UI in the browser nothing happens. Tested in both brave(chrome) & firefox.

https://user-images.githubusercontent.com/48956933/114635865-f94d1180-9cc5-11eb-8149-e05e1d959cd4.mov

**Comment by kazk** [comment]
This should be the same issue as https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658

I'll need to look into why the error is not showing.

**Comment by kazk** [comment]
See https://github.com/codewars/codewars.com/issues/2263#issuecomment-1007176572
