### ISSUE TITLE
Reporting incorrect number of kata's available.

### ISSUE THREAD

**Issue by MarkPearlCoZa** [Codewars/codewars.com#236]
CodeWars is reporting to me that there are 5 kata's based on my search criteria - as far as I can tell based on visual inspection there are only 4 kata's available?

![code wars bug](https://cloud.githubusercontent.com/assets/384153/12703868/48bcf496-c856-11e5-89fc-719476f73ffb.png)

**Comment by paul-calvelage** [comment]
I saw this a while ago where the count was obviously more than the results; at one point it even said "2 Kata found" and the results were totally blank.  But it's not doing it at the moment.  Instead I have a lot of extra kata that shouldn't be there.  See https://github.com/Codewars/codewars.com/issues/282.

Definitely something is going haywire with the search results.

**Comment by kazk** [comment]
Closing old issue. Closing as duplicate of #1053.
