### ISSUE TITLE
can somebody check the status of my account

### ISSUE THREAD

**Issue by basiclaser** [Codewars/codewars.com#237]
I have confirmed my account, am logged in, am also not logged in, and cannot login all at the same time. 
I'll try a password reset and see what happens. Thanks for any advice.

**Comment by kazk** [comment]
I'm sorry that no one responded.
You didn't include your Codewars username so I assumed it's the same as your GitHub's and found https://www.codewars.com/users/basiclaser

I'm closing this because I don't know what this issue is about.
