### ISSUE TITLE
Code editor smart edit features should be disabled in Discourse

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2379]
For some reasons it's also enabled in discourse input text boxes, which is inappropriate for the specific usage (typing plain text).

**Comment by hobovsky** [comment]
While we are at it, the way how `Home` and `End` work in discourse editor is annoying too.

**Comment by kazk** [comment]
The editor for Markdown was instantiated differently and the custom config was not applied. I'll disable for Markdown.

@hobovsky Can you elaborate? What's annoying/different? Doesn't it just jump to the beginning and the end of line?

**Comment by Blind4Basics** [comment]
home/end: in discourse, it behaves on complete §, not on lines in the editor. Meaning when you strike "home" with a 10 lines § on the screen, you go back 10 lines up instead of just at the beginning of the line in the editor

**Comment by kazk** [comment]
Isn't that because it's actually a single (wrapped) line?

**Comment by Blind4Basics** [comment]
I guess so, yes

**Comment by kazk** [comment]
I think I found a way. I'll try it.

**Comment by kazk** [comment]
Fixed

**Comment by hobovsky** [comment]
> Isn't that because it's actually a single (wrapped) line?

Probably so, yet none edit view I happened to use worked this way. They always use beginning and end of displayed lines as a target for Home and End.

Anyway, thank you for handling this, now it works much more intuitively for me.
