### ISSUE TITLE
Unnecessary italicisation in Perl

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2380]
In Perl, some texts get unnecessarily italicised:

![image](https://user-images.githubusercontent.com/23459568/118241826-391c3a00-b4ba-11eb-8066-d588aa16d2aa.png)

But it doesn't seems to directly come from CodeMirror:

![image](https://user-images.githubusercontent.com/23459568/118241849-40434800-b4ba-11eb-8242-3cf8a9b78f66.png)

Browser : Brave 1.24  
OS : Linux Mint 20

**Additional context**  
It seems to me that any text which is highlighted as grey in the codemirror editor get italicised  in codewars editor:
For instance, the update which fixes [this](https://github.com/codemirror/CodeMirror/issues/6675) issue hasn't been applied yet on CW, and prior to the fix the syntax here's how syntax highlighting was done for the given code:
![image](https://user-images.githubusercontent.com/23459568/118241631-01ad8d80-b4ba-11eb-88fd-97cedcb53ae1.png)

It can be seen here that `%10` in `5%10` is highlighted as grey, but when it comes on CW, it gets rendered as:
![image](https://user-images.githubusercontent.com/23459568/118241799-315c9580-b4ba-11eb-8ce6-d247a118b9aa.png)

**Comment by kazk** [comment]
In our theme, `.cm-meta` (usually metadata and some special token) class is italicized. Perl mode is tokenizing unexpected tokens as `meta`, but I won't blame them because it's difficult to tokenize Perl correctly.

I'll just stop italicizing `.cm-meta` in our theme.

**Comment by kazk** [comment]
Deployed
