### ISSUE TITLE
Test and attempt Button not working

### ISSUE THREAD

**Issue by Karth1kRav1chandran** [codewars/codewars.com#2385]
**Describe the bug**
Unable to test or attempt the code

**Expected behavior**
Expected to test code

- OS: Windows 10
- Browser chrome

**Additional context**

**Comment by Blind4Basics** [comment]
Hi,

Could you do a screenshot of the trainer, please? The link to your CW's account might be of use too.

**Comment by Karth1kRav1chandran** [comment]
https://user-images.githubusercontent.com/70200068/119219765-bec86700-bb04-11eb-97bb-3ec1889ebe60.mp4

**Comment by Blind4Basics** [comment]
looks weird, yes. But again, the link to your codewars account, and actually the one to the kata woudl be of help to handel this.

@kazk: link to the kata: https://www.codewars.com/kata/590ba881fe13cfdcc20001b4/ I just tried it and the buttons are working, on my side.

**Comment by kazk** [comment]
@Karth1kRav1chandran Is it only this kata? Try again without any extensions enabled and in Private Window. Most of these weird casese that only happens to a few users are caused by browser issues.

**Comment by Karth1kRav1chandran** [comment]
there was a over lap from pot player in that particular zone, Issue was resolved once i closed pot player. Thank you @Blind4Basics @kazk

**Comment by Blind4Basics** [comment]
:+1:
