### ISSUE TITLE
Unable to log in to CodeWars via GitHub

### ISSUE THREAD

**Issue by mandyWW** [codewars/codewars.com#2387]
A few months ago I signed up to Code Wars using GitHub. All was working fine until I logged out last week and since then, when I try to authenticate via GitHub I get: "Invalid GitHub user XXXXXX". Where XXXXXX is my correct GitHub login name.

**To Reproduce**
Login to CodeWars using GitHub

**Expected behavior**
I expect to be logged in

**Screenshots**
![image](https://user-images.githubusercontent.com/1316724/119306887-c0a83c80-bc62-11eb-8f92-6854f6d09d5b.png)

**Browser**
Chrome  90.0.4430.212 on PC. Same issue with Edge.

**Additional context**
My colleague is experiencing the same issue.

**Comment by kazk** [comment]
That error usually means that GitHub user is not associated with a Codewars user.

What is your Codewars username? User mandyWW doesn't seem to exist.

**Comment by mandyWW** [comment]
Ah, I changed my username to multiverseAdmin - is the the problem? The UI allowed me to do this, perhaps this was my first login since then? How can I login now?

**Comment by kazk** [comment]
No, changing your username doesn't affect the association with GitHub account.

https://www.codewars.com/users/multiverseAdmin doesn't have GitHub account associated with. Are you sure you didn't unlink your GitHub account? You can do a password reset with your email address and log in. Then link your GitHub account from Account Settings.

**Comment by mandyWW** [comment]
Thanks so much, all sorted. I could have sworn I had a GitHub linked account but seems I didn't - sorry to have wasted your time.
