### ISSUE TITLE
Javascript Testing Framework Error for Arrays

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#239]
I recently wanted to create a Kata related to sorting algorithms (which naturally involves arrays) but when I was testing out a solution (I didn't even code the algorithm yet at that stage - I just tested it using the built in JS ```.sort()``` method for arrays), the console returned the following error (which is shown on the image below):

![screen shot 2016-02-09 at 1 52 42 pm](https://cloud.githubusercontent.com/assets/7777884/12908804/2cfd8762-cf35-11e5-9e42-f06e00441f31.png)

The problem here is that the 2 arrays being tested here clearly are identical (how could ```[1,2,3,4,5,6,7,8,9]``` be different from ```[1,2,3,4,5,6,7,8,9]```?) but when I use ```Test.assertEquals()``` to check for equality, it says that the 2 arrays are not equal.  As long as this problem persists, I would not be able to finish and publish this Kata.

Please help me ASAP.  Any help, suggestions or advice would be much appreciated.  Please also notify me if it is an error on my part.

**Comment by mcelearr** [comment]
Hi Donald. This caught me out initially as well at first. `Test.assertEquals()` asserts that the arguments it is passed have the same value. This works for strings, numbers and booleans, but not for arrays or objects. An array of numbers does not have a 'value'. To test arrays and objects we use `Test.assertSimilar()`. Some other testing frameworks use `deepEqual()` for objects - it's the same idea.

Hope that answers your question!

**Comment by DonaldKellett** [comment]
Thanks a lot @mcelearr, I will change ```Test.assertEquals()``` to ```Test.assertSimilar()``` once I return to that Kata :smile:

**Comment by AseelM** [comment]
Thanks A mill @mcelearr had the exact same issue but now its resolved!
And thanks for the feedback @DonaldKellett :)

**Comment by mike1234-pixel** [comment]
Thanks @mcelearr legend!
