### ISSUE TITLE
Name is already taken when editing a Kata

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars.com#2390]
**Describe the bug**
As you can see in the screenshot it seems to be a security problem not very well handled.

**To Reproduce**
Not sure, but probably my StickyPassword plugin filled some hidden fields

**Expected behavior**
This should not happen at all, it should allow sending the edit of a Kata's description.

**Screenshots**
![image](https://user-images.githubusercontent.com/1063901/119360844-aa08e200-bc70-11eb-831a-c8b45d5bc3d9.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser: Firefox
- Version: 88.01

**Comment by javatlacati** [comment]
I think that the problem is produced by my plugin, however, I think that a Kata name with an email format should not be accepted.

**Comment by kazk** [comment]
This is not our bug.
A plugin installed in your browser incorrectly filled in the kata editor form. You had this already happen to [another kata](https://www.codewars.com/kata/57507369b0b6d1b5a60001b3/) and had saved it with the email name. The error in this screenshot is preventing you from saving another kata with the same name ("is already taken").
