### ISSUE TITLE
Inconsistency between tags shown in `details` && editor

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2392]
In the kata-details page or  front-page, there's six tags and one of them being `OOP`. See the image below ~~

![image](https://user-images.githubusercontent.com/65498235/119477291-681b9100-bd81-11eb-93a6-3e4992ef600f.png)

But in the editor, there's only 2 tags and one of them being `enumerators` which comes out of nowhere. Not sure if this was a cache issue, but I can't remove the `OOP` tag in editor as requested by someone. See image below ~~

![image](https://user-images.githubusercontent.com/65498235/119477723-cba5be80-bd81-11eb-9d16-7d7340606516.png)

**Comment by kazk** [comment]
This is by "design" :man_facepalming:

Users are not allowed to add arbitrary tags which is understandable. But usually this is done by showing similar predefined tags as you type.

Tags shown on the details page is "derived" from what users entered.

I don't know why it's done like this. The mapping is a huge mess (lots of questionable associations), and it also has inheritance too. I hate it, but this is working as expected.

Here's how it expands:

- `arrays` maps to `Arrays`
- `enumerators` maps to `Iterators` (?)
  - `Iterators` is under `Object-Oriented Programming` (?)
  - `Iterators` is under `Control Flow`
    - `Control Flow` is under `Basic Language Features`
      - `Basic Language Features` is under `Fundamentals`

Tags are not really useful at the moment. I do want to redefine them and maintain them openly.

**Comment by Voileexperiments** [comment]
This is a duplicate of #1594.

**Comment by ejini6969** [comment]
Okay, Thanks !!! Didn't know it has such complicated nested structure, closing this for now ~~
