### ISSUE TITLE
Memory leak in Test Cases?

### ISSUE THREAD

**Issue by Alfheri** [codewars/codewars.com#2393]
Following up on a comment to my C solution to [this kata](https://www.codewars.com/kata/54c27a33fb7da0db0100040e/c), I might have done something very stupid. In order to get some statistics on runtime, I added a loop to fixed tests (resulting in 20000 test cases). After some tries my browser complained about slow execution of content and the tab froze.

I use firefox-esr on a debian linux. Looking into this problem with top I found, that memory usage for the tab/WebContent grows by approximately 0.7gb with each run of the test cases.

**Comment by hobovsky** [comment]
The freeze and slow down of your browser is a known problem related to large amount of assertions, which are handled poorly by test output panel. Every red and green line in the panel requires some processing in DOM, and in some testing frameworks, when you have many assertions, you get many green (or red) lines and browser does a lot of work processing them. I think the performance problem is noticeable with just as many as 1000 assertions, so 20000 is definitely killing it.

It's a known issue and workaround is to not have many assertions in languages with noisy testing frameworks ;) Just call your function many times in a loop, but do not call `cr_assert_eq`.

Rising memory usage is (I believe) not related to this issue of output panel, but rather to memory management of the browser itself. Browser decides when to release memory and it probably decided there's still plenty to work with. Unless there's something strange happening, like green/red entries not being properly detached from the DOM tree, so they cannot be collected, but I do not recall anything like this being noticed before.

**Comment by Alfheri** [comment]
Thanks for the info. It is definitely the calls to `cr_assert_eq`. I don't know about "being properly detached from the DOM tree", but the problem disappears with only one call to `cr_assert_eq`.
