### ISSUE TITLE
Manually changing "language" URL parameter during initiation/sign-up

### ISSUE THREAD

**Issue by NormHarrison** [codewars/codewars.com#2394]
**Describe the Bug**
I noticed that Pascal was listed under the "Additional Languages" category, but wasn't an available choice as a language to use during the initiation/sign-up phase. I saw that the language seemed to be chosen via a URL parameter, which upon manually setting to Pascal, presented me with a proper Pascal example. I completed it and was shown the actual sign-up screen, where I choose to sign-in using Github instead. After doing so, I receive the "Internal server error" error presented in the image attached below.

I of course understand that this is a language still in beta development on the website, and that the URL parameter wasn't meant to be changed to a language in such state, but in addition to the above error (which isn't really a true "bug"), when I try to now log-in using my specific Github account, it refuses to continue and says my account is "invalid", which understandably may be a sort of blacklist feature.

**To Reproduce**
Manually change the `language`URL parameter during initiation/sign-up to one of the additional/beta languages listed below (and then sign-up with Github? I am unsure if this would also happen while creating a regular account).

**Expected behavior**
I assumed no syntax/logic problem to solve would appear, or at least after it did, that maybe I could still sign-up as normal (probably the former).

**Screenshots**
Specific error after signing-up via Github:
![image](https://user-images.githubusercontent.com/69526918/119734748-07ec2400-be41-11eb-84ce-7033d1eabeef.png)

The Pascal problem presented by manually changing the URL argument:
![image](https://user-images.githubusercontent.com/69526918/119736362-323ee100-be43-11eb-9701-e8a91aa8b3c5.png)

Trying to login using Github afterwards:
![image](https://user-images.githubusercontent.com/69526918/119736501-6914f700-be43-11eb-950c-b4440da04dc9.png)

**Browser**
- OS: Linux
- Browser Firefox
- Version 78.10.0 ESR (64-bit)

**Additional context**
I understand that this is definitely undefined behavior, I just thought it was somewhat strange that I was allowed to continue, but now seemingly unable to do so with this specific Github account

**Comment by MobulaKuhlii** [comment]
Have you tried signing up using non-beta language (this really doesn't matter, you can change your language setup afterwards or filter katas by desired language), because you probably didn't create an account after all (although I'm not 100% sure and making dummy github account to test that is a pain)?

**Comment by NormHarrison** [comment]
Thank you for your response, what you stated seemed to indeed be the case. Even though I was presented with the Github external account linking page, it seems that my account did not technically exist yet. I signed up using a direct email/password, then linked the account afterwards and everything appears to be normal. Sorry that this ended up being a non-issue, I was definitely just foolishly fiddling-around with things that were clearly not meant to be manually edited, although it is neat to see that the examples for some of the beta languages are ready.

Thank you again.

**Comment by ede-lab** [comment]
I have the same error. I intend open account on codewars to learn programming through challenges coder but I can't because when I tried sign in through my account github I receive the same error. What can I do to solve this issue?

I am assuming that it is possible create an account as a simple user and I don't need be a company or an educator.

**Comment by MobulaKuhlii** [comment]
First question: without listing steps you've taken to create an account there's no telling what went wrong (have you clicked 'sign up', chosen language, passed the intro kata and then linked your github?).
Second question: there's only 'simple' user account on codewars (from signing up perspective that is), and you can also sign up using email address.

**Comment by ede-lab** [comment]
I am trying log in using my account on github because I can't create a free account on the website. On this video (link: https://we.tl/t-3NsMshPWPk) you can see all steps I use to try logging on the website through my account github.

Thanks

**Comment by ede-lab** [comment]
Hello, sorry for pulling the topic up but anyone can help me with this issue? thanks

**Comment by ede-lab** [comment]
Hello everyone, again :) I just solved my issue. I just needed, firstly, pick which language I want learn and accept the challenge, before I can create an account on codewars website.
