### ISSUE TITLE
Perl logo is badly cropped

### ISSUE THREAD

**Issue by Kacarott** [codewars/codewars.com#2398]
I don't know if this technically counts as a bug, but it irks me.

The Perl logo (representing which languages a kata is available in) is badly cropped.

![](https://user-content.gitter-static.net/27af475caa8747a9785fa671a23d2824471c48cc/68747470733a2f2f66696c65732e6769747465722e696d2f3535613663643136356530643531626437383762376433362f3674485a2f7468756d622f53637265656e2d53686f742d323032312d30362d30362d61742d362e32302e32382e3534332d706d2e706e67)

Notice the missing left side of the circle is missing.

That is all, have a nice day.

Edit: Chrome/MacOS

**Comment by XRFXLP** [comment]
For me (Zoom : 200 %, Browser : Firefox 89, OS : Linux mint)

![image](https://user-images.githubusercontent.com/23459568/120932236-9c446980-c712-11eb-8041-8a38e5483044.png)


Which seems to me to be of good shape.

**Comment by Kacarott** [comment]
So another user with Chrome has reported no issue. I guess it is something on my end, perhaps a buggy extension. Apologies for the false alarm.
