### ISSUE TITLE
Can't submit a solution

### ISSUE THREAD

**Issue by RekaKR** [codewars/codewars.com#2400]
Hi,

I wanted to submit a solution but I couldn't because I got no submit button.
There was a moment I got for a sec but it's gone away and didn't get back. I tried to refresh, deep refresh, clearing the last hour of stored data.
Also, since then I did other Kata which I could submit.

(I attach a screenshot with my solution but I tried with longer or other solution too however it says that is correct.)
(Checked other, similar bug report but couldn't fix this.)

https://www.codewars.com/kata/57fe90ae08d102a2ba0011e6
![bug](https://user-images.githubusercontent.com/63584551/121668528-b03df180-caab-11eb-949d-f3db485bdf0c.png)

I'm using:
- OS: win7
- Browser: chrome
- Version: 91.0.4472.101 (64-bit)

**Comment by MobulaKuhlii** [comment]
Per design you can't submit solutions to drafts.

**Comment by hobovsky** [comment]
To accept solutions, kata has to be published. This kata is a draft, so maybe it was never published,  or got unpublished at some point at the past. It's still possible to run tests, but solutions are not accepted.
