### ISSUE TITLE
Code wars Yello Form 

### ISSUE THREAD

**Issue by ayushrana182** [codewars/codewars.com#2401]
**Describe the bug**
I cannot fill out the form because it has no options for my country, instead shows states of the USA only. Same issue with the university field.
![Capture](https://user-images.githubusercontent.com/43984189/122018532-acc7a480-cde2-11eb-97c2-329259bc86e2.PNG)

**Comment by MobulaKuhlii** [comment]
This may indicate that it's not available anywhere outside the US and I don't think this belongs in codewars issue thread.

**Comment by ayushrana182** [comment]
Hmm, could be that or the form has a bug? Where do you recommend I post this?

**Comment by XRFXLP** [comment]
From which site you've got this form? AFAIK there is no such form on codewars.com

**Comment by ayushrana182** [comment]
It popped up when I logged in to code wars today. This is the URL (https://codewars.yello.co/)

**Comment by hobovsky** [comment]
The form appeared recently (yesterday?) and took some users by surprise.

AFAIK @jhoffner works on this topic?

**Comment by jhoffner** [comment]
Yello rolled out a new form that seems to be a bit of a mess. For now I'm suspended the popups until we fully work out all of the kinks.  In the meantime if you want to continue to sign up, here is an older form that supposedly works better. 

https://codewars.yello.co/external/form/bKuBtDiUssbED481orsNNQ

If you are out of the US, you have to select "Outside of the United States" as the country field. I know, this is poor UX. I'm working with them to fix it.
