### ISSUE TITLE
Rank degraded from 3kyu to 7kyu  and reduce the honor 

### ISSUE THREAD

**Issue by pallwee88** [codewars/codewars.com#2403]
my account is degraded .
I am unable to earn any honor there after solving any kata.

profile link 
https://www.codewars.com/users/Pallwee

Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by DonaldKellett** [comment]
Well you were found plagiarizing the top solutions for at least 3 Kata that
are `4 kyu` or above, and therefore got your progress revoked for those
Kata (possibly with an additional penalty). Consider your lesson learned.

**Comment by Blind4Basics** [comment]
rather like 35 plagiarized /45 kata, actually
