### ISSUE TITLE
Updated score is not showing up for My Profile: https://www.codewars.com/users/MuraliNVN

### ISSUE THREAD

**Issue by MuraliNVN** [codewars/codewars.com#2407]
Updated score is not showing up for My Profile: https://www.codewars.com/users/MuraliNVN

**To Reproduce**
Click on link
https://www.codewars.com/users/MuraliNVN

**Expected behavior**
![image](https://user-images.githubusercontent.com/86220907/122714669-4bda1980-d285-11eb-8540-805e6be84117.png)

Actual Result: 
**Screenshots**
![image](https://user-images.githubusercontent.com/86220907/122714554-17fef400-d285-11eb-9b57-234bce001f6b.png)

**Comment by hobovsky** [comment]
It was discovered that many solutions of this account are copies of other solutions. Your points got revoked, the account was locked out of some areas, and a ban request has been filed against it.

**Comment by MuraliNVN** [comment]
Thank you for checking
