### ISSUE TITLE
Rank up from 1 kyu to 1 kyu 

### ISSUE THREAD

**Issue by e-mihaylin** [codewars/codewars.com#2411]
Yesterday I had 1st kyu (had it long time ago, js and overall) and 90%+ to 1st dan on the circle diagram in profile.
I got some more honor from katas and got rank up notification about up to 1st kyu.

Current stats:
Honor:21,001 (99%from js)
Overall:1 kyu / 0.1%
JavaScript:2 kyu / 99.5%

profile: https://www.codewars.com/users/e.mihaylin

Rank table here (I dont remember clear, but it seams that smth changed in ranking with time) https://docs.codewars.com/gamification/ranks/ says now:
1 kyu | 13,147
1 dan | 35,759

So the diagram was falsy about almost 1st dan yesterday and it is falsy about  0.1% with 21,001 honor now.

**Comment by Blind4Basics** [comment]
Hello,

Yes, some points got removed because it's been found you plagiarized some solutions to purple or blue kata. The current stats are what's left.

Honor has "nothing" to do with your rank, so that part is unrelated.

Cheers

**Comment by e-mihaylin** [comment]
Hi.
What is considered as plagiate and forbidden?
Interested in edge cases:
- Is it plagiate for any result, when solutions are grouped as similar?
For example, there are some katas (for example, code golf, with short solutions, when grouping is unavoidable).
- Is it plagiate when I complete kata with my solution, submit it, take someones other solution after my 1st submit, try it, improve it and submit again?
- Is it plagiate when I take not my solution before my 1st submit, try it (not submit), and then a) submit my solution based on not my b) submit my solution not based on not my.
As far as I remember, I did not submitted just copied elsewhere code, but I have putted it to successfull tests many times (remeber many times when could not get needed time complexity and tried not my approaches).
I want to understand where the border line is to not to cross it.

**Comment by Blind4Basics** [comment]
> * Is it plagiate for any result, when solutions are grouped as similar?
>   For example, there are some katas (for example, code golf, with short solutions, when grouping is unavoidable).

Code golf kata are a bit edgy. No general answer there, it depends on the context and other parameters. Otherwise grouping matters, yes. But not only.

> * Is it plagiate when I complete kata with my solution, submit it, take someones other solution after my 1st submit, try it, improve it and submit again?

No

> * Is it plagiate when I take not my solution before my 1st submit, try it (not submit), and then a) submit my solution based on not my b) submit my solution not based on not my.

I'm not sure to understand what you're describing. Apparently, you're talking about trying in the trainer a working solution that isn't yours first. If so, answer is yes.
 
> As far as I remember, I did not submitted just copied elsewhere code, 

According to what's been found in your solutions, you did. From time to time.

**Comment by e-mihaylin** [comment]
Thank you
