### ISSUE TITLE
Emojis are rendered on separate lines from other text with huge additional margins

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2413]
The CSS rules for emojis include `display: block` which moves them to separate lines, and `margin-bottom: 2em; margin-top: 2em` which add huge amount of space. I'm not sure whether it's intentional, but I'd be surprised to see emojis **not** being rendered together with the regular text.

A comment with an emoji:

![image](https://user-images.githubusercontent.com/31668662/123555071-1dc86e00-d78c-11eb-9a55-87616629ce33.png)

Inherited CSS rules for emojis which cause this behavior:

![image](https://user-images.githubusercontent.com/31668662/123554936-3d12cb80-d78b-11eb-9f5e-8cc5102945ec.png)

**Comment by kazk** [comment]
Thanks, deployed the fix.
