### ISSUE TITLE
Update NASM to 2.15.05

### ISSUE THREAD

**Issue by uniapi** [codewars/codewars.com#2416]
**Please**, update _NASM_ to version `2.15.05` to use more features!
The current codewars version is 2.11.
Here is the [NASM Version History](https://nasm.us/doc/nasmdocc.html).

**Comment by Voileexperiments** [comment]
Should be migrated to https://github.com/codewars/runner ?

**Comment by uniapi** [comment]
Thanks! Just has issued it there...
