### ISSUE TITLE
Unfollow users who have been suspended

### ISSUE THREAD

**Issue by sharedbyayla** [codewars/codewars.com#2418]
## The Problem
I recently realized that I am unable to unfollow users who have been suspended. These users also show up in inappropriate locations on the social list. 

The user aandreispinu has been suspended. Despite being suspended and having 0 kyu this user persists on my social list, above user accounts that have racked up more kyu.
![Social List including a suspended user](https://i.imgur.com/kTxoYAT.png)

I only even realized the user was suspended after visiting their profile page. 
![Suspended user's profile](https://i.imgur.com/BjiLLmH.png)

## The Ideal Solution
Once suspended, a user would be automatically removed from the social lists of the people who are allied with or following them. However, as I understand it, the clan/follow feature is not crafted for scale, and the time it would take to execute a mass unfollow would be so great that this solution will likely not be implemented. 

## Alternative Solutions
1. An "Unfollow" button on suspended profiles visible only to users who are currently allied with/following them.
1. An automatic unfollow action that occurs if/when you visit a suspended profile that you're following-- instead of just saying "This account has been suspended" it could also include "You will no longer see it on your social list".

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1dxr) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Connections to a banned user are now cleared when the user is banned, and the fix was applied to already banned users, so this issue should be resolved now.

**Comment by saarcoder** [comment]
![unfollow](https://github.com/user-attachments/assets/c2f6b6eb-b5c2-45ae-b2bf-9da023b995d2)
Is this true as well if I follow a group that already lists a banned user? I just ran into the issue when following a new group (Gensokyo, in my case).
