### ISSUE TITLE
Mazerunner Kata: Even published solution times out

### ISSUE THREAD

**Issue by e-user** [Codewars/codewars.com#242]
Quite some time ago, I created the Mazerunner Kata to fill the gap of high-tier Clojure Katas. Unfortunately, no solution ever submitted, _including the one I used to create the Kata_, works. There have been several complaints already and I'd really appreciate your support to help me release this Kata.

http://www.codewars.com/kata/mazerunner

**Comment by kazk** [comment]
I'm sorry that you never got any response. Closing this as the author's solution doesn't timeout anymore with the new runner.
