### ISSUE TITLE
Allow kata console to be resizable

### ISSUE THREAD

**Issue by JomoPipi** [codewars/codewars.com#2436]
It's pretty frustrating that I can't resize the height of console window when authoring kata. It can really get in the way if there are some important logs I need to look at.

I guess a good solution would be inserting a draggable area that lets you set its height, or even a full-screen button.

I tried just setting the height manually in the browser's dev tools, but it didn't look great.

![](https://cdn.discordapp.com/attachments/854768126546018314/867535033522585660/unknown.png)

**Comment by kazk** [comment]
https://user-images.githubusercontent.com/639336/126572262-408b8e1e-5c72-4875-8e51-91c13912726a.mp4

I'll need to test more, but I think this is good enough.

**Comment by kazk** [comment]
Deployed

**Comment by JomoPipi** [comment]
Awesome, you're the best!!
