### ISSUE TITLE
I can't comment or vote anywhere.

### ISSUE THREAD

**Issue by Gargooie** [codewars/codewars.com#2438]
Good day, I confirmed my email but still, I can't vote for solutions and comments won't be added, the post button just doesn't work. Why can't it work?

**Comment by hobovsky** [comment]
What is your Codewars username?

**Comment by Gargooie** [comment]
Gargooie. I can't comment anywhere, for example here 
https://www.codewars.com/kata/55908aad6620c066bc00002a/solutions/python

**Comment by Blind4Basics** [comment]
looks like:

> It's a known problem, and for now it's an unsolvable one, unfortunately.
> [See explanation here](https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658)
> 
> related: #2048, #2255 and some others.

> I can't comment or vote **anywhere.**

are you sure? For example, can you [here](https://www.codewars.com/topics/site-design)? If that doesn't work there, we'll need you codewars username.

**Comment by Blind4Basics** [comment]
> Gargooie. 

that's not your username.

**Comment by Gargooie** [comment]
> > Gargooie.
> 
> that's not your username. : https://www.codewars.com/users/Gargooie => dead end.
> 
> Did you confirm your account?

yes I confirmed it. it's undercase https://www.codewars.com/users/gargooie

**Comment by Gargooie** [comment]
> looks like:
> 
> > It's a known problem, and for now it's an unsolvable one, unfortunately.
> > [See explanation here](https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658)
> > related: #2048, #2255 and some others.
> 
> > I can't comment or vote **anywhere.**
> 
> are you sure? For example, can you [here](https://www.codewars.com/topics/site-design)?

yes I can. I couldn't for solutions of the tasks I completed

**Comment by Blind4Basics** [comment]
ok, so it's the issue above. You just happened to solve only old kata where there are already too much data/solutions/comments.

Closing & cheers
