### ISSUE TITLE
Submit error

### ISSUE THREAD

**Issue by iardelyan** [Codewars/codewars.com#244]
I have complete "Maximum Length Difference" task. Than I press "Run Test", and receive:

test(MaxDiffLengthTest)
mxdiflg Fixed Tests
Test Passed

But when I press "Submit" I get:

test(MaxDiffLengthTest)
mxdiflg Fixed Tests
0
test1(MaxDiffLengthTest)
100 Random Tests
Test Passed

What does it mean? I have already pass 1st test, but than I get "0".

**Comment by jhoffner** [comment]
I'm not following. "Run Test" usually has a smaller set of tests whereas "Submit" runs against the full suite of tests. Is that the issue or is something else happening? Screenshots would be helpful.

**Comment by shpp-iardelyan** [comment]
I already get it, and complete this task. Thank you
