### ISSUE TITLE
Discourse Markdown Editor is not actually WYSISYG in this case

### ISSUE THREAD

**Issue by JomoPipi** [codewars/codewars.com#2444]
**Describe the bug**
What I see in the viewer:
![image](https://user-images.githubusercontent.com/39433859/127999963-bf5bc437-ab94-4750-b8e9-6a09ef41c9ef.png)
The code:
![image](https://user-images.githubusercontent.com/39433859/128000059-e1e2467d-87e8-4d9e-b761-2462a5060297.png)
The result (nothing there):
![image](https://user-images.githubusercontent.com/39433859/128000161-b8e04e36-8dd9-4694-bf1e-fba0b92fc623.png)

- Browser: avast

**Comment by XRFXLP** [comment]
Duplicate of https://github.com/codewars/codewars.com/issues/2276

**Comment by JomoPipi** [comment]
> Duplicate of #2276

Closing, in that case. 

P.S. @XRFXLP, would you mind letting me know if there is anything I could do to help improve your opinion of my kata, here?
https://www.codewars.com/kata/60f5868c7fda34000d556f30/

**Comment by JomoPipi** [comment]
> Duplicate of #2276

Closing, in that case.

P.S. @XRFXLP , would you mind letting me know if there is anything I could do to help improve your opinion of my kata, here?
https://www.codewars.com/kata/60f5868c7fda34000d556f30/

**Comment by XRFXLP** [comment]
> would you mind letting me know if there is anything I could do to help improve your opinion of my kata, here? 

No, because that would be a lot of work from my side as I'm reluctant to get involved in the kata feedback process anymore.

I see you were bothered about the downvote, for which I've removed my vote.

**Comment by JomoPipi** [comment]
**Thank you!!** 😃

If there's anything I can do for you, just reach out to me.

![](https://www.crownconnect.com/assets/ThankYou.jpg)
