### ISSUE TITLE
Can't sign in. Redirected to codewars.com

### ISSUE THREAD

**Issue by shalick** [codewars/codewars.com#2447]
I can't Sign In. 

After I try it by github or email: 

![image](https://user-images.githubusercontent.com/5791344/128099751-255be2a0-3f1e-4680-94fd-db0e97feac73.png)

I am redirected to the main page with proposal to Enlist

![image](https://user-images.githubusercontent.com/5791344/128099928-6588769c-0e4e-4084-b6cb-f56a71c1376a.png)

Can't Enlist because name is already taken. 

- OS: [Linux Lite]
- Browser [tried chrome, firefox, brave]
- Version [latest]

**Comment by kazk** [comment]
Have you tried in Incognito/Private? I've had a few users report this via email and that worked for them (issue caused by their browser like extensions).

If that doesn't work, can you try looking at the Network tab in Developer tools? You should see something like this:

- `POST https://www.codewars.com/users/auth/github` 302
- `GET https://github.com/login/oauth/authorize` 302
- `GET https://www.codewars.com/users/auth/github/callback` 302
- `GET https://www.codewars.com/dashboard` 200

**Comment by shalick** [comment]
Yes I tried in Incognito/Private in Chrome and Brave. 
I took different name and email and push ENLIST. Then Sign out. Now I can log in via email to my old.
I logged in and deleted account with new name and then I can log in to my old via github.

Thank you very much for your comment and work.

**Comment by kazk** [comment]
Thanks for reporting back. I still don't know what happened, but I'm glad you got in.

**Comment by kyryll-yevseiev** [comment]
I still can't sign in with my old account. I create a new one and with a new one, I can log in and log out. But the old one still doesn't work. Frankly speaking, it's my second account I can't sign in. Can you help to merge the old accounts username babaloo (I don't remember email) and kyryll.yevseiev@gmail.com and let me in with my kyryll.yevseiev@gmail.com account?

**Comment by spectorari** [comment]
Yes this problem is happening to me too. I get redirected from the login back to codewars.com.

**Comment by spectorari** [comment]
I actually fixed this by:

1. Delete my cookies
2. Log in not using GitHub.
3.  If you tried using with GitHub, go back to step 1. 

For me, the bug lies in attempting to login with GitHub.

**Comment by Eveieve** [comment]
I have the same problem. I can't sign up without Github because my email is already taken. Whenever I click login via Github it gets redirected to the home page.

**Comment by alstonnguyen** [comment]
Same problem here, I'm getting redirected to main page after clicking sign in. I'm on version Version 112.0.5615.137 (Official Build) (arm64) of Chrome.

**Comment by Linyxus** [comment]
Same issue. Tried all the workarounds listed but none worked. :(

**Comment by elisabetCalavia** [comment]
The issue continues, I have tried what they indicate in the comments but I still can't login

**Comment by amittam104** [comment]
Facing the same log in issue. Redirected to the main page.
