### ISSUE TITLE
Using operator overloading against assertion methods

### ISSUE THREAD

**Issue by ozichukwu** [codewars/codewars.com#2448]
This shouldn't work
```python
class C:
    def __eq__(_, __): return True

def kata_solution(): return C()

test.expect(kata_solution()) #test passed
test.assert_equals(kata_solution(), True) #test passed
test.assert_equals(kata_solution(), False) #test passed
```

but it does (at least in [this kata](https://www.codewars.com/kata/reviews/5a49fca1f3a1435a900000ab/groups/610acddbf1cd350001e05817))

**Comment by DonaldKellett** [comment]
Looks like a standard monkey-patching cheat. We do not try to prevent all possible cheating solutions from passing (because that would be next to impossible); instead, cheaters abusing such solutions have their points revoked and repeat offenders may receive a permanent ban.
