### ISSUE TITLE
Broken Account?

### ISSUE THREAD

**Issue by mahksmith** [Codewars/codewars.com#245]
I am user kyb3r on codewars.

Two things I've noticed with my account:
1) not sure if this is actually a bug, but on "My Next Challenge" on the dashboard, I can ONLY see Beta Katas for Fundamentals in any language no matter the setting in my profile.
2) in trying to fix the bug above, I attempted to delete my account and start over but pressing the delete button appears to do nothing, and I can log into my account 24 hours later.

**Comment by jhoffner** [comment]
Yeah thats weird, that shouldn't happen, especially if you have the "fundamentals" training selected.

**Comment by jhoffner** [comment]
A fix has been deployed
