### ISSUE TITLE
Cannot change Development Experience

### ISSUE THREAD

**Issue by sixcy** [codewars/codewars.com#2450]
Describe the bugWhen I go in https://www.codewars.com/users/edit and want to change my Development Experience from Junior Developer to Mid-Level Developer, it rolls back to Junior Developer as soon as I click on "Update" at the bottom, without producing any error.

To ReproduceNo idea if it is reproducible with other accounts. You would probably need my account to reproduce it.

Expected behaviorMy Development Experience should have been updated to Mid-Level Developer

ScreenshotsShould not be necessary

Browser

OS: Ubuntu 20.04 LTS
Browser: Firefox 90.0.2

Additional contextThe issue appears to be for any other field

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1e1b) by [Unito](https://www.unito.io)

**Comment by Blind4Basics** [comment]
I cannot reproduce it, now.
