### ISSUE TITLE
"Description cannot be approved" for translation

### ISSUE THREAD

**Issue by Expurple** [codewars/codewars.com#2454]
I'm having trouble with approving a [translation](https://www.codewars.com/kumite/6113f3fb37b4ec003e675609) which I've made for my own [kata](https://www.codewars.com/kata/6112917ef983f2000ecbd506).

I click "approve", then "I'm sure" in the confirmation dialog, then this error shows up:

> Description cannot be approved, recent changes from related record must be merged first.

As far as I understand, this is a merge conflict in the description, caused by changes in the original kata that happened after I've started working on the translation. However, I've found no way around it.

### Expected behavior

Successfull automatic merge of the translation OR a better message about how to fix the error.

### What I've tried

I've searched this error message on Google and among existing issues on Github. Found #2262, but it has no info about fixing the error itself.

To avoid conflict, I've also tried submitting different versions of the description:
1) The current description of the kata + one new language-specific paragraph.
2) The current description of the kata as is.
3) An older version of the description (so that "Diff" tab disappears on the [translation page](https://www.codewars.com/kumite/6113f3fb37b4ec003e675609)).

I've also had an idea to back up the translation locally, delete it and then create a new one, based on the final version of the kata. But apparently there is no way to delete this translation from drafts and start from scratch.

**Comment by hobovsky** [comment]
Translation process is known for its deficiencies and description merge conflicts are a major PITA when approving translations. AFAIK improvements ot translation process are prioritized quite high, but I do not know any more details.

As for your specific problem, you can try following:
- Grab the most recent version of the description, be it from kata editor, or from freshly started, new translation (which will be later discarded).
- Fork the translation which you are not able to approve.
- Replace forked translation with the translation  obtained in the first step. Add language-specific paragraphs if necessary.
- Publish the translation. Try to approve it, but I am not 100% sure if kata authors can approve their own translations. If not, let someone know at `#help-translate` channel.

In case of any further problems you can come to Codewars Discord: https://discord.gg/mSwJWRvkHA for more direct help.

**Comment by Expurple** [comment]
Thank you for quick response, this method with forking heped. Approving your own translations works indeed, I've done it before with my other kata.

I'm marking my issue as resolved, although it still would be nice to see some tip on the site itself, without having to go to Github.
