### ISSUE TITLE
 Convert PascalCase string into snake_case

### ISSUE THREAD

**Issue by alexbprofit** [codewars/codewars.com#2462]
when clicking from test, all tests passed but when i click attempt, i got exception:

```
Traceback (most recent call last):
  File "/workspace/default/src/codewars-test/codewars_test/test_framework.py", line 111, in wrapper
    func()
  File "tests.py", line 32, in tests
    expected = re.sub(r'(.)([A-Z])', r'\1_\2', str(test_inp)).lower()
NameError: name 're' is not defined

**Comment by hobovsky** [comment]
If you mean this kata: https://www.codewars.com/kata/529b418d533b76924600085d then it's a kata bug and should be raised as a kata issue in its discourse.

This board should be used for issues related to Codewars platform itself, and not for specific kata.
