### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by 69abadon69** [codewars/codewars.com#2463]
**Describe the bug**
On submit  is shows : "Request failed with status code 404"

**Expected behavior**
It had to write some scores, like below, but it is not, same in kyu checker too. (https://auseika.github.io/kata-scan/)

**Screenshots**
![image](https://user-images.githubusercontent.com/58501268/130323007-f16531d7-36d9-481d-a5e0-247d0fd6f3b1.png)
Kyu checker:
![image](https://user-images.githubusercontent.com/58501268/130323093-cea16281-2996-4d8a-bf2e-37dd81ef90b1.png)

**Browser**
- Browser [chrome,]

**Additional context**
Others have the same problem too on my course.

**Comment by FArekkusu** [comment]
This is a tool provided by a user who AFAIK is not affiliated with CW. If you have any problems with it, raise the issue on the [related repository](https://github.com/auseika/kata-scan), not here.
