### ISSUE TITLE
The translation page shows outdated kata status

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2464]
The translation page shows the kata's status from the time that translation was published instead of its actual status. For example, [this translation](https://www.codewars.com/kumite/611f7e44ce90330042190d73?sel=611f7e44ce90330042190d73) says that the kata is still in beta, even though it's already approved:

Screenshot of the kata details page:
![image](https://user-images.githubusercontent.com/31668662/130366912-3b78fe28-35b3-4701-af5f-b2c6b95bb189.png)

Screenshot of the translation page:
![image](https://user-images.githubusercontent.com/31668662/130366998-1ccbd8c1-b059-40c8-a412-bf70b2debd4e.png)

**Comment by kazk** [comment]
Should be fixed
