### ISSUE TITLE
I can't request password recovery

### ISSUE THREAD

**Issue by lezzys** [codewars/codewars.com#2468]
**Describe the bug**
After pressing (Forgot your password?) on a sign in page [https://www.codewars.com/users/sign_in](url) I am redirected to a page where I am asked to enter my name and email address for registration. I can't request password recovery in any way. I know that my user name is smth like efik, but I want to register new account lezzys with my github and my email that was use for old account.

Thank you in advance for the answer.

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**
Request my email to send a message to restore the password from the account.

**Screenshots**
![1](https://user-images.githubusercontent.com/61874723/131258828-f2fcf269-8515-4fe1-8539-14f1a525d3e0.png)
![2](https://user-images.githubusercontent.com/61874723/131258832-38f5d13b-7585-43e8-b96e-7ccb37557e2c.png)

**Browser**
Opera last version.

- OS: Windows 10 last update
- Browser opera
- Version 78.0.4093.184

**Comment by kazk** [comment]
Can you open https://www.codewars.com/users/password/new ?

**Comment by lezzys** [comment]
Yes but I redirected to the same page. Here's screenshot.
![3](https://user-images.githubusercontent.com/61874723/131307638-81e149b5-eee6-480a-b9e0-0b92b4de1274.png)

**Comment by kazk** [comment]
Have you tried clearing cookies? Or Incognito/Private Window?

**Comment by lezzys** [comment]
Omg, I forgot that I can clean cookie, that's fixed my problem. Thank you for fast answers and have a good day!
