### ISSUE TITLE
Javascript tests bypass

### ISSUE THREAD

**Issue by ITFreha** [codewars/codewars.com#2481]
**Describe the bug**
Some katas use `chai` library to verify a solution. But there is a way to override the behaviour of methods used for verification.

**To Reproduce**
`require('chai').assert.strictEqual=()=>{}`

I've used this for fun to bypass verifcation in the following katas:
https://www.codewars.com/kata/5fad08d083d5600032d9edd7
https://www.codewars.com/kata/56a73d2194505c29f600002d

**Expected behavior**
Codewars infrastructure checks that validation methods have been modified

**Additional context**
And also I do not know how to cancel my solutions that are using bypass

**Comment by hobovsky** [comment]
Please see https://github.com/codewars/codewars.com/issues/1970#issuecomment-552014145

Closing as a duplicate.
