### ISSUE TITLE
Editing a collections name: text field does not respond to dark mode

### ISSUE THREAD

**Issue by falcowinkler** [codewars/codewars.com#2486]
**Describe the bug**
The testfield when editing a collections name is white with a white font. You can barely see the name that you typed.

**To Reproduce**
Edit a collections name in dark mode.

**Expected behavior**
The text field is dark, with a white color.

**Screenshots**
<img width="285" alt="Screenshot 2021-09-18 at 20 55 18" src="https://user-images.githubusercontent.com/8613031/133905677-56a5439b-6ff4-4d9a-88c3-ebfd4d20dc13.png">

**Browser**

- OS: macOS
- Browser Chrome
- Version 93.0.4577.63

**Comment by kazk** [comment]
Thanks for reporting. It's been like this for a while.
Deployed the fix.
