### ISSUE TITLE
Ability to remove previous clan members when changing clan

### ISSUE THREAD

**Issue by rmjoia** [codewars/codewars.com#249]
Hi to all! Great work here.

I don't know if this is a bug or not but, I've added a clan to my profile, then I changed it. In the dashboard, by the rule, all users in the same clan were added as allies, then, I've changed it and the same users remained there, so, I'm the only one in the list with a different clan. I think that, if you change a clan, if not automatically removed you could be asked if you wanted to remove them.

Thank you for the support.
Regards,
Ricardo

**Comment by ojas121** [comment]
Same issue here. Any workaround or solution yet?

**Comment by SiRazoR** [comment]
I have joined my university's clan and saw 220 allies ... to be honest i prefer to have only my friends as allies and after removing that clan from my profile settings nothing happened. Is there really no solution after 2 years?

**Comment by swkane** [comment]
Checking in again. Would like to see a fix to this.

**Comment by coinfreakgr** [comment]
still no fix?

**Comment by miku86** [comment]
Hey folks,

Once upon a time, I joined a clan with ~300 members, so there were many folks with 1kyu-3kyu. Then I created a new clan for some beginner friends with 8kyu and changed my old clan name to the new one.

Because the people of the old clan don't get deleted, the Allies list on the dashboard is pretty useless, because there are almost only the 1kyu-3kyu guys from my old clan.

A feature/fix would be really awesome, thanks!

**Comment by javatlacati** [comment]
still no fix? x2

**Comment by mandoiwanaga** [comment]
Here's a simple solution using Selenium on this [repo](https://github.com/mandoiwanaga/codewars_unfollow_allies)

**Comment by anatols-baymaganov** [comment]
still not fixed, up

**Comment by RekaKR** [comment]
So I found out if you click on the profile to **`Unfollow`** the person then **`Block`** (then **`Un-block`**) it gonna go away from the dashboard (have to refresh) BUT it takes a LOOONG time if u have 300 members of a clan u don't want to see there.
Also, if you **`Block`** before **`Unfollow`** it won't be deleted from the dashboard.

I'm also waiting for the one click solution.

**Comment by kazk** [comment]
This was done earlier this year

**Comment by oleksiisedun** [comment]
Not sure what was done, it doesn't work for me.
