### ISSUE TITLE
The word "issue" inside an active issue tag is hard to see in light mode

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2491]
As the title says, there's not enough contrast between the black text and the dark red background color of active issue tags in light mode. Since red background is used only for active issues, it is obvious what the tag says/means, but it still looks very unpleasant IMO which you can see in the following screenshot if you're using light mode on github:

![image](https://user-images.githubusercontent.com/31668662/134547757-c5210e7f-7ce4-4639-89cb-2c551b24a0ec.png)

**Comment by kazk** [comment]
Fixed. Thanks for reporting.
