### ISSUE TITLE
Draft kata was temporarily shown in search result

### ISSUE THREAD

**Issue by Paradoxial-Name** [codewars/codewars.com#2495]
**Describe the bug**
Able to see Draft kata in the trainer tab

**To Reproduce**
Opening the kata trainer should suffice

**Expected behavior**
I expected not to see the draft kata ?

**Screenshots**
![Screenshot (109)](https://user-images.githubusercontent.com/39615673/135770388-3d3d2b84-06db-42fa-b829-6d53537758c7.png)

**Browser**
If applicable, please provide your browser information.

- OS: Microsoft
- Browser chrome, firefox (shows up in both)

**Comment by Blind4Basics** [comment]
maybe a browser cash thing. Did you try after you cleared it?

**Comment by Paradoxial-Name** [comment]
> maybe a browser cash thing. Did you try after you cleared it?
> 
> edit: ok, I see it too, even after clearing the cache

Yeah, tried it, also gone now.
So now idea

**Comment by Blind4Basics** [comment]
the author republished/unpublished in the meantime, so it's not visible anymore, but that's still worth of investigations.

**Comment by kazk** [comment]
How long was this shown? I think the search index was just outdated for a bit.

**Comment by Muhammad-Salman-01** [comment]
> How long was this shown? I think the search index was just outdated for a bit.

I think more than 2-3 hours

**Comment by Paradoxial-Name** [comment]
I think 2 or 3 hours (not sure though), it was up for nearly 30 mins when I reported
and b4b commented like 1+ hour after me, so maybe 2 hours ?

**Comment by kazk** [comment]
This shouldn't happen anymore
