### ISSUE TITLE
Missing Honor graph

### ISSUE THREAD

**Issue by RVdeKoning** [Codewars/codewars.com#25]
On my Profile page, my Honor graph (which is the circular thingy that shows the progress to the next rank) is missing. It does not show up in the latest versions of FF, Chrome and IE. Weirdly enough, it does appear on the mobile version of IE.

**Comment by bkaes** [comment]
Cannot reproduce in FF 36 on Windows 8.1 x64. Maybe it was some kind of temporary hiccup on your system? Is it sill missing?

**Comment by RVdeKoning** [comment]
Still missing. I'm running FF 37, Chrome 41 and IE 11  on Windows 7 x64. All cache memories cleared, but still.
It occurred to me I have this problem since I solved one Kata for each language on Codewars, so I now have a rank for each language. Might this be the problem?

**Comment by jhoffner** [comment]
Looks like it is a PJAX related issue, as the graph shows up fine for me when loading the page directly (Chrome), but not when navigating to it from another page.

**Comment by RVdeKoning** [comment]
looks like it is solved. Today I found the graph working in all my browsers. Did you solve this or am I just lucky today?

**Comment by GiacomoSorbi** [comment]
I had the same issues 4-5 times, but now it seems disappeared to me too.

**Comment by bkaes** [comment]
@GiacomoSorbi *"disappeared to me too"* is kind of vague in this case, since it doesn't state whether the problem or the honor graph disappeared ;).

**Comment by GiacomoSorbi** [comment]
My bad: I meant that I had the same exact issue RV mentioned. And now it seems the issue (not the graph) is gone, I didn't see it happening again.
