### ISSUE TITLE
Light Mode: dark backgrounds in the user profile page

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2500]
Related to: #2081

In light mode,

*  the "badge" on the user profile is still showing a dark background:
![image](https://user-images.githubusercontent.com/32236948/136650363-af38b9b2-0fe3-4227-86bc-36e2b651e8e9.png)

* the honor breakdown too (not sure this one is an actual problem, but that still fills a bit weird when looking at the whole page):
![image](https://user-images.githubusercontent.com/32236948/136650436-c816b0a7-3f6c-488b-9a4e-dc5ce1268b34.png)

**Comment by kazk** [comment]
Yeah, the badge is an image. Will need to add an option to generate a light version, then include both in the HTML, then load one based on the theme.

For the honor breakdown, any suggestions for better colors? You can play with it and post screenshots here.

**Comment by Blind4Basics** [comment]
![image](https://user-images.githubusercontent.com/32236948/136684033-bd0744a1-ed50-4f94-916c-06e551174286.png)
(_"meh", about the red text on dark bars_)

"the simpler the better" (?) reusing the colors of the page:
![image](https://user-images.githubusercontent.com/32236948/136684105-68bcbaff-21ba-4a05-ac2e-a6969ffd241d.png)

Tho, I'd like better a lighter red for better readability, but that will "break" the unity of the colors theme. Like:
![image](https://user-images.githubusercontent.com/32236948/136684174-701af779-0b4d-4ae2-9e4e-4b7522f907a8.png)

**Comment by kazk** [comment]
Deployed the fix
