### ISSUE TITLE
Light/dark modes: the language box in a kata page is missing visible borders

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2501]
By default, the borders of the language box is barely visible (edit: well, it's the same in dark mode, so... "anyway"?):

![image](https://user-images.githubusercontent.com/32236948/136651541-9b81e8c2-5670-4bc0-b20e-22dd8c88f067.png)

When clicking on it, the languages background is of the same color than the borders and the... "menu bar just below":

![image](https://user-images.githubusercontent.com/32236948/136651586-fd7f58d6-a212-41af-b678-0f96fee9cd80.png)

Expected:
* either a different color for the border+background of the box and its options
* or a darker border so that it's always visiually delimited

**Comment by FArekkusu** [comment]
> ok, It's actually the very same behaviour in dark mode

Except in dark mode the button and the background thing actually have different colors (the `R` channel's value is 10 units higher for the button (idk how to correctly explain this)) but in light mode the colors are the same.

**Comment by kazk** [comment]
Deployed the fix
