### ISSUE TITLE
About the kyu/dan rank badges (shape glitches and color schemes)

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#2507]
(see #2506 too)

### shape glitches, depending on the zoom level

from time to time, some extra vertical bars are showing up (first screenshot taken at 270%, the others at 240%):

![image](https://user-images.githubusercontent.com/32236948/137580609-3d44b275-1f02-40d1-bb79-71ee572a9b6a.png)
![image](https://user-images.githubusercontent.com/32236948/137580634-c78e413b-68f6-4b88-91c3-e6dccae147a7.png)
![image](https://user-images.githubusercontent.com/32236948/137580656-c6bb5cec-cee4-4319-a722-dfa926a2a1ba.png)

### dan badges

The dan badges are the onlyones whose the color scheme is different for the hex thing and the text. Moreover, those two colors ~~are swapped~~ (edit: nope, they aren't, just my eyes coping differently with the bkg color) ~~when changing the light/dark mode, as shown above~~ (in light mode, I find the text of the badge a bit too "bright" to be easy to read at the default zoom level)

**Comment by kazk** [comment]
Light theme can use the same color (`#333`) for text:

![image](https://user-images.githubusercontent.com/639336/137581131-bac1f31b-dcfd-44ee-8265-7610a93919a1.png)

**Comment by Blind4Basics** [comment]
Q: is that wanted that fromerly "white" kata badges have become "grayish" in profile badges?

![image](https://user-images.githubusercontent.com/32236948/137599278-ede09b94-e189-40e3-8478-6681ba1343cf.png)

**Comment by kazk** [comment]
Fixed

**Comment by Blind4Basics** [comment]
and is that one wanted too, in light mode?

![image](https://user-images.githubusercontent.com/32236948/137930499-a1cb3198-18bf-4b09-9bde-cb60eca04da1.png)

**Comment by kazk** [comment]
I think rank colors in light theme needs some adjustments, but I wouldn't say "not very different".

![image](https://user-images.githubusercontent.com/639336/137969478-7bb87286-785a-4d1e-bdac-1f0055cf7747.png)

The outline is `#555555` vs `#e6e6e6`.

Uh, I changed the text color to `#333333` (https://github.com/codewars/codewars.com/issues/2507#issuecomment-944882886) for light theme, but the outline is still `#555555`. I can make that `#333333` in light theme.

![image](https://user-images.githubusercontent.com/639336/137972213-1077144b-aba5-4288-b75f-396a0796d08b.png)

Better?
