### ISSUE TITLE
Error when trying to link GitHub account

### ISSUE THREAD

**Issue by dinahjohnson** [Codewars/codewars.com#2510]
Internal server error when I created a new account and tried to link my GitHub account. I've also tried logging in via GitHub but I get an error when I try that way so I made a new account hoping and tried to link to GitHub.

**Comment by cybergirldinah** [comment]
Still not working. I tried entering the email account for the user cybergirldinah but it’s saying “not found”. And it’s giving this error when I try to log in via the GitHub profile linked to the account:

**Comment by kazk** [comment]
Are you sure you're using the same email address? What's your email? If you'd like to keep that private, email us at info@codewars.com.

**Comment by kazk** [comment]
Also, I can't see the error you mentioned.

**Comment by cybergirldinah** [comment]
Thank you for all of your help. I just sent my email info to the provided address.

**Comment by kazk** [comment]
Yeah, you're using a wrong email address.

**Comment by cybergirldinah** [comment]
Thank you so much! I must have saved the wrong email in my password manager for my acct.
