### ISSUE TITLE
Password reset is broken

### ISSUE THREAD

**Issue by AidKool** [codewars/codewars.com#2514]
**Describe the bug**
It is currently not possible to reset a password as the domain used for that task is currently parked.

**To Reproduce**
If you try to reset your password on https://www.codewars.com/users/password/new you'll get an email to reset your password, but the domain spt.codewars.com is not currently accessible, which makes it impossible to reset a password. 

**Screenshots**
![Screenshot from 2021-10-31 22-18-59](https://user-images.githubusercontent.com/73796715/139603051-6fc25f31-79e2-44de-9c07-dbf5e3c4116e.png)

EDIT: This can be closed. I have already figured out the problem.

**Comment by kazk** [comment]
Thanks for reporting. This was caused by some misconfiguration, and the fix was deployed.
