### ISSUE TITLE
i get the massage "is already taken" on codewars[short description of the bug]

### ISSUE THREAD

**Issue by arielbinder** [codewars/codewars.com#2515]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by arielbinder** [comment]
I want to log in my account to codewars,  but I can't beacause when I enter my email I recieve ''it was taken'' massage

**Comment by arielbinder** [comment]
![image](https://user-images.githubusercontent.com/93533173/139693843-f9f3d6f3-cca8-46de-a15a-24c589028b7b.png)

**Comment by Blind4Basics** [comment]
looks like you registered through github => don't try to login with your mail, but with github.
working?

**Comment by kazk** [comment]
That's a sign up form.
Sounds like #2509. Have you tried using Private/Incognito without any extension enabled?
