### ISSUE TITLE
Unable to login with my old github account

### ISSUE THREAD

**Issue by Rajashekar5576** [codewars/codewars.com#2517]
Unable to login with my old github account

**Comment by DonaldKellett** [comment]
You'll have to provide more information than that ;-) Some things you could include:

- Username of your old GitHub account
- When did you last log in to Codewars?
- Did you **register** (_not_ log in!) for an account on Codewars with your old GitHub account?
- Operating System name and version (e.g. Windows 10 / macOS Big Sur / Ubuntu 20.04)
- Browser name and version (e.g. Firefox 93.0)
