### ISSUE TITLE
/users/:user/completed_solutions?page=x returns 500 Internal Server Error when scrolled

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#252]
I open the list of my solutions at http://www.codewars.com/users/Unnamed/completed_solutions and scroll down. At some point solutions stop loading. I've looked at HTTP requests: http://www.codewars.com/users/Unnamed/completed_solutions?page=13 returns "500 Internal Server Error". Some time ago (when I had fewer solutions) I tried the same thing and the error was occuring at ...?page=8. It looks like it breaks on some specific solution.

**Comment by rollietikes** [comment]
I am having the exact same issue. 

http://www.codewars.com/users/rollietikes/completed_solutions

I've tried pulling my solutions for the last 24hrs and the page always returns the error.

**Comment by MarkPearlMYOB** [comment]
I'm getting a 500: Internal Server Error for a specific Kata, but not for any others...

http://www.codewars.com/kata/how-much-water-do-i-need/train/javascript

If anyone knows how I can resolve this let me know.

**Comment by kazk** [comment]
This should be fixed. See #1627 and #1013.
