### ISSUE TITLE
More options for default sorting

### ISSUE THREAD

**Issue by Kacarott** [codewars/codewars.com#2520]
**Is your feature request related to a problem? Please describe.**
I find it mildly annoying that I must change the 'Progress' filter of the Kata page every time I visit, to exclude katas I have already solved.

**Describe the solution you'd like**
I would like the 'Default Catalog List View' option under Account settings, to include additional radio buttons associated with the 'Progress' filter of the Kata page. (Potentially also something similar for 'Language' and 'Sort By', though I don't often change those).

**Describe alternatives you've considered**
Alternatively, a solution might be for CodeWars to remember my most recent filter settings, and preset them the next time I visit the Kata page.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1e45) by [Unito](https://www.unito.io)

**Comment by hobovsky** [comment]
Since all search parameters are passed by URL query string, one possibility is to store URL to a configured search as a bookmark in your browser.

**Comment by Kacarott** [comment]
Yes I did actually consider that. I probably would have just done that, but I also saw the 'Default Catalog List View' option which gave me hope that additional settings might be easy to implement. Using bookmarks is of course doable, but less pleasant (especially since I have a few different PCs which I access CodeWars on)

**Comment by Kacarott** [comment]
Since raising this, I had an idea for a far better implementation (and probably easier), which would make this idea redundant.
See [this post](https://github.com/codewars/codewars.com/discussions/2805)
