### ISSUE TITLE
Imperfect Ctrl D editor behaviour

### ISSUE THREAD

**Issue by legitnick** [codewars/codewars.com#2522]
**Is your feature request related to a problem? Please describe.**
There is a hotkey for word selection (Ctrl D), and it selects not only separate words but also parts of the words, which makes this hotkey not as useful as it could be.

**Describe the solution you'd like**
Make so that Ctrl D selects only separate words.

**Describe alternatives you've considered**
-

**Additional context**
There is such a feature in VS Code, and I do not think it is as hard to implement as autocompletion, for example.

**Comment by kazk** [comment]
Try it on https://codemirror.net/demo/sublime.html and see if it behaves differently. If it does, then it's our bug. Otherwise, it's out of scope of Codewars. You should open an issue on https://github.com/codemirror/codemirror instead.

**Comment by legitnick** [comment]
It turns out it really is a problem with Codemirrors Sublime Text bindings, thanks for the reply.
