### ISSUE TITLE
progress get's sent back

### ISSUE THREAD

**Issue by koko1237** [codewars/codewars.com#2529]
meaning my rank me finishing any kata's makes my rank go back down any kata in my main account I have solved 153 kata's and left for a month without doing ANY KATA'S I came back found my rank 8kyu not 1kyu

**Comment by Blind4Basics** [comment]
you're a copycat, don't get surprized your account has been restricted.

**Comment by koko1237** [comment]
I am nottt mr stupid

**Comment by Blind4Basics** [comment]
you are

**Comment by koko1237** [comment]
I am not I even took my answers made an new acount and the same thing
happend

**Comment by koko1237** [comment]
To my new account

**Comment by Blind4Basics** [comment]
Look, you misbehavied, you got caught, just get over it. You're losing your time, here.

Cheers

**Comment by koko1237** [comment]
Well I made another acount and the same thing happened again

**Comment by Blind4Basics** [comment]
of course, since you acted in a dishonorable way there again.
