### ISSUE TITLE
The website is 404

### ISSUE THREAD

**Issue by nt4f04uNd** [codewars/codewars.com#2533]
**Describe the bug**
Website returns 404

**To Reproduce**
Navigate to https://codewars.com

**Expected behavior**
Website works

**Screenshots**
![image](https://user-images.githubusercontent.com/39104740/142039758-4f333e68-6ac1-4f20-a1e5-e7a7215b4bfd.png)

**Browser**

- OS: Windows
- Browser chrome
- Version 96.0.4664.45

**Additional context**
No

**Comment by nt4f04uNd** [comment]
Just after I submitted it, it started working

**Comment by kazk** [comment]
Yeah, we were affected by this https://status.cloud.google.com/incidents/6PM5mNd43NbMqjCZ5REh
