### ISSUE TITLE
Incident affecting Search and Kata Editor

### ISSUE THREAD

**Issue by kazk** [codewars/codewars.com#2534]
Updates will be posted on https://status.codewars.com/

**Comment by Enakumaru** [comment]
kata search is not working

**Comment by Kacarott** [comment]
I can also not access the kata editor. Presumably due to it also relying on the search functionality, but I thought I'd mention it regardless.

**Comment by g964** [comment]
Same cause?
<https://www.codewars.com/kata/new> -> "Internal Server Error"

**Comment by zhibirc** [comment]
https://www.codewars.com/collections -> "500 Internal Server Error"

**Comment by Schulzkafer** [comment]
same

**Comment by Semantron** [comment]
Same on my side as well. No katas. Same errors.

**Comment by artpsh** [comment]
Same, There are no items to display

**Comment by kazk** [comment]
No updates from them yet. We're having lots of provider issues this week.
I'll try fixing Kata Editor and Collections Search to fail more gracefully.

**Comment by kazk** [comment]
Collections Search shouldn't crash anymore and show no results like Kata Search.

Kata Editor should work now. It only uses Elasticsearch to find kata with similar name, and it now fails gracefully.

**Comment by hugoderre** [comment]
It's always broken on my side, no Kata displayed in the search page.

**Comment by kazk** [comment]
Please read https://status.codewars.com/

**Comment by hugoderre** [comment]
Indeed there is no more 500 error, my bad

**Comment by kazk** [comment]
Deployed a basic fallback search for Kata for when Elasticsearch is not available, so the search page is usable. Please note that some features are limited or missing.

Working on a similar fallback for Collections search.

**Comment by kazk** [comment]
Closing because it should be usable now.

**Comment by Voileexperiments** [comment]
@kazk How is this "resolved" if "some features are limited or missing"? "Resolved" would mean "functionality has reverted to normal", not "usable with the limited fallback". It's still a workaround, and it's still missing features (e.g I can't search by kata author name).

**Comment by kazk** [comment]
Fair enough. There are some minor features missing, but most users will not notice it. The "incident" is worked around. I'll reopen this for now, and might open a separate issue later.

I just don't have any idea when they'll update us, and mostly wanted to indicated that the site is usable.

**Comment by kazk** [comment]
Reposting from Discord for those curious what's going on:

> We use hosted Elasticsearch instances (maintaining databases is a full time job). ES was upgraded from v5.6 to v6.8 about a year ago, and it was working fine since then. Two days ago, the clients (Codewars servers) started failing to connect to the ES server because its certificate got expired, which shouldn't happen because it's renewed by them automatically. So, I logged into their service to see what's going on, and found that there's a warning on our deployment: "Version Inconsistent". Apparently, when ES was upgraded a year ago, it failed to upgrade Kibana (a component for exploring and visualizing ES), and Kibana is still stuck at v5.6.
>
> So, our deployment had Elasticsearch v6.8 and Kibana v5.6 for about a year now without noticeable issues, but I guess configuration changes cannot be applied because of this inconsistency, and it's been stuck in a deadlock. The instances cannot be restarted because of this. The upgrade process cannot be reapplied because it requires v5.6 and sees v6.8. The downgrade process fails too because it requires v6.8 and sees v5.6.
>
> The dashboard suggested to contact support, so I opened a case. The support team looked into the issue after a few hours, but they had to escalate to the development team. We've been waiting since then, and looks like they started trying something this morning based on the activity log, but no updates yet. I guess we fell in some edge case.
>
> Anyway, I think Elasticsearch for Codewars is an overkill, so I'm researching to migrate off to something more simple.

**Comment by textninja** [comment]
> Anyway, I think Elasticsearch for Codewars is an overkill, so I'm researching to migrate off to something more simple.

While it's unfortunate that you're experiencing deployment issues, and I can relate to your frustration, I don't think migrating away from Elasticsearch is the answer, and I would caution against it. Elasticsearch is a great fit for the Codewars kata list, and I'm betting "simpler" options (Database queries? Rolling your own full text search?) will do more damage to site stability in the long run. That being said, if you do find a simpler way to provide faceted full text search, please consider sharing what you find!

**Comment by kazk** [comment]
This was frustrating (especially not getting updated on progress), but I'm not migrating off just because I was frustrated. This was a good opportunity to rethink what we actually need. Search is one of the areas I haven't really touched since inheriting the project, and it needed some work anyway.

We weren't doing anything advanced with Elasticsearch, and we don't have that many items to search from, so there are options. I can always reconsider Elasticsearch if it turns out to be the best option.

> if you do find a simpler way to provide faceted full text search, please consider sharing what you find!

I'm considering https://github.com/meilisearch/MeiliSearch. There are open issues related to large datasets (millions), but we won't ever have that many.

**Comment by kazk** [comment]
Searching by author's username is supported with `author:`. For example, `author:jhoffner` will only show kata by Jake. You can also negate to hide kata by the author, e.g., `-author:jhoffner`. Usernames with spaces needs to be quoted. I believe this is better than implicitly searching the author's username. We'll update the docs to mention this.

Searching the beta status is now possible with the new `Beta State` filter #999.

The list of tags is now back as well.
