### ISSUE TITLE
Internal Server Error causing no new katas to be available

### ISSUE THREAD

**Issue by AlKot16** [codewars/codewars.com#2539]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
See #2534
