### ISSUE TITLE
Can't delete account

### ISSUE THREAD

**Issue by mithatcanozdemir** [Codewars/codewars.com#254]
I have been trying to delete my account for a while now , for some reason I can't.

**Comment by opensamba** [comment]
I think this is important and should be provided as a normal user may ask to delete all his personal info

**Comment by jrieko** [comment]
The delete account button at the bottom of the account settings page doesn't work?

**Comment by kazk** [comment]
If "DELETE MY ACCOUNT" button at the bottom of your [Account Settings](https://www.codewars.com/users/edit) is not working, let me know and I'll reopen this issue.
![image](https://cloud.githubusercontent.com/assets/639336/26651297/17e02800-4601-11e7-8f17-f32e949c3291.png)

**Comment by Yash2108** [comment]
> If "DELETE MY ACCOUNT" button at the bottom of your [Account Settings](https://www.codewars.com/users/edit) is not working, let me know and I'll reopen this issue.
> ![image](https://cloud.githubusercontent.com/assets/639336/26651297/17e02800-4601-11e7-8f17-f32e949c3291.png)

I have tried to delete my account. But the button is not working. It asks for a confirmation but even after pressing the yes button there is no visible change .

**Comment by kazk** [comment]
@Yash2108 Codewars is currently having degraded performance issue and deleting a user is one of the most time consuming transaction. It's most likely timing out.
