### ISSUE TITLE
My  kata keeps showing "There are no items to display"

### ISSUE THREAD

**Issue by huangaosong** [codewars/codewars.com#2540]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
See #2534
