### ISSUE TITLE
Consecutive strings has two wrong test cases

### ISSUE THREAD

**Issue by Aldekenzo** [codewars/codewars.com#2542]
Time: 3848msPassed: 207Failed: 2Exit Code: 1
Test Results:
Basic tests
longestConsec(['zone', 'abigail', 'theta', 'form', 'libe', 'zas'], 2)
Expected: 'abigailtheta'
  Actual: 'thetaabigail'
   Which: is different.
          Expected: abigailthe ...
            Actual: thetaabiga ...
                    ^
           Differ at offset 0
Completed in 59ms
longestConsec(['ejjjjmmtthh', 'zxxuueeg', 'aanlljrrrxx', 'dqqqaaabbb', 'oocccffuucccjjjkkkjyyyeehh'], 1)
longestConsec([], 3)
longestConsec(['itvayloxrp', 'wkppqsztdkmvcuwvereiupccauycnjutlv', 'vweqilsfytihvrzlaodfixoyxvyuyvgpck'], 2)
longestConsec(['wlwsasphmxx', 'owiaxujylentrklctozmymu', 'wpgozvxxiu'], 2)
longestConsec(['zone', 'abigail', 'theta', 'form', 'libe', 'zas'], -2)
longestConsec(['it', 'wkppv', 'ixoyx', '3452', 'zzzzzzzzzzzz'], 3)
Expected: 'ixoyx3452zzzzzzzzzzzz'
  Actual: 'wkppvixoyxzzzzzzzzzzzz'
   Which: is different.
          Expected: ixoyx3452z ...
            Actual: wkppvixoyx ...
                    ^
           Differ at offset 0
Completed in 4ms
longestConsec(['it', 'wkppv', 'ixoyx', '3452', 'zzzzzzzzzzzz'], 15)
longestConsec(['it', 'wkppv', 'ixoyx', '3452', 'zzzzzzzzzzzz'], 0)
Completed in 73ms
Random tests

**Comment by hobovsky** [comment]
Problems with kata and kata tests should be reported in kata discourse. Please post your questions in kata discussion section.

Additionally, please read this paragraph of FAQ and see if you can find anything helpful there: https://docs.codewars.com/training/troubleshooting#kata-bug
