### ISSUE TITLE
Unable to Sign Up for a New Account

### ISSUE THREAD

**Issue by tier42-tott** [codewars/codewars.com#2546]
**Describe the bug**
When trying to sign up for a new account, I am asked to complete a simple fix to a multiply function. When solved correctly, it asks the exact same multiply question again. When that is solved correctly, it asks again, only this time the UI is glitched, and the submit button is covered by a copy of the code.

**To Reproduce**
Simply attempt to sign up for a new account in either Javascript or Python, as those were the only two I tested.

**Expected behavior**
I expected to be able to sign up for an account after answering the questions correctly.

**Screenshots**
![buggy_codewars](https://user-images.githubusercontent.com/95375282/144480398-c627273c-72f2-4a91-b577-b2cfd35e4b2a.png)

**Browser**
Used Chrome and Firefox, and had someone else try in a different location try in a Chrome incognito window.

- OS: Windows
- Browser: Chrome, Firefox
- Version: Chrome 96.0.4664.45, Firefox 94.0.2

**Comment by Faeq-F** [comment]
I have the same issue

**Comment by cmoneverybody** [comment]
I confirm this bug.
I also can't log in after completing the test task.
Next i in incognito Chrome i go to the "sign up" page via a direct link, but i can't authorize in via github.
![image](https://user-images.githubusercontent.com/7736571/144483668-4cacf3c5-f4bc-4278-8977-3cde759d07bc.png)
![image](https://user-images.githubusercontent.com/7736571/144483801-c6f041e7-5053-40f9-b896-b34d4c148e60.png)
![image](https://user-images.githubusercontent.com/7736571/144483855-2040ec5d-6d13-4820-9c71-08414ce62355.png)

**Comment by pm0nt3iro** [comment]
Same!

**Comment by Faeq-F** [comment]
![image](https://user-images.githubusercontent.com/61658458/144487034-5527c910-cf66-499a-9fe3-673551de1f01.png)

**Comment by Faeq-F** [comment]
Seems to be solved now

**Comment by kazk** [comment]
Should be working now
