### ISSUE TITLE
The code on the kumite diff tab overflows the surrounding HTML elements

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2547]
As you can see in the image below, the lines of code are not limited by the `div` element which they belong to, making them overflow. For some reason the scrollbar is also located at the bottom of the page instead of being a part of the correct `div` - I think it was correct at some point in the past but I'm not entirely sure.

![image](https://user-images.githubusercontent.com/31668662/144624558-5b363136-f665-4ccd-aa02-63b3642237c4.png)

**Comment by kazk** [comment]
Fixed
