### ISSUE TITLE
Contributors who add no code still get listed

### ISSUE THREAD

**Issue by Shinchy** [Codewars/codewars.com#255]
I've noticed that some users and contributing to Katas by adding a space or something similar. They then get listed as a partial author of the said Kata. They're essentially cheating the system to up themselves in the ranks.

There should be a way for the author to flag this as an unnecessary addition or something similar.

**Comment by crazymerlyn** [comment]
Contributing to a kata doesn't give you any honor.
In fact, once you edit a kata, you will no longer gain any points by solving that kata.

I think there are plans to give honor for valuable edits, but to the best of my knowledge, nothing of the sort exists yet.

I am actually surprised people are even doing this in the first place.

**Comment by jhoffner** [comment]
If earning honor for a particular kata is important to you then you have to complete it first before editing it. Once you edit a kata, you have been shown the solutions in all of the languages, so it would be a way to cheat if we did not lock you out of earning additional honor. 

As for meaningful edits. Kata translations are the only way for us to track those. Anything else you are just being a good samaritan.
