### ISSUE TITLE
Lost 1000 honor, downgraded from 1 dan to 1 kyu

### ISSUE THREAD

**Issue by VietAnh1010** [codewars/codewars.com#2550]
**Describe the bug**
I have completed 693 katas and was rewarded more than 12400 honors. For some reason, my account lost about 1000 honors.

**Screenshots**
![Downgraded](https://user-images.githubusercontent.com/91171052/145993687-67923782-c410-4496-9380-a2f592e8314d.png)

**Additional context**
Account name: `vietanh101003`
Checking the [site events](https://www.codewars.com/users/vietanh101003/site-events), the number of completed katas is 687, while on the [profile page](https://www.codewars.com/users/vietanh101003/stats) it was 693.

**Comment by hobovsky** [comment]
Did you spot, more or less, the point in time when the drop occurred? Was this some time recently, or you just logged in after some inactivity and noticed points are different than the last time?

**Comment by VietAnh1010** [comment]
The last time I completed a kata is on the last Saturday afternoon, and the next morning, the drop occurred.

**Comment by Blind4Basics** [comment]
@VietAnh1010 two cheats have been found in your older solution, you got a penalty for that.
