### ISSUE TITLE
Unexpected column widths in diffs

### ISSUE THREAD

**Issue by error256** [codewars/codewars.com#2552]
The columns of diff tables have unexpected widths in some cases at least on kata revision pages, not sure about translations.
![Diff table on a kata revision page](https://user-images.githubusercontent.com/5375100/146346980-98979059-c922-4e34-9d3f-895aad6e695f.png)
(https://www.codewars.com/kata/5b609ebc8f47bd595e000627/revisions)
It looks like it happens when the first row of a table with "table-layout: fixed" doesn't have widths set.

**Comment by kazk** [comment]
Thanks. Yeah, this seems to happen whenever `Expand` is the first row.
Controlling the behavior of table cells was much tricker than I thought.

**Comment by error256** [comment]
I'm not sure how it's done in the modern web, but I think it could be `colgroup` with `col`s and `width`s for `col:nth()` (or `max-width` if the `table-layout` doesn't have to be `fixed`).

**Comment by kazk** [comment]
I had to use `table-layout: fixed` to prevent the row from overflowing.

The change I made for #2547 should work well except for this edge case I forgot to consider...

I'll take a look after some sleep.

**Comment by FArekkusu** [comment]
The `<td>` elements containing the code belong to the `w-full` class which has a `width: 100%!important` property - disabling it seems to fix the problem. Idk what's causing the issue, but looking into this one might be a good start.

![image](https://user-images.githubusercontent.com/31668662/146362375-baf37965-1d99-45ec-83be-7b77e4e0aedd.png)

**Comment by kazk** [comment]
You disabled `w-full` from everywhere by unchecking the property. That resolved this issue by removing the width from the table, but that causes the row to overflow again.

Removing `w-full` class from `td` doesn't fix it.

**Comment by kazk** [comment]
I think I found a fix. I'll deploy it soon.

**Comment by kazk** [comment]
Deployed
