### ISSUE TITLE
Username did not change

### ISSUE THREAD

**Issue by sherryRobbins** [codewars/codewars.com#2557]
**Describe the bug**
I changed my username name but the solution for the kata "You're a square" still show my old username. I did delete my account but I returned. I still see my old username.

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.
https://www.codewars.com/kata/54c27a33fb7da0db0100040e/solutions/cpp/all/newest

**Expected behavior**
I would expect to not see my username as I did delete the account.

**Comment by kazk** [comment]
I'm assuming your deleted account not too long ago. The solutions page is showing the cached result, and the cache is invalidated when there's a new solution. This is usually quick enough, but I'll look into invalidating when a user is deleted.
