### ISSUE TITLE
My Account was restricted.

### ISSUE THREAD

**Issue by filosoficaguilar** [codewars/codewars.com#2559]
Hi.

Mi account with user [IvanHernandezA](https://www.codewars.com/users/IvanHernandezA) was restricted for second time, but i didnt cheat, i don't know if it is because i use third part tools to code and then just paste it into the kata.

Could you help me please?

**Comment by farhan443** [comment]
Is this "third party tool" something like an obfuscator?

**Comment by filosoficaguilar** [comment]
Noup are pgadmin for SQL katas and google colab for python katas and i've been practicing with one-line-code

**Comment by Blind4Basics** [comment]
using solutions you find on the internet is not the way you're supposed to solve kata.
