### ISSUE TITLE
The feedback button does nothing for me.

### ISSUE THREAD

**Issue by CoffeeCodeKevin** [Codewars/codewars.com#256]
I'm running fully updated firefox without adobe flash and tested my extensions off, which only block ads and social buttons. Clicking it repeatedly seems to only highlight the text "Feedback".

I suppose I should add while I'm here that I usually get this message 10-15 times each problem I do: "Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated."

**Comment by kazk** [comment]
Closing because I don't think we have the feedback button anymore.
