### ISSUE TITLE
By using the "exit()" statement you can actually solve a kata

### ISSUE THREAD

**Issue by Scrayil** [codewars/codewars.com#2561]
**Describe the bug**
I was trying to solve this: [kata](https://www.codewars.com/kata/551f23362ff852e2ab000037/train/python)
Since i was frequently getting timeout errors, i tried to print the huge pyramid that was being passed as parameter during tests in order to check it's size.
I was implementing a recursive function, so after printing it i used the "exit()" statement to exit the program.
After a few hours i noticed that the kata was marked as solved and that i got the points for it.
I don't know if this happens with others katas too, but it's worth checking it.

**To Reproduce**
The accepted solution can be found [here](https://www.codewars.com/users/Scrayil/completed_solutions)

**Expected behavior**
The interpreter should print the pyramid and exit without accepting the code as a valid solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/71236213/148588133-2a6b4410-a7f9-4d26-b689-e51fe2885fd7.png)

- OS: Arch Linux
- Browser: Firefox
- Version: 95.0.1 (64-bit)

**Comment by Blind4Basics** [comment]
Hi, 

This is a known thing, and be very careful with that: htis is considered a cheat and people using this (more than once) can get their account banned (htis warning is more directed to the reader than to you).
I doubt it will get fixed.

**Comment by Scrayil** [comment]
> Hi,
> 
> This is a known thing, and be very careful with that: this is considered a cheat and people using this (more than once) can get their account banned (this warning is more directed to the reader than to you). I doubt it will get fixed.

I didn't find any mention to this bug in the issues section, i thougth this was a new thing.
This problem could be fixed by checking if all the tests have been executed successfully or if the processes have halted too early. Maybe by running the code inside a subprocess and getting it's output.

**Comment by kazk** [comment]
It's been discussed multiple times here and other repos. We don't consider this a bug.
See https://github.com/codewars/codewars.com/issues/2179#issuecomment-644977083 for my response.
