### ISSUE TITLE
I lost 30261 honor in one day

### ISSUE THREAD

**Issue by g964** [codewars/codewars.com#2564]
On the 01/08/22 I had *390809* honor, on the 01/09/22 at the same hour I had *360548*. What happens?

**Comment by Blind4Basics** [comment]
https://github.com/codewars/codewars.com/issues/2563#issuecomment-1008203821 ?

**Comment by g964** [comment]
I don't remember having duplicate records.

> @kazk: The bug I had introduced this week adds a duplicate record when a migrated solution group is voted.

If this bug wrongly introduced duplicate records my honor would have had a big increase in previous days but there was none; the increase was as usual.

**Comment by kazk** [comment]
> If this bug wrongly introduced duplicate records my honor would have had a big increase in previous days but there was none; the increase was as usual.

The site events having duplicate records is not a new bug.

Looks like your site-events had some duplicated records for the authored kata upvotes. Those records are removed and readded for each authored kata when rebuilding the site events, so that was fixed as a side effect.

**Comment by g964** [comment]
> Looks like your site-events had some duplicated records for the authored kata upvotes.

Since I lost so many honor it seems one could say "your site-events had *lots and lots* of duplicated records"... Furthermore honor for completed kata has decreased too. Same reason? 
Sorry to say that but are Codewars updates more to worry about than Windows updates?-)
Nevertheless thanks for your answer.

**Comment by anter69** [comment]
Just to confirm the issue: I remember going over 50k honor end of last year - now down to 47k. I don't care that much about it, but it was a bit of a "surprise"...

**Comment by kazk** [comment]
@g964 

> Since I lost so many honor it seems one could say "your site-events had lots and lots of duplicated records"... 

No, you have a few records that's worth a lot, like `16500` and `15080` honor points each. And the number of votes is basically the minimum number of updates to the record, so those had more chance of being affected by the bug. Having a few duplicates just affect you a lot.

> Furthermore honor for completed kata has decreased too. Same reason?

Yes, those were recalculated from scratch as well.

> Sorry to say that but are Codewars updates more to worry about than Windows updates?-)

Why did you need to say this? I understand it was surprising, and it's frustrating not being able to trust the number, but it's not like I'm actively trying to. I also don't think the fix broke anything for you.

@anter69

Yeah, there are multiple issues filed related to site events having duplicate records, and #1715 is one of them. I should try deduplicating them.
