### ISSUE TITLE
Sorting by "Low satisfaction" does not sort results properly

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2566]
Functionality of sorting search result by satisfaction rating (introduced somewhat recently) does not seem to sort returned kata correctly.

![image](https://user-images.githubusercontent.com/23709795/149178685-31115993-57e8-48f2-81a6-681369db2d72.png)

It seems to _roughly_ work for beta kata: when filtering for beta, the first page is filled with kata of a low quality, but still not strictly ordered. I think I remember the sorting working correctly when it was introduced, so maybe it stopped working after getting rid of Elastic Search?

**Comment by kazk** [comment]
Yeah, I was using a different field to sort. Deployed the fix.
