### ISSUE TITLE
Poor UX of "Restore password" form

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2567]
The form which appears when restoring a password to a non-existent email looks bad:

![image](https://user-images.githubusercontent.com/23709795/149319029-9e2ed8ad-0d68-4790-bcee-7f674500ad4f.png)

- The text box is not readable in dark mode
- The "not found" message could be improved

**To Reproduce**
- Go to login page
- Click "forgot password"
- Enter some totally invalid email into the text box and click "Send me instructions"

**Browser**
Opera, Win10

**Comment by kazk** [comment]
Fixed
