### ISSUE TITLE
Unable to post comments/issues on kata discussion pages

### ISSUE THREAD

**Issue by san00** [Codewars/codewars.com#257]
Hi,
I've been unable to post any comments/ issues/questions on kata discussion pages. This is a continuous and ongoing problem, I've had since joining. Please try to resolve

**Comment by jhoffner** [comment]
Thanks for reporting @san00. However without any details on what type of issues you are having I am not able to do much about it. What exactly is happening? Are you sometimes able to post a comment or never? If you open your inspector does the console give you an error? Is it new comments or just replies that are giving your problems? Which browser?

**Comment by san00** [comment]
Hi @jhoffner, Thanks for replying.
Okay, the issue I have is that I can compose a message but nothing happens when I click post. It's as if if hasn't registered that I'm pressing the button. This has happened continuously. I get no error messages or anything else. I can see the red bar at the top move as if something will happen but it never does.

I managed to post 1 comment a little few weeks ago but I'm not sure why it worked that time and not before or since as I was using the same browser and computer. (Firefox and mac).
I hope this helps.

Thanks San

**Comment by san00** [comment]
Also not sure if this is the right place to post these issues but I'm having problems with a few approved kata at levels 7 and 8.
I create solutions that pass all the test cases but find that I cannot submit my solution/s as I get messages saying the code has failed when the code is right? (example kata  You're a square!, Ghostbusters (whitespace removal) and Drink about( this one passes the test case fine but I can't submit it as I get 1 test passed, 1 test failed message).

**Comment by jhoffner** [comment]
Thanks @san00. Not able to repro yet but I'll try to dig deeper. 

For the kata tests that you are having problems with. The test cases provided with the kata are usually there to get you started and so that you can see the basic idea of how things are getting tested. Usually not all of the test cases that are ran when you submit are provided. So you are likely failing additional test cases that are not shown.

A reason for not showing all of the test cases is that seeing them all at once can sometimes cause a lot of confusion. The ones shown are there to keep understanding the requirements simple. Also many kata authors like to prevent coders from cheating the solution by creating random test cases, so that hardcoded values cannot be used to pass the tests but not actually solve the problem.

**Comment by PropeReferio** [comment]
I can't post any questions or comments either. Bummer.

**Comment by hobovsky** [comment]
#1814  #1858 and a few more

**Comment by benjaminkaufmann90** [comment]
same for me. Didn't work since sign up for me for any of the katas (no matter the category 'questions', 'issues' etc.).
I signed up 2019-11-24

**Comment by HansGerber** [comment]
same for me. Didn't work since sign up for me for any of the katas (no matter the category 'questions', 'issues' etc.).
I signed up 2019-11-24
Username: HansGerber7

**Comment by kazk** [comment]
Make sure you have your account confirmed. See https://github.com/Codewars/codewars.com/issues/1930#issuecomment-528154637

**Comment by HansGerber** [comment]
> Make sure you have your account confirmed. See [#1930 (comment)](https://github.com/Codewars/codewars.com/issues/1930#issuecomment-528154637)

Thank you that fixed it. Strangely I couldn't find an email regarding verification in my mailbox. After using the resend button I got it.

**Comment by jordankittle** [comment]
I have confirmed my account and still can't post comments.

**Comment by kazk** [comment]
@jordankittle Then it's caused by something else. Please open a new issue using the template.

**Comment by luluUK** [comment]
Hello.... Hope somebody can help me resolve my issue. I can't comment or ask questions on any Katas solutions. My account has been verified and there are no errors showing in my browser. I've checked on firefox, chrome and safari ... it's not working on any of them.

**Comment by IceGlance** [comment]
The problem occurs and is very annoying.

POST request 
{"markdown":"To avoid redundant Counter(word) calculation","masked":false,"label":null,"parent_comment_id":"60f5c9227fda34004958b24e"}

Response 
{"success":false,"message":"Internal Server Error","status":500}

**Comment by sabyasachi** [comment]
Any update here? I have the same problem as @HeferH24. Posted a couple of comments yesterday; today nothing happens when if I try:
- Posting comments on solutions
- Press "Clever" or "Best Practice Buttons."

**Comment by kazk** [comment]
Most likely #2263. Explained in https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658 . I'm working on it this quarter.

**Comment by cylmad** [comment]
+1 same here, unable to comment or press Clever/Best Practice buttons.

**Comment by kazk** [comment]
See https://github.com/codewars/codewars.com/issues/2263#issuecomment-1007176572

**Comment by cylmad** [comment]
I had a look on this case #2263, hoping to find a solution, but not clear to me if it's still open/on going issue (?) cause I can see all requests at a "closed" state...

**Comment by kazk** [comment]
What do you mean by a solution? It's still not working?

**Comment by cylmad** [comment]
Yes it is, sorry I didn't check before leaving the last comment.
Thx for your help.
