### ISSUE TITLE
Katex isn't working in conditional rendering blocks

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2571]
For kata descriptions, Katex syntax doesn't work currently when used inside conditionnal rendering blocks:

![image](https://user-images.githubusercontent.com/32236948/149652300-d2c356ac-3642-4d98-b318-eda081c1887f.png)

currently renders as:

![image](https://user-images.githubusercontent.com/32236948/149652315-40810ee6-a9a8-44ea-9dba-a417630acb08.png)

Note: is that possible to have the katex equations rendered with a smaller font too?

**Comment by hobovsky** [comment]
> Note: is that possible to have the katex equations rendered with a smaller font too?

Check the options in "Size" section in KaTeX docs: https://katex.org/docs/supported.html

**Comment by kazk** [comment]
Should be fixed.

**Comment by Blind4Basics** [comment]
[confirmed](https://www.codewars.com/kata/61e2edfeaf28c2001b57af98)

:+1:
