### ISSUE TITLE
Cannot delete a kata which was switched from published to draft

### ISSUE THREAD

**Issue by Alked** [codewars/codewars.com#2573]
**Describe the bug**
When I tried to delete [this kata](https://www.codewars.com/kata/61e8f33707b3ee002c0e1d30/), the page shows me
```
User does not have permission to perform this action
```

**To Reproduce**
Go to the edit page, click on delete, and click on the confirm button

**Screenshots**
![image](https://user-images.githubusercontent.com/37265172/150506970-a86eaa6b-5334-4c16-8aee-0b99ac7814d0.png)

**Browser**
- OS: Windows 10
- Browser: Chrome 96.0.4664.110

**Comment by kazk** [comment]
You cannot delete a kata after other users have submitted solutions.
