### ISSUE TITLE
When you are begining the initial test in javascript, not fit well the css blocks

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2579]
### Discussed in https://github.com/codewars/codewars.com/discussions/2578

<div type='discussions-op-text'>

<sup>Originally posted by **Dann-Herz** January 25, 2022</sup>
I'm talking about this part 
![Selection_023](https://user-images.githubusercontent.com/69129863/150961250-e1960284-f292-490d-ba4b-aef386b3a605.png)
and it won't let you submit the answer, but if I change the margin of the element below, works well with 
`margin-top: 80px; //  for example`
![Selection_022](https://user-images.githubusercontent.com/69129863/150961591-def0dfc7-23d4-4ad5-a47f-a06a834a145b.png)
It's just a recommendation, I don't know if this is part of the initial test
</div>

**Comment by kazk** [comment]
@Blind4Basics Can you reproduce this? I can't, tried Firefox and Chromium.

**Comment by Blind4Basics** [comment]
thing is, I don't see the sample tests window, in the home page, when selecting a language... (because I _guess_ it's in the home page of codewars.com ??)

I actually didn't understand at all what the OP said and since he provided almost no concrete context.... :/

**Comment by kazk** [comment]
What do you see when you open https://www.codewars.com/?language=javascript logged out?

**Comment by Blind4Basics** [comment]
this:

![image](https://user-images.githubusercontent.com/32236948/151045881-902205e3-2135-4937-9603-5cf70c866e97.png)

**Comment by kazk** [comment]
Yeah, that's what I see. Working as expected.

**Comment by kazk** [comment]
@Dann-Herz We cannot reproduce the issue. Can you provide your browser info? Also, do you have any extensions enabled?

**Comment by Blind4Basics** [comment]
how di he get to see the sample tests? He hacked the css/page? (they are there, but hidden?)

**Comment by kazk** [comment]
What do you mean by sample tests? I don't see it in the screenshot.

I think the solution editor is duplicated for some reason.

**Comment by Blind4Basics** [comment]
oh right... (looks like and don't do/see anything right, today... x/ )
