### ISSUE TITLE
Kata "How far will I go?"in Java;  can't submit

### ISSUE THREAD

**Issue by ertogrul** [Codewars/codewars.com#258]
Hello, 
I am passing tests prepared in this Kata, but I encounter an error when I try to submit.
Message:
Nope! Try again.
Unknown error.

**Comment by jhoffner** [comment]
This sounds like you just haven't passed all of the tests for the kata. The tests shown are not usually the complete set, when you submit there usually is additional tests that are ran.

**Comment by ertogrul** [comment]
Jake,
I passed all visible tests in Kata. I cannot pass additional tests when I
don't see them. Can you make those additional test visible?

Michal.

2016-03-20 1:09 GMT+01:00 Jake Hoffner <notifications@github.com>:

> This sounds like you just haven't passed all of the tests for the kata.
> The tests shown are not usually the complete set, when you submit there
> usually is additional tests that are ran.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codewars/codewars.com/issues/258#issuecomment-198812151>
>



-- 
Pozdrowienia,

Michał Kordyzon.

**Comment by Darnor** [comment]
That's not really how Codewars works.

You get some example Tests which should give you a general idea what you'll have to do. But there are likely additional hidden tests which run when you submit your solution. They likely test some edge cases or contain tests with random data.

If you're really stuck with this Kata, maybe you could give https://gitter.im/Codewars/codewars.com/kata-solving-help a try and see if someone can help you.

**Comment by ertogrul** [comment]
Ehhh, sorry it's very hard for me to pass tests that I cannot see. Anyway,
maybe it's not related to my code. Look on text below.

[image: Obraz w treści 1]

2016-03-20 14:49 GMT+01:00 Hansruedi Patzen <notifications@github.com>:

> That's not really how Codewars works.
>
> You get some example Tests which should give you a general idea what
> you'll have to do. But there are likely additional hidden tests which run
> when you submit your solution. They likely test some edge cases or contain
> tests with random data.
>
> If you're really stuck with this Kata, maybe you could give
> https://gitter.im/Codewars/codewars.com/kata-solving-help a try and see
> if someone can help you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codewars/codewars.com/issues/258#issuecomment-198932207>
>



-- 
Pozdrowienia,

Michał Kordyzon.
