### ISSUE TITLE
Incorrect substitution of variables at login screen

### ISSUE THREAD

**Issue by jenner247450** [codewars/codewars.com#2585]
Instead of my nickname, I need to enter my email. And therefore in field of email is my nickname - which doubt to.

I mean, instead of enter "jenner247450" (nickname) and my pass, i must enter my email, but in field i see my nickname, which doubt me.

**Comment by kazk** [comment]
I'm not sure if I'm understanding you correctly.

You should see the following when logging in:
<img src="https://user-images.githubusercontent.com/639336/152061815-d670a2f0-5ed5-4eb1-8f66-16355a7c2255.png" height="400">

Do you mean you see the following?

<img src="https://user-images.githubusercontent.com/639336/152061975-94ff4d0a-1a7e-4463-b6ea-3c6024600480.png" height="400">

That's done by your browser or extension.

But maybe there's something we can do to prevent it, or some hint to make them fill in the email.
