### ISSUE TITLE
I used wrong git hub account incidentally and now I can't log in using my account, now wrong account, what to do?

### ISSUE THREAD

**Issue by conmksh-cg** [codewars/codewars.com#2587]
I tried to log in to codewars.com, but incidentally clicked on my working account, as a result I can't log in because my working account may be used only on working PC, I see an error 'Unknown GitHub user @my-login. Sign up or link your account first', and there is no option to log out, so now I can't use my github account where I've finished about 300 katas, I tried to clean 'Local storage', 'Session storage', 'Cookies', and 'Empty cache and hard reload', didn't help, I could log in using incognito mode, but I would like to be able to log in normal way. What to do?

**Comment by Hacker2** [comment]
I've managed to log in somehow, please close the issue, I can't close it

**Comment by hobovsky** [comment]
Closing per OP's request.
