### ISSUE TITLE
Styling for "error" in editor does not have enough contrast [Dark mode]

### ISSUE THREAD

**Issue by Kacarott** [codewars/codewars.com#2591]
This seems to only affect Dark mode, as Light mode has its own set of values. Currently, text in the editor which is marked as an error, is very difficult to read, due to low contrast between the highlight colour, and the underlying text colour. The highlight colour is bound to the variable `--colour-cm-error`, which currently is set to `#f2777a` and looks like this:

<img src="https://user-images.githubusercontent.com/43819332/153415217-d828f626-fa06-4211-ae79-42419127a2b5.png" width=500>

I would suggest changing the hex value to something like `#b15255` which would result in this:

<img src="https://user-images.githubusercontent.com/43819332/153416163-e2433a86-30c2-40fb-8226-4fe92b25ef85.png" width=500>

This new value feels very similar at a glance, but is *far* more readable (in my opinion)

**Comment by kazk** [comment]
Deployed, thanks
