### ISSUE TITLE
[All katas are failing to load]

### ISSUE THREAD

**Issue by YohannTisserand** [codewars/codewars.com#2618]
All the katas on the website are failing to load, I tried JS / Ruby, none of them works. I have a page 'Loading [name of the katas]' with a wheel spinning. Tried to get access to a kata through Fundamentals on the hub, didn't help.

**To Reproduce**
Just try to get access to a kata

**Expected behavior**
Get access to a kata

**Browser**
Google Chrome Version 98.0.4758.109 (Official Build) (x86_64), no extensions.

- OS: macOs BigSur 11.6
- Browser Google Chrome 
- Version Version 98.0.4758.109 (Official Build) (x86_64), no extensions.

**Comment by kazk** [comment]
Yeah, sorry about that. Just deployed the fix.

**Comment by YohannTisserand** [comment]
I have seen it is working just right now. Thank you for the fix.
