### ISSUE TITLE
Completed a kata but don't get any honor

### ISSUE THREAD

**Issue by MHXV** [codewars/codewars.com#2619]
[I](https://www.codewars.com/users/MHXV) just completed a kata ([ASCII Games: Dance Dance Evolution I](https://www.codewars.com/kata/58f58dc3663082a4ba000033/javascript)) but don't get any point. 
I found the honer change from 3870 to 3998 after the solution pass, but turn back to 3870 a few minutes later(also occur in Rank Breakdown). Is it a bug or something else.

**Comment by Blind4Basics** [comment]
Hi,

you didn't author that solution. The progress got removed.

**Comment by MHXV** [comment]
> 


> Hi,
> 
> you didn't author that solution. The progress got removed.

[This is my solution](https://www.codewars.com/kata/reviews/58fa3eea860376bb1300026a/groups/622474c71958980001d88bff)

**Comment by Blind4Basics** [comment]
Yes I know that.
Do you have a discord account? If so, poke at me (DM) on CW's server.

**Comment by MHXV** [comment]
> Do you have a discord account?

No

**Comment by Blind4Basics** [comment]
gitter, maybe, then?

**Comment by MHXV** [comment]
> gitter, maybe, then? (github account will do, for that)

I haven't use gitter before, I willI have a try.

**Comment by Blind4Basics** [comment]
Situation clarified. Completion revalidated.

Cheers

**Comment by MHXV** [comment]
Thank you very much
