### ISSUE TITLE
When editing a kata, it after fixing a broken spec it will return success but still have 1 failure

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#262]
<img width="276" alt="next_kata_in_a_sequence_-_kata_creator___codewars" src="https://cloud.githubusercontent.com/assets/579835/13902036/73a9195e-edf5-11e5-893c-52d45c5f0a23.png">

Repro steps:
- Add passing specs and then validate
- Add a new failing spec and then validate
- Fix the spec and then validate

This was happening with Ruby, other languages are unconfirmed

**Comment by kazk** [comment]
Closing as fixed. I don't think this has happened recently.
