### ISSUE TITLE
z-index of "next train challenge" div is incorrect

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2626]
**Describe the bug**

( _I use "z-index" here as a way to describe the behavior more than anything: I don't actually know how the loading is done and how all of this interacts on the page_ )

When entering the dashboard page on a narrow screen, if one puts the mouse over the bell to get to the messages notifications while the content of the `trainer-next-challenge` div is still loading, it's impossible to actually access the linked messages :

It looks as if the z-index of the tool that is loading messages (red arrow in the capture) is higher than the one of the menu showing the messages, so when the user move the mouse down toward the first box, the `trainer-next-challenge` div gets hobered instead and the whole menu of the notifications disappears.
Hence one has to wait that the `trainer-next-challenge` div finished laoding before one can access to his messages.

![image](https://user-images.githubusercontent.com/32236948/157300685-8ebb79f6-65c3-4750-a90f-5d165408a090.png)

**Expected behavior**
what's under the notification panel (ie `menu right-0 shadow-lg`) should actually be under it. x)

**Browser, OS**
FF, win7

**Additional context**
* same behavior in incognito mode
* the problem isn't just with the circle thing, it's the whole div. The circle showing up above the menu is just a symptom: the menu is still disappearing if the mouse moves "over" that div

**Comment by kazk** [comment]
Fixed
