### ISSUE TITLE
Permutations Kata attempts and tests output "should equal" x when x is already the required result

### ISSUE THREAD

**Issue by Krish-sysadmin** [codewars/codewars.com#2632]
**Describe the bug**
The Permutations Kata attempts and tests output "should equal" x when x is already the required result

**To Reproduce**

```

thearray = []

def permutations(string, theindex=0): #
    arrayOfLetters = list(string)
    global thearray

    if theindex == len(arrayOfLetters):
        thearray.append(''.join(arrayOfLetters))

    else:
        for i in range(theindex, len(arrayOfLetters)):
            arrayOfLetters[theindex], arrayOfLetters[i] = arrayOfLetters[i] ,arrayOfLetters[theindex] # 
            permutations(arrayOfLetters, theindex+1)
    
    out = list(dict.fromkeys(thearray))


    return out  

# print(permutations("aabb"))

```

**Expected behavior**
The code when run elsewhere returns the correct array of possible permutations  (such as ['aabb', 'abab', 'abba', 'baab', 'baba', 'bbaa']) but Codewars seems to fail to recognise that. 

**Screenshots**
![image](https://user-images.githubusercontent.com/75043245/158343592-f03836bd-e377-465d-bb9f-111f580314a1.png)

**Browser**

- OS: ChromeOS
- Google Chrome 
- Version 98.0.4758.107 (Official Build) (64-bit)

**Additional context**
N.A.

**Comment by hobovsky** [comment]
Your solution is incorrect.

When you have problems solving a kata, you might want to read [Solution troubleshooting guide](https://docs.codewars.com/training/troubleshooting), which could have some helpful hints. The problem which makes your solution to fail is hinted in the guide.

If you cannot figure out anything useful from the doc, you can ask for help on kata discourse or on Codewars Discord server.

Hint: Run your solution locally in your IDE twice with different inputs, for example:

```python
print(permutations('ab'))
print(permutations('abc'))
```

The second call will return incorrect results in your IDE too.

**Comment by Krish-sysadmin** [comment]
@hobovsky Thanks for your help. Does the order of the output matter? For the second one I get ['abc', 'acb', 'bac', 'bca', 'cab', 'cba'] which seems to be correct

**Comment by hobovsky** [comment]
Please lets continue this discussion on [kata discourse](https://www.codewars.com/kata/5254ca2719453dcc0b00027d/discuss/python), or on [Codewars Discord](https://discord.gg/mSwJWRvkHA), whichever suits you better.

This board is dedicated for problems with the Codewars platform and website, and not for support with solving kata.
