### ISSUE TITLE
Failed first registration, "username already taken" when re-registering

### ISSUE THREAD

**Issue by LGretzk** [codewars/codewars.com#2654]
**Describe the bug**
I signed up for an account, used it, logged off and could not access it again. Email & password showed as invalid. I then signed up for another account with the same email address and a different username. I want to use my original username, but it shows as already taken (although the first account does not exist).

**Expected behavior**
I expect the original username do not show as already taken. I expect to be able to change my current username to the original one.

**Additional context**
When I signed up the second time using the same email address I didn't get the "email already registered" message. If the first account existed I would not have been able to register with the same email address twice.

**Comment by LGretzk** [comment]
It's LGretzk (the one that shows as invalid). Thanks.

**Comment by kazk** [comment]
> When I signed up the second time using the same email address I didn't get the "email already registered" message.

Looks like you first registered with an email with a typo `@protonmaill.com`. You can log in with this email and the password, then update the email in Account Settings. Make sure to delete the second user you had created before doing that.

**Comment by LGretzk** [comment]
Thanks!
