### ISSUE TITLE
Code highlight not working on discussion pages

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2655]
**Describe the bug**
See title.
code highlight is working in preview, and when seeing the message in the dashboard, but not when the message is [in the discourse page](https://www.codewars.com/kata/62443a1ea8fca9002346d72c/discuss#624b5fd258ad06006b65a033) or in a [comment under a solution](https://www.codewars.com/kata/reviews/5ad3017d68d4e336c9001cfe/groups/624b1a534665cf0001f066c5#624b67e0d581dd00217f5571).

![image](https://user-images.githubusercontent.com/32236948/161638475-df339596-0439-41e2-afda-33e97902a5a8.png)

**Comment by kazk** [comment]
Fixed

**Comment by Blind4Basics** [comment]
![image](https://user-images.githubusercontent.com/32236948/162562858-c4155263-52db-4fed-b0b5-aa062ee1170d.png)

is that related?

**Comment by kazk** [comment]
That's #2276. The discussion page is now rendered on the client side, but the dashboard is still rendered on the server side.
