### ISSUE TITLE
If a kata had a version in language X and that version gets removed, contributors cannot translate to X anymore.

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#266]
See http://www.codewars.com/kata/56dec885c54a926dcd001095. If I try to translate it to Haskell, I just get a error 500, since there are already either pending translations or language variants.

_Note:_ I just edited the kata directly instead.

**Comment by tigretoncio** [comment]
thank you, appreciated

**Comment by srMarquinho** [comment]
Same happened here to a Ruby translation that has been deleted.
http://www.codewars.com/kata/remove-the-noise-from-the-string

**Comment by kazk** [comment]
This will be tracked in #1268
