### ISSUE TITLE
'Total completed katas' not updating

### ISSUE THREAD

**Issue by B7Bprog** [codewars/codewars.com#2664]
Hey, 
my 'Honor breakdown' shows 'completed kata(183), but the number of 'Total completed katas' never changes. It sits at 59, no matter how much more katas I complete.

![image](https://user-images.githubusercontent.com/54496822/162597320-a999e0ae-ef93-43d1-bc70-985ce92ffe8c.png)

**Comment by EloiseRosen** [comment]
It can sometimes take a while for that page to update. If you go here you can see the up-to-date number (64):  https://www.codewars.com/users/B7Bprog/completed
The 59 will update to 64 after a while.

**Comment by B7Bprog** [comment]
Thank you. Now it's all clear.
