### ISSUE TITLE
Kata voting widget only appears when user has chosen a language version that has been solved with

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2667]
Previously if someone has solved a kata in at least one language version, regardless of which language version is chosen the kata voting widget will appear in solution and discourse pages.

Since the UI change a few hours ago this is not the case. For example, I have solved Multiply (the entry kata, which everyone *should* have solved) in C#, so I can see the kata voting widget if I choose C# as the language version:

![image](https://user-images.githubusercontent.com/14909989/162862079-52ebd72b-fbf2-4ced-90e9-f1f8d2899b76.png)

But I haven't solve the kata in Rust, so I don't get the voting widget in discourse pages if I choose Rust as the language version:

![image](https://user-images.githubusercontent.com/14909989/162861951-f37a1a4d-299e-4642-bf3a-e9de1c0f1fa7.png)

Since kata voting is done towards the whole kata and not any specific language versions of it, it shouldn't be locked behind solved language versions.

**Comment by kazk** [comment]
I actually broke this 3 months ago. Just deployed the fix.
