### ISSUE TITLE
Cannot login to codewars

### ISSUE THREAD

**Issue by lukkio88** [codewars/codewars.com#2668]
Hi,

I cannot login to codewars.
Or better, I am trying to login through my github account. It says it's linked but I still cannot access the problems, the page is the same as I wasn't logged in.

While if I try normal credentials (user + pass) I get the same problem.

Can you help? or is it just me not being able to use the portal correctly?

**Comment by hobovsky** [comment]
I can try and walk you through your problem on `#support-requests` channel on Codewars Discord, if you'd be willing to join.

If you don't want to join that's fine too. We can continue here, and first youd just have to tell me a link to your Codewars profile. Is this [lukkio88](https://www.codewars.com/users/lukkio88)?

**Comment by lukkio88** [comment]
Hi, I think I just sorted out.
What I did was cleaning the whole history from chrome (my default browser) which also implied logging out from all the websites. Then I re-tried with just mail and password (I had to reset the password) and it worked.

The github login was still giving me the same problem.

> If you don't want to join that's fine too. We can continue here, and first youd just have to tell me a link to your Codewars profile. Is this [lukkio88](https://www.codewars.com/users/lukkio88)?

Yes that's my profile.

**Comment by hobovsky** [comment]
I am not sure I understand:
- You managed to log in with a login and password, do I get this correctly?
- You have problems logging with Github, right? If so, please try to log in with email and password and link with Github again. As far as I see your account is not currently linked with Github, and it's a known issue that they get unlinked somehow, sometimes, but maintainers were not able to reproduce it yet.

**Comment by lukkio88** [comment]
> - You managed to log in with a login and password, do I get this correctly?
Yes. At the end I managed to login with my mail and pwd, but I had to cleanup the browser cache for some reason.

> You have problems logging with Github, right? If so, please try to log in with email and password and link with Github again. As far as I see your account is not currently linked with Github, and it's a known issue that they get unlinked somehow, sometimes, but maintainers were not able to reproduce it yet.

Yes. When I try to access through my github account another UI asks me for mail and pwd, but the only reply I get is *your account is already linked*. And It doesn't allow me to login.

**Comment by kazk** [comment]
> Yes. When I try to access through my github account another UI asks me for mail and pwd, but the only reply I get is your account is already linked and it doesn't go any further.

Can you post a screenshot? You should be in Account Settings page.

I think you're trying to "Sign in with GitHub", but your account is currently not linked to GitHub. You're probably being redirected to the sign up form (another known bug that I can't reproduce), and it says GitHub is linked, but that means it's linked to a **new account** and not your existing one.
