### ISSUE TITLE
code alignment troubles in "Show Kata Test Cases"

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2669]
![image](https://user-images.githubusercontent.com/32236948/163274147-f0b93939-c9fe-4425-8852-8f03399aad77.png)

lines are apparently overlapping and underscores are disappearing. The bottom line seems to actually always be missing if another line is just below (see comma of parentheses: one missing pixel each time, except on the last line of the "group")
Everything is still ok in a code editor (trainer/fork panel), that's only when the tests are shown in the discourse or the solutions pages.
(Same problem in light mode)

**Comment by kazk** [comment]
Which kata? The one I just tried doesn't have this issue.

![image](https://user-images.githubusercontent.com/639336/163274752-6943a729-df71-4803-9179-a2db97c2ddb6.png)

**Comment by hobovsky** [comment]
Do you have view zoomed in? Maybe it's a matter of zoomed view, or some other scaling? DPI? Custom styling to make font larger?

**Comment by JohanWiltink** [comment]
I just noticed the same rendering on https://www.codewars.com/kata/52945ce49bb38560fe0001d9/solutions/lambdacalc

![Untitled](https://user-images.githubusercontent.com/18171520/163288048-83ee2151-87f0-46ec-827a-87ed39c81ef6.png)

Bog standard Windows 10, Firefox 99.0, no zooming in or scaling whatsoever. Windows won't tell me a DPI setting, but it's also on default.

**Comment by JohanWiltink** [comment]
Font seems different between kazk's on one hand and Blind's and mine on the other. Possibly depends on platform.

**Comment by kazk** [comment]
When did this start? I did update CodeMirror yesterday from [`5.65.0` to `5.65.2`](https://github.com/codemirror/CodeMirror/compare/5.65.0...5.65.2).

Does it happen when editing too?

**Comment by JohanWiltink** [comment]
Editing looks to be unaffected.

Does it make a difference what and where I'm editing? Neither kumite editor nor kata editor seem to have the problem.

**Comment by Blind4Basics** [comment]
it's here, for example (for me) : https://www.codewars.com/kata/5acc79efc6fde7838a0000a0/discuss/python

I noticed yesterday just before I posted the issue (my eye got caught by the function names "with spaces in them")
Again, it's like this only in the discourse and solutions pages.
@hobovsky no zooming, no. I actually tried zooming in and out and it stays the very same whatever the scale.

windows 7, FF 99 (64bits), here

**Comment by kazk** [comment]
> Editing looks to be unaffected.

> it's like this only in the discourse and solutions pages.

Ok, maybe something changed with `runmode` that's used to syntax highlight, and it only affects Windows?

Can you try https://codemirror.net/demo/runmode.html and see if it happens there?

**Comment by JohanWiltink** [comment]
![Untitled](https://user-images.githubusercontent.com/18171520/163454729-2650594d-c6c2-4712-b421-d6a0d9be5884.png)

Like this? The `'g'` in `dithering (n-1)` is complete - this is rendered with enough vertical spacing to show everything.

**Comment by kazk** [comment]
No, click `Highlight!` button and see if the output has the same issue.
![image](https://user-images.githubusercontent.com/639336/163455468-73e5ce21-c6d1-4043-aeca-b715fbe03b61.png)

**Comment by Blind4Basics** [comment]
looks normal: 

![image](https://user-images.githubusercontent.com/32236948/163459115-9e2a673c-9273-4f74-966f-54600f0109de.png)

**Comment by kazk** [comment]
The text needs to be XML to get highlighted there.

Try something like
```xml
<describe_test>
  <test_it>
    <test_equals actual="0" expected="1"></test_equals>
    <test_equals actual="1" expected="2"></test_equals>
  </test_it>
</describe_test>
```

---

I'll try reverting CodeMirror and see what happens.

**Comment by Blind4Basics** [comment]
ha, sorry... I was thinking that couldn't be the way to go, but... 'x)

I get this, but not sure that will help:
![image](https://user-images.githubusercontent.com/32236948/163461029-640b28ae-8d8a-457e-9636-b4d7944b4ef6.png)

**Comment by JohanWiltink** [comment]
![Untitled](https://user-images.githubusercontent.com/18171520/163461301-f3ea73e7-4780-40d4-ac2d-eb91d72ed059.png)

with some things that extend below the line: yes, `g` and `_` are rendered completely.

**Comment by JohanWiltink** [comment]
But that still doesn't look comparable to code that's actually going wrong:
![Untitled](https://user-images.githubusercontent.com/18171520/163461855-495eb9c0-12ef-441e-9cf3-88d7789d0095.png)
so I don't fully understand what you're having us test here.

**Comment by kazk** [comment]
I was trying to see if the latest CodeMirror has the same issue.

Now we know it's not CodeMirror.

Can you run this in the console?

```javascript
var style = document.createElement("style")
style.innerText = `#fixture_panel code {font-family: monospace !important}`;
document.head.appendChild(style)
```
This will use the default monospace font.

**Comment by Blind4Basics** [comment]
yu^p, that resolves the problem

**Comment by kazk** [comment]
Then it's the font. I don't think we changed this recently :/

**Comment by error256** [comment]
I don't have this exact issue, but I did notice the change in line height around that time. It's `font-size: 1em`, `line-height: 18px` now. If `em` is mixed with `px`, doesn't it mean that it depends on system DPI?

**Comment by Blind4Basics** [comment]
happens in ruby too, see #2688

**Comment by kazk** [comment]
> I don't have this exact issue, but I did notice the change in line height 

I think something was accidentally changed with the theme update. I don't see anything obvious, but probably some inherited property changed.

This is not happening on other code blocks (e.g., solutions on profile), right?

> happens in ruby too

Language shouldn't matter.

**Comment by kazk** [comment]
Changed the style to match other code blocks. Please confirm if this is fixed.

**Comment by JohanWiltink** [comment]
Seems fixed. I checked `Test cases` on the `Solutions` page, and `View solution` on `Discourse`l those were the places I could read back to be affected.

**Comment by kazk** [comment]
Thanks!
