### ISSUE TITLE
The console.log() function drops the first doubled space from Javascript kata output

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#267]
This is an odd bug I discovered while working on a Javascript kata relating to text formatting.  The console.log() function _always_ drops the first doubled space from the HTML output I am using.  

Most of the time this goes unnoticed since multiple spaces in HTML are typically displayed as a single space in the browser.  However, where the raw formatting is important, developers frequently override this for debugging purposes using the &lt;pre&gt; tag, CSS, ....

This bug manifests in multiple browsers.  Here's what happens:

For example:

``` javascript
console.log('<pre>AA  BB  CC</pre>');
console.log('<pre>AA--BB--CC</pre>');
```

displays as

```
AA BB  CC

AA--BB--CC
```

Notice that the double space between AA and BB has been truncated to a single space, but not the double space between BB and CC.  Only one space is removed, so if there are 3 spaces, instead 2 appear.  If 4, then 3, etc.  Single spaces do not appear to be affected.  If a single space appears first, then console.log() continues to lurk secretly in the shadows and gobbles up half of the next double space when it is output. Very scary stuff.

Closer examination reveals that only the first double space in the _entire_ kata is dropped, so immediately adding another line:

``` javascript
console.log('<pre>AA  BB  CC</pre>');
console.log('<pre>AA  BB  CC</pre>');
console.log('<pre>AA--BB--CC</pre>');
```

results in 

```
AA BB  CC

AA  BB  CC

AA--BB--CC

```

Notice the second line does not manifest the buggy behavior.  This holds true in my tests no matter how many additional calls to console.log() are made.  So it is pretty simple to workaround now that I know to feed the beast a double space before outputting preformatted text to console.log().  But it was frustrating working on the text justification kata when my first two words were not spaced properly in the console output.

(Tested on latest stable Chrome and Firefox on Windows 10)

**Comment by kazk** [comment]
Fixed in https://github.com/Codewars/codewars-runner-cli/pull/438.
