### ISSUE TITLE
Difficult to distinguish between resolved and unresolved questions & suggestions label

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2670]
The overall UI looks good, except this part, in which the previous version seems better IMO! Maybe for resolved suggestions & questions label, the color contrast can be adjusted to darker ones. (as shown below)

![image](https://user-images.githubusercontent.com/65498235/163671844-498d7450-1b9e-4762-bdee-fb49bfdc41da.png)

**Comment by kazk** [comment]
Deployed the fix
