### ISSUE TITLE
Kumite editor reverts `Test Cases` on `Save` when `Details`/Description has also changed

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/codewars.com#2671]
I have now lost work multiple times in the following way: I fork a solution, update the tests ( and optionally the solution ) ( to try out something new ), write a description in `Details`, and only then `Save`. This saves my description ( and solution ), but reverts my tests ( which I have `Run` successfully several times ).

This does not seem to happen on a forked fork, but I can reproduce it exactly as described on a directly forked solution.

It does not seem to depend on kata language, platform or browser - I reproduced it on a Lambda Calculus kata on Firefox and a JavaScript kata on MS Edge ( I now feel dirty, but I'm doing it for you ) on Windows 10 and a JavaScript kata on Firefox on Debian.

This behaviour is not new or really recent, but I cannot exactly pinpoint the first time I got bitten. Possibly months ago. ( I don't run into it _that_ often. )

**Comment by kazk** [comment]
This was a regression from the changes I made for solution forks to use the current tests/preloaded code back in February.
