### ISSUE TITLE
Comment-link doesn't jump to the relevant comment if the page is loaded in the same browser tab

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2678]
Here's a [link](https://www.codewars.com/kata/61cd0378ab22ae0033905112/discuss/python#62683c2b8a0e6f42c1a95790) to an issue I've raised on a kata. If you click on it here, you will go to discourse section of that kata, the page will scroll down, and the comment thread will be expanded and highlighted, as intended.

Now, [in this comment](https://www.codewars.com/kata/61cd0378ab22ae0033905112/discuss/python#626992de8a33feba3dad8ff5) I've posted the same link to the same issue as a reference for the author. For some reason, clicking on it there does nothing - the page reloads, of course, but that's it (the kata author confirmed it's not working for him as well in a reply). Since this second comment is relatively fresh, you can find it from the dashboard and try clicking on the link from there, but the result will be the same - you'll go to the discourse section and nothing else will happen. In fact, if you create a kumite, post this link in its description, publish the kumite, and click on the link, it will not work as well.

What's common between all these 3 cases is the fact that clicking on the link made the browser navigate to that discourse section in the currently opened tab, i.e. you navigate from a CW page to a CW page in the same browser tab. I believe this is the source of the problem since you can write a comment containing a comment-link anywhere, switch to comment preview mode, click on it, **the linked page will open in a new browser tab**, and everything will work correctly (this has been also tested and confirmed for kumite editor's description preview and kata editor's description preview which also open the page in a new tab).

**Comment by kazk** [comment]
This was because `history.pushState` doesn't affect `:target` selector. https://bugs.webkit.org/show_bug.cgi?id=83490

Same issue as #2656. The links to comments on dashboard and user's profiles were working because I had a workaround for them, but I forgot about the notification and links within Markdown.
