### ISSUE TITLE
Update CodeMirror to fix === issue in Julia

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2679]
For details, please see: https://github.com/codemirror/CodeMirror/issues/6913

**Comment by kazk** [comment]
I updated to the latest version released today, but I don't think it's fixed. Same result on https://codemirror.net/mode/julia.

**Comment by XRFXLP** [comment]
Hopefully that would be fixed in [this](https://github.com/codemirror/CodeMirror/commit/e71f6843ad67603350c545b8fdf41917e631a533) patch.
