### ISSUE TITLE
Katas from Collections can be deleted by non-collection-creators

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2680]
**Describe the bug**
Katas can be deleted from collections by logged in users who have not created the collections by little HTML manipulation

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

Execute this script in browser console:
```javascript
Q = document.getElementsByClassName('is-hidden');
for(var x of Q)
    x.classList.remove('is-hidden')
```
After that, the page will look as if I have created that collection:
![image](https://user-images.githubusercontent.com/23459568/166400707-53f56a11-c290-444a-a67e-dd4dc79f65d3.png)

On clicking dustbin icon on kata:
![image](https://user-images.githubusercontent.com/23459568/166400758-80ba1075-3195-434f-ac0c-ee6707a3a723.png)

After that:
![image](https://user-images.githubusercontent.com/23459568/166400787-bb2c4456-9feb-4bce-bfc9-7a283463d84c.png)

(But "edit" and "delete kata collections" doesn not work)

**Expected behavior**
Since, it was intended that only collection creator can modify collections, the behaviour should comply with that intention.

**Additional context**
I've made sure that this is not some cookie/cache related behaviour, by opening the sites on different devices/browser

**Comment by kazk** [comment]
Thanks for reporting. A quick fix was deployed soon after you posted this. Requests to delete an item in a collection you don't own should fail now.

Next time, please follow https://github.com/codewars/codewars.com/security/policy for these bugs that can be easily abused.
