### ISSUE TITLE
Increase contrast between highlight colours of keywords and non-keywords in C/C++/C#

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2681]
In C/C++/C# there is hardly any noticeable difference between colour highlighting of keywords and non-words.

As can be seen from screenshot taken of C:
![image](https://user-images.githubusercontent.com/23459568/166401285-4c7e18c4-54a6-47d9-aad2-7babbd94109b.png)
**Describe the solution you'd like**
Increase contrast between these two sets.

**Describe alternatives you've considered**
Change the text colour of code editor using client side JavaScript

**Comment by FArekkusu** [comment]
I find it weird that `--color-cm-atom` is used for types but `--color-cm-keyword` is used for keywords (particularly `auto` in C++ and `var` in C#) even though built in type names are keywords too. IMO, the same color should be used for both.

![image](https://user-images.githubusercontent.com/31668662/166977866-91bde9bb-8b01-4ff7-932b-2c376a5794ea.png)

![image](https://user-images.githubusercontent.com/31668662/166979193-ef9e058f-43bd-4354-98b0-45139f55d7af.png)

___

Apart from that, the colored text is hard to discern in light mode. It looks more or less fine in the screenshot below, but it's noticeably worse when you look at it on CW.

![image](https://user-images.githubusercontent.com/31668662/166982798-f412d1f2-a0d8-4b08-9d55-053b618166e4.png)

I wonder if a separate issue should be opened for this or not considering these problems are related.

**Comment by kazk** [comment]
Some languages don't use `cm-type` and uses `cm-atom` instead for types. I can change `cm-type` to use `--color-cm-keyword`.

> I wonder if a separate issue should be opened for this or not considering these problems are related.

Please open a new issue. I didn't add a new color.

**Comment by kazk** [comment]
Updated `.cm-type` color
