### ISSUE TITLE
i can't access my account[short description of the bug]

### ISSUE THREAD

**Issue by kevinjuniorr** [codewars/codewars.com#2684]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by Madjosz** [comment]
The bug template is there for a reason. Please give additional information. What have you tried? Are you logging in via e-mail address or via GitHub? Have you tried it in incognito/private mode? Have you tried to reset your password? What is the error message you are encountering? etc.
