### ISSUE TITLE
Anonymous users can access the training editor by manually going to the training URL

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2686]
### Bug

It seems that users which are not logged in are not intended to train on a kata as there is no option for "Train" on kata page:

![image](https://user-images.githubusercontent.com/23459568/167248416-02fd18f0-f8e9-45e8-b9b3-9926fa8988b8.png)

But on appending `/train` at the end of the URL, one can access the training editor:

![image](https://user-images.githubusercontent.com/23459568/167248456-7e219370-0696-408f-9c4a-de264f9a5482.png)

### Expected Behaviour

I'm not sure in which part the bug is:
1. Is the bug in the first screenshot where there weren't any training option for anonymous users?
2. Or it was not intended that they can visited the training page (second screenshot)?

### Browser

Brave 1.38

**Comment by hobovsky** [comment]
I think that the ability to train is intended, its been always possible to train on a kata as a guest, and sign up after solving a kata.
I did not know the Train button is not visible for guests.

**Comment by XRFXLP** [comment]
> I think that the ability to train is intended, its been always possible to train on a kata as a guest, and sign up after solving a kata.

I thought the removal of this ability of training in this situation was in the development:  See https://github.com/codewars/codewars.com/issues/2306#issuecomment-761442720
