### ISSUE TITLE
Improper handling of some non-alphanumeric characters in kata search bar

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2697]
As the title says, some non-alphanumeric (for instance `#` or `%`) are not properly handled:

![image](https://user-images.githubusercontent.com/23459568/169652735-b07d9644-f293-4fef-8e65-981bfd3c91b1.png)

results in: (`#` somehow is filtered resulting in no result even though there is such kata: [Simple Fun #98: Day Of Week](https://www.codewars.com/kata/58980e288927f7f6e300001b) )

![image](https://user-images.githubusercontent.com/23459568/169652741-8967dfd5-4383-4d3c-b25d-c281a67a3732.png)

Another example:
![image](https://user-images.githubusercontent.com/23459568/169652786-0980972a-705a-40ad-9e4d-f2bf1bfda8d6.png)

results in: (other parameters query info gets appended in the search bar)
![image](https://user-images.githubusercontent.com/23459568/169652806-d2f4a983-cb9b-41b8-9327-9c7f6b14bc3b.png)

## Expected Behaviour

Characters should not disappear and nothing additional should be appended

**Comment by kazk** [comment]
Deployed a fix
