### ISSUE TITLE
Forums with many comments don't load completely

### ISSUE THREAD

**Issue by bkaestner** [codewars/codewars.com#27]
According to the statistics, the [feature-request](http://www.codewars.com/topics/feature-requests) forum should have ~190 top-level comments. However, I can only see requests up to the following one:

> A time estimate for how long it takes to solve each Kata would be useful for interview prep (coding under pressure). The estimate could either be submitted by the Kata author or based on historical averages. [by mxdubois, 3 months ago]

A quick check with `$$('.comments-list > .comment').length` ([`$$` = `document.querySelectorAll`](http://stackoverflow.com/a/22244912/1139697)) reveals that there are really just 94 top-level comments. So I can't view the additional ~100. They also don't load when I'm scrolling down.

**Comment by jhoffner** [comment]
Considering this an enhancement for now. We may do away with that forum completely.

**Comment by bkaestner** [comment]
Closed as the forums are read-only nowadays.
