### ISSUE TITLE
Javascript code formatting of post-increment operator (i++) is wrong on solutions page

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#270]
The code formatting of the solution below is incorrect.  It executes without error and is colored correctly by GitHub so this appears to be a bug.

The post-increment operator in the following code (i++) seems to be incorrectly parsed as the binary addition operator(+) with a missing argument as opposed to the unary post-increment(++) operator with only one argument.

![screenshot from 2016-03-27 14 16 53](https://cloud.githubusercontent.com/assets/5090280/14066970/f8b24080-f426-11e5-91f0-6a8ff6447267.png)

``` javascript
function Xbonacci(s, n){
  var len = s.length, i = len - 1;
  while (i++ < n) {
    s[i] = s.slice(i - len).reduce(sum, 0);
  }
  return s.slice(0, n);
}
```

Source: www.codewars.com/kata/556e0fccc392c527f20000c5/solutions/javascript

**Comment by jhoffner** [comment]
Thanks for reporting. Updating our version of CodeMirror would probably help but unfortunately we are stuck on an older version until we can get the time to do an upgrade, which involves basically redoing our integration due to breaking changes on their end.

**Comment by paul-calvelage** [comment]
I don't think updating CodeMirror would help, since the solutions page appears to be using highlight.js (https://highlightjs.org/).  I can reproduce this bug in the current version of highlight.js using one of Codewars CSS sheets:
```html
<html><head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/default.min.css">
<link href="http://d3l8wp33uu8nxs.cloudfront.net/assets/application-f1025241cadf54fd707645a4935c0b1a.css" media="screen" rel="stylesheet" type="text/css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
</head><body>
<pre><code class="javascript">
function Xbonacci(s, n){
  var len = s.length, i = len - 1;
  while (i++ < n) {
    s[i] = s.slice(i - len).reduce(sum, 0);
  }
  return s.slice(0, n);
}
</code></pre></body></html>
```
![wrong](https://cloud.githubusercontent.com/assets/5090280/14205106/c63ba7dc-f7d6-11e5-8c87-a57f074f3551.png)

This could probably be reported upstream as well, since I didn't see an issue for this at https://github.com/isagalaev/highlight.js/issues, and it's reproducible on the latest version.

After looking at this more closely, I finally have an explanation as to why the highlighting is so inconsistent between the editor and the solutions page: there are two different highlighting solutions at play here: CodeMirror and highlight.js.  

Perhaps the inconsistency should be a separate bug?  I have wondered why code that looks good colored in the editor suddenly looks awful when I get to the solutions page.

Additionally, I saw another variation of this problem today.
![merge](https://cloud.githubusercontent.com/assets/5090280/14204246/eccff200-f7d0-11e5-85da-3e4ee672878d.png)
This one also has a less than comparison after the ++.  I wonder if that's what triggers the problem?
Source: http://www.codewars.com/kata/55e1990978c60e5052000011/solutions/javascript

**Comment by kazk** [comment]
Closing this because this is third party issue and regular expression based syntax highlighting can never be perfect.
We may consider switching to use CodeMirror to do the highlighting in the future.
