### ISSUE TITLE
Description not updated despite fork with updates approved!

### ISSUE THREAD

**Issue by ejini6969** [codewars/codewars.com#2700]
Not entirely sure if it's a specific issue of [this kata](https://www.codewars.com/kata/55633765da97b266e3000067/discuss), but there's alr three versions of translations approved, 1 in Python, 2 in JS which changes the description. However, the update seems to make description more messed up! (Not sure if this is related to the use of KaTex tho)

Messy description despite update
![image](https://user-images.githubusercontent.com/65498235/169935990-5593037a-7b73-49c7-8744-3023986d9991.png)

Description in fork
![ffffdssfdds](https://user-images.githubusercontent.com/65498235/169936469-4aa60603-666f-492e-aa88-a903957ffef6.gif)

**Comment by kazk** [comment]
Looks like merging forks that only changes description has been failing for a while.

**Comment by ejini6969** [comment]
Guess this explains why approval on translation that modifies description does not make one become a contributor!

**Comment by Blind4Basics** [comment]
> Guess this explains why approval on translation that modifies description does not make one become a contributor!

errr... it's the other way arrund, isn't it? x)

**Comment by kazk** [comment]
There was an unexpected validation error preventing save. Should be fixed.
