### ISSUE TITLE
Behind VPN can't access site anymore

### ISSUE THREAD

**Issue by mclark4386** [codewars/codewars.com#2702]
**Describe the bug**
Behind a VPN I get the following when trying to access the site in general:
<img width="982" alt="Screen Shot 2022-05-25 at 5 15 14 PM" src="https://user-images.githubusercontent.com/484943/170377499-e28ffa6c-1f0b-454f-9049-6837f5bc0599.png">
If I switch which exit I'm connected to it may or may not work for a time, but eventually it'll error back out to this.

**To Reproduce**
I'm using NordVPN with an exit in the USA. Current server(exit) is #9702.

**Expected behavior**
To be able to get to the site regardless of VPN status, unless the VPN is blocking it.

**Screenshots**
See above

**Browser**
Tested in Vivaldi, Chrome, and Safari and happens the same in all.

**Additional context**
Happy to answer any questions!

**Comment by kazk** [comment]
We don't want to do this, but we have some IP/ASN blocked because of persistent spammers (most likely a small group or same person, though) spamming n-word and posting NSFW images. They kept coming back and blocking slowed them down.

I can disable the rule and see what happens if you want.

**Comment by mclark4386** [comment]
I'm going to be awake for maybe an hour more if you want. Otherwise I can ping in here again tomorrow if you are wanting to do this "real-time".

**Comment by kazk** [comment]
Disabled for now.
