### ISSUE TITLE
Can't recover account?

### ISSUE THREAD

**Issue by josephbaitz** [codewars/codewars.com#2707]
Every time I click login it just sends me back to the home page. Not logged in. 
Every time I add my email to reset my password and click "forgot your password?" It sends me back to the homepage.
Every time I successfully login through my GitHub it takes me back to the homepage. Not logged in again.
Then I go to "Sign Up" and it says "You're already signed in."
Then I add my email and username and they're "already taken."
Its a never ending loop of not being able to do anything on this website.
I'm unable to login or recover my account. I have no idea what to do other than make a new account?
Maybe I'm missing something but I've tried multiple browsers to no avail.

I expected to be able to login through my GitHub or at the very least recover the account and reset my password.

![Screenshot 2022-05-31 182513](https://user-images.githubusercontent.com/61953529/171311486-9494263c-e850-4490-8ece-b92642478062.png)

![Screenshot 2022-05-31 184633](https://user-images.githubusercontent.com/61953529/171311636-369e0891-507d-46d0-9b45-2889ebe1a59d.png)

- OS: Windows 10 Pro
- Browser Chrome, Firefox Developer

**Comment by kazk** [comment]
Have you tried in Incognito/Private window? A few users have reported this in the past, but I can't reproduce.

Do you see anything in Dev console? Maybe a screenshot of the network tab would help to understand.
