### ISSUE TITLE
My Rank rolled back

### ISSUE THREAD

**Issue by rizomus** [codewars/codewars.com#2718]
**Describe the bug**

I received a notification about ranked up to 3.  And Rank Breakdown actually was changed. 
A few days later I stil can see notification (screenshot), but my rank now rolled back to 4.

**Expected behavior**

I'd like to return rank 3

**Screenshots**

![rank 3](https://user-images.githubusercontent.com/104506812/173178732-c280fda1-2a20-4ab9-a17c-cd30968e7920.png)

**Browser**

- OS: Win 8.1 x64
- Browser google chrome 
- Version 102.0.5005.63

**Comment by Blind4Basics** [comment]
Hello,

I guess https://www.codewars.com/users/rizomus is you codewars account?
Some of your solutions got invalidated because you didn't "solve" those kata, you just used code you found on the internet.

Cheers
