### ISSUE TITLE
bug in Array.sort()

### ISSUE THREAD

**Issue by lameroid** [Codewars/codewars.com#272]
Javascript
[0,1,2,3,4,5,6,7,8,9,10].sort((first, second) => Number(first) > Number(second)) returns [5, 0, 1, 2, 3, 4, 6, 7, 8, 9, 10];
On locale machine it returns  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

**Comment by jhoffner** [comment]
This is because all environments and all JS engines are not created equal. We will be rolling out updated versions of Node soon, thats the best we can do.
