### ISSUE TITLE
Extra background on code lines (css)

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2722]
I've noticed this morning that all lines of code are slightly "highlighted" (indentation included) in a weird fashion.

Upper is the acutal display. I added a contrast filter on the second to make the problem more obvious:

dark mode:
![image](https://user-images.githubusercontent.com/32236948/173757608-72bc7afe-ae36-4eba-99fc-4f04528e69ee.png)

light mode too:
![image](https://user-images.githubusercontent.com/32236948/173758255-069a2d17-11e1-49aa-a924-32233158131f.png)

Happens everywhere I looked at (edit: but not everywhere _everywhere_... see [below](https://github.com/codewars/codewars.com/issues/2722#issuecomment-1156109778)).

It looks like it's related to css formatting of the `code` tag itself

**Comment by kazk** [comment]
> Happens everywhere I looked at.

Can you inspect the element and see which rules are applied?


I did update some dependencies, so it's possible, but I don't see it.

![image](https://user-images.githubusercontent.com/639336/173759795-ef233f70-f7e7-4036-bf4f-9b53874afc81.png)

**Comment by Blind4Basics** [comment]
it's this rule that is causing troubles: 

```css
pre[lang], code[class^="language-"], code[data-language] {
  background-color: var(--color-cm-editor-bg);
}
```

**Comment by kazk** [comment]
Which page are looking at? Or does it happen to all code blocks?

**Comment by Blind4Basics** [comment]
That one was in my solutions profile page (.../users/.../completed_solutions), but I've seen it in solutions-stats too. It show sup neither in kata solutions pages nor in solutions groups pages.

**Comment by kazk** [comment]
I can't reproduce it. Do you have userscript disabled?

**Comment by Blind4Basics** [comment]
:+1: yeah, that's hob's script, sorry.

**Comment by hobovsky** [comment]
I just wonder how because I don't recall doing anything around, but I will check.

Sorry for the problem.
