### ISSUE TITLE
Can't login to Codewars using my GitHub account

### ISSUE THREAD

**Issue by YousufRab** [codewars/codewars.com#2727]
I get the error message:
"Unknown GitHub user YousufRab. Sign up or link your account first."

My account is linked. I have tried unlinking from Github account settings and relinking it again through Codewars login but the error message persists.

Any help would be appreciated.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1b5j) by [Unito](https://www.unito.io)

**Comment by za** [comment]
I am also having the same issue.

**Comment by YousufRab** [comment]
> 

Try turning off any adblock plugins on your browser. It worked for me

**Comment by chisem29** [comment]
help

**Comment by VanessaGreene** [comment]
Hi @chisem29, please reach out to our support team at info@codewars.com for account issues :)

**Comment by jmeno1011** [comment]
I solved this problem.
We need to visit the "Sign up" page. 
Then there is "Link Your Github Account" button at the end. 
Clicking it should let you access the service!
