### ISSUE TITLE
Code editor formatting of Javascript ES6 class is wrong on training page

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#273]
[Please note: This is not a duplicate of the issue I recently filed regarding a formatting bug by highlight.js on the solutions page.  The issue here relates to the CodeMirror editor on the training page.]

Notice how the code editor formats this Javascript ES6 class incorrectly.  The object properties within sayFullName() are not colored correctly.  The words 'log', 'firstName', and 'lastName' should all be blue since they are object properties.  On the other hand, it seems the word 'constructor' should be colored white rather than blue to match the other functions.

Curiously, the 'log' property _is_ colored correctly in the greetExtraTerrestrials function that follows.

![es6](https://cloud.githubusercontent.com/assets/5090280/14207973/1390fbcc-f7eb-11e5-89b1-5b85babc3eb3.PNG)
Source: http://www.codewars.com/kata/56f7f8215d7c12c0e7000b19/train/javascript

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/39341980-9613a610-498a-11e8-9b33-4b5328a4c744.png)
