### ISSUE TITLE
Unauthorized Error on all Kata

### ISSUE THREAD

**Issue by icarus-child** [codewars/codewars.com#2732]
**Describe the bug**
When trying to test or attempt code for the kata, a red 'Unauthorized' box shows up in the output window with a 0ms return time

**To Reproduce**
Run any code in any kata

**Expected behavior**
Code return to be shown in the output box

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser: Attempted with Firefox 101.0.1 (64-bit) and Microsoft Edge 102.0.1245.44 (Official build) (64-bit)

"You don't have the right, O you don't have the right, you don't have the right, O you don't have the right"

**Comment by fabiankllr** [comment]
Same on Google Chrome Version 102.0.5005.115

**Comment by eisbar1** [comment]
When tryinng to complite simple initiation challenge 
OS: linux Firefox and Chrome

**Comment by kazk** [comment]
We're affected by Cloudflare outage https://www.cloudflarestatus.com/incidents/xvs51y9qs9dj
