### ISSUE TITLE
Internal Server Error on `/trainer/setup`

### ISSUE THREAD

**Issue by sohamsv** [codewars/codewars.com#2743]
Message I get:
Internal Server Error
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our [Github issues list](https://github.com/codewars/codewars.com/issues). This will help us get things fixed faster.

**Comment by kazk** [comment]
> If you would like to supply us with some details as to how this happened please visit our [Github issues list](https://github.com/codewars/codewars.com/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Please provide some details :D

Are you on https://www.codewars.com/trainer/setup ?

That page is currently broken. Unfortunately, I don't have access to the external service causing this, so we'll need to wait...

**Comment by deekayex** [comment]
I got this message immediately after registering with my GitHub 

Message I get:
Internal Server Error
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our [Github issues list](https://github.com/codewars/codewars.com/issues). This will help us get things fixed faster.

**Comment by kazk** [comment]
Yeah, the broken page is the page you're redirected to after signing up, unfortunately.

I _think_ you can still use the site by choosing kata from https://www.codewars.com/kata/search/?q=&r%5B%5D=-8

**Comment by kazk** [comment]
Added a workaround to prevent crashing immediately after signing up. Pages other than https://www.codewars.com/trainer/setup should be working now.
Go to https://www.codewars.com/dashboard if you saw this error immediately after signing up.

**Comment by Exoutia** [comment]
I also got the sane thing just now

**Comment by AndyScroll** [comment]
Same problem. I wanted to change language from C# to JS.

**Comment by jhoffner** [comment]
Fix is being deployed now
