### ISSUE TITLE
Esc in VIM mode unfocuses code editor

### ISSUE THREAD

**Issue by eaglesdare** [codewars/codewars.com#2744]
**Describe the bug**
When editor is set to VIM mode, when exiting insert mode with `ESC` key the editor is unfocused and not reacting to any input.

**To Reproduce**
1. Open any kata.
2. Focus the solution editor.
3. Toggle VIM mode on.
4. Press `i` to enter insert mode.
5. Press `ESC` to exit insert mode.
6. Observe that editor is now unfocused and does not react to inputs.

**Expected behavior**
The editor is expected to react to further inputs of user after exiting insert mode with `ESC` key.

**Screenshots**
n/a

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser: Vivaldi
- Version: 5.3.2679.61 (Stable channel)

**Additional context**
n/a

**Comment by kazk** [comment]
I can't reproduce this. Vim mode is the most tested because I use it.

Does it work on https://codemirror.net/5/demo/vim.html ?

**Comment by eaglesdare** [comment]
> I can't reproduce this. Vim mode is the most tested because I use it.
> 
> Does it work on https://codemirror.net/5/demo/vim.html ?

Yes, it's the same issue on this page.

**Comment by kazk** [comment]
Then that's not Codewars' bug.

Have you tried disabling browser extensions? If you can still reproduce it on that page without any extensions enabled, maybe it's a CodeMirror bug for Vivaldi. Perhaps you can find something in https://github.com/codemirror/codemirror5
