### ISSUE TITLE
Navigation broken from Edit account to Leaderboard

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#275]
Just try to navigate from https://www.codewars.com/users/edit to http://www.codewars.com/users/leaderboard

you will see:

>    http://www.codewars.com/users/{:protocol=>"http"}

**Comment by kazk** [comment]
Closing this because I can't reproduce and it's been 2 years. Let me know if this is still happening.

**Comment by javatlacati** [comment]
Fixed thank you
