### ISSUE TITLE
Filter/section leaderboard

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#276]
Can you please add filters or tabs on the leaderboard to check rankings for system language, clan and country?

**Comment by javatlacati** [comment]
migrated: https://codewars.ideas.aha.io/ideas/CW-I-92

**Comment by ChrisDillinger** [comment]
Still really frustrated w/ accessing leaderboards... haven't used the site in a bit and now I can't figure out how to view my own clan's leaderboard......
