### ISSUE TITLE
Usability improvements for "Pending translations" view

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#2770]
Privileged users (moderators and menders) can access a listing of translations pending for approval under https://www.codewars.com/kumite/translations . It's a very useful view for maintainers who work on reducing the backlog of pending translations, but could be improved a bit to make their work easier:
- Translations to retired kata and drafts are shown, which, I think, is not necessary.
- A bit more details could be presented, like, for example, kata rank or beta/approved. It would make it easier to focus on translations which require potentially smaller effort to review and test.
- New translations could be somehow differentiated from forks with fixes, which would make it easier to introduce and merge bug fixes to kata. However, I am aware that determining whether a translation is a bugfix is not always easy.
- It could be useful to see that there are pending translations on kata which a viewing user has not solved. It would still 403 when the link is followed, but there would be at least a hint that there's some potentially easily fixable kata with a pending fix which can be solved right away and get the bugfix merged.
- Would it be possible to see whether a translation is mergeable or not? This would allow to easily recognize translations which require a closer review and effort to fix due to merge conflicts, outdated language versions, broken tests, etc.

Since the view is not visible to general users it does not need to be really pretty, I am thinking about documenting it anyway. It does not have to have full-blown UI (at least initially), operating on URL parameters is a good tradeoff between usability and difficulty of implementation.

**Comment by Madjosz** [comment]
Additionally a language filter would be nice since currently it is only linked to "trained languages".

**Comment by ejini6969** [comment]
IMO
i) Filter for draft / retired / beta / approved translation can be added or group retired and beta into one criteria called "unsalvageable" 
ii) Yes, filter by rank should be added
iii) Filter by language should be on the list too ! Therefore, one does not need to constantly switching trained language in the profile settings.
iv) Ability to see if a translation has merge conflicts / up-to-date language version benefit a lot to maintainers but not sure what parameters should be used to distinguish thoo
v) Not sure about the ability to see translations on unsolved katas. Would that be spoiling the solution or tests? If not (just displaying the list of pending translations), then that should be fine !

**Comment by hobovsky** [comment]
Filter by languages is available by adding URL params: `languages=lang1,lang2,lang3` or `all`.

**Comment by kazk** [comment]
> Translations to retired kata and drafts are shown, which, I think, is not necessary.

I'll hide them by default.

> A bit more details could be presented, like, for example, kata rank or beta/approved.

I'll add the rank/beta hex.

> New translations could be somehow differentiated from forks with fixes, which would make it easier to introduce and merge bug fixes to kata. 

I'll add options to filter them.

> It could be useful to see that there are pending translations on kata which a viewing user has not solved.

It should be shown with [`all=true`](https://www.codewars.com/kumite/translations?all=true).

> Would it be possible to see whether a translation is mergeable or not? This would allow to easily recognize translations which require a closer review and effort to fix due to merge conflicts, outdated language versions, broken tests, etc.

- merge conflicts: No. Need to check for conflict whenever a kata changes, and keep this status in some field to query with.
- outdated language versions: Should be
- broken tests: Translations published with broken tests should be excluded already

**Comment by kazk** [comment]
I felt like doing some UI, so I added a filter drawer.

![image](https://user-images.githubusercontent.com/639336/184468909-36b5a5d6-ff26-4d82-b696-776aa73683e3.png)

Example listing translations for betas only:

![image](https://user-images.githubusercontent.com/639336/184468917-8d6532d6-7f81-49d6-b4d5-601d117e64f4.png)

- :sparkles: next to the language icon means it was forked from kata to update
- :heavy_plus_sign: next to the language icon means a new translation. (Note: this is WIP and currently listing anything not forked from kata. I'm planning to a field to translation indicating if it's a new translation that I can query.)
- `Invalid Version` badge means the version is no longer valid
- `Outdated Version` means it's not using the latest version of the language
