### ISSUE TITLE
Improve syntax highlighting of Solidity

### ISSUE THREAD

**Issue by XRFXLP** [codewars/codewars.com#2772]
It appears that Solidity syntax is highlighted as that of JavaScript:

![image](https://user-images.githubusercontent.com/23459568/184562876-92edb39e-dd3a-4c20-b7aa-f2421bcdc7ca.png)

for the contrast, this is code on remix - Ethereum IDE:

![image](https://user-images.githubusercontent.com/23459568/184562911-8c0400e0-cdb3-495d-8cac-1c2ff668b0e8.png)

### Expected Behavior: 

Highlighting of keyword should not be as per the language keyword set

**Comment by kazk** [comment]
The package has `codemirror` in `dependencies`, so it'll cause multiple `codemirror` in `node_modules` directory. It should be moved to `peerDependencies` with version `5.x`.

I'll open a PR.

**Comment by kazk** [comment]
Deployed using my fork for now. I don't know if that project is still maintained. If not, I'll create a new package under @codewars.
