### ISSUE TITLE
"Submit when ready" message after successful attempt shouldn't be shown for draft/retired kata

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#2777]
On a draft Beta kata, you can 'Train Again', but the button to 'Submit' never appears after a successful attempt, although it instructs the user to submit as it would regularly do. Either it's not possible to submit, in case 'Train Again' should not appear in the first place, or it should be possible to submit.

**Comment by Blind4Basics** [comment]
but as a matter of facts, you _can_ train again. You just cannot finish the training, sort of.

**Comment by nomennescio** [comment]
Yes, I can train again, but not submit, although it claims I can. Something is wrong here.

**Comment by nomennescio** [comment]
One of the two is true: either you can train and submit or you can't train and therefore not submit
Or maybe: if you can train, but can't submit, the website should not report that you can
but I think that's weaker and not to be preferred.

**Comment by Blind4Basics** [comment]
> Yes, I can train again, but not submit, although it claims I can. Something is wrong here.

might be worth to change the title to 'submit button shouldn't show up after an attempt on drafts", no?

**Comment by nomennescio** [comment]
> > Yes, I can train again, but not submit, although it claims I can. Something is wrong here.
> 
> might be worth to change the title to 'submit button shouldn't show up after an attempt on drafts", no? (or did I misunderstand the intent again?)

I'm not the judge of that. I can see both behaviors can be consistently defended, and I don't have a real preference in this.
If it's the intention to not let someone submit a second solution, than prevent the 'train again' button. If not, allow a second submission.

**Comment by nomennescio** [comment]
> Draft kata has never allowed submitting final. It's just that the recent beta process change to send katas to draft causes this to happen a lot more frequently.

If that's true, the 'Train Again' button should be removed.

**Comment by kazk** [comment]
"Train Again" button won't be removed because you can train again, and it's also necessary when reviewing draft kata.

The solution is not discarded. The unsubmitted solution should be there when you come back later, and you can submit when the kata is published.

> although it instructs the user to submit as it would regularly do.

![image](https://user-images.githubusercontent.com/639336/186802811-b84c9bf5-04c9-4f91-8b8b-3f1840c69bf7.png)

I can change this to something explaining you can't submit draft/retired.

**Comment by nomennescio** [comment]
> I can change this to something explaining you can't submit draft/retired.

Alright, thanks for clarifying the situation.

**Comment by hobovsky** [comment]
Point in case: https://www.codewars.com/kata/5a2b703dc5e2845c0900005a/discuss#6324604f2341c9004b0c18e4

**Comment by kazk** [comment]
Deployed
