### ISSUE TITLE
Display test cases in the order of appearance, consistently for all languages

### ISSUE THREAD

**Issue by Expurple** [codewars/codewars.com#2783]
Kata authors often order test cases from the easiest to the hardest. For a user, this is very convenient and allows to iterate and implement features step by step.

For some languages, such as Python, the test results are displayed in the same order as the tests are defined in the source code:

![python-source](https://user-images.githubusercontent.com/56318093/186909174-6063f9e2-b909-4a4a-8c13-be5506430ff4.png)

![python-displayed](https://user-images.githubusercontent.com/56318093/186909383-6928ae62-9c3b-43a2-8736-2cbb18466b94.png)

As I said, this is very convenient.

However, for some other languages, such as Rust, the test results are sorted alphabetically:

![rust-source](https://user-images.githubusercontent.com/56318093/186909671-36b0789a-bddd-4354-8eb9-31de7e27ddea.png)

![rust-displayed](https://user-images.githubusercontent.com/56318093/186909852-1540eaf9-539a-4ad7-96d8-1148c5b981ee.png)

So either users get a worse experience, or the author has to apply hacks like this:

![rust-hack-displayed](https://user-images.githubusercontent.com/56318093/186910203-44476ae9-1e9d-4745-bfc9-29243bdbb987.png)

**I suggest displaying tests in the order of appearance for all languages.**

I've originally intended to use C++ as a "bad" example, but apparently it's no longer alphabetically sorted. So maybe there's already some work in this direction and this is a duplicate issue.

Example screenshots are from [Ideal Trader](https://www.codewars.com/kata/610ab162bd1be70025d72261) editor view. The change should equally affect the trainer and the editor.

**Comment by hobovsky** [comment]
> I suggest displaying tests in the order of appearance for all languages.

This depends heavily on a testing framework, and is not easily possible to control from outside (i.e. by code runner)

- Some frameworks do no special processing and just execute tests as they encounter them in the code (Python)
- Some frameworks perform tests asynchronously (Mocha for JS, but I think it's disabled on CW)
- Some frameworks do some heavy managment of test classes and test cases and just decide on their own (NUnit?)
- Some frameworks execute tests concurrently and test report is created in order of reported progress, and not in order of execution (NUnit)
- In some frameworks, tests are in a bag which is not ordered in any way (JUnit tests are classes and test cases are methods, and classes and methods have no order of appearance, unless annotated explicitly)

So generally the notion of "order of appearance" is not even defined for some languages, or for some testing frameworks.

Having said that, programmers can often (not always tho) control the order of execution of tests in a framework-specific way. They just don;t bother. So I would say it's up to authors/translators to maintain consistency between languages, and use proper ordering of test groups, test cases, using proper annotations (`@Order`) for JUnit), etc.
