### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by EvanHsieh0415** [codewars/codewars.com#2807]
**Describe the bug**
When I log in, it shows 502 errors

**To Reproduce**
Login will show

**Expected behavior**
Login and use the service successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/74277414/189843188-3a205ec9-f744-4dc8-bd8d-af08605bf2c8.png)

**Browser**

- OS: Windows 10
- Browser Firefox
- Version 105.0b9 (64bit)

**Comment by kazk** [comment]
I'm looking into it. I don't see anything on our servers at the moment, so I'm guessing it has something to do with Cloudflare.

https://status.codewars.com

**Comment by Madjosz** [comment]
It might be a problem with Cloudflare so everybody will be affected. Please look at https://status.codewars.com/ to monitor the current status.

**Comment by EvanHsieh0415** [comment]
Cloudflare error too
![image](https://user-images.githubusercontent.com/74277414/189855153-75fbf49b-fefa-46a2-8180-0afa0aea09e6.png)

**Comment by EvanHsieh0415** [comment]
log in successfully
