### ISSUE TITLE
Can not open the Codewars website

### ISSUE THREAD

**Issue by yassinelshaiatany** [codewars/codewars.com#2809]
Dear Codewars Team,

I'm Student Programmer

In this week I trained for some katas for python but today when I opened the website it shows me 5xx: Server Error

In the normal the expected behavior is to open my account dashboard or my last kata that I trained

Screenshot of what happened
![image](https://user-images.githubusercontent.com/84511001/189860808-7f6e5e34-4407-46de-952c-b0ff5bbebe83.png)

I'm using Chrome Browser

- OS: Windows
- Browser Chrome
- Version 105.0.5195.102

**Comment by Madjosz** [comment]
Duplicate issue of #2807
Please look for already existing issue before opening a new one.

**Comment by yassinelshaiatany** [comment]
Ok Thanks!
