### ISSUE TITLE
On submit "Failed to send to server. Check your internet connection" but connection is fine

### ISSUE THREAD

**Issue by ScientificProgressGoesBoing** [Codewars/codewars.com#281]
On submit "Failed to send to server. Check your internet connection" but connection is fine.

http://www.codewars.com/kata/54e6533c92449cc251001667/train/ruby
All tests on "Run tests" passed before hitting submit. 
Logged in and can access next kata. 
Tried reset and tried again, same failure to send to server message.

**Comment by crazymerlyn** [comment]
Does reloading the page fix the problem? See #154.

**Comment by ScientificProgressGoesBoing** [comment]
I found some script still being blocked, and now it works. Sorry. (Thanks for replying.)
