### ISSUE TITLE
Raising a question/issue/suggestion while filters are active causes posted comment to be hidden

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2810]
Let's say I'm raising a question while the filter is set to "issues". After posting the question, the comment is sent but it's not shown because it's filtered. This causes a very undesirable effect where I can't see the comment I just posted, and will easily think the comment was not posted. (Yes, the numbers in the filter widget have changed, but that's very unnoticable.)

**Comment by kazk** [comment]
Fixed by updating the filter to match the new comment when necessary.
