### ISSUE TITLE
[Kata search page] The search engine is close to unusable

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2813]
Since the last change about the search engine of the kata page, this feature became close to unusable to me, compared to what it was.
As far as I can tell:
- it uses exact syntax checks
- associating words lead to a lot less results than expected. Are spaces separated words considered a `AND` instead of a `OR`?
- bug that led me here... Using `.` to show space chars:
  - `binary.tree`, with `All languages`: 14 results
  - `binary..tree`, with `All languages`: 0 results
 => well...

Before this update, finding kata was already very hard, very often. Now, it's a nightmare, and a google search is more efficient, I believe...

**Comment by Blind4Basics** [comment]
> The update only changed the UI, so it's been like this for a while.

I remember a time when I could search for kata authors, tho, and I _believe_ approximate match was working (not sure tho... I bet on my memory playing me again... x) ). Well, the search engine never did miracles anyway...

> It's AND and the order matters. 

Couldn't we at least get a OR, like any normal search engine? (maybe quotes support to bypass the OR behavior??)

**Comment by kazk** [comment]
> I believe approximate match was working

It used to when we used Elasticsearch. I had to migrate away from it quickly because of an incident we had that caused the site to break for a few days. I knew it wasn't as good, but not significant enough to justify the more complex setup. It's been like a year.

> Couldn't we at least get a OR

Yeah, I can do that.

**Comment by kazk** [comment]
Deployed
