### ISSUE TITLE
Completed kata should not be in search results for "Kata I have not completed"

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#282]
The "Double Char" kata, which I have completed multiple times, is showing up in my kata search results for: http://www.codewars.com/kata/search/javascript?q=&r[]=-8&r[]=-7&xids=completed&beta=false.  This search is filtered for "Kata I have not completed".
![search results](https://cloud.githubusercontent.com/assets/5090280/14441759/50ccf56a-0004-11e6-9519-cf9d6e9d3a07.PNG)
I completed this kata some time ago in Javascript and just recently again in Python.  This is reflected on my user page http://www.codewars.com/users/PaulCalvelage.
![progress](https://cloud.githubusercontent.com/assets/5090280/14441909/2a5d44f6-0005-11e6-82dd-a5442ba5a92b.PNG)

Here's what I think I may have done that led to this problem:
1. A while ago, I solved the kata for the first time and clicked 'Submit'.  I was prompted to take time to refactor & comment before submitting the final solution.  However, I have a vague memory that I did **not** submit it at that time.
2. Instead, I closed the browser window without logging off.
3. In a **different browser** I logged back in.  After that, the kata did not get updated as completed for search purposes no matter how many more solutions I submitted.  Also as I recall my first solution did not show up on http://www.codewars.com/kata/56b1f01c247c01db92000076/solutions/javascript after I sumbitted the final solution (the first time).  Subsequent solutions did show up.

My memory is a little sketchy on the details, since this was a little while ago and I just noticed that the search didn't update after doing it again in Python.  It's possible I'm not remembering the exact sequence of events that started the problem.  But it's definitely not being filtered properly in the search results at this point.

**Comment by paul-calvelage** [comment]
Update: I found at least eight (8) more completed kata that are showing up in search results for "Kata I have not completed":
http://www.codewars.com/kata/formatting-decimal-places-number-0
http://www.codewars.com/kata/do-something-n-dot-times-simplifying-for-loops
http://www.codewars.com/kata/leonardo-dicaprio-and-oscars
http://www.codewars.com/kata/grasshopper-object-syntax-debug
http://www.codewars.com/kata/days-in-the-year
http://www.codewars.com/kata/return-negative
http://www.codewars.com/kata/multiply
http://www.codewars.com/kata/broken-greetings

**Comment by paul-calvelage** [comment]
When I first posted this bug, I had a theory about what might have caused it.  Now after collecting more examples I have no clue.  

Apologies for being redundant, but in case you need more examples to help find the pattern, here are nineteen (19) more completed kata that are showing up in my "Kata I have not completed" search:

Search parameters: http://www.codewars.com/kata/search/my-languages?q=&xids=completed&beta=false&order_by=rank_id+asc

---
http://www.codewars.com/kata/semi-optional
http://www.codewars.com/kata/invalid-login-bug-fixing-number-11
http://www.codewars.com/kata/is-integer-safe-to-use
http://www.codewars.com/kata/improving-math-dot-round-x
http://www.codewars.com/kata/whats-up-next
http://www.codewars.com/kata/max-headroom-and-javascript-style
http://www.codewars.com/kata/simple-validation-of-a-username-with-regex
http://www.codewars.com/kata/strive-matching-number-1
http://www.codewars.com/kata/validate-code-with-simple-regex
http://www.codewars.com/kata/regexp-basics-is-it-a-digit
http://www.codewars.com/kata/whats-wrong-with-these-identifiers
http://www.codewars.com/kata/enumerable-magic-number-2-true-for-any
http://www.codewars.com/kata/regex-count-lowercase-letters
http://www.codewars.com/kata/is-the-string-uppercase
http://www.codewars.com/kata/take-an-arrow-to-the-knee-functionally
http://www.codewars.com/kata/fix-the-bugs-syntax-my-first-kata
http://www.codewars.com/kata/lario-and-muigi-pipe-problem
http://www.codewars.com/kata/remove-the-time
http://www.codewars.com/kata/did-she-say-hallo

**Comment by jhoffner** [comment]
Thanks for all of the info. This is probably also related to why completed kata sometimes come up within the next challenge section. I am working on some major updates to the code execution engine but will look into this afterwards.

**Comment by paul-calvelage** [comment]
The `App.data.completedCodeChallengeIds` array on the kata page is __*exactly*__ 1000 entries long, which makes me think that Balkoth's comment was correct in Issue https://github.com/Codewars/codewars.com/issues/37 that one cause for this is going over 1000 solved katas.  It gets worse the further over 1000 you get.

**Comment by paul-calvelage** [comment]
The "Double Char" kata was one of the first kata I completed on Codewars, and it was one of the first I noticed in the problematic search results.  It seems the completed kata are leaking into the search results in a FIFO manner now that I am over 1000 kata.

**Comment by kazk** [comment]
This should be fixed. See https://github.com/Codewars/codewars.com/issues/1739#issuecomment-491437011
