### ISSUE TITLE
Beta feedback buttons respond to clicks well outside their borders

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#283]
The beta feedback buttons respond to clicks well outside their borders.  This is quite surprising!
### How to reproduce:
1. Complete a beta kata.
2. Rank the kata by clicking one of the buttons beneath the question "How difficult do you think this kata is?"
3. Click on one of the bullet point items within the description that subsequently appears below the button.

**Expected behavior**: Clicking on the text below the button should not do anything, since it is not within the borders of the button.  Specifically, a user should be able to use the mouse to highlight the text within the bullet points without activating the button.

**Buggy behavior**: Clicking on one of the bullet point items below the button has the same effect as clicking within the borders of the button; it cancels the difficulty ranking, causing the description to disappear and the button to no longer be highlighted.  The user cannot use the mouse to highlight the text within the bullet points without inadvertently activating the button.

![beta ranking](https://cloud.githubusercontent.com/assets/5090280/14515105/958fd0d4-01c4-11e6-8aae-3cf07474e7e9.PNG)
Source: http://www.codewars.com/kata/565adf1bf8d70b663900003b/solutions/javascript

**Comment by kazk** [comment]
Fixed
