### ISSUE TITLE
Changed GitHub username, can not sign in or up with a new account

### ISSUE THREAD

**Issue by rocco-muscaritolo** [codewars/codewars.com#2832]
**Describe the bug**
I changed my GitHub username and now I can no longer sign into my existing CodeWars account, nor can I sign-up as a new user.

When I try and sign-up for a new account and click "Link GitHub account", I get a 500 internal server error.
`Request ID: x-request-id: 8e1e460b-8beb-4412-b816-2c26d3d169fe`
```
cache-control: no-cache
cf-cache-status: DYNAMIC
cf-ray: 7589829bfedf1869-EWR
content-type: text/html; charset=utf-8
date: Tue, 11 Oct 2022 18:03:03 GMT
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
referrer-policy: strict-origin-when-cross-origin
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=R3m1W8wyF60Dlu%2FOARWCW20YmvJ5Nc3ZNJc6L%2FjYhIBAbEknMVe3YBDMtl0ufhnAo847f1SeMiNAHemSbEu%2FVyTcVnQGHOlsFYg3KFjxO5b6qK4CMPEosti3ept07eZ%2Fizc%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
set-cookie: CSRF-TOKEN=p6Myw4dMe%2BAuChc5QOei36vJbndbo%2Bek3Rfah4sVrVpcuQw78NfkJzV5OVx3XBGNnePJh6WDu%2FTvaoej5SCbeA%3D%3D; path=/; SameSite=Lax
set-cookie: _session_id=113a4ae541de8c9198daf1555f95707e; path=/; expires=Fri, 14 Oct 2022 18:03:03 GMT; HttpOnly; SameSite=Lax
via: 1.1 google
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 8e1e460b-8beb-4412-b816-2c26d3d169fe
x-runtime: 0.664850
x-xss-protection: 1; mod
```

The result URL is:  https://www.codewars.com/users/auth/github/callback?code=8c02238b569691f9d66c&state=43f9bbbc20c4ffbda202e7d4fdc8dd0324a8d4d10081637e

**To Reproduce**
Link an existing GitHub account, change the username, try to sign in or sign-up.

**Expected behavior**
Either my existing CodeWars account should update its GitHub username after it changes.  Or I should be able to signup with a new account after my GitHub username has changed.

Account UUIDs should be independent of usernames or emails.

**Screenshots**
<img width="600" alt="Screen Shot 2022-10-11 at 2 08 29 PM" src="https://user-images.githubusercontent.com/510742/195167116-4974cebb-2312-44a1-baa4-542450655ab8.png">

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
> Link an existing GitHub account, change the username, try to sign in or sign-up.

We don't use GitHub username to sign in, so username change should be irrelevant. We use GitHub user id to find the associated user.

> I can no longer sign into my existing CodeWars account

What's your Codewars username?

**Comment by rocco-muscaritolo** [comment]
> What's your Codewars username?

CaptBeardie

**Comment by kazk** [comment]
User https://www.codewars.com/users/CaptBeardie doesn't exist

**Comment by rocco-muscaritolo** [comment]
I signed up by using my GitHub account, which was formerly, "CaptBeardie".

<img width="389" alt="Screen Shot 2022-10-11 at 3 10 26 PM" src="https://user-images.githubusercontent.com/510742/195178583-858dd1e4-3135-45ec-86d8-e5c117699214.png">

**Comment by kazk** [comment]
I'm confused now. Did you change Codewars username or GitHub username?
"CaptBeardie" doesn't exist on Codewars. Changing a GitHub username doesn't affect Codewars in any way. Unless you also changed Codewars username or deleted the account, this doesn't make sense.

I can look up a user by email address if you email us at info@codewars.com with a title `GitHub issue #2832`. You can also post your email address here if you don't mind.

**Comment by rocco-muscaritolo** [comment]
Yes, as per the subject line. "Changed GitHub username, can not sign in or up with a new account"

I did not change or delete my CodeWars account. I Signed up through my GitHub account.

I'll email you there.

**Comment by kazk** [comment]
Looks like you changed your Codewars username to match your GitHub. https://www.codewars.com/users/rocco-muscaritolo

That account is not linked to GitHub, though. I don't know what happened.

You can sign in by using password reset, and linking it again from Account Settings.
