### ISSUE TITLE
Kumite for Sass doesn't appear listed

### ISSUE THREAD

**Issue by javatlacati** [codewars/codewars.com#284]
I created the following Kumite:

* http://www.codewars.com/kumite/570fe170d7601912c80012cd?sel=570fe170d7601912c80012cd

but it doesn't appear listed on the kumites list neither when I filter by language.

Thank you in advance.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1eb5) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Closing because Sass kumite is not supported.
Adding support for CSS+HTML is tracked by https://github.com/codewars/runner/issues/21
