### ISSUE TITLE
The name of the Github account does not change after changing it

### ISSUE THREAD

**Issue by TheAwiteb** [codewars/codewars.com#2850]
My old username is `Awiteb`, after I changed it to `TheAwiteb` it didn't change on [codewars.com](https://codewars.com)

My profile: [Awiteb](https://www.codewars.com/users/Awiteb)

**Comment by kazk** [comment]
I don't think there's a way for us to detect when you change your GitHub username. You should be able to unlink and link in Account Settings to update.

**Comment by TheAwiteb** [comment]
> I don't think there's a way for us to detect when you change your GitHub username. You should be able to unlink and link in Account Settings to update.

I am afraid that it will create a new account for me, and then I can not go back to the old account

**Comment by kazk** [comment]
You can still log in with your GitHub account because username is irrelevant for that.

**Comment by Madjosz** [comment]
You can change your Codewars username in your account settings to whatever you want (unless it is already used by another user). It doesn't have to line up with your GitHub username.

**Comment by TheAwiteb** [comment]
I confirmed my email, then unlink the account from the Codewars and relink it
