### ISSUE TITLE
Some completed kata are not included in profile and honor point totals (maybe ranking too)

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#286]
My profile page (http://www.codewars.com/users/PaulCalvelage/completed) claims that I have completed 1,083 kata.  However, a `grep` count of the completed kata on the same page puts the total at 1,128.  The http://www.codewars.com/users/PaulCalvelage/site-events page also has the count at 1,083, which may mean that my honor point calculation has been incorrectly calculated by omitting 45 kata.  This may or may not be affecting the ranking calculation as well--I don't have enough information to know.

**Background**: I have been doing some testing of the kata search.  My strategy has been to make use of the website normally, save the HTML source, and then run a `grep` search to hunt for inconsistencies or clues.

``` bash
grep -Eo '<a href="/kata/[^"]*">[^<]*</a>' completed.html | cat -n > completed.txt
```

Here's a list of the 1,128 kata I have completed, according to my profile: https://drive.google.com/file/d/0B57YN95qmy_fOE04NkIyWThaQWM/view?usp=sharing

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
