### ISSUE TITLE
Author unable to see translations, even when linked directly

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#288]
Usually an author cannot see one of my translations, but it can complete the approving process if I feed him/her the direct link.

This does not seem the case for [this kata](http://www.codewars.com/kata/how-many-stairs-will-suzuki-climb-in-20-years/).

Translations are regularly visible, forkable and of course editable by me:
![image](https://cloud.githubusercontent.com/assets/4815731/14609674/d17d689c-0582-11e6-8b4c-85811a9c58c3.png)

**Comment by rollietikes** [comment]
I am able to see both translations under the "+" tab but when I try to select either of them I get the 500 error. I also receive a 500 error when selecting the direct links provided by GiacomoSorbi in our discourse. 

Uh oh! Something went wrong! (500)

We have taken note of the situation and will be looking into it. We are still a beta product.

If you would like to supply us with some details as to how this happened please Email Us. This will help us get things fixed faster.

**Comment by rollietikes** [comment]
This still has not been corrected and Giacomo worked hard on translating the Kata into Javascript and Ruby. Will someone please try to resolve the issue so the translations can go live?

**Comment by jhoffner** [comment]
Not really sure I understand what the issue was but I was able to approve both translations for you. Thanks for letting me know.

**Comment by jhoffner** [comment]
I'll leave this open so that I can investigate further later.

**Comment by Steffan153** [comment]
This does not appear to be happening anymore -- maybe close it?
