### ISSUE TITLE
Python match/case keyword syntax coloring.

### ISSUE THREAD

**Issue by CommanderQuack** [codewars/codewars.com#2884]
It's not a huge deal, but I think it would be nice to have `match` and `case` show up in purple.

Thanks.

**Comment by CommanderQuack** [comment]
Alrighty, I've opened it 👍

**Comment by CommanderQuack** [comment]
The PR has been approved. I don't know if you need to update anything, but [here it is](https://github.com/codemirror/codemirror5/pull/7014).

**Comment by kazk** [comment]
Cool, I'll update when the new version is released.
