### ISSUE TITLE
I tried to log in using my github account in the link https://www.codewars.com/users/sign_in , and it said invalid github account. However, I did signed up with my github. My user is AlbertoF13.

### ISSUE THREAD

**Issue by AlbertoF13** [codewars/codewars.com#2895]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by kazk** [comment]
[AlbertoF13](https://www.codewars.com/users/AlbertoF13) doesn't have GitHub account associated with it. Maybe you accidentally unlinked it? To fix this, you need to use password reset to sign in, then link your GitHub again from Account Settings.

**Comment by kuchaguangjie** [comment]
I have the same error, I did unlink, I just tried to login on a new computer.
