### ISSUE TITLE
The "Sort by" dropdown for Kata has white text and a white BG.

### ISSUE THREAD

**Issue by XigenMatt** [Codewars/codewars.com#29]
Chrome 41 windows.
See attached screenshot.

![codewars-dropdown](https://cloud.githubusercontent.com/assets/6813852/7028126/c263f11a-dd4b-11e4-8cdf-0c424379a35f.jpg)

**Comment by paul-calvelage** [comment]
I can reproduce this on IE and Edge as well; these browsers show a white background for me:
* Chrome 50 (Windows 10 and Ubuntu 14.04)
* IE 11 (Windows 10)
* Edge 25 (Windows 10)

Firefox 46 on Windows 10 and Ubuntu 14.04 displays a black background.
