### ISSUE TITLE
Completed Kata is not showing as completed and no points were awarded

### ISSUE THREAD

**Issue by mattcollier** [Codewars/codewars.com#290]
http://www.codewars.com/kata/number-of-permutations-without-repetitions/solutions/javascript

I have completed this Kata, but I received no points, and the check mark indicating completion is not displayed.  However, I can view solutions and I can even see 'my solution'.

My profile name is mattcollier.

**Comment by jhoffner** [comment]
Sometimes things take a while in the background if the queue gets backed up. Did this ever resolve itself?
