### ISSUE TITLE
CW-310: No honor for referrals

### ISSUE THREAD

**Issue by MIC132** [codewars/codewars.com#2923]
**Describe the bug**
I seem to be getting no honor from my referrals.
The people in question confirmed their emails and have finished some Katas.
My username is MIC132

I don't miss those points too much, but it's quite clearly a bug unless I'm missing something major.

**To Reproduce**
Go to my profile and check honor
https://www.codewars.com/users/MIC132

**Expected behavior**
I should receive 3 honor per referral up to 5 and then 1 per (according to what's on the site)
Thus I should have 9 referral honor.

**Screenshots**
![image](https://user-images.githubusercontent.com/5782727/215358648-82fb6b4b-d349-4a12-9c09-af2a27aaaaa5.png)
![image](https://user-images.githubusercontent.com/5782727/215358707-b9e5493e-5bac-41c4-b230-b2366668ed69.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows
- Browser: Vivaldi
- Version: 5.6.2867.62

**Comment by VanessaGreene** [comment]
This issue has been escalated to the Codewars engineering team, we hope to have a fix for this issue soon.

**Comment by VanessaGreene** [comment]
Hi @MIC132, this issue has now been resolved, and I'm happy to inform you that your referral points have been updated on your Codewars account. Thank you for flagging this issue for us.
