### ISSUE TITLE
Some profile tooltips incorrectly use 2nd person point of view instead of 3rd person

### ISSUE THREAD

**Issue by paul-calvelage** [codewars/codewars.com#294]
When I am on somebody else's profile page, some of the tooltips refer to that person's accomplishments using the second person point of view, such as: "View all kata that **you** have successfully completed".  This is wrong, since I did not successfully complete these kata; Nancy27 is the user who completed the kata on her profile page, not me.  It should say, "View all kata that **Nancy27** has successfully completed".  Some of the tooltips correctly use the third person, so it is inconsistent.

![profile](https://cloud.githubusercontent.com/assets/5090280/14938571/f84a5c4c-0ef5-11e6-98c6-842e1ad64e81.png)
Source: http://www.codewars.com/users/Nancy27

As it stands, the "social" tooltips correctly use the third person, whereas the "kata" and "discourse" tooltips incorrectly use the second person.  Here's what I am seeing as I hover over each link on Nancy27's profile page:

| Link | Tooltip |
| --- | --- |
| Kata: Completed | View all kata that **you** have successfully completed |
| Kata: Unfinished | View all kata that **you** have started but have not yet completed |
| Kata: Authored | View all kata that **you** have authored |
| Social: Following | View all users that **Nancy27** is following |
| Social: Followers | View all users that are following **Nancy27** |
| Social: Allies | View all users that are both being followed by and follow **Nancy27** |
| Discourse: Conversations | View all comments that are related to **your** activity |
| Discourse: Replies | View all replies to comment threads **you** have started |
| Discourse: Authored | View all comments that **you** have created. |
| Discourse: Needs Resolution | View all open issues, suggestions and questions to kata **you** have authored |

The period in the Discourse > Authored tooltip is also inconsistent with the others, which have no period.

**Comment by kazk** [comment]
Fixed
