### ISSUE TITLE
Forked translations ignore version change on first save

### ISSUE THREAD

**Issue by Kacarott** [codewars/codewars.com#2948]
When forking a translation/fork to update it, the first time "Save" is pressed, the language version is reverted to match its parent. For content maintainers this means that they must remember to update the language version *again* after saving, and before publishing.

**To Reproduce**
Fork any translation with an out-of-date language version, update the language version, make a trivial code change to allow saving, and press save. The language version will be reverted.

**Comment by kazk** [comment]
Should be fixed
