### ISSUE TITLE
The display order of programming languages should be consistent

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#295]
The order in which programming languages appear next to a kata is inconsistent across the website.  I suggest consistently listing the kata languages in order of translation date.

**What I Like:** The profile and search pages, as well as the "similar kata" section of the kata page use an ordering (apparently) based on the order in which the translations of the kata were made.  

The first language icon in the list is the original language, which is useful to know when making general comments, issues, or suggestions.  It helps me to understand the intent of the author in following paradigms, best practices, etc. of a particular language.  Ironically, the one place where this ordering is not used is the kata page where the discourse is taking place.  So I suggest using this ordering consistently across the website and making the original language and history of the kata translations even more explicit somehow.

**What I Don't Like:** The top of the kata page uses a completely different ordering, which is a fixed subset of JavaScript, CoffeeScript, Ruby, Haskell, Python, Clojure, Java, and C# in that order.  Not only is this inconsistent with the other pages, but as I mentioned the translation order would be very useful to see on the "discourse" page.

**Example:** The "Especially Joyful Numbers" kata was apparently created in Ruby, and subsequently translated to Python and JavaScript.  This is the ordering used on the search and profile pages.
http://www.codewars.com/kata/search/my-languages?q=especially+joyful+numbers
![search](https://cloud.githubusercontent.com/assets/5090280/14938974/9c34f3e6-0f03-11e6-8ca7-1e85c9be36e4.png)
http://www.codewars.com/users/Abelard_Snazz/authored
![profile](https://cloud.githubusercontent.com/assets/5090280/14938975/a2e077a6-0f03-11e6-96c6-e27159b3d076.png)
However, the kata page uses a fixed ordering where JavaScript always comes first, if it is present:
http://www.codewars.com/kata/especially-joyful-numbers
![kata](https://cloud.githubusercontent.com/assets/5090280/14938971/94e2f570-0f03-11e6-8ced-041a12b1d3b1.png)

**Comment by kazk** [comment]
Closing this because the order is consistent now.


![image](https://cloud.githubusercontent.com/assets/639336/26533131/a7b04d7e-43c8-11e7-9502-7729d85a697c.png)

![image](https://cloud.githubusercontent.com/assets/639336/26533138/ba26e260-43c8-11e7-982b-0e91f52f85f2.png)
