### ISSUE TITLE
Incorrect error output

### ISSUE THREAD

**Issue by prisfma** [Codewars/codewars.com#296]
I was resolving kata [Format a string of names like 'Bart, Lisa & Maggie'](http://www.codewars.com/kata/53368a47e38700bd8300030d) with the following code:

```
function list(names) {
   return names.map(function(obj) {
        return obj.name;
    }).join(', ').replace(/(.*),(.*)$/, "$1 & $2");
}
```

And the message said it expected "Bart, Lisa, Maggie, Homer & Marge" but got "Bart, Lisa, Maggie, Homer & Marge", which I checked that both were actually the same.

It misleaded my troubleshooting and I didn't find that it should be `.replace(/(.*),(.*)$/, "$1 &$2")`, so I ended up solving another way due to that bug.

**Comment by jhoffner** [comment]
I'm not sure what is happening here. Is this kata specific or an issue with the Code execution? If its code execution related please log a bug here https://github.com/Codewars/codewars-runner-cli.
