### ISSUE TITLE
I can't submit the kata whatever I do

### ISSUE THREAD

**Issue by pdinger1** [codewars/codewars.com#2961]
When I run the code everything runs fine, but it just goes until it times out on purpose and then the submit button doesn't show up

**To Reproduce**

def is_square(n):
   
    if(n == 0):
        return True
    elif(n < 0):
        return False
    for num in range(1, n):
        if(n/num == num):
            return True
        elif(num == int(n/2)):
            return False

**Expected behavior**
It should give true or false for if the number is a perfect square

**Screenshots**
![Screenshot 2023-03-10 162908](https://user-images.githubusercontent.com/127565647/224440162-933b6e31-6d19-4ee6-8d04-2817b55cc1a8.png)

**Browser**
Tried on both Chrome and Edge (newest versions)

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by JohanWiltink** [comment]
Your code is _hugely_ inefficient, and submit tests rightly time it out. This is not a Codewars issue, it's ( at best ) a kata issue, which you can raise on the discourse page of the kata itself.
