### ISSUE TITLE
Unit tests pass automatically on any error

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#297]
For Java, JUnit4 tests pass automatically when error is launched even with `trycatch`. You can take for example [this Kata] (http://www.codewars.com/kata/proficient-classic-hello-world/solutions) where Merlyn solution should not pass at all.
The testing pattern that if launches any exception fails the tests can't be used.

**Comment by jhoffner** [comment]
Thanks. Please re-file this issue and optional submit a PR to https://github.com/Codewars/codewars-runner-cli
