### ISSUE TITLE
Request Error: Network Error

### ISSUE THREAD

**Issue by SkynI25** [codewars/codewars.com#2976]
**Describe the bug**
When I try to suggest the solution, I got this error.

**Request Error:
Network Error
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.**

**To Reproduce**
https://www.codewars.com/kata/514b92a657cdc65150000006/train/javascript

**Expected behavior**
Should have to execute the code

**Screenshots**
![image](https://user-images.githubusercontent.com/20556561/228704369-96d93477-abb9-4393-9a74-e78e0a1bbad3.png)
![image](https://user-images.githubusercontent.com/20556561/228704500-86adc79e-1d34-4aa2-aed5-6e06670ebc99.png)

**Browser**
Chrome

- OS: Windows
- Browser: Chrome
- Version:  111.0.5563.111

**Additional context**
I think certification has expired. Might be helpful little bit..?

**Comment by kazk** [comment]
Fixed
