### ISSUE TITLE
Lost honor issue

### ISSUE THREAD

**Issue by OKitel** [codewars/codewars.com#2982]
**Describe the bug**

I had around 1.4k honor the day before yesterday, today I have only 753 honor. It's not the first time when I notice an honor deduction. I didn't receive any notifications from codewars.

I'm curious where all that honor went... Is it a bug? Is it collateral damage from an update? Is it a punishment for cheating?
This is very disappointing because I almost ranked 3 kyu.

Could you explain, please?

**To Reproduce**

See my account https://www.codewars.com/users/rsschool_c4c9da14c9c87710/site-events

**Screenshots**

![image](https://user-images.githubusercontent.com/79774026/230730324-03fc4b4d-689b-4304-91e2-d00de1ba01a9.png)

**Browser**

- OS: Windows
- Chrome

**Comment by OKitel** [comment]
I noticed something strange. I'm sure that I solved yellow tasks as well, but I don't see any honor awarded for them on my [site-events](https://www.codewars.com/users/rsschool_c4c9da14c9c87710/site-events) page. There are only points for blue and white.

![image](https://user-images.githubusercontent.com/79774026/230730987-b8d16c30-6736-44e1-a4e1-dce2a9c0f89e.png)

**Comment by Blind4Basics** [comment]
Hello,

Earning honor is based on actually solving the kata, not hunting solutions on the internet. So a lot of your solutions got invalidated, hence the decrease.

Cheers
