### ISSUE TITLE
Upgrade to Clojure 1.8

### ISSUE THREAD

**Issue by nrakochy** [Codewars/codewars.com#299]
Getting this error on compiling- 
    
    java.lang.RuntimeException: No such var: string/last-index-of

I think this was added in Clojure 1.8 - [docs](https://github.com/clojure/clojure/blob/722e023ea00b27a47b11afc29fa7fe0a282696f4/src/clj/clojure/string.clj#L339)

For sake of reference, `string/blank?` compiles fine.

**Comment by jhoffner** [comment]
Please submit a PR or issue to https://github.com/Codewars/codewars-runner-cli
