### ISSUE TITLE
Unable to Cancel CodeWars Red Subscription - Subscription Edit Page Errors on load

### ISSUE THREAD

**Issue by IntegerMan** [codewars/codewars.com#2993]
**Describe the bug**
Going to CodeWars.com on mobile (Android) or desktop (Win 11 Edge) to manage an active CodeWars red subscription generates a 500 internal server error web page for my user at URL https://www.codewars.com/subscription/edit

**To Reproduce**
1. Log in
2. Click on your profile picture, then `Account Settings`
3. Scroll down to `Red Subscription` and click `Manage`
4. Observe error page

**Expected behavior**
Not this. I should be able to see my active subscription and successfully cancel it.

**Screenshots**
![image](https://user-images.githubusercontent.com/5049957/232647207-c1f6964a-6887-43f0-bf16-4b944c0032dd.png)

**Browser**
Multiple. Observed most recently in Edge 112.0.1722.39

- OS: Win 11
- Browser Edge
- Version 112.0.1722.39

**Additional context**
This bug occurs consistently and is preventing me from cancelling an active subscription that will charge me again should I be unable to cancel it.

My CodeWars profile page is at https://www.codewars.com/users/IntegerMan

**Comment by kazk** [comment]
Deployed a fix. Please try again and let me know.

**Comment by IntegerMan** [comment]
Still broken for me even after signing out and back in. I'm happy to try again tomorrow if you think it might take time to propagate.

**Comment by kazk** [comment]
Yeah, looks like I misunderstood the root cause. I guess you used https://stripe.com/payments/link to subscribe. This wasn't a supported payment method when our code was written, so it's failing to handle the unexpected value returned from Stripe.

I'll let you know when a fix is deployed.

**Comment by kazk** [comment]
Deployed. Let me know if this works.
If not, I'll look into it again tomorrow.

**Comment by IntegerMan** [comment]
Thank you for the prompt iterations. It worked just fine! I appreciate your help.
