### ISSUE TITLE
Landing page freezes Ubuntu using Firefox

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#3]
Firefox (Version 36.0.4 | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0) almost freezes on Ubuntu 14.04 if I visit the front page (not the dashboard, but www.codewars.com without being logged in).

(Originally filed on CW by bkaes)

**Comment by jhoffner** [comment]
@bkeas is this reproducable or was it a one time thing?

**Comment by bkaes** [comment]
It happened at least three times, Wednesday, Thursday and Friday. I usually open Firefox in private mode, so it needs to redownload all files and I need to sign in. 

At this point, the browser freezes completely, till Firefox recognizes the problem and asks whether the script should continue or whether the execution should be canceled. Unfortunately, I don't have access to the critical machine till monday. I'll try tomorrow with FF 36 on Win 8.1 with a similar configuration (Core2Duo, ~4GB RAM).

The current PC doesn't have this problem (Win 8.1, FF 28; Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0), so it might be machine specific.

**Comment by bkaes** [comment]
I managed to get a similar error on the [feature request](http://www.codewars.com/topics/feature-requests) page with a borrowed netbook (Win 7, FF 28; Mozilla/5.0 (Windows NT 6.1; WOW64; rv:28.0) Gecko/20100101 Firefox/28.0; Asus Eee PC; AMD E-350 1.6 GHz, 4 GB RAM). The original dialog message:

> Ein Skript auf dieser Seite ist eventuell beschäftigt oder es antwortet nicht mehr. Sie können das Skript jetzt stoppen oder fortsetzen, um zu sehen, ob das Skript fertig wird.

> Skript: http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:14

Roughly translated:

> A script on this page is broken or doesn't respond. You can stop or continue the execution to check whether the script finishes:

> script: http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:14

I think this kind of freeze/lock usually only happens on pages with many DOM elements, such as the feature request page.

**Comment by jhoffner** [comment]
OK. Yeah the Feature Reqeusts page makes more sense. Its kind of a mess right now. The landing page is a bigger concern, that shouldnt be a heavy page.

**Comment by bkaes** [comment]
Firefox definitely freezes a little bit on my current machine (Notebook from 2009; Core2Duo T6500 @ 2x2.1GHz, 4GB RAM, Win 8.1 [64bit]). The network analysis showed that http://cdn.mxpnl.com/libs/mixpanel-2.1.min.js took the most time, but that could be due to the hickup of ~3-5 seconds. 

I just noticed that the console shows the following message right after the browser gets responsible again:

> too much recursion www.codewars.com:3

Unfortunately, I can't check the `profile.json` generated by the profiler (Firefox takes forever to show it), but a simple codewars loading page rendering in private mode generates a ~5MB profile, so there might be something up. I'll definitely post the profile generated by the first machine on Monday.

**Comment by bkaes** [comment]
I'm now back at the first machine (the one where Firefox freezed), this time using Windows 7. Firefox hangs for two seconds, during a DOM event (event logging) that happens after `DOMContentLoaded`.

Again, the errors message "too much recursion" gets logged the same moment Firefox gets responsible again. The [generated profile is again ~5MB](https://gist.github.com/bkaes/cfc0e6b8e788d377b7fb) (gist) and cannot be inspected in Firefox :/.

**Comment by bkaes** [comment]
Did you change something? The page doesn't freeze anymore on with the first configuration (FF 36, Ubuntu 14.04), the profile.json shrank to ~4MB (-1MB), and the previous ~2second DOM event went down to ~42ms. I'll try again later, but so far the issue seems to be gone.

**Comment by jhoffner** [comment]
I updated the intercom library yesterday. That may have been the issue. I'm fairly certain its caused by a 3rd party library but haven't gotten a chance to look into it yet.

**Comment by bkaes** [comment]
> I updated the intercom library yesterday. That may have been the issue.

It still happens from time to time, but I can't really provide a reliable way to reproduce this behaviour, except

1. clean cache (or start private browsing session) in FF,
2. visit www.codewars,
3. repeat step one if nothing happened on step two.

I haven't tried any other browser, so it might be FF specific.

**Comment by bkaes** [comment]
It also happens in IE (IE11, 11.0.9600.17690 on Win8.1x64) occasionally:

![slow-codewars](https://cloud.githubusercontent.com/assets/6301773/6993637/f761fa22-dafa-11e4-859a-cc2117e2a864.png)

> [Rough translation] A script with long execution time prevents that "codewars.com" reacts.

Additionally, the tab crashed when I tried to cancel the execution. This can be reproduced by simply visiting "www.codewars.com".

**Comment by bkaes** [comment]
Still happens in FF and IE on the front page. Additional, when one tries to hook up the browser's debugger, the debugger freezes completely (tested in FF).

**Comment by bkaes** [comment]
The (small) freeze also happens on kata's with many comments, as http://www.codewars.com/kata/550f22f4d758534c1100025a/discuss#554068a05b88f1d903000051 has just passed the freeze threshold.

**Comment by ariscop** [comment]
I'm having a similar problem in iceweasel 37 on debian
```
Error: Script terminated by timeout at:
jQuery.wait@http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:31:7770
t@http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:32:7376
t@http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:32:8392
t@http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:32:8392
t@http://d3l8wp33uu8nxs.cloudfront.net/assets/application-db8e9b5e11a53a89c5eb849aec5970dc.js:32:8392
```

**Comment by ariscop** [comment]
Solved at my end by disabling adblock, can't explain why though since it only seems to block analytics and facebook. Might not be the same bug.

**Comment by bkaes** [comment]
Still happens occasionally. No idea why. AdBlock is deactivated on CodeWars, but I'm also using disconnect.me

**Comment by bkaes** [comment]
\*Bump\*: Just happened on Windows 7 Home Premium, using Firefox 38.0.5.
