### ISSUE TITLE
Javascript Person Constructor

### ISSUE THREAD

**Issue by tadwhitaker** [Codewars/codewars.com#30]
I’m trying to pass the second lesson on the Javascript test to register. It’s the one where it uses the Person(name) construction.

1. There is nothing that says the expected names are Kate and Joe/Jane. That only becomes obvious with an error message.
2. If I set name = Joe, it errors and says it was expecting Jane. If I set name = Jane, it errors and says it was expecting Joe. This happens every single time in Chrome even after shutting down the browser and reopening it. And, it happens in Safari too.

**Comment by jhoffner** [comment]
Sounds like you are having an issue passing the challenge. I just tested and there is nothing wrong with the actual system. 

To give you a hint. There is nothing that specifically expects Joe/Jane/Kate, etc. Those are just values passed in by the tests.

**Comment by tadwhitaker** [comment]
Ah, got it. Okay, I’ll try it again. So sorry about this, but that error message makes me think that it was expecting those specific values!


Regards,


Tad Whitaker
Whitaker & Co.
1388 Haight Street, #143
San Francisco, CA 94117
(415) 602-8468
PI# 26458




Drone stuff: facebook.com/candlestickrobotics



NOTICE:  This e-mail (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. §§ 2510-2521, is confidential and may contain client materials and/or work product. This e-mail is intended only for the addressee named above.  If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution, or copying of this communication is strictly prohibited. Please reply to the sender that you have received this message in error, then delete it and any and all copies of it. Thank you.
