### ISSUE TITLE
Solution tab opens with "You have not earned access to this kata's solutions Solutions are locked for kata ranked far above your rank. Rank up or complete this kata to view the solutions." message after kata submit

### ISSUE THREAD

**Issue by vmred** [codewars/codewars.com#3002]
**Describe the bug**
After kata submit and rank increased page with solutions opens with "You have not earned access to this kata's solutions
Solutions are locked for kata ranked far above your rank. Rank up or complete this kata to view the solutions." message

**Preconditions**
- Have at least 8kyu rank.

**To Reproduce**
- Write solution for any kata (8kyu f.e. https://www.codewars.com/kata/59441520102eaa25260000bf)
- Click on Test button
- After tests passed click on Attempt button
- After tests passed click on Submit button

**Solution**
<details>
<summary>Spoiler</summary>
return len('hello')
</details>

**Expected behavior**
Solution tab opens with other solutions.

**Actual behavior**
Solution tab opens with "You have not earned access to this kata's solutions
Solutions are locked for kata ranked far above your rank. Rank up or complete this kata to view the solutions." message
<img width="1377" alt="image" src="https://github.com/codewars/codewars.com/assets/16134967/797eb3d1-fdad-4913-a6f9-4d2ec2585026">

**Screenshots**
<img width="802" alt="image" src="https://github.com/codewars/codewars.com/assets/16134967/f4632752-e2bd-4c1a-a2cf-67ad0507d01e">

<img width="1370" alt="image" src="https://github.com/codewars/codewars.com/assets/16134967/f79b298b-1e51-4d89-8c58-220f403dccd8">
<img width="889" alt="image" src="https://github.com/codewars/codewars.com/assets/16134967/e6efd726-0379-41e3-9304-8d23339f0b6d">

**Browser**
Chrome, 112.0.5615.137 version.

**Comment by Blind4Basics** [comment]
Not related.

You got several solutions invalidated yesterday, because you didn't author them. I'm pretty sure you noticed the honor/rank drop.
You did it again today. So it seem you didn't want to understand, so those solutions also got invalidated and your account got locked. What you currently see is one of the consequences of the lock.

Closing.
