### ISSUE TITLE
Working solution is not accepted by Kata

### ISSUE THREAD

**Issue by Diasell** [Codewars/codewars.com#302]
KATA: Sum of many ints
LANGUAGE: Python

MY SOLUTION:

```
def f(n, m):
    rest = n%m
    sum1 = (m*(m-1))/2
    sum2 = (rest*(rest+1))/2
    return sum1 * (n/m) + sum2
```

**Description**
Each time i run the code it gives me an random test failure and if i run  the same script locally on my machine i would get the correct result

Check the screenshots that i've attached to this issue:

![codewars_bug1](https://cloud.githubusercontent.com/assets/14127052/15071911/db76850e-1397-11e6-8733-aa5b507ccf4f.PNG)
![codewars_bug1_1](https://cloud.githubusercontent.com/assets/14127052/15071914/e0e22188-1397-11e6-9672-e888ff7c7471.PNG)

**Comment by kazk** [comment]
Next time, ask kata specific questions on kata discourse.

---

Your solution works using Python 2 (your PyCharm has `Python27`), but not Python 3.
You can fix this by selecting Python 2 on Codewars, or by using floor division (`//`) in Python 3.
