### ISSUE TITLE
List of completed languages in a translation editor is truncated and leaves many languages inaccessible

### ISSUE THREAD

**Issue by hobovsky** [codewars/codewars.com#3025]
When working on a new translation, left panel shows a kata reference with snippets of all unlocked languages. If there is many solved languages, only few of them are accessible:

100% zoom:

![image](https://github.com/codewars/codewars.com/assets/23709795/eaceb22d-7734-45c2-8053-a06b6dbbf35a)

50% zoom:

![image](https://github.com/codewars/codewars.com/assets/23709795/3cf02175-8e4d-4010-9d4c-aa3713a6dd4c)

**To Reproduce**
- Complete a kata in many languages
- Initiate new translation to the kata
- References of only few languages are accessible

**Browser**

- OS: Win11
- Opera

**Comment by VanessaGreene** [comment]
Escalated reference CW-101.

**Comment by hobovsky** [comment]
inb4 "fixed": can we have the tabs sorted, to ease searching for languages a bit?

![image](https://github.com/codewars/codewars.com/assets/23709795/d1f28d87-084c-4962-8fcc-05b5ce538683)

**Comment by VanessaGreene** [comment]
@hobovsky This has been resolved, please let me know if you encounter any issues with the update.

**Comment by hobovsky** [comment]
As I mentioned in the post just above yours: it would be very helpful if the tabs were ordered alphabetically. Currently, they are ordered by ID (and implicitly by date of completion), what makes finding a specific language unnecessarily dfficult:

![image](https://github.com/codewars/codewars.com/assets/23709795/73107578-27a4-45e7-98b3-a650b04e7088)

Thanks!
