### ISSUE TITLE
Training set up radio buttons enlarged?

### ISSUE THREAD

**Issue by Akshaybagai52** [codewars/codewars.com#3029]
**Describe the bug**
When I sign up in codewars via github then i'm seeing this page where I had to "Select the level that fits your coding ability based on the programming language you know the best." but the UI of the options look like as in attached mirror and also i'm not able to select any options in my pc i

**To Reproduce**
1. Sign up in codewars via github or email.
2. Then you will see this question
--What best describes your current programming skill level?
   Select the level that fits your coding ability based on the programming language you know the best.
_and in options the UI is looking broked and i'm not able to select any options in this

**Expected behavior**
As per developer of codewars

**Screenshots**
![image](https://github.com/codewars/codewars.com/assets/100753870/6c4c7280-e97d-41bb-b63c-5be31b3239fd)
![image](https://github.com/codewars/codewars.com/assets/100753870/8558f539-988a-49ac-8901-6828b5b4c000)
![image](https://github.com/codewars/codewars.com/assets/100753870/36fd283c-e0b3-431f-9b45-2952ab0ac607)

**Browser**
Chrome

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**

**Comment by VanessaGreene** [comment]
Hi @Akshaybagai52 thank you for flagging this, we have recently updated our sign-up flow and training settings, can I ask you to head to your training setting page and tell me if this issue persists?
