### ISSUE TITLE
output does not work

### ISSUE THREAD

**Issue by titzelle** [Codewars/codewars.com#303]
When I run  test, I have just the message correct or incorrect but nothing appears in the window : not the tests or the console.log. Nothing !!!
I have tried to reload my browser and to change browser. It did not fix the issue.
When I restart my computer, it works for a while and then breaks again.
please help me. I really love and need these katas !

**Comment by jhoffner** [comment]
Is this still happening? Without repro steps I am unable to do anything about this. Thanks.
