### ISSUE TITLE
Selecting 3.8 for Python version in trainer might select 3.11 instead

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#3035]
There are 3 options for Python version:

![image](https://github.com/codewars/codewars.com/assets/14909989/971ab6bd-5ba9-4bc6-9985-9f275e00ca24)

In some katas, like [this kata](https://www.codewars.com/kata/64c5886e24409ea62aa0773a), when selecting 3.8 *after selecting 3.10 or 3.11* the first time it'd select 3.11 instead. Only the second time it'll become 3.8.

**Comment by VanessaGreene** [comment]
Hi @Voileexperiments Thank you for flagging this, I have escalated this to the team and hope to have an update for you soon. 

Escalated ticket reference CW-100.

**Comment by VanessaGreene** [comment]
Following up on this ticket
