### ISSUE TITLE
submit button not showing up

### ISSUE THREAD

**Issue by Hanane2023** [codewars/codewars.com#3041]
I do solve some exercise and click on test and its all correct but the submit button  doesn't show up and i end up just skipping to move on to the next challenge  any suggestion i have windows 10 and I'm working on chrome i tried to open it on edge still the same problem  any suggestion
![Capture](https://github.com/codewars/codewars.com/assets/137444697/15d01355-ba35-4f27-bb26-6ecf05692280)

**Comment by Kacarott** [comment]
Are you pressing "Attempt"? The "Test" button just runs the sample tests. Once your code passes those, you need to press the "Attempt" button in order to run the full tests. If those also pass, then the "Submit" button will appear.

**Comment by Hanane2023** [comment]
> Are you pressing "Attempt"? The "Test" button just runs the sample tests. Once your code passes those, you need to press the "Attempt" button in order to run the full tests. If those also pass, then the "Submit" button will appear.
its works thank you so much
