### ISSUE TITLE
Internal Server Error reported when submitting simple string matching function.

### ISSUE THREAD

**Issue by cj-rupp** [Codewars/codewars.com#3046]
I'm new to Codewars. As mentioned above, I got an Internal Server Error, when trying to submit a simple function involving string matching. This was repeated 3 times, before I thought I might as well report something.

I'm starting with simple finger exercised in JavaScript, but I expect to be able to do more later. 

I didn't save anything to file, but this was (all) the code I was trying to submit.

```
function getCount(str) {
  const vowelMatches = str.match(/[aeiou]/g);
  return (vowelMatches) ? vowelMatches.length : 0;
}
```

I do test, then attempt (all good), and then I hit SUBMIT, wait a while, and then get the error message back.

I don't have a screenshot. 

I'm using firefox (116.03), under Windows 11(Home 22H2) on WiFi

I think that's all I know. I hope this is just a transient blip, but I would like to know if I'm doing anything (inadvertently) wrong.

Thanks a lot.

C. J.

**Comment by hobovsky** [comment]
What kata is it? If you mean [Vowel Count](https://www.codewars.com/kata/54ff3102c1bad923760001f3/discuss), I tried to run your code and encountered no problems. Does the problem still persist on your side? If yes, is it possible to have a screenshot?

**Comment by BDubOne** [comment]
> I'm new to Codewars. As mentioned above, I got an Internal Server Error, when trying to submit a simple function involving string matching. This was repeated 3 times, before I thought I might as well report something.
> 
> I'm starting with simple finger exercised in JavaScript, but I expect to be able to do more later.
> 
> I didn't save anything to file, but this was (all) the code I was trying to submit.
> 
> ```
> function getCount(str) {
>   const vowelMatches = str.match(/[aeiou]/g);
>   return (vowelMatches) ? vowelMatches.length : 0;
> }
> ```
> 
> I do test, then attempt (all good), and then I hit SUBMIT, wait a while, and then get the error message back.
> 
> I don't have a screenshot.
> 
> I'm using firefox (116.03), under Windows 11(Home 22H2) on WiFi
> 
> I think that's all I know. I hope this is just a transient blip, but I would like to know if I'm doing anything (inadvertently) wrong.
> 
> Thanks a lot.
> 
> C. J.

This is exactly what happened to me. Also, my solution was nearly identical.

**Comment by VanessaGreene** [comment]
Hi @cj-rupp and @BDubOne, are you still encountering this issue? If so can you please name the katas it occurred on and provide screenshots or a screen recording of the issue?

**Comment by VanessaGreene** [comment]
@cj-rupp please let me know if this issue is still present.

**Comment by BalaM314** [comment]
Same error when submitting this code:
```js
function solution(n){
  //Math goes brrrr
  const a = 3, b = 5, ab = a * b;
  if(n < a) return 0;
  let numA = Math.ceil(n / a);
  let sumA = a * numA * (numA - 1) / 2;
  let numB = Math.ceil(n / b);
  let sumB = b * numB * (numB - 1) / 2;
  //Remove double counts
  let numAB = Math.ceil(n / ab);
  let sumAB = ab * numAB * (numAB - 1) / 2;
  return sumA + sumB - sumAB;
}
```

**Comment by hobovsky** [comment]
> Same error when submitting this code:

@BalaM314  could you show a screenshot of the error you get?

**Comment by BalaM314** [comment]
Not getting it anymore, but it had the header "Internal Server Error" on a prettily formatted webpage, and below it it said that "we have been notified and are looking into it" or something like that
