### ISSUE TITLE
Honour fell down

### ISSUE THREAD

**Issue by ArnaBannonymus** [Codewars/codewars.com#3049]
I am arnab1998 . My honour fell down by 1000. please check it.

**Comment by hobovsky** [comment]
As explained in [this post](https://github.com/codewars/codewars.com/issues/1498#issuecomment-1698102947):

> > My honour fell down too . Can it be fixed? Please let me know... Username: arnab1998
> 
> Please do not reuse old threads which are already fixed and closed. Your issue is totally unrelated to the original topic of this thread.
> 
> Your points were taken away because many of your solutions for difficult kata were copies of solutions of other users. The best way out of this situation is to delete the current account, create a new one, and use it to submit only your own solutions, not copied from other users, and not copied from web.
> 
> Please create a new ticket if you want to discuss the matter further.

Answering the follow-up question:

> Can it be recovered for the codes of mine only .please

I don't think this will happen. No one knows which solutions are yours, and no one is going to spend time to evaluate all solutions and check which might be honest, and which are not. Starting from scratch will be just easier.

**Comment by Blind4Basics** [comment]
not an issue.
