### ISSUE TITLE
I can't publish a Kata

### ISSUE THREAD

**Issue by MrPlazmaDude** [Codewars/codewars.com#305]
I finished up my first Kata tonight. I wrote all the functionality, test cases and a detailed description. I titled it, tagged it and then verified the solution. Everything checks out until I click publish. It goes through the process of validating the solution then kicks out, clears the solution and test cases then displays two errors at the top: Initial Solution can't be blank and Test Fixture can't be blank. Publish also switches to un-publish even though it's never actually published. When clicking un-publish, it reloads the page without any styles and displays "Uh oh! Something went wrong! (500)."

I can reload it via the switch Kata menu and try again but it's always the same problem. My apologies if this is a duplicate but I couldn't seem to find anything related my experience. I attached a screen shot of the error messages.

Thanks

<img width="1226" alt="screen shot 2016-05-13 at 9 23 57 pm" src="https://cloud.githubusercontent.com/assets/1680432/15265959/dc49f474-1951-11e6-9b00-ce6cc55a28d9.png">

-Edit: Not sure if this is related, but there are a couple warnings in the console:

<img width="1015" alt="screen shot 2016-05-13 at 9 36 48 pm" src="https://cloud.githubusercontent.com/assets/1680432/15265988/deb252d2-1952-11e6-9315-2ebe1ced7fe6.png">

**Comment by bkaestner** [comment]
Possibly related: #248.

**Comment by MrPlazmaDude** [comment]
Thanks, I'll try starting a new one. Getting out of sync does seem to fall in line with some of the other behaviors I have been noticing. After I click publish, the complete solution is replaced with a really old revision of the code and the text cases seem to be working but not always as expected.

**Comment by MrPlazmaDude** [comment]
I copied everything over to a new one and it published just fine. I guess without knowing any more I will chalk it up to #248 

Cheers.

**Comment by MrPlazmaDude** [comment]
Closing since it's related to another issue.
