### ISSUE TITLE
After having changed the account's email address, the original address is still sent to Stripe for subscribing

### ISSUE THREAD

**Issue by interrupt-routine** [Codewars/codewars.com#3053]
Long ago I modified the email address associated with my account. I recently upgraded to Codewars Red. On Stripe's checkout page, the 'E-mail' field was pre-filled with the original email address that I used to open my account, instead of the current one. Moreover, this was a readonly HTML field. I edited it anyway via the inspector, but I'm not sure whether this was properly registered by the form, because I did not get a confirmation email at my current address, despite the subscription successfully taking effect. Unfortunately I cannot check whether I received anything at the old address, because I lost access to it after a drive failure.

**Expected behavior**
The current email address should be sent to Stripe.com when subscribing to Red.

**To Reproduce**
I guess create a new account, change the email address, and check which address shows up on Stripe when trying to subscribe.

**Comment by VanessaGreene** [comment]
Hi @interrupt-routine I will look into this, do you mind emailing info@codewars.com referencing this issue number so I can check your personal details and update your details?

**Comment by VanessaGreene** [comment]
@interrupt-routine has this issue been resolved?

**Comment by interrupt-routine** [comment]
I don't think there is anything specific to my account here - the Red subscription registered correctly on my Codewars profile, so I cannot subscribe again.

It should be easy enough to check if the bug can be replicated:

1. create a new codewars account
2. change the email address associated with the account
3. start the procedure to upgrade to Red
4. check which email address is sent to `stripe.com` on the checkout page:  the original one or the new one.

If you cannot replicate the bug (i.e. the email address is the new one), then you can close this issue as not reproducible in clear conscience.
