### ISSUE TITLE
CW-99: Counter of pending issues on search page is outdated

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#3054]
As a workaround for a [missing feature](https://github.com/codewars/codewars.com/issues/932) I wanted to scrape the search result for kata with pending issues. Unfortunately, it turns out that the numbers displayed on the search page are most probably cached and severely outdated. For example, the kata  [Convert string to camel case](https://www.codewars.com/kata/517abf86da9663f1d2000003) has 51 issues in its whole discourse, 5 of them is still pending, but the summary shows 19 pending issues:

![image](https://github.com/codewars/codewars.com/assets/23709795/1e5f39ad-dad7-42c2-af89-bca13eb724d4)

While the #932 is in backlog and waits for its turn, would it be possible to update the numbers reported by search, or know what to do to trigger update of the numbers?

**Comment by VanessaGreene** [comment]
Escalated to CW-99.

**Comment by VanessaGreene** [comment]
@hobovsky as this was escalated I will mark it as closed here and update you when it has been actioned.
