### ISSUE TITLE
Non-CW favicon displayed in some places

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#3057]
Initially reported [on Discord](https://discord.com/channels/846624424199061524/846624870187401227/1130798176937459743):

HTML of Codewars page references an icon which is not Codewars logo, but is fetched and shown by some tools:

![image](https://github.com/codewars/codewars.com/assets/23709795/5194eada-465b-44a2-afed-95500f33d87c)

![image](https://github.com/codewars/codewars.com/assets/23709795/7be9026b-aaba-48e7-bf24-8782e71cac5f)

`Unnamed` found it referenced in HTML as:

```text
<link href="https://uploads-ssl.webflow.com/img/webclip.png" rel="apple-touch-icon" />
```

**Comment by VanessaGreene** [comment]
Escalated on Jira - 13 Sept 2022

**Comment by kazk** [comment]
Should be fixed
