### ISSUE TITLE
Vim Mode -- mixing auto-indented spaces and manual tabbing

### ISSUE THREAD

**Issue by shelltr** [Codewars/codewars.com#306]
This mainly affects Python for me. During Vim mode, when I go to a new line the editor will auto indent with spaces. Whenever I try to indent with tabs I get actual full-sized tabs, which gives me an error for mixing spaces and tabs.

This does not happen when not using Vim.

**Comment by aresti** [comment]
I'm also experiencing the same.

**Comment by sunjay** [comment]
+1

**Comment by aztlan2k** [comment]
+

**Comment by anilpai** [comment]
👍

**Comment by dustinbrown** [comment]
+1

**Comment by UncleGoogle** [comment]
+1

**Comment by treyhunner** [comment]
I'm also experiencing this issue

**Comment by kazk** [comment]
I made a [comment](https://github.com/Codewars/codewars-runner-cli/pull/305#issuecomment-279846194) about this when I was adding Go. It's also difficult to notice this until the code is submitted because a tab and 2 spaces looks the same in the editor.

**Comment by kazk** [comment]
This should get deployed today.
Resolved by adding `CodeMirror.keyMap['vim-insert'].Tab = 'insertSoftTab'`, disabling hard tabs aligning with other key mappings.
