### ISSUE TITLE
C# Katas fails to run

### ISSUE THREAD

**Issue by dgoldaraz** [Codewars/codewars.com#308]
Any time I tried to run the tests or submit a solution I got "No tests were provided" or "Unknow error"

**Comment by g964** [comment]
I confirm that. I always get  "No tests were provided" or "Unknow error" or "Nope! Try again."

**Comment by g964** [comment]
With Coffeescript impossible to translate : "Waiting for results...".

**Comment by MiloszKrajewski** [comment]
Confirming. Most (all?) kata I was doing recently with C# return "No tests provided" on "Run Tests" and "Unknown error" or "Submit".

**Comment by g964** [comment]
As far as I know C# and Coffeescript are running.

**Comment by jhoffner** [comment]
I fixed another issue which seems to have resolved this as well. I am closing.
