### ISSUE TITLE
Total Kata Count

### ISSUE THREAD

**Issue by SimiGold1** [Codewars/codewars.com#3082]
I have completed 30 kata. yet total completed kata is 13. Username is SimiGold

**Comment by Madjosz** [comment]
Please note that the values on your user profile page https://www.codewars.com/users/SimiGold are cached and are only refreshed every x amount of time. [Tab "Kata" -> "Completed"](https://www.codewars.com/users/SimiGold/completed) should show the latest value and I can see 17 kata there. Where do you get the 30 from?

**Comment by VanessaGreene** [comment]
Hi @SimiGold1 I can see that you have completed 74 kata. If you are still having issues seeing your katas please let me know.
