### ISSUE TITLE
Equal operator overload bypasses all tests

### ISSUE THREAD

**Issue by IvanVZabrodin** [Codewars/codewars.com#3083]
**Describe the bug**
If you make a class with only a overloaded `==` operator, which always returns `True`, you can bypass any kata that use `assertEqual`.

**To Reproduce**
For example, python:
```python
def solution(a, b):
    return TrueEq()

class TrueEq:
    def __init__(self):
        pass
    
    def __eq__(self, b: int):
        return True
```
This bypasses all `assertEqual` tests by returning `True` for all the tests

**Expected behavior**
It should do a opposite check (e.g. `expected == actual` instead of `actual == expected`)
This should theoretically work on all languages that have operator overloading and do not have type constraint `==` (e.g. `===` in JS)

**Comment by Blind4Basics** [comment]
yes, this is called the `eq cheat`. As in, cheating. This is a "won't fix" for many reasons, discussed in several threads already ([see here](https://github.com/codewars/codewars.com/issues/2179#issuecomment-644977083), for example

Are you CreoCode? Suggestion: don't use that. Accounts using this several times are banned. The cheats got flagged.

**Comment by Blind4Basics** [comment]
side note: checking the opposite doesn't change anything in python (because the interpreter might try the reverse operation on failure)
