### ISSUE TITLE
CW-169: Creating a user with the ".js" suffix extension causes errors in the loading of the profile page's CSS.

### ISSUE THREAD

**Issue by hobovsky** [Codewars/codewars.com#3092]
### Discussed in https://github.com/codewars/codewars.com/discussions/3091

<div type='discussions-op-text'>

<sup>Originally posted by **anabergerr** October 26, 2023</sup>

When creating my user using .js at the end, I noticed that the CSS of the page doesn't load. This only happens when I use .js.

Here's a screenshot of the page and the link.

https://www.codewars.com/users/ana.js

![image](https://github.com/codewars/codewars.com/assets/89489383/ca92f62e-98d8-4fae-9a82-ac9e44daed47)
</div>

**Comment by VanessaGreene** [comment]
This has been escalated to engineering (CW-169)
