### ISSUE TITLE
Process was terminated. It took longer than 10000ms to complete

### ISSUE THREAD

**Issue by nikitaneo** [Codewars/codewars.com#31]
I've been getting "Process was terminated. It took longer than 10000ms to complete" errors on any java code I try to run. How can I fix it?
![image](https://cloud.githubusercontent.com/assets/6105093/7054425/ff66985c-de44-11e4-9011-c96f2aa612b8.png)

**Comment by bkaes** [comment]
On _any_ Java code, or only on this specific kata?

**Comment by nikitaneo** [comment]
Oh, i`m sorry. I optimize my solutions and now its ok.
