### ISSUE TITLE
Can't cancel Red subscription

### ISSUE THREAD

**Issue by novikovdv** [Codewars/codewars.com#3113]
**Describe the bug**
Hey! I'm trying to cancel my Red subscription through Brave browser (also I tried to cancel through Chrome, but error remains), but for some reason can't do it. I saw exactly the same error earlier, but I thought it will be fixed. Link: https://www.codewars.com/subscription/edit

**Screenshots**
<img width="808" alt="Снимок экрана 2023-12-07 163954" src="https://github.com/codewars/codewars.com/assets/113970241/3106b9db-6fa5-43dc-9bac-53b7c300322f">

**Browser**
Brave

- OS: Windows 11
- Browser:  Brave
- Version: v1.60.125

**Comment by VanessaGreene** [comment]
Hi @K1ngFish, please email infor@codewars.com with your email address and username. Our support team will be able to help with subscriptions :)

**Comment by novikovdv** [comment]
Hi! I received message that this email address is not found @VanessaGreene

**Comment by hobovsky** [comment]
I think it should be `info@codewars.com`

**Comment by novikovdv** [comment]
That's works, thank u guys

**Comment by VanessaGreene** [comment]
Thank you for fixing that @hobovsky
