### ISSUE TITLE
Internal Server Error when changing Red subscription

### ISSUE THREAD

**Issue by SimpleEnigma88** [Codewars/codewars.com#3126]
I've been trying for two week to change my payment method for my Red subscription and it keeps giving an Internal Server Error page.
![image](https://github.com/codewars/codewars.com/assets/17863123/c077ee9f-2745-4597-af0c-0048b481f002)

**Comment by Madjosz** [comment]
From the Andela announcement in Codewars Discord server:
> If you do experience issues with Codewars over the holidays, please get in touch with info@codewars.com.

**Comment by VanessaGreene** [comment]
@SimpleEnigma88 has your subscription issue been resolved?

**Comment by SimpleEnigma88** [comment]
I ended up deleting my account, which effectively resolved it, lol.I hated doing that, I wanted to come back to Red in a couple of months.On Feb 9, 2024 12:11 PM, Vanessa ***@***.***> wrote:
@SimpleEnigma88 has your subscription issue been resolved?

**Comment by VanessaGreene** [comment]
Please refer to issue [3139 ](https://github.com/codewars/codewars.com/issues/3139) for further updates.
