### ISSUE TITLE
How  can I easily get my API key to make api calls to pull in my code solutions in other projects I have? 

### ISSUE THREAD

**Issue by MarkSchemmer** [Codewars/codewars.com#3132]
@kazk, How can I get my codewars api key so I can make an api call and get my solutions? 

If that exists why is it not included in the documentation?

**Comment by zPointless** [comment]
there is no api key

**Comment by zPointless** [comment]
Also, you can't get your kata solutions from the API.

**Comment by kazk** [comment]
We don't have an API to retrieve your solutions. I think there's a feature request filed for it, but it's not currently on our roadmap.

Also, there's no key because all officially supported endpoints are public (see https://dev.codewars.com/#authentication).
