### ISSUE TITLE
CW-225: want to cancel subscription, but have such issue 

### ISSUE THREAD

**Issue by faceless121212** [Codewars/codewars.com#3147]
![Снимок экрана 2024-01-21 223956](https://github.com/codewars/codewars.com/assets/96148344/dbb37940-a94d-4aff-b74d-357b0e631941)

**Comment by hobovsky** [comment]
Could you please send an email to `info@codewars.com` with information that you want to cancel your subscription? I notified admins about your issue and someone should take a look at it at the beginning of the week, but I think it will be easier for them when you send them an email.

**Comment by VanessaGreene** [comment]
Thank you @hobovsky, for directing this to support. @faceless121212 I'm sorry you encountered this issue, we are currently investigating this error, and I hope to have an update for you shortly.

**Comment by chrisrandledev** [comment]
I am still getting this issue when trying to view my Red Subscription page. I'm annoyed as I've been paying for months and not using this Red account.  £19 a month is a lot and if I didn't know better I would say this issue was being left in on purpose.

**Comment by VanessaGreene** [comment]
Hi @chrisrandledev, we are aware of this bug and our team are actively working on an updated solution as we speak. In the meantime, please email info@codewars.com today and our support team will cancel your subscription. We are sorry that you've had a negative experience in updating your subscription, this isn't our intention. Can you please add further information to your support email regarding your last bills and this amount sounds incorrect for a monthly subscription.

**Comment by chrisrandledev** [comment]
Sure I will do. Thanks for the prompt response
________________________________

**Comment by VanessaGreene** [comment]
Please refer to issue [3139](https://github.com/codewars/codewars.com/issues/3139) for further updates.
