### ISSUE TITLE
"Your Rank Progress" not enough lines for all used languages...

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#315]
All in the title

**Comment by paul-calvelage** [comment]
When you say "not enough lines"...  Is the last language overflowing the box on your profile page?  Or is it obscured?  Do you have a screenshot?

I have tried a lot of languages on mine and it looks OK.  I have lines for "Overall", Clojure, CoffeeScript, C#, Haskell, Java, JavaScript, Python, and Ruby.  I haven't done any of the new TypeScript or Elixir kata yet, though.  Maybe 1 or 2 more languages would be enough to put me over the edge.  I'll check later.

**Comment by jhoffner** [comment]
A short-term fix has been deployed, which is to just add scrollbars when the languages overflow. The section will need to be redesigned at some point.
