### ISSUE TITLE
Inability to approve certain Kata due to 500 error

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#316]
Yesterday I was just searching for beta Kata that were "Awaiting Moderator Approval" and approving them and I ran into this issue - although some Kata are "Awaiting Moderator Approval" (and perhaps for a long time), when I tried to approve them by clicking on "Approve/Edit Kata", a 500 error occurred and I cannot edit/approve the Kata.

I also noticed that this 500 error (when trying to edit certain beta Kata) is Kata-specific, that is, once a beta Kata is plagued with this bug, no matter how may times I click on "Edit/Approve Kata", the server will always respond with a 500 error rendering that particular beta Kata dead (even if it was very well-written and no issues were raised).

Some examples and screenshots:

http://www.codewars.com/kata/filling-an-array-part-1/

![2016-05-21 12 14 17](https://cloud.githubusercontent.com/assets/7777884/15446273/91dd3b88-1f4d-11e6-99eb-320f331d2aac.png)
![2016-05-21 12 15 08](https://cloud.githubusercontent.com/assets/7777884/15446275/ac3bcfee-1f4d-11e6-98d5-58d37c23a0d2.png)

http://www.codewars.com/kata/sum-and-length/

![2016-05-21 12 16 42](https://cloud.githubusercontent.com/assets/7777884/15446282/e4a69120-1f4d-11e6-873b-baea526a83d7.png)
![2016-05-21 12 16 56](https://cloud.githubusercontent.com/assets/7777884/15446283/ec408aa8-1f4d-11e6-9cd1-9a44da611cc1.png)

http://www.codewars.com/kata/sum-of-positive/

![2016-05-21 12 20 01](https://cloud.githubusercontent.com/assets/7777884/15446294/5ae5af74-1f4e-11e6-9541-63a7c2454773.png)
![2016-05-21 12 20 28](https://cloud.githubusercontent.com/assets/7777884/15446296/6afcb416-1f4e-11e6-83d7-824df032e15f.png)

**Comment by error256** [comment]
I'm not sure but I think it might happen if "Allow Contributors" has been turned off by the kata author because it's quite likely there are such katas but I've never seen a proper error message stating that contributors are not allowed..

**Comment by the-zebulan** [comment]
I'm not sure if it's related (I'm guessing it might be?) but when I try to just click `Edit Kata` on previously ranked katas, I'm getting the same 500 error. I wasn't planning on actually editing the ranked katas but just wanted to look inside a couple of them.

I've tried it on both `preview.codewars.com` and `codewars.com` with the same result. I was just about to make an issue but this one seemed to be so close I thought I would comment here first.

**Comment by suic86** [comment]
Another [kata]( https://www.codewars.com/kata/averages-of-numbers) with the same problem. :(

**Comment by tachyonlabs** [comment]
I saw some talk about this same issue in the discourse for a kata recently, and wondered whether this is why my "Resistor Color Codes" kata has been in the "Awaiting moderator approval" state for some weeks now: https://www.codewars.com/kata/search/my-languages?q=needs_approval&xids=not_completed

**Comment by jhoffner** [comment]
It looks like this issue is related to author's unselecting the "allow contributors" checkbox. After a certain period of inaction by the author to respond to a new issue, this checkbox doesn't have an affect - which is why it looks like eventually these kata were able to be approved.

**Comment by tachyonlabs** [comment]
As above, the first kata I wrote is still awaiting approval, but my second kata was approved with no problem quite a while ago. With both of them I have the "allow contributors" checkbox unchecked, but one difference between them that I suppose could possibly be affecting things is that with my approved one I had approved some translations by other people before it was approved, whereas my presumably-stuck one has not has any translations submitted by others yet.
