### ISSUE TITLE
I cannot log in via github, create a new account, or reset my password.

### ISSUE THREAD

**Issue by EvelynSays** [Codewars/codewars.com#3166]
**Describe the bug**
When trying to create an account, I linked my github account. It then asked me for an e-mail and proceeded to tell me that my e-mail was already in use. I requested a password reset which came through, but clicking the link takes me to the homepage. If I try to log in, it tells me I'm already logged in. If I click "Get Started" it asks me to link my email and a username to my github, but tells me both my emails are already in use.

**Expected behavior**
I should be able to log in via github or reset my password.

**Screenshots**
![image](https://github.com/codewars/codewars.com/assets/53948799/b2211299-c5dd-4510-ada1-7e456ad3863c)
![image](https://github.com/codewars/codewars.com/assets/53948799/0e2a48fe-ee38-4713-b6c4-95b1c6aba2b6)

**Browser**
Brave, Firefox.

- OS: [e.g. macOS]
- Chrome, Firefox
- Windows 11

**Additional context**
Any browser I try to fix the problem on gets softlocked.

**Comment by mitegab** [comment]
I think  you need to checkout your connection or any VPN problem.

**Comment by ahmedgamalna3em** [comment]
hello ms. / mrs. 'evelySays',  'mitegab' the site tell GitHub Successfully Linked and stop
and in the same screen when iam write again email to enter in the site not leaves
![cw](https://github.com/codewars/codewars.com/assets/81826582/8d5ebdf3-4854-4209-8205-336f899e56b9)

**Comment by VanessaGreene** [comment]
Hi @EvelynSays @ahmedgamalna3em,

Please try the following to recover access to your account:

- Clear all your cookies on Codewars ([here](https://www.hellotech.com/guide/for/how-to-clear-cookies-chrome-safari-mozilla-firefox-edge) is a guide to help you do this).
- Log out of GitHub, and clear your cookies for GitHub. 
- Open an incognito window in your preferred browser
- Head to GitHub in your incognito browser and log in.
- Head to codewars.com (in your incognito browser) and login via the GitHub option.

**Comment by Fifteefihve** [comment]
That didn't fix it for me. I even tried multiple browsers and different profiles in firefox
