### ISSUE TITLE
Editing a kata translation in a new language (Elixir) with more than 500 CW

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#317]
When a kata has been passed by more than 500 Codewarriors it is impossible to re-edit it. 
But it could be useful when it has just been translated in a new language (Elixir) and you need to make a few adjustements.

**Comment by bkaestner** [comment]
See also: [proposal for pull-requests](https://codewars.ideas.aha.io/ideas/CW-I-1), #123 (second post).

**Comment by g964** [comment]
Yes, proposal...proposal but nothing has been done about that since looonnng!

**Comment by jhoffner** [comment]
Description adjustments should be possible via the kata translation. What type of adjustments were you looking to make?

**Comment by bkaestner** [comment]
@jhoffner User translates old kata into new language &rightarrow; new language has some weird behavior (e.g. `AssertEqual` arguments swapped in Java/C#) &rightarrow; translation gets approved without checking &rightarrow; old kata has now wrong tests/issues that aren't resolvable.

**Comment by g964** [comment]
I translated a kata with more than 500 Codewarriors who passed into Elixir. After publishing I saw that my random tests cases were the same at each run (the seed was not re-initialized by Elixir) but I can't correct that because the tests are locked for all languages even if only 2 or 3 guys passed it in Elixir. I think the 500+ rule should be modified... Many proposals exist for that.

**Comment by jhoffner** [comment]
OK got it. I've got a fix, which is to apply the 500 limit on a per language level. It requires some denormalization so I want to do some more testing before pushing it out. Its been a long wait but its almost over.

**Comment by g964** [comment]
Excellent ! Very good for Elixir and Typescript! :-) 
What about the "disturbing" warnings in the new version of C#. Maybe it could be simple to suppress them?

**Comment by jhoffner** [comment]
I'll have to check into the disturbing warnings. I still haven't seen those in action. 

I finally converted the app from being heroku based to AWS based, and I have the preview environment up and running. https://preview.codewars.com

Preview has the latest updates to the 500 limit fix, so you should be able to make your updates over there. I'm going to be testing the new environment out for probably a week or so before switching www.codewars over to AWS. If you guys wouldn't mind using preview every so often to help me test, that would be great. 

One caveat. Preview is using a different leaderboard database, so your points may be out of sync temporarily between the two environments. Once everything is merged over the leaderboard will get itself back into sync so don't worry about losing your data.

**Comment by g964** [comment]
An example amongst many others by @Lunat1q: <http://www.codewars.com/kata/twice-linear/discuss#574866fb49a16777a400018c>. I was able to correct it since it is < 500+.

**Comment by jhoffner** [comment]
CW has been migrated over to AWS and everything in preview is now live. This issue should now be resolved.
