### ISSUE TITLE
Haskell timing out unexpectedly

### ISSUE THREAD

**Issue by holzensp** [Codewars/codewars.com#318]
I've tried the "Build a pile of Cubes" exercise in Haskell. It runs for over 6000ms, even on the given test program. That said, it _does_ seem to pass all the tests well inside that time bound. I tried adding the pragma `{-# OPTIONS_GHC -O3 #-}` which resulted in an error of `-O3` and `--interactive` not being compatible. Is it possible that the interactive session simply fails to close?

I tried it on my own system (GHC 7.10.3, but the difference is never that big on numerical stuff), with considerably larger problem sizes. Here's my code _with_ QuickCheck generators, so as to try it on very large cases:

```

import Test.QuickCheck

prop_knownGood = forAll knownGood $ \(n,s) -> findNb s == n

prop_random = \s -> s >= 0 ==> let n = findNb s in (n*(n+1) `div` 2)^2 == s || n == -1

knownGood :: Gen (Integer, Integer)
knownGood = do
  o <- abs <$> arbitrary
  n <- (^(o :: Int)) . abs <$> arbitrary
  return (n, ((n*(n+1)) `div` 2)^2)




isqrt :: Integer -> Maybe Integer
isqrt n
  | n' * n' == n = Just n'
  | otherwise = Nothing
  where
  n' = go n

  sq :: Integer -> Integer
  sq k = k * k

  powPairs = let pows = iterate sq 2 in zip (1:pows) pows

  go :: Integer -> Integer
  go m = case m of
      0 -> 0
      1 -> 1
      _ -> head
           $ dropWhile outOfRange
           $ iterate (\k -> div (k + div m k) 2)
           $ go (div m lowerM) * bound
    where
    ((bound, lowerM):_) = dropWhile ((m <) . snd) powPairs
    outOfRange r = sq r > m || m >= sq (r+1)
    
findNb s
  | even r    = r `div` 2
  | otherwise = -1
  where
  r = maybe 1 id $ do
    s' <- isqrt s
    dr <- isqrt (s' * 8 + 1)
    return (dr - 1)
```

It passes 100 tests every time well under 6000ms, even with verbose checking (where all the inputs are printed to stdout), it takes around five seconds for one hundred tests with inputs as large as, for example:

```
1829936310740550619478634271657009218686914636960963702989913351953813881942127338423881307894849929473544151614834247404938506888810393593366621025097555723795897391124788818946991834194962314686584228042794325414744581649801843090282941424423105215988256359531181510002960438214533285506122284021943255719018850334854844865348046099293754689877570602534954013462220597315257577777525556384257158551611059647639434961566932091226477261347923971921617129716202773576824154689946164590023569517163157387748656829856187810978696006714017130434513092041015625
```

**Comment by bkaestner** [comment]
> Is it possible that the interactive session simply fails to close?

Haskell tests run via `runhaskell`, see https://github.com/Codewars/codewars-runner-cli/blob/master/lib/runners/haskell.js.

**Comment by holzensp** [comment]
Well, running `time runhaskell PileOfCubes.hs` gives me this:
```
...
Passed:
(15624722518287446627037310616316692383878522699200314331,14900102713313998387505723863552291099526935617962570511666012910836780626183176689427264136042475476991620720145714508414687830070643213608886139986334682103628901740694903573835146498678407879690727793473038511484234916)
Passed:
(33825307664249166246182912,327270628601807819640997891134001774818558945236297606832306817364853884902683605394608240848571203584)
+++ OK, passed 100 tests.
runhaskell PileOfCubes.hs  1.49s user 0.12s system 93% cpu 1.724 total
```

1724 ms vs 6000 ms seems unlikely :(

**Comment by holzensp** [comment]
Okay, this may just be a server load issue... I even have this
```
module FromToStepGenerator where

generator :: Integer -> Integer -> Integer -> [Integer]
generator f t s = [f, f + signum (t-f) * abs s .. t]
```
taking more than 6000ms for 6 test cases.

**Comment by bkaestner** [comment]
Err, I just took your solution above, put it into the kata editor, removed all QuickCheck related stuff, and then submitted it:

> Process took 1537ms to complete

Did you try to resubmit it yet?

**Comment by holzensp** [comment]
It went through now. It seems to have been server-load related.
