### ISSUE TITLE
during submitting ,it is showing internal error 

### ISSUE THREAD

**Issue by Reemkhan09** [Codewars/codewars.com#3209]
after completing my test whenever i m trying to submit my test it is showing internal error what should i do how to fix it

**Comment by hobovsky** [comment]
What kata is this? In what language? Does the same problem appear for every kata, or only for some of them? Can you show a screenshot of the error? Does the problem appear on every attempt, or only sometimes?

**Comment by JosefinRobertsson** [comment]
This has happened to me a lot too the last few days. It doesn't always happen. It can happen not just when submitting a kata but also when doing other things like sorting the solutions. The personal stats are still updated (for me at least)

**Comment by patrickpiedad** [comment]
This issue just happened to me. Short description below:

- I completed "8 kyu Square(n) Sum" using Javascript.
- I tested my answer (successful), then attempted my answer (successful).
- I did not refactor my answer. I clicked on submit.
- The page immediately moved to the next page (which isn't common, it usually stays at the submit page for 5-10 seconds)
- The page was blank and stayed there for over 15 seconds. I scrolled up and down to see if it froze, then it gave the internal error
- I refreshed the page, and it went through. I was still given the honor points and the page refreshed to the proper solutions page.

*Note: I code my answers in my IDE (InteliJ Idea) and then copy-paste into the codeWars editor (this shouldn't affect anything but mentioned just in case)

Hope this helps!

**Comment by allan-bonadio** [comment]
Happened to me once, just now.  Only did 1 kata so far, this was it.  Python, the squared digits kata.  I edited all in the codewars window ide.  Finally got it right, tested and attempted, ok.  Then I went to do something, maybe 10min, 30min, dunno.  Then I thought, OMG I'm still on the timer!  so I clicked on Submit.  I went away again.  Came back, and it was showing that error.  Not sure if codewars remembers how long it took us, didn't see a timer.

**Comment by johanrex** [comment]
Same. Did some 6 kyu python 3.11 kata and submit results in internal server error.

**Comment by johanrex** [comment]
This Kata: "Stop gninnipS My sdroW" (https://www.codewars.com/kata/5264d2b162488dc400000001/train/python). 
Python 3.11. 

This code, when submitted gives internal server error:

```
def spin_words(sentence):
    words = sentence.split()
    for i, word in enumerate(words):
        if len(word)>=5:
            words[i] = word[::-1]
    return " ".join(words)

```

**Comment by eXp-virus** [comment]
Same here, ****everytime** I submit a solution** (no matter which kata the problem belongs to), I get internal server error. It's been happening since the past few days.

**Comment by Janarthanan6119** [comment]
For me too,its showing internal server error
![WhatsApp Image 2024-05-20 at 20 25 50_2eb9b7f6](https://github.com/codewars/codewars.com/assets/91175755/f5427d97-206d-4683-82a6-e43925e2f663)

**Comment by Janarthanan6119** [comment]
> For me too,its showing internal server error ![WhatsApp Image 2024-05-20 at 20 25 50_2eb9b7f6](https://private-user-images.githubusercontent.com/91175755/332106574-f5427d97-206d-4683-82a6-e43925e2f663.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjE3NDcsIm5iZiI6MTcxNjIyMTQ0NywicGF0aCI6Ii85MTE3NTc1NS8zMzIxMDY1NzQtZjU0MjdkOTctMjA2ZC00NjgzLTgyYTYtZTQzOTI1ZTJmNjYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2MTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YmIwMzdkMDBjYTgyOTE2ZDY5YTkyN2I5ZDI1NzMzYjQ1ODQ0OGYzZTgxNTZjNmYzMmU3OGY5OGRlYWFjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6dG5pcBfByThO9t0fWSunRrAG2ZYS1eAPJoPXi5yMUQ)

**Comment by Janarthanan6119** [comment]
Now its(Internal error) clear

**Comment by hobovsky** [comment]
**Janarthanan6119**, your problem has another underlying cause than the issue discussed in this ticket. Your error should have gone away now.

**Comment by OGMetalDad** [comment]
I am getting this error now submitting 4 kyu "Matrix Determinant" in C++.  Multiple submissions and after reading the above comments tried refreshing but no love unfortunately.  

I am so glad I started pasting my work into Notepad++ when I start refactoring 'cause my solution was gone when I hit back.  
/whew

**Comment by Tonyac-create** [comment]
Hello, we have same problems today and yesterday. For the kata "Detect Pangram" when I want to submit the solution. And yesterday when I come to the site with Dashboard. 
![image](https://github.com/codewars/codewars.com/assets/79973772/db8e8ecf-bcb4-495f-b5cc-7f2c121f6668)

**Comment by VanessaGreene** [comment]
Hi all, we are currently investigating this issue, I'm sorry that you've experienced issues submitting kata at this time, we hope to have a fix for this very shortly. Please let me know your username and the kat you experienced issues with. This will help us determine how much data has been correctly saved.

**Comment by johanrex** [comment]
@VanessaGreene 

Name:
johanrex

This kata:
https://www.codewars.com/kata/554e4a2f232cdd87d9000038/train/python

This code:

```
def DNA_strand(dna):
    mapper = {
        "T":"A",
        "A":"T",
        "C":"G",
        "G":"C",
    }
    
    return "".join([mapper[c] for c in dna])

```

**Comment by johanrex** [comment]
User name:
johanrex

This kata:
https://www.codewars.com/kata/5266876b8f4bf2da9b000362/solutions/python

**Comment by VanessaGreene** [comment]
Hi @johanrex, I'm happy to confirm that these Kata solutions saved on your profile and that you received your points.

**Comment by VanessaGreene** [comment]
Hi all, This error has been identified as a connection timeout on our solutions pages, we have deployed a fix to reduce the likelihood of this occurring again. Please let us know if you experience any further errors when loading solutions pages, and we will investigate.
