### ISSUE TITLE
about codewars

### ISSUE THREAD

**Issue by leishaozaici** [Codewars/codewars.com#3212]
how many register users in codewar  up to now?

**Comment by Claukorze** [comment]
Hi @leishaozaici ,

Thanks for reaching out to us and we would like to invite you to share your questions or comments to know more about Codewars with our Community in [Discord](https://discord.com/invite/mSwJWRvkHA) or find topics related to General discussions about it as well in [discussions](https://github.com/codewars/codewars.com/discussions).

Thank you!
