### ISSUE TITLE
Internal Server error 

### ISSUE THREAD

**Issue by vanessa2186** [Codewars/codewars.com#3216]
Hi! Looks like the dashboard doesn't load! As I went in codewars page today I got this message:

![Screenshot 2024-05-20 154506](https://github.com/codewars/codewars.com/assets/76069229/ab927b9a-5f1c-4b1c-9900-c62e6aab043f)

then tried a different browser and got this as I tried logging-in:

![image](https://github.com/codewars/codewars.com/assets/76069229/e79fab70-2789-4fa6-bc22-14cbd28fe1a3)

however, when I checked status page there appear to be no issue... which isn't correct as I still get the server error above!
![image](https://github.com/codewars/codewars.com/assets/76069229/b6298c7e-0e1b-401b-b19d-5eb9a6e104dc)

Thanks

**Comment by hobovsky** [comment]
Yes, it has been noticed.

Nevertheless, thank you for your report! I will try to bring attention of admins to the issue, even though I believe they also already noticed.

**Comment by VanessaGreene** [comment]
@vanessa2186 is this error still happening for you?

**Comment by vanessa2186** [comment]
@VanessaGreene  looks like is all good now!  👍

![image](https://github.com/codewars/codewars.com/assets/76069229/84633e45-170d-4f60-b16c-52e526a6f6f8)

**Comment by puddingForever** [comment]
it still happens for me after submitting the task which I got accepted.  When I tried to check other solutions it shows internal server error which blocks me to check other solutions

**Comment by Claukorze** [comment]
Can you please share with us screenshots or a video to try the reproduce the case? Thank you!

**Comment by cyrusyan021** [comment]
> Can you please share with us screenshots or a video to try the reproduce the case? Thank you!

It shows "Internal Server Error" by simply clicking "Submit button" and View Solutions.

**Comment by vanessa2186** [comment]
Hi! Yes, it looks like the issue is back when submitting katas... 🙁

![image](https://github.com/codewars/codewars.com/assets/76069229/177297cd-29d1-43d5-9a3e-80be15cb5bf0)

...but looks like the kata is submitted though... (blurred my solution to avoid spoilers)

![image](https://github.com/codewars/codewars.com/assets/76069229/52e74cbc-ab00-4b79-8049-14dee03f5df1)

**Comment by MareikeFla** [comment]
Hi, I also have an Internal Server error every time I submit a kata - But it is saved as submitted in my profile.
![Screenshot from 2024-05-21 14-17-58](https://github.com/codewars/codewars.com/assets/148346025/90a6a8c1-6e9d-4328-a00b-fd61fc74355c)

**Comment by sfdcluke** [comment]
![Screenshot at 2024-05-21 18-30-25](https://github.com/codewars/codewars.com/assets/61444572/592e9bb5-45f8-4166-ac5b-1b898d2f6ee6)

As soon as you log in to codewars we are greeted by this error.

**Comment by Claukorze** [comment]
It seems the service has been reestablished, can you please try again?  Thanks for you patient and understanding

**Comment by MareikeFla** [comment]
No, still Internal Server error every time I submit a kata.

**Comment by vanessa2186** [comment]
Apologies for late reply! Looks like it's back for me! It takes me right to the solutions page upon kata submission 👍 
Thanks!

**Comment by vanessa2186** [comment]
Ok... it's happening again! I give up.... 🙁

![image](https://github.com/codewars/codewars.com/assets/76069229/80fb0e2b-ffe2-4a16-b40b-b199aa8377d0)

**Comment by assarjunior** [comment]
![Annotation 2024-05-22 151636](https://github.com/codewars/codewars.com/assets/169374624/0e28458b-70f5-4f75-882c-ae5cc24496ac)
problem while opening any link inside codewars

**Comment by ykzhong** [comment]
> ![Annotation 2024-05-22 151636](https://private-user-images.githubusercontent.com/169374624/332811016-0e28458b-70f5-4f75-882c-ae5cc24496ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODc4ODksIm5iZiI6MTcxNjM4NzU4OSwicGF0aCI6Ii8xNjkzNzQ2MjQvMzMyODExMDE2LTBlMjg0NThiLTcwZjUtNGY3NS04ODJjLWFlNWNjMjQ0OTZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTUxNDQ2YzVkNWVhNzk0ZjA0ODI0OGUzOWY4MTEwM2RmYmEwZDQ3ZWUwNGExNTIyZWYzMjdiYmZmY2ZlMTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lwknf9_sHqPqI11nxbT2u_SDkIT4x4vVOCMKT36O48M) problem while opening any link inside codewars

I have the same problem, even when i go to the Home page.

**Comment by ctrl-alter-ego** [comment]
I've just signed up, and I get it on the dashboard and the practice page. I managed to get the practice page to load once, but scrolling down it produced the internal server error message.

**Comment by ptd3v** [comment]
I've been getting the internal server error every day for about a week, when solving an issue.

**Comment by VanessaGreene** [comment]
Hi everyone! Thank you for all your patience over the past few days. We experienced several temporary outages on some of our services, which have prevented you from accessing Codewars or submitting your Kata solutions.
 
Our engineering team has established the root cause of this issue and determined that it was caused by one of our third-party services experiencing both failures and urgent maintenance in the past few days. 
 
We are monitoring this situation and preparing to make necessary changes in the unfortunate case that we continue to experience issues. 

Further information can be found here: https://codewarsstatus.com/incidents/2r36twmzxr15

**Comment by BurntToastSVG** [comment]
well how can i fix it 
for gods sake please stop this error

**Comment by ctrl-alter-ego** [comment]
> well how can i fix it

You won't be able to; this is one for them.

**Comment by truanthh** [comment]
![Screenshot_2](https://github.com/codewars/codewars.com/assets/139843863/1ab63a5e-2841-4076-9c5a-274bf44369af)
looks like a lot of people have this. same thing was yesterday and the day before.
its happening after i submit a solution to kata. (solution gets submitted though). also happens when i try to see other solutions.

**Comment by VanessaGreene** [comment]
Hey everyone! We understand the frustration caused by the extended time it's taking to resolve this issue. We've identified that the problem is related to the solution page timing out during loading. Don't worry; your solutions have been saved. Our team is working hard to pinpoint and address the cause of this loading issue. Thank you for your patience and understanding!

**Comment by woodstea23** [comment]
Just joined and I get this error when trying to go to either Home or Practice. Dead in the water for now...

**Comment by nobuluci** [comment]
just joined and i get internal server error when trying to go to practice

**Comment by SlothSan** [comment]
This issue is back, loading the dashboard on Chrome / Windows gives me the same internal server error. 

Good luck with the fix!

**Comment by opheli2003** [comment]
Same here when trying to log in

**Comment by VanessaGreene** [comment]
Our team is investigating reports of outages, we hope to be back up and running shortly. We apologize for the inconvenience this has caused. If you are encountering other issues, please contact info@codewars.com.

**Comment by VanessaGreene** [comment]
Hi all, we have now recovered from this outage, this was caused by an external service experiencing outages. You can read more at https://codewarsstatus.com/incidents/cr7v1x71xmq1. If you encounter further issues, please contact our support team at info@codewars.com.

**Comment by incmoga** [comment]
I have the same problem, even when i go to the Home page.

![photo_2024-11-25_20-38-45](https://github.com/user-attachments/assets/58645cc6-dc15-453a-b22e-dd60ff82fb8c)

**Comment by hobovsky** [comment]
The issue has been noticed and engineering team has been notified. Someone will get to work on this, but currently there is no ETA.

**Comment by scoraig52** [comment]
I have this exact error all day today. Any known ongoing issue?

**Comment by hobovsky** [comment]
I managed to get to one of admins and things got a bit better, but still wonky. Errors are still common, but some pages mostly work. But for example the search page is difficult to show.

I can keep bugging admins but i am afraid that they can be difficult to reach during weekend :)

**Comment by scoraig52** [comment]
I don't want to get in trouble with the union. It's fine if they'll have a look at it on Monday ;)
