### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Iqbal313-cloud** [Codewars/codewars.com#3217]
![Screenshot from 2024-05-20 21-08-29](https://github.com/codewars/codewars.com/assets/136589428/a7b332a8-1934-48cb-b93c-24286941e016)

**Comment by Iqbal313-cloud** [comment]
please solve this

**Comment by hobovsky** [comment]
Seriously...

![image](https://github.com/codewars/codewars.com/assets/23709795/4a2e3fb1-f5de-4cea-8038-fa1fba1c83ce)
