### ISSUE TITLE
Extra blank lines in kata solutions

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#322]
It looks like some of the solutions are not being trimmed of whitespace properly, resulting in extra blank lines displaying.  It looks weird.

Actually if I copy the text, the "blank" lines seem to have leading spaces, so maybe that is why they are not being filtered out correctly.  

So far I have noticed this in two Python kata.

http://www.codewars.com/kata/53f103c3ef9ad4014f00013b/solutions/python:
![untrimmed](https://cloud.githubusercontent.com/assets/5090280/15455151/d2c8156a-2019-11e6-92a4-4adc80cb4f7a.PNG)
http://www.codewars.com/kata/54162d1333c02486a700011d/solutions/python:
![untrimmed2](https://cloud.githubusercontent.com/assets/5090280/15455153/dc149724-2019-11e6-910b-e05900fa225f.PNG)
![untrimmed3](https://cloud.githubusercontent.com/assets/5090280/15455154/dea66b2a-2019-11e6-80bd-73f641220934.PNG)
![untrimmed4](https://cloud.githubusercontent.com/assets/5090280/15455170/639e7fb6-201a-11e6-8d56-5f9fb09c1dc3.PNG)

**Comment by paul-calvelage** [comment]
Here's an example I just saw in a Ruby solution to [Basic variable assignment](http://www.codewars.com/kata/50ee6b0bdeab583673000025/solutions/ruby/all/clever).  Yikes!
![ruby](https://cloud.githubusercontent.com/assets/5090280/15511420/64e36446-21a9-11e6-9ba3-83e17c723dd3.PNG)

**Comment by paul-calvelage** [comment]
It seems this can happen in the "Show Kata Test Cases" area as well, since 11 extra lines are showing here:
![test cases](https://cloud.githubusercontent.com/assets/5090280/15697599/a6724d1a-2789-11e6-932f-63874b8d2a0c.PNG)
http://www.codewars.com/kata/master-of-files/discuss#574e55c8296e4103f8001121

**Comment by kazk** [comment]
Closing this because I don't think this is a bug. Isn't it just displaying what was submitted?
@jhoffner please re-open if you still think this is a bug.
