### ISSUE TITLE
Elixir code formatting removes newlines

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#324]
I had [some code](http://www.codewars.com/kata/all-inclusive/solutions/elixir) like

``` elixir
def foo(bar), do: true
def foo(baz) do
...
```

In "Past solutions" and in the solution list it became

``` elixir
def foo(bar), do: true  def foo(baz) do
...
```

**Comment by kazk** [comment]
I believe this isn't happening anymore. Please let me know if it is.
