### ISSUE TITLE
suspected outage (June 5 2024)

### ISSUE THREAD

**Issue by ChanOmegaWebDesign** [Codewars/codewars.com#3240]
```
Internal Server Error
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our [Github issues list](https://github.com/codewars/codewars.com/issues). This will help us get things fixed faster.

Internal Server Error
```
That is all that shows on my dashboard, started after submitting a solution. Looks/acts like the same problem as 2 weeks ago.

**Comment by VanessaGreene** [comment]
Hi @ChanOmegaWebDesign our team is investigating the cause, and we hope to be back up and running shortly. If you are encountering other issues, please contact info@codewars.com.
