### ISSUE TITLE
[internal server error on kata submission]

### ISSUE THREAD

**Issue by jroycodes** [Codewars/codewars.com#3241]
![Screenshot 2024-06-05 193009](https://github.com/codewars/codewars.com/assets/97290886/1b9964a0-c0d4-4fbd-8186-fb75713460fa)

**Comment by dmaxu** [comment]
I'm having the same issue when going to the home page.

**Comment by techni-ca** [comment]
I'm getting this on the dashboard and practice but not on sparring, leaderboards, docs, profile...

**Comment by woodstea23** [comment]
I've had this problem intermittently on the Home and Practice pages this morning, but most of the time it's just when I submit or when I try to go to Solutions for any particular kata.

**Comment by shinobiinu** [comment]
I have also encountered this issue several times.

**Comment by DraginDA** [comment]
When you go to the "view solutions" section, this error constantly pops up

**Comment by MadhurToppo** [comment]
I encountered this error several times today upon code submission.

**Comment by jroycodes** [comment]
Hopefully it gets sorted out

**Comment by jsspen** [comment]
I'm getting this constantly when submitting. It has been occurring for a few days now though refreshing the page had been working... until this morning. I tried refreshing one multiple times with no luck. I hit back and my solution was clear. Copied my code back in and submitted and this time got a popup that there was a server error and to try again. Hitting OK brought me to the same Internal Server Error as before but luckily this time refreshing it worked.

**Comment by VanessaGreene** [comment]
Hi all, This error has been identified as a connection timeout on our solutions pages, we have deployed a fix to reduce the likelihood of this occurring again. Please let us know if you experience any further errors when loading solutions pages, and we will investigate.

**Comment by jroycodes** [comment]
> Hi all, This error has been identified as a connection timeout on our solutions pages, we have deployed a fix to reduce the likelihood of this occurring again. Please let us know if you experience any further errors when loading solutions pages, and we will investigate.

Works nicely now. Thanks
