### ISSUE TITLE
CW-359: CW is showing Codewars Red ad to users already subscribed to Codewars Red

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#3251]
This happened since a month or two ago, but I'm beginning to see Codewars Red ads, even though I'm already subscribed:

![image](https://github.com/user-attachments/assets/3d767235-6ab4-4db7-ac04-186c2da38e0c)

When clicked it says I'm already subscribed:

![image](https://github.com/user-attachments/assets/21457123-d2e5-4c54-bda3-2abc2a39967c)

This didn't happen before: all Red users are exempt from CW Red ads.

**Comment by VanessaGreene** [comment]
Hi @Voileexperiments, thank you for flagging this, we are aware of this issue, and our team is trying to fix it. We encountered an error in our own advertising platform that isn't always filtering out Red users, we hope to have this fixed as soon as possible as it is not ideal.

**Comment by VanessaGreene** [comment]
Hi @Voileexperiments, We have just pushed a fix for this issue to production. However, this current ad may show until dismissed (by hovering over it and clicking on the x at the top right of the ad). From now on, you shouldn't receive any ads. I apologize for the inconvenience this has caused.
