### ISSUE TITLE
Code deleted after refreshing page in browser

### ISSUE THREAD

**Issue by matthewmoppett** [Codewars/codewars.com#326]
I recently did the kata "Square into Squares. Protect trees!" and confirmed the correctness of my code by pressing "Submit". I decided to make a couple of small changes and then pressed "Submit Final", but was greeted by the response "Unknown Error" several times in a row. I decided to refresh the page to see if that might solve the problem, and found that after the page had reloaded, all my code had disappeared and been replaced with the default starting code for that kata. 

The browser I was using was Firefox, although I recall that something similar has happened to me when completing a kata with Google Chrome. 

Addendum: I did the kata again and hit the same problem with "Unknown Error" after pressing "Submit Final". This time, luckily, I made sure to copy my code to the system clipboard before reloading the page. Once again, all my code had been replaced with the default starting code.

**Comment by jhoffner** [comment]
Thats not good at all :( We will prioritize this issue.

**Comment by pocesar** [comment]
Same happened to me, was writing a huge test case in a new Kata, and after "Unknown error", I tried clicking "Save", but my test case was gone, along with everything I've written BUT the description

**Comment by Davo36** [comment]
Same here.

I've just started solving problems on this site.  I have previously used Spyder a lot for Python programming, and in that IDE, you press F5 to run your code.

On the Codewars site, this refreshes the page, and all your code disappears... never to be seen again.  Had this happen twice now... very frustrating.

Can't see how to save code and the automatic save seems to run infrequently.

Hope it can be fixed shortly.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
