### ISSUE TITLE
Translation process is ripe for abuse

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#328]
[Crime doesn't pay.](http://idioms.thefreedictionary.com/Crime+doesn't+pay)  At least it shouldn't...

After reading the answer to #174, which was closed a while back, it occurred to me that if the honor for forked translations is going to the original translation author, then the translation process would be vulnerable to a squatting attack.  Here's a potential strategy:

1. Search for the latest kata.  These are the most likely to lack translations.
2. Create pointless, low quality translation stubs in each of the possible languages.
3. Wait for honest people to fork your malicious "translations".  They are forced to do this by the current translation rules, which require at most one "root" translation in each language.
4. Reap the rewards once they are approved.  Crime does pay?

**Comment by jhoffner** [comment]
Good points. Though AFAIK no one is doing this. Due to the long backlog of issues that CW has I'm going to list this as a low priority. If it starts to become an issue we can address.
