### ISSUE TITLE
Kata search filter issue

### ISSUE THREAD

**Issue by HollowPo1nt** [Codewars/codewars.com#3285]
**Describe the bug**
The Progress filter option "Kata I have not completed" also shows all of the items for "Kata I have not trained on" option 

**To Reproduce**
1. go to https://www.codewars.com/kata/search/
2. switch between "Kata I have not completed" and "Kata I have not trained on" Progress options (the count of found katas helps)

**Expected behavior**
"Kata I have not completed" option shows only katas that were attempted to solve by me

**Additional context**
Well, technically "Katas I have not trained on" _may be_ described as "Katas I have not completed". But honestly, I just cannot find the one I actually started but wasn't able to load its page again.

**Comment by hobovsky** [comment]
You can find the kata you started but did not finish in your profile:

![image](https://github.com/user-attachments/assets/9a090d6f-55f2-43b8-a077-6504314fb730)

**Comment by Claukorze** [comment]
Thank you @hobovsky for jumping on this and please @HollowPo1nt let us know if you can't find it or if you experiment another issue with our platform.  Keep training 💪 

Thank you!
