### ISSUE TITLE
Missing link in the documentation

### ISSUE THREAD

**Issue by KomorowskiKuba** [Codewars/codewars.com#3286]
**Describe the bug**
There is no link to the documentation, but there is TODO instead 😅

**To Reproduce**
Go to: https://docs.codewars.com/getting-started/setting-up

**Expected behavior**
There should be a link do the documentation instead of TODO.

**Screenshots**
<img width="964" alt="Zrzut ekranu 2024-10-1 o 18 32 54" src="https://github.com/user-attachments/assets/9753881f-69c1-4098-8f74-806e86cb73ef">

**Browser**
- OS
- Chrome

**Comment by Claukorze** [comment]
The missing links have been solved. Thank you!
