### ISSUE TITLE
Sorting by "oldest" kata shows newest first instead

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#329]
Selecting "Sort by: Oldest" on the kata search page instead shows the __newest__ kata first.  Here's the URL:
```
http://www.codewars.com/kata/search/?q=&order_by=published_at+desc
```

I think this was meant to be `asc` instead of `desc`.  Otherwise it's approximately the same ordering as "Sort by: Latest".  The only difference is that "latest" seems to sort by modification date for approved kata instead of publication date.  For beta kata the ordering is the same either way so it's easier to see the bug if we filter for beta kata only, as below.  

http://www.codewars.com/kata/search?q=&beta=true
![latest](https://cloud.githubusercontent.com/assets/5090280/15517081/e4f33c8c-21c3-11e6-9829-82fac74617c6.png)
http://www.codewars.com/kata/search?q=&beta=true&order_by=published_at+desc
![oldest](https://cloud.githubusercontent.com/assets/5090280/15517088/ee455400-21c3-11e6-9e7b-2f7a4bb1a5d9.png)

Sorting by "oldest" should be the opposite of "latest", not the same.

**Comment by jhoffner** [comment]
Fixed
