### ISSUE TITLE
"My Solutions" shows up emtpy (for some of the kata)

### ISSUE THREAD

**Issue by Serkora** [codewars/codewars.com#33]
The kata is marked as **solved**, I can see everyone else's solution for a particular language, but if I choose **My Solutions**, I only get **There are no solutions yet for this kata.**
This happens for me _at least_ for this one http://www.codewars.com/kata/i-liked-the-sql-better-dot-dot-dot/, others _seem_ to be fine, but haven't checked all, obviously. As I remember, there were some problems on the server at the time I was trying to complete this kata, so that may be related, but in any case, check the integrity of the records and what not.
![screen shot 2015-04-10 at 10 51 31 pm](https://cloud.githubusercontent.com/assets/8090867/7095550/0b61d9ce-dfd4-11e4-91b2-6124170e0cee.png)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1ecr) by [Unito](https://www.unito.io)

**Comment by pootzko** [comment]
same thing for me with this one: http://www.codewars.com/kata/is-this-working

**Comment by paul-calvelage** [comment]
Something is going on with marking kata as completed that might be related to this scenario.  See issues https://github.com/Codewars/codewars.com/issues/265 and https://github.com/Codewars/codewars.com/issues/282

**Comment by galan** [comment]
Some for me, bug is still valid. Fortunately the honor points have been given.

**Comment by VanessaGreene** [comment]
@Serkora Is this issue still present? If so let me know and I'd be happy to reopen this.
