### ISSUE TITLE
No docs on Typescript testing framework

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#331]
I was trying to do something like `Test.randomToken()` but I suppose that will have to implement the funvction myself.

**Comment by jhoffner** [comment]
Yeah, the framework is Mocha. You can use Chai.js or the built-in Node assertion libraries. I didn't provide documentation since those libraries have their own, but I guess I could add a link.

**Comment by javatlacati** [comment]
Sure! please add them to the [docs page](www.codewars.com/docs)

**Comment by kazk** [comment]
TypeScript page includes a link to Mocha.
https://github.com/Codewars/codewars.com/wiki/Language-TypeScript
