### ISSUE TITLE
Site Instability

### ISSUE THREAD

**Issue by bachmccann** [Codewars/codewars.com#3313]
Encountering "Internal Server Errors" when accessing various links on the Codewars site.  Problem has occurred intermittently over the last couple of days.  Screen shot has been attached.  The issue is occurring frequently this morning, making the site unusable.
![Screenshot 2024-12-13 090439](https://github.com/user-attachments/assets/43ba0459-01e5-4732-8537-2f626a83671e)

**Comment by VanessaGreene** [comment]
Hi @bachmccann, we are currently monitoring reports of significant load times and short bursts of outages in the past few minutes. We will have an update shortly.

**Comment by VanessaGreene** [comment]
Hi @bachmccann, we are still investigating this issue, please keep an eye on https://codewarsstatus.com/ for more updates. We're sorry for this inconvenience.

**Comment by bachmccann** [comment]
Vanessa,

The Codewars site continues to experience frequent outages.  I received the
following error message this morning when attempting to access the site.  I
thought that it might help your troubleshooting efforts as it provides more
detailed information (see attached).

Jim
