### ISSUE TITLE
Submit Final button missing [bug]

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#337]
That's bad... was just 13 places to top 100 :sob: 
![cw](https://cloud.githubusercontent.com/assets/1063901/15623605/566bd27e-243b-11e6-902d-d6c376e7f671.PNG)

**Comment by javatlacati** [comment]
More info: it only happends on that one, it appears as passed, but no solutions are shown.

**Comment by javatlacati** [comment]
it also happends on this: http://www.codewars.com/kata/5634fcfd8ddea5109800004f/ no points awarded

**Comment by javatlacati** [comment]
also on this: http://www.codewars.com/kata/55cbbc7baa3e004f4f0000fc/train/javascript

**Comment by jhoffner** [comment]
Is this still an issue?

**Comment by javatlacati** [comment]
yes, still the same both on preview and cw site

**Comment by jhoffner** [comment]
OK I just realized the issue. Both of these challenges are drafts. You can't submit solutions to draft challenges. Not sure how you found them. These didn't come up for you while browsing the site did they?

**Comment by jbampton** [comment]
https://www.codewars.com/kata/grasshopper-convert-to-celsius/javascript  This one is draft and has solutions

**Comment by jhoffner** [comment]
Not sure how recent those solutions are. This may be fixed now with recent changes - meaning new solutions won't go through. The submit final button doesnt work on that kata either. 

Any idea what the use case is here? Interesting that draft kata are receiving so much attention without being published - unless maybe they were published and then unpublished later on.

**Comment by javatlacati** [comment]
They appear as drafts now I get to them from the Beta Kata filter at the  Kata search bar. That explains why I get a lot of comments on a Kata I've marked as a draft last week.
What Beast says is true... it is a draft and train button is enabled. I think it is cool but not sure how did he got the link. Perhaps have the button label changed to something like take a peek on draft will be less confusiong. Thanks :)

**Comment by northcoders-chris** [comment]
Am I also experiencing this issue? It has happened twice today. I have a much higher rank than these Katas which may be the reason. I am doing them as I am preparing a course using CodeWars for beginners.
![screen shot 2017-04-14 at 08 54 59](https://cloud.githubusercontent.com/assets/5517662/25037311/60f259b8-20f0-11e7-9d9b-6df98e7bd3f2.png)

I have also done it on this Kata http://www.codewars.com/kata/combine-objects but I clicked 'Show Solutions' in that case as I like to explain the top rated solution to beginners

**Comment by jbampton** [comment]
https://gitter.im/Codewars/codewars.com  Other users reports this today in the chat room.

**Comment by MichalGajda** [comment]
Hello, i have similar problem with this kata: https://www.codewars.com/kata/simple-rot13-dot-5-cypher/train/java . Whenever i use "Attempt" button tests are passing, but no points are given, no "Submit/Submit Final" option appears, kata stays in "Unfinished" section.
Here is screen, but without code:
![kataproblem](https://cloud.githubusercontent.com/assets/23103851/25041401/0cf15c18-2110-11e7-8aef-9dddcc51cc12.png)

**Comment by ryanclarke** [comment]
I have this issue too. And I've tried in Edge, Opera, and Firefox.

**Comment by agnes-kabaly** [comment]
I have the same problem today... I can't submit my new solutions nor old solutions ... :C

**Comment by burntham** [comment]
I'm having the same issue, I'm unable to submit solutions :/

**Comment by tgt87** [comment]
I have the same problem too...Can't submit solutions 😞

**Comment by Heathercoraje** [comment]
Same here :(

**Comment by kreafox** [comment]
Same issue, can't submit solutions :(

**Comment by agnes-kabaly** [comment]
It's works again...(but I didn't do anything) :3

**Comment by adi-malhotra** [comment]
After Attempt, it doesn't show Submit Final for a problem and it remains in my unfinished section.

**Comment by mrkeremyilmaz** [comment]
Although all tests are successful, no submit button appears. Also there is a red border around outputs section. 
![Red Border Screenshot](https://user-images.githubusercontent.com/26116031/41821459-d80f519e-77e9-11e8-97a7-6431458d6ece.png)

**Comment by Kalyalev** [comment]
Cannot submit solutions on any katas. Missing submit buttons on al

**Comment by nocnoi** [comment]
This problem still exists. Would appreciate it if the developers could fix the issue.

**Comment by omgjlk** [comment]
Seems to work if I make Safari go full screen. But if it's just windowed the buttons fall off the bottom of the screen. I can just barely see the COLOR of the buttons, but can't click them.

**Comment by chrum** [comment]
Still exists :( but after some experiments with window size i managed to click it :D

**Comment by Voileexperiments** [comment]
The original issue happens because the kata is in *draft*, which is intended. (Retired katas are treated the same as draft katas.)

However there's *another*, separate issue where the submit final button overflows into the next line due to css problems. That is not this issue.
