### ISSUE TITLE
avatar - image

### ISSUE THREAD

**Issue by dcrystalj** [Codewars/codewars.com#339]
I have linked account to github on registration and also use gravatar image. On [codewars](http://www.codewars.com/users/dcrystalj) i cannot see my image.

**Comment by adam-tokarski** [comment]
It might have be question of some cache. I can see your avatar now.

**Comment by dcrystalj** [comment]
I can see it gets loaded but not displayed correctly. On firefox its fine. on chromium 50.0 - ubuntu it's not. I have tried deleting cached and it didn't help

**Comment by javatlacati** [comment]
Then it's not codewars bug, you can report this bug at [chromium site](https://www.chromium.org/for-testers/bug-reporting-guidelines)
