### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by szurkemedve** [Codewars/codewars.com#34]
Sometimes when submitting Python katas, I receive an unknown error.
I have a feeling, that it happens when testing function that returns a list or None. Running the test for None manually reproduces the unknown error. eg. at this kata:
http://www.codewars.com/kata/54d81488b981293527000c8f/train
Submitting this solution: http://pastebin.com/1Pkn7nuZ
(i know, that it's not a good solution because of the timeout)
produces the error without going near the 6 sec timeout:
Unknown error
Process took 2909ms to complete

**Comment by jhoffner** [comment]
I can reproduce this issue. It fails on the long tests only. May be an issue with the testing framework.
