### ISSUE TITLE
Change Your Password is not Working

### ISSUE THREAD

**Issue by Maxi-Heartnet** [Codewars/codewars.com#340]
Hi, i forgot my password and i'm trying to set it up via "Forgot Password". I received the email, but the thing is that when i write my new password and click on the "CHANGE MY PASSWORD" button, the page doesn't do anything, the just reload and my new password is not setted up, and the page just stay as before, it doesn't display any message or something.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
