### ISSUE TITLE
Resolved issue is initially marked as "soon" instead of "just now"

### ISSUE THREAD

**Issue by paul-calvelage** [codewars/codewars.com#341]
Not a big deal, but noticeable--

I marked one of my own suggestions as resolved by replying to the thread, and a caption appeared underneath that said "Suggestion marked resolved by PaulCalvelage **soon**".  Instead of "soon" it should have said "just now".  I would estimate that before a minute went by it changed from "soon" to "just now", so I don't think the timing was off by more than that.

Also, as a side note, since the word "soon" appeared in the same grey color as "PaulCalvelage" without any punctuation, it looked to me like it was part of the username.  My crazy brain initially interpreted "soon" as part of my last name since I wasn't expecting my comment to travel into the future!  

So if we want to [split hairs](http://idioms.thefreedictionary.com/split+hairs), "soon" (or "just now", "3 minutes ago", etc.) should really be white colored to match the rest of the caption, or separated by a comma, bullet point, or something.

![comment_crop](https://cloud.githubusercontent.com/assets/5090280/15697777/7c93eca4-278b-11e6-91f1-14ab69411c40.png)

Source: http://www.codewars.com/kata/master-of-files/discuss

**Comment by kazk** [comment]
Fixed
