### ISSUE TITLE
Unable to publish a Ruby translation in days [other kata translations work fine]

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#343]
I started with [this translation](http://www.codewars.com/kumite/5749d6bc8bf8b62b6e002334?sel=5749d6bc8bf8b62b6e002334), a pretty simple one, but got tons of timeout and even when it worked, it told me that the `lt` operator is unknown (well, I am pretty confident Ruby can still compare two numbers instead).

I tried to work around that with [another solution](http://www.codewars.com/kumite/5749d6bc8bf8b62b6e002334?sel=574b98b6974b95d970000392), forking the previously flawed one. Well, that NEVER worked, always timed out, no matter what.

Even if I try to force to check it all by pressing "publish", which usually works, I get a published kata with failed test cases.

Strange things, if I try to publish Ruby translations for other katas, everything seems to work well. Any tips?

**Comment by g964** [comment]
You can see #342. It's not only Ruby... or this Ruby kata translation.

**Comment by jhoffner** [comment]
It looks like in this case `rand()<0.22` needs to be `rand() < 0.22` in order to work (spaces required). I'll have to look into why that is.

**Comment by GiacomoSorbi** [comment]
I am pretty confident I tried with spaces as well, but to no avail back then.

Thanks for your attention anyway :)

**Comment by jhoffner** [comment]
@GiacomoSorbi see my notes on #342, If you use the optimization that I recommended then you shouldn't get the timeout issues anymore (and it will run **much** faster).
