### ISSUE TITLE
Language icons wasting screen space by overflowing

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#350]
My laptop screen is 1366x768, which means space is at a premium when kata training.  Even more so since Codewars is wasting some of it.

The language icons on some well-translated kata are causing the "menu bar" to overflow to a second line on the right.  But it appears there is extra unused space to the left of the language icons, between "1 issue reported" and the "js" icon.  If the wasted space were used, the menu line would not need to overflow:
![wasted space](https://cloud.githubusercontent.com/assets/5090280/15775331/4722a2c0-294f-11e6-8318-93897a2b1695.PNG)

Overall there is a lot going on at the top of the page. As more and more languages and other features are added to Codewars, this will only get worse.

**Comment by jhoffner** [comment]
Its a responsive column based layout so moving that over when space is needed is harder than it looks. I'm planning on replacing the language icon buttons with a single dropdown (similar to kumite/translations).

**Comment by javatlacati** [comment]
Icons are the best of the GUI, it will be better in my opinion to make the moon a second row below so when you'll have a language with a huge name it could not break the layout.
