### ISSUE TITLE
Strive attribution is misaligned and covers up horizontal scroll bar

### ISSUE THREAD

**Issue by paul-calvelage** [codewars/codewars.com#351]
The "powered by Strive" banner covers up most of the horizontal scroll bar in the kata instructions, as well as obscuring a few pixels at the bottom of the vertical scroll bar.  Yes, it looks sloppy since it is not aligned properly.  But worse, it makes it hard to read kata descriptions (such as [this one](http://www.codewars.com/kata/536602df5d0266e7b0000d31/train/javascript)) that overflow the right of the box, since the horizontal scroll bar is hidden underneath.

![scroll](https://cloud.githubusercontent.com/assets/5090280/15776491/e2603b0c-2955-11e6-8323-1873a8acf3d9.png)

NOTE: Tested in Chrome and Firefox on Windows 10.  The screenshot is from Chrome, but it looks almost the same on Firefox as well.

**Comment by kazk** [comment]
Looks like this was fixed.
