### ISSUE TITLE
Bookmark Bug

### ISSUE THREAD

**Issue by matthewbryancurtis** [Codewars/codewars.com#352]
The bookmark feature is acting buggy. Chrome vs 50, OSX.
- Unable to bookmark/favorite kata (Molecule to Atoms by romanzes)
- Bookmark/favorite dropdown stays frozen open after mouse leaves

**Comment by Ij888** [comment]
Chrome v55, FF on Windows works okay. The bookmark bug seems only to manifest in Chrome OSX.

**Comment by kazk** [comment]
The bug that prevented bookmarking is fixed now.
