### ISSUE TITLE
Unwanted scroll up when translating new Kata

### ISSUE THREAD

**Issue by aryan-firouzian** [codewars/codewars.com#353]
When I want to translate a Kata I need to check some names and values in original language. So, I scrolled down to see it on the left side, but when I stroke any key on keyboard to write down, it automatically scroll up to the top. Sometimes it is bothering.
It happend to me recently while I was using Chrome 50.0.2661.102 and Firefox 45.0.2.

**Comment by DonaldKellett** [comment]
I've also encountered the same problem a few times when authoring (PHP) Kumite.

**Comment by hlaaftana** [comment]
This still happens and has always been and still is the main slowdown when translating kata.

**Comment by Kacarott** [comment]
Want to bump this. It is *very* annoying. It happens every time I translate a kata.

**Comment by kazk** [comment]
Deployed a fix. I had to change how they're rendered, so let me know if you find anything weird.
