### ISSUE TITLE
update Keyboard Shortcuts page

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#355]
`Ctrl + Enter` doesn't submit on windows `Ctrl + S` does. Please test on major platforms and update the docs and the trainning pages.

**Comment by javatlacati** [comment]
related to #24

**Comment by kazk** [comment]
Closing this because this is a duplicate of #212. I'm going to include the updated information in #881 once tests are done.
Also, this is not related #24 which is about enabling shortcuts without focus.
