### ISSUE TITLE
Document Vim Keyboard shortcuts supported

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#356]
I couldn't fin anywhere in the docs how to use `Vim Editor Keyboard Shortcuts` can you document it so people can use them and hopefully get a better user experience?

**Comment by kazk** [comment]
Do you mean ex commands? I don't think Codewars adds anything extra. And I'm not sure if `:w` is intentional.

See [CodeMirror's Vim mode](https://codemirror.net/demo/vim.html).
