### ISSUE TITLE
Honor points not properly awarded.

### ISSUE THREAD

**Issue by wenshutang** [Codewars/codewars.com#36]
I recently completed the "text align justify" Kata (4 kyu), but noticed that my honor only went up by 1. This has happened many times in the past, but recently all my points were adjusted. Is anyone else seeing this? Or am I missing something?

**Comment by wenshutang** [comment]
I just checked now and I have been given the correct amount of honor points.

**Comment by jhoffner** [comment]
Yeah they sometimes take a minute or two to update in the background. What do you mean by "recently your points were adjusted"?

**Comment by wenshutang** [comment]
Last week I logged in and noticed I went from 78 honor points to 118 points
