### ISSUE TITLE
Internationalization of the entire codewars platform

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#360]
I've been looking for the language option, but I have not found. 
There are many people who are willing to contribute to the translation of the platform to his native language.
It would be good if this option exists.

**Comment by jhoffner** [comment]
Please log all feature requests to https://codewars.ideas.aha.io/

**Comment by javatlacati** [comment]
https://codewars.ideas.aha.io/ideas/CW-I-73

**Comment by sidoruk-sv** [comment]
> There is no portal here ... sending you back to Aha!

Please update link and explain, how can we track progress on this feature?
Maybe some help on common internationalization practice implementing (crowdsourced translation as option)

**Comment by javatlacati** [comment]
for now it is a won't fix only bugs are the only priority
