### ISSUE TITLE
Saving TypeScript reference in kumite causes self closing tags to transform into closed tags

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#361]
`/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" />` turns into `/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" ></reference>` on save, which causes a compile error. This seems to happen when opening up a previously saved kumite.

**Comment by kazk** [comment]
The cause of this is still unknown, but those comments can be removed because the new runner doesn't need them.
