### ISSUE TITLE
Site no longer lists my rank

### ISSUE THREAD

**Issue by LesRamer** [Codewars/codewars.com#363]
I was previously ranked 200th with a peer that was approximately ranked 31,000th. This placed my 200th well within the top 1% for the entire site.

Because of this, I can no longer use my relative rank as evidence of my programming skill.

I suggest either restoring the leader-position for all (perhaps all over a threshold of 50 points), or calculating the relative-rank as a percentile of the overall population.

**Comment by jhoffner** [comment]
I'm not sure what is being logged as the issue here. Are you saying it doesn't show you your leader position on your profile? Can you check it again, you may have caught it when a site update was happening.

**Comment by LesRamer** [comment]
That must have been it. The position appears to show again. I also offered the suggestion to show position as a percentile. Take it if you like, but since the position appears to be working (again), I'll close this item. Thanks,

**Comment by jhoffner** [comment]
Thanks. Percentile update will be in an upcoming release
