### ISSUE TITLE
Github Login is broken for some users

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#368]
Seems to work only some of the time

**Comment by jhoffner** [comment]
Not fixed, the flakeyness just gave me the impression that it was. There seems to be certain variable conditions that cause it to fail. Possibly based off of how the domain is originally loaded before getting to the sign in page (naked vs www, http vs https).

**Comment by jhoffner** [comment]
Should be resolved after latest deployment

**Comment by jhoffner** [comment]
Issue persists, though it looks like it is now caused by a different issue.

**Comment by StevePaget** [comment]
This is still broken for me.

**Comment by AlexMapley** [comment]
Bump. This is broken for me `GitHub account is not linked to an existing Codewars user.`

**Comment by lricoy** [comment]
I am also getting the `GitHub account is not linked to an existing Codewars user.` Tried incognito window, revoking access, clearing cache and nothing worked so far.

**Comment by Aaron-Chan** [comment]
it still not sloved?

**Comment by lricoy** [comment]
Doesn't look so. I am still having the issue at least. I have even tried to contact Codewars's support last week but no reply so far 😞

**Comment by kostromich** [comment]
thats true
Profile: GitHub successfully linked as <username>|Unlink
Login form: GitHub account is not linked to an existing Codewars user

Got requests chain with 302 response code

**Comment by lricoy** [comment]
The same @kostromich described worked for me.

**Comment by 99rockets** [comment]
I am facing the same problem.

**Comment by derpyzza** [comment]
is this problem fixed? i link up my github account to sign in, and it forces me to enlist a new account into the site, and when i try inputting my existing account it says it already exists ( which it does. i made it ). it also does not let me manually log in with my email and password. when i log in manually, it just kicks me back to the landing page with a little form to fill in to enlist to the site

**Comment by kazk** [comment]
@derpyzza This is an ancient issue. See more recent issues like #2447, #2449 and #2509 for steps to diagnose and possible solutions. The issue of getting redirected to the sign-up form seems to happen very rarely under unknown conditions, and I haven't been able to reproduce it.
