### ISSUE TITLE
Single Quotes replaced by double quotes upon saving in (PHP) Kumite

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#369]
I don't know if this bug is language-specific (PHP) or appears in all languages but when I click the "Save" button in a PHP Kumite, the single quotes in my code are automatically replaced by double quotes which yields a syntax error when I publish my Kumite.  The screenshot below shows an example of this bug:

![2016-06-11 2 43 51](https://cloud.githubusercontent.com/assets/7777884/15983754/8ccd424e-2fe4-11e6-81be-559c06f20204.png)

**Comment by kazk** [comment]
This doesn't seem to happen anymore.
