### ISSUE TITLE
Katas not marked as completed in search

### ISSUE THREAD

**Issue by AlbinTheander** [Codewars/codewars.com#37]
Some of the katas never gets marked as completed for me.

The funny thing is that the kata "Metaprogramming: Lisp-style Generic Functions" [http://www.codewars.com/kata/metaprogramming-lisp-style-generic-functions] works as some kind of divider. I still haven't solved this one.

When the kata list is sorted by "Latest", katas that appear before the divider kata are correctly marked as completed when solved, while katas that appear after it never gets marked as completed.

I've tried to solve the katas multiple times and in different languages, but it doesn't make any difference to this odd behaviour.

It's no hurry, just a bit inconvenient when I'm looking for new katas to solve. Let me know if I can do anything to help you figure it out. 

Thanks for a wonderful site!!!

**Comment by vferries** [comment]
I have the same problem for some months now. Really hard to find katas I've not already completed...

**Comment by Balkoth** [comment]
I'm also affected. 
I think it happened after I solved my 1000th kata, I never had this problem before.

**Comment by paul-calvelage** [comment]
Issue https://github.com/Codewars/codewars.com/issues/282 might be related to this.

**Comment by paul-calvelage** [comment]
The `App.data.completedCodeChallengeIds` array on the kata page is __*exactly*__ 1000 entries long, which makes me think that Balkoth's comment is correct.  I recently went over 1000 and now my searches are not being filtered properly.

**Comment by kazk** [comment]
Closing old issue. `App.data.completedCodeChallengeIds` is no longer limited to 1000 items.
