### ISSUE TITLE
Icon fonts fail to load

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#371]
Fonts from d2zywx0xwifbv5.cloudfront.net are blocked by the same-origin policy in Firefox 47.0.

**Comment by BHare1985** [comment]
I have the same problem, screenshot: 
![image](https://cloud.githubusercontent.com/assets/2180284/15986030/f6f5f170-2fcb-11e6-96f2-208a9b998eee.png)

**Comment by jhoffner** [comment]
I spent a good portion of the day yesterday working on this. I thought I had it fixed. It works on all browsers on multiple devices for me now. Maybe try clearing your cache?

**Comment by error256** [comment]
Clearing the cache doesn't help. I tried a different system too -- it's the same.

**Comment by BHare1985** [comment]
Same for me ,clearing cache has no effect. The issue is: `Font from origin 'https://d2zywx0xwifbv5.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://www.codewars.com' is therefore not allowed access.`

**Comment by jhoffner** [comment]
Yeah its the oddest thing. I fixed that issue yesterday. Was able to consistently reproduce it, deployed a fix, it immediately went away. But somehow different sets of old problems that I thought I fixed are showing up for different people on different networks. Its kind of maddening but I'm continuing to look into the issues.

**Comment by BHare1985** [comment]
Fixed for me now

**Comment by jhoffner** [comment]
Thanks for letting me know. I didnt change anything yet. Let me know if they go away again.

**Comment by error256** [comment]
Works for me too. If I remember correctly, `Access-Control-Allow-Origin` was `*, *`, now it is `*`.

**Comment by jhoffner** [comment]
Yes cloud front cached the resources. I added nginx into the mix and there was some old heroku based code that added `*` from within rails, so both were adding their own header. I removed the code from rails and switched nginx to server assets statically without rails. Once deployed the changes took affect immediately for me but I guess they stayed cached on different edge servers.
