### ISSUE TITLE
Logged in as different user after refreshing window

### ISSUE THREAD

**Issue by geresdi** [Codewars/codewars.com#375]
I just had this experience after refreshing on kata [Matrix Determinant](https://www.codewars.com/kata/52a382ee44408cea2500074c/train/python). All settings, history etc. of the other user is available to read and edit. My environment is Windows 8.1 and Firefox 46.0.1. I also get an error 400, Page does not exist when trying to log out. I made some screenshots, let me know if I should send them in private.

**Comment by jhoffner** [comment]
Yes please do, jake[AT]codewars.com

**Comment by jhoffner** [comment]
Closing as this is being tracked within #386
