### ISSUE TITLE
Translation into C++

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#377]
I'm trying to translate a kata into C++ but I got lots of "Nope", "Try again" or
```
clang++-3.6 -stdlib=libc++ -std=c++1y -isystem /runner/frameworks/cpp error: expected ';' after struct
}
 ^
 ;
1 error generated.
0 Passed
0 Failed
0 Errors
```
I think there might be a problem of the "runner" because I have all the necessary ';' and no struct in my code:-)

**Comment by jhoffner** [comment]
This will get more attention if logged in the [Code Runner Repo](https://github.com/Codewars/codewars-runner-cli).

**Comment by g964** [comment]
Thanks, done.
