### ISSUE TITLE
Instructions and tests not matching Kata 

### ISSUE THREAD

**Issue by jordanflow** [Codewars/codewars.com#378]
There seems to be some issues with the interface on Code Wars.  Instructions aren't matching up with tests...Methods aren't working correctly in their REPL.

**Comment by jhoffner** [comment]
This is an odd bug. Possibly a caching issue. Have you seen it again? Do you remember which kata had the invalid description?

**Comment by kazk** [comment]
I'm closing this because not enough information was provided to reproduce.
