### ISSUE TITLE
unable to submit any Haskell kata

### ISSUE THREAD

**Issue by kdepp** [Codewars/codewars.com#379]
I've tried several katas, all failed to submit. Here is the error message:

```
/tmp/haskell116513-14-1bld6jj/Codewars/Kata/CommonDenominators/Test.hs:2:8:
    Could not find module `Codewars.Kata.CommonDenominators'
    Use -v to see a list of the files searched for.
```

**Comment by codebje** [comment]
I'm seeing this too, to confirm that it's not just @kdepp having the problem:

```
/tmp/haskell116513-14-1t1ld6u/undefined.hs:4:8:
    Could not find module `TinyThreePassCompiler'
    Use -v to see a list of the files searched for.
```

**Comment by lucky3** [comment]
I'm having the same problem with several other Haskell katas, too:
https://www.codewars.com/kata/5747a9bbe2fab9a0c400012f/discuss#575ecda86888b30fd70003bd
https://www.codewars.com/kata/570a6a46455d08ff8d001002/discuss#575ebf85529e84d843000232

So do the others (https://www.codewars.com/kata/5544c7a5cb454edb3c000047/discuss#575ee83b51071bf224000119)

**Comment by bkaestner** [comment]
Seems like all Haskell variants with hierarchical module names are affected. However, I can't recall a plain module name kata beside [multiply](https://www.codewars.com/kata/multiply/), which is broken at this point.

**Comment by jhoffner** [comment]
This should be logged in the [Code Runner repo](https://github.com/Codewars/codewars-runner-cli/issues). The Haskell image should be frozen. I suppose there may be a chance it was mistakenly rebuilt - though the last deployment was 5 days ago so this issue would have appeared then. I'm not sure what is happening on the image that would cause things to suddenly change - but I know nothing about Haskell so without community help to get the image unfrozen and buildable again, I may not be able to do anything.

**Comment by jhoffner** [comment]
OK this actually was an issue with CW. I thought it was Haskell specific but it affected a few languages for CW specific reasons. The issue should be resolved now.
