### ISSUE TITLE
Unable to edit already approved kata

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#38]
It seems now I should have the power.

I tried adding some sample test case on [this kata](http://www.codewars.com/kata/extract-the-domain-name-from-a-url-1/), though, but to no avail: I keep getting a 500 Error.

Let me know if you require screenshots, additional info or the like. Thanks for your kind attention :)

**Comment by bkaes** [comment]
I'm currently mobile, so I can't check this: are you a contributor? Only
contributors can change the kata after it's been approved.

**Comment by jhoffner** [comment]
The 500 error is definitely no good. Also is the UI telling you that you have the ability to edit that particular kata?

**Comment by GiacomoSorbi** [comment]
I just went over the 3000 pts threshold today, so, yeah, I get that kind of
message for any kata, approved or not, whether I am a contributor or not:

[image: Inline image 1]

**Comment by bkaes** [comment]
As far as I can remember: yes. The "edit this kata" link is there, but
leads to a 500 if one didn't contribute during beta.

Can provide screenshots tomorrow.

**Comment by GiacomoSorbi** [comment]
Oh, so in other words I can edit approved katas, for example, once the author or an admin approves a translation of mine?

That could do for now [I just wanted to improve some older and not too perfected kata].

**Comment by GiacomoSorbi** [comment]
Just translated [this kata](http://www.codewars.com/kata/format-a-string-of-names-like-bart-lisa-and-maggie/), so once it gets approved, if you remember correctly, I should then be able to edit the kata (and add some random tests).

**Comment by GiacomoSorbi** [comment]
Not to abuse your patience, but [here](http://www.codewars.com/kata/luck-check/) is another kata that I could fix once my translation gets approved (or I can edit it somehow else).

In case you approve any of them, notify me so that I can fix the issues ASAP :)

**Comment by jhoffner** [comment]
@GiacomoSorbi your translations have been approved.

**Comment by GiacomoSorbi** [comment]
Thanks Jake, but as I just commented, regrettably I seem to still get that nasty 500 when trying to edit the kata, apparently no matter whether I am a contributor or not.

**Comment by GiacomoSorbi** [comment]
Errata corrige: apparently I get the 500 error only [in your old kata](http://www.codewars.com/kata/paginationhelper/), the others seem to be editable now: could it be a matter of having been solved more than X (500, was it?) times?

**Comment by jhoffner** [comment]
Yeah I just saw that myself and already filed an issue. I was going to downgrade its rank to 6 or 5 kyu since its an early kata and the scale wasn't as worked out back then.

**Comment by GiacomoSorbi** [comment]
I see; well, in the meantime thanks for the approval wave and I'll work trying to fix/improve the "unlocked" ones :)

**Comment by bkaes** [comment]
To answer @GiacomoSorbi's question in the thread: No, I can't edit this kata either, but occasionally I was able to edit katas. I don't really know whether this has to do with the state of the kata at the point of translation.

On the other hand, I translated "Is a number prime" after it was published, and I was still able to edit the *bug* notice last month.

**Comment by GiacomoSorbi** [comment]
Mh, as that kata has over 2000 positive submissions already and assuming it didn't get more than 1500 in a month, the thing is getting rather mysterious.

Oh, well, we'll see.

**Comment by bkaes** [comment]
For the record: I'm able to edit http://www.codewars.com/kata/collatz (there was an error in my Haskell translation).

**Comment by GiacomoSorbi** [comment]
Good to know (and I include the kata itself that I just solved and translated, not to mention is somehow refreshing to know that even a coder way better than me can make mistakes in kata translations :p), so let's see if I can too, but so should I, considering that it is a relatively new kata with few successful submissions.

**Comment by Stargator** [comment]
@jhoffner Just curious, why was this closed? Is the issue resolved somehow?
