### ISSUE TITLE
Code passes test but occurs error on submit

### ISSUE THREAD

**Issue by hoku3859** [Codewars/codewars.com#383]
Hello,

I hope this is the right forum for this, but I have been trying to solve the kata StringMerger.
When testing my code it runs fine, but when I submit it I receive a null pointer error on regex, when I am not running regex in the program.
Is this a bug?

My code:
import java.util.ArrayList;
import java.util.Arrays;

public class StringMerger {

    public static boolean isMerge(String s, String part1, String part2) {
       String[] p1 = part1.split("");
		String[] p2 = part2.split("");
		
		if (p1.length+p2.length != s.length()){
			return false;
		}
		
		ArrayList<String> sSplit1 = new ArrayList<String>(Arrays.asList(s.split("")));
		ArrayList<String> sSplit2 = new ArrayList<String>(sSplit1);
		
		for (String c : p1){
			if (!(sSplit1.remove(c))) {
				return false;
			} 
		}
		
    
		if (sSplit1.size()!=p2.length){return false;}
		for (int i = 0 ; i< sSplit1.size(); i++){
			if (!(sSplit1.get(i).equals(p2[i]))){return false;}
		}
		
		
		for (String c: p2){
			if (!(sSplit2.remove(c))){return false;};
		}
		
		
    if (sSplit2.size()!=p1.length){return false;}
		for (int i = 0 ; i< sSplit2.size(); i++){
			if (!(sSplit2.get(i).equals(p1[i]))){return false;}
		}
		
		return true;
		
    }

}

**Comment by RvdV1979** [comment]
I have exactly the same experience: https://github.com/Codewars/codewars.com/issues/381

In fact, it applies for every Java Kata which you want to submit as a final submission...

**Comment by matthewmoppett** [comment]
Same here: all Java kata are giving me the same error message on pressing "submit", regardless of the code in my test solution (i.e. even if it's just a minimal "return 0" etc.). The error message is:

java.lang.NullPointerException at java.util.regex.Matcher.getTextLength(Matcher.java:1283) at java.util.regex.Matcher.reset(Matcher.java:309) at java.util.regex.Matcher.(Matcher.java:229) at java.util.regex.Pattern.matcher(Pattern.java:1093) at clojure.core$re_matcher.invokeStatic(core.clj:4674) at clojure.core$re_find.invokeStatic(core.clj:4716) at clojure.core$re_find.invoke(core.clj:4716) at codewars.runners.java$class_name.invokeStatic(java.clj:14) at codewars.runners.java$class_name.invoke(java.clj:11) at codewars.runners.java$source_code_file.invokeStatic(java.clj:35) at codewars.runners.java$source_code_file.invoke(java.clj:30) at clojure.core$map$fn__4785.invoke(core.clj:2646) at clojure.lang.LazySeq.sval(LazySeq.java:40) at clojure.lang.LazySeq.seq(LazySeq.java:49) at clojure.lang.RT.seq(RT.java:521) at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38) at com.sun.tools.javac.api.ClientCodeWrapper.wrapJavaFileObjects(ClientCodeWrapper.java:140) at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:132) at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) at codewars.runners.java$compile_and_load.invokeStatic(java.clj:83) at codewars.runners.java$compile_and_load.doInvoke(java.clj:79) at clojure.lang.RestFn.invoke(RestFn.java:439) at codewars.runners.java$fn__599.invokeStatic(java.clj:110) at codewars.runners.java$fn__599.invoke(java.clj:105) at clojure.lang.MultiFn.invoke(MultiFn.java:229) at codewars.runners$run.invokeStatic(runners.clj:22) at codewars.runners$run.invoke(runners.clj:17) at codewars.core$_main$fn__664.invoke(core.clj:40) at clojure.lang.AFn.call(AFn.java:18) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.lang.Thread.run(Thread.java:745)

**Comment by Mattystein** [comment]
I too have this exact error. Cannot submit any Kata solutions.

**Comment by jhoffner** [comment]
This should be resolved as of earlier today.
