### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by anselmoalves** [Codewars/codewars.com#384]
Can't login into Codewars anymore. Getting the following message: "GitHub account is not linked to an existing Codewars user."
Before that, I was seeing the avatar of another user instead of mine.

**Comment by jhoffner** [comment]
There was what I thought to be a thread-safety issue caused by a config change. I had reverted that change last night - so I'm troubled to see that you only reported this an hour ago. Have you tried clearing your cache?

**Comment by anselmoalves** [comment]
@jhoffner Yes, I have. Also tried incognito window, but no luck so far.

**Comment by jhoffner** [comment]
Ok thanks for the info. I'm closing this issue as it is being tracked with #368 and #386
