### ISSUE TITLE
Logged me in as another User

### ISSUE THREAD

**Issue by brandon-thimmesch** [Codewars/codewars.com#386]
I'm not sure how this happened, but I clicked on my profile and I was logged out, so I clicked on sign in with GitHub and it signed me in as another user "Gundark". I logged out and was able to log in as myself again with the GitHub login; however, logging in as another user was alarming as I could have had full access to their account.

**Comment by jhoffner** [comment]
Yeah this has been reported a few times recently and its my highest priority right now.

**Comment by brandon-thimmesch** [comment]
I only reported it again due to the other reports indicating that they were doing something different than me when it happened. Best of luck in figuring out the cause of this!

**Comment by jhoffner** [comment]
Absolutely, thanks for reporting!

**Comment by BartoszAp** [comment]
Just wanted to give additional information. we are able to change settings, names and maybe delete accounts.

**Comment by jhoffner** [comment]
Did this just happen to you? I'm currently dealing with an issue (which seems to be getting increasingly worse) where I am logged out after every page load. They are likely linked.

**Comment by BartoszAp** [comment]
Yea, i was able to edit a name on one of the accounts(not mine)

**Comment by EJanuszewski** [comment]
I got the same, didn't get chance to try see if I can change details, but really concerning, the guy i logged in as didn't even have github linked and hasn't been on for 6 days

**Comment by jhoffner** [comment]
Did everyone here get this issue by using Github login?

**Comment by BartoszAp** [comment]
Yes

**Comment by EJanuszewski** [comment]
Yep, I've only ever used the github login

**Comment by brandon-thimmesch** [comment]
Yes, same here.

**Comment by javatlacati** [comment]
I'm not and using too github login.

**Comment by jhoffner** [comment]
Great thanks for letting me know. I believe this issue should be resolved but its hard to say, so I will leave the issue open to see if someone else reports. In the meantime I will be upgrading a number of our database components to try to resolve any further issues.

**Comment by thomzi12** [comment]
Hey -- just wanted to say the same (randomly logging out, then being logged in as a different user) is happening to me. I am using Github login.

**Comment by jhoffner** [comment]
@thomzi12 Thanks for letting me know. That sucks that it's still happening but I just came across something that might be the culprit. I'm also putting guards all over the place to at least try to catch this issue just in case. I should have it deployed shortly.

**Comment by jhoffner** [comment]
An update on this issue. The guards that I have put in place seem to be trapping the issue, so I feel a bit more confident that it has at least been prevented - though the underlying cause has yet to be identified. I believe that the underlying cause to be responsible for the majority of 500x errors that people are seeing.

**Comment by jhoffner** [comment]
#368

**Comment by Brzozova** [comment]
I have still the same problem. What can I do?

**Comment by Obround** [comment]
Bump, me too-- unable to login.

**Comment by kazk** [comment]
@Obround Please open a new issue using the issue template. A lot have changed since this was closed.
