### ISSUE TITLE
Haskell module found for tests, but not for submission

### ISSUE THREAD

**Issue by holzensp** [Codewars/codewars.com#387]
I was training on the Longest Common Subsequence kata. When I ran test it all worked fine:
![run tests](https://cloud.githubusercontent.com/assets/1875918/16024766/6b077610-31bb-11e6-9e93-1039cc393e1d.png)

Hitting submit, however, told me that the module `LongestCommonSubsequence` could not be found.
![submit](https://cloud.githubusercontent.com/assets/1875918/16024797/968c021a-31bb-11e6-8c24-7a8f714f394f.png)

**Comment by jhoffner** [comment]
This should be resolved now.
