### ISSUE TITLE
Unable to Submit any Kata solutions (NullPointerException...)

### ISSUE THREAD

**Issue by Mattystein** [Codewars/codewars.com#388]
I cannot submit any Kata solutions as each time I get errors starting with NullPointerException (full output below). Seems to be since the server migration for me.

I can Run Tests with no issues, and pass the tests but unable to Submit.

Kata's that this error confirmed to occur every time for me:
https://www.codewars.com/kata/which-are-in
https://www.codewars.com/kata/leonardo-dicaprio-and-oscars
https://www.codewars.com/kata/regexp-basics-is-it-a-digit

It appears that all Kata are affected for me.

`
java.lang.NullPointerException at java.util.regex.Matcher.getTextLength(Matcher.java:1283) at java.util.regex.Matcher.reset(Matcher.java:309) at java.util.regex.Matcher.(Matcher.java:229) at java.util.regex.Pattern.matcher(Pattern.java:1093) at clojure.core$re_matcher.invokeStatic(core.clj:4674) at clojure.core$re_find.invokeStatic(core.clj:4716) at clojure.core$re_find.invoke(core.clj:4716) at codewars.runners.java$class_name.invokeStatic(java.clj:14) at codewars.runners.java$class_name.invoke(java.clj:11) at codewars.runners.java$source_code_file.invokeStatic(java.clj:35) at codewars.runners.java$source_code_file.invoke(java.clj:30) at clojure.core$map$fn__4785.invoke(core.clj:2646) at clojure.lang.LazySeq.sval(LazySeq.java:40) at clojure.lang.LazySeq.seq(LazySeq.java:49) at clojure.lang.RT.seq(RT.java:521) at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38) at com.sun.tools.javac.api.ClientCodeWrapper.wrapJavaFileObjects(ClientCodeWrapper.java:140) at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:132) at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) at codewars.runners.java$compile_and_load.invokeStatic(java.clj:83) at codewars.runners.java$compile_and_load.doInvoke(java.clj:79) at clojure.lang.RestFn.invoke(RestFn.java:439) at codewars.runners.java$fn__599.invokeStatic(java.clj:110) at codewars.runners.java$fn__599.invoke(java.clj:105) at clojure.lang.MultiFn.invoke(MultiFn.java:229) at codewars.runners$run.invokeStatic(runners.clj:22) at codewars.runners$run.invoke(runners.clj:17) at codewars.core$_main$fn__664.invoke(core.clj:40) at clojure.lang.AFn.call(AFn.java:18) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.lang.Thread.run(Thread.java:745) 
0 Passed
0 Failed
1 Errors
Process took 2173ms to complete`

**Comment by jhoffner** [comment]
OK, it looks like all Java kata may be affected. I'll look more into this tomorrow. Have you noticed any issues with non-java kata?

**Comment by Mattystein** [comment]
I haven't actually done any Kata in other languages unfortunately, so I can't say.

**Comment by bryangators** [comment]
Any update? I tried signing up yesterday with java and I am positive I used the correct syntax on the test and was getting errors. I had to use python to join. Now i passed all tests for the first challenge and it is giving me a null pointer exception as well

**Comment by jhoffner** [comment]
OK I've identified the issue. A fix should be deployed within the hour.

**Comment by bryangators** [comment]
Awesome thank you!
