### ISSUE TITLE
Typo in 3000+ Honor message

### ISSUE THREAD

**Issue by the-zebulan** [Codewars/codewars.com#389]
I was very happy to achieve this milestone today on Codewars. I noticed the letter `v` missing from the word `have` and just wanted to let you guys know.

![message](https://cloud.githubusercontent.com/assets/7484300/16060085/445ec4a4-3243-11e6-84b0-8bb88c6c44a0.png)

**Comment by DonaldKellett** [comment]
Congrats @the-zebulan ! :smile:  It sure feels good to finally become a moderator doesn't it?

**Comment by the-zebulan** [comment]
Thanks @DonaldKellett !

I didn't know how people became moderators until today. I've been learning Python for two years but I have improved my knowledge exponentially since finding Codewars. It just seems appropriate to try to give back and help make Codewars better in whatever small way I can.

*With great power comes great responsibility.* :smiley:

**Comment by jhoffner** [comment]
Thanks @the-zebulan (and congrats). This has been fixed.

**Comment by the-zebulan** [comment]
@jhoffner ,

Thank you for the fix and the great website!
