### ISSUE TITLE
Tests not submitted suddenly after working for an hour

### ISSUE THREAD

**Issue by dfrho** [Codewars/codewars.com#390]
Had this problem intermittently all day. Jake said it's because of the new server...

on JS "Math Matters" kata. I hope this gets fixed before my bootcamp starts. Thanks for your efforts.

**Comment by jhoffner** [comment]
Are they not submitting at all or are you not able to finalize your solution? Also, does the "Run Tests" button work?

**Comment by dfrho** [comment]
They were submitting tests for an hour then stopped. Can't finalize.

**Comment by jhoffner** [comment]
This is same as #391, should be resolved now.
