### ISSUE TITLE
There was an issue submitting your final solution

### ISSUE THREAD

**Issue by VincentNewkirk** [Codewars/codewars.com#391]
On the 'Argue the toss' JS Kata my solution passes all tests. However, I get this error message when trying to submit the solution. "There was an issue submitting your final solution".

function anArgument() {
  var endString = ''
  var firstArg = '"' + arguments[0] + '"';
  if( arguments.length === 1){
    return 'You gave me 1 argument and it is ' + '"' + arguments[0] + '"' + '.';

  } else if ( arguments.length === 0) {
  return "You didn't give me any arguments.";

  } else {
    for ( var i = 1; i < arguments.length; i++ ) {
      if( i + 1 === arguments.length ){
      endString += ' and ' +'"' + arguments[i]+ '"' + '.';

      } else {
        endString += ', ' + '"' + arguments[i] + '"';
      }
    }
   return 'You gave me ' + arguments.length + ' arguments and they are ' + firstArg + endString;
  }
}

**Comment by jhoffner** [comment]
Thanks for reporting. I've seen this come up in the logs a few times today. It looks like it happens for specific kata + user combinations. My theory is that a database upgrade by our hosting provider has caused the issue. The ORM we are using is in bad need of an upgrade which I am starting work on tomorrow and should have it done and tested hopefully within a few days. Right now I believe that is the best hope to resolve the issue.

**Comment by anter69** [comment]
Just dropped in to confirm that I have the same issue on multiple katas, e.g.
* https://www.codewars.com/kata/algebraic-string/python
* https://www.codewars.com/kata/noobcode-04-hot-singles-dot-dot-dot-compare-two-arrays-return-the-unpaired-items/python

(logged in as this GitHub user)

**Comment by dguard** [comment]
Have similiar issue like **anter69** for most of katas, eg:

https://www.codewars.com/kata/ipv4-parser/solutions/javascript
https://www.codewars.com/kata/551e949bbf4e52c106000aed

(logged as github user)

**Comment by r080te4** [comment]
Have the same issue with js katas.
When I publish the first solution it works well.
If I press Train Again and try to push new solution I'll have
"There was an issue submitting your final solution" message
If I'll press many times it can suddenly work, but not always.
If I return there later, it can suddenly work, but not always.
Example kata:
https://www.codewars.com/kata/574c5075d27783851800169e

**Comment by r080te4** [comment]
If I force the SUBMIT FINAL button after getting the issue, sometimes I have a normally working solutions page, sometimes I switch to my solutions and see that my last solution (2nd or 1st) is not listed (If check after time they are ok). And once I had a message that the solutions are locked for me cause I haven't finished the kata yet after the SUBMIT FINAL.

p.s.
also have
- 500 error many times 
- 404 error few times 
- cloudware message
ater pressing the SUBMIT FINAL button

**Comment by jhoffner** [comment]
Thanks for the details. This was an issue before the site infrastructure was changed, but it looks to have become more common after the transition. I'm working on some site updates to hopefully take care of the root issue.

**Comment by treefingers11** [comment]
I started experiencing this issue this evening, as well.  It occurs with every kata I try.

Although I suspect this may not make a difference, I am only working on JS katas.

**Comment by PiotrBerebecki** [comment]
I have the same issue - I'm getting "There was an issue submitting your final solution" message whenever I try to submit JavaScript katas. I'm logged in a GitHub user.

**Comment by mingrammer** [comment]
I have the same issue with python

**Comment by Em-Ant** [comment]
Yesterday I had the same issue on this kata https://www.codewars.com/kata/526a569ca578d7e6e300034e/train/javascript. Today it cannot be loaded at all. The ruby version loads, but cannot be submitted.

**Comment by anter69** [comment]
I just solved a kata, it worked fine. However, when I tried to submit a new solution (somewhat different) then I got the _"There was an issue submitting your final solution"_ error message.

**Comment by jhoffner** [comment]
I've deployed a fix that should hopefully solve this, based off of some of the examples that I've found and tested.

**Comment by mingrammer** [comment]
I've tested 'submit final' few minutes ago, but same error is occured again ... (submit before final is fine)

test problem : https://www.codewars.com/kata/5747fcfce2fab91f43000697/train/python

**Comment by Em-Ant** [comment]
It works ( and it's really fast )  for  https://www.codewars.com/kata/526a569ca578d7e6e300034e/train/javascript. Thanks.

**Comment by sek** [comment]
As far as the "possible fix deployed" tag, I'm able to log in fresh, train again on this kata: https://www.codewars.com/kata/5626b561280a42ecc50000d1, submit and submit final, and get the same error every time still.

**Comment by anter69** [comment]
I still get the same error message on at least two katas.

**Comment by znalbert** [comment]
Just had this issue on https://www.codewars.com/kata/56269eb78ad2e4ced1000013/train/javascript while logged in as a github user.

**Comment by Em-Ant** [comment]
I'm having problems refactoring this https://www.codewars.com/kata/551f23362ff852e2ab000037/train/javascript/5763bd8b1d8b623f5c0001a7

**Comment by gege83** [comment]
Hi everyone,

Same error for solutionId = 5764fea1edc6f7a9450001ca
request for /api/v1/code-challenges/projects/575d92c5fcee864674000639/solutions/5764fea1edc6f7a9450001ca/finalize
the respons is the following: 
{"success":false,"message":"Code can't be blank, Finalized Finalized cannot be true unless completed_at is set, Finalized Finalized cannot be true unless code is set","errors":[{"reason":"Code can't be blank, Finalized Finalized cannot be true unless completed_at is set, Finalized Finalized cannot be true unless code is set","fields":["code"]},{"reason":"Finalized Finalized cannot be true unless completed_at is set","fields":["finalized"]},{"reason":"Finalized Finalized cannot be true unless code is set","fields":["finalized"]}],"error":422}

**Comment by HLFH** [comment]
@jhoffner Same issue: *There was an issue submitting your final solution*. So, I can't submit my final solution on https://preview.codewars.com/kata/570cc83df616a85944001315/, and I don't know but Word Count is in my list of solved katas:
![capture d ecran 2016-06-18 a 16 59 20](https://cloud.githubusercontent.com/assets/2359059/16171700/06a98b36-3576-11e6-8459-f3fab899dcd7.png)

And yet, I didn't submit any solution because I'm getting the issue. So, I don't understand why this kata is in my list of solved katas.

**Comment by pwynn** [comment]
Having the same issue.  I passed a kata but the author decided on some changes making my solution invalid. Passed all tests again but receive "There was an issue submitting your final solution".

**Comment by anter69** [comment]
The issue persists: I just completed kata 5676f07029da352ba2000065, the solution was submitted successfully -- however, when trying to submit a different solution, I get the usual error message.

I would be happy to provide more details if needed, just explain where/how to extract it from the browser (chrome).

**Comment by juliankolbe** [comment]
Same here with this kata: https://www.codewars.com/kata/573c84bf0addf9568d001299.
It says i have past solutions, and when I submit final it adds +1 to the solved counter, but when I refresh its gone again and it still says I have not solved it

**Comment by lhaggar** [comment]
I've managed to reproduce this with the following steps (may not be the only cause?):

1. Complete kata so tests pass
2. Submit kata but do not submit final
3. Navigate away from page, to discussion page for example
4. Notice honor increase, and completed status on profile, but you can't see other warriors solutions
5. Re-train kata, copy previous solution from past solutions tab
6. Submit solution, then attempt to submit final - you'll get the error message.

**Comment by anter69** [comment]
The issue seems to be mostly gone. Thanks!

**Comment by znalbert** [comment]
Final submit just worked for me.  Thanks, guys!

**Comment by jhoffner** [comment]
Awesome. Yeah it ended up being caused by a irreversible DB upgrade and a 3 year old bug in Mongoid that I tracked down and monkey patched. I'll leave this open for a bit longer just because there may be some straggler accounts that need to be repaired.

**Comment by mingrammer** [comment]
The issue seems to be fixed. Thanks.

**Comment by Em-Ant** [comment]
@jhoffner I still cannot **refactor** or **train again** this [kata](https://www.codewars.com/kata/551f23362ff852e2ab000037/train/javascript) and submit a new solution, both in ruby and js. I get server timeout or unknown error. Do you think it is a different issue ?

**Comment by GeoWill** [comment]
Thanks for your work on this
For Twice Linear in Python:
I've been able to submit my final solution now, but solutions section of kata is still locked.

**Comment by l7b** [comment]
Please help me. Similar error
![default](https://user-images.githubusercontent.com/18369080/43423170-53a10a1a-9454-11e8-8040-c6ed8b31b87c.png)

**Comment by l7b** [comment]
Please help me. Similar error
![default](https://user-images.githubusercontent.com/18369080/43423379-f894f8b0-9454-11e8-94c0-1f0c39bfb158.png)

**Comment by oucema001** [comment]
i have the same problem and i am logged as a github user as well
