### ISSUE TITLE
No test were provided or constant time out.

### ISSUE THREAD

**Issue by vsarunov** [Codewars/codewars.com#393]
On kata Weight for Weight(5kyu) I constatly get a timeout despite the server status is showing everything is ok, as well as when I press "Run Tests" the following(screenshot) comes up
![image](https://cloud.githubusercontent.com/assets/13823101/16076253/5287083c-32ea-11e6-8fda-c070e1f87353.png)

I thought it mind be just one day issues on 14/06/2016, today I tried again and met the same issues.

P.S I am using C#.

**Comment by vsarunov** [comment]
Faced exactly the same problem with another kata, now I might consider that something is wrong with the server.

**Comment by r080te4** [comment]
Faced problem for different js kata. 
Retry to push solution helped.

**Comment by Em-Ant** [comment]
The same on this kata https://www.codewars.com/kata/526a569ca578d7e6e300034e/train/javascript

**Comment by GaKSmith** [comment]
Had this problem with several kata and multiple languages.

One of which is https://www.codewars.com/kata/540c33513b6532cd58000259/train/clojure

I think it's the random tests might be too much for the server.

**Comment by r080te4** [comment]
For js kata:
Now occurs simultaneoulsly with 'Unknown error'.
Button repush don't help, page refresh don't help.
';' in the end of the line helped many times.

**Comment by r080te4** [comment]
With ';' at the end of the line, issue occued, but button repush helped.

**Comment by r080te4** [comment]
I guess it is related to #394.

**Comment by Em-Ant** [comment]
Today this https://www.codewars.com/kata/526a569ca578d7e6e300034e/train/javascript cannot be loaded at all.
