### ISSUE TITLE
"Unknown error" while submitting solution

### ISSUE THREAD

**Issue by oduvan** [Codewars/codewars.com#394]
<img width="869" alt="screen shot 2016-06-15 at 1 21 16 pm" src="https://cloud.githubusercontent.com/assets/265844/16076448/16c1ed6e-32fc-11e6-9adf-b5c13df1411a.png">

For mission "Binary Addition"

**Comment by r080te4** [comment]
Same issue with js on many kata.

**Comment by oduvan** [comment]
Thank you for answering.

Keep up a good work

**Comment by Em-Ant** [comment]
+1

**Comment by bibodha** [comment]
The console shows that it's throwing a 401: Unauthorized.

**Comment by jhoffner** [comment]
This looks to be related to #382

**Comment by hmfoster** [comment]
+1

**Comment by r080te4** [comment]
For js kata:
Now occurs simultaneoulsly with 'no tests provided'.
Button repush don't help, page refresh don't help.
';' in the end of the line helped many times.

**Comment by r080te4** [comment]
With ';' at the end of the line, issue occued, but button repush helped.

**Comment by r080te4** [comment]
I guess it is related to #383.
