### ISSUE TITLE
Comments is invalid

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#396]
When I try to update one of my Katas for a language ( C# ) that hasn't been solved more than 500 times it shows the error:

>comments is invalid

¿What does this mean?¿Is it documented anywhere?¿How can I solve it?

**Comment by javatlacati** [comment]
Is this for that code? <xmp>```c#
   Solution.Main("parameter1", "parameter2","parametern")
```</xmp>

**Comment by jhoffner** [comment]
OK thats likely caused by a data issue that related to you or anything you can fix. Which kata is it?

**Comment by javatlacati** [comment]
https://www.codewars.com/kata/57036f007fd72e3b77000023/edit/csharp

**Comment by javatlacati** [comment]
id doesn't pass with c# or csharp on the description :/

**Comment by jhoffner** [comment]
OK this lead me to a weird data issue (empty comments being saved). I fixed the data. This might be a cause of some other issues. Haven't determine the underlying cause yet though. Please let me know if you can save now.

**Comment by javatlacati** [comment]
Can save now Ty :bow:
