### ISSUE TITLE
Bad link for Comments for Translation Kumites

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#397]
If you analyze the html from the dashboard feed you could nottice that no links are generated for comments regarding Kata translation on the Kumite section of the translation.
Beside if you can look there's an extra `"`
![err cw](https://cloud.githubusercontent.com/assets/1063901/16092439/857530ee-32fd-11e6-8e87-8e4a4422b94e.PNG)

**Comment by kazk** [comment]
Closing as duplicate of #68
