### ISSUE TITLE
After few deconnexion. Loose all the honor point.

### ISSUE THREAD

**Issue by mcamuzat** [Codewars/codewars.com#398]
hello, 

I have a huge number of disconnections. after the last disconnection I loose all the honor point.

I keep the level, and my position but the honor is 0. is it possible to do something ?

https://www.codewars.com/users/mcamuzat

thank in advance

**Comment by jhoffner** [comment]
Thats strange. I'll look into this more. Though don't worry, that value is just a cached/denormalized calculation. It should have fixed itself on the next action that you took that earned you honor, but regardless I have went ahead and trigger the update for you so you should be good now. I'll leave this ticket open until i am able to debug it further.

**Comment by mkousta** [comment]
This happened to me too, some minutes ago https://www.codewars.com/users/faiakismk

**Comment by mcamuzat** [comment]
Perfect. 
@jhoffner thank you for your reactivity !
