### ISSUE TITLE
Training page loaded with light theme

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#399]
<img width="1678" alt="train__incorrect_array_remove_method___codewars" src="https://cloud.githubusercontent.com/assets/579835/16103242/91af105e-332b-11e6-8cf9-fdd93d2581ac.png">

Chrome, OSX, No error was shown in console. `App.data.theme == 'inverted'`. 

Only train page is inverted. I must logout and back in to fix.

**Comment by kazk** [comment]
Closing this because I believe it's been fixed.
