### ISSUE TITLE
Unable to publish Sass Kumite

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#400]
Today I just authored a Sass Kumite and clicked on the "Publish" button; however, upon publishing, I realized that my honor did not increase at all.  Upon double-checking, I found out that my Kumite was not visible in the "Kumite" section and that the Kumite was not published at all (it was still in the "Drafts" section).

The screenshots below explain this in more detail:

1. After publishing the Sass Kumite, it can nowhere be found in the public "Kumite" section: ![2016-06-16 10 49 00](https://cloud.githubusercontent.com/assets/7777884/16103994/f5895cfe-33af-11e6-960e-c6efae4f5987.png)
1. After navigating to my user profile and selecting "Kumite -> Published", the Sass kumite still cannot be found. ![2016-06-16 10 49 51](https://cloud.githubusercontent.com/assets/7777884/16104013/110cbba6-33b0-11e6-86ea-e012bb09c832.png)
1. I then selected "Kumite -> Drafts" instead and found my Sass kumite (still) lying there: ![2016-06-16 10 51 40](https://cloud.githubusercontent.com/assets/7777884/16104039/5a4eb346-33b0-11e6-9f92-2842f78c6b43.png)
1. When I click on the Kumite title to view the Kumite, it can be seen that the "Fork" button is missing, confirming that the Kumite is not published despite the fact that I clicked on the "Publish" button: ![2016-06-16 10 51 50](https://cloud.githubusercontent.com/assets/7777884/16104040/5ccac006-33b0-11e6-8466-657ebceb73d8.png)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1eff) by [Unito](https://www.unito.io)

**Comment by jhoffner** [comment]
Thanks for the details. I think I saw the error log for this. The system tried to run Sass in order to save its output, but the runner doesn't support the language.

**Comment by DonaldKellett** [comment]
Thanks for the reply and explanation @jhoffner 

I understand that Sass is not supported by Codewars yet but is there any way (workaround) to make it publish successfully without the runner trying to execute the code (and fail)?

**Comment by dantesolis** [comment]
@jhoffner  & @DonaldKellett  just following up on since I would like to write a kata  in scss. How could one add support to `scss` or `sass`. Thanks.

**Comment by javatlacati** [comment]
@dantesolis about the sass support please follow [this issue](https://github.com/Codewars/codewars-runner-cli/issues/584) on the codewars runner project

**Comment by dantesolis** [comment]
@javatlacati are you referencing the [issue-584](https://github.com/Codewars/codewars-runner-cli/issues/584). And thanks for letting me know. Will try to create/publish one.

**Comment by kazk** [comment]
Closing because Sass kumite is no longer supported.
Adding support for CSS+HTML is tracked by https://github.com/codewars/runner/issues/21
