### ISSUE TITLE
There was an issue submitting your final solution

### ISSUE THREAD

**Issue by sek** [Codewars/codewars.com#403]
I have been able to successfully submit a second solution to a kata in some cases, but I am now getting the same error attempting to submit a new solution to a kata I've previously solved, for both Python and Java, so I thought it may be worth reporting.  "Run Tests" and "Submit" both pass, but the "Submit Final" shows a red bar **"There was an issue submitting your final solution"** - I've tried many times, so I think I've ruled out a network issue =)

Strangely the failed submissions **do** show up in some of the views. ex: "Compare with your solution" - so maybe despite the error, the solution was saved.  However it doesn't show up in some others - ex: "My Solutions"

**Comment by r080te4** [comment]
#391 
Already created.

**Comment by sek** [comment]
I searched just before entering, strange that the existing issue didn't show up. This should be closed as duplicate.

Same as many on #391 I am logged in as github user
As far as the "possible fix deployed" tag, I'm able to log in fresh, train again on this kata: https://www.codewars.com/kata/5626b561280a42ecc50000d1, submit and submit final, and get the same error every time right now.
