### ISSUE TITLE
"No Tests Were Provided" (old, recurring issue)

### ISSUE THREAD

**Issue by dfrho** [Codewars/codewars.com#405]
![train__return_specifics_from_an_object____codewars](https://cloud.githubusercontent.com/assets/3064557/16125208/9c4a26ee-33c0-11e6-81f2-980f6878d17f.jpg)

Recurring issue since Monday of this week....Jake says its the new server. Would love to have a stable learning environment, soon.

**Comment by jhoffner** [comment]
BTW I noticed your screen is white. Did you mean to select the light theme or did it load like that for you? Another bug was logged about this, just trying to gauge how often it happens.

**Comment by dfrho** [comment]
Yeah I chose the white - will turn it off Jake, thanks. I also learned how
to write my own tests which helped clear the last issue -- I had cut and
pasted the function call from the test area into repl.it then couldn't get
it to reset, so just rewrote Test.assert.

David

**Comment by jhoffner** [comment]
OK thanks. NP you can keep the white! :) Was just making sure you choose it and it didn't choose you.

**Comment by dfrho** [comment]
Right! lol. I glossed over that...thought it might be part of the bug, lol.
Thanks Jake!
