### ISSUE TITLE
Upvote is failing

### ISSUE THREAD

**Issue by Vort** [Codewars/codewars.com#406]
When I try to upvote this kata:
https://www.codewars.com/kata/deodorant-evaporator/cpp
, nothing happens.
After looking at browser's debug information, I have found this response:
`{"success":false,"message":"Languages is invalid","errors":[{"reason":"Languages is invalid","fields":["languages"]}],"error":422}`
Probably this is related to newly implemented C++ support.

**Comment by Vort** [comment]
Similar problem here:
https://www.codewars.com/kata/closest-pair-of-points/discuss/javascript
`{"error":"The operation: #<Moped::Protocol::Command @length=74 @request_id=3690 @response_to=0 @op_code=2004 @flags=[] @full_collection_name=\"app7940682.$cmd\" @skip=0 @limit=-1 @selector={:getlasterror=>1, :safe=>true} @fields=nil> failed with error 16837: \"cannot use the part (1 of comments.5.comments.1._id) to traverse the element ({1: null})\" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.", "type":"OperationFailure"}`

**Comment by jhoffner** [comment]
The fix for this has been deployed and tested.

**Comment by Vort** [comment]
Error at second kata (closest-pair-of-points) is fixed, thanks.
But first kata (deodorant-evaporator) still gives "Languages is invalid" error.
