### ISSUE TITLE
Comments in Kata Solution not loaded/displayed/published properly

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#409]
![2016-06-17 10 36 09](https://cloud.githubusercontent.com/assets/7777884/16154195/5af184e0-34dc-11e6-8dc7-6a3ad5da00f5.png)

As can be seen from the screenshot above, the website acknowledges that 3 comments in total have been published on that particular Kata solution; however, for some reason, only the first comment is being shown no matter how many times I reload the page or log in again.

I suspect that this bug has to do with the "Cross Origin Policy" as depicted in the screenshot below showing the console errors:

![2016-06-17 10 36 44](https://cloud.githubusercontent.com/assets/7777884/16154482/9cba2944-34dd-11e6-9775-32bcf548d543.png)

**Comment by jhoffner** [comment]
There was a rare data issue caused by when someone edited a comment under certain conditions. This was due to a low level ORM driver issue. Some comments may be lost due to that. The fix is deployed now so you shouldn't see this issue again.
