### ISSUE TITLE
"typescript" replaced by "jscript" in description

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#411]
I wanted to modify the description of https://www.codewars.com/kata/5547cc7dcad755e480000004 when I added the typescript translation but when I write with the usual 3 backticks

typescript
removeNb(26) should return [[15, 21], [21, 15]]
removeNb(100) should return []

I get after re-publishing:

jscript
removeNb(26) should return [[15, 21], [21, 15]]
removeNb(100) should return []

"typescript" is replaced by "jscript" and so examples don't appear in the description of the kata for those who want to take the kata in Typescript.

Same thing in https://www.codewars.com/kata/pi-approximation/typescript and others... e.g https://www.codewars.com/kata/rectangle-into-squares/typescript.

**Comment by kazk** [comment]
Fixed. See #426
