### ISSUE TITLE
Can't re-train on a problem

### ISSUE THREAD

**Issue by JamesBrill** [Codewars/codewars.com#412]
I completed [this problem](https://www.codewars.com/kata/molecule-to-atoms/train/javascript) in JavaScript, realised I hadn't removed my debugging output and went back to "re-train" to submit a fixed solution. But all I ever see on that page is "Loading kata...". I can access the training pages for the other 3 languages just fine. I can also still access the JavaScript solutions.

<img width="762" alt="screen shot 2016-06-19 at 16 20 15" src="https://cloud.githubusercontent.com/assets/2140027/16178206/d1fb2664-3639-11e6-8901-27dbc8c1fb4a.png">

**Comment by jhoffner** [comment]
Latest deployment should resolve the issue

**Comment by JamesBrill** [comment]
Sadly not - the issue persists.

**Comment by kazk** [comment]
Closing old issue. Please open a new issue if this problem is still there.
