### ISSUE TITLE
Site timeouts when trying to solve the same Kata in multiple languages

### ISSUE THREAD

**Issue by ghost** [Codewars/codewars.com#413]
Running into frequent site timeouts when trying to solve the same Kata in multiple languages. I have now seen this error pattern on multiple Kata and I am confident it is not an Algorithmic issue related to language specifics. I am able to solve the Kata in Python(or some other language) and then move on to others such as Ruby or Javascript and the solution will pass the test cases but when submitted to the server it times out. This series of errors started about a week ago and has affected multiple Kata including:

7 kyu
Reduce My Fraction
https://www.codewars.com/kata/576400f2f716ca816d001614/train/javascript
![screenshot from 2016-06-19 14 11 25](https://cloud.githubusercontent.com/assets/7141278/16179866/d02ccc00-3627-11e6-9d87-cb3cead6af1b.png)

Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremely busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated.

**Comment by Vassah** [comment]
I'm also experiencing this issue, have been for at least a few days.
7kyu
Sorting Dictionaries
https://www.codewars.com/kata/53da6a7e112bd15cbc000012/train/python

**Comment by error256** [comment]
I'm not sure if it's the same problem. I'm getting "Submission timed out..." for https://www.codewars.com/kata/find-the-motif-in-dna-sequence in Python and JS.

**Comment by jhoffner** [comment]
@error256 I just tested, I'm not getting issues. What does your network inspector say? Any failed XHR calls?

**Comment by error256** [comment]
No, no XHR errors or other suspicious things.

**Comment by jhoffner** [comment]
Improvements have been made recently. Not sure if this is still a nagging issue, though I do expect there to be failures from time to time.

**Comment by rollietikes** [comment]
Thanks I have noticed the site performance improvements.

**Comment by kazk** [comment]
Closing this because the issue seems resolved, please let me know if it's not.
