### ISSUE TITLE
Solution which didn't pass tests accepted.

### ISSUE THREAD

**Issue by GeoWill** [Codewars/codewars.com#415]
kata: Twice linear (5kyu python)
user: will_r
I was still figuring this kata out, and had a solution which passed basic tests but no the 'submit' tests. After opening the discussion page in another tab my solution was at some point accepted while I was checking email. 
I have since created a correct solution, but am now getting solution submission error similar to: 
https://github.com/Codewars/codewars.com/issues/391

**Comment by jhoffner** [comment]
This issue should be resolved. If not then please comment on #391
