### ISSUE TITLE
unable to view solved kata's javascript solutions

### ISSUE THREAD

**Issue by almarkov** [Codewars/codewars.com#416]
https://www.codewars.com/kata/build-a-pile-of-cubes/solutions/javascript
probably, after i wrote comment and upvoted some other comments

**Comment by jhoffner** [comment]
This is likely related to #391

**Comment by dcsmith926** [comment]
Got basically the same exact thing, for a Kata I authored, still in Beta: https://www.codewars.com/kata/priori-incantatem/solutions

I attempted to comment on somebody's solution, but after hitting "Reply" nothing happened. So I refreshed, and now a 500 error occurs each time I try to view solutions.

**Comment by jhoffner** [comment]
This issue should be resolved now.
