### ISSUE TITLE
Always server error with c++ solutions

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#417]
Each time I try to get C++ solutions of a kata  I get:

`Looks like there was a server error! (500)...`

Example: <https://www.codewars.com/kata/which-are-in/solutions/cpp>

**Comment by g964** [comment]
Now I get "The kata failed to load. Please try reloading the page" again and again.

**Comment by g964** [comment]
I just saw that it happens in almost every language:-(

**Comment by jhoffner** [comment]
All kata or just specific ones? I'm still dealing with a database upgrade issue that is causing data problems when loading. It only affects some records.

**Comment by g964** [comment]
I can't try all my katas:-). I tried a few in different languages and it happens that they load in one or two languages but not in the other ones. Thanks for your work!

**Comment by jhoffner** [comment]
Do you have repro steps. I don't have a lot to go on at the moment. I also deployed a bunch of updates today so the problem may have resolved itself.

**Comment by g964** [comment]
Seems to work now, thanks!
