### ISSUE TITLE
ruby - fundamental section

### ISSUE THREAD

**Issue by FrcTeam4464** [Codewars/codewars.com#418]
Tried to the longest palindrom and triangle_type problems. It passes all the tests but does not let me submit. Not able to proceed further. It gives an "unknown error"
It looks like the problems I pick pass but does not get submitted for credit.
Thanks for any resolution you might have.

**Comment by FrcTeam4464** [comment]
In the above the user name is psatya@aol.com

**Comment by jhoffner** [comment]
Thanks for logging. This is the same issue as #388. Closing as a duplicate.

**Comment by FrcTeam4464** [comment]
Thanks.


-----Original Message-----
