### ISSUE TITLE
Can't submit a solution for 'Reduce My Fraction' kata

### ISSUE THREAD

**Issue by Homy** [Codewars/codewars.com#420]
All tests passing, but it fails when i submit:

> Process was terminated. It took longer than 7000ms to complete
> 0 Passed
> 0 Failed
> 0 Errors

the solution:
```
def reduce(fraction):
    m = min(fraction)
    fr = 1
    r = (range(1,m+1))
    r.reverse()
    for i in r:
        if fraction[0]%i == fraction[1]%i == 0:
            fr = i
            break
    new_fraction = [item/fr for item in fraction]
    return new_fraction
```
the issue persists for 3 days already

**Comment by jhoffner** [comment]
This was likely caused due to an issue on the code runner servers. You should be good now, if not then there is something specific to your account that is happening.

**Comment by Homy** [comment]
still the same...tried  to relogin, it didnt help
Process was terminated. It took longer than 7000ms to complete
0 Passed
0 Failed
0 Errors

**Comment by Homy** [comment]
Also sometimes it gives different message:

Unknown error

Nope! Try again.Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated.

Unknown error
Process took 4046ms to complete
