### ISSUE TITLE
Can't Add specific description  for typescript

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#426]
For [this Kata](https://www.codewars.com/kata/57642a90dee2da8dd3000161/) I've tried to add specific code description for every lnaguage but can't do this for TypeScript.

Already tried with

``````
```typescript
arr2bin [1,2] == '11'
arr2bin [1,2,'a'] == '11'
arr2bin [] == '0'
```
``````

But nothing gets saved. What I'm doing wrong?

**Comment by g964** [comment]
I add the same problem. See: "typescript" replaced by "jscript" in description (#411), labelled as a bug Now the reference disappears completely.

**Comment by kazk** [comment]
Seems to be working now.

**Comment by javatlacati** [comment]
confirmed I can see ti too. Thank you sir.
