### ISSUE TITLE
Can not be approved, error 500

### ISSUE THREAD

**Issue by smile67** [Codewars/codewars.com#427]
https://www.codewars.com/kata/especially-joyful-numbers/

https://www.codewars.com/kata/sum-of-array-averages/

Thanks;-)!

**Comment by DonaldKellett** [comment]
#316

**Comment by brendanvos** [comment]
@smile67 @jhoffner @kazk Can likely be closed as duplicate was closed by jhoffner

**Comment by kazk** [comment]
Closing this because this is a duplicate of #316 and it has been fixed.
