### ISSUE TITLE
Process was terminated. It took longer than 10000ms to complete

### ISSUE THREAD

**Issue by pr4s4n** [Codewars/codewars.com#43]
My code shows it is correct when i hit run tests and when i try to submit it it shows the "Process was terminated. It took longer than 10000ms to complete".

Please help me fix it I am pretty new here.

Thanks

**Comment by bkaes** [comment]
It's about [shorter concat reverse longer](http://www.codewars.com/kata/shorter-concat-reverse-longer/discuss/java), right? You're probably using a sup-par algorithm, and therefore need more than 10 seconds.

Issues like these (usually) aren't connected to the codewars-engine and should be discussed on the kata's discussion site instead.
