### ISSUE TITLE
Can't fully switch from light to dark theme (or vice versa)

### ISSUE THREAD

**Issue by paul-calvelage** [codewars/codewars.com#432]
I experienced this using Chrome 51 on Windows 10.  I haven't tested this on other browsers.

**Steps to reproduce**:
1. While training on a kata, attempt to switch from light to dark, or from dark to light theme using the moon and sun icons.

**Buggy Behavior**: Only the "Your Solution" and "Your Test Cases" areas change color to the new theme, resulting in the weirdness shown in these screenshots:
![darktolight](https://cloud.githubusercontent.com/assets/5090280/16562289/90ce1dda-41ca-11e6-959e-2fef55852812.png)
![lighttodark](https://cloud.githubusercontent.com/assets/5090280/16562293/93cb3b8a-41ca-11e6-91e2-8a9dcd6f53a0.png)

**Expected Behavior**:  The entire workspace should change, as below (pressing F5 to reload accomplishes this as a workaround):
![dark](https://cloud.githubusercontent.com/assets/5090280/16562362/adac58fe-41ca-11e6-8f73-03c689b607fd.png)
![light](https://cloud.githubusercontent.com/assets/5090280/16562365/b0804dba-41ca-11e6-8139-229eba1f9407.png)

Link: https://www.codewars.com/kata/uppercaseplace/train/javascript

**Comment by DonaldKellett** [comment]
Same problem experienced in Safari (v9?) on OSX El Capitan (10.11.x)

**Comment by MurKit** [comment]
A little different problem on Firefox at Linux Mint. 
I don`t know if that problem appeared after the latest update, but please fix it. 
Every time I start new training theme becomes light. There is no option to choose DAY\NIGHT as earlier. So I have to reload the page and then theme becomes dark again.
Very strange. 
![screenshot at 2016-07-05 23 28 34](https://cloud.githubusercontent.com/assets/13369896/16598834/78107e16-4308-11e6-9150-d89a7fcc7aa5.png)

**Comment by davidhu2000** [comment]
Also, the night/light theme randomly switches between katas. Whenever i finish one, and click next kata, the theme automatically switch to light mode.

**Comment by s2k** [comment]
In my context [Safari 9.1.1 (11601.6.17) on OS X 10.11.5 (15F34)] the theme switches randomly _and_ partially. For example most of the page is using the light theme, but the profile menu is shown in dark.

This happens even without touching the sun/moon icons at all.

**Comment by aryan-firouzian** [comment]
I also face the same problem. I always want to have dark theme, while the page randomly load with light theme by default. I use chrome, version 51.0.2704.103.

**Comment by aaronransley** [comment]
Same problem here, both with random theme switches on kata load, and partial color changes when clicking on theme buttons. OS X, Chrome 51.0.2704.103

**Comment by ykaykay** [comment]
I am still receiving the issue @paul-calvelage outlined above. Anyone else get this?

**Comment by alaahussein94** [comment]
@ykaykay Same. I'm using Chrome version 65.0.3325.181 and running on macOS High Sierra version 10.13.3.

**Comment by monobrawl** [comment]
On a Mac with High Sierra 10.13.4:
- with Safari 11.1 (13605.1.33.1.2) - only the box is switched and when I refresh it goes back to dark. 
- with Chrome 65.0.3325.181 - I don't get the option to switch themes at all.

(Note: I find the dark theme extremely tiring and am desperate to switch to the light one)

**Comment by Amomum** [comment]
I also have the same issue as @paul-calvelage on Win7 in Firefox and in Chrome.

**Comment by LeksorHayabusa** [comment]
so do i on my OS 10,12 and Chrome 67  as @paul-calvelage

**Comment by elyselam** [comment]
I prefer white theme :(

**Comment by hackedWifi** [comment]
4 years and still not resolved.

**Comment by mjarraya** [comment]
> 4 years and still not resolved. Not everyone likes dark mode.

I've been using this for a while, it does the job
https://github.com/gttotev/codewars-light

**Comment by postatum** [comment]
There's an `inverted` theme in Codewars css which looks like a light one.
One could automate running this JS on each page to switch to it:
```js
$('body').removeClass('dark-theme').addClass('inverted-theme')
```

**Comment by kazk** [comment]
Fixed by replacing with the new site wide theme switch. You can toggle between dark/light modes from the moon/sun icon at the top.
