### ISSUE TITLE
Problem with clan function

### ISSUE THREAD

**Issue by appkovacs** [Codewars/codewars.com#433]
Hello!

We are a team and tried to register separated profiles with giving our clan name during registration process. It isn't working this way, because we cannot see each other on Allies section.

**Comment by jhoffner** [comment]
Sorry about that. Can you please provide a screenshot of your dashboard's allies section and also the usernames. I'll take a look. Thanks.

**Comment by appkovacs** [comment]
There are only 1 row in Allies section, it contains only my username. There are several teammates, who has set definitely the same clan name during registration, but we can't see each other.

**Comment by appkovacs** [comment]
![qwertz 3fc375f9c83097a8](https://cloud.githubusercontent.com/assets/16986206/16619435/5511b430-438e-11e6-8aa4-47e5339504ba.jpg)

**Comment by jhoffner** [comment]
The issue with you not being linked up to your clan members should be resolved now.
