### ISSUE TITLE
Unsubscribe link is broken.

### ISSUE THREAD

**Issue by mspreij** [Codewars/codewars.com#434]
The first unsubscribe link of the "Code caffeine - kata with your coffee!" messages redirects to a URL like
https://www.codewars.com/unsubscribe/newsletter?email=<my email address>
which gives a 400 error page.
I just used the second link instead, but you probs wanna fix.

**Comment by jhoffner** [comment]
Thanks. I've removed the link for now (the 2nd one is now the only one).
