### ISSUE TITLE
Solution not showing up on the solutions page

### ISSUE THREAD

**Issue by jbampton** [Codewars/codewars.com#435]
https://www.codewars.com/kata/sum-of-multiples/ruby

https://www.codewars.com/users/Beast

I completed this in Ruby and I can see it in my completed list on my profile but cannot see my solution on the solutions page and it says I don't have a solution.

@jhoffner I can remember this has happened to me a number of times now on a few different kata

**Comment by jhoffner** [comment]
OK I'll take a look and get back to you hopefully later on today.

**Comment by jhoffner** [comment]
To be clear, this issue is related to you not seeing your solution, but you are still able to access the solutions page correct?

**Comment by jbampton** [comment]
I just checked it again and now my solution is visible on solutions page.  Not sure why I couldn't see it yesterday but can see it now.
