### ISSUE TITLE
Square Every Digit 

### ISSUE THREAD

**Issue by MicahWoldu** [Codewars/codewars.com#437]
The expected value is: 811181 and it gets: 811181. However, the code provided below is still failing to pass the test. Why is this the case?

function squareDigits(num){
  var str = num.toString();
  str = str.split('');
  var arrayLength = str.length;
  var tnt = "";
  for (var i = 0; i < arrayLength; i++) {
      tnt += Math.pow(parseInt(str[i], 10), 2);
  }
  return tnt;
}

**Comment by jhoffner** [comment]
Please post issues like these on the kata discussion form as its content related. The issue is likely that you are passing in either a number or string and the tests are expecting the opposite.
