### ISSUE TITLE
Server error when resetting password

### ISSUE THREAD

**Issue by kathicks** [Codewars/codewars.com#439]
I've entered my email on the 'forgotten my password' page and get the following error message:
**"Looks like there was a server error (500)"**

![codewars_password_server_error](https://cloud.githubusercontent.com/assets/9768414/16615285/862b79f0-436d-11e6-892e-5a01611393d7.PNG)

**Comment by kazk** [comment]
Closing old issue. Multiple users have reset password recently so this shouldn't be happening anymore. Please open a new one if this issue is still there.
