### ISSUE TITLE
Comment Issues ( no visibility + edit discards text )

### ISSUE THREAD

**Issue by Enteleform** [Codewars/codewars.com#440]
I recently encountered an issue with the [**Give Me Diamond**](https://www.codewars.com/kata/give-me-diamond/discuss/python) kata, and posted an explanation of the issue in the `discussion` section.

---

The comment has the `spoiler` flag enabled, so it should be hidden from _other users_ that have not completed the challenge.

For some reason, it is also being hidden from _my account_:

![issue1](https://cloud.githubusercontent.com/assets/10906415/16636921/36261b2c-43a9-11e6-9887-e49d379e3729.png)

---

Additionally, if I attempt to edit the comment, the original content is not retrieved and I am presented with an empty input form:

![issue2](https://cloud.githubusercontent.com/assets/10906415/16636922/362b293c-43a9-11e6-8f20-faff7b3d9dfc.png)

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
