### ISSUE TITLE
Issue with unlocking solutions after submitting a correct solution

### ISSUE THREAD

**Issue by danehrlich1** [Codewars/codewars.com#441]
Hi All:

I completed a kata, but after submitting my solution and then confirming my solution as final, I was not able to unlock / view other solutions to the kata. The reason for this I am told is that "Since you have not yet solved this kata we have hidden the solutions from you." This is despite the fact that I just successfully completed it. I checked again 30 minutes after passing the kata, but still have not had any luck. Please see the below screenshots. Is this an error on the backend, or did I miss something?

![screen shot 2016-07-07 at 5 49 18 pm](https://cloud.githubusercontent.com/assets/3357202/16672498/161fdbc4-446c-11e6-913b-602e112a4c38.png)
![1e42eb5a-ffd5-452e-b980-dd7b2868153f](https://cloud.githubusercontent.com/assets/3357202/16672500/1ad648c4-446c-11e6-8384-1e1b028d4571.png)

**Comment by Vishal-vash** [comment]
Yup getting the same issue ...

**Comment by warborn** [comment]
Getting the same issue with many katas yesterday, i submitted many answers for the same kata but unfortunately can't see the solutions yet. When i click on "unlock solutions" the solutions are shown but if i go to "my solutions" There's a message that says "There are no solutions yet for this kata."

**Comment by aryan-firouzian** [comment]
Getting the same issue.
I solved a Kata named "Catching Car Mileage Numbers" in python and later I translated it to C#.
But when I want check C# solutions I need to unlock it, even after I solve my translation.

**Comment by efess** [comment]
I just ran into this issue with Kata "Escape the Mines!" for JS. 

I do remember moving to discourse before hitting "submit", checking out some comments, and clicking the browser back navigation - where my solution was erased and I had to copy/paste it back in.

![image](https://cloud.githubusercontent.com/assets/772580/19737170/62f07236-9b80-11e6-8ef7-9fc9e9c71fce.png)

![image](https://cloud.githubusercontent.com/assets/772580/19737213/8c08b200-9b80-11e6-8e95-5a1b348750f5.png)

**Comment by kazk** [comment]
If this happens again for new submissions, please comment on #1683.
