### ISSUE TITLE
Incorrect styles loaded from time to time

### ISSUE THREAD

**Issue by Vort** [Codewars/codewars.com#442]
Half of page refreshes produces outdated styling.
For example, satisfaction rating icon disappears.
![cw_style](https://cloud.githubusercontent.com/assets/1242858/16678582/30af0712-44e9-11e6-8ec6-99901997e72b.png)
This happens because different css's gets loaded:
Good one: https://www.codewars.com/assets/application-8438214c37a8cb6afb8883f3762bb26e.css
Bad one: https://www.codewars.com/assets/application-85800a8b59f748041d4a16a8e903bf6c.css

**Comment by kazk** [comment]
Closing as fixed.
