### ISSUE TITLE
Author names missing from search results

### ISSUE THREAD

**Issue by Vort** [codewars/codewars.com#443]
Some entries in katas list have no authors specified.
![cw!UNITO-UNDERSCORE!search](https://cloud.githubusercontent.com/assets/1242858/16678694/33d1e8aa-44ea-11e6-9870-b0503b91881d.png)
Sometmes this gets fixed by page refresh, sometimes - not.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1ege) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Maybe related to #46

**Comment by Claukorze** [comment]
We couldn't reproduce it so in case this issue happens again please create a new GitHub issue. Thank you!
