### ISSUE TITLE
Cannot add Translation to Kata

### ISSUE THREAD

**Issue by Dan-Nolan** [Codewars/codewars.com#446]
This Kata is still missing a few languages, however I can't add a translation: 

https://www.codewars.com/kata/weight-for-weight/discuss/javascript

The dropdown is missing the "+ Add New" option

**Comment by CursedFlames** [comment]
Fortunately, you can still get it by visiting the translations page (remove /train/language, replace with /translations)

**Comment by Dan-Nolan** [comment]
Ah thanks for reminding me, it looks like this is fixed with today's release 😄
