### ISSUE TITLE
Can't submit or test

### ISSUE THREAD

**Issue by acouderc** [Codewars/codewars.com#450]
I've been trying to submit my code for hours and I either get a "No tests were provided", "Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated." or "unknown error".
Bug happened on https://www.codewars.com/kata/reverse-polish-notation-calculator/train/javascript and https://www.codewars.com/kata/52c4dd683bfd3b434c000292/train/javascript, and I managed to submit https://www.codewars.com/kata/5324945e2ece5e1f32000370.
Username gjfgkdtgqdhgdkd

**Comment by FelixxHo** [comment]
I have the same error when trying to test / submit solution in different Kata.
but the status of server is showing 'Operational'.

**Comment by CursedFlames** [comment]
I'm also getting this problem, including with a kata translation I'm working on

**Comment by rollietikes** [comment]
Same issue looks like there are some major problems tonight irrespective of the site status page listing no incidents.

**Comment by nest-aka-swan** [comment]
I have this error in all Katas.
'Unknown error' or
'Submission timed out while communicating with our servers.' etc

**Comment by kwypchlo** [comment]
same here

**Comment by trueneu** [comment]
Same here, problem persists.

**Comment by astandrik** [comment]
+1

**Comment by schu34** [comment]
preview.codewars.com seems to be working

**Comment by schu34** [comment]
preview.codewars.com seem to be working for both testing and submitting

**Comment by jhoffner** [comment]
Background job processing went down last night so no submissions were getting processed (or points, or anything else for that matter). Processing is back up and all jobs have been processed. If you attempted a solution that passed the kata then you may find that it is marked done now.

I will be rolling out a new code execution architecture that will alleviate many of these issues from happening again and is also much faster. I'm working through a few remaining issues and will be releasing hopefully today.

**Comment by Themalni** [comment]
It's 11.01.2017 and I can't submit my solutions to katas.  Tried two different katas and both gave me this: 

![issue_1](https://cloud.githubusercontent.com/assets/12295765/21861404/061c9b88-d835-11e6-9442-37012b6fad1c.JPG)
 
![issue_2](https://cloud.githubusercontent.com/assets/12295765/21861412/0cfdbb1c-d835-11e6-9bf8-a9767ef559af.JPG)

I will wait till tomorrow and try to submit my solutions again, just wanted to let you know about the issue.
