### ISSUE TITLE
Site timeouts on multiple Kata 

### ISSUE THREAD

**Issue by rollietikes** [Codewars/codewars.com#451]
Multiple site timeouts tonight and problems submitting solutions. I am unable to submit or test. This is not Kata specific but a site issue. The submission sometimes times out and then the Kata appears completed on my solution page.

**Comment by astandrik** [comment]
+1

**Comment by CodeTaha** [comment]
+1 I have been trying continuously, since the past 12 hrs, nothing works. Neither 'Run tests' nor Submissions

**Comment by PiotrBerebecki** [comment]
Getting errors (e.g. 'Submission timed out while communicating with our servers...' or 'Unknown error') when trying to 'Run Tests' or 'Submit ' any kata. Tried in Firefox and Chrome. Please resolve as I need to get my daily kata fix :)

**Comment by KatHicks** [comment]
+1 keep trying to submit my solution and just says either 'no tests were provided' (when there are multiple in the test cases window) or says 'submission timed out while communicating with our servers'.

**Comment by CodeTaha** [comment]
@KatHicks Yes even I experienced the same issue. It recursively gives 3 types of errors
1. No tests provided
2. Unknown Error
3. Submission timed out server busy ...

**Comment by rollietikes** [comment]
Yes, Codewars is totally down and has been for over 12hrs. This is a major outage.

**Comment by jhoffner** [comment]
Background job processing went down last night so no submissions were getting processed (or points, or anything else for that matter). Processing is back up and all jobs have been processed. If you attempted a solution that passed the kata then you may find that it is marked done now. 

I will be rolling out a new code execution architecture that will alleviate many of these issues from happening again and is also much faster. I'm working through a few remaining issues and will be releasing hopefully today.
