### ISSUE TITLE
Katas in PHP fail to load

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#453]
As I see just now PHP has been added as a Kata language very recently from the fact that a few Kata have been translated into PHP.  However, when I click on the PHP icon to attempt to undertake the Kata in PHP, it always says that "The kata failed to load. Please try reloading the page.", like such:

![2016-07-15 10 18 32](https://cloud.githubusercontent.com/assets/7777884/16877326/166858e4-4ada-11e6-86d0-d67a54531d08.png)
![2016-07-15 10 19 30](https://cloud.githubusercontent.com/assets/7777884/16877356/38a67670-4ada-11e6-9fc3-c55c72b28db8.png)
![2016-07-15 10 21 47](https://cloud.githubusercontent.com/assets/7777884/16877427/8c555b6a-4ada-11e6-808e-0856c43b6339.png)
![2016-07-15 10 22 31](https://cloud.githubusercontent.com/assets/7777884/16877437/a34594f2-4ada-11e6-907f-1dcb03858d55.png)

**Comment by jhoffner** [comment]
Yeah they got translated on preview.codewars.com, but unfortunately show up in www (same shared database). Once I work through some final issues with the latest updates I will push to www and they will work.
