### ISSUE TITLE
Getting "UNKNOWN ERROR" on Kata submission

### ISSUE THREAD

**Issue by Vishal-vash** [Codewars/codewars.com#454]
Everytime I'm submitting a KATA, I'm getting "Unknown Error" and its failed to submit. I tried it with 3 different Katas and getting the same error on submission. I am using Chrome Browser, but this never happened before. Also getting ### **_"Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated."_** frequently...

**Comment by astandrik** [comment]
Why can't anyone read previous issues?

**Comment by jhoffner** [comment]
The issue is resolved.
