### ISSUE TITLE
Sign up error with Javascript and Java

### ISSUE THREAD

**Issue by neildcruz19** [Codewars/codewars.com#457]
After the first two challenges a generic error message shows up

>\> Hmmm... There seems to be an error with this page.

**Comment by boots525** [comment]
I am also having this issue. Two days running.

**Comment by neildcruz19** [comment]
I was able to sign up yesterday using the javascript sign up tests.

**Comment by jhoffner** [comment]
Thanks for letting us know. Over the weekend there was an issue processing background jobs. Everything should be working as expected now.
