### ISSUE TITLE
Python 2.x string output doesn't accept unicode strings

### ISSUE THREAD

**Issue by deadowl** [Codewars/codewars.com#459]
I was trying to rewrite a kata translation for one of my kata a month or so ago, and was unable to get it to pass due to issues in the test cases. It seems like the Python kata test framework completely rejects unicode strings now.

**Comment by jhoffner** [comment]
I'll try to take a look tomorrow. What kata is this for?

Get Outlook for iOS




On Sat, Jul 16, 2016 at 4:50 PM -0700, "deadowl" <notifications@github.com> wrote:












I was trying to rewrite a kata translation for one of my kata a month or so ago, and was unable to get it to pass due to issues in the test cases. It seems like the Python kata test framework completely rejects unicode strings now.

**Comment by deadowl** [comment]
Vigenere Cipher and Vigenere Autokey Cipher in particular. The current Python test cases are so bad for those they need to be replaced, although it looks like you actually have a beta process for translations now, which was a much-needed improvement from my perspective.

Character encoding support has been going downhill in a very bad way. I've had complaints on like half of my kata about character encoding issues, all of which had assumed UTF-8 strings and that had been coded with Javascript in mind. I think the root of the problem is that the different languages that are being supported have different character set support, and that contributors might not have much experience with character encoding issues.

https://www.codewars.com/kata/vigenere-cipher-helper/discuss
https://www.codewars.com/kata/vigenere-autokey-cipher-helper/discuss

I'm also wondering if the new issue I'm seeing with the affine cipher kata is related to this. If not, feel free to fork out another issue.

https://www.codewars.com/kata/affine-cipher-helper/discuss

**Comment by jhoffner** [comment]
Character encoding beyond ascii accidentally got broken with the new runner released on Friday, which I'm in the process of pushing an update out for.

**Comment by jhoffner** [comment]
I deployed a fix yesterday. Please verify that this is still an issue.

**Comment by deadowl** [comment]
It looks like when test.it is called with the kata builder on a unicode string, it fails to output and none of the following asserts are presented or executed, unless trying to resubmit. Same with the print statement.

**Comment by deadowl** [comment]
Python, at least 2.x, has a source coding declaration https://www.python.org/dev/peps/pep-0263/
Not sure if that's applicable. I don't know what's going on otherwise. Here's the Vigenere solution and test cases I want to replace the present ones with, which will break every existing solution, but also resolve every reported complaint and issue.

[vigenere.zip](https://github.com/Codewars/codewars.com/files/372729/vigenere.zip)

**Comment by ebreton** [comment]
I hit the same issue today, trying to write a kata about unicodes.

My issue is not to be able to display any message with unicode. 

When trying  ```test.it(u"Testing with {0}".format(incoming))```, where ```incoming``` is a unicode. I got the following error:

```python
Traceback:
   in 
  File "./frameworks/python/cw-2.py", line 56, in it
    print("{0}".format(format_message(message)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
```

I also tried the work  around ```print u"Testing with {0}".format(incoming)```, which leads to:

```python
Traceback:
   in 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
```

Is there a way to display unicode messages on the execution of tests ?

**Comment by kazk** [comment]
This will be tracked at https://github.com/Codewars/codewars-runner-cli/issues/508
