### ISSUE TITLE
Kata has no author

### ISSUE THREAD

**Issue by bkaestner** [codewars/codewars.com#46]
[Déjà vu Duplicates](http://www.codewars.com/kata/547f601b4a437a2048000981) has no author. Well, it has one ([lkspencer](http://www.codewars.com/users/lkspencer)), but his name isn't shown in the status bar, see below.

![missingauthor](https://cloud.githubusercontent.com/assets/6301773/7246268/94ce1366-e7fa-11e4-9248-3a004841bb4b.png)

(Sorry for the marked text, I forgot to deselect my selection before I took the screenshot)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1egz) by [Unito](https://www.unito.io)

**Comment by bkaes** [comment]
Somehow, the issue resolved itself.

**Comment by bkaes** [comment]
This still happens from time to time. However, whenever I try to reproduce it, the name will be shown again.

**Comment by jhoffner** [comment]
It is likely a caching issue. It's been sporadically happening for a long time and really hard to reproduce in local development.

**Comment by paul-calvelage** [comment]
Today, the Multiply kata has no author for me (Chrome / Windows 10):
![kata](https://cloud.githubusercontent.com/assets/5090280/15653739/bd5a4b8c-265c-11e6-8d13-b90d75266b24.png)
![search](https://cloud.githubusercontent.com/assets/5090280/15653742/c1901010-265c-11e6-8cd7-17e1ea87732e.png)
I see the same thing in Firefox without being logged in:
![firefox](https://cloud.githubusercontent.com/assets/5090280/15653770/00a0d4b0-265d-11e6-8027-0c3b5a11d227.png)

**Comment by kazk** [comment]
"Multiply" kata doesn't have `createdBy`.

`curl 'https://www.codewars.com/api/v1/code-challenges/multiply' | jq .`

```json
{
  "id": "50654ddff44f800200000004",
  "name": "Multiply",
  "slug": "multiply",
  "category": "bug_fixes",
  "publishedAt": "2013-05-18T18:40:17Z",
  "approvedAt": "2013-12-03T15:41:04Z",
  "languages": [
    "javascript",
    "coffeescript",
    "ruby",
    "python",
    "haskell",
    "clojure",
    "java",
    "csharp",
    "elixir",
    "cpp",
    "typescript",
    "php",
    "crystal",
    "dart",
    "rust",
    "fsharp",
    "swift",
    "go",
    "shell",
    "c"
  ],
  "url": "https://www.codewars.com/kata/multiply",
  "rank": {
    "id": -8,
    "name": "8 kyu",
    "color": "white"
  },
  "createdAt": "2012-09-28T07:12:31Z",
  "approvedBy": {
    "username": "alchemy",
    "url": "https://www.codewars.com/users/alchemy"
  },
  "description": "The code does not execute properly. Try to figure out why.",
  "totalAttempts": 1347655,
  "totalCompleted": 738863,
  "totalStars": 211,
  "voteScore": 652,
  "tags": [
    "Bugs"
  ],
  "contributorsWanted": true,
  "unresolved": {
    "issues": 2,
    "suggestions": 1
  }
}
```

**Comment by VanessaGreene** [comment]
@bkaestner Has this issue occurred again recently? If so, please let me know.

**Comment by bkaestner** [comment]
@VanessaGreene Unfortunately, I'm not an active Codewars user anymore, so I can't tell whether those issues are resolved. But it has been ~8 years, so I guess the cache is fine nowadays. And if no one else reported this, it is probably resolved, thanks for closing. 🙂

Same holds for the other issues I originally opened, can't really comment on them, sorry.
