### ISSUE TITLE
Kata cannot be approved

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#460]
Smile67 tried serveral times to approve my kata "Sum without highest and lowest number".
The kata has the status "Awaiting moderator approval"
(https://www.codewars.com/kata/576b93db1129fcf2200001e6)

He has got every time a server error 500.

Can you help?

**Comment by g964** [comment]
Same here, impossible to approve: error 500.

**Comment by jhoffner** [comment]
Kata publishing seems to be having a few issues. I'll be looking into it today.

**Comment by SteffenVogel79** [comment]
This problem holds up the last week.

**Comment by SteffenVogel79** [comment]
This problem ist not resolved.
Smile67 tried again before 1 minute and receives the 500-error again.

Can you reopen this Bug?

**Comment by jhoffner** [comment]
I just approved it fine without an issue.

**Comment by SteffenVogel79** [comment]
Ok. Strange! Smile got the 500-error.
Thanks a lot for your help!!!
