### ISSUE TITLE
New katas are not visible in the kata-list

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#461]
New katas are not visible in the kata-list "https://www.codewars.com/kata/search/my-languages?q=" or "https://www.codewars.com/kata/".

For example: https://www.codewars.com/kata/578b4f9b7c77f535fc00002f

Is there a problem?

Can you help?

**Comment by jhoffner** [comment]
"My languages" is selected as the default filter. Are you looking for a kata that was not chosen as a training language?

**Comment by SteffenVogel79** [comment]
As I wrote: New katas are also not visible in "https://www.codewars.com/kata/".

You can check this by my new kata (https://www.codewars.com/kata/578b4f9b7c77f535fc00002f), that I created yesterday.
It is not visible in the kata-lists.

**Comment by jhoffner** [comment]
Looks like this is also related to some timeout issues I have been seeing with publishing. Did you have the same problem? I am looking into this today. Sorry for the inconvenience and thanks for contributing.

**Comment by SteffenVogel79** [comment]
The publishing of my kata lasts relatively long.

But this is not only my problem. All new katas are not shown up in the kata list, but only on the authors profil.
I saw more than one other katas, that have been published yesterday and are until now not in  the lists.

Thanks for your great job and friendly answers.

**Comment by SteffenVogel79** [comment]
Now i tried to publish a new kata, and i got a timeout error.

**Comment by jhoffner** [comment]
Looks like it is something that is causing our background engine to crash, so background jobs are not processing. I'm working on the fix now.

**Comment by SteffenVogel79** [comment]
Thanx for your quick help and good luck!

**Comment by SteffenVogel79** [comment]
Now, it begin, that katas from yesterday appear in the list.

**Comment by SteffenVogel79** [comment]
Very good job! Thanx!!!!!

**Comment by dkamyshov** [comment]
Hello, so I've just came across the same issue: my beta kata is not visible in the "new katas" list. The kata in question is this one: https://www.codewars.com/kata/5933b154a08ce9f9730005f8

As a sidenote, katas that I published a couple of days ago appeared on the list immediately.

Could you help?
