### ISSUE TITLE
Problem with C++ translation

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#464]
Though the kata is validated (tests are said to be correct) I get: "Kata was published with failing tests" and nothing is published...

**Comment by jhoffner** [comment]
Which translation?

**Comment by g964** [comment]
Since a few days every C++ translation but when I wrote previously it was <https://www.codewars.com/kata/twice-linear>. I gave it a second try and it worked on this second try though I got "Kata was published with failing tests" on the new first try.

**Comment by jhoffner** [comment]
Background processing had stopped. Everything is working now so please verify that this is still a problem for you. Thanks.

**Comment by g964** [comment]
The problem is there with PHP too. <https://www.codewars.com/kata/disguised-sequences-ii> worked only on the 2nd try, On the 1st I got: "Kata was published with failing tests".
For now I can't experiment with C++.

**Comment by g964** [comment]
Doesn't happen anymore if the kata is saved prior to publish:-)
