### ISSUE TITLE
Kata can be submitted, even if I don't pass all tests

### ISSUE THREAD

**Issue by anter69** [Codewars/codewars.com#465]
I had this issue with 2 katas today: if I generate an out of range error, I can pass all tests:
```
You have passed all tests! :)

STDERR:
Traceback:
   in <module>
   in only_oddDigPrimes
IndexError: list index out of range
```

E.g. in this kata: https://www.codewars.com/kata/55e0a2af50adf50699000126 try this code (python 2):
```python
def only_oddDigPrimes(n):
    if n == 20: return [7, 19, 31]
    print [][1]
```

**Comment by Taliesin84** [comment]
I'm having the same issue in a lot of katas, like this one ->https://www.codewars.com/kata/custom-array-filters/train/python

I just pass the preliminary tests and am still able to submit the final solution! (SPOILER ahead)
![kata](https://cloud.githubusercontent.com/assets/18401384/17031612/e2f79bae-4f6c-11e6-8148-e9978a71e160.png)

**Comment by Geebz** [comment]
https://s32.postimg.org/gnwzkuq5x/2016_07_28_00_44_33.png

yep, the same story

**Comment by jhoffner** [comment]
There was an older version that was having this issue. The odd thing is that if you passed the tests it should should you a message that I'm not seeing, so it seems like old code somehow. 
<img width="674" alt="train__custom_array_filters___codewars" src="https://cloud.githubusercontent.com/assets/579835/17218777/e4f989d6-549d-11e6-90d4-77408e5f7a58.png">

Maybe cache busting is broken. Try doing a hard refresh?

**Comment by BSp-r** [comment]
And another one, a few different.
Kata (c#): https://www.codewars.com/kata/happy-little-trees/csharp
Try submit this code:
```csharp
using System;
using System.Collections.Generic;

public class Tree : ITree
{
  public class Branch
  {
    public int Length { get; set; }
    public int Position { get; set; }
  }
  
  
  public int Height { get; private set; }
  public List<Branch> Branches { get; private set; }
  
  public Tree()
  {
    Height = 1;
    Branches = new List<Branch>();
  }
  
  public void GrowTrunk()
  {
    Height++;
    //Console.WriteLine("GrowTrunk method is called...");
  }
  
  public void GrowBranches()
  {
    for(int i = 0; i < Branches.Count; i++)
      Branches[i].Length++;
  }
  
  public void NewBranch()
  {
    Branches.Add(new Branch{ Length = 1, Position = Height });
  }
  
  public void Ouch(int n)
  {
    if(n > 0 && Branches.Count >= n)
      Branches.RemoveAt(n);
  }
  
  public string Description()
  {
    string eos = String.Empty;
    int count = Branches.Count;
    if(count > 0)
    {
      string[] ps = new string[count];
      string[] ls = new string[count];
      for(int i = 0; i < count; i++)
      {
        ps[i] = Branches[i].Position.ToString();
        ls[i] = Branches[i].Length.ToString();
      }
      eos = $" that have position(s): {String.Join(",", ps)} and length(s): {String.Join(",", ls)}";
    }
    
    return $"The tree trunk is {Height} unit(s) tall! There are {count} branch(es){eos}!";
  }
}
```
The `test5` is failed because of the wrong index at line `41`: http://prntscr.com/bz5pj0.
Now just uncomment the line `25` and try again.
There will be a very long output with STDERR in the end:

> Max Buffer reached: Too much information has been written to stdout.

http://prntscr.com/bz5sal , http://prntscr.com/bz5srb

But we passed, because the `test 5` (which is failed) was not called (as well as `test3` and `test4`).

**Comment by jhoffner** [comment]
Odd. I get this with that code. 
<img width="682" alt="train__happy_little_trees___codewars" src="https://cloud.githubusercontent.com/assets/579835/17259828/2f1ede46-5582-11e6-89f8-131449b19d57.png">

Did you try doing a hard refresh to clear your cache? I'm still wondering if this is an issue with cache busting being broken as I fixed something that would have caused this last week.

**Comment by jhoffner** [comment]
Looks like cache busting isnt working at all for the actual output panel (Iframe).  Can you try clearing cache for that as well? 

In the meantime I'll get cache busting re-enabled for the output window.

**Comment by BSp-r** [comment]
Yes, i tried. Doesn't work. I think it because the STDERR interrupts executing of all test cases after the `test2`. Look, in the case with `WriteLine` method we have executed only the first few tests which pass successfully, other cases just not execute: http://prntscr.com/bz7xdw , http://prntscr.com/bz7z4t. Therefore we can submit. But if the `test5` would one of the first, we could not.

**Comment by jhoffner** [comment]
Yeah I fixed this exact issue last week, where the CW UI was not paying attention to STDERR and just seeing that all tests passed. 

I recently pushed up the cache busting for the output iframe. Maybe try it again?

**Comment by Taliesin84** [comment]
It's working for me now! Thanks!
