### ISSUE TITLE
Dart - Syntax highlighting not correct [Kumite Testing]

### ISSUE THREAD

**Issue by lteacher** [Codewars/codewars.com#466]
_Moved from Codewars/codewars-runner-cli#188_

I noticed that the syntax doesn't look nice in the various code view sections. Couldn't figure out what it is set to now, assuming its js or something like that, [but there is one for dart](http://codemirror.net/mode/dart/index.html):

Specifically I saw this on the example at the above link:

``` javascript
  CodeMirror.defineMIME("application/dart", {
    name: "clike",
    ... other stuff
```

The markdown looks great, however.

**Comment by kazk** [comment]
Closing old issue. Dart's highlighting should be fine. Please let me know if this issue is still there.
