### ISSUE TITLE
Comments on closed/rejected translations don't have a proper href attribute

### ISSUE THREAD

**Issue by bkaestner** [codewars/codewars.com#47]
Fortunately, I've got a notification about Jake's comment and could find the translation: http://www.codewars.com/kumite/553a556b54f6034493000022?sel=553a556b54f6034493000022. Still, Jake's comment gets shown on the dashboard, but the anchor doesn't have a `href` attribute:

```html
<ul class="bulleted-text">
 <li><a href="/users/jhoffner">jhoffner</a></li>
 <li><span class="bullet"></span><span>commented on</span>
       <a class="js-commentable"> ""Make them bark!" CoffeeScript Translation"</a>
 <!-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -->
 </li>
 <li><span class="bullet"></span><time data-text-time="1429898932">5 minutes ago</time></li>
</ul>
```

**EDIT**: This also holds for links in the "authored" list on the user's page, but _not_ notifications.
**EDIT2**: See http://www.codewars.com/users/%20imagostorm/authored_comments for an example for an approved translation that doesn't have the correct `href` attribute.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1eh5) by [Unito](https://www.unito.io)

**Comment by Steffan153** [comment]
> Comments on closed/rejected translations

It doesn't have to be closed - it actually does it on any translation.

**Comment by VanessaGreene** [comment]
@bkaestner @Steffan153 Is this issue still present?
