### ISSUE TITLE
Why I can not display the "full width" char in the result of my kata but you can?

### ISSUE THREAD

**Issue by myjinxin2015** [Codewars/codewars.com#470]
![!!](https://files.gitter.im/Codewars/codewars.com/SY1N/_____2016-07-22T03-17-25.861Z.png)

**Comment by jhoffner** [comment]
You're best bet is to use HTML safe encodings. For example `&#10004;` is how the ✓ is rendered.

**Comment by jhoffner** [comment]
You could write a replacement function. ie: `console.log("✓".replace("✓", "&#10004;"));`

**Comment by myjinxin2015** [comment]
Ok.this is a way...
