### ISSUE TITLE
Publishing Timed Out!

### ISSUE THREAD

**Issue by wthit56** [Codewars/codewars.com#475]
For some reason [a particular kata](http://www.codewars.com/kata/538dc8eb8ca4a3d1c400088f/edit/javascript) is giving me trouble when trying to Re-Publish with some changes I made. After 30 seconds or so I get the above message. 

I've tried refreshing the page, waiting a day or so... but I'm still unable to publish these changes. I've tried re-publishing [a different kata](http://www.codewars.com/kata/54613bb89726f637490009c4/edit/javascript), making tiny changes to make sure it's doing something, and it re-publishes without a problem.

**Comment by kazk** [comment]
#901

**Comment by NeuroSerpens** [comment]
This is still happening to me. I must have tried to republish my task 10 times now...

**Comment by MollyJeanB** [comment]
This is happening to me as well with [this kata](https://www.codewars.com/kata/5aa736a455f906981800360d). I have tried off and on for the last few hours and always get a "Publishing Timed Out!" error
