### ISSUE TITLE
I can no longer access my account?

### ISSUE THREAD

**Issue by davidshaw1234** [Codewars/codewars.com#476]
Hey, so I just joined codewars and I have to say its very fun. However, today, I wanted to add some more languages because I wanted to do problems in different languages, and it suddenly logs me out of my account! No big deal, I try to log back in, and suddenly my email is no longer validated with the system. I definitely remember signing up so I am confused as to why I can no longer use my emails. My user name is suburbanpikachu and I am 7 kyu. However, both of my email addresses show no history of codewars ever registering. I have created a new account called suburbanpika using one of the emails, but would love my old account back. It seems that there is no email associated with the username, suburbanpikachu, and if there is, I may be hacked if the email does not contain the words davidshaw plus an array of numbers or letters. Thanks for the help!

**Comment by jhoffner** [comment]
Hi David. It looks like the first account you created had an extra l in it (`gmaill.com`). I've deleted the newer account and updated the email on your older one so you should be good now.
