### ISSUE TITLE
Unable to post comments - nothing happens

### ISSUE THREAD

**Issue by san00** [Codewars/codewars.com#478]
Hiya,

I've had an ongoing issue with codewars as I've been unable to post comments, issues or feedback etc.
Nothing happens when I click the post button and I've tried with numerous  kata over the months.

Please fix,
Thanks

**Comment by jhoffner** [comment]
Does your web console show you any errors?

**Comment by san00** [comment]
No, it doesn't show any errors or other messages when I hit the post button.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.

**Comment by kuldeepgajera** [comment]
yes.its still there..the issue is still there

**Comment by vegantom** [comment]
Tried on firefox (including private mode so add ons are disabled) and chrome, but cannot add to the discussion, I see that Kazk has closed this but with no solution of how to fix the issue.

**Comment by kazk** [comment]
For anyone having this issue and can't find the email. You can re-send it from your account settings. https://github.com/Codewars/codewars.com/issues/1930#issuecomment-528154637
