### ISSUE TITLE
Kata solved, all tests clear, but still doesn't accepted by the system.

### ISSUE THREAD

**Issue by nikz2710** [Codewars/codewars.com#479]
http://www.codewars.com/kata/5656b6906de340bd1b0000ac/train/clojure

My solution

```
(ns longest.core)
(require '[clojure.set :as set])

(defn longest [s1 s2]
  (apply str (sort (into [] (set/union (set s1) (set s2))))))
```

All tests pass without errors, but overall result is still negative, seems like a system issue.

**Comment by g964** [comment]
Same thing with solutions which were working.

**Comment by jhoffner** [comment]
I'm not sure what happened, but this was an issue with the runner cli. Somehow line breaks were being escaped. I am deploying a fix to production now and the PR can be viewed here https://github.com/Codewars/codewars-runner-cli/pull/220
