### ISSUE TITLE
Add information about required honor to Kata Creator doc

### ISSUE THREAD

**Issue by oduvan** [Codewars/codewars.com#481]
[Here](https://www.codewars.com/docs/kata-creator) it says:

The Kata Editor is the authoring tool used to create kata. It is accessible through the profile menu, found in the top right corner of this site.

I was trying to find it in profile menu and I couldn't.

Thank you

**Comment by jhoffner** [comment]
How much honor do you have? You need to earn 25 before you can create a kata.

**Comment by oduvan** [comment]
That makes sense.

I would put this information into the article I have linked.

**Comment by amypellegrini** [comment]
Same here, I looked around the site until I ended here. This should be explained in the docs.

**Comment by kazk** [comment]
Closing this because the new documentation mentions the privilege. https://github.com/Codewars/codewars.com/wiki/Kata-Creator
