### ISSUE TITLE
Please help, I am new here dont know whatit is

### ISSUE THREAD

**Issue by shreyas23sk** [Codewars/codewars.com#484]
I am attempting to join the website, but after i push the submit button of the first exercise the monitor screen of the website goes blank. Please help

**Comment by jhoffner** [comment]
What browser, browser version and OS are you using?

**Comment by shreyas23sk** [comment]
Chrome 51.0.2704.103 m
Windows 8

**Comment by shreyas23sk** [comment]
I did th exercise in python

**Comment by kazk** [comment]
Closing old issue. I'm sorry you got not replies. Please open a new one if this issue is still there.
