### ISSUE TITLE
JS prints an extra space character ahead by `console.log()`

### ISSUE THREAD

**Issue by littlefisher** [Codewars/codewars.com#485]
``` javascript
console.log("First line");
console.log("Second line");
```

And now it looks like:

```
 First line
Second line
```

Hope the unexpected space character could be removed. Feeling uncomfortable with it. :(

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/29701509-0264f452-8921-11e7-8eec-2fd4fd1d15b1.png)
