### ISSUE TITLE
No new honor points are added!

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#486]
Since 30.07.2016 no new honor points are added!
I solved katas and nothing happens. Also other users stay at their honor values.

**Comment by g964** [comment]
Correct; moreover we can find honor in 3 places: top right, <https://www.codewars.com/users/leaderboard>,
<https://www.codewars.com/users/USER/site-events> and they all are different.

Also: if you publish and approve a translation of one of your own kata this translation doesn't appear anywhere.

**Comment by g964** [comment]
Things are normal now:-)

**Comment by SteffenVogel79** [comment]
There seems to be again a problem...
