### ISSUE TITLE
In C# a translation cannot be re-published if there is console-output

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#487]
In C# a translation cannot be re-published if there is console-output!

If I create a C#-translation with console-output (for a better unterstanding of the values by the user) I can publish the translation. But if I want to change this published translation, all tests are green and then I get the error message, that the tests failed. 
This error seems only to appear, if the translation has console output.

**Comment by kazk** [comment]
The old runner had some issues with C# having large output (#1103). It's fixed in the new one. Let me know if this is still an issue.
