### ISSUE TITLE
Submit Final options is not appearing

### ISSUE THREAD

**Issue by AnwarShah** [Codewars/codewars.com#490]
I have completed this http://www.codewars.com/kata/memoized-fibonacci/train/ruby kata, and ran the test and submit. both was a green signal, but after I can't submit final, since every time i submit, the button again says submit, no "Submit Final"

**Comment by dsschnau** [comment]
I had a similar issue happen this morning with a C# test. I write my code, submitted it and all tests passed, but no 'Submit Final' button became available.

**Comment by kazk** [comment]
This should be fixed now
