### ISSUE TITLE
Problems with translations!

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#493]
Again there are these two problems:

No new honor points.

Also: if you publish and approve a translation of one of your own kata this translation doesn't appear anywhere.

**Comment by jhoffner** [comment]
Are you sure honor is an issue? The queue processing had went down over the weekend which was the cause for it last time. 

Also please separate these out into two issues with more description for the translation approvals. Otherwise when one issue get fixed the other gets closed as well.

**Comment by SteffenVogel79** [comment]
You are right. At this moment there is only the problem with the translations.
I changed the topic of this issue.

Translations are approved by the author but are not visible in the kata and there are also no points for the creator of the translation.

**Comment by SteffenVogel79** [comment]
At this moment a new translation from me could be approved and it is visible and 5 points for me.

BUT: 
For this kata it does not work:
https://www.codewars.com/kata/find-the-combination
And from other users I heard also from this problem.

**Comment by SteffenVogel79** [comment]
Seems to be ok now.
Translations can now be approved.
Thanks for your quick help.
