### ISSUE TITLE
Problems approving beta-katas

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#494]
Smile67 tried to approve my kata
https://www.codewars.com/kata/5797d1a9c38ec2de1f00017b

But there was again the 500-error.

Can someone help?

**Comment by DonaldKellett** [comment]
@SteffenVogel79 did you tick the box for "Allow Contributors" in your (affected) Kata?

**Comment by SteffenVogel79** [comment]
This box is not checked! But this is not the problem. Other katas of mine, where the box is also not checked, could be approved by the user Smile67.

The message is the same like in 496.

**Comment by SteffenVogel79** [comment]
"GiacomoSorbi" approved it now.

Bit this error occurs often in the last times...
