### ISSUE TITLE
Cannot translate a kata to a different version of a language it's already in

### ISSUE THREAD

**Issue by lf-** [Codewars/codewars.com#495]
If I click the button to translate a kata, it brings up the translation editor, which is all fine and dandy. There is a small issue here though: I cannot select a language the kata is already in in the language dropdown.

Normally, this would make sense, but in the case of Python and maybe some others, it doesn't make sense to disallow selection of a language that the kata is already in, as there may be significant changes between versions of the language that would require translation.

**Comment by jhoffner** [comment]
Codewars doesn't support language version independent translations. If you want a python kata to be available in both Python 2 and 3, the test cases and example solution need to be written in a cross compatible way. You can select a default version, but when the kata/translation gets published the system will check all available versions and enable any that work.

**Comment by lf-** [comment]
How would I go about submitting a change to it then?
