### ISSUE TITLE
Unable to star a kata from http site pages

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#500]
Katas can't be starred/unstarred using http pages while it works normally using https.

**Comment by aryan-firouzian** [comment]
I created an issue today about star/unmark katas. Then I noticed this issue, and I tried https, and it worked with https. But still not working on http pages.

**Comment by jhoffner** [comment]
Ah nvm, this behavior was changed. OK I need to work on making everything https by default

**Comment by augmt** [comment]
In my case the newsletter directs me to HTTP pages.

**Comment by kazk** [comment]
I've switched everything to https so this shouldn't happen anymore. The newsletter link is also fixed.
