### ISSUE TITLE
Leading spaces on all Python projects

### ISSUE THREAD

**Issue by rodentz** [Codewars/codewars.com#503]
I'm only on my second kata, "Down Arrow With Numbers" but both this and the previous kata (don't recall name, something about return boolean if string is palindrome) have a strange problem. Both of them always have a leading space before the first print statement, even if it is the first line of the function invoked. I have added snapshots of my code and the output. 

I'm guessing it's probably something stupid I'm missing, but I can't figure it out. Please help?

![code](https://cloud.githubusercontent.com/assets/20979374/17607321/f6c5e3fc-5fd9-11e6-9422-c7c6ee67d717.png)

![output](https://cloud.githubusercontent.com/assets/20979374/17607325/f9f6c082-5fd9-11e6-93f4-58e27e9db6df.png)

**Comment by jack17529** [comment]
http://stackoverflow.com/questions/24093387/pascals-triangle-for-python

**Comment by rodentz** [comment]
Hi Jack, I don't need help with generating the down-arrow correctly. This seems to be a problem with the UI (or something under the hood) of Codewars. Even if my function is:

def whatever(x):
  print ("this")
  print ("this")

the first print statement produces a leading whitespace character (space?) 

This happens on every kata. This means that any kata that requires printed output (not just returning a value) fails. Frustrating.

**Comment by jhoffner** [comment]
hi @rodentz. We do have a fix for this which should be released today. However I also wanted to note that AFAIK there are no kata that depend on printed output. You can print whatever you want and thats great for debugging, however the tests depend on the return value of functions. In the kata that you are referencing you need to return a string from the function, not print anything.

**Comment by jhoffner** [comment]
To follow up on this, you may be used to other sites that do require you to print output, since they test functionality based off of the data that is passed in and out of the process. Codewars is different in that it runs actual unit tests inside of the same process. See the example. test cases given for the kata you mentioned. They are expecting the function to return a string.

**Comment by rodentz** [comment]
Jake,

Thanks, didn't realize that. When I created a string and returned it everything worked fine!

**Comment by brendanvos** [comment]
@jhoffner I believe your fix for this has been deployed and thus this issue can be closed.
