### ISSUE TITLE
Last activity of an user (FEATURE)

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#505]
Is there a possibility to see the date of the last activity of an user?
So I can avoid creating translations of katas from users, that are offline for years...

Perhaps a new field, which saves/shows the last login of an user?

**Comment by jhoffner** [comment]
We actually already have the field tracked, just not sure how to handle this as far as privacy is concerned. Maybe an "active within the last 30 days" flag instead?

**Comment by SteffenVogel79** [comment]
Yeah! This would be a very good solution!

**Comment by SteffenVogel79** [comment]
Now it is given with "Last Seen". Thanks!

Very good new chances! Thanks a lot!
