### ISSUE TITLE
Unable to update a kata when the initial solution that pass the Test suite (already saved)

### ISSUE THREAD

**Issue by wdalmut** [Codewars/codewars.com#507]
If you create a kata and wrongly fill in the initial solution with the final solution and then publish it you cannot update that kata anymore because you receive a message:

```
Initial Solution is invalid. (php) The code should not pass the kata test cases
```

You can see the kata https://www.codewars.com/kata/palindrome-strings/discuss#57ae47c372292d4e750001d9 where the PHP kata have the solution in the initial solution and nobody is able to update it.

I have also tried to delete the PHP kata version but nothing happend

**Comment by kazk** [comment]
Closing because the kata is fixed now.
