### ISSUE TITLE
Total rank assessments and rank votes are not visible on some kata

### ISSUE THREAD

**Issue by SteffenVogel79** [codewars/codewars.com#512]
Ranking in most katas is not visible!

Please change this back!

**Comment by jhoffner** [comment]
I'm not sure what you mean. Please provide some screenshots and description. Thanks

**Comment by SteffenVogel79** [comment]
![noranksapproved](https://cloud.githubusercontent.com/assets/20505967/17713445/3a228144-63fb-11e6-87fc-069b2c6a9a32.PNG)
![noranksbeta](https://cloud.githubusercontent.com/assets/20505967/17713446/3a2772e4-63fb-11e6-82f9-afae90a58a24.PNG)

**Comment by SteffenVogel79** [comment]
Both Katas HAVE rankings! But in the most katas since the new update there are no rankings.

**Comment by jhoffner** [comment]
I think I see what you mean. Total rank assessments and rank votes?

**Comment by SteffenVogel79** [comment]
Yes. correct. Total rank assessments.
Only few katas show it now.

**Comment by kazk** [comment]
Fixed
