### ISSUE TITLE
aha.io codewars portal is gone!

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#514]
Take for example 

https://codewars.ideas.aha.io/ideas/CW-I-92

**Comment by jhoffner** [comment]
Yeah we cancelled that product and the portal went with it unfortunately.  For now feature requests can be made here, though honestly I don't have a ton of bandwidth to handle feature requests. If something isnt strategic or a major issue, its not likely to get worked on any time soon.
