### ISSUE TITLE
Unable to edit a new translation (at least in Elixir)

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#516]
No "Save", "Publish" or "Run" buttons. Impossible to write or paste into the frames "Solution", etc... Same thing in "Preview".

**Comment by g964** [comment]
In fact it seems that happens only (?) in this kata: <https://www.codewars.com/kata/565abd876ed46506d600000d/translation/new>

**Comment by g964** [comment]
Still unable to edit a new Elixir translation:
<https://www.codewars.com/kata/565abd876ed46506d600000d/translation/new>

**Comment by g964** [comment]
It happens in a lot of kata and lots of language.

**Comment by jhoffner** [comment]
@g964 I noticed you are starting to create translations again. have your problems gone away or are you still getting them?

**Comment by g964** [comment]
Still the same with Elixir. I tried to translate a few kata to Elixir but the fields are all UN-editable. No way to write or paste in them. Sometimes the description itself doesn't appear.

**Comment by jhoffner** [comment]
Yeah its odd. All of these work fine for me. 

Can you try again and this time open up your web console. Perhaps some errors are reported there which would help me debug.

**Comment by g964** [comment]
With:
<https://www.codewars.com/kata/56fcc393c5957c666900024d/translation/new>
what I got with Google Chrome:
```
Subscribed to model_update
application-08d1549….js:32 Objectid: "545207bac8e60b30fc000942"updates: Objecthonor: 34126__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
application-08d1549….js:32 Loading /assets/bundles/code_snippets-2cf0a6c83aed77dfd9414a52178a639c.js
application-08d1549….js:32 Loaded /assets/bundles/code_snippets-2cf0a6c83aed77dfd9414a52178a639c.js
3application-08d1549….js:23 Uncaught TypeError: Cannot read property 'prev' of undefined
VM52 56fcc39…:188 Uncaught TypeError: Cannot read property 'prev' of undefined
application-08d1549….js:23 Uncaught TypeError: Cannot read property 'prev' of undefined
```
Edit fields are NOT editable.

Hope that helps.

**Comment by jhoffner** [comment]
That gives me something to go on, though doing a search there are no properties called prev in the codebase so thats a doozy. I'll keep digging. Thanks.

**Comment by g964** [comment]
Same kata:
<https://www.codewars.com/kata/56fcc393c5957c666900024d/translation/new>

With Edge (still unable to paste or write into my Elixir "Solution") I get:
```
SCRIPT5007: Unable to get property 'prev' of undefined or null reference
application-08d1549bf5945ff6f83f89cbc1e0ad4a.js (22,32696)
```

**Comment by g964** [comment]
When I can't paste in Google Chrome, in Console "Source" a line is underlined (I only copy a part of it) for : `application-08d1549bf5945ff6f83f89cbc1e0ad4a.js`

```
&&t.context.prev&&(t.context=t.context.prev),p==="->"?t.inArrowBlock?t.context=t.context.prev:t.inArrowBlock=!0:t.inArrowBlock&&p==="end"
```
It could indicate where the error is?

**Comment by g964** [comment]
I tried today after re-writing and re-saving my code and it succeeded. The first program file was saved in the ordinary way and I didn't see any weird char in it.  Puzzling but most important it worked! Later I will try with another kata. For the time being I think you can close this issue. Anyway thanks for your great work!
