### ISSUE TITLE
"Run Tests" seems to test code, but not my code

### ISSUE THREAD

**Issue by getokoe** [Codewars/codewars.com#517]
If i run the test it says all tests are passed successfully but after re-running the test it gives an error. To me looking at the error message suggests that it is not my code which is tested. See the attached screenshot for reference.

This happened during the 8 kyu Pole Vault Starting Marks kata. 

[Screenshot](http://pasteboard.co/9pnb6cLMM.png)

**Comment by SteffenVogel79** [comment]
Better asks this question in codewars as a thread/issue to the kata.

**Comment by jhoffner** [comment]
This is an odd one. Not sure how to reproduce but I will keep an eye out for this happening again.

**Comment by khairul07** [comment]
I can not test or submit my solution for last 6/7 days. what happened to codeWar??
Can you someone please help?? Its codewar problem or something in my browser??
Please help.When I click Run Test button the Output shows nothing, its completely blank.

![untitled](https://cloud.githubusercontent.com/assets/8148555/17942860/f1e1a372-6a5a-11e6-9aca-79a2a67d086c.png)

**Comment by kazk** [comment]
Sorry for the lack of response. I'm closing this because it's been a while and we've replaced the code execution service this year. Please let me know if this is still happening.
