### ISSUE TITLE
Notification email with broken (or missing) links

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#52]
I usually get broken links in about 50% of the mails I receive from CW, as they have a (seemingly) random space somewhere in the url, so that I have to manually remove the random "%20" from it to have it work.

Today I got one totally without link, like this (user and kata name removed for privacy, let me know if you may need them):

![codewars](https://cloud.githubusercontent.com/assets/4815731/7365538/72bb28d0-ed91-11e4-81be-ce64305b4359.png)

**Comment by jhoffner** [comment]
Thanks for letting me know. I had disabled Mandrill's link tracking because it seemed to be the reason why random whitespace was being added - apparently it just made things worse :worried:

**Comment by GiacomoSorbi** [comment]
Oh, not sure if it is somehow related, but while we are at it, I would also like to report that among a few tens (if not hundreds, not sure) of translations I did, I only got notified once by an email telling me that my translation was approved (and IIRC, the link behaved correctly, no extra space).

**Comment by jhoffner** [comment]
The email issue should be resolved. We should open a new issue for the missing translation approval notifiations

**Comment by GiacomoSorbi** [comment]
Not sure if you can be interested and/or know it already, but I can confirm that now mandrillapp works fine and in a week I never had any more notifications with an extra random space.
