### ISSUE TITLE
Server timeouts and 504 error

### ISSUE THREAD

**Issue by erinjohnson21** [Codewars/codewars.com#520]
When I submit a test I am getting a server timeout and now I have a 504 error.

Been happening off and on for the last couple of hours.

**Comment by doughsay** [comment]
This has been happening for a few days now, even though the status page says everything is operational.  I have to submit my code many times before it finally goes through.  Many timeouts, and generally slow responses throughout the site.

**Comment by SteffenVogel79** [comment]
+1
Same as yesterday....

**Comment by GothiKal** [comment]
I have been having this same issue for ~24 hours. I have only been able to get etst cases running when i first open a kata. once i add code the servers just give up and throw errors.

**Comment by SteffenVogel79** [comment]
Timeouts, Timeouts, Timeouts.... Its so annoying!

**Comment by jhoffner** [comment]
Unfortunately these issues started happening while I am on vacation. I've gotten a chance to deploy some hotfixes (a new one today) that should keep things moving along, but it's not 100% yet. Im back on Sunday and will be prioritizing fixing these issues over everything else. 

Get Outlook for iOS




On Fri, Aug 19, 2016 at 11:32 AM -0700, "SteffenVogel79" <notifications@github.com> wrote:












Timeouts, Timeouts, Timeouts.... Its so annoying!

**Comment by filthycoding** [comment]
Timeouts are there again!
![image](https://cloud.githubusercontent.com/assets/23276523/20488778/956afa46-b008-11e6-9657-ec4edeec8ce1.png)

**Comment by filthycoding** [comment]
Seems like the runner can't handle missing semicolons.

**Comment by filthycoding** [comment]
There are some periods where the servers work, and some don't. Maybe not enough servers available at some times?
