### ISSUE TITLE
[Kata] - "String Pyramid" bug (C++14).

### ISSUE THREAD

**Issue by czarny247** [Codewars/codewars.com#521]
I have a bug in this Kata, which looks like this:

Test Results:
  ExampleTests
  _0_Test1
✘  Expected: equal to 
 # 
***
Actual: 
 # 
***

  _1_Test2
✘  Expected: equal to 
  c  
 bbb 
aaaaa
Actual: 
  c  
 bbb 
aaaaa

So, even if I have the proper solution, it's not passing example tests. As you see "Expected" and "Actual" are the same.

**Comment by SteffenVogel79** [comment]
This is not an codewars-issue! So create a comment at the kata!

And by the way: check for spaces and the last line-ending-character and compare with the test!
