### ISSUE TITLE
Katas not loading

### ISSUE THREAD

**Issue by gmmendezp** [Codewars/codewars.com#525]
All Katas stay loading forever. As in the following image:
![train counting change combinations codewars](https://cloud.githubusercontent.com/assets/10534817/17833057/976d755c-66d0-11e6-9313-582aa3050cb6.png)

The console shows: ```Uncaught TypeError: this.renderViews is not a function code_challenges-99c77e905a861fec11cb64696a989cba.js:1 ```

**Comment by jhoffner** [comment]
What happens if you clear your cache?

**Comment by gmmendezp** [comment]
I tried chrome's incognito and firefox, I still get the issue.

**Comment by jhoffner** [comment]
I'm not able to reproduce but I see that there are a number of errors happening for other users. Does it work at all for you on preview.codewars.com?

**Comment by gmmendezp** [comment]
It does work in preview.codewars.com

**Comment by john-bai** [comment]
@jhoffner I can reproduce the bug before/after clearing cache. There's a runtime error:
![image](https://cloud.githubusercontent.com/assets/246892/17833529/d730ae62-66d4-11e6-994b-9d8ebe5313b8.png)
```
code_challenges-99c77e9….js:1 Uncaught TypeError: this.renderViews is not a functionrender @ code_challenges-99c77e9….js:1showPlay @ code_challenges-99c77e9….js:1_setLanguage @ code_challenges-99c77e9….js:1(anonymous function) @ code_challenges-99c77e9….js:1f @ application-dac16c7….js:15fireWith @ application-dac16c7….js:15x @ application-dac16c7….js:16t @ application-dac16c7….js:16
```

**Comment by jhoffner** [comment]
New local cache busted scripts were deployed and all server caches were cleared. This shouldn't be an issue anymore.

**Comment by john-bai** [comment]
Issue looks fixed for me. I can't reproduce now.
