### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#526]
It shows no comments, no descriptions....
It is as would be accessing without login!

And I cannot logout to new login!

**Comment by jhoffner** [comment]
Please provide a full description, repro steps, screenshots, etc.

**Comment by SteffenVogel79** [comment]
![cw1](https://cloud.githubusercontent.com/assets/20505967/17833865/50ca3b26-672a-11e6-9a0b-d132df2ab227.PNG)
![cw2](https://cloud.githubusercontent.com/assets/20505967/17833866/50ccd0fc-672a-11e6-9b7b-9414c8881626.PNG)
![cw3](https://cloud.githubusercontent.com/assets/20505967/17833867/50d0c338-672a-11e6-8255-a55260c0269d.PNG)

**Comment by SteffenVogel79** [comment]
And the codewars-wheel in left corner is always turning...

**Comment by SteffenVogel79** [comment]
The 404-Error is when trying to "sign out"

**Comment by SteffenVogel79** [comment]
![cw4](https://cloud.githubusercontent.com/assets/20505967/17833880/a1b3b0e4-672a-11e6-9994-54b99a9b48e4.PNG)

**Comment by SteffenVogel79** [comment]
And the reminder-list is broken. there is no scroll-area. i have a lot more than these items in my reminder list.

The problems are present for appr. 1-2 hours.

**Comment by SteffenVogel79** [comment]
And there is no progress-circle on the profile.
![cw5](https://cloud.githubusercontent.com/assets/20505967/17833892/fa27b7f2-672a-11e6-9bb0-6dbc156e1f17.PNG)

**Comment by jhoffner** [comment]
Gotcha, thanks. A fix is being deployed now. It was a bad deployment
