### ISSUE TITLE
Request Error of the Kata named "How much water do I need?" in JavaScript

### ISSUE THREAD

**Issue by YuyangGong** [Codewars/codewars.com#530]
when I try to complete a kata ["How much water do I need?"](http://www.codewars.com/kata/how-much-water-do-i-need/train/javascript) in JavaScript, whatever result I return it will always warn me the "500: Internal Server Error". Can someone fixed this or tell me what I do wrong?

**Comment by Maxim-Bernasevsky** [comment]
We are need have patience. Sometimes site not work, but need little time wait.
