### ISSUE TITLE
Earning acces to kata's solutions: NO!

### ISSUE THREAD

**Issue by janat08** [Codewars/codewars.com#531]
I'm not in love with having to complete a bunch of tests that don't entirely amount to much on a framework that's not as smooth as to be working locally.

If the objective here in denying access to some of the best learning material (in terms of exploring your artsy solutions and applications) is to prevent users from exhausting the content, you're off base. These solutions are good enough as to warrant attention irregardless of readers confidence, and even than they're inspiring enough as to probably move them to create new katas. If it were to come to comparing what's likelier to occur: users not learning procedurally, not engaging; or getting hooked after witnessing level 10 wonders, be inclined to generate katas after having gone through less of a grind.

I've been told that you're working on it months ago, and I'd like to pretend that it basically takes just deleting a line.

**Comment by jhoffner** [comment]
Hi @janat08. Thanks for the note. Not sure where you heard that we were working on removing the ability to see solutions without completing the kata or forfeiting your honor but thats not something we are planning to do. 

The reason for preventing all solutions from being read is not about exhausting the content, but about the integrity of the gamification of the site. Earning points is something that keeps users motivated to keep training and if you can just view the solutions to any kata then whats the point of earning points at all? 

The point of the site is not to be a repository of solutions to problems, its to inspire developers to keep pushing themselves to try harder things and get better as developers. Actually trying to complete the kata is the way that happens. Simply viewing solutions without trying to solve the challenge yourself isn't going to cause anything to stick. 

You can see the solutions however, you just have to forfeit honor. You are not able to view solutions if for harder kata until you rank up, which again is to make it harder for users to cheat. If there is too much cheating happening, the integrity is lost and the motivation that the points provide are lost with it.

**Comment by janat08** [comment]
Yea I misread the conversation on feature requests email notification. 

I imagine a better solution to motivating developers would be to allow them to see how and where their solutions to counting chickens apply in more so real katas that you see at higher levels. I also argue that repeating a word one too many times carries the meaning out of it into oblivion, with katas not necesserily having applicable connotations behind them for users to recognize real world problems as something they had solved in kata.

If you must insist on **gamification** of website rather than sheer challenge, and humiliation (from unlocking lvl 10 solutions) of a skill that is most likely undeserving of being gamified akin to something of a lawyer or doctor having to progress in his profession field on a website through a gamified system, you could just record statistics of users and produce some frank from that where you account for number of tries, time per kata, and time browsing solutions and etc. More than anything that will actually allow you to compare users by these objective stats.

**Comment by janat08** [comment]
I'm less so interested in a rank that is somewhat based on one part grind, and one part some made up arbitration that doesn't really give much of an insight in competitive sense or just basic competency. Even than in less so extrinsic values, which is what gamificaiton is about, without brutal- real- comparison and scoring, if you want a more so immediate kick out of completing kata you could could challenge a user to a field of computing where he scores less so poorly.

If you want gamification that is more so mutually beneficial where you don't "judge" the users distancing them from website as apposed to having them think I have level 10 there, and yet not making completely arbitrary system of leveling, you probably could utilize scores of users with high honor as baseline. Where if there's linear correlation between honor and a score parameter like amount of tries, that will take precedence amongst parameters.
