### ISSUE TITLE
Vim Mode - Pasting does not overwrite selected text

### ISSUE THREAD

**Issue by mephillips** [Codewars/codewars.com#532]
This seems to happen anytime when pasting while there is a selection. Here's a basic example. Assume you start at the begging of a file that looks like this:

```
ABCD
EFGH
```

Hit YjVp

Expected:

```
ABCD
ABCD
```

EFGH should be highlight (V) and overwritten (p)

Actual:

```
ABCD
EFGHABCD
```

The text is pasted after the current selection

**Comment by kazk** [comment]
Seems to be fixed now. I think the CodeMiror version was updated since this issue was reported.
