### ISSUE TITLE
Can not modify a published kata (Publishing Timed Out)

### ISSUE THREAD

**Issue by myjinxin2015** [Codewars/codewars.com#534]
One of my published kata has a typo, I want to modify it, and then click the "republish" button, after 1-2 minutes, will post an window: 

```
Publishing Timed Out!
The server timed out while trying to publish your changes.
```

I try many times, always failed. so I unpulish it, and then modify it, and then save it. and then I click "publish" button, but I still got this error window:

```
 Publishing Timed Out!
The server timed out while trying to publish your changes.
```

I'm not sure what's happened...Is this a issue?

BTW: for a test, I try to modify another kata(change only one char) and republish it, it will got the same error.

**Comment by g964** [comment]
I have lots of problems too to edit-publish translations: for example edit fields are not editable with Elixir, "Save" and "Publish" buttons are always gray... the server adds bad lines in Typescript tests. 
I hope that Jake has time to correct all these bugs. Maybe too many new languages and new features in too short a time?

**Comment by jhoffner** [comment]
@myjinxin2015 which kata is this?

**Comment by kazk** [comment]
Closing due to no response.
