### ISSUE TITLE
Codewar Problem Run tests and Submit

### ISSUE THREAD

**Issue by khairul07** [Codewars/codewars.com#536]
![untitled](https://cloud.githubusercontent.com/assets/8148555/17942481/5b444d58-6a59-11e6-8e7f-312793d5a05d.png)
I can not test or submit my solution for last 6/7 days. what happened to codeWar??
Can you someone please help?? Its codewar problem or something in my browser??
Please help.When I click Run Test button the Output shows nothing, its completely blank.

Thanks in advance.

**Comment by jhoffner** [comment]
Can you try clearing your cache? You can also try right clicking within the output section and click reload frame while holding shift.

**Comment by SteffenVogel79** [comment]
(The wonderful site is calles CodeWars. With "s" at the end. ;-))

When I try to run the tests, it is not very quick, but all tests are running correctly.

**Comment by jhoffner** [comment]
@khairul07 what happens when you load https://runner.codewars.io directly? Does it show text indicating that its ready?

**Comment by khairul07** [comment]
@jhoffner yes its show ready.

**Comment by khairul07** [comment]
@jhoffner its now working . i do not know how but working.

thanks for help.
