### ISSUE TITLE
Cannot submit kata

### ISSUE THREAD

**Issue by labarreto** [Codewars/codewars.com#538]
All the tests pass, it just does not let me submit. There is no error message. The kata question doesn't even show up under "unfinished."

THe question I'm working on is "Playing with digits"

**Comment by labarreto** [comment]
Update: it's not just the question, none of the kata I'm trying to submit are being submitted.

**Comment by labarreto** [comment]
And I can't even bookmark questions

**Comment by jhoffner** [comment]
Can you post some screenshots? Also please open up your console and refresh the page, and report any errors that may come up. Thanks.
