### ISSUE TITLE
Cannot get to Sign Up screen even after completing C# problem

### ISSUE THREAD

**Issue by jbennington** [Codewars/codewars.com#539]
Clicking Sign Up keeps looping back to require a problem to be solved.
I am only doing C# and not currently familiar or interested in other languages.
It indicates that I properly corrected the problem (changing string to int) several times, but still will not let me create an account.
I have a GitHub account, but it says they are not linked, so I assume I have to have a code wars account regardless of logging in with GitHub or not.

FYI...using Internet Explorer 11

**Comment by diegobanuelos** [comment]
Same thing here. I invited a new programmer to the site, and he could not create his user after completing the screening tests...
