### ISSUE TITLE
Publishing Timeout - New Kata

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#544]
I can't publish [this kata](https://www.codewars.com/kata/57c18a16c82ce75f4b000020/edit/python). There's a following error message:

`Publishing Timed Out!: The server timed out while trying to publish your changes.`

**Comment by g964** [comment]
Happens sometimes but often it is nevertheless published. Verify...

**Comment by suic86** [comment]
Thanks for quick response. I forgot to mention that I had the same issue yesterday while editing an existing kata. I agree that it gets published after (some time and) few tries but if one needs to try it 5 or more times to get it published is annoying :/
