### ISSUE TITLE
Ordering of Unfinished Katas

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#545]
Would it be possible to revert the ordering of Unfinished Katas i. e. order from last unfinished to the first.

Reason: With the current ordering one can't easily come back to recently unfinished katas.

Thanks,

suic

**Comment by jhoffner** [comment]
The ordering wasn't broken, unfinished kata being added to the list was. This is fixed now (though some previous solutions may not show up until I can get a ton of old data updated with missing timestamps.
