### ISSUE TITLE
Test case output misleading on white space.

### ISSUE THREAD

**Issue by deadowl** [Codewars/codewars.com#55]
I keep hearing people raise issues about this on the Jaden Casing Strings kata, so I figure it would be good to address. Essentially, the actual result and expected result aren't comparable in terms of white space.

> My solution works, but I receive this error: "Expected: How Can Mirrors Be Real If Our Eyes Aren't Real, instead got: How Can Mirrors Be Real If Our Eyes Aren't Real". Unless I'm drinking crazy-juice, those looks the same to me.

I would personally prefer the actual and expected results be output in preformatted text with white space and control characters being visually represented. It would be useful for some potential kata, such as converting between Windows and Unix newline styles. Could even be implemented as a toggled view.

**Comment by jhoffner** [comment]
Can you provide some examples of output that is not correct? We are already setting `white-space: pre` on the divs that wrap the individual passed/failed outputs.

**Comment by deadowl** [comment]
Should have said fixed-width preformatted text, though that probably wouldn't be enough. 

The problem: A lot of people aren't noticing the trailing whitespace on the test case failure because there's nothing to cue them in on it.

Scare quotes around the expected/actual would be one way to make the whitespace visible. A visual tab/space/newline indicator would make it clear what specific characters are contributing whitespace. Some text editors have a feature like this, though it would require a bit of backend processing and wouldn't be raw output.

**Comment by deadowl** [comment]
I'd label this a bug rather than an enhancement due to the volume of issues this specific kata has had regarding this specific issue in the past two or three months. Of course I don't get to see your email volume, but this issue has created a higher volume of email for me in the past few months. I imagine it's because Codewars has become more popular among novice coders.

**Comment by bkaes** [comment]
> Can you please provide some examples of output that is not correct? We are already setting `white-space: pre` on the divs that wrap the individual passed/failed outputs. 

Since #159 indicates some trouble, and #17 still there, could it be that `white-space: pre` doesn't completely solve this issue?

**Comment by bkaes** [comment]
@JTorr has just provided an example output on [this kata](http://www.codewars.com/kata/54de3257f565801d96001200/discuss#55cffb2c29639d534800010d):

``` plain
#Buy: 169850 Sell: 116000; Badly formed 1: CSCO 250.0 29 B ; (test output: expected value)
#Buy: 169850 Sell: 116000; Badly formed 1: CSCO 250.0 29 B ; (test output: actual value)
#Buy: 169850 Sell: 116000; Badly formed 1: CSCO 250.0 29 B  ; (actual value, when code run in terminal)
[remark:                                                  ^^ two spaces instead of one, but only one shown]
```

**Comment by deadowl** [comment]
I suppose that could be one example, but not per-se related. What I'm trying to state is that although the whitespace may be visible, leading and trailing whitespace are difficult to gauge. Even then, you can't tell the difference between tabs vs spaces, CR-LF vs LF, etc. My proposal would be to markup whitespace and non-printable characters semantically (also paying attention to accessibility), then use CSS to provide relevant visual cues to identify those characters specifically. E.g. I've seen someone's Dreamweaver setup use faded bullet characters for spaces and faded right-arrow characters for tabs.

**Comment by g964** [comment]
@jhoffner :
I'm one with lots of issues about gauging white spaces in some of my katas (see example above by JTorr).
Why doesn't Codewars use constantly a monospace family font for outputs? It would be more convenient for anyone, no need for "nice" font here!

**Comment by jhoffner** [comment]
I've updated the font to be monospaced. Marking the non-printable characeters sounds like it has a great chance of causing some sort of backwards incompatibilities with some pre-existing kata. Please let me know if the monospaced font solves the issues you are having.

**Comment by g964** [comment]
@jhoffner Thanks a lot :+1: Hope that will not cause problems.
