### ISSUE TITLE
No honor points at the moment and timeout when republishing

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#550]
No honor points at the moment (for 1-3 hours) and timeout when republishing a kata.

**Comment by g964** [comment]
Look at: <https://www.codewars.com/users/SteffenVogel_79/site-events>. It may be updated there.

**Comment by jhoffner** [comment]
Sorry guys. I dont know why the Sidekiq process started doing this all of a sudden but it just stops hangs. I'll be looking into this more today, in the meantime I'm restarting the servers and things should be back to normal within 20 minutes or so (once its gets through the backlog).
