### ISSUE TITLE
Server Error 500 at Signup

### ISSUE THREAD

**Issue by Igitt** [Codewars/codewars.com#551]
After finishing the 2 initial typescript tasks, I get a reproduceable "Looks like there was a server error! (500)". After this I cannot access the main page until clearing my browser storage.

**Comment by nicwest** [comment]
I have the same issue with both python and clojure

**Comment by seda007** [comment]
Same problem with javascript

**Comment by dwiedersum** [comment]
The Same with PHP

**Comment by dsky1990** [comment]
Same problem with javascript

**Comment by Ivanabee** [comment]
same for javascript now

**Comment by nazmulapu** [comment]
Same problem with Java

**Comment by hova4** [comment]
the same problem with java

**Comment by waspeer** [comment]
Same

**Comment by mpmont1979** [comment]
Same issue here with Java.

**Comment by shisaq** [comment]
Same problem with JavaScript

**Comment by andreypetrov** [comment]
Same problem with Java (both on safari and chrome)

**Comment by jhoffner** [comment]
Wow, not sure what happened but clearly this just started. Looking into it now.

**Comment by jhoffner** [comment]
This should be fixed now.
