### ISSUE TITLE
Bookmark select/remove is not working

### ISSUE THREAD

**Issue by aryan-firouzian** [Codewars/codewars.com#552]
I am trying on Chrome Version 52.0.2743.116, and I am not able to bookmark any kata or remove previously bookmarked katas. I also tried on my Android tablet (again chrome app) and still not possible to mark or urmark.

**Comment by jhoffner** [comment]
There is an issue with this not working on http. We don't force https on all pages due to some users having issues with iframes with the kata editor. For now the workaround should be to use https.

**Comment by kazk** [comment]
This should be fixed now by forcing https. Links from emails (notification and news letter) used to go to http and the bookmarking was not working there.
