### ISSUE TITLE
"SUBMIT FINAL" bringing up "Solutions have been withheld" message instead of showing other people's solutions

### ISSUE THREAD

**Issue by tachyonlabs** [codewars/codewars.com#553]
I haven't had this problem with any other katas, but when I did the "Your order, please" kata -- https://www.codewars.com/kata/your-order-please/train/python -- and clicked "SUBMIT FINAL" after passing the SUBMIT tests, instead of being taken to a page showing other people's solutions as usual, I got a message "Solutions have been withheld. Since you have not yet solved this kata we have hidden the solutions from you. If you choose to view the solutions you will forfeit your eligibility to earn honor/rank progress for this kata." Returning to the kata page and resubmitting my solution doesn't change anything, even though on my profile it shows the kata in my list of completed katas.

**Comment by mwgalloway** [comment]
I have been having the same issue, with every kata I have completed. I am a new user though and have only completed three kata.

**Comment by EthaneHole** [comment]
Same issue with this kata only: https://www.codewars.com/kata/the-sum-of-the-first-and-the-last-prime-factor-make-chains-of-numbers/ruby
I still earned the honor points but couldn't see the solutions. And after unlocking them, mine wasn't in the list.

**Comment by Wizek** [comment]
Same issue.

**Comment by Wizek** [comment]
For me, resubmitting the same solution makes it work. Has happened twice for me in about 6 katas, so quite frequent. Most recently with this one: https://www.codewars.com/kata/weird-string-case/solutions/haskell

It's not ideal that we have to submit twice.

**Comment by kazk** [comment]
I've found the cause, but it's not easy to fix because it involves data from the past few years. See https://github.com/Codewars/codewars.com/issues/1683#issuecomment-456951790 for details.

**Comment by kazk** [comment]
If this happens again, please let me know by commenting on #1683.
