### ISSUE TITLE
Again no new honor points and timeouts when republishing

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#555]
Again no new honor points (only in site-events visible) and timeouts when republishing

**Comment by SteffenVogel79** [comment]
Now, after appr. 1-2 hours it works again.

**Comment by jhoffner** [comment]
The queues froze up again. I put a possible fix in place but apparently it didn't work. Its an incredibly hard issue to reproduce (haven't been able to other than it happening randomly in production) so it may take some time before I can fully flesh out the issue.
