### ISSUE TITLE
Random tests are currently impossible in Rust

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#556]
I'm not really sure but it looks like there's no way to generate random numbers properly without using an external crate which requires adding a dependency to `Cargo.toml` project file.
https://doc.rust-lang.org/rand/rand/index.html
https://stackoverflow.com/questions/30735490/unresolved-name-randthread-rng

**Comment by jhoffner** [comment]
Thanks for reporting. This will be better tracked within the github.com/Codewars/codewars-runner-cli repo. You are also welcome to submit a patch if you feel up to it.

**Comment by error256** [comment]
Moved to codewars-runner-cli.
