### ISSUE TITLE
Socket Connection Error?

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#560]
I was just authoring and testing a (PHP) Kata when I noticed that the tests were not executing.  Usually, when this type of error occurs, the server times out after trying to execute the code for 7 seconds and then the timeout error message pops up.  However, this time, when I click on "Validate Solution", even after I wait for 30 seconds (or more), nothing pops up, not even the timeout message.

So I save my Kata Draft and try out a few random easy Kata.  It turns out that the code execution itself is working just fine - it usually takes about `200ms` to run the test cases for most Kata, far from timing out.  **However, the absurd time delay was caused by the code runner "Establishing a socket connection..."**, which for some reason is taking much longer than usual, sometimes as long as half a minute (or more).  Any idea what might be causing this?

**Comment by jhoffner** [comment]
Sounds like an issue with the realtime service we use. I'll have to look into making the realtime connection an optional aspect of the initialization process.
