### ISSUE TITLE
Translation stuck in Beta, maybe a solution.

### ISSUE THREAD

**Issue by natacha-beck** [Codewars/codewars.com#562]
I'm on CW since 6 months and start to play with translation since 4. 

I have 2 remarks:
- It could be nice to know if a kata already have pending translation before solved it. Sometimes I just do a kata to translate this one, so it is little bit sad to see after solved it that the translation already exist. 
- Lot of time I can see pending translation of kata, just because the author of this one no longer used CW. In this case for the moment only admin can accept this one. Maybe you can think of an alternative way to accept this one, maybe something like the beta status but for the translation in this way translation can be accepted after some kind of peer-review.

**Comment by kazk** [comment]
I'm closing this because translations are now approved much quicker (https://github.com/Codewars/codewars.com/issues/1065), resolving the second point and minimizes the first.
