### ISSUE TITLE
Unable to get any error massage, just a cross with 0 that is X 0

### ISSUE THREAD

**Issue by ahmed-waqar** [Codewars/codewars.com#564]
When I submit my solution it passes one of the test and gives one test failed with no error massage just a cross and zero.
Error snap shot is provided below:
(https://cloud.githubusercontent.com/assets/21168511/18250016/659dac3c-734f-11e6-8d37-31761af865bd.png)

Program text is provided too:
[Program.txt](https://github.com/Codewars/codewars.com/files/455166/Program.txt)

**Comment by jhoffner** [comment]
Which kata is this for?

**Comment by ahmed-waqar** [comment]
Link for the Kata is given below:
https://www.codewars.com/kata/common-denominators

Can you please also tell the meaning of the error "cross zero" as shown in snap shot.
Thank you

**Comment by kazk** [comment]
I believe this is not Codewars issue.
Your solution is simply failing the first test. I think that kata also tests empty input and expects zero.

---

![](https://cloud.githubusercontent.com/assets/21168511/18250016/659dac3c-734f-11e6-8d37-31761af865bd.png)
