### ISSUE TITLE
Kata description on dashboard double encodes HTML entities

### ISSUE THREAD

**Issue by djlauk** [Codewars/codewars.com#565]
If a kata description uses characters in the description that have special HTML entities, they show up double encoded on the [dashboard](https://www.codewars.com/dashboard) (e.g. `&` becomes `&amp;amp;`, `>` becomes `&amp;gt;` etc.).

Please note, that the description shows up just fine when viewing the kata. I noticed this for the [Persistent Bugger](https://www.codewars.com/kata/persistent-bugger) kata and made screenshots of both the dashboard and kata view to illustrate:

Dashboard (double encoded):
![image](https://cloud.githubusercontent.com/assets/3351287/18266149/809eeddc-7419-11e6-856e-7e14b5462b7b.png)

Kata view (displayed correctly):
![image](https://cloud.githubusercontent.com/assets/3351287/18266156/8f976350-7419-11e6-9407-b77ea2e215dd.png)

**Comment by kazk** [comment]
Closing old issue. I believe this is fixed now.

![image](https://user-images.githubusercontent.com/639336/50568928-4ed89c80-0d0f-11e9-8c2e-b01d943b86b6.png)
