### ISSUE TITLE
Not awarded points

### ISSUE THREAD

**Issue by misterbl** [Codewars/codewars.com#566]
Hi,

I am not sure if I am doing something wrong, but I have just completed 2 katas and I was not awarded any points. I can see my solutions in the list of solutions after submitting my answers.

**Comment by jhoffner** [comment]
There is sometimes a delay. Did you ever end up getting your points?

**Comment by Julix91** [comment]
Same here. - I'll try to remember to come back and update here if I ever got the honor points, but what's confusing is that the progress towards the next belt did get updated, just honor not.

Gamification is a tool to help the learning experience, and as someone who knows a bit or two about behaviorism and operant conditioning, I can tell you that the speed of feedback is incredibly important. Instant feedback is part of what makes this so fun, so the error might not be "not awarded points" (if they do show up later) but instead "points taking longer than 3 seconds to update". The shorter the better. Haven't looked at the code yet, any reason why it would take longer than that to update?

**Comment by misterbl** [comment]
Hi

I realised the problem was that I only had a "submit" button and not "submit" final..apparently this is an issue when u use Firefox. It works perfectly fine now with using Chrome

**Comment by razvan-panda** [comment]
The same thing happened to me. The points appeared to be awarded when submitting but they were taken back after clicking submit final. The problem is definitely solved as it no longer appears in the list under kata I have not completed. But the code does not appear under solutions -> my kata. It does appear if clicking on compare though.

**Comment by craigsmithmd** [comment]
I joined codewars and I reached a rank of 3 Kyu with 1124 points, but then was thrown back to 8 Kyu with 1 point.  I can the see the history of problems solved.  Every time I solve a problem, I am given a few points and then the points are reduced to 1 point with a rank of 8 Kyu.  I am solving different problem ranks 4 Kyu, 3 Kyu, 2 Kyu and even a few 1 Kyu - yet appear stuck at 8 Kyu.  Any advice?
![3kyu](https://github.com/codewars/codewars.com/assets/132099235/19abcc0f-c111-42d2-8366-0d80a7549ec7)

**Comment by Blind4Basics** [comment]
@craigsmithmd : CW username, please? (I found an account with your name, but it has 0 kata solved)

**Comment by craigsmithmd** [comment]
@Blind4Basics Thank you! https://www.codewars.com/users/victormarcos1/ 
![IMG_4384 (1)](https://github.com/codewars/codewars.com/assets/132099235/03f84c92-7b6f-44d9-b887-c5d58f1a18ff)

**Comment by Blind4Basics** [comment]
...and how many github accounts do you have, exactly...? => already answered.
