### ISSUE TITLE
Cannot Submit [Final] Answer

### ISSUE THREAD

**Issue by joewhale** [Codewars/codewars.com#567]
For the Kata 'Greet Me', when I press the submit button, "I have passed all tests", but the submit final answer does not show up. I have tried logging out and logging back in.

**Comment by matthewmoppett** [comment]
I have the same problem (https://www.codewars.com/kata/simplifying-multilinear-polynomials/train/haskell) -- I can pass the final tests, but when I do, no "submit" button is shown.

**Comment by kazk** [comment]
This should be fixed now
