### ISSUE TITLE
Cannot enlist

### ISSUE THREAD

**Issue by bdealmeida** [Codewars/codewars.com#570]
After completing the Java enlistment test I've tried enlisting but am brought to the same page. I've linked my GitHub account, filled all information numerous times, and have even tried on a different computer but nothing changes. Also, there are no messages on the page (IE: I need to fill out something else), the page looks the same as before I even tried enlisting the first time

**Comment by luomiao55** [comment]
When my friend try to sign up, he also met this problem

**Comment by jhoffner** [comment]
I think there might be a certain condition with github signups that causes something to get messed up. The only thing that I can think of off the top of my head is that perhaps the email on the github account isn't set or is different... 

This is a high priority item and I will be looking into it within the next few days. Sorry for the inconvenience.

**Comment by bdealmeida** [comment]
No it's okay! I also had a teacher try without a github, and it did the
same to him. This sounds like an awesome site, I can't wait to use it

**Comment by pezzabros** [comment]
Hi, I am also experiencing the same problem during the registration process. My Github account is connected, I fill the form and when I click on "Enlist" I get redirected to the same page. Any idea?
Thanks

**Comment by luomiao55** [comment]
I do not think this is the issue of github, I try to sign up without linking the github account but it still not work

**Comment by bdealmeida** [comment]
Yeah it's odd, like maybe the HTML link isn't pointing the right way or
something. Obviously I doubt that's what's wrong but it doesn't seem like a
normal problem. Maybe the server processing enlistments and directing the
user to the next page is falsely redirecting the user back to the sign up
page?

Also, when attempting the first few times I noticed there was a password
input, but after a few tries that went away

**Comment by bdealmeida** [comment]
Just tried again and it worked! After tinitially trying I had to do the
test again, but upon completing that I could sign up

**Comment by rhubley** [comment]
Could not signup in Edge or IE 11 on Windows 10. The submit button continued to return you to the same question.

**Comment by IIIRADIII** [comment]
Same error on Google Chrome. After completeng C# and trying to press enlist nothing happened.

**Comment by Djok0** [comment]
Same here.
Chrome, Firefox, Safari, with or without github account.

**Comment by TitouanT** [comment]
Me too, I tried several times but always the same page show up again and again.

**Comment by purpose50** [comment]
i have the same problem

**Comment by jhoffner** [comment]
@purpose50 Did you just try now? I've been investigating and have a error report to indicate each time it happens and havent seen it in 30 minutes. Also I just made a change that I had hoped would fix it. 

Can everyone else having this issue please leave the username you signed up with, along with your github username (if you used that), and let me if the loop happens on the code challenge or on the profile setup step. Thanks.

**Comment by purpose50** [comment]
I just tried it again and it worked. i'm in, thanks.

**Comment by purpose50** [comment]
another error, i bypassed the login page but got this: "Fix "Aw, Snap!" page crashes and other page loading errors

**Comment by purpose50** [comment]
able to log in now

**Comment by IIIRADIII** [comment]
It works now for me

**Comment by domagojk89** [comment]
I have the same problem, anybody found a solution?

**Comment by mutenous** [comment]
I have this error. SIgning up would Aw Snap! me so I deleted site cookies and tried relogging with no luck.

**Comment by raydot** [comment]
I am getting this error too.  I just get a message "Failed to connect account" with no further explanation on FF, Chrome, Safari for OS X.

**Comment by cherno1985** [comment]
I'm having the same issues, somehow, after clearing cookies and cache it gets back to the sign up page..

Could it have something with it?

**Comment by HenryCavendish** [comment]
same.. what to do? how to fix this damn issue?

**Comment by bdealmeida** [comment]
I tried again after a day or two and it worked, didn't change anything
though.

**Comment by kazk** [comment]
This should be fixed now.

Please try again if you haven't already signed up. And please open a new issue if this happens again.
