### ISSUE TITLE
Not awarded points

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#572]
I completed 3 Katas today. Points remain stuck on 942. Using Firefox. No question I did do SUBMIT FINAL 3 times. Completed Katas show in my profile - just no points :-( 

Similar #566?

**Comment by jbampton** [comment]
I have the same problem,  just did 5 kata and got no points.

**Comment by jbampton** [comment]
My points came the next day, so I don't have a problem anymore.

**Comment by dinglemouse2250** [comment]
Mine too. There was a 12 hr delay for some reason. So I am closing this issue.

**Comment by Julix91** [comment]
How can you say you don't have a problem? The delay means something is off/weird, no? Or is that expected behavior?
