### ISSUE TITLE
Enforce 1-second time limits on new Kata test procedures (prevent future 7-second timeouts on valid solutions)

### ISSUE THREAD

**Issue by J-Sorenson** [Codewars/codewars.com#574]
There has been a bit of a trend with some of the level 4/5 Kata to evaluate a solution based on performance.  I understand some cases where doing it the "wrong way" will cause it to run for 10 minutes instead of 1 second.  However, some Kata have the optimal solution still take 3 to 4 seconds.  This leaves little to no variation in user-submitted code without getting the dreaded 7-second timeout.  In fact, there are days where a "passed" submission will fail simply because the server has too many tasks.

CodeWars architecture is not designed to easily profile your code.  When you get the 7-second timeout, you don't even  get a list of the attempted inputs, so you can't test it offline and see what input caused your code to spiral.

Besides, making a Kata that is purposefully designed so that most submissions will take too long is just **mean** to the CodeWars server.  The admins are having a hard enough time keeping things afloat on a budget.

As far as I see it, if your proposed solution does not pass the tests within **ONE** second, then the proposed Kata should be **rejected**.  CodeWars is not meant for benchmark challenges, and it gives frustratingly minimal information to the person when their code exceeds the time limit.  This intent should be made clear to anyone developing the Kata.

**Comment by kazk** [comment]
Closing this because I don't think this is Codewars issue. Authors should handle this depending on their intentions.
Also, it's been a long time and a lot have changed. We've recently [replaced the runner](https://github.com/Codewars/codewars.com/issues/1336) and it should have better performance.
