### ISSUE TITLE
Is the preview environment configured for OAuth? 

### ISSUE THREAD

**Issue by zyrolasting** [Codewars/codewars.com#578]
GitHub via OAuth is fine on `codewars.com`, but when starting from `preview.codewars.com` GitHub redirects back using a URL containing the query string param `error=redirect_uri_mismatch`. Console also reads `[c: clientId must be either a string or null; statusCode=400; code=40012]`. IIRC about OAuth, this is a configuration problem, so no code needs to change.

Did you guys never intend to allow OAuth use on `preview` and forgot to remove the GitHub login button, or will it be a valid origin for SSO later?

EDIT: Added screenshot and edited text for clarity

![screenie for codewars oauth](https://cloud.githubusercontent.com/assets/1312121/18490054/57240748-79ce-11e6-9d74-9cb06a60d03e.png)

**Comment by guioconnor** [comment]
I saw a similar error.

Accessing Kata in a logged out state causes this error while the UI displays a "loading description" message.

This is true for both 8Kyu Katas as well as Beta (and presumably the ones in between to).

8Kyu: https://www.codewars.com/kata/sum-mixed-array

Beta https://www.codewars.com/kata/57f026cfe77282a4d8000200

```ably.min.js:217
Uncaught [c: clientId must be either a string or null; statusCode=400; code=40012]
d @ ably.min.js:217
d @ ably.min.js:220
connect @ application-9aac560….js:32
init @ application-9aac560….js:32
(anonymous function) @ application-9aac560….js:32
u @ application-9aac560….js:31
(anonymous function) @ application-9aac560….js:31
f @ application-9aac560….js:15
fireWith @ application-9aac560….js:15
ready @ application-9aac560….js:15
H @ application-9aac560….js:14```

![image](https://cloud.githubusercontent.com/assets/35854/19022015/29b3e5ba-88c6-11e6-898c-d0f1bc617df9.png)

**Comment by kazk** [comment]
Closing old issue. You should be able to log in to preview with GitHub.
