### ISSUE TITLE
Kata editor tooltip text wrong for Publish button?

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#579]
In the Kata Editor the `Publish` button has a tool-tip that says something like `Earn +1 honor for publishing`.

But when I published a Kata I thought I got more than just 1 point. 

Maybe the text is not in step with the scoring system?

**Comment by kazk** [comment]
![image](https://cloud.githubusercontent.com/assets/639336/24386645/898ffd40-1325-11e7-8439-0092c68033f1.png)

---

Airtable from [Honor and Leaderboard Updates](https://medium.com/@Codewars/honor-and-leaderboard-updates-a1491f2cb2e2):

![image](https://cloud.githubusercontent.com/assets/639336/24386693/d3894532-1325-11e7-8d96-d011f27b4040.png)
