### ISSUE TITLE
Neither the save or publish functionality when translating a kata seems to work for me

### ISSUE THREAD

**Issue by zacbraddy** [Codewars/codewars.com#58]
I'll preface this by saying I could easily be misunderstanding the process here, perhaps my code is waiting to be approved or something. I had begun writing a translation for a kata that I had solved. I had solved it in javascript and I was working on a translation for c#. I got about half way through and had to stop because I had to go to work. I hit save and when I returned to the site later that day I couldn't find anywhere on the website to get back to my saved translation. 

If I'm just missing something here please let me know where I can find these saves! In any case I re-wrote my solution and test cases, finished it all up and hit publish, which I was told was successful however upon returning to the orginal kata I see no c# translation, I have no authored translations on my profile and my translation seems to have just disappeared.

I haven't tried this on any other kata's to see if it was just the one I was trying to translate but I'm not willing to put in the time translating another kata if my work is just going to be lost! If you think there is something I am missing I'm happy to be corrected but I couldn't find anything in the "docs" section to help me and my publish just doesn't seem to be appearing.

Cheers.

**Comment by bkaes** [comment]
Did you check your [profile's draft translations section](http://www.codewars.com/users/ozrevulsion/draft_translations)? Which kata did you translate? Do you have the kumite ID still in your browser history, if so, could you provide it?

**Comment by ozrevulsion** [comment]
Hi Ben

Yep, it was indeed, me being a plonker. I found my solution (although it
was an incomplete solution from a few saves back) in my draft_translations.
Btw where would I get to that in the front end I haven't seen it anywhere?!
I corrected the code that was saved and hit publish again. This still
didn't make the translation show up on the front of the kata I translated.
I took a guess at there being a published_translations section as I didn't
see the kumite in the draft anymore and I seem to have published it twice
now! But it still doesn't show up on the front page, maybe this will
refresh over time?

Here is a link to both published kumites.

The one I published today
http://www.codewars.com/kumite/55409100ee5c2b9a6e0000d6?sel=55409100ee5c2b9a6e0000d6

The one I published yesterday
http://www.codewars.com/kumite/5541e05a7390e31b58000098?sel=5541e05a7390e31b58000098

Could it have had something to do with me missing off the using statements
for the nunit framework in the example test cases and submitting them in
that state? Or could it be the Console.WriteLine I've included in my
solution tests?

Cheers
Zac

**Comment by GiacomoSorbi** [comment]
Mh, it happened more than once to me: you may have been disconnected (the system won't tell you until you refresh the page).

A good habit about this is saving and then checking if the cursor in your current box is at position 0 of the text; if not, you didn't save a thing, so copy&paste your work elsewhere, open a new tab with CW, login and finally refresh the editor page (if you first refresh it, you end up in the login screen in the same tab and are not sent back to the editor once logged), so that you can copy and paste back things to keep working.
