### ISSUE TITLE
[Help] 6 kyu Multiples of 3 and 5

### ISSUE THREAD

**Issue by DoctaCloak** [Codewars/codewars.com#580]
I am not sure if this is intentional or not... or just worded incorrectly.  So for this kyu, are you guys requesting that the sum be below [sum 23] || did you mean to pass in the value of 1,000 and request that you pass in all values that are below that, except to only count multiples of 3 * 5 which is 15, once?  It isn't actually possible to run an equation and return the sum of 3 and 5 if this wasn't the case, because you aren't able to go over 10?

I am going to run my code and see if it goes through, but I think that you guys missed smtg if you're quoting from Project Euler.

**Comment by jhoffner** [comment]
This is a content issue, please post on the discourse page of the kata.
