### ISSUE TITLE
unable to submit on Directions Reduction

### ISSUE THREAD

**Issue by davilla77** [Codewars/codewars.com#581]
Similar to tdm's comment on https://www.codewars.com/kata/directions-reduction/discuss

when I hit Submit on my C++ solution it produces the output:

Time: 27ms Passed: 0 Failed: 0

and does not give me the option to submit a final solution. I would think this is a problem with the kata, but some others are able to get their solutions to go through, including g964.

CodeWars username davilla

**Comment by kazk** [comment]
Closing as duplicate. See #1411 for related issue.
