### ISSUE TITLE
The type or namespace name `VisualStudio' does not exist in the namespace `Microsoft'.

### ISSUE THREAD

**Issue by KrasimirGeorgiev** [Codewars/codewars.com#586]
I am new to codewars. On my first task i get an error: 

"/tmp/csharp116820-17-joi5m/fixture.cs(1,17): error CS0234: The type or namespace name `VisualStudio' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?
Error: Command failed: mcs -out:/tmp/csharp116820-17-joi5m/test.dll -lib:/runner/frameworks/csharp/nunit -r:nunit.core.dll,nunit.core.interfaces.dll,nunit.util.dll,nunit.framework.dll,Newtonsoft.Json.dll,EntityFramework.dll,Qualified.dll -reference:System.Numerics.dll -reference:System.Drawing.dll -reference:System.Data.dll -reference:System.IO.dll -reference:System.Linq.dll -reference:System.Linq.Dynamic.dll -reference:System.Linq.Expressions.dll -reference:System.Messaging.dll -reference:System.Threading.Tasks.dll -reference:System.Xml.dll -reference:System.Web.dll -reference:Mono.Linq.Expressions.dll -target:library -warn:2 /tmp/csharp116820-17-joi5m/code.cs /tmp/csharp116820-17-joi5m/fixture.cs
/tmp/csharp116820-17-joi5m/fixture.cs(1,17): error CS0234: The type or namespace name `VisualStudio' does not exist in the namespace `Microsoft'. Are you missing an assembly reference?"

I think it's because of the the Example Test Cases  - using Microsoft.VisualStudio.TestTools.UnitTesting;
If anyone has an idea why is this error and how to fix it i would be thankful.

**Comment by jhoffner** [comment]
Not sure which kata  you are referring to but it would be best to log an issue in the discuss section, since it sounds like its content related.
