### ISSUE TITLE
Kumite editor display current code, but "run" button sending older versions

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#59]
It happened to me many, many times, but this one I got a good screen as an example:

![image](https://cloud.githubusercontent.com/assets/4815731/7441436/76fde1e4-f0e8-11e4-9cfe-495f4237f077.png)

In this case it is obvious that there is not a single line from the Ruby version I took as a template for the Python version, but in other instances getting an error and finding what's wrong when your code is indeed all correct can be rather annoying.

Usually that is all solved saving, refreshing and then running the tests again.

I am on Chrome latest on Ubuntu, if that may be of some interest.

**Comment by GiacomoSorbi** [comment]
Another instance, this time with reversed conditions (from Python to Ruby), if it helps:

![image](https://cloud.githubusercontent.com/assets/4815731/7445480/086b19b2-f1b6-11e4-81ea-7d0b0769db4a.png)

**Comment by jhoffner** [comment]
Did this just start happening recently?

**Comment by GiacomoSorbi** [comment]
Maybe a bit more frequently, but I have encountered it in, say, at least the last two months.

**Comment by jhoffner** [comment]
@GiacomoSorbi did this issue go away. This is an old ticket I would imagine this isn't a problem anymore.
