### ISSUE TITLE
List of privileges I can unlock as I gain more honor

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#590]
Hi,

it would be nice to have a list of privileges which one can unlock as one gains more honor (3000 honor points -> One can approve katas). I've found a link in the discussion under [Ranking & Honor](http://www.codewars.com/docs/ranking-and-honor-1) page but this doesn't work anymore.

Regards,

suic

**Comment by brendanvos** [comment]
Hi suic,
I wouldn't be surprised if you already seen this as you are so active in the community, but a list has been compiled and released in the [airtable](https://airtable.com/shrDt7USqZ7GStRb0/tblk0mEQbDl3JWQrT/viwdZcVcThJKTXyuB) within the [Medium post regarding the honor and leaderboard updates](https://medium.com/@Codewars/honor-and-leaderboard-updates-a1491f2cb2e2).

This issue can likely be closed, although it would be nice to have a place where any and all future privilege changes will be reflected and which can be accessed from Codewars itself.
-Brendan

**Comment by suic86** [comment]
@brendanvos Thanks! To be honest, I've seen that document but I didn't notice the Priviliges tab :)
