### ISSUE TITLE
Getting a 400 when clicking 'train' link on dashboard

### ISSUE THREAD

**Issue by kgraves** [Codewars/codewars.com#596]
I'm new to codewars, just signed up, and am trying to check out the training feature, but when I click it, I'm getting a 400. Here's the [page](https://www.codewars.com/kata/5502c9e7b3216ec63c0001aa/train/train) that it redirects me to.

**Comment by jhoffner** [comment]
Looks like there is an extra train in the URL. thats odd. Thanks for reporting we will look into it.

**Comment by kazk** [comment]
Closing old issue. Please let me know if this is still happening.
