### ISSUE TITLE
Timeouts :(

### ISSUE THREAD

**Issue by ralphcallaway** [Codewars/codewars.com#6]
Didn't realize how much I really loved this site until I couldn't submit a solution for going on two weeks now.

Steps to reproduce:
- Run tests for any kata
- Submit solution for any kata

Outcome: 
- "Submission Timed Out"

Hopefully killing off the issue forum gives the team time to get to the bottom of it.

**Comment by nathandoctor** [comment]
Hey Ralph - I just tested and am getting it working on every language except Java, which is hitting our timeout pretty often. Is this the language you're using? Because of JVM load time that language has been pretty non-performant and we're working on fixing it.

**Comment by ralphcallaway** [comment]
@nathandoctor been using coffeescript pretty much exclusively for the past few weeks, is there is any diagnostic info I can provide when a timeout occurs?

**Comment by jhoffner** [comment]
Issue is a recurring problem with background jobs somehow being stopped. Servers have been restarted and the site should be working as normal, I'll keep investigating the underlying issue.

**Comment by ralphcallaway** [comment]
@jhoffner keep up the great work, just tested a couple kata and it's flying at the moment, let me know if there is any diagnostic details on my side i can provide that would assist in troubleshooting the underlying issue (will close this for now and reopen if it starts occurring again)
