### ISSUE TITLE
Your next challenge widget shows solved kata

### ISSUE THREAD

**Issue by rohitpaulk** [Codewars/codewars.com#60]
The "Your next challenge" section on the homepage shows me kata that I've already solved. When I click on the title, I see 'Train Again' on the kata's page.

**Comment by jhoffner** [comment]
How often does this happen and what language and "focus" do you have selected?

**Comment by rohitpaulk** [comment]
Hey @jhoffner, I only noticed this today, not sure if it's happened before.

The language is Ruby, and the focus is Fundamentals.

**Comment by james64** [comment]
I noticed the same today for me. The language here is java.

**Comment by paul-calvelage** [comment]
Issue https://github.com/Codewars/codewars.com/issues/282 might be related to this.  Something is going on with marking kata as completed.

**Comment by dinglemouse2250** [comment]
Just saw the same thing today for SQL Kata. It suggested a "rank up" Kata which I had already completed.

**Comment by jhoffner** [comment]
@dinglemouse2250 it makes sense for SQL. there are only a handful of kata so it has to cycle through without much other choice.

**Comment by dinglemouse2250** [comment]
I assumed the "Your next challenge..." would filter out ones I had already done. I have completed all of the current SQL ones so I expected it might say something like `"There are no items to display"` (same as the Kata Search page does).

**Comment by jhoffner** [comment]
Yeah the idea of code kata was originally something that you repeat your training on, to get better each time. Most users ended up being not that interested in repeat training but for the trainer we decided it's better to give repeats vs nothing at all.

**Comment by jhoffner** [comment]
AFAIKT this is working as designed. You are not given challenges you have solved unless you have cycled through all of them. Closing until I hear otherwise.
