### ISSUE TITLE
javascript 'WeIrD StRiNg CaSe' kata test case broken

### ISSUE THREAD

**Issue by kgraves** [Codewars/codewars.com#600]
Many people are talking about it [here](https://www.codewars.com/kata/weird-string-case/discuss)

The test passes `this is a test` into the written function, and here's the output:

```
Expected: 'ThIs Is A TeSt', instead got: 'ThIs Is A tEsT'
```

You can see the error between the 'A' and the 'T' of test. The algorithm is supposed to ignore spaces, as evidence by the beginning of the expected answer.

**Comment by jhoffner** [comment]
Please log this issue on the kata discussion section, as an issue. Github issues is for site functionality only.

**Comment by kgraves** [comment]
@jhoffner It already is. It has been tagged as an issue at least 7 times in the discussion, and has a multitude of comments about the problems with the tests.
