### ISSUE TITLE
Kata republishing problem

### ISSUE THREAD

**Issue by Alpha-H** [Codewars/codewars.com#601]
I'm having **serious** issues with republishing a kata . At first I accidently typed in the JS solution window now I just can't delete it . Whatever I do - unpublish the kata and then delete the language but when I republish it still shows that there's a JS version of the kata although I deleted it many times , then saved the kata and then republished . Need immediate help!

**Comment by jhoffner** [comment]
Which kata is this for?

**Comment by Alpha-H** [comment]
It was for my kata 'Abundant Numbers'. However, I really got tired of it
and started from the scratch again. Then it worked.
