### ISSUE TITLE
Top percentile is not as expressive as "Top 0.01%" 

### ISSUE THREAD

**Issue by LesRamer** [Codewars/codewars.com#603]
StackOverflow.com ranking displays the elite-user percentile ranks as (top 0.01%) whereas codewars only reports whole percentiles (e.g., "#198 / 100%"). StackOverflow's "top 0.01%" distinguishes an individual as being among the best of +10k.

"Top 0.53%" is NOT necessarily any more useful than "Top 1%". It is arguable that leaving a little wiggle-room to the "imagination", perhaps showing "Top" stats beginning only when you get above the 50th percentile, "Better than average", "Top 10%", "Top 1%", "Top 0.1%", "Top 0.01%".

So recapping, the size of the codewars community is such that whole-integer percentiles are not particularly telling. I think lots of the community would use the number as a line on their resume to promote themselves as being knowledgeable if they had a "Top x%" they could use.

**Comment by brendanvos** [comment]
As the userbase of codewars continues to grow I think this simple change becomes more valuable.

It would also be interesting to have an approximate tally of the number of registered users on the about page.

**Comment by kazk** [comment]
Number of registered users can be somewhat approximated by going to one of the easiest challenges, sort the solution by newest, then visiting the top user's page.

For example, this is from the newest submission of "multiply" kata in JavaScript:

![image](https://cloud.githubusercontent.com/assets/639336/24575155/fa1228f6-1652-11e7-9423-c24aa0ddfdf6.png)

**Comment by brendanvos** [comment]
I actually tried this before, but I was unsure about the ranking behavior for users at the same kata. I just managed to find 2 users with 2 honor and they had distinct rankings, so this method should be decent.

After much searching I managed to find a user with only 1 honor:
![image](https://cloud.githubusercontent.com/assets/11360165/24579950/90568080-16cd-11e7-88a4-2cafb2df18e2.png)

**Comment by brendanvos** [comment]
Actually, I just found some potentially contrasting information;
![image](https://cloud.githubusercontent.com/assets/11360165/24579997/9ea6162c-16ce-11e7-9bcc-c7ad4209a574.png)

Although I'm not sure how this behaves with users completing a kata multiple times.

**Comment by dinglemouse2250** [comment]
I think the 287K users is somewhat misleading.

It sounds great but it is not really a true representation of reality if there are 100K who just put their toe in the water for one or two Kata but then never returned. 

Perhaps the percentages should be based on the number of "active" users where that might means something like they solved a Kata in the past 3 months. Or maybe only count users with > 30 honour (say) to filter out all the outliers who never came back.

**Comment by brendanvos** [comment]
@dinglemouse2250 I think it would be acceptable for the about page to say "X registered users".

While that certainly wouldn't be a representation of active users it would give a good idea of the scale and market-penetration of the site.

**Comment by Voileexperiments** [comment]
Clearly the way to go is to present a honor-rank graph (with possible log x-axis).

If my previous experience at these kind of data are correct, it should be quite linear if you present it that way.

**Comment by kazk** [comment]
Changed to top percentile rounding to the nearest hundredths. I'll make some adjustments later. #1111
