### ISSUE TITLE
Twitter linking

### ISSUE THREAD

**Issue by Alpha-H** [Codewars/codewars.com#607]
I've been trying to link my twitter account with codewars since the day I joined. And I've been getting the same **5xx:Server Error** from day one. How can I avoid this error??? By the way the error **500** is also very frequent and creates issues when submitting kata's . I think other people face the same issues. Any ideas about them???

**Comment by NoRelect** [comment]
I have this error as well :(

**Comment by tachyonlabs** [comment]
Me too ... I tried some weeks ago, and then just tried again now with the same error.

**Comment by tsukanovvv** [comment]
The same error...

**Comment by tachyonlabs** [comment]
Oh hey! I just tried linking my Twitter account again and it finally worked with no problems! You other people should give it a try as well and see if the same is true for you ...

**Comment by NoRelect** [comment]
It works! Thank you very much
