### ISSUE TITLE
C kumites bad links

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#609]
https://www.codewars.com/kumite/540dd412d333dcf9e00005f5?sel=540dd412d333dcf9e00005f5
https://www.codewars.com/kumite/573a33866da1d0677a00164a?sel=573a33866da1d0677a00164a

> Looks like there was a server error! (500)
> 
> We have taken note of the situation and will be looking into it.
> 
> If you would like to supply us with some details as to how this happened please visit our Github issues >list. This will help us get things fixed faster.

**Comment by kazk** [comment]
Can't reproduce. Please let me know if this is still happening.

**Comment by javatlacati** [comment]
Fixed ty!
