### ISSUE TITLE
New fork notifications not working

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#61]
Hoping of not being too annoying with bug report, here is a new one, as by screenshot (and not that any new comment on discussions seem to work perfectly, but that's another issue):

![image](https://cloud.githubusercontent.com/assets/4815731/7446589/5f72df3e-f1dd-11e4-9ac4-e45e64c525ae.png)

**Comment by GiacomoSorbi** [comment]
FYI, it happened again:

![image](https://cloud.githubusercontent.com/assets/4815731/8324777/0d65f2fe-1a54-11e5-84c4-415ba9236329.png)

**Comment by jhoffner** [comment]
This should be fixed now. Please let me know if it happens again
