### ISSUE TITLE
Changing honour points

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#610]
The honour points of some warriors are changing without doing anything.

Is there a change in the pointing system? Or is this a bug?

**Comment by jhoffner** [comment]
Yes, I had updated the blue and purple kyu based rewards to be higher (in some cases exponentially) - particularly for content creation. However you just made me realize that there should probably be a more official announcement if thats going to happen, as well as probably a discussion i gitter or someplace to help solicit feedback on what changes make sense. 

I'm going to rollback the updates for now.
