### ISSUE TITLE
In C++ "boost/algorithm/string.hpp" is not available.

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#615]
Hi,

in my kata https://www.codewars.com/kata/correct-the-time-string/train/cpp , that works for a long time in C++, is now a problem.

The error message:
"-isystem /runner/frameworks/cpp  fatal error: 'boost/algorithm/string.hpp' file not found
# include <boost/algorithm/string.hpp>"

Did you changed files for C++? Could you fix this, so that this library is available again? Or did maybe only changed the path?

**Comment by cordarei** [comment]
I encountered a similar error when submitting a solution to another kata: https://www.codewars.com/kata/57591ef494aba64d14000526/discuss#57fddf15a5372ed0790000c9

    -isystem /runner/frameworks/cpp  fatal error: 'boost/range/numeric.hpp' file not found
    #include<boost/range/numeric.hpp>
            ^
    1 error generated.

**Comment by FArekkusu** [comment]
According to the comments under the kata mentioned by @cordarei it works now. @SteffenVogel79's kata works too. Perhaps this issue could be closed.

**Comment by kazk** [comment]
Thanks @FArekkusu
