### ISSUE TITLE
Solutions remain locked after Submit Final

### ISSUE THREAD

**Issue by dmitryleskov** [Codewars/codewars.com#617]
My solution passed all tests, so I clicked Submit Final, but solutions remained locked. I tried logging out of Codewars, logging in again and re-submitting, but it did not help.

**Update 11-Oct-2016:** Noticed that the Kata is displayed among Completed in my profile.

Kata URL: https://www.codewars.com/kata/two-to-one/train/python

URL of the locked solutions page:  https://www.codewars.com/kata/5656b6906de340bd1b0000ac/solutions/python

**Comment by kamork** [comment]
I'm having the same problem, it seems to be keeping me in a loop of the same kata as well. (I click "next kata" and will find myself back at the same one.)

**Comment by dmitryleskov** [comment]
Any chance for this issue to get some attention?

**Comment by rollietikes** [comment]
Adding to this issue as it seems to be affecting one of my Kata as well and I have also seen this same thing before on Kata I myself solved.

https://www.codewars.com/kata/ad2070-help-lorimar-troubleshoot-his-robots-ultrasonic-distance-analysis/ruby

Two users have now reported they solved the Kata but the solution remains locked. I also noticed user AndyCamino solved the Kata and it is reported as solved on his profile in language Ruby but there is no solution posted in the Ruby Kata. 

![screenshot from 2016-11-27 11-00-46](https://cloud.githubusercontent.com/assets/7141278/20651028/df0a61ae-b491-11e6-9d02-9733bf0a24a4.png)

**Comment by s2k** [comment]
Sme here: I solved the https://www.codewars.com/kata/tiy-fizzbuzz/ruby kata (and it's listed in the "Completed Kata" section in my profile, and *yet* the solutions are locked.
![Screenshot 2019-07-05 at 09 58 56](https://user-images.githubusercontent.com/118248/60707388-e52e8a80-9f0b-11e9-837e-f13e0383c76f.png)
![Screenshot 2019-07-05 at 09 58 34](https://user-images.githubusercontent.com/118248/60707395-ec559880-9f0b-11e9-87f7-2188bd9f2ff7.png)

**Comment by hobovsky** [comment]
#1683

**Comment by kazk** [comment]
The issue should be fixed (the affected data from the past is not yet fixed). If this happens again, please let me know by commenting on #1683.
