### ISSUE TITLE
toExponential is not a function

### ISSUE THREAD

**Issue by douvaughn** [Codewars/codewars.com#618]
Kata: https://www.codewars.com/kata/rainfall/train/javascript

When I run the test I pass all the test, but get this error:

> TypeError: actual.toExponential is not a function
>    at assertFuzzyEquals
>         at /runner/frameworks/javascript/cw-2.js:179:21
>     at Promise._execute
>     at Promise._resolveFromExecutor
>     at new Promise
>     at Object.describe
>             at Object.handleError
>         at ContextifyScript.Script.runInThisContext
>     at Object.exports.runInThisContext

**Comment by kazk** [comment]
This is not Codewars issue.
I think you're returning string `'-1'` when the record is not found, confused by the description. I made a [suggestion](https://www.codewars.com/kata/56a32dd6e4f4748cc3000006/discuss#58d9e2e4091c110e8600019b) to fix this.
