### ISSUE TITLE
'Your next challenge' widget escapes '>' in code

### ISSUE THREAD

**Issue by rohitpaulk** [Codewars/codewars.com#62]
![screenshot from 2015-05-04 17 01 25](https://cloud.githubusercontent.com/assets/3893573/7452776/98a63704-f27f-11e4-80dc-0dccd16dd094.png)

**Comment by bkaes** [comment]
Duplicate of #15?

**Comment by rohitpaulk** [comment]
Aah yes. Thanks, closing this.
