### ISSUE TITLE
Feature: Ignore solutions, comments and notifications of certain users

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#623]
## Feature:

Ability to ignore solutions/forks (don't show them), comments (don't show them) and notifications (don't get them) from users on blacklist in user profile.
## Rationale:

1. In my understanding CodeWars is a place where people should enjoy coding and learning new things from each other and not about annoying discussions and fighting against each other and having battles about nonsense. Some users and conversations are really annoying and would be good to have a functionality which can filter out comments, solutions and notifications from certain users. This would help focus on important things like creating new content (katas translations) :) 
2. People shouldn't be attacked just because they want to do things in their own way. I also believe that on CodeWars should be freedom to disagree :) and freedom should prevail over enforcement.
3. It could be good prevention of trolling and offensive, disrespectful and _ad hominem_ comments.

**Comment by SteffenVogel79** [comment]
+1

**Comment by dinglemouse2250** [comment]
+1 if someone can teach me how to filter the vacuous babble on gitter

**Comment by the-zebulan** [comment]
`@suic`,

***Battles about nonsense?***

1. I messaged you about an error in your Python translation the other day and you ignored me (as you previously stated you would). After waiting 24 hours (and seeing you active on Codewars throughout), I messaged the katas author, @SteffenVogel79 . To try and help out, I made a fork of your translation to fix the error and submitted it. It was then approved by the katas author.

2. When you turned two simple `test.assert_equals` into 37 lines of over-complicated `Example Test Case` code (including a loop!), I replied with a simplified version (matching the Codewars Python docs style) that was 17 lines long.

These comments/suggestions/translation fixes are for the benefit of all Codewars (Python) users. As you said, Codewars is a place to enjoy coding and learn things from each other. Constructive criticism is part of learning. I have learned many things from your comments, solutions and forks. I enjoy reading your code. 

---
The only thing I would like to add to your feature request is that, if at all possible, I would still like to be able to see your comments and solutions even after you black list me. You're a great coder, just stubborn.

**Comment by suic86** [comment]
@jhoffner 

I don't want to involve you into the thing which started this request. As there's no reaction on it from dev or admin people see since it has been reported I want to ask if you need evidence or if you find this feature request irrelevant. If you think so, I'll close this issue.

I see the reason for this functionality more and more. On the other hand I see 1) the possible technical difficulties/issues 2) and the limited audience etc.

Thanks,

suic

**Comment by SteffenVogel79** [comment]
I would like to have this feature NOT because of the discord between suic and zebulan. I like both of them!

I would like to have this feature because of guys who create issues only because they do not unterstand the description of a kata. Or they change the example tests, because they say these would be wrong, and wonder why their code fails on the real tests...

**Comment by suic86** [comment]
At admins and developers: Please, give some feedback on this.

Recently I heard about CodeWars Pro. I would definitely pay for this feature as it would give me more control over my account. My current solution is to disable all the email notifications as I don't want to be spammed by nonsense. On the other hand this has disadvantages too :(

Regards,

suic

**Comment by jhoffner** [comment]
@suic86 This could be a pro feature maybe. I'm still not 100% sure what is wanted here. If someone logs an issue on your kata, you will want to know about it no matter what so that you can close it. 

As for blacklisting users. So you want to blacklist a specific user and not see their comments at all, or just not be notified? Not being notified is easier to implement, blacklisting comments is likely too much effort for what time I have available.

**Comment by suic86** [comment]
@jhoffner not be notified would be a good first step. Ideally it would be good not to see the comments but I understand the technical difficulties.

> If someone logs an issue on your kata, you will want to know about it no matter what so that you can close it.

This is a good point. Reported issues should be ignored even for blacklisted users.

Thanks,

suic

**Comment by kazk** [comment]
#787
