### ISSUE TITLE
Character encoding issues - Python 2.7 and Python 3.4.3

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#624]
## Py 2.7 Issue

I've create a [kata using non-ascii characters](https://www.codewars.com/kata/hungarian-vowel-harmony-easy). I have the following issue when I print the input and expected output using this code:

``` python
word = u"kéz"
ref = u"kéznek"
print "%s -> %s" % tuple(w.encode('latin-1') for w in (word, ref))
```

I randomly get two different outputs:
1. `kéz -> kéznek`
2. `kÃ©z -> kÃ©znek`

My guess is that there are multiple runners with different output encoding settings.
## Py 3.4 Issue

I'm not able to create a Py 3.4 version as I get this error:

```
Unable to decode the command from the command line:
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 234: surrogates not allowed
```

I wasn't able to repro this outside Codewars.

**Comment by suic86** [comment]
Any update on this?

**Comment by kazk** [comment]
This issue will be tracked in `Codewars/codewars-runner-cli`:

- https://github.com/Codewars/codewars-runner-cli/issues/558
- https://github.com/Codewars/codewars-runner-cli/issues/545
- https://github.com/Codewars/codewars-runner-cli/issues/508
