### ISSUE TITLE
Can't submit Consecutive strings

### ISSUE THREAD

**Issue by aclapinpepin** [Codewars/codewars.com#625]
I pass all 9 tests when I run them:

<img width="1280" alt="screen shot 2016-10-12 at 23 49 43" src="https://cloud.githubusercontent.com/assets/8513369/19328981/bc2d2c7c-90d6-11e6-868e-09c3f062bca7.png">

But when I submit the kata, the 9 tests are green but one random failure occurs:

<img width="1280" alt="screen shot 2016-10-12 at 23 50 14" src="https://cloud.githubusercontent.com/assets/8513369/19329000/dcbaa83e-90d6-11e6-8327-e6c0abeab603.png">

I haven't made any changes the the test suite.

Thanks for your input.

**Comment by jhoffner** [comment]
Consult the discourse section for the kata to see if there are any hints. The tests ran when you submit are not usually the same exact tests that are provided as examples.

**Comment by guilhermefontans** [comment]
I have the same problem

![screenshot from 2017-05-12 02-08-50](https://cloud.githubusercontent.com/assets/12877722/25983076/6285b0f8-36b8-11e7-82c2-8c5d5b85062f.png)

![screenshot from 2017-05-12 02-09-09](https://cloud.githubusercontent.com/assets/12877722/25983102/8abe8de2-36b8-11e7-868d-b4619176ade6.png)

When debugging, it looks like the test is expecting a different value.
![screenshot from 2017-05-12 02-09-46](https://cloud.githubusercontent.com/assets/12877722/25983135/c9e05d3e-36b8-11e7-9e51-cb12f0a12b97.png)
