### ISSUE TITLE
Feature: API for completed problems

### ISSUE THREAD

**Issue by fabiopedrosa** [Codewars/codewars.com#628]
I'd really like an endpoint for checking which problems a specificil user has completed.

Our clan has a bot watching for submissions, so we can tell which users have completed the problems.

**Comment by kazk** [comment]
You can get the list of code challenges completed by the `user` using
`https://www.codewars.com/api/v1/users/{user}/code-challenges/completed`

See https://dev.codewars.com/#get-user:-completed-challenges
