### ISSUE TITLE
Unable to edit an existing approved kata with random number of tests

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#63]
I am a bit embarrassed about talking some code I wrote, but as I am not sure if you read my reply in the aforementioned topic, I would like to point out the matter as I wrote it [here](http://www.codewars.com/kata/ninja-vs-samurai-attack-plus-block/discuss#55465aefb5d2407d7600003f).

The point that having a random number of tests may freeze the publishing of the edits it is just a wild guess, but other parts of the tests I added were readily saved. I tried anything else for hours, including renaming variables or trying different ways, but it really didn't take the randomness in the duel among warriors.

Now the kata got over 500 submissions, so the problem is over (for me, at least), but I still wonder what it could have been and we have about 50% of the tests working on it.

As always, thanks for your kind attention :)

**Comment by GiacomoSorbi** [comment]
To clarify: in the kata editor window, my tests correctly validated each single time; I just could not save my edits if the part with the random number of tests was included.

Saving kata translation in the kumite editor with the same exact logic (random number of tests included) never gave a single problem.

**Comment by jhoffner** [comment]
@GiacomoSorbi is this still an issue?
