### ISSUE TITLE
Whitespace gets discarded in specific situation in code wars editor

### ISSUE THREAD

**Issue by neonphlux** [Codewars/codewars.com#631]
Take this snippet of code:

`for(let i = 0; i < 5; i++) {
  console.log("=  =");
}`

For some reason, in the code wars editor, the first iteration (i = 0), the console.log discards one whitespace between the equal signs. (=WW=) Should be two whitespaces between the equal sign, funny enough the same happens in this editor. If i edit it i see 2 whitespaces between the equal sign, but reading here i see only one.

**Comment by kazk** [comment]
Fixed in https://github.com/Codewars/codewars-runner-cli/pull/438.
