### ISSUE TITLE
Add ability to create kata in pairs or groups

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#632]
## Feature

Ability to create katas in pairs or groups so multiple people can participate on creation of a single kata.
## Rationale

Many newbies on Codwars create new katas which are rather simple or duplicates. IMHO more experienced users should rather help them to create something more interesting (or supervise them) instead of telling them (or complaining) about duplication. However, there isn't an easy way to do it.
## Implemenation

I don't have a precise idea how this should be implemented so let's discuss it here :)

**Comment by jhoffner** [comment]
I would think this could be done using the kumite interface. Basically you could start a kumite, go back and forth and once its ready you would create a kata from the kumite, causing the kumite to become private so that the answer isn't visible anymore.

**Comment by suic86** [comment]
Thanks @jhoffner you're right I'll try it out next time and write about my experience.
Regards,
suic
