### ISSUE TITLE
Impossible to republish, impossible to delete

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#633]
I can't republish this kata:
https://www.codewars.com/kata/56dbeec613c2f63be4000be6/edit/fsharp

I can't delete the F# language in this kata (I thought that could have been a solution...). " Are you sure you want to delete ?" -> "YES, I WANT TO DELETE THIS LANGUAGE" but nothing happens !

**Comment by g964** [comment]
I forked the F# translation and that fork was published but when I try to train on this kata in F# it is always the previous version which remains, not the forked one.

**Comment by jhoffner** [comment]
Do you want to delete F# or edit it? I was able to do a test publish and update the test cases. I didn't try to delete it since I'm not sure if thats what you really want. 

As for forking translations. Did you fork a translation after it was approved? Once a translation is approved, the translation no longer has any effect on the kata - you have to edit the kata directly.

**Comment by g964** [comment]
Could you have a look at:

<https://www.codewars.com/kumite/5807833f2e14ac6d3900013b?se l=58079a7e765e00bedf00002d>

There are two F# translations.
The first one is the original version with a typo in the "transpose" function of the random tests.
The second one is the forked one with the typo fixed. 
Both were approved. I want that the kata on which one trains be the second one but when I published the fork, it appears that one still trains on the original (bad) version.

So if you can, the better is to delete the F# version of the kata and after that I hope I will be able to publish a fresh new one version (without typo:-) 

PS: how come it is impossible to delete a translation?

**Comment by jhoffner** [comment]
Yeah unfortunately whichever translation gets approved first becomes the one copied into the kata.  Its a bug that you can possibly approve 2 or more translations. 

Just to be clear, once a translation is approved, nothing and I mean nothing matters in terms of what you do with a translation after the fact. If you want to fix F#, you need to make the changes directly to the kata itself. 

Thats why I still feel a bit confused about what you want here. Why delete F# from the kata when you could just fix it directly?

**Comment by g964** [comment]
Yes I can edit the translation to fix it and I have done that for that translation so many times but when it is done it is then impossible to re-publish it : always timing-out.
Every single time I get 
`
Please wait while we publish
We are validating your code and publishing your changes. This shouldn't take too long.
`
and 15 or 30 seconds afterwards
`
Publishing Timed Out!
The server timed out while trying to publish your changes.
CANCEL
`
It has already happened with other kata and other languages when republishing...
It is why I want this F# translation deleted hoping that it will be possible to do a new F# translation without problems. As you can see I can't fix the problem directly despite the fact that I have to add only two letters in a word and nobody - atm- did this F# kata.

**Comment by g964** [comment]
@lhysrc reported correctly the following problem because I cannot republish the F# translation:
`
F# version: I get error:

| (::)::_ as m -> List.map List.head m :: transpose (List.map List.tail m)
----------------------------------------------------------------^^^^^^^^^

/runner/stdin(70,65): error FS0039: The value or constructor 'transpose' is not defined
`

**Comment by g964** [comment]
No news?

**Comment by jhoffner** [comment]
I'm on vacation for a wedding but it's at the top of my list for when I get back.

**Comment by jhoffner** [comment]
I deployed some updates, still need to do some of my own testing but so far so good.
