### ISSUE TITLE
C: unable to link math.h

### ISSUE THREAD

**Issue by lilsweetcaligula** [Codewars/codewars.com#636]
During a translation of one of the katas to C, the standard math (math.h) library had to be used. The header (#include <math.h>) was properly included both in the Solution and in the Test Cases section.

Solution section:

```
#include <math.h>

unsigned bin_to_decimal(const char *binstr) {
  // solution code..
  while ((bit = *binstr++)) {
    value += bit == '1' ? (unsigned)pow(2, power) : 0;
    --power;
  }
  // solution code..
}
```

Test Cases section:

```
#include <criterion/criterion.h>
#include <math.h>

unsigned bin_to_decimal(const char *binstr);

Test(CoreTests, ShouldPassAllTheTestsProvided) {
  cr_assert_eq(bin_to_decimal("0"), 0);
  cr_assert_eq(bin_to_decimal("1"), 1);
  cr_assert_eq(bin_to_decimal("101010"), 42);
  cr_assert_eq(bin_to_decimal("10001001"), 73);
}
```

However, during compilation, the following error appears:

```
STDERR:
/workspace/fixture.c /workspace/solution.c -o /workspace/solution ./frameworks/c/criterion.c -I./frameworks/c -lcriterion-0fcad5.o: In function `bin_to_decimal':
/workspace/solution.c:(.text+0x69): undefined reference to `pow'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Commenting out all the calls to the functions in the math.h library makes compilation successful.

I suspect the issue could be that math.h requires the "-lm" switch to be specified to the compiler during compilation, or else linker fails. Perhaps, this could be the case.

Thank you!

**Comment by g964** [comment]
Same thing with `sqrt`.

**Comment by kazk** [comment]
Codewars/codewars-runner-cli@69c23b8
