### ISSUE TITLE
Unable to Re-publish a kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#64]
Following problems with AssertEquals 
http://www.codewars.com/kata/55466989aeecab5aac00003e/discuss
in the Java translation of a kata
http://www.codewars.com/kata/55466989aeecab5aac00003e
I decided to republish it, but since more than 24 hours, it's impossible to republish it!

**Comment by jhoffner** [comment]
Is this still an issue?

**Comment by g964** [comment]
Yes, still an issue. I have for hours:

"Please wait while we publish
We are validating your code and publishing your changes. This shouldn't take too long."

I decided to change the way I used to test with AssertEquals and AssertArrayEquals since Osmosis passed the kata with only one succeeded test.

**Comment by lsolano** [comment]
![code_wars_edit](https://cloud.githubusercontent.com/assets/1569800/8273796/19b3cec0-184a-11e5-8b5a-cbe05944e558.png)

@jhoffner  Same for me,

I'm trying to fix an import, and re-publish a Kata and the GUI dies any time I hit re-publish. I takes (literally) hours if I leave the window open.

Inspecting the network traffic I saw a script (tracker.js / line 6) that keeps doing a kind of ping, every 5 to 10 seconds but it never ends.

`http://data2.gosquared.com/ping?vw=934&vh=955&dw=917&dh=1496&st=0&sl=0&mst=300&msl=0&i=2&et=0&bc=1&cb=_11&a=GSN-087086-V&id=1be3022ea777d29dba752edbf605d6f9&tv=6.3.1677`

   `tracker.js Line 6`

**Comment by hexafraction** [comment]
It seems that this only happens when editing a testcase/testfixture, perhaps since all submitted solutions need to be re-validated. Could you confirm that this is the same behavior for you?
If it is, it might help to run this asynchronously (e.g. check author's solution against testcases, publish, and then revalidate all in the background).
