### ISSUE TITLE
error code can be submited

### ISSUE THREAD

**Issue by differentrain** [Codewars/codewars.com#642]
https://www.codewars.com/kata/length-of-missing-array/cpp
Output logs:

```
  RandomTests
  Log
     2 3 5 Expected: equal to 4
              Actual: 5
You have passed all tests! :)

```

Words "2 3 5" was output by "std::cout<<d.size();" to check what's wrong with my code.
Finally I got the point: I forgot to check the min value of arrays' size,  but here I can submit the error code.
# If I delete "std::cout<<d.size();", I can't pass the tests.

```
std::cout<<d.size();          Pass
std::cout<<d.size()<<' ';   Pass
std::cout<<d.size()<<'\n'; Failed
```
# 

also see https://www.codewars.com/kata/reviews/57d28ed00b77ab18a6000029/groups/580c1adaa592a3833f0014c0

**Comment by kazk** [comment]
This is the same new line problem as #867.

```
2 3 5<FAILED::>Expected
```

**Comment by brendanvos** [comment]
@kazk Is this not also the same as #630 which was closed with Codewars/codewars-runner-cli@25e5609 ?

**Comment by kazk** [comment]
@brendanvos same issue, but #630 is C and this one is C++. I don't think C++ has been fixed yet. See [frameworks/cpp/main.cpp](https://github.com/Codewars/codewars-runner-cli/blob/master/frameworks/cpp/main.cpp).

**Comment by kazk** [comment]
https://github.com/Codewars/codewars-runner-cli/pull/413
