### ISSUE TITLE
Elixir code editor goes black after specific line of code

### ISSUE THREAD

**Issue by sixtead** [Codewars/codewars.com#643]
When I try to paste or type this line of code `Enum.map(fn(x) -> "#{elem(x, 0)}/#{elem(x,1)}" end)` in this kata https://www.codewars.com/kata/some-egyptian-fractions/train/elixir editor goes black and clears all of the lines

**Comment by henryhamon** [comment]
I got the same issue...
In the Kata Editor, when type the "->" the editor goes black and all buttons (save, publish and run) are disabled.

**Comment by parkerjm** [comment]
having same issue with a big block of code. if I remove the `end` of the function and of the module and the text shows correctly. If I type `end` at the end, the screen goes blank. if I then hit backspace to delete the `d` from `end`, the text comes back. so, the text is there and I can still even edit it, but the display is broken.

**Comment by kazk** [comment]
I believe this is fixed (can't reproduce with the example given). Please let me know if it's not.
