### ISSUE TITLE
Code Editor Hot-Key Broken

### ISSUE THREAD

**Issue by rycasorchard** [Codewars/codewars.com#645]
There is an issue with the code editor. When using any combination of keys which has ctrl in, it doesn't work.

Ctrl+leftarrow (to select), Ctrl+C, Ctrl+V, etc.

This looks to be an error with the CodeMirror responding to the Ctrl keypress.

**Comment by kazk** [comment]
CodeMirror was updated to the latest 5.24.4.
If this still happens, please try https://codemirror.net/. Then file an issue on upstream if it's broken there because there's nothing we can do in that case.

Please let me know if it works there and it's still broken on Codewars.
