### ISSUE TITLE
Make validate solution in kata editor to run code in focus

### ISSUE THREAD

**Issue by dinglemouse2250** [codewars/codewars.com#646]
Depending on which tabs had focus when you press the "VALIDATE SOLUTION" button you used to be able to validate any combination of
- (Complete OR Initial) solution 
- using (Final OR Example) Test Cases.

But now it seems only running Complete/Final (regardless of tabs).

So there is no way to check behaviour of example tests or initial solutions

**Comment by g964** [comment]
Right!

**Comment by dinglemouse2250** [comment]
This issue is preventing me publishing Kata

(reluctant to publish something I cannot test all combinations of)

**Comment by kazk** [comment]
Deployed. The button and `Ctrl/Cmd+Enter` uses the active combination now.
