### ISSUE TITLE
Complete The Pattern #12 - c++ version doesn't run

### ISSUE THREAD

**Issue by dex73r** [Codewars/codewars.com#647]
-isystem /runner/frameworks/cpp  fatal error: 'boost/algorithm/string/join.hpp' file not found
# include

```
     ^
```

1 error generated.

**Comment by jhoffner** [comment]
Please log this issue on the kata discussion page as an issue there. Github is for site issues, not content.

**Comment by g964** [comment]
I think it's a site issue: at the beginning of C++ at CW "boost" library was present but had disappeared...
