### ISSUE TITLE
C++ Test Framework Cheat

### ISSUE THREAD

**Issue by LawfulHacker** [Codewars/codewars.com#648]
The user Durdo [reported](http://www.codewars.com/kata/base-2/discuss#58091ac3b44adbc16b000ebe) an error on my Kata and during the test for his issue I found that the C++ test framework has an issue which allow us to cheat.

This issue was already reported by my on [codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli/issues/252), but didn't get any attention.

It just require one test passing if the real function doesn't return a value.

The following test if pasted on the code, allow us to pass any C++ Kata.

``` c++
Describe(ImJustCheating)
{
    It(BecauseIcan)
    {
        Assert::That(0, Equals(0));
    }
};
```

Tested Katas which allowed this trick:

https://www.codewars.com/kata/strings-mix/train/cpp
https://www.codewars.com/kata/magnet-particules-in-boxes/train/cpp
https://www.codewars.com/kata/getting-along-with-integer-partitions/train/cpp
https://www.codewars.com/kata/valid-braces/train/cpp
https://www.codewars.com/kata/build-a-pile-of-cubes/train/cpp

**Comment by kazk** [comment]
https://github.com/Codewars/codewars-runner-cli/issues/252
