### ISSUE TITLE
c++ solution test

### ISSUE THREAD

**Issue by SFaghihi** [Codewars/codewars.com#650]
In katas "Sum by Factors" and "Infix to Postfix Converter" the final tests fail with passed: 0 failed: 0 and no other apparent error.

**Comment by NilsBrause** [comment]
I have the same Problem with the kata "Are they the \"same\"?". Output just says:

Time: 15ms Passed: 0 Failed: 0
Test Results:
  SameTest
  test1

**Comment by jhoffner** [comment]
I'm not sure how to reproduce either of these issues but some recent changes have been deployed which may have resolved this.

**Comment by kazk** [comment]
Closing this assuming the changes resolved the issue. Let me know if not.
