### ISSUE TITLE
[Feature] D-Lang

### ISSUE THREAD

**Issue by ConnorVG** [Codewars/codewars.com#654]
It would be great if there was a [D-lang](http://dlang.org/) integration.

**Comment by jhoffner** [comment]
Always free to add it [here](github.com/Codewars/codewars-runner-cli)

**Comment by ConnorVG** [comment]
I would love to if I had time, I might look into it this weekend if I can.

**Comment by kazk** [comment]
Codewars/codewars-runner-cli#130
