### ISSUE TITLE
[haskell] Can I have ghc version 8?

### ISSUE THREAD

**Issue by wizzup** [Codewars/codewars.com#655]
Your Haskell [compiler](https://www.haskell.org/ghc/) is version 7.6.3 (released April 2013, thats 3 years 6 months old). Haskell was update alot since then, even the base library, for example
- `Data.List.sortOn` function was introduce
- `<$>` no longer required `import Control.Applicative`

I write code and test locally then copy and retest/submit on web editor (your vim emulation is is not that good, but that just another story). Lot of the time code would run fine locally and then failed on web editor because those minor version mismatch.

I don't need the latest ghc to be able to solve the katas, however, there is no gain to keep practice writting code for an old compiler version.

**Comment by jhoffner** [comment]
The Haskell image is frozen due to issues building it. Something in its build script is no longer working. No one on our team knows Haskell so unfortunately if its going to get fixed, its not likely to be by us. The good news is that you can head over to github.com/Codewars/codewars-runner-cli and contribute/fix it yourself.

**Comment by shapr** [comment]
tongue in cheek question, do I improve my codewars ranking by fixing the Haskell image to support ghc 8? :smiley:

**Comment by jhoffner** [comment]
Nope. But I do want to gather together a list of GH contributors so that everyone gets credit.

A GH Contributor profile badge might be a good idea

Thanks,

--
Jake Hoffner
Sent with Airmail

**Comment by kazk** [comment]
This issue will be tracked at https://github.com/Codewars/codewars-runner-cli/issues/454
