### ISSUE TITLE
Robbed of 50+ points!! - What happened?!

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#657]
Suddenly my honor just _dropped_ by 50 points? 

That's 2 days of effort down the drain :-(

I was able to capture a screenshot from the leader- board showing the discrepancy. But now even the leader=board shows to lower number

![robbed](https://cloud.githubusercontent.com/assets/22114719/19835628/ca6e7364-9ee0-11e6-8b7f-8fc45434f26a.png)

Please reinstate my points,

**Comment by suic86** [comment]
Hi, this happens time to time. [This](https://www.codewars.com/users/dinglemouse/site-events) shows the correct honor points (check Total at the bottom of the page).

Regards,

suic
