### ISSUE TITLE
No Train button on iPhone?

### ISSUE THREAD

**Issue by truth1ness** [Codewars/codewars.com#66]
Does codewars not work on iPhone? I opened up my dashboard on my iPhone and I can't figure out how to start training. The "Your Next Challenge..." box and the blue "Train>" button in it don't appear anywhere. Can you not use this site on mobile?

**Comment by jhoffner** [comment]
None of the web code editors (we use CodeMirror) support touch very well, so we just disabled it for mobile. We could update the editor to revert back to a normal text area for touch - but honestly it's such a  low use case that anyone would want to use it that we just never bothered.

However the commenting system also uses CodeMirror, so we do at some point want to allow that to fallback to normal text areas on mobile.

**Comment by truth1ness** [comment]
Aw, that's too bad. I'd love to be able to work on katas on mobile. Even if editing isn't that smooth it'd be cool to even just view it on my mobile to start thinking about the problem. That'd still be more productive than most other things I do while waiting around with nothing but my phone.
