### ISSUE TITLE
Request Timeout: Language undefined is not supported

### ISSUE THREAD

**Issue by calebkleveter** [Codewars/codewars.com#661]
I have been having issues with some of the katas. I can't set the language that I am using.

[![enter image description here][1]][1]

I use the drop down and select Swift 3, but nothing happens. I can use Haskell and JavaScript just fine, but Swift is being unruly.

If it helps here is what I am running:

- OS X 10.11.6 El Capitan
- Mid 2007 iMac
- Google Chrome 54.0.2840.71

  [1]: https://i.stack.imgur.com/b0dEJ.png

**Comment by zentech** [comment]
I can't use javascript for my second kata
