### ISSUE TITLE
Feature Request: Users with high kyu can mark issues/questions/suggestiong as resolved

### ISSUE THREAD

**Issue by suuuzi** [Codewars/codewars.com#663]
Only the author of a kata can mark as resolved. Users with privilege to edit Katas could mark as resolved, since they can edit and fix issues or suggestions.

There are many good katas stuck in beta from users who don't access CodeWars anymore.

**Comment by jhoffner** [comment]
Good suggestion (and easy to implement). Anyone with 2000+ honor, plus any coauthors/contributors can now mark issues as resolved.

**Comment by the-zebulan** [comment]
@jhoffner ,

I think this is a great idea, thanks for implementing it!

I thought I remembered this being mentioned a while back and just did a quick search and came up with #118 . That issue might be able to be closed now too since it was asking for basically the same thing.
