### ISSUE TITLE
PHP Server Execution Error

### ISSUE THREAD

**Issue by SamuelCaudenberg** [Codewars/codewars.com#666]
Hello,

I'm trying to sign up to codewars to learn some PHP, every time I try to submit the code I get this error though:
Server Execution Error:
Request Timeout: The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
However, when I check the statuspage it says 'All Systems Operational' so I'm not sure what the issue is here.

**Comment by ben8p** [comment]
Same here for JS

**Comment by lucafma** [comment]
Same for Python

**Comment by AndreaAstronaut** [comment]
same for sql

**Comment by maximrondin** [comment]
Same here for JS

**Comment by rkclark** [comment]
Same for Ruby. Been this way for a few hours.

**Comment by ilyakorol** [comment]
Same for SQL
