### ISSUE TITLE
I have 2000+ Honor but I can't resolve issues

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#668]
Today I got the following notification:

> 2000+ Honor: You have now the ability to resolve issues on any kata!

<s>But I actually don't have it :(</s>
Update: But I actually can't do it on some katas ([1](https://www.codewars.com/kata/k-permutations-of-n), [2](https://www.codewars.com/kata/ordering-beers-in-poland/discuss/python), [3](https://www.codewars.com/kata/broken-sequence))

**Comment by CptDemocracy** [comment]
Hey suic86, same problem here. Except that I only have 1491 honor at the moment of writing.

**Comment by SteffenVogel79** [comment]
Use preview.codewars.com! There it is possible. :-)

**Comment by jhoffner** [comment]
Production was deployed
