### ISSUE TITLE
Add a short description about "Kumite" to the about page

### ISSUE THREAD

**Issue by AnTi-ArT** [Codewars/codewars.com#669]
There is no info about Kumite on the help/about pages, nor on the Kumite page itself nor in the forum. I'm new to codewars and after I failed to find info on the page I ended up googling "codewars kumite" just to find the blog post that explains what Kumite is about... I thought it was some kind of PvP system, but it seems more Coop now...

Just one or two sentences on the about page would help tremendously.

**Comment by kazk** [comment]
https://github.com/Codewars/codewars.com/wiki/Kumite
