### ISSUE TITLE
Green Cursor not able to write

### ISSUE THREAD

**Issue by max05051998** [Codewars/codewars.com#671]
Hello everyone
I just started using Codewars some days ago and i think its a great learning tool!
After going through some katas i noticed that my cursor turned green and i wasnt able to type, instead it deleted some random code fragments while i was typing. The Probem fixed itself after some keystrokes, but i think its still worth filing an issue here to let people know this bug exists.

Thanks for developing such a great tool!
-Max

**Comment by evmorov** [comment]
The cursor is becoming green when you're in Vim mode:

![2016-11-08 16_04_49](https://cloud.githubusercontent.com/assets/1059480/20100146/34e90aea-a5cd-11e6-9e0c-00ebde9ed4d9.png)

Just press "VIM" button and everything will be ok. But I suggest you to learn Vim instead. You can start with [this tutorial](http://www.openvim.com/tutorial.html).

**Comment by max05051998** [comment]
Oh wow well this is embarassing 😳😂 Thanks for clearing that up 👍
