### ISSUE TITLE
After finishing a KATA, the page doesn't allow me to upload

### ISSUE THREAD

**Issue by dongqiqi24** [Codewars/codewars.com#674]
As usually, after Run Examples, and Run Suite, the button Run Suite will change to another content to allow me to upload the result and get Honor. However since last week, the button doesn't change(always shows Run Suite.)  And there is alert bouncing out about having error with the server.
This is really confusing, I don't know if the button changes place? Or really have something to do with the server. Thank you.

**Comment by Drazyhaze** [comment]
I am having the same problem. Randomly started and I have cleared cookies, cache, tried different browers. No Solutions.

**Comment by jhoffner** [comment]
I have never been able to reproduce myself but I have a possible fix up on preview.codewars.com

**Comment by Drazyhaze** [comment]
I waited it out and it self corrected. I think it was just servers being at a high capacity.

Thanks !

Reid Quisenberry (mobile)
Lead Web Developer
678.679.1185
www.nlbstudios.com
