### ISSUE TITLE
Test Results issue

### ISSUE THREAD

**Issue by pkcollin** [Codewars/codewars.com#675]
![kata](https://cloud.githubusercontent.com/assets/8688548/20240703/14d01578-a8ed-11e6-9a21-c0806e2d0724.png)

Expected when it runs the tests and the answer never have the numeric values.

**Comment by jhoffner** [comment]
Please provide details

**Comment by pkcollin** [comment]
It's pretty simple, when I run suite or test examples, if it fails under
expected it shows some combination of symbols for expected and actual. Did
you see the picture? I have been using print statements to show the values.
What isn't clear? It has never shown me a numerical value.

**Comment by jhoffner** [comment]
I meant that I have no idea how to reproduce the issue. Please provide the kata, language and code that caused the problem.

**Comment by pkcollin** [comment]
All of my katas. Java. Does anyone else get it? Maybe it's specific to me?
Try maybe uploading a picture? Or connecting to github and git taking the
photo from that?

**Comment by dinglemouse2250** [comment]
(I believe @pkcollin is just referring to those escaped < and > in the test output)

**Comment by pkcollin** [comment]
[image: Inline image 1][image: Inline image 2]

**Comment by pkcollin** [comment]
Any luck?

**Comment by kazk** [comment]
I'm closing this because not enough information was provided. "[image: Inline image 1][image: Inline image 2]" is not visible here. If this is still happening, please open a new issue with details. A picture without context is not helpful. If all of Java kata are outputting like this, please give us some links to them.
