### ISSUE TITLE
Typo on template when translating a kata to TypeScript

### ISSUE THREAD

**Issue by brunolm** [Codewars/codewars.com#677]
If you go to any kata and create a translation for TypeScript it will fill in the fields with some code and there is this error:

```
import {assert} from "chai";"
```

An extra quote after the line.

-----

Also I always replace the `import solution = require('./solution')` with:

```
import { methodName } from './solution';
```

It could also be `import solution from './solution';`

**Comment by g964** [comment]
Translations ro TS have lots of problems when saved and published...
