### ISSUE TITLE
Quote marks become encoded entities on edit (`'` -> `&#39;`)

### ISSUE THREAD

**Issue by brunolm** [Codewars/codewars.com#678]
Translate a kata (use quotes on your code) and save. Go on the link to edit and quotes will be changed from `'` to `&#39;`.

This **only happens in Solution and Test cases** panels, while the **initial setup and example test cases are unaffected**.

Language: TypeScript
Kata: any

![quotes bug](https://i.imgur.com/DqX3IMr.png)

**Comment by kazk** [comment]
Closing old issue. I believe this is no longer happening. Please open a new one if this issue is still there.
