### ISSUE TITLE
By far the most ANNOYING error

### ISSUE THREAD

**Issue by darold-kelly** [Codewars/codewars.com#684]
Randomly, when I attempt to complete a Kata, the computer does not allow me to type for several seconds.   Much like how the insert key replaces characters as you type, this error seems to act in the same manner but does replace anything. It is very annoying because I often have to type random characters for several seconds to fix it. 

I've expereinced it on multiple different computers on multiple connections. It happens randomly, so I do not know what causes it. A way to identify it is tht the space that you try is green.

**Comment by jhoffner** [comment]
Sounds like you have VIM mode on. Green spaces only show up in VIM mode. In the top right of the editor you will see it selected. Unselect it.
