### ISSUE TITLE
Allow empty code blocks for grouped code blocks

### ISSUE THREAD

**Issue by muesli4** [Codewars/codewars.com#685]
As some languages may require further instructions, while others don't, the markdown parser should allow code blocks to be empty. (As an alternative different descriptions could be used for each language.)

**Comment by jhoffner** [comment]
I actually started a half finished feature related to this. I hope to have that out ASAP.

**Comment by kazk** [comment]
[Optional Section Formatting](https://github.com/Codewars/codewars.com/wiki/Markdown-Formatting#optional-section-formatting) can be used now :)

<pre>
This is some shared instructions.

~~~if:javascript,ruby
This content will only be shown if javascript or ruby are active.

**Special Note**: Markdown is still available to be used within these "if" blocks
~~~
~~~if-not:ruby
This markdown will only be shown if ruby **is not** the active language.
```javascript
// still only shown if javascript is the active language, since it has multiple examples next to it
```
```python
# only shown if python is active
```
~~~
</pre>
