### ISSUE TITLE
Python Katas: Run Examples and Run Suite - no response on Output screen

### ISSUE THREAD

**Issue by rangwa** [Codewars/codewars.com#686]
I have been using Codewars for 3 days and was able to complete only 3 katas because the Run Examples and Run Suite don't run most of the time. So I keep checking through the day and sometimes it works but most of the time, it doesn't.

This is for Python.

I tried these but no effect:
Reloading the page
Running https://runner.codewars.io/

Internet: 40 Mbps download, 25 Mbps upload.
Browser:Chrome

Is there something I can do to debug/resolve this issue or is this a known issue on Python?

**Comment by jhoffner** [comment]
Is this still an issue?

**Comment by andrew-dutton** [comment]
Yes. Despite having solved this kata...

https://www.codewars.com/kata/57102bbfd860a3369300089c

...I am unable to view others' solutions.

**Comment by jhoffner** [comment]
OK, sounds like this is the same/related issue as #674, #665, and #688. There are some updates in preview.codewars.com that are meant to correct this issue, though you may need to solve the kata again unfortunately. I haven't been able to reproduce myself so I'm not sure.

**Comment by andrew-dutton** [comment]
Same problem I'm afraid.

I went in the to kata, re-solved it, resubmitted it, same result:

https://preview.codewars.com/kata/57102bbfd860a3369300089c/solutions/ruby

other solutions are locked.

**Comment by jhoffner** [comment]
Thanks Andrew. What is your CW username so that I can debug?

**Comment by andrew-dutton** [comment]
AndyCamino

**Comment by jhoffner** [comment]
@andrew-dutton your issue should now be fixed now on preview. However your issue is different from the one logged here. 

@rangwa do you still see output issues?
