### ISSUE TITLE
Code Editor inserts a new line above current line on every keypress

### ISSUE THREAD

**Issue by cgspeck** [Codewars/codewars.com#693]
Would love to come back to the site but it in unusable on my Android tablet.

As described in the title of this issue, when using the code editor, and when I press any key, a newline is inserted by the code editor above the line which is currently being edited.

Symptoms occured in two different ruby katas. I've never observed this behaviour in any other text entry box.

**Comment by ArchiCat** [comment]
Same problem here. If I attach a blutooth keyboard, it starts to work properly, but not with the onscreen keyboard.

**Comment by jhoffner** [comment]
This is an issue with Codemirror, which unfortunately they have not been able to fully resolve over the years. https://github.com/codemirror/CodeMirror/issues/1196

**Comment by kazk** [comment]
I'm going to close this because the mentioned issue is closed as "WONTFIX".
