### ISSUE TITLE
Can not remove JavaScript from languages for Kata

### ISSUE THREAD

**Issue by ThePaSch** [Codewars/codewars.com#696]
I've been trying to [author a Kata](https://www.codewars.com/kata/583da22670407fb535000364). That Kata had JavaScript preselected as a default language, which I didn't realize until after I wrote some code. I changed the language to C#, removed JavaScript from the list of language by using the X in the language list, and proceeded to complete that Kata.

After testing and validating my Kata, I tried to publish it. I was promptly greeted by an error stating that I may not leave the code and test fields empty - which I definitely didn't, as my fields for C# were all properly filled out.

I realized that JavaScript had not properly been removed from my list of languages. I tried doing so again, and the interface indicated that a deletion had indeed happened (there was no more X next to JavaScript in the languages list), but saving and/or reloading the Kata in the editor brought the X back, together with completely empty fields.

No matter how often I try to remove JavaScript, it keeps returning after a page reload or after trying to save the Kata. As it stands, I can not publish my Kata without writing an additional version for JavaScript, which was not my intention.

**Comment by rn542** [comment]
This has happened to me before. It is obviously a bug, but what you can do is copy everything onto a new kata, after renaming your current one. Then, you can publish that copy.
