### ISSUE TITLE
site navigation broken

### ISSUE THREAD

**Issue by yggdr** [Codewars/codewars.com#697]
There are already a few issues open relating to the site navigation, but I find it to be almost totally broken. Every second link I click doesn't work immediately. Usually I have to explicitly click on the browser URL bar and hit enter once more to actually load new content. This happens all over the place, e.g. after submitting a Kata solution and wanting to start the next one: The symbol top left starts spinning, a very thin loading bar at the very top starts filling up, then... nothing. Spinner stops, loading bar filled up, but no new content, I'm stuck on the solutions site for the old Kata. Same goes trying to navigate to the forums: Clicking on the forum loads the overview, clicking on a specific forum there starts spinning the symbol in the top left, then nothing again.
This happens all over the site and makes navigating very frustrating. I'm testing this in Firefox 50 with several JS blockers, but they are all now configured to let everything happen on the site (which was very frustrating in and of itself. Seriously, I have to allow a dozen .io sites to execute their scripts, plus their respective CDN domains?! WTF?!).
I even started a completely fresh browser (Midori) with no blocking plugin whatsoever, same result.

**Comment by bacarlino** [comment]
I'm having navigation issues on a Windows 10 machine - the problems seem similar to yours. Once I'm actually into a kata and submit it, it reports a server issue. At this point, even if I pass all the tests, it'll never let me submit the final solution as completed. I'[m not having this problem on my Linux machine (that I've noticed) or even on iOS.

**Comment by jhoffner** [comment]
@bacarlino Did you try preview.codewars.com yet?

**Comment by bacarlino** [comment]
No, I'm just now browsing through the threads and am noticing this is a known issue and there have been responses... I will continue to read the below solved threads. Thanks!

**Comment by bacarlino** [comment]
Well the navigation is working, but still getting the server error message and not able to submit final.
