### ISSUE TITLE
Invisible notifcation blocks navigation (image included)

### ISSUE THREAD

**Issue by ezekeal** [Codewars/codewars.com#698]
an invisible iframe (that holds the notifications) is blocking the upper 80% of the buttons on the bottom right
!['blocked buttons'](http://i.imgur.com/Ksrlvoz.png)

**Comment by jhoffner** [comment]
What browser/os is this?

**Comment by ezekeal** [comment]
This was on Mac / Chrome (50 something) but I just checked and it no longer seems to be an issue.
