### ISSUE TITLE
PHP tests for Twice Linear kata

### ISSUE THREAD

**Issue by chapeupreto** [Codewars/codewars.com#699]
Hello Code Warriors friends!

I think there's a problem when running PHP tests for kata named Twice linear.
When I click `Run Examples`, basic tests are all ok.
However, when I click `Run Suite`, those *same basic tests* fail.
Please take a look at the following screenshots where I use `var_dump` to print some information.
My username is chapeupreto.

Thanks for any help.

![fail](https://cloud.githubusercontent.com/assets/834048/20775683/64be190e-b743-11e6-9a66-53650edcdc31.png)
![ok](https://cloud.githubusercontent.com/assets/834048/20775684/64e633bc-b743-11e6-95af-82c476ec1183.png)

**Comment by g964** [comment]
See answer on the kata itself:
<https://www.codewars.com/kata/twice-linear/discuss>
