### ISSUE TITLE
406 On Status Site

### ISSUE THREAD

**Issue by ralphcallaway** [Codewars/codewars.com#7]
Steps to reproduce:
- Go to status.codewars.com

Result:
- 406 Not Acceptable

![screenshot 2015-03-27 15 01 38](https://cloud.githubusercontent.com/assets/841021/6876968/3ee38fba-d492-11e4-8303-e4ca24c55ea7.png)

**Comment by jhoffner** [comment]
URL forwarding seems to be flakey using our provider. I updated the url to point directly to the statuspage.io site.

**Comment by justhappens** [comment]
I keep getting this 406 error and also "submission time out" these 2 days. Thanks

PS. I tried a Kata for "quite" many times...
