### ISSUE TITLE
Can't use keyboard shortcut Ctrl+V to paste code in any of the kata

### ISSUE THREAD

**Issue by DivyanshBatham** [Codewars/codewars.com#70]
Few days back I was able to do it but right now I can't. I don't know maybe it's the web browser or any kind of changes in the website. I have checked that my 'V' key works fine and my 'Ctrl' key too because I am able to copy stuff.
And to be more specific whenever I paste something with Ctrl+V it transfers my text cursor to the end of the code.
I hope it's just a bug because it's very incontinent to paste (for an example variable name,etc.) again and again in the code.
Check the [video](https://www.dropbox.com/s/0mnqgki3wuwig35/Ctrl%2Bv.avi?dl=0) as a proof.

**Comment by bkaes** [comment]
Did you enable vim or emacs mode by chance?

**Comment by DivyanshBatham** [comment]
I think so I didn't noticed it before but now its on EMACS mode???

**Comment by DivyanshBatham** [comment]
I my also having problems with **Selected Text** + Backspace and **Selected Text** + Delete.....and was to post another issue regarding the same.

**Comment by DivyanshBatham** [comment]
Oh thanks @bkaes I figured it out....:)  But can you tell me what these mode means??

**Comment by bkaes** [comment]
Emacs and vim are two popular editors. They have they own kind of commands and control sequences, which differ from your "normal" GUI. For example, in vim you `y`ank a line and `p`ost it, you `:w`rite a file, and you `u`ndo your actions. Those commands are quite handy if you work on a terminal, especially if you don't have a mouse.

Read the Wikipedia articles on emacs, vim, ed and nano for more information about those editors.

**Comment by Darqhan** [comment]
Hello #Everyone, 
I have an issue with my East-European keyboard My language setting is Hungarian, and it was working till now. But since last week it not works, ie. ALT+b suppose to be "{", instead it jumos back 8 spaces (works like shift+tab). Did I made a wrong setup somewhere? In the browser the keys are working, only in the editor not. Thanks in advance.

**Comment by stokescomp** [comment]
I got copy and paste working by disabling emacs mode by clicking EMACS button so it isn't selected.

**Comment by xDrews** [comment]
> Did you enable vim or emacs mode by chance?

Hero!

**Comment by the-lensky** [comment]
> Я получил копирование и вставку, отключив режим emacs, нажав кнопку EMACS, чтобы он не был выбран.

YES, SCIENSE
