### ISSUE TITLE
Example of "Allow Contributors?" box controlling whether or not a kata can be approved

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#704]
There was speculation about this in https://github.com/Codewars/codewars.com/issues/316 but now I have a concrete example to pass on:

Codewars user @Gabbek was kind enough to test this for me with my kata https://www.codewars.com/kata/regex-tic-tac-toe-win-checker which had had "Beta Status:Awaiting moderator approval" status for a while, and had an unchecked "Allow Contributors?" box. Gabbek tried to approve it and got error 500. 

After that I checked "Allow Contributors?" and republished the kata, and then Gabbek was able to approve it with no problem. Then I unchecked "Allow Contributors?" and republished, no problem with that either.

So hopefully this helps you track down this bug, because there seem to be many katas stuck in beta right now due to the error 500 problem.

**Comment by tachyonlabs** [comment]
And now we tried it with my kata https://www.codewars.com/kata/resistor-color-codes as well -- once again, error 500, then checking the "Allow Contributors?" box, then approval with no error.

**Comment by jhoffner** [comment]
I've removed this flag for now until the feature can be more properly redesigned. Its causing too many issues.
