### ISSUE TITLE
Add PayPal Support for CodeWars Red

### ISSUE THREAD

**Issue by suic86** [codewars/codewars.com#706]
## Feature
Ability to pay for CodeWars Red subscription by PayPal

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1f95) by [Unito](https://www.unito.io)

**Comment by jhoffner** [comment]
Is there anyone who would signup for Red only if it supported PayPal? I was looking into this but it turns out I would have to completely redo the payment system if I wanted to support both Stripe and PayPal.

**Comment by Adobels** [comment]
I don't like to use my credit card online and I have not an Alipay account. I upvote the feature.

**Comment by claimred** [comment]
I would like paypal feature as well

**Comment by tachyonlabs** [comment]
An alternate method would be good -- today I've tried entering three different credit cards of mine plus a debit card, and Stripe has declined every one of them. :-(

**Comment by moonbrv** [comment]
Right now I'm not able to pay with any of my cards, all of them are valid and I use them every day. Not able to login to Alipay at all... Adding PayPal will be great, even if the price will be a bit bigger.

**Comment by njohnson7** [comment]
My cards won't work either.

**Comment by njohnson7** [comment]
If anyone else is still experiencing this issue, I finally found a card that works: https://www.netspend.com/

It's a pretty terrible card for everything else, but it's the only one I've tried that works for Codewars for some reason.

**Comment by kazk** [comment]
PayPal is still not supported, but you can now pay with Apple Pay and Google Pay.

---

> Regular credit card is not working for me in Europe.

I'm assuming that was because of SCA:

> Strong Customer Authentication (SCA), a rule in effect as of September 14, 2019, as part of PSD2 regulation in Europe, requires changes to how your European customers authenticate online payments. Card payments require a different user experience, namely 3D Secure, in order to meet SCA requirements. Transactions that don’t follow the new authentication guidelines may be declined by your customers’ banks.
>
> https://stripe.com/docs/strong-customer-authentication

I just updated the Stripe integration and it's now compatible. Sorry it took this long to notice.

**Comment by ffred** [comment]
> 
> 
> Is there anyone who would signup for Red only if it supported PayPal? I was looking into this but it turns out I would have to completely redo the payment system if I wanted to support both Stripe and PayPal.

Hi, don't need the options provided by Red, but was about to pay once for 6 month to support Codewars.
but don't use my credit card for automatic recurring payment and still don't pay nearly anything with my credit card outside France online.. so always use Paypal for this sort of things.
now you say that you would have to support two payment system if you add Paypal, but you could also keep just Paypal. so people could pay with Paypal, but also with their credit card on Paypal (without needing a Paypal account).

but of course I will not ask you to change all your system and go to Paypal just for me. the free Codewars is enough for me.
maybe I will find a way to support later..
thanks.

**Comment by ffred** [comment]
will try another way later, but just to let you know, I just tried to subscribe and was thinking to pay with Google Pay since you mention it, but I'm only proposed to enter a credit card number with no other option.
also tried from my phone to see if the Google Pay option could show only from an android platform, but nothing more..
![image](https://user-images.githubusercontent.com/20115501/102971168-24360e80-44f9-11eb-8ee4-bf4f35d0d9ef.png)

**Comment by kazk** [comment]
> now you say that you would have to support two payment system if you add Paypal, but you could also keep just Paypal. so people could pay with Paypal, but also with their credit card on Paypal

No, we use Stripe to process payments and manage subscriptions. It's not about supporting credit card payments. Of course, it's _possible_ to abstract billing and support both, but it will require a significant effort and it's not a priority.

For Google Pay and Apple Pay, it'll show up automatically when your environment is supported. It can depend on your browser, OS, region, etc. We don't control that condition, so I can't help you, but we have users subscribed with both.

**Comment by kazk** [comment]
If I remember correctly, for Google Pay, you need Google Chrome and you need to be signed in to an account with payment information. For Apple Pay, you need to be using Safari.

**Comment by ffred** [comment]
> No, we use Stripe to process payments and manage subscriptions. It's not about supporting credit card payments. Of course, it's _possible_ to abstract billing and support both, but it will require a significant effort and it's not a priority.
> 
I understand, no problem..

>For Google Pay and Apple Pay, it'll show up automatically when your environment is supported. It can depend on your browser, OS, region, etc. We don't control that condition, so I can't help you, but we have users subscribed with both.

well, my recent Android Phone with Google Play installed and set should work then..
will try from another computer when back at work (holidays now..).
thanks.

**Comment by VanessaGreene** [comment]
Hi all, I apologize for leaving this issue open for so long. Unfortunately, we cannot currently provide payment options through Stripe or PayPal. We will let you know if this changes. 

Currently, our Stipe (which is connected to Cdoewars Red and our merchandise) accepts payment from the following wallets: 
- Alipay
- Amazon Pay
- Apple Pay
- Google Pay
- Link
- giropay
- AfterPay/Clearpay
- Klarna 
and, of course, a debit card, which supports virtual cards through digital banking apps such as Revolut, Monzo, etc.
