### ISSUE TITLE
Can't stop following (and stop forcing me to follow people)

### ISSUE THREAD

**Issue by jklegseth** [codewars/codewars.com#709]
I sign up and because of my email I am following 359 people? Please don't force me to opt-in to users just because we share an email domain.

The only option is to remove them one at a time. Except it is not letting me do it. 

1. I click on my Following tab
2. I click on a user and on their profile click Unfollow
3. I return to my Following tab. They are still listed. If I return to their profile it shows I am not following but my profile seems to think I am (the the count of people I follow never goes down).

**Comment by jhoffner** [comment]
Did you set your clan name? You probably automatically followed people who were in your clan

**Comment by jklegseth** [comment]
@jhoffner I don't think I was prompted to select a clan?? I assumed it was done based on my email domain, as you say _automatically_. Is there a way to change my clan name? I see no option to edit it in my profile. 

My reason for opening this was a) I should not be automatically added to any group, I should opt-in, b) once opted into a clan it should be a simple matter to leave it and c) the Unfollow action does not work (maybe this is because I can't Unfollow people in my clan?). 

Minor issues, really, and this is just a suggestion. I feel it's poor UX. I have no use to follow 359 people but I would like to follow about 10 (none of them in my current clan), so the Follow feature useless for me. I've seen no other complaints here so maybe it's just me.

**Comment by jhoffner** [comment]
Yeah it looks like you set your clan to "Bloc" which has 361 users. Currently our clan feature is limited, its only real use case is to automatically "ally" people (you automatically follow each other), which acts as a clan leaderboard when viewing the list. 

Its not ideal and I hope to change it soon.

**Comment by kazk** [comment]
> a) I should not be automatically added to any group, I should opt-in, b) once opted into a clan it should be a simple matter to leave it and c) the Unfollow action does not work (maybe this is because I can't Unfollow people in my clan?)

Closing because all of these should be resolved. You can now remove previous clan members when updating the clan.
