### ISSUE TITLE
Saved Kata Translations are not accessible

### ISSUE THREAD

**Issue by Stargator** [Codewars/codewars.com#71]
I was trying to translate a Kata, because I could see the Translate button and figured I was allowed to despite not having the "New Kata" button in my dropdown.

I created a translation of the following kata in Java:
http://www.codewars.com/kata/this-is-an-other-problem

I clicked the save button after filling out sections, Solution, Solution Setup, Preloaded, Test Cases, and Example Test Cases.

Then I logged out and went back to the same URL and the data was still present.

However, the URL is not saved anywhere. So if I user did saved their work and then logged out without saving the URL, then they would have no way to reach their translation in progress.

I'd recommend a section of the profile for translations completed and those unfinished.

**Comment by jhoffner** [comment]
You should have a draft translations section within your profile.

**Comment by Stargator** [comment]
I'm at 50 Honor now, if that has any impact.

I clicked on View Profile. All I see are the following, My user details at the top, then two sections, Your Rank Progress and Honor Breakdown.

Then I see the following list in order:

Kata
    Completed
    Unfinished
    Authored

Kata Solutions
    Completed
    Unfinished
    Obsolete

Social
    Following
    Followers
    Allies

Discourse
    Conversations
    Replies
    Authored
    Needs Resolution

**Comment by jhoffner** [comment]
This should be fixed now.

**Comment by Stargator** [comment]
Verifying, the fix worked for me. Thanks.
