### ISSUE TITLE
Removing old info

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#711]
Since months and months I have in the notification area lots of:

`Well done! You have ranked up to...`

What is the way to suppress all that?

**Comment by jhoffner** [comment]
I'm actually updating the notifications system now so I can make it so that it only shows read notifications newer than a few weeks old.

**Comment by SteffenVogel79** [comment]
I have the same problem with a F#-upranking. But other uprankings are not showed all the time. Only this F#-upranking.

**Comment by SteffenVogel79** [comment]
For me, noe this old F#-upranking-information has gone.
Thanks.
