### ISSUE TITLE
Can't Publish Python 2.x or 3.x Version of a Kata

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#712]
I've created a [new Python kata](https://www.codewars.com/kata/leap-year-with-restrictions) and tried to enable both Python 3.x and 2.x in a standard way (i. e. Validate Solution and (Re-)Publish the kata). This kata is compatible with both versions of Python.

When I try to Re-Publish with Python 2.x enabled, it shows the following message:

> Default Version is not a supported version

Another example of the same issue is [this kata](https://www.codewars.com/kata/580be55ca671827cfd000043/discuss#58404e176fcbf5ec68000073). There is also another [kata](https://www.codewars.com/kata/write-number-in-expanded-form/discuss) with a fairly similar issue but without the above mentioned message.

Regards,

suic

**Comment by suic86** [comment]
It's just happened to me again. My guess is that there's some issue with the version dropdown box in the kata editor (at least for Python). I have a question regarding this: What is the default version of Python? Regards, suic

**Comment by the-zebulan** [comment]
@suic86 ,

I think the same issue just happened again for me on this kata:

https://www.codewars.com/kata/simple-beads-count/python

Python 2 is unavailable but if I click `Edit Kata` and choose `Python 2`, the tests pass just fine?

**Comment by 10XL** [comment]
@the-zebulan Try to republish with 2.7.6 selected in the dropdown. After I did this, I was able to select both versions in the trainer.

**Comment by suic86** [comment]
@10XL I've tried it and got:

> Default Version is not a supported version
