### ISSUE TITLE
Eveytime I enter in my information the page refreshes and will not let me sign up. 

### ISSUE THREAD

**Issue by hines-sharrod** [Codewars/codewars.com#713]
Eveytime I enter in my information the page refreshes and will not let me sign up/enlist.

**Comment by jhoffner** [comment]
Looking into it, out of curiosity, what happens if you go to https://www.codewars.com/dashboard?

**Comment by hines-sharrod** [comment]
Here is my result. 
![screen shot 2016-12-08 at 6 43 44 pm](https://cloud.githubusercontent.com/assets/8672599/21032282/8b4d7d10-bd76-11e6-8046-f92f5be94aaa.png)

**Comment by hines-sharrod** [comment]
this was for Javascript and I tried without linking Github and also with doing it.
