### ISSUE TITLE
ISSUE Down-votes the Kata

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#716]
## Current Status

Currently when one reports and `ISSUE` it also down-votes the kata (i. e. it sets `How satisfied are you with this kata?` to `None`).

## Issue/Rationale/Solution

This made sense in older versions of CodeWars but it doesn't make sense with the current setup as:

1. one can be `Very` satisfied with a kata which contains an `ISSUE`.
2. one can be not satisfied with a kata which doesn't have any `ISSUE`s

Solution: Separate these two things => don't down-vote a kata when `ISSUE` is created

**Comment by jhoffner** [comment]
Good catch, this will be out in the next release

**Comment by suic86** [comment]
Thanks!
