### ISSUE TITLE
Sudden loss of Preloaded Code when writing tests for draft PHP Kata

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#717]
When I was writing tests for a draft PHP Kata I was about to publish (probably about 15-30 minutes to completion), I clicked the "Validate Solution" button to check all tests were executing properly and then suddenly the following error occurred:

![screen shot 2016-12-10 at 11 01 57 pm](https://cloud.githubusercontent.com/assets/7777884/21074155/af641e2c-bf2c-11e6-88b7-d5057d9ae2f8.png)

I was stunned when I saw this error message as although I did not import/download the actual email-sending library called PHPMailer into my Kata (and in fact I couldn't and didn't intend to), right at the start when I started drafting this Kata, I wrote a class called `PHPMailer` which was supposed to behave like the actual PHP library PHPMailer **superficially** and everything was working fine until then.  I then checked the Preloaded section of my code - and to my horror, the fake `PHPMailer` class (and all of the Preloaded code I have previously written) has completely disappeared.

Now, you might say that I might have accidentally clicked on "Preloaded" when I was writing the tests and pressed Backspace after highlighting all that code (accidentally) which caused all that code to be deleted but I think that that is **not** the case **because** of one thing - when I instinctively started rewriting my Preloaded "fake" `PHPMailer` class with the PHP keywords `final class`, there was **no** syntax highlighting at all although the "Language Select" was still on PHP 7.0 which suggests that a bug indeed occurred when this event happened.  Furthermore, when I logged out and rebooted my computer and then logged in to my account again and resumed to the Editing panel of this draft Kata, the initial interface did not show up properly with weird formatting; unfortunately I was not able to replicate it.

Please help me investigate this issue.  I have lost at least half an hour's worth of work because of this sudden glitch and I would not want it to happen again.

Thank you very much,
DonaldKellett (donaldsebleung on Codewars)

**Comment by DonaldKellett** [comment]
UPDATE: This might be some sort of server error.  I seem to be able to temporarily retrieve my Preloaded Code when I re-click on "PHP" in the Language Select but then when I try to save the Kata it just keeps loading with this screen:

![screen shot 2016-12-10 at 11 16 34 pm](https://cloud.githubusercontent.com/assets/7777884/21074236/003524ca-bf2f-11e6-8624-a54698b8dc39.png)

Hopefully the issue will be solved by tomorrow morning and I sure hope I don't lose all that Preloaded code!

**Comment by DonaldKellett** [comment]
13/12/16 UPDATE: Was finally able to reproduce the "weird formatting bug" I mentioned earlier, here are some screenshots:

![screen shot 2016-12-13 at 11 28 29 am](https://cloud.githubusercontent.com/assets/7777884/21126499/916eb222-c127-11e6-882d-c8e3bcd60988.png)
![screen shot 2016-12-13 at 11 28 47 am](https://cloud.githubusercontent.com/assets/7777884/21126500/91c1c412-c127-11e6-83cd-d3921b37166d.png)

As can be seen from the second screenshot the Preloaded code just simply does not show up (as in the entire code editing area, not just it being empty) which clearly demonstrates that it is a bug.  @jhoffner please fix this ASAP as I would not like hours of hard work on this Kata to be wasted on a single bug.  Thank you very much.

**Comment by kazk** [comment]
@DonaldKellett have you experienced this recently? I'm going to close this because it's been a while, but please let me know if this is still an issue so I can reopen.
