### ISSUE TITLE
Markdown headers like ##Overview## stopped displaying correctly in kata descriptions

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#719]
In my kata descriptions I have some Markdown headers like this ##Overview## that previously displayed just fine, with the header text in a larger font and on a line by itself, but right now the headers are displaying in body text on the same line as the following paragraph, and including the hashmarks. See https://www.codewars.com/kata/fizz-buzz-cuckoo-clock as an example of how those headers have stopped displaying correctly.

**Comment by dinglemouse2250** [comment]
Ditto - I use similar markdown https://www.codewars.com/kata/airport-arrivals-slash-departures-number-2/javascript also worked fine yesterday.

**Comment by jhoffner** [comment]
I'm surprised that used to work. "## header" is the proper format. 

I deployed an updated version of the markdown parser library today which is why this must have changed.

**Comment by dinglemouse2250** [comment]
Yes.  FYI - Now it is fussy about the spaces. I've just re-published a dozen broken descriptions.

```
#Header1
##Header2
```
Used to work. But now it must be changed to:

```
# Header1
## Header2
```

**Comment by tachyonlabs** [comment]
Thanks for the correction -- I guess I had misinterpreted a markdown cheat sheet a while ago, and until yesterday the misinterpretations had worked. I went back and fixed them now. I guess I should close this if it's not actually an issue.
