### ISSUE TITLE
Kata doesnt load in PC browsers, but easily loads in Android smartphone browsers.

### ISSUE THREAD

**Issue by spands** [Codewars/codewars.com#72]
Im a new user. Nothing loads when i choose a language under "To join you must first prove your skills.
Choose your language to begin...". Tried in different machines and it did not load either.
But it works fine in my mobile browsers.

**Comment by bkaes** [comment]
Do you use the FF or Chrome addon "Disconnect.Me"? That one blocks `platform.twitter.com`, which seems to be necessary for the loading page.
