### ISSUE TITLE
CheckBox AllowContributors is missing in Kata-Editor

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#720]
CheckBox "AllowContributors" is missing in Kata-Editor

So I cannot change the value in my kata, to get this approved or to uncheck this field to prevent the kata to be changed by other people.

Please let this important field return.

**Comment by jhoffner** [comment]
I had taken it out because it was causing approval issues but what I'll do instead of put it back in but its only effective if the kata isn't ready for approval. Once it can be approved then its open for edits (so that it can be approved).

**Comment by SteffenVogel79** [comment]
I do not like the idea, that other warriors can edit other katas with the thought "I know better, what is right!".
I think the author should be the only one, who can edit his kata.
The only exception: When a user is offline for more than 6 months, i would allow to edit a kata, when there are issues!

**Comment by SteffenVogel79** [comment]
But in the time, when a kata is approvable, it is nice, when all warriors can edit it.

**Comment by jhoffner** [comment]
6 months is a pretty long time. Currently if there is an outstanding issue that is over a week old then the kata becomes open for edits. 

We do track revisions, and the author gets notified of any changes. So if someone ever edits a kata in a way that an author doesn't like, they can go to the revisions page and revert to the original. However we need to keep things moving along without too much red tape.

**Comment by SteffenVogel79** [comment]
Ok, great! Thanks for the quick help!

And again: Thanks for the good work and this great plattform. :-)
