### ISSUE TITLE
Publishing a PHP Kata keeps timing out

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#721]
As I adopted a compromise method to get around [the issue I previously filed](https://github.com/Codewars/codewars.com/issues/717) by manually selecting the PHP language every time I finish saving my Kata before I add any new code in, I was finally able to complete the test cases for my draft Kata.  However, every time I click "Publish", it keeps timing out after about 15 seconds:

![screen shot 2016-12-13 at 12 15 31 pm](https://cloud.githubusercontent.com/assets/7777884/21127525/80ef22fe-c12e-11e6-92f7-8e0a7de6c792.png)

I don't know if this issue is specific to the PHP language or me as a user (or a recent issue for every Kata authored) but it is mildly annoying how it seems that these issues are not being investigated and/or fixed lately.  It would be great if someone investigated into these problems and could give me a reply.

Thank you very much :smile:

Yours sincerely,
DonaldKellett (donaldsebleung on Codewars)

**Comment by jhoffner** [comment]
Background processing went down last night. Its back up but will take some time to work through its backlog.
