### ISSUE TITLE
Translation selected but is not showing on Kata

### ISSUE THREAD

**Issue by rollietikes** [Codewars/codewars.com#722]
I created a Typescript translation tonight to my Kata.
https://www.codewars.com/kata/help-suzuki-complete-his-chores

I published the translation then approved it but it has not appeared on the Kata and no honor was given. I've seen this behavior before on other Kata and had the issue one time before for a translation someone else did on my Kata and Jake had to fix it. 

![screenshot from 2016-12-12 21-00-11](https://cloud.githubusercontent.com/assets/7141278/21128287/84633d06-c0ae-11e6-8b46-07174486da6e.png)

![screenshot from 2016-12-12 21-06-42](https://cloud.githubusercontent.com/assets/7141278/21128334/e889c80e-c0ae-11e6-9d0a-e806508266ce.png)

**Comment by rollietikes** [comment]
As you can see Translation shows as "closed" but it does not appear on Kata.

![screenshot from 2016-12-12 21-29-29](https://cloud.githubusercontent.com/assets/7141278/21128724/17604358-c0b2-11e6-9089-e6d26824f1fc.png)

**Comment by rollietikes** [comment]
The translation is now appearing on the Kata so the issue has now been resolved.

**Comment by jhoffner** [comment]
Thanks. The background processing queue had an outage so thats why this happened.

**Comment by rollietikes** [comment]
Awesome thanks Jake.
