### ISSUE TITLE
"Stats are being refreshed" for hours

### ISSUE THREAD

**Issue by StevePaget** [Codewars/codewars.com#723]
The stats on my profile page have been "being refreshed" for hours, in both IE and Chrome, through a LAN or mobile connection. Every other user profile I visit is the same.

Also, when I complete a Kata at the moment, no honor points are being awarded.

Is this a common thing? I haven't noticed it before.
Is it broken?

**Comment by tedmiston** [comment]
I have experienced this for hours at a time too since the rollout of Red.

**Comment by jhoffner** [comment]
background processing went down. Its back up but it will take some time to work through its backed up queue
