### ISSUE TITLE
Failed to load resource https://runner-pro.codewars.io/

### ISSUE THREAD

**Issue by tedmiston** [Codewars/codewars.com#724]
I have been experiencing this issue intermittently since Red was rolled out.  (I am not a Red member.)

Sometimes when clicking _Run Examples_ or _Attempt_, my code is attempted to be executed on a server that throws this error.  Sometimes I can fix it by logging out and back in, but other times I just have to save my code and come back to the site later.  I have experienced this perhaps a dozen times with multiple problems, though I do not think it is associated with any particular problems specifically.

Another anecdote is that when it does happen, it doesn't seem to affect every problem.  I can open up new problems in other tabs and keep coding, but refreshing the page for the problems that are "stuck" on the broken server connection does not seem to save them.

I have experienced it both in the latest stable versions of Chrome and Safari.

The Codewars status page lists all servers as operational with no issues.

```
Failed to load resource: net::ERR_CONNECTION_REFUSED

https://runner-pro.codewars.io/?utm_source=codewars&utm_medium=web&utm_campaign=kata_trainer#theme=dark&congrats=true&pro=false
```

<img width="575" alt="screen shot 2016-12-13 at 11 25 05 am" src="https://cloud.githubusercontent.com/assets/366688/21148632/de3fce2a-c126-11e6-86fc-a8dd612ca5f3.png">

**Comment by tedmiston** [comment]
@jhoffner Is it fixed?

**Comment by jhoffner** [comment]
Yes

**Comment by tedmiston** [comment]
Awesome.  Thanks again.

**Comment by tedmiston** [comment]
Awesome.  Thanks again.

Just ranked up to 4 kyu this morning 😎
