### ISSUE TITLE
Failing to re-publish a kata

### ISSUE THREAD

**Issue by FA810** [Codewars/codewars.com#725]
I don't know if it's just me: I can use the platform normally and solve katas but, at the moment, it doesn't seem to be possible to re-publish one of my katas with 3 translations (already working and validating tests  with no issues) where I simply need to change the description.
I see the red progress bar extending in the browser's window's top (both in Firefox and Chrome) but always getting "Publishing Timed Out!" warning.

**Comment by jhoffner** [comment]
background process went down. Its back up but its going to be a while before it catches up on its work.
