### ISSUE TITLE
Publishing Timeouts (Again)

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#729]
As I was updating the "Task" section of each of my Kata Descriptions for all of the Kata in the PHP Kata Series I have authored, I noticed that the publishing started to timeout again:

![screen shot 2016-12-16 at 4 47 44 pm](https://cloud.githubusercontent.com/assets/7777884/21256956/4c4dc120-c3b0-11e6-85b7-fafa9f8cbb16.png)

I presumed this was because the Stats pages were being refreshed.  But when I checked my profile page, the page said nothing about when stats were being refreshed:

![screen shot 2016-12-16 at 4 55 57 pm](https://cloud.githubusercontent.com/assets/7777884/21257018/8918800e-c3b0-11e6-9bdf-0598dfabe4c9.png)

So are the background processes failing again?

**Comment by jhoffner** [comment]
Yes, looks like there were some more queue processing dropouts. The stats refresh shouldn't have anything to do with publishing (unless somehow stats refreshing is bringing down the queue processor, which I don't think is the case). 

I'll continue to monitor the servers to try to identify what happened. Closing this for now.
