### ISSUE TITLE
Tweet it! button text populates incorrectly

### ISSUE THREAD

**Issue by tedmiston** [Codewars/codewars.com#733]
I clicked the _Tweet it!_ button after ranking up.  Instead of the text field getting populated with a message, it dumps in a dict of many messages.

![screen shot 2016-12-16 at 11 54 12 am](https://cloud.githubusercontent.com/assets/366688/21289390/81b98a78-c46a-11e6-9a57-2f1dbe2be5f0.png)

**Comment by jhoffner** [comment]
This should be fixed. Thanks.

**Comment by tedmiston** [comment]
Awesome! Thanks, Jake.
