### ISSUE TITLE
Lost 481 Honor

### ISSUE THREAD

**Issue by Saka7** [Codewars/codewars.com#734]
I had 1446 honor. Today, I've noticed that I have only 965 honor left. Looks like I've lost all honor for "Beta code challenge completed". [Site Events](https://www.codewars.com/users/SAKA/site-events)

**Comment by suic86** [comment]
Hi, `site-event` matters, always :) Until you lost points on `site-events`, you don't have to worry. If you see less points elsewhere it's probably some synchronization thing and it's enough to wait some time.

Regards,

suic

**Comment by Saka7** [comment]
Yeah, everything is fine now.
