### ISSUE TITLE
Run Example Tests with the reference implementation on (Re-)Publish

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#737]
## Rationale

On pressing (Re-)Publish, the reference implementation of a kata is currently tested only with `Tests` but not against `Example Tests`. This is causing issues when one changes the tests but not the `Example Tests`.

Running `Example Tests` with the reference implementation on (Re-)Publish would prevent this. Other positive side-effect is that it would encourage people to write them. :)

**Comment by kazk** [comment]
Closing as resolved.
