### ISSUE TITLE
Sudden Boost of Honor

### ISSUE THREAD

**Issue by stripedpajamas** [Codewars/codewars.com#738]
Hello-- today I was working on CodeWars from a very slow internet connection at the library, and completed a 6kyu mission in Javascript (Kebabize). When it went through, I got about 500+ honor points. My account page now reports me having solved 500+ katas, whereas if I go to the Solutions tab, I see that I have (truthfully) only solved about 130. 

Peter

**Comment by jhoffner** [comment]
What is your username?

**Comment by stripedpajamas** [comment]
stripedpajamas

**Comment by vnvizitiu** [comment]
I encountered something similar as well, went from 18 real completed to 97 completed showing up on my dashboard

and now i have 100+ honor

**Comment by vnvizitiu** [comment]
username vnvizitiu

**Comment by jhoffner** [comment]
OK, it looks like the number of solved kata is correct, its just that your honor got boosted. This was due to a premature honor update that was pushed to production and then quickly reverted. You're points should return to normal soon (if they haven't already).

**Comment by RomanPrivalov** [comment]
Hi, have the same problem. After solving kata my kata counter in profile show me 90 completed katas, but the real number is 30. Also my honor was increased too much. Profile name: RomanPrivalov
