### ISSUE TITLE
Clicking add bookmark throws 500

### ISSUE THREAD

**Issue by tedmiston** [Codewars/codewars.com#740]
When clicking ⭐️ to add a bookmark, the servers throws a 500 error and a kata does not get added to my bookmarks.  This feature previously worked but recently stopped sometime in the past few days.  I can reproduce it on any kata I try to bookmark.  My user ID is tedmiston.

Screenshot:

![screen shot 2016-12-23 at 1 13 41 pm](https://cloud.githubusercontent.com/assets/366688/21460059/492cce34-c912-11e6-976d-1b2a5154eb35.png)

(IDs blacked out in case they are sensitive)

**Comment by greeven** [comment]
I can confirm that bug. Tested in Chrome and Firefox.
