### ISSUE TITLE
New Privileges Unlocked Without an Increase in Honor.

### ISSUE THREAD

**Issue by DHDawson** [Codewars/codewars.com#741]
Hello,

I logged on to codewars today and I had discovered that all abilities up to 3,000 honor had been unlocked while still having just over 1,000 honor. This is definitely a bug. Below is a screenshot of my notifications in codewars:
![screenshot from 2016-12-23 18-31-54](https://cloud.githubusercontent.com/assets/22350804/21460291/8acc895c-c93e-11e6-928a-77dbe4568a6a.png)

Thanks,
D.Dawson

**Comment by berkan1056** [comment]
Hi,

The same thing happened to me as well. I solved a beta kata and I instantly gained almost 600 honor points and reached somewhere in 800's. When I logged in today, the honor points that I got were removed.

Screen shot of my notifications in codewars : 

![image](https://cloud.githubusercontent.com/assets/16754287/21460493/93dc1d1a-c951-11e6-9c98-64cc7252c66b.png)

Thanks.

**Comment by DHDawson** [comment]
Hi,
That's strange - abilities were unlocked on my account - I never had a jump in horour. It is exactly the same as yesterday.

Thanks,
D. Dawson

**Comment by jhoffner** [comment]
This was due to an accidental update to the honor system, which will finally be rolled out properly this week. For now just enjoy the new privileges :)
