### ISSUE TITLE
Unable to approve kata

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#743]
I've recently (I think starting this week) attempted to approve 2 Kata to bring them out of Beta but both failed in the exact same way:

1. I see the green notice stating that I can approve it by editing the Kata and setting the rank.

![screen shot 2016-12-24 at 7 15 32 pm](https://cloud.githubusercontent.com/assets/7777884/21466669/5a52782a-ca0d-11e6-860c-1c6d03e9a579.png)

2. I go in, set the rank and click "Publish".

![screen shot 2016-12-24 at 7 16 11 pm](https://cloud.githubusercontent.com/assets/7777884/21466672/727494d8-ca0d-11e6-90f1-a5b229eeac73.png)

3. After I publish it (*once*), instead of bringing the Kata out of Beta, it returns with an error stating that I cannot estimate the rank of a Kata out of Beta and that it can no longer be edited:

![screen shot 2016-12-24 at 7 18 08 pm](https://cloud.githubusercontent.com/assets/7777884/21466679/b88624c8-ca0d-11e6-8804-58bde979f2fa.png)

4. When I leave the editing page and check the Kata again, it remains stuck in Beta:

![screen shot 2016-12-24 at 7 18 58 pm](https://cloud.githubusercontent.com/assets/7777884/21466686/d5db712c-ca0d-11e6-9541-a2217b18ec8b.png)

Initially, for the first Kata that I tried to approve this week (and failed), I thought that the error arose because another Moderator tried to approve it at the same time, which is understandable if it occurs only once.  However, now that I've tried to approve the second Kata in this week and failed in the same manner, I don't really think that's the case anymore.  Maybe something can be done to suppress the error shown above when the rank of the Kata is set by a Moderator for the first time being?

**Comment by suic86** [comment]
I've had the same issue not only with this kata. :(

**Comment by suic86** [comment]
[One more](https://www.codewars.com/kata/five-fundamental-monads/discuss/haskell) :(

**Comment by jhoffner** [comment]
This should be resolved now. I was able to approve one of the example kata.
