### ISSUE TITLE
CW red Kyu breakdown count mismatch

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#745]
Sometimes the totals of "Completed Kata" and "Completed Kata by Rank" do not match.

How can that be?

![total-mismatch](https://cloud.githubusercontent.com/assets/22114719/21474941/ffd30c3e-cb79-11e6-86a8-293a96c1f674.PNG)

**Comment by jhoffner** [comment]
Could it be that you completed some beta kata?

**Comment by dinglemouse2250** [comment]
D'oh!
