### ISSUE TITLE
Author unable to enter Kata editor. Receiving server 500 error when trying to edit existing Kata.

### ISSUE THREAD

**Issue by rollietikes** [Codewars/codewars.com#747]
Receiving server 500 error when trying to enter Kata translator for existing Kata. After trying for more than an hour I am now logging an issue. This seems to be a wide problem and I have tried to enter the Kata editor many times for the below Kata. This is a new issue and I have had many recent edits with no problems until now.

This is effecting all languages of  the Kata. I am unable to enter the Kata editor for 6 of my 11 Kata.

https://www.codewars.com/kata/584dc1b7766c2bb158000226
https://www.codewars.com/kata/57f09d0bcedb892791000255
https://www.codewars.com/kata/57dc0ffed8f92982af0000f6
https://www.codewars.com/kata/57d4ecb8164a67b97c00003c
https://www.codewars.com/kata/571c1e847beb0a8f8900153d
https://www.codewars.com/kata/57102bbfd860a3369300089c

**Comment by g964** [comment]
Same for me!-(

**Comment by suic86** [comment]
I can't edit those katas either. :(

**Comment by dpleshkov** [comment]
I couldn't mine too! :(

**Comment by jhoffner** [comment]
Fixed

**Comment by cmngDev** [comment]
The operation: #<Moped::Protocol::Command @length=58 @request_id=16026 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="admin.$cmd" @skip=0 @limit=-1 @selector={:ismaster=>1} @fields=nil> failed with error nil

Same error occurred again!
