### ISSUE TITLE
Lower kyu rank options missing when approving katas

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#748]
I have seen this with a few katas, but will use https://www.codewars.com/kata/bracket-buster as an example. I had ranked it as 7 kyu when I solved it a while back, the "Average Assessed Rank" is 6 kyu, and the "Average Power User Assessed Rank" is 7 kyu. My intention was to approve it as 7 kyu, but the only options in the Rank drop-down box are 6, 5, and 4 kyu. I tried this with both Firefox and Chrome in case some weird browser thing was going on.

**Comment by jhoffner** [comment]
This is by design now. Far too many people are ranking kata too low, so now the highest of the two rankings (power vs non power) are provided as the minimum kyu level that can be approved.

**Comment by tachyonlabs** [comment]
Oh OK, thanks for the explanation.

**Comment by g964** [comment]
Good!
