### ISSUE TITLE
Error when trying to enter kata editor.

### ISSUE THREAD

**Issue by dpleshkov** [Codewars/codewars.com#749]
I was trying to enter the kata editor from <a href='https://www.codewars.com/kata/file-path-operations/discuss'>https://www.codewars.com/kata/file-path-operations/discuss</a> and the url I go to is <a href='https://www.codewars.com/kata/file-path-operations/edit/python'>https://www.codewars.com/kata/file-path-operations/edit/python</a>. There isn't a problem when I edit my beta kata <a href='https://www.codewars.com/kata/naughty-or-nice-2'>https://www.codewars.com/kata/naughty-or-nice-2</a> though.

**Comment by jhoffner** [comment]
Fixed.
