### ISSUE TITLE
In the Trainer of kata I'm currently creating "Your Test Cases:" are coming out of nowhere?

### ISSUE THREAD

**Issue by DivyanshBatham** [Codewars/codewars.com#75]
Earlier I put them while creating the kata but after my first Preview of kata I deleted them in the kata's editor and again when I previewed my kata Those deleted "Your Test Cases:" came back. Then i tried to delete them in the Preview and returned to kata's editor and it prompt about local edits so i saved it and now in the kata's editor those "Your Test Cases:" are not there but when i preview the kata them came back in the preview mode......I'am so confused please help
If you want to get the video of what's happening then put a comment and I'll make one.

**Comment by Deantwo** [comment]
I have had the same issue with one of my Katas while trying to make sure the **Test Cases** replied corrected with "Was: <expected>, Expected: <was>".

In the Trainer Preview, did you click "Reset"?
The Trainer does seem to try to remember what was in the code boxes last time you did the Preview, which is confusing and at the very least not needed for the preview. The same thing happen when you "Train Again", which is equally annoying.
