### ISSUE TITLE
Attempt button fails and notify API returns 401

### ISSUE THREAD

**Issue by dyong0** [Codewars/codewars.com#751]
I've already sent you an email about this, and somehow I found this github page so I'm posting it here now.

The problem happens when I click **Attempt button** and an alert shows up, which says like "there's an error on the server". So I investigated how it failed, and found out that the cause was **notify** API failure. I was getting 401 when the API called.

To check this problem happens only the current problem that I was solving, I tried another problem too. Same issue again. So I thought it should be the cache or cookie holding information such as session id, then cleared them, logged in again, and tried it again. But still failed with the same problem.

I think currently you have this problem in your side. Can you fix this please? I put the picture of the issue I've got.

![screen shot 2016-12-29 at 14 09 52](https://cloud.githubusercontent.com/assets/7734590/21537176/a6486b38-cdd0-11e6-8d2f-a9888d7ac109.png)

**Comment by kazk** [comment]
Closing old issue. Please open a new issue if this problem is still there.
