### ISSUE TITLE
Profile "Streaks" "Most Consecutive Days" section doesn't seem to know about 2017 yet

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#753]
It's 3:40pm on January 1 for me here in California. This morning I did some katas, both beta and approved, but the "Streaks" "Most Consecutive Days" section of my profile still says "Ended On:Dec 31, 2016", even though my Python and Java sections both say "Last Completed:Jan 2017".

**Comment by jhoffner** [comment]
Should be fixed now

**Comment by tachyonlabs** [comment]
Oh! I just checked it again, and now it shows the correct date/number.
