### ISSUE TITLE
[Feature Request] Automatically modify minimum number of upvotes and rank assessments required to approve Beta Kata based on Average Assessed Rank

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#757]
### The "Problem"

Currently, all Beta Kata require the exact same number of minimum upvotes and rank assessments (I believe 10 each?) before they can be approved by a Moderator.  This has lead to two "problems":

1. Low-ranking Beta Kata (e.g. 7kyu/8kyu) are often approved soon after they are published, sometimes taking as little as a few hours.  Although this is not a problem in and of itself, this sometimes leads to poorly authored Kata making their way out of the Beta process simply because experienced Codewars users have not completed the Kata yet and raised relevant issues to prevent it from being approved.  For example, I have recently completed a 7kyu/8kyu Kata (I can't remember its name) that does not have any random tests in the JavaScript version.  While the Kata itself had a few language versions which probably had random tests (which lead to it being approved by a Moderator and understandably so), I felt that if the Kata had stayed in the Beta process for a bit longer, an experienced Codewars user would sooner or later have completed the JavaScript version of the Kata and raised an issue regarding the lack of random tests which would have prevented it from being approved.
2. On the other hand, the vast majority of high-ranking Beta Kata (usually around 4kyu or higher) get stuck in the Beta process for at least a few weeks (or sometimes even months or over a year) before finally being approved even if the Kata itself is very well-made and has no issues.  This is because not nearly as many users are able to successfully complete such Kata and therefore such high-ranking Beta Kata are rarely upvoted and rank-assessed by fellow Codewars users.  Even worse, if a single Codewars user raises an issue on one of these Kata at any point in the Beta process, the high-ranking Beta Kata is unlikely to ever get out of Beta because by the time someone has raised an issue on said Kata, the Kata author may already be no longer active and therefore unable to fix the issue.

The net result of this "problem" is that there is an abundance of low-level Kata (especially 7kyu katas) which may not always be well-authored, but there is a grave shortage of higher-level Kata, especially those from 2kyu upwards.  This Beta Kata approval system also discourages Codewars users capable of authoring higher-level Kata from actually authoring them instead of authoring a whole load of low-level Kata in order to gain honor quickly.

### The Proposal

To solve this problem, I propose a solution which automatically changes the minimum number of upvotes and rank assessments required of a Beta Kata for a Moderator to approve it based on its **average assessed rank**:

- For a Kata with an Average Assessed Rank of "Proficient" (i.e. 1kyu/2kyu), it only requires 4 upvotes (Very Satisfied) and 4 rank assessments to get it approved by a Moderator
- For a Kata with an Average Assessed Rank of "Competent" (i.e. 3kyu/4kyu), it only requires 7 upvotes and 7 rank assessments to get it approved by a Moderator
- For a Kata with an Average Assessed Rank of "Novice" (i.e. 5kyu/6kyu), it requires 10 upvotes and 10 rank assessments to get it approved by a Moderator
- For a Kata with an Average Assessed Rank of "Beginner" (i.e. 7kyu/8kyu), it requires at least 20 upvotes and 20 rank assessments to get it approved by a Moderator

Naturally, all Beta Kata must have no issues whatsoever before being approved by a Moderator regardless of its Average Assessed Rank.

#### The Rationale

If implemented, the proposal above takes into account the fact that low-ranking Beta Kata are completed by the vast majority of users on Codewars, most of whom are not familiar with the mode of work on Codewars and upvote Beta Kata solely on whether they enjoyed it or not without seriously assessing it technically.  This should prevent low-ranking Beta Kata of poor quality from accidentally being approved by a Moderator in its early stages.  It also takes into account the fact that only a small fraction of Codewars users have the technical capability required to complete Beta Kata of an Average Assessed Rank of Competent/Proficient so high-level Beta Kata are less likely to get stuck in Beta for a long time which in turn encourages competent programmers to author high-level Kata of substance.

#### Edge Cases - What if, for example, a Beta Kata previously with an Average Assessed Rank of "Competent" gets averagely ranked as "Novice" on its 7th Rank Assessment?

In such cases, it would be logical for the system to automatically require 10 upvotes and rank assessments as opposed to the previous 7 for said Kata to be approved instead of allowing it to be approved on the 7th upvote/rank assessment.  If then, its average assessed rank gets changed back to "Competent" before it receives 10 upvotes/rank assessments then the Beta Kata should naturally be ready for Moderator Approval again.

**Comment by jhoffner** [comment]
Wow, this was really long and well thought out! I really appreciate the effort and the format. The interesting thing though is that I already added this in about a month ago. The numbers I had came up with however were 5, 8, 10 and 12. Since this isn't something that is well understood by the community I didn't end up making a site-wide announcement about the change. 

The minimum satisfaction rating was also updated so that:
90+% is needed for white
85+% for yellow
75+% for blue
70+% for purple

I also have honor updates ready to be released soon, I just need to get to writing the blog post. There is a big shift towards earning a much larger amount of honor towards creating and completing harder kata - to further encourage people to work on harder challenges.

**Comment by DonaldKellett** [comment]
@jhoffner ,

Thanks for the compliment :smile:  It's great to know that similar changes have already been implemented for about a month or so - I had no idea!  The numbers you've just mentioned (5, 8, 10, 12 upvotes and 70%, 75%, 85%, 90% for Proficient, Competent, Novice and Beginner respectively) sound good to me - I have no intention of suggesting a different system :smile:

Well, since this system is already in place, I guess I can safely close this issue now :smile:

Cheers,
DonaldKellett (donaldsebleung on Codewars)

**Comment by g964** [comment]
Since you are changing things why not to give different kyu to a kata according to different languages? 
The reason is that a kata can be quite easy in a given language but much more difficult in another one. For example in C you have to write yourself auxiliary functions before being able to do the job whereas in another language you can use libraries functions.
Moreover kata will be approved in a language known by the one who will approve it. Now a kata is approved on a few known languages basis.
However the approving process might be longer and some kata could never been approved in some languages used at Codewars.
At last I suppose it would demand a lot of work to implement that...
PS: this process would only concern new kata.

**Comment by jhoffner** [comment]
@g964 Thats probably about the hardest thing you could think to change unfortunately. It poses all kinds of headaches both from a site design and code change perspective.

**Comment by myjinxin2015** [comment]
How to make these beta kata more appear in front of the user, this is a problem
In addition, can you add a function to the authored page: split page display or a search box?
My Kata is too much, it's not easy to find an old kata :)
