### ISSUE TITLE
New C# users unable 'prove their worthiness' to join up.

### ISSUE THREAD

**Issue by ChristianECooper** [Codewars/codewars.com#76]
I suggested a colleague drop by the site, but despite there being C# kata he was unable to sign up, as the facility to prove himself at sign up did not include his language.

**Comment by bkaes** [comment]
The [multiply kata](http://www.codewars.com/kata/multiply) is missing a C# translation, which might be the reason.

**Comment by jhoffner** [comment]
Yeah I have this on my task list to do this sprint. Beyond translating the kata the other main thing that needs to happen is C# documentation.

**Comment by jhoffner** [comment]
This is fixed. I'm in the process of deploying C# 6 support now so we will probably wait until next week before we make an official announcement - to give time to test.
