### ISSUE TITLE
Logging me out every few minutes, in the middle doing katas

### ISSUE THREAD

**Issue by iggirex** [Codewars/codewars.com#762]
I'm not sure how to reproduce this issue, it happens constantly to me. I used to not have to sign in to CodeWars everyday, but now I do. After I sign in, I get automatically signed out after a period of time, could be 10 minutes or 3 hours. It will do it when I'm actively on the site doing katas, sometimes it'll happen like 10 minutes after the last time I signed in.

**Comment by kazk** [comment]
Duplicate of #1.
