### ISSUE TITLE
Can't use Github account, please help

### ISSUE THREAD

**Issue by MirceaUngureanu** [Codewars/codewars.com#766]
I just deleted my account so I can create a new one but it doesn't let me use my GitHub on the new account because it's still bound to the old one. Can you please help me with this?
Error: The GitHub account is already associated with a different user
Old user is: user3996411
email: 586ba5962e8d9cb309000010@noreply.codewars.com

**Comment by MirceaUngureanu** [comment]
Any updates on this issue?

**Comment by jhoffner** [comment]
Give it a shot now

**Comment by MirceaUngureanu** [comment]
I still get the same error "The GitHub account is already associated with a different user"

**Comment by MirceaUngureanu** [comment]
It's not resolved, I'm still getting the same error "The GitHub account is
already associated with a different user"

**Comment by jhoffner** [comment]
Sorry about that, try again. Pretty sure I got it this time.

**Comment by MirceaUngureanu** [comment]
It's resolved, thanks for that :)
