### ISSUE TITLE
/users/:user/completed_solutions throws 500 error

### ISSUE THREAD

**Issue by DarthBergstrom** [Codewars/codewars.com#767]
A few things to check first:

Is the issue you are filing related to a specific kata?
Possibly, I noticed this after completing the kata "Merged String Checker" ( https://preview.codewars.com/kata/54c9fcad28ec4c6e680011aa ). This could simply be poor timing and unrelated. I am still able to view my solution through the kata's site -> "My Solution"; however, from that page I cannot click "refactor". 

Is the issue you are filing related to how a specific language behaves when being executed?
No.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.
My username is: DarthBergstrom, the issue can be found navigating to my profile, followed by clicking the "Solutions" tab. The my completed solutions page ( https://www.codewars.com/users/DarthBergstrom/completed_solutions ) is showing a 500 error.

I confirmed this is also happening on the preview.codewars.com site.

Appreciate your time and assistance! Love Love Love the site!!!

-Warren

**Comment by kazk** [comment]
This should be fixed
