### ISSUE TITLE
No checkmark showing I have solved my own Kata?

### ISSUE THREAD

**Issue by dinglemouse2250** [codewars/codewars.com#768]
For some reason there is no little check-mark to say that I have completed one of my own authored Katas.

I definitely have (!) and I can see my solution on the  "Solutions" page etc. Have tried re-submitting a few times but it makes no difference. This one just refuses to show the check-mark.

**Comment by dinglemouse2250** [comment]
![issue-768](https://cloud.githubusercontent.com/assets/22114719/21739023/c27eb0ae-d4e3-11e6-8149-43cedab1d740.PNG)

**Comment by kazk** [comment]
Let me know if this is still happening.
