### ISSUE TITLE
"Final solution invalid. The solution should pass the provided test cases" but solution did pass the example tests

### ISSUE THREAD

**Issue by dpleshkov** [Codewars/codewars.com#771]
I was fixing an issue on my <a href='https://www.codewars.com/kata/alien-accent'>Alien Accent</a> kata, but when I clicked the Re-Publish button, a message showed up saying my solution is invalid. I validated my solution and ran the example tests and it passed them though. Am I missing something?

**Comment by jhoffner** [comment]
Duplicate of #770. I'm working on it now.

**Comment by DonaldKellett** [comment]
#770

**Comment by brendanvos** [comment]
@dpleshkov @jhoffner @kazk Can likely be closed as duplicate #770 was stated as fixed and closed by jhoffner.

**Comment by kazk** [comment]
Closing this because this is a duplicate of #770 and it has been fixed.
