### ISSUE TITLE
No results appearing on "Run Examples"

### ISSUE THREAD

**Issue by davethehat** [Codewars/codewars.com#772]
The code appears to be executed, but no results are appearing. Tried in a couple of katas, same behaviour.

![cw-results](https://cloud.githubusercontent.com/assets/818162/21857494/8caba83c-d81d-11e6-9f6b-677fefd71489.jpg)

**Comment by jhoffner** [comment]
What os/browser? Anything reported in the web console? Which kata?

**Comment by Strandberg95** [comment]
I have the same issue. Might just be a temporary bug

**Comment by Strandberg95** [comment]
Because i did not have this problem yesterday.

**Comment by ImGuss** [comment]
Same issue with me. I tried in both Firefox and Chrome and it's giving me the same issue when running examples or attempting to submit my solution. It times out sometimes too.

**Comment by Strandberg95** [comment]
Good thing i decided to research this. Im new to the site, so was not sure if the code just did not work or if it was some sort of glitch. And I had just spent two hours writing code that worked perfectly in Eclipse haha. 
Because you know. It's not easy to trust a server-side compiler haha.

**Comment by Aaronmyster** [comment]
I'm seeing this issue as well.

**Comment by jhoffner** [comment]
Can you guys test preview.codewars.com and see if that works? If so then its caused by a change I made yesterday (that fixed this issue for someone else).

**Comment by aahill50** [comment]
@jhoffner yes preview.codewars.com seems to work correctly

**Comment by jhoffner** [comment]
nvm, its a different issue. I'm working on it. The main production cluster went down. Red users are unaffected.

**Comment by bestwebua** [comment]
I see the same issue, unable to run examples.

**Comment by jhoffner** [comment]
Should be resolved now. Turns out AWS started auto-updating the docker version on our images, and there was a change to the Docker API response that broke some of our logic.

**Comment by davethehat** [comment]
Thanks!

**Comment by bestwebua** [comment]
Thanks, works like a charm!
