### ISSUE TITLE
Collection move up/down reordering is flakey

### ISSUE THREAD

**Issue by dinglemouse2250** [codewars/codewars.com#775]
I tried the "move up" / "move down" buttons for rearranging Katas in one of my Collections but it doesn't seem usable.

* Sometimes the Kata moves as expected.
* Sometimes it does not move at all.
* Sometimes it moves in an unexpected direction.

**Comment by DonaldKellett** [comment]
I've also experienced this before in my ["Esolang Interpreters" collection](https://codewars.com/collections/esolang-interpreters) - I tried to reorder the Kata such that the "first" Kata in the Series would be at the very top, followed by the "second", and the "third" and so on but it never seemed to work.  In addition, the "Delete" feature in Collections (to remove it from the Collection not the Kata itself) also seems flakey.  Initially I added a few Kata that I did not author into the Collection mentioned above and when I recently tried to delete them from the Collection by clicking on the trash can button, it doesn't seem to work quite well - sometimes the Collection is displayed with those Kata removed and sometimes it is shown with those Kata still in there.
