### ISSUE TITLE
Problem sending requests

### ISSUE THREAD

**Issue by nkoroi** [Codewars/codewars.com#776]
First, AWESOME platform/idea/everything. CW is currently my favorite thing on the internet.

**System details**
OS - Kali linux light 64 bit.
Browsers- Chromium & Firefox
Internet Speeds:
    Ping - 19ms
    Download - 18.75mbps
    Upload - 2.98mbps

**Problems:**

- Code submission of any sort (run examples/ attempt) has a  > 2/10 probability of giving any feedback beyond "Status: Sending request...". I have tried Firefox and Chromium; none performing better than the other. Occasionally will hit bug #688  
- (not sure if this is really a bug or my mistakes) Katas that DO send and receive requests tend to be "confusing" i.e All tests are passed yet "Attempt" returns "Failed". Even for the really simple katas that i am sure to have solved.

Collectively these two problems have resulted to only one solved and accepted kata after several attempts throughout the day.

**Comment by nkoroi** [comment]
Forgot to mention, most times katas do not even load and it gets stuck on "Loading Kata:<kata name>". The problems sending requests occur after it randomly gets past this; which it manages to do less often than it does.

**Comment by mgiorgino** [comment]
Same problem here !

**System details**

OS - Archlinux 64 bits
Browsers - Chrome & Chromium & Firefox
Ping - 46 ms
Download - 12.79 Mbps
Upload - 42.56 Mbps

**Problem**

I sometimes manage to run examples/tests, but it's just impossible to attempt a kata : it is failing all day long... At least for the Haskell version.
I'm in Tunisia if this makes any difference...

**Comment by nkoroi** [comment]
The problems from yesterday seem to have all vanished. Performance is now at optimum efficiency.
