### ISSUE TITLE
highlight.js: Some C# keywords are not highlighted

### ISSUE THREAD

**Issue by SlyBeetle** [Codewars/codewars.com#779]
https://www.codewars.com/kata/reviews/5739964ef14baceffa0000c0/groups/587d19f3436f3c0f68001cba

Why?

**Comment by kazk** [comment]
Duplicate of #206.

**Comment by kazk** [comment]
Reopening this because #206 is the editor (CodeMirror) and this one is hilight.js issue.

**Comment by kazk** [comment]
Fixed by replacing with CodeMirror (#1778)
