### ISSUE TITLE
Oversensitive anti-cheating system?

### ISSUE THREAD

**Issue by adam-tokarski** [Codewars/codewars.com#78]
Hi,
I've submitted solution that is - in my opinion right and clean - but it seems that anti-cheating system mis-recognized it as "possible cheating". 
Next I've problems with submitting changed code. Then it was not submitting at all, without any message. When finally the second one showed at solutions list, it's now as without cheats flag..

Moreover, it seems that misrecognized as cheating was negative at my honor level (not to high yet anyway). Is it possible to unflag the first solution and regain missed points?

If you need to see mu solution, I can send you, but I believe, you can find it anyway.

**Comment by bkaes** [comment]
I haven't heard of direct anti-cheating responses yet. This is probably kata related, which kata did you solve, and in what language?

**Comment by adam-tokarski** [comment]
This is Polydivisible Numbers (Python): http://www.codewars.com/kata/polydivisible-numbers/python
And solution: http://www.codewars.com/kata/reviews/556237b38633bfa13e000023/groups/55641fecd87c08baf100006c

**Comment by jhoffner** [comment]
Yeah that solution definitely should not be marked as a cheating solution. I just re-ran the verify code and now it is marking it as invalid as well - so something is definitely going wrong.

**Comment by jhoffner** [comment]
Closing as we have introduced a new anti-cheating system that involves manual admin approvals of all suspected cheats.

**Comment by adam-tokarski** [comment]
Thanks! 
But according to "site events history" page, it has still negative impact to my honor points. Is it somehow cached, or you have to correct it manually?

**Comment by jhoffner** [comment]
Its fixed now
