### ISSUE TITLE
Honorboard Split Request

### ISSUE THREAD

**Issue by ericswenson15** [Codewars/codewars.com#780]
I think the leader board should be split into completed challenge people and created challenge people.
comparing those who earned points be completing challenges to those who earned points by creating challenges is not fair because of the point award difference, and the difference in skill required
I think the platform has enough challenges available to sustain this change.

**Comment by suic86** [comment]
I would suggest to have these two and one total. There are people who are great solvers and content creators too (e. g. myjinxin2015 :))

Regards,

suic

**Comment by jhoffner** [comment]
This is actually already done and ready to push out :) Its just going out with a revamp of the honor system which I still need to finish a few house keeping things on.

**Comment by ericswenson15** [comment]
Ok great thanks hoffner and I agree suic

**Comment by ericswenson15** [comment]
When were you planning on pushing out the update?

**Comment by jhoffner** [comment]
Mmmm maybe tuesday or Wednesday. Everyone's honor is going to change so I'm a little nervous and would like to find time to clone production and test on a copied db first, if I get the time.

**Comment by ericswenson15** [comment]
Changing honor makes sense in this situation. Send out an email letting people know why ahead of time.

**Comment by dinglemouse2250** [comment]
> not fair because of the point award difference, and the difference in skill required...

@ericswenson15  I can't help notice you haven't authored any Kata so perhaps your assumptions how much skill it takes to create them can be taken with a grain of salt. I agree with @suic86 - some of the CW Kata authors that I follow are the most skillful coders that I know...

**Comment by ericswenson15** [comment]
Good point I just published one, so I now know how much skill it takes, and I actually think you may be correct. The skill is similar to that of solving the problem, just backwards, and more difficult given the need for creativity. I'm no longer certain that the system should be changed, especially because those who put more effort in (the original creators) would be the most negatively affected by the change.

**Comment by ericswenson15** [comment]
@jhoffner I have faith that you'll come up with the best solution, because you have both completed and authored many solutions.

**Comment by DonaldKellett** [comment]
@ericswenson15 just remember that it takes little skill to author *any* Kata on Codewars but it takes a lot of skill to author a **good** (high-quality) Kata :wink:

**Comment by g964** [comment]
Lots of skills and lots of time!
