### ISSUE TITLE
Impossible to republish a Typescript translation

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#782]
I got lots of time:
`Example Fixture is invalid. (typescript) The example test cases should pass when ran against the complete solution`
I validated the Example Fixture and Test Cases without any problem and I change only a word in a string... I wanted to replace "scale" by "travel".
Kata: <https://www.codewars.com/kata/salesmans-travel>

**Comment by muesli4** [comment]
I don't know whether it is related but I get the same error for a C# Kata (Kumite Translation). I tried modifying some parts after accepting it. Validation succeeds but republishing fails. Could the error be independent of *Typescript*? Let me know if you need any more information.

This is the kata: https://www.codewars.com/kata/5512ec4bbe2074421d00028c

**Comment by kazk** [comment]
@g964 Let me know if you're still having this issue.
