### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by Charleygrossman** [Codewars/codewars.com#784]
Just a quick prod to see if Swift would (or could) come to Codewars. Being an iOS specific systems language, it might not be doable. But is it? I think a large membership of Codewars would enjoy it being added. Cheers!

**Comment by jhoffner** [comment]
???? It already is on Codewars :)

**Comment by DonaldKellett** [comment]
@Charleygrossman as jhoffner said Swift is already supported on Codewars and out of Beta but perhaps you haven't noticed because there aren't a lot of Kata that are currently authored/translated into Swift.  Perhaps you could try authoring a few Swift Kata of your own :smile:

**Comment by Charleygrossman** [comment]
Oh awesome!
