### ISSUE TITLE
python traceback is missing line numbers, files

### ISSUE THREAD

**Issue by eightyeighteyes** [Codewars/codewars.com#785]
The traceback display of the python katas isn't showing files or line counts, which makes debugging difficult.

This is what the traceback ends up looking like:

```
Traceback:
   in 
   in tower_builder
TypeError: can't multiply sequence by non-int of type 'float'
```

This is what it should look like:

```
def uh_oh():
    a = a

>>> uh_oh()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in uh_oh
UnboundLocalError: local variable 'a' referenced before assignment
```

To repro:
Raise any error (or cause an error to be raised) in any code block of any kata.

I don't think this is kata specific... this has been happening with every kata.

It doesn't appear to be a CSS or client side problem.  Here's the source from the element:

```
<raw content="Traceback:
   in <module>
   in interpreter
UnboundLocalError: local variable 'a' referenced before assignment">Traceback:
   in <module>
   in interpreter
UnboundLocalError: local variable 'a' referenced before assignment</module></raw>
```

But for what it's worth: OS X 11.6, Chrome 55.0.2883.95

**Comment by kazk** [comment]
Currently, file names and line numbers are intentionally removed, so it's not CSS or browser issue.

```js
// get rid of some of the noisy content. We remove line numbers since
// they don't match up to what the user sees and will only confuse them.
```

This is because Python tests are executed using concatenated file:

```python
# python -c file.py / python3 -c file.py
try: from imp import reload
except: pass
reload(__import__('sys')).path.append('./frameworks/python')
reload(__import__('sys')).path.append('/home/codewarrior')

test = Test = reload(__import__('cw-2'))

# +Preloaded

# +Solution

# +Tests
```

I haven't looked into the reasons why it's done this way, but this needs to be improved first in order to enable useful tracebacks.

**Comment by eightyeighteyes** [comment]
Thanks!  This would be a great improvement, especially for people who are just starting out, or for people working on the more complex katas.

**Comment by kazk** [comment]
[The new runner](https://github.com/Codewars/codewars.com/issues/1336) avoids concatenation so it'll show line numbers with error messages.

```python
def multiply(a, b):
    return a b
```

![image](https://user-images.githubusercontent.com/639336/37758404-52402a5a-2d6d-11e8-9f15-450e9d0f4cc7.png)

**Comment by kazk** [comment]
The new runner was deployed :) #1336
