### ISSUE TITLE
Feature Request: Ability to block certain users from commenting on an authored kata, similar to Youtube's feature.

### ISSUE THREAD

**Issue by ericswenson15** [Codewars/codewars.com#787]

**Comment by jhoffner** [comment]
The features I'm thinking for this:

- A blocked user can't comment on your authored kata
- You won't receive notifications from blocked users (if they comment somewhere else)
- There comments will be masked by default

**Comment by ericswenson15** [comment]
yeah that would be great thanks

**Comment by ericswenson15** [comment]
You are flying through these requests!

**Comment by jhoffner** [comment]
Implemented
