### ISSUE TITLE
Bad #katas shown by tag in katas search

### ISSUE THREAD

**Issue by james64** [codewars/codewars.com#79]
1 - initiate new kata search
2 - click on 8kyu filter
3 - now for example logic tag shows 4 kata inside
4 - clicking logic tag fetches only 2 katas (tag number being updated)

Correct katas count should be displayed.

**Comment by adam-tokarski** [comment]
The same when filtering:
1. Show Pythons Kata, by default all approved:
![image](https://cloud.githubusercontent.com/assets/10441317/9494610/30514964-4c07-11e5-8608-6924d6f858bf.png)

2. change status to "approved & Beta", should be more positions by tags, but:
![image](https://cloud.githubusercontent.com/assets/10441317/9494657/74b95844-4c07-11e5-9591-70a1875d4849.png)

**Comment by kazk** [comment]
Fixed
