### ISSUE TITLE
Mark katas completed by language

### ISSUE THREAD

**Issue by mmatthews1981** [codewars/codewars.com#790]
I would like to be able to sort and filter the katas in such a way that katas are shown as completed only if I have completed them in the language I've selected. 

Example: I've finished lots of javascript fundamentals, but now I would like to do C# fundamentals. Unfortunately, finishing a kata in one language seems to mark it completed in all languages, and I find this highly inconvenient.

**Comment by Bubbler-4** [comment]
Adding to this, I don't think I want a check mark (that just indicates I solved it in *some* language), but instead I want unsolved/attempted/solved/forfeited status per language. If you plan to work with coloring the language logos like #1162, the colors could be black/gray/green/red-ish respectively. If "forfeited per language" doesn't exist at all, forfeited could work with a kata-level mark (where the current check mark is shown) instead.

Where this could be applied to:

* Kata list page e.g. `https://www.codewars.com/kata/latest/my-languages`
  * At least when the language selector is not `All` or `My languages`
* Kata details page e.g. `https://www.codewars.com/kata/58bf9bd943fadb2a980000a7`
  * The language selection dropdown can be decorated, I think? There could be other ways to provide the info, e.g. remove the dropdown and put the list of language logos with the same design as Kata list page.
  * If so, it should be applied to all of Details, Solutions, Forks, Discourse
  * For Details, "Similar Kata" and "Other Kata Authored By" sections may get the same decorations used in the Kata list page.
* User's kata page e.g. `https://www.codewars.com/users/solitude/completed`
  * Same things should apply to all of Completed, Unfinished, Authored
