### ISSUE TITLE
Ability to add test cases for katas with more than 500 solutions

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#791]
I understand the reasons behind the "500 solutions" rule but I still think that at least the tests should be editable. Keeping the reference solution unchangeable will limit the possible extensions.

@jhoffner: This way I also want to ask Admins/Moderators  to fix the issue reported [here](https://www.codewars.com/kata/55cb632c1a5d7b3ad0000145/discuss#5887fbb92d99a00c9f0000a9) i.e. adding the random tests by `donaldsebleung` to the JS version.

Thanks,

suic

**Comment by suic86** [comment]
I've found some issues related to the 500-solvers rule since I've raised this issue.

#### Issue no 1.:

The criteria of quality for new katas have changed significantly (e.g. random tests are _de facto_ must have). Old katas don't meet the new criteria but they can't be updated or improved due to the 500-solvers rule. On the other hand, when one creates a new version (of an old kata) including the new requirements, the kata is considered to be a duplicate.

#### Issue no 2.

There are many old Python katas using `xrange` in their test harness. This makes them incompatible with Python3. However, they can't be updated due to this rule.

#### Issue no 3.

Some JS katas have become unsolvable due to change of the default node version to 6.6.0. These can't be fixed either.

Regards,

suic

**Comment by kazk** [comment]
@jhoffner If the goal of this rule is to prevent invalidating large number of solutions, how about limiting by the number of solutions invalidated?

---

1. Allow the author and contributors to edit regardless of the number of completions (Maybe show some warning that the edit might fail).
2. Once the change has been made, trigger the process currently used to invalidate solutions, but just keep track of invalidations and don't apply the status yet.
    1. If the number of invalidated solutions is below the limit, finalize the changes (apply the changes made to the kata and update the status of invalidated solutions).
    2. Otherwise, revert the changes and notify the user who made the change.

The idea is somewhat similar to CI build for pull requests. Also, optionally introduce a new privilege to handle inactive author/contributors.

**Comment by anter69** [comment]
I just noticed (by chance) that the 500 solutions limit is removed, but only on the preview server. Is this intended/correct? @Voileexperiments

**Comment by Voileexperiments** [comment]
Nope, it is available on the main site too since a few days ago.

**Comment by anter69** [comment]
Then I guess it could be closed, same as #1301

**Comment by anter69** [comment]
> There are many old Python katas using xrange in their test harness. This makes them incompatible with Python3. However, they can't be updated due to this rule.

You could always fix those issues with a simple `xrange = range` statement in the "preloaded" section (yes, you could use `try ... except`, but the point is the same)
