### ISSUE TITLE
[Feature Amendment Request] Alter the Kyu options available for Moderators upon Kata Approval

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#792]
@jhoffner ,

With regards to the current system of the choices of Kyu Ranks available to a Moderator for selection upon Kata approval, I would like to suggest an amendment as this new system has proven to overrate certain Kata.  Before I continue, I would like to assure you that I **completely understand** why this new system was in place in the first place (I am aware that certain Kata previously were under-ranked to some extent).  Currently, the available Kyu levels to a Moderator upon Approval are the higher of the two average assessed ranks (by normal and power users respectively) and the two Kyu levels directly "above" (i.e. harder) as far as I know, to which I would like to suggest the following amendment be made: the 3 Kyu choices should be the higher of the two average assessed ranks (same as right now) and **1 Kyu ranking above or below that**.

To support my amendment proposal, I would like to bring to your attention two Kata that I personally believe have gained too high a Kyu ranking.

The first such Kata is none other than my own Kata, [Esolang Interpreters #3 - Custom Paintf**k Interpreter](https://codewars.com/kata/esolang-interpreters-number-3-custom-paintf-star-star-k-interpreter), which currently has a ranking of **3kyu**.  While I personally am a bit happy that my Kata would receive such high a ranking (as it benefits me in terms of rank and honor gained), I, along with a number of other reputed Moderators all agree that this Kata should actually be ranked **4kyu** and not **3kyu**.  The only reason it was approved as **3kyu** was because many novice (normal) users on Codewars overrated it as **3kyu** which caused the dropdown to not allow a Kyu rating lower than that.  But if you take a look at that Kata (which I believe you did seeing as you censored the title), you will realise that it really isn't all that hard to complete it - there are a lot of 3Kyu kata that are at least 5 times more challenging than it.

The second overrated Kata I'd like to bring to your attention is a **genuine Issue**.  It's called [Keep up the hoop](https://www.codewars.com/kata/55cb632c1a5d7b3ad0000145/discuss#5888b5e8ad05f28252000060) and is currently approved as **7kyu**.  However (SPOILER ALERT!!!), the sole task in this Kata is to return the string `"Keep at it until you get it"` if the positive integer passed in is less than or equal to 10 and `"Great, now move on to tricks"` otherwise **with no error handling or other fancy requirements whatsoever**.  Clearly, such a Kata should ideally be rated 8kyu (which you hopefully also agree to) as it only requires a simple `if/else` conditional (nothing more!); yet, it was approved as 7kyu just because some inexperienced user "accidentally" gave it `1kyu` ranking which pulled the Average Assessed Rank up to `7kyu`.  *Not to mention that this approved Kata only has 3 simple fixed assertions as its entire test suite in JavaScript* (but that is another issue entirely and I will raise it tomorrow morning in my timezone as I have to go to bed :p )

Many thanks for your attention :smile:

Cheers,
DonaldKellett (donaldsebleung on Codewars)

**Comment by jhoffner** [comment]
Thanks for bringing these to attention. For now I'll change it so that the lower kyu level of the two averages (power vs normal).  Whichever of these is the smaller number will be used as the lower bounds. It would be nice to eventually factor out outliers from the avgs so that the 1kyu issues don't happen - but that will need to come later.
