### ISSUE TITLE
Blog comments won't load when linked from user profile comment section

### ISSUE THREAD

**Issue by brendanvos** [Codewars/codewars.com#799]
How to reproduce:

- Navigate to codewars blog post which has comments.
- Follow the link to the profile of a user who has commented. <sub>(As of posting I suggest navigating to the profile of the most recent commenter [here](https://www.codewars.com/blog/sneak-peak-kumite-plus-kata-translations) as the post is fairly recent and the user hasn't made many comments since)</sub>
- On the user's profile navigate to the Discourse tab and find the comment that the user made on the blog.
- Follow the link to the blog post.
- Notice that the Discuss/Comment section perpetually says "Loading comments..."

[Here](https://www.codewars.com/articles/5411f0efd436bda65b000cfc#586bb43669b6fd5ddf000113) is a url that demonstrates the issue without following the steps for reproduction.

**Comment by kazk** [comment]
Closing old issue. Blog on Codewars is no longer used.
