### ISSUE TITLE
API for Users returns wrong data

### ISSUE THREAD

**Issue by MindWanderer** [Codewars/codewars.com#8]
Note: as a shorthand, all URLs in this post are relative to *http://codewars.com/api/v1/users/* .

Today the bug that was displaying the *:username/code-challenges/completed* results in place of *:username* seemed to have been fixed.  Then jhoffner told me how to find *:username/code-challenges/completed* and it all went to hell.

I went to *MindWanderer/code-challenges/completed*.  Yay!  That worked.  Then I went back to *MindWanderer*.  Huh, that now also shows my completed challenges as well.

I played around with different usernames, as well as *:username/code-challenges/authored* and it looks like some sort of caching issue.  After an API call for a user, for several minutes, all calls for any data regarding that user return the same thing.  It's server-side caching; if I make a call on one machine at one IP address, a different machine at a different IP address returns the same data.  It seems to clear after several minutes of inactivity.

**Comment by jhoffner** [comment]
Caching issue has been deployed. Thanks.
