### ISSUE TITLE
StackTrace of exceptions shown without newlines

### ISSUE THREAD

**Issue by james64** [Codewars/codewars.com#80]
When exception is raised during test execution (possibly other usecases as well) exception, its message and stack trace are printed without standard whitespace formatting making it quite unreadable. Example:

java.lang.RuntimeException: /God.java:2: error: cannot find symbol public static Human[] create(){ ^ symbol: class Human location: class God /God.java:4: error: cannot find symbol throw new IOException("example message"); ^ symbol: class IOException location: class God /GodTest.java:7: error: cannot find symbol Human[] paradise = God.create(); ^ symbol: class Human location: class GodTest /GodTest.java:8: error: cannot find symbol assertEquals("Adam are a man", true ,paradise[0] instanceof Man); ^ symbol: class Man location: class GodTest 4 errors at codewars.runners.java$compile_and_load.doInvoke(java.clj:85) at clojure.lang.RestFn.invoke(RestFn.java:439) at codewars.runners.java$fn__572.invoke(java.clj:110) at clojure.lang.MultiFn.invoke(MultiFn.java:227) at codewars.runners$run.invoke(runners.clj:22) at codewars.core$_main$fn__634.invoke(core.clj:40) at clojure.lang.AFn.call(AFn.java:18) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.lang.Thread.run(Thread.java:745)

**Comment by kazk** [comment]
![image](https://cloud.githubusercontent.com/assets/639336/24432311/25f168b2-13d6-11e7-9f7e-a413b14d67b8.png)
