### ISSUE TITLE
"wrong number of arguments (1 for 0)" message when assessing kata rank

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#800]
![image](https://cloud.githubusercontent.com/assets/639336/22362737/be5789de-e419-11e6-9006-997091d8044d.png)

- The message "wrong number of arguments (1 for 0)" is shown when a rank is clicked.
- The same message is shown when clicked again to unselect or clicking other rank to change.
- The message goes away after about 5 seconds.
- The clicked rank does not appear selected until the page is reloaded.
- Honor does not increase for new "Beta Kata Rank Assessed". Confirmed that other new "Kata Satisfaction Vote" does.
- Confirmed this with multiple Beta katas.

**Comment by St3f4n** [comment]
Same thing for me since today... Never saw this before.

**Comment by tachyonlabs** [comment]
I just got that too.

**Comment by jhoffner** [comment]
Fixed
