### ISSUE TITLE
Return of the needing-to-reload-page-to-update-content issue

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#803]
Last night and this morning (California time) I've been seeing a return of that issue where clicking something changes the URL as it should, but the content of the page doesn't update to match until I reload the browser window. For example, clicking Submit Final when a solution has passed the test cases, or typing a search term into the search box on https://www.codewars.com/kata/my-languages and hitting return. I'm seeing this with the current versions of both Firefox and Chrome, under Windows 10.

**Comment by dpleshkov** [comment]
Have same thing too, with Mac OS Sierra, on Chrome.

**Comment by jhoffner** [comment]
Should be resolved now. Was a weird new setting that needed to be turned off on our DNS provider.
