### ISSUE TITLE
Blocked users should not be able to comment and vote katas of the blocking user

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#808]
Thanks for the feature of blocking users.

I tested it in the morning:

It is possible as blocked user to write a new comment to a kata from the user who blocked me.
(only answering is not possible at the moment)

And to prevent revenge bad votings, it should be unpossible to vote for a kata from a user that blocked me.

**Comment by jhoffner** [comment]
Hmm. Disappointing, I tested that locally and it worked. Can you block me so that I can test with you

**Comment by SteffenVogel79** [comment]
Now, it doesn't work at all. I choose the "block" button. I tried several times. Often no response. Sometimes for a few seconds "Blocking...", but then it get back to the blue "Block"-Button.
(Same on preview.codewars.com)
I also tried to disfollow you before, no change in behavior.

(Sorry for the late response.)

**Comment by SteffenVogel79** [comment]
(I could try blocking with Dentzil (colleage and cw-warrior) in appr. 10 hours, when I am at work.)

**Comment by jhoffner** [comment]
I may have prevented admins from being blocked. I can setup a new account as well and we can try that. Ill have some time tomorrow to inspect.

**Comment by SteffenVogel79** [comment]
Dentzil and I tested it right now.

As I said:
Writing a new comment to a kata from a blocked user is possible.
Answering is not possible, because the comments are from the blocking user are not visible.

Doing a kata from the blocking user is possible.
Voting for a kata from the blocking user is possible. (I think, this should also be unpossible to prevent bad revenge votings...)

**Comment by SteffenVogel79** [comment]
Hey Jake, could you inspect the blocking-feature?
