### ISSUE TITLE
Translation markup : add instructions for missing languages

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#810]
During Kata translation you can mark a section as being language-specific code.
Unfortunately, the translation instructions are missing a list of supported language tags.
Had to discover by trial and error that 'c++' is not a supported tag, but that I should use 'cpp' instead.
Please document.

**Comment by kazk** [comment]
Updated https://github.com/codewars/codewars.com/wiki/Markdown-Formatting to mention valid language tags are those found in URLs.
