### ISSUE TITLE
CW very slow and lots of 5xx server errors (15:32 GMT)

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#811]
Again, lots of server errors and slowness, making CW unworkable.
It seems that is is happening regularly lately. Please add capacity, or solve any server issues.

**Comment by brendanvos** [comment]
@nomennescio This issue is not distinct from #809. Duplicate issues do not add awareness to the issue, they simply make the handling of issues more resource intensive. 
I would recommend adding your time and commentary to #809 as a comment and closing your issue.

**Comment by nomennescio** [comment]
Closed, with the following remark. Server responsiveness is inherently bound to occurrences, which are time-bound, and cannot possibly be combined without knowing the rootcause. If CodeWars want feedback on server responsiveness and customer experience, than Github issues are maybe not the best way to track those.
