### ISSUE TITLE
Issue: Haskell Random Tests Call Solution Setup instead of Solution

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#812]
I tried to create a Haskell translation of [this kata](https://preview.codewars.com/kata/pairs-of-integers-from-0-to-n) and facing with the following issue:

The random test call the `Solution Setup instead` of `Solution`:

<img width="450" alt="screen shot 2017-02-02 at 23 50 01" src="https://cloud.githubusercontent.com/assets/11985251/22571980/7826d882-e9a2-11e6-8b03-b74617347fe3.png">

<img width="502" alt="screen shot 2017-02-02 at 23 44 58" src="https://cloud.githubusercontent.com/assets/11985251/22571937/42894638-e9a2-11e6-9d49-405095361136.png">

**Comment by jhoffner** [comment]
If the solution setup tab is active it will use that, if the solution tab is active it will use that instead. It allows you to test the setup code (useful for bug/refactoring based challenges).

**Comment by suic86** [comment]
Hi, I'm aware about that functionality. I might said it in a wrong way: The issue that the _Solution tab **is selected**_ but the _Solution Setup **is called**_ in tests instead. Regards suic
