### ISSUE TITLE
Frequent Haskell timeouts in code without loops

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#813]
The last week I've regularly encountered timeouts when running either Haskell example test, or full tests, even in "oneliners" without any loop involved. It seems running Haskell is often passing the 12 seconds mark.

**Comment by feigaoxyz** [comment]
second this.
has huge amount of timeout with simple Haskell code.

**Comment by BorisAbramkin** [comment]
Yep, same problem. Although after like 10 attempts it usually works (without changing the code).

**Comment by kazk** [comment]
Haskell timeouts were increased (https://github.com/Codewars/codewars-runner-cli/commit/d5bde1ad0c8059ecf61f8b7993f49a26eedbcf63).
Please let me know if this issue still exists.

**Comment by nomennescio** [comment]
I have this issue reoccurring. Often I have to retry 3-4 times before the outcome does not time out. In most cases the actual runtime is well below 1 second, so way below the 12 seconds timeout. I suspect it has something to do with the compilation process?
