### ISSUE TITLE
Unable to log into Codewars for the past week due to 5XX: Server Error

### ISSUE THREAD

**Issue by johnkchan** [Codewars/codewars.com#814]
Hi Codewars Team,

I have been trying to log into the Codewars website for the past week but have been faced with a consistent "5XX: Server Error". When i check the status page, it reports back saying that all systems are operational.

I have tried logging in using different computers and mobile devices but to no avail. This error seems to be related to my account as I am able to access the codewars page when I am not logged in.

Is there a workaround for this error?

**Comment by jhoffner** [comment]
Hi John, sorry to hear about the issues. What is your username? Are you using github to login?

**Comment by johnkchan** [comment]
Hi Jake,

Yes, I am logging in through GitHub. I am still unable to access codewars.

My username is "jonathan.chan"

Best Regards,
Jonathan

**Comment by omnilord** [comment]
I had a similar issue, NOT logging in with github.  When I first visited the domain (codewars.com) I got a 500 error that directed me here.  Opened the domain in a Chrome Incognito window, loaded fine.  Revisited the domain in a regular window, and now it loads, was able to login just fine after that.  Time was between 23:07 and 23:10 EST, my username is Omnilord.

**Comment by johnkchan** [comment]
I have tried logging in using Chrome's Incognito feature but still face the same 5XX: Server Error. I believe it might have to do with logging in through GitHub.

Did you log in using an account opened with Code Wars?

**Comment by jhoffner** [comment]
@johnkchan I tried reseting your oauth token. I'm not sure thats going to work but I haven't been able to reproduce any of this myself. Let me know if that helped at all.

**Comment by johnkchan** [comment]
@jhoffner I am still unable to log in. 

Screenshot of Server Error:
![capture](https://cloud.githubusercontent.com/assets/16432155/22840280/ddc08a46-ef9a-11e6-9401-bd7c434243f4.PNG)

**Comment by jhoffner** [comment]
OK. What happens if you request to reset your password?

**Comment by johnkchan** [comment]
@jhoffner After resetting my password on GitHub, I still face the same error.

**Comment by jhoffner** [comment]
No sorry I meant reset your password on Codewars. I was going to have you try logging in not via github Oauth.

**Comment by johnkchan** [comment]
@jhoffner I have performed a password reset on Codewars just now, same error page.

**Comment by jhoffner** [comment]
OK I was finally able to reproduce the issue on your account and have deployed a fix. You should be good now.

**Comment by johnkchan** [comment]
@jhoffner confirmed, thank you!
