### ISSUE TITLE
honor points problem

### ISSUE THREAD

**Issue by aryan-firouzian** [Codewars/codewars.com#818]
There is a friend of mine in Kyu 3 with 288 points. He occasionally solve some katas. After point revision, I expect to see more points for him. He told me there is no difference in his point and he was right about it.
Can you check username "rebvar", it may lead to a bug in point calculation.

**Comment by brendanvos** [comment]
His profile says "Last Seen: Nov 2016".
My points didn't seem to update until I spent some time on the site after the update.

My guess is that there is a background queue that is slowly processing the updated honor calculations for existing users, but users that are active are triggering the calculation when they perform an action that would earn them more honor.

**Comment by aryan-firouzian** [comment]
Oh. thanks for pointing out. I will ask him to be active for some days.
