### ISSUE TITLE
Sudden inexplicable increase in honor, again

### ISSUE THREAD

**Issue by matthewmoppett** [Codewars/codewars.com#819]
My honor points (user name: matthewmoppett) have gone up from around 530 to 2384 for no reason. This issue has been reported before, fixed, and closed: [https://github.com/Codewars/codewars.com/issues/739], but it has reoccurred.

**Comment by suic86** [comment]
Hi, read [this](https://medium.com/@Codewars/honor-and-leaderboard-updates-a1491f2cb2e2#.yuiy5aoqm).

Regards,

suic

**Comment by matthewmoppett** [comment]
Oh, cool. Thanks.
