### ISSUE TITLE
Java Imports

### ISSUE THREAD

**Issue by RainbowZephyr** [Codewars/codewars.com#82]
Java imports are not handled correctly and the tests crash most of the time, stating unknown symbol even though the code runs on eclipse

**Comment by ChristianECooper** [comment]
What are you trying to import?

**Comment by RainbowZephyr** [comment]
java libraries particularly JUnit libraries

**Comment by jhoffner** [comment]
Can I get more details on this? An example solution & fixture combo that does not work would be very helpful.

**Comment by kazk** [comment]
Closing this because it's been more than 1.5 years and no feedback has been provided.
