### ISSUE TITLE
[Proposal][RFC] Test.randomTests and Test.randomArgumentsOf

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#822]
## Background

> random tests have become de facto standard for any new kata and missing random tests are often reported as an issues. On the other hand, CW doesn't offer any tooling for random input creation.
> #781

This proposal might be more appropriate on [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli), but I'm posting here because I don't think many kata authors will see it there. Currently only in JavaScript.

## Goal

Make random tests easy for authors and provide useful feedbacks for solvers.

```javascript
// Example kata to capitalize the input
const ALPHABET  = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
const generator = randomArgumentsOf(['string', {pool: ALPHABET, length: 4}]);
const solution  = s => s[0].toUpperCase() + s.slice(1);
const reference = s => s[0].toUpperCase() + s.slice(1).toLowerCase();
const tests     = 10;
randomTests(generator, solution, reference, tests);
```

![image](https://cloud.githubusercontent.com/assets/639336/22812823/d9cbdd36-eefb-11e6-8b0a-1e51e84eddd7.png)

## Known Problems

The table gets crowded for multiple arguments, especially if it includes arrays or objects.

### randomTests

```javascript
const isEqual = require('lodash').isEqual; // Test.assertDeepEquals
const inspect = require('util').inspect;

function randomTests(generator, solution, reference, tests = 100) {
  const failures = [];
  for (let i = 0; i < tests; ++i) {
    const values = generator(); // random arguments as array
    // stringify input here because user solution might modify its content
    const input = values.map(v => inspect(v)).join(', ');
    // do reference first to protect against user solution modifying the input
    const expected = reference.apply(this, values);
    const actual = solution.apply(this, values);
    if (!isEqual(actual, expected)) {
      failures.push({Input: input, Expected: inspect(expected), Actual: inspect(actual)});
    }
  }
  const failed = failures.length;
  if (failed == 0) {
    Test.expect(true);
  } else {
    Test.expect(false, `Failed ${failed} of ${tests} random tests`);
    console.log(`<LOG:TABLE:Failed Test Cases>${JSON.stringify(failures)}`);
  }
}
```

### randomArgumentsOf

Utility function to help kata author with writing `generator` used in `randomTests`.
Uses [chance](http://chancejs.com) which is already available (thanks to [this comment](https://github.com/Codewars/codewars.com/issues/781#issuecomment-275435800)).

```javascript
const chance = new require('chance')();
function randomArgumentsOf(...args) {
  const gs = args.map(a => (typeof a == 'string') ? chance[a].bind(chance) : () => chance[a[0]].call(chance, a[1]));
  return () => gs.map(g => g());
}

const gen = randomArgumentsOf('word', ['string', {length: 3}], 'date', ['bool', {likelihood: 20}]);
console.log(gen()); //=> ['tiz', '4UD', 2045-03-03T17:55:53.216Z, true]
console.log(gen()); //=> ['lucof', 'uVU', 2101-07-19T14:54:38.047Z, true]
console.log(gen()); //=> ['zugemfa', '@ny', 2103-01-27T13:25:50.851Z,  false]
```

**Comment by DonaldKellett** [comment]
Sounds awesome to me, if implemented this would make life much easier for both novice Kata authors and us Moderators :smile:  And I'm still perplexed as to how you created that screenshot (of failing random tests) for the proposal.  If this actually gets implemented I would be more than happy to contribute to the new documentation that comes with it :smile:

**Comment by kazk** [comment]
@DonaldKellett that screenshot is actual output in kumite.

**Comment by kazk** [comment]
@DonaldKellett I modified the code snippet a little so you can paste in kumite and run. Just make sure to  place the example at the end. Thanks for your feedback :)

**Comment by Voileexperiments** [comment]
Bump ;-)

**Comment by kazk** [comment]
I had completely forgotten about this. I'm going to work on improving JS soon so I'll come back to this.

**Comment by kazk** [comment]
Closing because we're not going to add anything to the custom test framework.

[fast-check](https://github.com/dubzzz/fast-check) will be available for Node.js 10.
