### ISSUE TITLE
Server Error - undefined method 'revised_by'

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#823]
Status page https://codewars.statuspage.io/ says all systems operations

But I get server error.

**Comment by jhoffner** [comment]
Please provide repro steps. Is a certain page causing this error?

**Comment by dinglemouse2250** [comment]
PSA.

![issue-823](https://cloud.githubusercontent.com/assets/22114719/22844791/ec798f9e-f033-11e6-8289-197ac4ef78ff.PNG)

**Comment by dinglemouse2250** [comment]
Happened same instant I did a submit final for https://www.codewars.com/kata/color-choice

Until then all was fine.

Dunno if just coincidence / bad luck.

**Comment by jhoffner** [comment]
A fix is being deployed right now
