### ISSUE TITLE
Upgrade Elixir to latest version

### ISSUE THREAD

**Issue by unclesnottie** [Codewars/codewars.com#827]
Codewars needs to support Elixir 1.4.x.  Codewars is a great tool for learning a new language but isn't useful when the version of the language is very outdated.

**Comment by rockneurotiko** [comment]
Please, Elixir 1.2 have more than a year.

**Comment by kazk** [comment]
I think this issue needs to be moved to [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli).

I just skimmed through changelogs for 1.3 and 1.4 and it seems like there're many deprecations that emits warnings. Upgrading is easy, but I'm not sure how this will affect existing contents.

- <https://github.com/elixir-lang/elixir/blob/v1.3/CHANGELOG.md>
- <https://github.com/elixir-lang/elixir/blob/v1.4/CHANGELOG.md>

**Comment by kazk** [comment]
See https://github.com/Codewars/codewars-runner-cli/issues/291
