### ISSUE TITLE
Why experience points for translations go to kata author, not to translator?

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#83]
Hi. I have noticed that I have 55% towards 7 kyu in Ruby, while, as far as I remember, I never solved anything in this language.

I think this is due to the fact that once my kata with a Ruby translation made by someone else is approved, I get the 'experience points' for that, not the author of translation.

Also, the translated solution in this case is also published under my name, which I think is wrong, because it was written by someone else and that contributor has no credit for the solution.

I really think this is wrong, because it misrepresents my abilities and abilities of contributors.

**Comment by jhoffner** [comment]
I actually just discovered this myself yesterday and quickly deployed a fix. The issue seemed to be that if you fork a translation in order to improve/correct/merge content, then the credit was being given to the fork being approved, and not the original translation author. 

However it doesn't look like you have actually forked a ruby translation before, so there must be another issue here that I will need to look into ASAP.

**Comment by MMMAAANNN** [comment]
Jake, I did not fork any Ruby translations indeed, my knowledge of Ruby is poor.

I wrote a few katas and Giacomo (and others) helped translating them into other languages. Particularly, Giacomo translated some of them to Ruby. After approval of a couple of katas, I have 55% of progress towards 7 kyu in Ruby, which I should not have (in my opinion).

Also, as you may know, when someone contributes a translation, the translated solution is posted under kata author's name, and not the translator's name.

I'm glad you react so promptly and I hope it all gets fixed all right!

**Comment by MMMAAANNN** [comment]
Yay, now at least in part it works as I expected!

I translated a kata into CoffeeScript and the translated solution is published under my name, not author's!
http://www.codewars.com/kata/whens-my-birthday/solutions/coffeescript

Thanks!

I guess it is not possible to revert this for all previous wrongly attributed publications? I translated several katas into Python, one of them 2 kyu, and my solution there is still under author's name, not mine:
http://www.codewars.com/kata/reviews/554ceecb085cd8072800009e/groups/554ceede085cd807280000ad

**Comment by jhoffner** [comment]
Yeah I was able to push out a fix yesterday for that, but I also want to try to write a migration script that will fix previously approved translations. That is going to be tricky business, one small bug in the script and things could get worse, so I am not going to rush that fix out the door.

**Comment by MMMAAANNN** [comment]
Thank you very much!

**Comment by Deantwo** [comment]
This would explain why I have progress in Python, I did a fork on a translation.

Think you could fix that for me? [Deantwo](http://www.codewars.com/users/Deantwo)
