### ISSUE TITLE
Re-publish C kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#832]
1) When re-publishing a C kata the "Example Tests:" part is NOT re-published with the modifications. This part is kept as it was *before* the modifications.

2) When running only the "Example Tests:" ALL "Test Cases" are run so it is impossible to validate separately "Example Tests:"  and  "Test Cases"

kata: <https://www.codewars.com/kata/55e2adece53b4cdcb900006c/edit/c>

**Comment by g964** [comment]
1) Fixed: updated hours later.

**Comment by kazk** [comment]
Closing because 2 is duplicate of #103
