### ISSUE TITLE
Kata Info Scrolling Up When I Type in the Code Area

### ISSUE THREAD

**Issue by dpleshkov** [Codewars/codewars.com#834]
When I am making a translation on a kata, and I scroll down on the left bar(the one that shows description, example tests, tests, user's solution, etc.) and then I type in the code area on the right, the left bar scrolls all the way up. This is really frustrating.

**Comment by kazk** [comment]
Duplicate of #353?

**Comment by kazk** [comment]
Duplicate of #353.
