### ISSUE TITLE
Make kata progress drop-down configurable

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#836]
*Progress* drop-down on Kata search page allows choice of
* All 
* Kata I have not trained on
* Kata I have not completed
* Kata I have completed

---

I wish that the default item for this drop-down was configurable in *Account Settings* because currently I am changing it every single time to avoid seeing Kata I have already completed.

**Comment by kazk** [comment]
Closing this because this is a subset of #1578. Please follow that issue instead.
