### ISSUE TITLE
solved, unsubmitted kata, after refresh the code disappiered, looks completed on profile

### ISSUE THREAD

**Issue by skully** [Codewars/codewars.com#839]
Scenario:
I solved a kata, but did not submitted my code yet, because I was on the way of refactoring. I accidentally pressed the refresh button. My whole code disappeared and returned to the beginning state, but the kata was under the completed katas in my profile, but I can't see my solution or others solution (at least my solution would be great to see again), it behaves uncompleted (which is ok, because it's not submitted yet).

**Comment by error256** [comment]
Your code should be on the Past Solutions tab of the training page. Isn't it there?

**Comment by skully** [comment]
Oh, ok, I can see mine somehow now on completed...sorry for your inconvenience...
