### ISSUE TITLE
Something strange with timeouts, may be for a particular kata...

### ISSUE THREAD

**Issue by ChristianECooper** [Codewars/codewars.com#84]
I was working on the "Java Kata First non zero number in N!" as seen here: 
http://www.codewars.com/kata/555f86296aced17d90000035/train/python

First strange thing I notices is that the URL thinks I'm training in Python...

Second strange thing - I'm getting a _whole 6ms_ of run time before getting this message:

```
test(SolutionTest)
n: 50, 0ms
f: 2, 0ms
f: 3, 0ms
...
...
f: 43, 6ms
f: 44, 6ms

Process was terminated. It took longer than 10000ms to complete 
```

The second number you are seeing is the number of elapse milliseconds since entering the method!

**Comment by jhoffner** [comment]
I think this issue is caused by a combination of a slow running machine (noisy neighbors) combined with compile and run time being both counted towards the 10s timeout. This issue has certainly not been perfected but improvements have been made which should alleviate the issue.
