### ISSUE TITLE
Kata Editor : annoying jumps

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#840]
Especially when translating a Kata, the online editor has annoying behaviour.

If you scroll either the Kata or Description tab ("left part of window") downwards to see e.g. the test cases to translate, and then type into either the upper or lower tabs (solution, setup, preloaded, test cases, example test cases tabs) ("right part of window"), the left part immediately scrolls/jumps back to the beginning of the Kata or Description.

This makes translating more time-consuming than necessary, due to the constant need of repositioning the left part to the correct lines.

Please consider changing this resetting of the scrolling behaviour.

**Comment by jhoffner** [comment]
Same as #834
