### ISSUE TITLE
Translation should count towards your language ranking

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#841]
After doing several "higher" level Katas for C, I noticed that -- although a translation requires a solution in the new language -- creating the implementation in C did NOT count towards my C proficiency.
I can understand you will not get full points, because you have already solved the Kata for another language, but should it not add to your "experience"/Kyu level of that language?

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1fda) by [Unito](https://www.unito.io)

**Comment by g964** [comment]
Agreed. I translated lots of katas into C, C++, Swift and many others but, for example my Swift proficiency is still null... Things here are sometimes mysterious:-)

**Comment by nomennescio** [comment]
Found another instance of this: when my level 2 Kyu Haskell translations were approved, my Haskell proficiency just stuck at level 5, without any progress.

**Comment by nomennescio** [comment]
Although this was labeled a high priority bug, this is still open 3 years later...

**Comment by kazk** [comment]
Fixed
