### ISSUE TITLE
train api endpoint returns a 500 error

### ISSUE THREAD

**Issue by beemyfriend** [Codewars/codewars.com#846]
the api call: `https://www.codewars.com/api/v1/code-challenges/javascript/train?access_key=:my_api_key` returns a 500 error claiming that there are "No route matches api/v1/code-challenges/javascript/train".

The documentation says that 500 errors are internal server errors. Is the api server under maintenance, am I not calling the api endpoint correctly, or is there something else going on?

![screenshot 4](https://cloud.githubusercontent.com/assets/17094367/23517022/ce13b8e4-ff4d-11e6-85f1-4dea985c6dac.png)

**Comment by jhoffner** [comment]
This endpoint is no longer supported since the architecture changed. At the moment there isn't a way to submit kata through our API.

**Comment by beemyfriend** [comment]
Ok, thanks!

**Comment by kazk** [comment]
Closing this because documentation has been updated.
