### ISSUE TITLE
Not getting notifications if you are just a contributor of a kata

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#85]
I have been discussing this for a time with others of the most active users and I think we could boost a lot the quality of the CW experience if we built a system that allowed users to directly contact the author/translator of a given version of the kata to report bugs, suggest improvements or (why not) request clarifications.

Currently this is not directly possible (I either find some issue re-checking an old kata or get contacted via mail, hangout or twitter by the author himself), but I think an improvement in that way shouldn't take too many resources and would help in making us all feel more like an unique community.

A bug reporter could also get some small reward (like 1pt of honour if there was an actual bug, which seems fine as we get 2pts for just doing a beta kata) and, to prevent abuse, you could limit the number of times an user can ask for help on a specific kata by something like 1+1/100pts. Users like bkaes, jolaf or ChristianECooper (just to name the very first few that come to my mind) provided me and other authors with tons of useful tips and suggestions, so they surely did something good for CW.

Conversely you could also think of rewarding an author/contributor which actively checks and fixes his/her kata, but this could be a bit more debatable (if I did all perfectly working from the beginning, I get no reward, but that could be checked and thus rewarded too).

**Comment by bkaes** [comment]
Are you sure the issue's title matches its contents? Either way, I think a "Watch" option similarly to the github function would be great, a way to manually (un-)subscribe to a discussion.

**Comment by GiacomoSorbi** [comment]
Mh, it seems to me the title addresses the main part of it, yeah: do you feel it ambigous? And how much is this "while"? Because I didn't get notification after a few days I did a translation and posted about it.

**Comment by bkaes** [comment]
> And how much is this "while"? 

Well, in this particular case I'm talking about the manual (un-)subscribe method, something that isn't implemented at all. Also, I think that directly contacting a contributor might lead to a dead end. It's still a good way to get things done, but a more general flag system might make things even better. That way, you could flag a kata for author/translator/moderator attention. I think my feature request about that is still visible in the FR forum, but I'm not completely sure.

Other than that, I like your overall approach, reminds me of StackOverflow's review queues and edit reputation.

**Comment by jhoffner** [comment]
Kata authors are always sent email notifications about new discussions within their kata, unless they have notifications completely turned off. Currently, translators do not get these by default. We have an auto-unsubscribe system that stops sending you notifications on a thread you were active on after 3 days of inactivity.

I think ideally `@GiacomoSorbi` style user links could be used to trigger a notification to a specific user.

**Comment by GiacomoSorbi** [comment]
My initial idea was more on the spirit of bkaes-senpai comment, but I know it would be a bit more complex to implement: ideally when user X has an issue on kata Y, he/she could submit a comment and that comment is pushed to everyone which is interested (author, translators and other contributors): I click there, see if anyone has already flagged that he/she is taking care of it and, if not and if it something I can do, I flag it and try to fix it. If I cannot fix it, I can deflag it and the ball is put on the centre of the field again.

To make things even smoother, a power-user could be allowed to edit even approved kata he didn't contribute to (which is now is still returning a 500 error, if I am not wrong) and to browse a list of current issues, sortable/filtered by both language and solved/all categories.

The flag goes away when either X or at least two among author and contributors agree that it is solved; power-users (again: possibly with a small reward) or admin could only have to check for very old or disputed (X and a sole contributor disagree on it being solved) flags.

This would help solve (or at least greatly reduce) the problem that we are facing as we are growing bigger and bigger (which, *per se*, is surely good): right now, on a side there are lots of kata which could be fixed with very small fatigue (and we surely have a good number codewarriors willing and able to do a thorough job about it); on the other, there are lots of very old issues still open even if they are apparently solved, possibly because the original user is no longer active or simply didn't bother checking the issue as solved.

Final note of this long rant: implementing a more complex rewarding system, possibly with more gamification and differentiation in terms of achievements, would surely follow CW spirit of giving coders a training ground to improve and show their skills.

I see a small part of my points comes from an obscure "achievements" section, not sure about it, but I think it would be cool to differentiate a bit more and get badges (or even, better yet, weapons, scrolls or anything more in line with the feudal Japan theme) for specific tasks. I.e.: a guy solving 500 problems is good as he is one fixing 100 katas, but they could have different skills/mindsets/attitudes and it could prove of interest to both fellow codewarriors and external head hunters to be able to differentiate them at a glance.

Just my 0.02€ and I am really enjoying what CW is currently offering me and I can't stop encouraging others to come here and give it a shot; it is just that while I may be a rather poor coder, I should have grown some more aptitude to see things more from a marketing/user experience point of view. And there you always have room for further improvement.

**Comment by jhoffner** [comment]
OK I'm finally getting to this. I'm making it so that if the author hasn't been active within 3 days then all coauthors (including translators) + the author get the notification. Hopefully this doesn't become too annoying for some power users.

**Comment by jhoffner** [comment]
Hmm, I'm also going to only notify coauthors/translators when a new issue is added, not any comment (to reduce noise)
