### ISSUE TITLE
Unable to translate a kata: server error

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#851]
I had already published about that but I don't see anymore my post ... so I re-post:-(
Kata: <https://www.codewars.com/kata/56baeae7022c16dd7400086e/translation/new> ("Phone Directory")

Each time I get:
```
Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.
```

**Comment by javatlacati** [comment]
The worst part of this... I can add translations with your link even if I havent passed the kata. Does this diserves it's own bug report?

**Comment by kazk** [comment]
Possibly related #1268

**Comment by kazk** [comment]
@g964 can you open this page now?

**Comment by javatlacati** [comment]
I still can open the translation page even if I haven't passed the Kata yet

**Comment by kazk** [comment]
Closing as original issue should be resolved.

@javatlacati that will be #860.
