### ISSUE TITLE
Editing Kata permission: allow for translation approvals

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#855]
I do have enough honor to be able to edit any (?) Kata, and can basically modify all languages, HOWEVER, it is not possible for me to approve pending translations.

Allowing this would also solve other issues already posted about the inability to get translations approved for 'abandoned' Katas.

Alternatively, introduce a separate permission, coupled to honor, that does allow the approval of translation for Katas for which you're not the owner.

**Comment by DonaldKellett** [comment]
I agree with your suggestion; IMHO Moderators (users with 6000+ Honor) should be able to approve Kata translations as well as actual Kata.

**Comment by kazk** [comment]
https://github.com/Codewars/codewars.com/issues/1065
