### ISSUE TITLE
cannot publish

### ISSUE THREAD

**Issue by darrenburgess** [Codewars/codewars.com#856]
having problems publishing my first kata. It passes all validation. When I try to publish, the page eventually returns a server time out error. Or, the yinyang spinner spins indefinitely. The js browser console returns:
```
Subscribed to defer_response
defer response received: 
{success: false, dmid: "kMisvstA", deferred: true}
```
This is the same result returned in chrome, safari, firefox.  account = darrentburgess
kata: https://www.codewars.com/kata/58c331628b4f2e60890001ae/train/javascript

**Comment by macobo** [comment]
One extra tidbit of info that might be useful for the developers:

On the kata publishing page, open the developer console, go under network tab, hit publish and see what requests are done and what status code and body the server returned.

**Comment by darrenburgess** [comment]
here are the requests from the network 
![cursor_and_rail_fence_cipher__encoding_and_decoding_-_kata_creator___codewars_and_inbox_ _personal__238_messages_](https://cloud.githubusercontent.com/assets/7114602/23827161/13318846-067b-11e7-87c2-09c09aef35f3.jpg)

**Comment by RLOG89** [comment]
Having a similar issue.  Mine always hangs indefinitely on the "Please wait while we publish" yin-yang page.  I've tried multiple times over the last 3 or 4 days with no success.

Here is my network tab (this will keep going if I leave it)
<a href="http://tinypic.com?ref=2vsj52s" target="_blank"><img src="http://i64.tinypic.com/2vsj52s.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by darrenburgess** [comment]
@RLOG89   Glad to see I am not the only one.

I think that the console message is super meaningful.  
```
Subscribed to defer_response
defer response received: 
{success: false, dmid: "kMisvstA", deferred: true}
```
seems to indicate that the requests are being queued up and are never processed.  I tried recreating my kata as a new record, but got the same error.

I wonder if it is my user account, and perhaps yours as well, that is somehow blocked from submitting new kata?

**Comment by RLOG89** [comment]
@darrenburgess 
This seems likely as I'm sure others would have raised an issue if they'd been struggling to post a kata over the last few days.  Hopefully someone can clear this up for us.

**Comment by jhoffner** [comment]
@RLOG89 and @darrenburgess are you still having issues? I've published a number of kata today without any issues.

**Comment by darrenburgess** [comment]
No, it is still providing the same message in the console. @jhoffner 

FWIW, getting a javascript error now:
![publishing_error_jpg_and_microsoft_word](https://cloud.githubusercontent.com/assets/7114602/23919917/121919dc-08cf-11e7-83e5-e10cf967fafb.jpg)

**Comment by RLOG89** [comment]
No change for me, still not working.

**Comment by jhoffner** [comment]
Try refreshing and see if it actually changed. Based off of that error it would seem that websockets are not working for you.

**Comment by darrenburgess** [comment]
Thank you @jhoffner.  No, refreshing has no effect.  Note that I have attempted this in different browsers all on mac OS 10.11.6.  Going to try from a windows machine. Are you saying this may be an local environment problem?

**Comment by darrenburgess** [comment]
@jhoffner  I get the same error on a windows machine.

**Comment by darrenburgess** [comment]
@joffner.  Also note that I attempted to recreate the kata in another record. Issue persisted in the new record as well.

**Comment by jhoffner** [comment]
I deployed a fix to preview.codewars.com and verified. www is being deployed now.

**Comment by darrenburgess** [comment]
Thank you!
