### ISSUE TITLE
kata listing in /search

### ISSUE THREAD

**Issue by FA810** [Codewars/codewars.com#859]
I wish this won't upset anyone but we have an issue here:

https://www.codewars.com/kata/search/

the katas shown now at the top are always of two types:
- brand new ones in beta, 10 people solving them for beta points if they got no issues, then the oblivion;
- approved ones with new translations;

this leaves out katas still in beta with new translations; this is unfair in my opinion because it doesn't promote making new translations of old katas and you find always the ones from the same authors who can easily get them approved.

I've translated a kata in beta in javascript and it doesn't show up as first in any criteria ("newest", "recently published", ...). Why even bothering translating? All this while top users can approve each others' katas and get them always shown first; see "Gap in primes" for example: 2128 solutions, 16 languages and yet always first page, and always the same few authors with old katas, therefore I don't get why they are shown under "Newest".

**Comment by jhoffner** [comment]
I just verified by approving some beta translations for 1 kata and it appears at the top of the list.

<img width="808" alt="kata___codewars" src="https://cloud.githubusercontent.com/assets/579835/23957161/edab3fac-095b-11e7-951a-dbc79d327d99.png">

**Comment by FA810** [comment]
well, I think it's because you're an admin.
But tell me: why I can't see my own kata just translated while I see "Gap in primes" who got a change in description today and previous change in code more than a month ago?
https://www.codewars.com/kata/gap-in-primes/revisions

**Comment by jhoffner** [comment]
There definitely isn't some kind of sorting that singles out admins or approved kata, the most recently used published date is used as the only sort field. There may be some kind of issue where its not consistently being set when translations are approved perhaps.

What was the kata you translated?

**Comment by FA810** [comment]
this one:
https://www.codewars.com/kata/tombola-validation/revisions
not appearing when I filter "My languages", all katas, approved and beta, all status trained/untrained.

**Comment by FA810** [comment]
Moreover I have to point out that if one chooses "Approved and beta" and "Newest", it results in all the approved first, old ones.

**Comment by jhoffner** [comment]
OK it looks like there is an issue with your kata not getting its published date updated. This isn't a beta vs approved issue, its a kata specific one that I'm now looking into. 

> Moreover I have to point out that if one chooses "Approved and beta" and "Newest", it results in all the approved first, old ones.

<img width="443" alt="kata___codewars" src="https://cloud.githubusercontent.com/assets/579835/23960326/e8ebb8da-0964-11e7-8e84-56bc90d604b0.png">

You don't see this? I see a mix of beta and approved.

**Comment by FA810** [comment]
I tried again. The approved and beta seems to be happening when I click the kata icon on the left bar, my default criteria are [sort by:newest], [language:my languages], [status:approved and beta] and [progress:all], this is when I get no beta.

**Comment by jhoffner** [comment]
Turns out adding new languages directly to kata were not updating the published date that was being sorted on. I've fixed this and it will go out in the next deployment.

**Comment by FA810** [comment]
the kumite translation wasn't working (sometimes it fails to load the page); that's the reason why I've added it directly from the "Edit kata" link. I think I didn't get points for this, while I probably would with a new kumite (I'm not sure).
