### ISSUE TITLE
"Broken Greetings" deleted?

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#863]
@jhoffner your "Broken Greetings" kata completed by many is returning server error with some message I've never seen before.
I came across this in the description of a kata. If this kata was deleted for some reason please let me know so I can suggest the author to update the description.
I'm assuming this is an error because I've seen kata retired, but not deleted (except for early beta ones).

### Screenshots

<https://www.codewars.com/kata/broken-greetings>
![image](https://cloud.githubusercontent.com/assets/639336/24112243/251a8738-0d56-11e7-8039-128ef0e9f165.png)

<https://www.codewars.com/kata/50654ddff44f800200000001>
![image](https://cloud.githubusercontent.com/assets/639336/24112265/3bb499f2-0d56-11e7-900d-09f885a0f0a8.png)

[site:codewars.com intitle:"broken greetings"](https://www.google.com/search?q=site:codewars.com%20intitle:%22broken%20greetings%22)
![image](https://cloud.githubusercontent.com/assets/639336/24112321/663925bc-0d56-11e7-82b1-db5d6d20385b.png)

**Comment by jhoffner** [comment]
This landing page kata was retired but accidently got deleted (this is the only one that it happened to). Since it was no longer in use and way too easy for solutions or much else to really matter, I hadn't taken the time to try to restore it. 

Does anyone really care? I can try to bring it back if so but I'm not sure if there is much value.

**Comment by kazk** [comment]
> Does anyone really care? I can try to bring it back if so but I'm not sure if there is much value.

I'm not sure either. I just found the link to it in the description of "[PHP in Action #1 - Introduction to Superglobals \[Fundamentals\]](https://www.codewars.com/kata/php-in-action-number-1-introduction-to-superglobals-fundamentals/php)" kata by @DonaldKellett:

> This Kata Series assumes that you have already learnt the fundamentals of PHP such as data types (e.g. strings, numbers, booleans), functions and basic OOP. A good indicator that you are ready for this Kata Series is if you can complete both the [Multiply (8kyu) in PHP](https://www.codewars.com/kata/multiply/train/php) and the [Broken Greetings (8kyu) in PHP](https://www.codewars.com/kata/broken-greetings/train/php) without hesitation and without referring to external sources in the process.

---

@DonaldKellett what do you think? Is there an alternative you can point to?

**Comment by kazk** [comment]
I think I misunderstood.

> This landing page kata was retired but accidently got deleted

So restoring means restoring to *retired*?
If so, I don't think there's much value since it can't be completed and it's little awkward to point to "retired" kata in the description.

**Comment by jhoffner** [comment]
We could restore it to not retired. It did teach an important concept about scoping/context, though it was way too easy. 

Priority wise though I don't get a bunch of time each week to dedicate to CW and there are some higher priority issues that need to come first. @DonaldKellett I would just unlink it from the kata in the meantime.

**Comment by DonaldKellett** [comment]
Thanks @kazk and @jhoffner for the notification; I will be editing that section of the Description soon :smile:

**Comment by kazk** [comment]
I think we can pretend it never existed. Closing
