### ISSUE TITLE
Beta Kata with Unresolved Issues approvable by Moderator ("Improved" Beta Process?)

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#866]
@jhoffner ,

I am not sure whether this is an (recent) intended feature or a bug but [this (just previously) Beta Kata which still contains an **unresolved** Issue](https://www.codewars.com/kata/find-twins) has just been approved by a Moderator.  Now, I *may* be mistaken and this (approved) Kata may have just jumped to the top of the search results due to a recently approved translation but I seriously doubt this is the case, my reason being I recently noticed that some of my low-Kyu (i.e. `8-5 kyu`) older Kata are already "Awaiting Moderator Approval" even if they have not reached the requirements that you mentioned a few months ago (e.g. White Kata requiring `>90%` satisfaction rate with at least 12 votes and rank assessments etc.).

*If* I am not mistaken and this Kata being approved with unresolved Issues is due to an "Improved" Beta Process aiming to get more Kata out of Beta in a short period of time, then I would like to kindly *suggest* that you **reconsider the Beta Process**.  Previously, Beta Kata that may have had a "high satisfaction rate" due to large numbers of inexperienced Codewars users (without the best interests for Codewars Kata quality at heart) upvoting the Kata without thinking twice about code coverage, naming conventions etc., could still be prevented from leaving Beta by a more experienced Codewars user with **the best interests of Codewars at heart** raising genuine, serious Issues on the Kata, which ensured that at least 90% of Kata leaving Beta were of a high quality.  However, if unresolved Issues on a Beta Kata can no longer withhold faulty, problematic Beta Kata from being approved, then the "Issue" tag pretty much becomes useless and the proportion of poor-quality approved Kata on Codewars will skyrocket which may deter serious programmers from using the Website.

Back to that particular Kata I was mentioning about, hopefully you will agree with me after looking at the PHP test cases for that Kata that **5-6 fixed assertions in the entire test suite** is *hardly* "full code coverage" and thus **goes against the [Kata Best Practices](https://www.codewars.com/topics/kata-best-practices#code-coverage)** in the official Forum which justifies the Issue I raised regarding the lack of random tests as an **official Codewars stance**.  Therefore, I would like to *propose* that you make an exception to this (recently approved) Kata and **bring it back into Beta** as it is still clearly lacking in quality.

I sincerely hope that such an event will not occur again as we experienced, dedicated users strive to maintain the overall quality of content on Codewars.

Yours sincerely,
DonaldKellett (donaldsebleung on Codewars)

**Comment by jhoffner** [comment]
The kata you are referring to (Find Twins) was approved in December, so it must have been a translation. 

The part of the process that was updated is that if you have a track record for creating high quality kata, then the number of votes needed to get out of beta are less. 

The discount rules are as such:
- More than 10 approved kata? 20% discount on votes needed
- More than 20 approved kata? 33% discount on votes needed
- More than 30 approved kata? 50% discount on votes needed

Satisfaction scores must still be as high as they normally need to be, which is based on kyu level.

**Comment by kazk** [comment]
@jhoffner is this correct interpretation?

<table>
<thead>
<tr>
<th>Level</th>
<th>Satisfaction %</th>
<th colspan="4">Required Votes by # of Approved Kata</th>
</tr>

<tr>
<th></th>
<th></th>
<th>&lt;10</th>
<th>&lt;20</th>
<th>&lt;30</th>
<th>30+</th>
</tr>
</thead>

<tbody>
<tr>
<td>White</td>
<td>90+</td>
<td>12</td>
<td>10</td>
<td>8</td>
<td>6</td>
</tr>

<tr>
<td>Yellow</td>
<td>85+</td>
<td>10</td>
<td>8</td>
<td>7</td>
<td>5</td>
</tr>

<tr>
<td>Blue</td>
<td>75+</td>
<td>8</td>
<td>6</td>
<td>5</td>
<td>4</td>
</tr>

<tr>
<td>Purple</td>
<td>70+</td>
<td>5</td>
<td>4</td>
<td>3</td>
<td>3</td>
</tr>
</tbody>
</table>

---

Based on this [comment](https://github.com/Codewars/codewars.com/issues/757#issuecomment-270100977) from #757 and rounding to nearest integer.

**Comment by DonaldKellett** [comment]
Apologies @jhoffner for falsely assuming that said Kata was recently approved and bothering you in the process due to my own misunderstanding, I will do my best to ensure that such a situation will not occur again :(

**Comment by DonaldKellett** [comment]
As for the **actual** modifications to the Beta Process that you just mentioned regarding discounting the number of upvotes needed for Moderator approval of Kata authored by reputable Kata authors, I **completely agree and support** it - many thanks for adding the feature! :smile: :tada:

**Comment by dinglemouse2250** [comment]
Suggestion: If that table in previous comment from @kazk was correct can it please be documented in the blog as a reference?

**Comment by kazk** [comment]
We need to update "[Beta Kata Process](https://www.codewars.com/docs/beta-kata-process)" documentation.
I'm going to include the updated version in #881 (or ask for contribution after setting it up) and the table can be included in it.
