### ISSUE TITLE
Problems merging a translation

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#87]
Usually I can fix things forking a translation and putting the new description in place of the old one; this time it seems there are [more issues](http://www.codewars.com/kumite/556afa4742de965afc00007f): any tip to finally have it approved as it was the case with the other I did for the same kata?

[The author modified the description after that, but I thought that I went around that with the last fork, if this may help]

**Comment by jhoffner** [comment]
I was able to push it through by adding a new line. There is definitely a bug here but unless it starts happening more often I'm going to consider it tolerable and close it.
