### ISSUE TITLE
Removing Solution

### ISSUE THREAD

**Issue by beansitsme** [Codewars/codewars.com#870]
I submitted a code which passed all of the test cases but then realized that the test cases didn't cover some corner cases so I updated the code to reflect the corner case. Unfortunately, both solutions are posted and the obsolete one cannot be deleted. I tried to create custom test cases in order to move the older code into the obsolete section but no luck.

Anyway to remove submitted solutions?

**Comment by brendanvos** [comment]
Nope!

**Comment by brendanvos** [comment]
@jhoffner @kazk @beansitsme Can be closed as it's not a suggestion/issue/bug and there is already a suggestion regarding this topic (#540).

**Comment by kazk** [comment]
@brendanvos this is not the same as #540. #540 is about accidentally submitting *exact* duplicates.

@beansitsme 
> the test cases didn't cover some corner cases

I'd recommend making a suggestion on the kata discourse page to improve the tests and include the tests you wrote as an example. If the author agrees and once those tests are added, your older solution should be marked as obsolete. Also, you can write a comment on your old solution about the corner cases and include a link to you improved solution.

If this answers your question, please close this issue.
