### ISSUE TITLE
Changes in honor for translation?

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#871]
@jhoffner 
Did honor for translations change once more? It was 64 for a "4 kyu" and now I simply got 24... 

I didn't translate any more 7 or 8 kyu (a poor 4 honor), I will not translate anything now...

As @bkaestner said there is no incentive to translate and I would add no incentive to author. If your kata is easy enough it is a 7 kyu and you got 4 honor for each translation which it is not worth the work and if it is rather long in the description or in the solution nobody takes it and you stay in beta for a long time.

**Comment by brendanvos** [comment]
According to [your site events](https://www.codewars.com/users/g964/site-events):
>Blue code snippet translation approved	68	4080

Looks like you're getting 60 honor per blue translation in addition to the 4 for every translation regardless of color.

**Comment by g964** [comment]
I don't remember how many blue translations I have done... But for the last one I went from xxx34 to xxx98 - which I thought was normal: 64 honor - but in a few tenth of seconds the score went down to xxx58 (so 24 honor) hence I think that the rules can have been changed.

**Comment by bkaestner** [comment]
> As @bkaestner said there is no incentive to translate and I would add no incentive to author

I said[ that __honor__ does not provide an incentive](https://gitter.im/Codewars/codewars.com?at=58d3e6aef7f7d4810449dcd8). Whether or not a bunch of points is your primary drive is something different.

**Comment by g964** [comment]
@bkaestner : I don't see the difference...

**Comment by 10XL** [comment]
could it be that after you scored the 64 translation points, you were given negative points from kata downvote(s)? you could remove the translation and add it again.

**Comment by g964** [comment]
I doubt that in so little a time I was downvoted 40 times... but who knows:-)

**Comment by jhoffner** [comment]
@g964 The point system has not changed. If it had you would have had a massive drop since point changes are always retroactive. Not sure what happened. Maybe a fluke, maybe its corrected itself since? You have so many points its hard to tell by eyeballing things. 

As for the statistics not being inline with other pages. Stats are calculated at periods throughout the day. They are too expensive on the servers to keep realtime. Your stats page now says 1857.
