### ISSUE TITLE
Suggest: Another option for the Kata "Progress" drop-down to find abandoned Kata

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#873]
I would like to be able to select "**Kata I have trained on but not completed**"

For example, I have lots of Kata I started training on but for whatever reason abandoned. I'd like to know what they were so I can revisit them. 

Unfortunately (but probably typically) I was too negligent to bookmark them and too disorganized to put them into collections

**Comment by tachyonlabs** [comment]
I said this on Gitter, too, but if you go to your profile page and select the Kata tab and then Unfinished, this bills itself as "View all kata that you have started but have not yet completed" -- on one hand I think the list it shows me, at least, should probably be longer than it is, but on the other hand it's not like I've actually been keeping track of the number, so I may just have an inflated view of things.

**Comment by brendanvos** [comment]
And my input from gitter:
Here's your URL https://www.codewars.com/users/dinglemouse/unfinished

**Comment by dinglemouse2250** [comment]
It would still be more convenient from the Kata page but this does exactly what I wanted, so I am happy for this issue to be closed...
