### ISSUE TITLE
Weird Codewars Red "Most Consecutive Days" Streak behavior again

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#875]
I'm pretty sure my streak had gotten up to over 200, but now it's saying this --
![image](https://cloud.githubusercontent.com/assets/2389786/24560415/98632f2a-15f7-11e7-9fcc-80fcdf7520f0.png)
-- which doesn't make sense anyway re the 143 vs 144. I am https://www.codewars.com/users/tachyonlabs

**Comment by kazk** [comment]
I suddenly got 0 :(
![image](https://cloud.githubusercontent.com/assets/639336/24574114/709fa52c-1642-11e7-8f43-2f9ff5a5f6c9.png)

**Comment by jhoffner** [comment]
I updated the logic to use a 28 hour timeframe to be a bit more lenient towards hitting exact days (to compensate for time zone differences). I had tested on a number of accounts and it all seemed fine, I must have missed something. 

I'll look into this hopefully tomorrow. Your streak information is still there I just need to tweak the calculation.

**Comment by kazk** [comment]
Maybe it's not the calculation? It looked fine earlier today, but "Current Streak" became `0` when I competed a kata.

![image](https://cloud.githubusercontent.com/assets/639336/24583495/ac08003c-1700-11e7-9ebe-30fb5b8f8497.png)

![image](https://cloud.githubusercontent.com/assets/639336/24583497/bd134170-1700-11e7-80a1-bfea3bdfcf12.png)

Other stats haven't refreshed yet.

![image](https://cloud.githubusercontent.com/assets/639336/24583499/ca7f9e94-1700-11e7-9217-f77bd9219e39.png)

![image](https://cloud.githubusercontent.com/assets/639336/24583509/495eda86-1701-11e7-9d44-90f9df3764af.png)

![image](https://cloud.githubusercontent.com/assets/639336/24583510/55083076-1701-11e7-94e1-ad5e0c459292.png)

**Comment by tachyonlabs** [comment]
Looks like it's back the way it used to be now:
![image](https://cloud.githubusercontent.com/assets/2389786/24669195/5992c308-191e-11e7-9f6f-965144d66d5f.png)
So I think the most number of days value is correct again, but the "Current Streak" that was being put in before does seem like a useful feature to have as well.

**Comment by jhoffner** [comment]
Current streak is now hidden if it's the same as the current. Seemed like redundant information.

Thanks,

--
Jake Hoffner
Sent with Airmail

**Comment by tachyonlabs** [comment]
My streak is acting up again, on my profile it says "Ended On:Apr 29, 2017" even though I have continued to do katas on the days following that as well.
