### ISSUE TITLE
Full tests replacing example tests in newly approved translations, making solutions visible in the example tests box

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#876]
OK, this one is a mess:

Earlier today I saw a description of this happening in the discourse for this kata: https://www.codewars.com/kata/andys-coffee-addiction/discuss

And then when I solved the Python translation of this kata -- https://www.codewars.com/kata/simple-fun-number-62-draw-rectangle/train/python -- I saw that the full test cases were in the example tests box, including the solution code that the random tests run against.

Earlier today @nekokat did a CoffeeScript translation of my Resistor Color Codes, Part 2 kata, which I approved, and although the example tests in the Kumite are exactly as they should be, again, if you go to https://www.codewars.com/kata/resistor-color-codes-part-2/train/coffeescript you'll see that the full tests again including the solution code are visible in the Example Tests box, and clicking RUN EXAMPLES runs them.

**Comment by jhoffner** [comment]
I noticed this earlier and thought someone just messed up. This was a copypasta error on my part. I'm deploying a fix now. 

Whatever translations were approved over the last day are going to need to be manually updated unfortunately :(

**Comment by jhoffner** [comment]
Actually I'm working on a script that will update the last few days automatically.
