### ISSUE TITLE
[Suggestion] Additional Percentile Precision

### ISSUE THREAD

**Issue by brendanvos** [Codewars/codewars.com#877]
Dedicated users quickly earn enough kata to reach the 99th percentile. A tenths place decimal for precision would better depict the position of higher level warriors. 

Percentile progress is fairly rapid, so it may be better to only show decimal precision on the profiles of warriors who have reached the 99th percentile.

**Comment by kazk** [comment]
Suggested before in #603, if I'm not misunderstanding.

**Comment by brendanvos** [comment]
You are correct, closing as a duplicate of #603
