### ISSUE TITLE
no data was written to STDOUT or STDERR. 

### ISSUE THREAD

**Issue by yonichanowitz** [Codewars/codewars.com#879]
Is this a standard message for someone who fails an entry challenge, or something unique?

i am using a corporate internet link, which may be the problem, though i am not sure.

thank you.

**Comment by brendanvos** [comment]
You get that message when you attempt to run the example tests when there are none. 
If there are no tests to run nothing happens and no data is written to STDOUT or STDERR.
Write some tests!

**Comment by yonichanowitz** [comment]
i was writting several tests. the problem was that the company i work at has a firewall so sensative, it would not let the codewars challenge go through

**Comment by erickuu** [comment]
i not understan what is "Response received but no data was written to STDOUT or STDERR. ????"

**Comment by erickuu** [comment]
> i not understan what is "Response received but no data was written to STDOUT or STDERR. ????"

I undertand the problem ...

**Comment by Blind4Basics** [comment]
@erickuu : https://docs.codewars.com/training/troubleshooting#memorysaturation
