### ISSUE TITLE
Unable to submit Kata solution: "Attempt" button never changes

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#884]
I have solved this Kata https://www.codewars.com/kata/wise-drunk-man/train/javascript

* I pass all examples ("Run Examples" button)

* I pass the solution attempt ("Attempt" button)

But the "Attempt" button never changes to "Submit Solution" (or whatever the label is) so I am unable to submit my solution for this Kata

Tried logout/login - refresh etc - still same.

**Comment by kazk** [comment]
That's because the kata is in "Draft".

![image](https://cloud.githubusercontent.com/assets/639336/24834508/b8a5c8e6-1c9c-11e7-922a-ba97719aa8b6.png)

**Comment by dinglemouse2250** [comment]
Oh... I never noticed. 

I'm sure it was Beta earlier. Author maybe unpublished when I was 1/2 way thru. Thanks.
