### ISSUE TITLE
Stats page not updating properly

### ISSUE THREAD

**Issue by bigsee** [Codewars/codewars.com#886]
My stats have not updated for a few days. I have definitely completed more katas than the stats tell me and even within the stats page there is an inconsistency. The stats says that I have completed 38 katas in PHP and 2 in Javascript, but that I have completed 39 overall.

Couldn't see anything on your StatusPage. Is there an underlying/ongoing issue that explains why my Javascript progress is not being updated?

Username is: bigsee

Thanks in advance for your time and energy!

**Comment by tachyonlabs** [comment]
Ditto -- since I guess Friday morning (PDT) my honor has gone up but my profile always says "Stats are being refreshed, your browser will reload soon..."

**Comment by kazk** [comment]
Maybe the issue in background processing queue came back. See #723, #731.

**Comment by jhoffner** [comment]
There was an issue with the stats worker. I've corrected the issue but it may take a day or so before stats fall back into place.
