### ISSUE TITLE
Suggest to add a filter, solved/not-solved by specific language

### ISSUE THREAD

**Issue by ekailia** [Codewars/codewars.com#887]
In the list of Kata, there are ticks before some headings, saying "You have already solved this kata".

They were solved by some languages that I already know, But I am looking for Kata to practice a new language. I am not able to distinguish if a kata is solved by **which language**.

Suggest to add a filter against specific language. For example, I'd like to select Kata that have not been solved with Haskell.

**Comment by kazk** [comment]
Possible duplicate of #790 which requests to filter by currently selected language.

**Comment by kazk** [comment]
Closing as duplicate of #790
