### ISSUE TITLE
Please do something about abandoned katas / translation approvals

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#888]
Related issues:
Editing Kata permission: allow for translation approvals enhancement #855 opened on Mar 10
Feature: Users with high kyu can approve translations enhancement #591 opened on Sep 24, 2016
Proposal: "No active contributors" flag for abandoned katas enhancement #127 opened on Jul 15, 2015

Multiple users have recognised the annoyance of having pending translations, which will never get approved, because the kata has been abandoned by the original author. Already some related issues were submitted, the first in 2015. And these have been marked as 'enhancement', without any committed solve date.

If implementation of these enhancements is postponed for too long, at least provide a way for users to contact an admin who can solve this manually.

Personally, I have 7 pending translations, which amount to >1000 points. If I don't have any clue if these points are 'postponed' indefinitely, and I have no way to know beforehand if a translation I make will ever get approved, I feel not motivated to contribute a translation anymore.

**Comment by DonaldKellett** [comment]
Pretty sure this has been suggested before but I'll say it again: Moderators (i.e. users with `6000+` Honor) should be able to approve Kata Translations as well as actual Kata in Beta.  This should solve the "inactive author" problem - if an author is inactive, one could just post the translation link onto our Gitter channel and a Moderator could head towards the translation and approve it.

**Comment by kazk** [comment]
In #496, I [suggested](https://github.com/Codewars/codewars.com/issues/496#issuecomment-287511690):

> How about moving everything into Kumite style (even the original language) and allow moderators (or create a new privilege) to administrate them? If I remember correctly, Kumite can be turned into Kata and I'm assuming there're already some connection. Is making Kata into a group of Kumite possible? i.e., exporting the languages directly entered in Kata editor to Kumite and treating them similar to translations.
>
> ```
> Current                                   Kata as group of Kumite
>              +---- Kumite ---+            +- Kata (Kumites) -+
> +- Kata --+  | [Python]      |            | +[JavaScript]    |
> | [JS]    |--| [Haskell]     |            | +[Ruby]          |
> | [Ruby]  |--| [C]           |            | +[Python]        |
> +---------+  | [Go]          |            | +[Haskell]       |
> Approved by  +---------------+            | +[C]             |
> moderators    Approved by the author      | +[Go]            |
>                                           +------------------+
>                                           Approved by moderators
> ```
>
> Some benefits that I can think of at the moment:
> [...]
> - Improves management
>   - Doesn't rely on single user
>   - Approval is more uniform (allow translation approval #855)

and @jhoffner [replied](https://github.com/Codewars/codewars.com/issues/496#issuecomment-290561321):

> @kazk As for exporting all languages added directly via the kata editor as translations, so that they can be improved. Its an interesting idea. [...]
>
> I'm in the process of creating a new kata/challenge UI from scratch, which will be shared between both Qualified and Codewars. I'm not likely to get too deep into changing anything else until I start to connect that UI to Codewars.

**Comment by Voileexperiments** [comment]
Bump.

Since kata edits are already done (#1010), maybe this should be the next?

**Comment by kazk** [comment]
https://github.com/Codewars/codewars.com/issues/1065
