### ISSUE TITLE
"There is some Issue" flag

### ISSUE THREAD

**Issue by adam-tokarski** [Codewars/codewars.com#89]
It happens that Kata, already not in Beta mode, has some Issues, like in http://www.codewars.com/kata/simple-substitution-cipher-helper/train/python. Although that issue is with testing, not the Kata itself, maybe should be some flag, somewhere at the top of description, marking Kata as having some problems. In extreme cases it would save time young padawans. 
That flag would be activating when someone raise an Issue in discuss, and disabling when is solved. 

What do you think?

**Comment by jhoffner** [comment]
We added issue summaries a while back.
