### ISSUE TITLE
Link to "convention" div in Kata Best Practices is broken

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#891]
Just thought I'd let you know, the `href` attribute of the link "Follow Conventions" at the top of the "Kata Best Practices" page in the Forum is set to `#` instead of `#convention` which means clicking it doesn't auto-scroll to that corresponding section of the guide.

![screen shot 2017-04-12 at 11 24 29 pm](https://cloud.githubusercontent.com/assets/7777884/24965769/996993b6-1fd7-11e7-9372-dc88ccafd49c.png)

**Comment by jhoffner** [comment]
The current documentation system needs to be phased out. This should get resolved once it does.
