### ISSUE TITLE
Issue with sign up

### ISSUE THREAD

**Issue by bercohen** [Codewars/codewars.com#894]
I solved the first JavaScript test when trying to sign up to codewars, and all the tests passed.
Yet it does not allow me to sign up.
Just asks me if I want to try the test again.
![whatsapp image 2017-04-13 at 11 15 30 pm](https://cloud.githubusercontent.com/assets/23509267/25032335/45578376-20a1-11e7-8585-a1026e693d22.jpeg)

**Comment by tachyonlabs** [comment]
There's a sitewide problem going on right now ... *all* katas are having that problem. :-(

**Comment by bercohen** [comment]
Thank you!

**Comment by hopkinskong** [comment]
@tachyonlabs Yea. #893

**Comment by jhoffner** [comment]
Issue is fixed
