### ISSUE TITLE
Cannot delete draft katas

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#899]
When I try to delete some draft katas that I published and then instantly unpublished (for testing purposes), the page gets stuck forever after I pressed "Yes, I want to delete the kata". This seems to happen in multiple browsers.

**Comment by 10XL** [comment]
Can you check the console? I have a similar issue, this might be a duplicate of https://github.com/Codewars/codewars.com/issues/878

**Comment by Voileexperiments** [comment]
I think yes, this is duplicate of #878 .
![image](https://cloud.githubusercontent.com/assets/14909989/25059057/e66c0aa4-21b2-11e7-9a6d-89286c758a13.png)

That one seemed to have gone quiet for a while though.
