### ISSUE TITLE
Cannot set estimated difficulty while approving a kata

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#90]
Really MINOR bug, but just to let you know, if I both set the estimated difficulty for a kata and approve it with a given official difficulty, I get this (which is easily solved by pressing F5 on your browser):
![image](https://cloud.githubusercontent.com/assets/4815731/7958168/fade8136-09ec-11e5-930c-06899a66af02.png)

**Comment by jhoffner** [comment]
I'm pretty sure this is fixed, though estimated ranks are meaningless once they are approved so it shouldn't really matter.
