### ISSUE TITLE
Frequent Publishing Timeouts again

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#901]
I just updated the Description of one of my most recent approved Kata to include a link to the next Kata in the Series and when I clicked "Re-Publish" the "waiting" message showed up for around 30 seconds and then it told me that the publishing timed out:

![screen shot 2017-04-15 at 4 03 15 pm](https://cloud.githubusercontent.com/assets/7777884/25062004/92a085e2-21f5-11e7-8021-764e25796dee.png)

I re-attempted the "Re-Publish" multiple times to no avail.

**Comment by DonaldKellett** [comment]
Frequent publishing timeouts still occurring today as I was attempting to update the tests in one of my recently published Beta Kata:

![screen shot 2017-04-16 at 10 58 44 pm](https://cloud.githubusercontent.com/assets/7777884/25072063/c9d4d1ea-22f8-11e7-920c-5021a51f9741.png)

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
