### ISSUE TITLE
UTF-16 characters displayed by console.log is not encoded properly

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#902]
I'm writing a JS kata that requires displaying Unicode characters to console.log, and it seems that out of about magic/100 times or something, the result printed is not encoded properly:

Expected (happens in (100-magic)/100 times):
![image](https://cloud.githubusercontent.com/assets/14909989/25062874/0f82ece6-2208-11e7-9262-41b4a50c64c4.png)

Actual (happens in magic/100 times):
![image](https://cloud.githubusercontent.com/assets/14909989/25062868/eed7ea0a-2207-11e7-865b-4cfd92af0882.png)

EDIT: The kata I was writing is now alive, so you can check it for yourself:
https://www.codewars.com/kata/xiang-qi-xiangqi-slash-chinese-chess-board-validator

**Comment by Voileexperiments** [comment]
So I'm now attempting the new [Check and Mate?](https://www.codewars.com/kata/check-and-mate) kata, and it seems that this problem affects even chess pieces as well:

Expected (happens most of the time):
![image](https://cloud.githubusercontent.com/assets/14909989/25079452/3c0b5baa-236f-11e7-94e0-a73f65ea5a5a.png)

Actual (happens sometimes):
![image](https://cloud.githubusercontent.com/assets/14909989/25079471/6e9e366e-236f-11e7-912e-24d3e8f31d01.png)

My educated guess (haven't actually checked encoding conversion for those garbled text, but I've encountered enough of them during my life) is that what happens here is the complementary behaviour of the above problem. Maybe apparently a small portion of the AWS servers are running in a different locale, and hence has different encoding from the others (possibly even at China)?

In any case, there are probably some implicit encoding happening somewhere in the chain.

(By the way, @myjinxin2015 suggested to me yesterday to use `codePointAt` to deal with the problem:
```javascript
const form = s => [...s].map(c=>`&#${c.codePointAt(0)};`).join(""); //maps char to char.codePointAt(0)

usage:

s='車馬象士將士象馬車'
console.log(s)  VS  console.log(form(s))
```
which work perfectly, however it doesn't quite solve the mystery: Why is it needed to reparse the UTF-16 chars as codepoints again? And how did the text come out in a wrong encoding when it goes wrong?)

**Comment by Voileexperiments** [comment]
Another thing I noticed: The console output is fine when the tests are still running and streaming console output (it's on by default in kata editor), but only become garbled after the tests are completed (or killed by SIGKILL or whatever) and results are concluded.

I think this suggests that the problem comes from the final encoding of the results page.

**Comment by kazk** [comment]
This has been happening for a while. I [suggested](https://www.codewars.com/kata/576bbb41b1abc47b3900015e/discuss#5876fc857aad391887000307) myjinxin to use that method.

I thought this was classic [Mojibake (文字化け)](https://en.wikipedia.org/wiki/Mojibake), but I've seen it randomly display correctly if I submit multiple times and I don't know why is that.

@jhoffner, is [Codewars/output.codewars](https://github.com/Codewars/output.codewars) still used? I don't know how it's used, but [public/index.html](https://github.com/Codewars/output.codewars/blob/c6fd4c9d1deb3d5044f395b8945d48ed2c23550b/public/index.html) lacks `<meta charset="utf-8" />` which might be related.

**Comment by kazk** [comment]
`<meta charset="utf-8" />` fixes this for [Codewars/output.codewars](https://github.com/Codewars/output.codewars).

```
git clone https://github.com/Codewars/output.codewars
cd output.codewars

rm Gemfile.lock # failed to install eventmachine-1.0.3 with Ruby 2.4
bundle install
bundle exec rackup -p 3000 config.ru

open http://localhost:3000
```

Adding 
```js
$(function() {
  $('body').css('background-color', '#222').html('車馬象士將士象馬車');
});
```

in `public/js/app.js` produces.

![image](https://cloud.githubusercontent.com/assets/639336/25309930/ee913390-278d-11e7-902b-5f35da0eb391.png)

Adding `<meta charset="utf-8" />` in `public/index.html`.

![image](https://cloud.githubusercontent.com/assets/639336/25309935/0e765460-278e-11e7-8bae-2a2414c377aa.png)

**Comment by jhoffner** [comment]
Output.codewars is no longer used. However I'm rolling out a rebuilt output UI (vuejs based) tomorrow so that may fix things.

**Comment by jhoffner** [comment]
The UI is released but this problem is not resolved :( `utf-8` is the default charset of the page. I'll try to look into this more this week, it might be coming back wrong from the CLI.
