### ISSUE TITLE
Tabs vs spaces in the vim editor

### ISSUE THREAD

**Issue by DestyNova** [Codewars/codewars.com#903]
Some languages (at least Haskell) do not like tabs, but the editor (at least in vim mode) seems to insert tabs by default. Could we perhaps have either spaces by default (which would probably be safer than tabs), or allow tabs vs spaces to be chosen in the account preferences menu?

**Comment by anthonylebrun** [comment]
+1

**Comment by kazk** [comment]
This was fixed a while ago. Vim mode should always insert spaces now.
