### ISSUE TITLE
Thousand separators for honor display disappears whenever honor score is updated

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#904]
So, thousand separators for honor display was a recent addition to CW platform. It makes your honor look like this:
![image](https://cloud.githubusercontent.com/assets/14909989/25081426/ec05d85c-237c-11e7-9246-34265a07b01b.png)

However, I noticed since the day it was out that sometimes the separators disappears from an already open webpage:
![image](https://cloud.githubusercontent.com/assets/14909989/25081449/08357a82-237d-11e7-81cd-ef6d2298cc20.png)

I just spent a little time experimenting, and it seems that whenever a user's honor score is updated (due to completed kata. Not sure about other honor sources, can't test them readily) the honor display is updated too, but the thousand separator isn't inserted in the updated display.

This happens in the same tab you just completed a kata on as well, so testing it is as easy as to just find a random 7kyu kata and complete it.

**Comment by dinglemouse2250** [comment]
1000's separator is also absent from the number displayed on user profile page, user profile badges, etc

**Comment by kazk** [comment]
I think this is caused by the following code:

```js
App.PubSub = {
  // ...
  handleModelUpdate: function(e) { // {id: string, updates: {honor: number}}
    console.dir(e);
    if (e.updates)
      return Object.keys(e.updates, function(t, n) {
        return $("[data-rt='" + e.id + ":" + t + "']").text(n) // <--
      })
  }
}
```

`Object.keys` seems to have multiple non-standard definitions in `application.js`, but I think the above uses the following:
 
```js
function keys(t, n) {
  var r = Object.keys(t);
  r.forEach(function (e) {
    n.call(t, e, t[e])
  })
  return r;
}
```
