### ISSUE TITLE
Cannot submit a corrected solution

### ISSUE THREAD

**Issue by MMMAAANNN** [Codewars/codewars.com#91]
There is this kata:
http://www.codewars.com/kata/last-digit-of-a-large-number/solutions/javascript/all/best_practice

It had a bug which made many solutions not working (incorrect expected type of return). I happened to solve the kata during the period when it had the bug, so I was forced to return the wrong type too (string instead of integer). Now that the bug is corrected, my previous solution is invalid, which is good.

However, when I try to submit the corrected solution, it does not appear in solutions. I tried twice. It did not appear in the published solutions, only my old invalid solution is there.

Notably, it does appear in the trainer on the "Past solutions" tab.

This is not the first time I see such behaviour. I remember a similar situation with one of my katas (do not remember which one exactly right, now, but I can find) - I tried to publish another solution to my own kata and it did not get published, only went to my "Past solutions" available in the trainer.

**Comment by iAmMrinal0** [comment]
I am facing the issue and came here to post it. Everytime I check "obsolete" solutions section in my profile I have to remind myself that few problems have already been solved but I still check the kata for updated test cases which is a time waste for me.

And I don't know if you noticed it, if you try to view "All solutions" then the incorrect solution would also be shown there.

**Comment by adam-tokarski** [comment]
Still there is some problem. After correct solution, it is shown in [My solution] list, but I can't find it at [All solutions] panel.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.

**Comment by vsevolod19860507** [comment]
https://www.codewars.com/kata/525c1a07bb6dda6944000031/ in Swift. The same problem.
