### ISSUE TITLE
Kumite and 'edit languages' page unavailable 

### ISSUE THREAD

**Issue by lnuic123** [Codewars/codewars.com#913]
So today I wanted to code in other language but it would always show Aw, Snap! on google chorme. I also tried to open site in private mode so it would ignore cache but still wouldn't work... The page shows in 1 ms but then it throws this error. Also looking through other pages noticed that kumite is also not working.

**Comment by jhoffner** [comment]
Is there a specific kata this is for or are you referring to the kumite page itself?

**Comment by lnuic123** [comment]
kumite page itself, here is the pic of error if im allowed to post it(http://prntscr.com/f1ffwl)
also Im using latest Chrome version, now I tried with Opera also, still getting same error
It seems that problem is specific for my account...

**Comment by jhoffner** [comment]
Thanks for the screenshot. Is your CW username the same as your github?

**Comment by lnuic123** [comment]
Yes it is

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
