### ISSUE TITLE
'Other Kata Authored By ...' shows katas of wrong user with similar username

### ISSUE THREAD

**Issue by mattesno1** [codewars/codewars.com#914]
I currently have a kata in beta. when I view its details there is a section "Other Kata Authored By ..." which shows katas of a different user with a name similar to mine.

my username is "mattes"
his username is "matt c" (mind the space)
kata in question: https://www.codewars.com/kata/dude-my-computer-cannot-count/java

Cheers,
Daniel

![Screenshot](http://i.imgur.com/IHVMjki.png)

**Comment by kazk** [comment]
Fixed
