### ISSUE TITLE
Broken kata tests is not fixed within a long time

### ISSUE THREAD

**Issue by wKich** [Codewars/codewars.com#915]
I know that issue with specific kata should be on the discourse page of that kata. But all these issues are not solved within 8 months. Tests not fixed. Nobody is allow to change it. Moreover this kata in 8 kyu and all newcomers will be disappointed when cannot solve it, because tests is broken.
https://www.codewars.com/kata/fix-the-program-to-return-hello-world-message-object

**Comment by DonaldKellett** [comment]
Unfortunately the Kata you linked to has already received over 500 solutions so the test cases can no longer be edited.  @jhoffner Would you mind retiring this Kata?  Thanks a lot :smile:

**Comment by jhoffner** [comment]
Retired
