### ISSUE TITLE
[Suggestion] Warn Kata users of forfeiting eligibility on "Solutions" tab of language that user has not completed **before** revealing solutions

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#916]
Today, I have just realised that if a user completes a Kata in one language (which automatically brings you to the "Solution" tab of that language variant of said Kata) then choose another language in the Language Dropdown without first navigating back to "Details" or "Discourse", he/she immediately forfeits his/her eligibility of that language and views all the solutions for that language without any prior warning.  This has taken me by surprise when I completed a particular `6 kyu` Kata in JavaScript, PHP and CoffeeScript (at different times all from either the "Details" or "Discourse" tab, so I did not accidentally forfeit my eligibility for any of these 3 languages), and then while I was still on the "Solutions" tab for CoffeeScript, I changed the language to "Python" expecting to see a message like "Solutions have been withheld".  Instead, I immediately saw all the relevant Python solutions and when I clicked "Train Again", the "Unlock Solutions" button was already set to "View Solutions" which I presume implies that I already forfeited my eligibility.

In this case, may you please add a warning message asking for the user's permission to proceed before eligibility for that language is forfeited and all solutions for that language are shown?  Thank you very much for your help and attention :smile:

**Comment by jhoffner** [comment]
Did you edit the kata first? That would have caused this.

**Comment by DonaldKellett** [comment]
Now I see :wink:  I presume that publishing a PHP translation to said Kata and having it approved would count as "editing the Kata"?

**Comment by DonaldKellett** [comment]
UPDATE: I have just tested this on a Kata I have not translated before and the "Solutions have been withheld" warning message appears as expected on languages I have not completed in so I guess this Issue can be closed now.  Thank you for your help and attention anyway :smile:
