### ISSUE TITLE
Ability to filter out markdown by language

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#917]
Currently language code blocks are filtered out if multiple fenced language blocks are grouped in sequence within the markdown. If the current language is present within the list of code blocks, then it will be chosen, otherwise it will default to the first code block in the group. 

Example:
````markdown
```javascript
function jsOnly() {}
```
```ruby
def ruby_only()
end
```
````

However it would be convenient to be able to show and hide entire blocks of markdown based off of selected language. It would work using special `if` or `if-not` statements. 

For example:
````markdown
```if:javascript
### JavaScript Specific Instructions
This is normal markdown which will only be rendered if javascript is the language

~~~javascript
The alternate code fence syntax can be used to display javascript blocks
~~~
```
````

It should also support targeting multiple languages at the same time:

````markdown
```if:javascript,ruby
### JavaScript/Ruby Specific Instructions
This is normal markdown which will only be rendered if javascript or ruby is the active language

~~~javascript
// this is still only shown if javascript
~~~
~~~ruby
# this is still only shown if ruby
~~~
```
````

You should also be able to exclude certain languages
````markdown
```if-not:haskell,ocaml,clojure,fsharp
### Non-Functional Languages
This is normal markdown which will only be rendered if Haskell,OCaml,Clojure or Fsharp is NOT the active language
```
````

> NOTE: The reason for utilizing code fences for this feature is that its much easier/safer to extend the marked.js logic since it already provides a handler function for interpreting fenced code.

**Comment by Voileexperiments** [comment]
This new feature is choking some katas which have descriptions written in non-conformal format i.e single line code blocks using 3 backticks because it picks up the whole line as if it's a language while it's not, which result in a parse error. e.g:

https://www.codewars.com/kata/a-simple-music-decoder/

If you enter the train screen it's put to a halt while loading, with error message `Uncaught Error: Unknown language: ""1,3-5,7-11,14,15,17-20"```"`.

(Incidentally that kata also has improper headers without spaces between # and the actual text.)
