### ISSUE TITLE
New CW test display: Now characters are displayed in variable width regardless of half/full-widthness

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#919]
My ASCII Games kata relies on displaying ASCII board on logs, which relies on every character being rendered at the same width (and half-width width is strictly half the width of full-width width) to be read properly.

But after the change:
![image](https://cloud.githubusercontent.com/assets/14909989/25401429/250f3f38-2a28-11e7-8308-9ff729c01133.png)
![image](https://cloud.githubusercontent.com/assets/14909989/25401448/33ed143a-2a28-11e7-85d3-29e487884a3a.png)

It becomes pretty much unreadable.

**Comment by jhoffner** [comment]
Which kata is this?

**Comment by Voileexperiments** [comment]
These two:
https://www.codewars.com/kata/ascii-games-dance-dance-evolution-i
https://www.codewars.com/kata/ascii-games-warning-ice

**Comment by Voileexperiments** [comment]
Sorry but it's not fully fixed yet:
![image](https://cloud.githubusercontent.com/assets/14909989/25507924/6b965a94-2be1-11e7-8930-efc1b6601ec3.png)
The font in the display is still in variable width. If in fixed width the `^` should point at the relevant character like this:
![image](https://cloud.githubusercontent.com/assets/14909989/25507943/8cde0bde-2be1-11e7-8f54-f66711f64858.png)

**Comment by jhoffner** [comment]
I forgot about STDERR. I've got a fix bto preview now
