### ISSUE TITLE
JS syntax highlighting: `=` and `-` without whitespaces inbetween during simultaneous variable assignments

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#920]
![image](https://cloud.githubusercontent.com/assets/14909989/25418704/5ca757e8-2a80-11e7-8412-f10736ddd5f8.png)
![image](https://cloud.githubusercontent.com/assets/14909989/25418718/72b17a28-2a80-11e7-8d5c-ab91fed328ea.png)

Probably something minor.

**Comment by jhoffner** [comment]
Is this within markdown or within the code editor?

**Comment by Voileexperiments** [comment]
Within the code editor.

**Comment by jhoffner** [comment]
Hmm. OK the code editor was recently updated. Its CodeMirror so it's gotta be an issue on their end.

**Comment by kazk** [comment]
We'll need to update CodeMirror. Codewars currently uses `5.19.0` and this issue is still there. The latest CodeMirror `5.42.2` doesn't (at least not reproducible on [demo](https://codemirror.net/mode/javascript/) page).

**Comment by kazk** [comment]
Fixed by updating CodeMirror to 5.24.4.
