### ISSUE TITLE
Edit Kata is briefly available for all katas during page load

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#921]
Find a random kata. Either load the page entirely new, or refresh one using F5 (clicking the sub-items on a kata won't work).  Before the page finishes loading there will be a brief period where the "Edit Kata" button is visible and clickable:

![image](https://cloud.githubusercontent.com/assets/14909989/25439230/76b022f2-2ace-11e7-9167-b6e4b706dfec.png)

Of course, clicking on the button leads to the edit page, which will greet you with a 500 error due to the lack of privilege.

**Comment by kazk** [comment]
This is because `.js-edit-challenge` is removed in JavaScript.
It's displayed for a long time if the connection is slow.

```js
App.ns("Controls.CodeChallenges.SocialButtons", App.Control({
  init: function() {
    var e;
    if (((e = App.data.permissions) != null ? e.save : void 0) === !1)
      return $(".js-edit-challenge").remove()
```

The same thing is happening for `#carbonads-container`.
I see ads display if I throttle my connection using Developer tools.

```js
App.ns("Controls.CodeChallenges.ListController", App.Control({
  init: function() {
    var e;
    this.track("Loaded"),
    ((e = App.currentUser) != null ? e.hideAds : void 0) && $("#carbonads-container").hide(),
```

**Comment by kazk** [comment]
Closing as wont fix because I believe this is required to cache server rendered page.
