### ISSUE TITLE
Profile Honor Percentile

### ISSUE THREAD

**Issue by NeuroSerpens** [Codewars/codewars.com#923]
The honor percentile should have a '%' after the number but instead it is being shown as an ordinary number (98th instead of 98%).

**Comment by Voileexperiments** [comment]
That's the correct way to use percentile:

https://en.wikipedia.org/wiki/Percentile

>For example, the 20th percentile is the value (or score) below which 20% of the observations may be found.

**Comment by NeuroSerpens** [comment]
What the heck hahaha. I had never heard of this...
It's still very strange, but alright then. If it's not wrong then it's just
ugly lol.
