### ISSUE TITLE
Document new if/if-not markdown code fencing

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#925]
I'm already adding this to a new tip popup for translations, but we should officially document the new features. 

Current markdown for popup:

## Basic Code Block Filtering:

The easiest way to provide language specific content is when providing language specific code examples. If you simply place language examples on top of each other, only the one related to the current language will be shown.

````markdown
``` javascript
function example(){
  // only shown if javascript is active
}
```
``` ruby
def example
  # only shown if ruby is active
end
```
````

If the kata already has languages examples, do not delete them. Instead append your language example to the bottom of the existing ones.

## Filterable Markdown Blocks

A newer feature on Codewars is the ability to filter entire sections of markdown using `if` and `if-not` statements. These statements are also used with code blocks. The following examples try to illustrate different ways in which you can use these statements.

````markdown
```if:javascript,ruby
This content will only be shown if javascript or ruby are active.
> A few things to note:
- Markdown is still available to be used within these code blocks
- The altenative code fence <code>~~~</code> syntax can be used for nested code fences.
```
```if-not:ruby
This markdown will only be shown if ruby **is not** the active language.
~~~javascript
// still only shown if javascript is the active language, since it has multiple examples next to it
~~~
~~~python
# only shown if python is active
~~~
```
````

**Comment by kazk** [comment]
@jhoffner
Little off topic, but since you mentioned popup, I think some popups contains useful information that can be reused in the documentation. Also, I'm not aware of a way to re-read them once dismissed.

I've collected popups that I was able to receive by visiting Codewars logged out and stored them under [docs/_infos/popups](https://github.com/kazk/docs.codewars.com/tree/64994bf1f1038a351680647c8c9583c90e78917c/docs/_infos/popups). Some of them contained typos so I fixed and commented.

**Comment by jhoffner** [comment]
Yeah my goal is to link the popups to a specific documentation page/url. It would also be nice if they showed up in the notifications dropdown, but right now they are actually a different system than the system notifications. System notifications are generated and stored in the database, the popups tips are just a yaml based set of rules that get ran on each page load.

**Comment by 10XL** [comment]
@jhoffner Invalid languages cause katas to not render the description or properly load the trainer. See https://github.com/chjj/marked/issues/810

**Comment by jhoffner** [comment]
@10XL I'm deploying a fix now to provide a fallback
