### ISSUE TITLE
Document new auto-detect HTML nature of STDOUT logging

### ISSUE THREAD

**Issue by jhoffner** [codewars/codewars.com#927]
In order to be compatible with both test frameworks that output values that look like HTML, and frameworks/content that due output HTML, a new auto-detect feature has been added. 

The nature of this feature and all of its restrictions should be documented. We should also be documenting `<LOG:ESC:>` and `<LOG:HTML:>`. We also now support `<!doctype html>`, which acts like `<LOG:HTML>` but is easier to use if multi-line log statements are used, since `<LOG:HTML:>` requires that you replace line breaks with `<:LF:>`

See #844

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1fgz) by [Unito](https://www.unito.io)

**Comment by jhoffner** [comment]
In addition, `<LOG:ESC:>` should probably be aliased as `<LOG:TEXT:>`

**Comment by kazk** [comment]
https://github.com/codewars/docs/issues/192
