### ISSUE TITLE
CW test suite not working for the last 3 hours i tried.

### ISSUE THREAD

**Issue by AwelEshetu** [Codewars/codewars.com#929]
![testsuit](https://cloud.githubusercontent.com/assets/4153683/25555220/ec471982-2ce8-11e7-94ac-5a4fb7dfd7f0.png)

**Comment by Voileexperiments** [comment]
Other katas work, it's just this kata which is not working because Test suite implicitly calls `Array.isArray` on its arguments, which causes the first test to fail in the middle. I've pointed out the issue in the discuss page:

https://www.codewars.com/kata/array-dot-isarray/discuss
