### ISSUE TITLE
Problems with anti-cheat system

### ISSUE THREAD

**Issue by chirrory** [Codewars/codewars.com#93]
I solved a kata in a way which I think it's clean and no cheating was involved, but for some reason the system flagged it as invalid because of possible cheating. 

Also my honor went down because of this. Is there a way to figure out why my solution was considered cheating and also restore the lost honor points?

Here's a link to the kata in question:
http://www.codewars.com/kata/simple-maths-test/python

**Comment by adam-tokarski** [comment]
Takę look at https://github.com/Codewars/codewars.com/issues/78#issuecomment-105680288. I've simiral problem, and also was dishonored.

**Comment by jhoffner** [comment]
I'm closing this as we have implemented a new anti-cheating flow where all suspected cheats must first be approved by an admin - to ensure we don't have false positives.
