### ISSUE TITLE
Kata Run Sample Tests and Attempt does not work

### ISSUE THREAD

**Issue by tanzimhoque** [Codewars/codewars.com#930]
Whenever I click on Attempt it just shows a blank page on Output tab. Clicking on Run Sample Tests button does nothing.

![kata](https://cloud.githubusercontent.com/assets/6842836/25557219/3595d864-2d05-11e7-8699-8dda9fcf6c1c.png)

**Comment by Voileexperiments** [comment]
Duplicate to #928

**Comment by dzjp** [comment]
I am having the exact same issue, also my code is not saved at any time.
