### ISSUE TITLE
Ads Display on Kumite Page for Red Subscriber with Ads Disabled.

### ISSUE THREAD

**Issue by mitron6** [Codewars/codewars.com#931]
Red Subscriber with Set Advertising option un checked is being shown ads on the Kumite page.
Browser: Chrome Version 57.0.2987.133 (64-bit) on MacOS Sierra Version 10.12.4.
Problem last observed at 10:45 AM Pacific Time on April 29, 2017.

![screen shot 2017-04-29 at 10 45 41 am](https://cloud.githubusercontent.com/assets/8966523/25557582/4d2cc3a2-2cc9-11e7-87fe-c0661f7fe0d1.png)
![screen shot 2017-04-29 at 10 46 40 am](https://cloud.githubusercontent.com/assets/8966523/25557584/52b46744-2cc9-11e7-9db4-a351c90a3d0a.png)

**Comment by kazk** [comment]
Closing old issue. I don't think this is happening anymore. Please let me know if it is.
