### ISSUE TITLE
Inconsistency in Haskell module naming.

### ISSUE THREAD

**Issue by wizzup** [Codewars/codewars.com#934]
What is the conventions used for Haskell module naming? 

They are different among katas.

Example:

- [single level](http://www.codewars.com/kata/string-repeat/train/haskell)
- [multiple level](http://www.codewars.com/kata/opposite-number/train/haskell)

---

Despite no problem on codewars site, I do prefer the single level module naming because it make testing code ***locally*** posibile without any modification.

Haskell compiler (GHC) seem to search for import module by looking for source code file name, for example (single level module),

    moule AddOne where

    addOne :: Int -> Int 
    addOne x = x + 1

Should name the source file; `AddInt.hs` to be able to import for testing.

    module Testing where 

    import AddInt

    main = doTest

Likewise, for multiple level module; `import Codewars.Kata.Opposite` it is expected following directory/file structure

   ./Codewars/Kata/Opposite.hs

Only the testing file which have `main` function is not require to have the same name as module name , in fact; it is not even need module declaration at all , if it not going to be imported by any code elsewhere. 

---
Why do I want to write solution locally?

There are some editor features that the online editor is lacking of.

- Code completion, linting
- Faster code/test/fix iteration
- Familiar look-and-feel, keyboard-shortcuts

**Comment by kazk** [comment]
> What is the conventions used for Haskell module naming?

I don't think there's any. Module name can be arbitrary as long as the declaration matches the following pattern:
```js
    haskell: /module\s+([A-Z]([a-z|A-Z|0-9]|\.[A-Z])*)\W/,
```
[lib/config.js#L24](https://github.com/Codewars/codewars-runner-cli/blob/16e81aa7e67758f6133b1ceec555a2e3df1e2ec3/lib/config.js#L24)
(I don't know why the pattern includes `|` in character class, but you should ignore them)
