### ISSUE TITLE
Kata search: selecting multiple ranks only returns amount of results equal to the results of the highest rank selected

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#936]
I am search katas using these set of criterias:

![image](https://cloud.githubusercontent.com/assets/14909989/25648787/237105dc-3002-11e7-8c51-e2f5b607644b.png)

The page says "217 katas found", but scrolling down will only give me as many as 41 results (which is how many 5kyu JS katas I haven't completed). Then I tried selecting 6-4kyu, and as expected, only 35 results are shown (the amount of 4kyu katas I haven't completed).

**Comment by kazk** [comment]
Fixed
