### ISSUE TITLE
JS+React: Kata trainer and Kumite window have different behaviours

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#938]
I was trying to fiddle with this kata:

https://www.codewars.com/kata/react-with-jsx

It appears that the same code behave differently in Kata trainer and Kumite window.

In Kata trainer, the code behaves as expected.

In Kumite window, however, this happens when I try to run the code:

![image](https://cloud.githubusercontent.com/assets/14909989/25666273/a589f420-3052-11e7-8722-b6ed631711ac.png)

**Comment by Dan-Nolan** [comment]
Huh, I feel like I've seen this before when the Node version was different between the kata editor and the trainer. Looking at that particular kata though only Node v6.6.0/Babel should be available.

**Comment by Voileexperiments** [comment]
Hmm, yeah, I forgot to check the JS version. For some reason kata solution forks are defaulting to Node v6.6.0 (without Babel).

I guess the problem is sitting on another castle.
