### ISSUE TITLE
Getting belt upgrades for translations I didn't do of an approved kata

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#94]
As by subject, I got a little level up on two languages that I know very, very little and for which I didn't did anything on my own.

I know it is still related on the "bug" (or feature) of getting all the solutions on the author's credit, but still I think it should be somehow fixed. I felt like cheating, in a way:

![image](https://cloud.githubusercontent.com/assets/4815731/8013391/238e56a0-0bc9-11e5-80ac-425b71a87601.png)

**Comment by jhoffner** [comment]
Ugh, I thought I fixed that :disappointed: Looks like I have to do more digging down the rabbit hole.

**Comment by jhoffner** [comment]
Oh wait I think I know the issue. I should have a fix for this soon.

**Comment by MMMAAANNN** [comment]
This is related to https://github.com/Codewars/codewars.com/issues/83

**Comment by jhoffner** [comment]
I reset your Java & CSharp rankings and also did a data migration which fixes some missing links between translations and kata, which *should* prevent this from happening again.

**Comment by GiacomoSorbi** [comment]
Wow, that was really quick; perfect and thanks again, Jake!
