### ISSUE TITLE
A (never) comprehensive list of broken katas

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#940]
So, I've cleaned up (read: finished) most of the 6kyu/5kyu JS katas now, and I feel confident enough I have encountered all the broken JS katas, which I'm compiling them as a list here:

---

### [Hello W... wait what?](https://www.codewars.com/kata/hello-w-dot-dot-dot-wait-what)

Issue: using `arguments.callee.toString()` or similar to get user code, which has become obsolete a long time ago and hence doesn't work at all.

Solution: fix it with the standard `fs` code:

```javascript
const fs = require('fs');
const usercode = fs.readFileSync('/home/codewarrior/solution.txt', 'utf8'); //the whole user submission, as text
```
---

### [Trick the Christmas Calender](https://www.codewars.com/kata/trick-the-christmas-calendar)

Issue: putting ***a whole image data chunk*** into the preloaded code. Crazy! Which leads to E2BIG error (due to too big code):

`Server Execution Error: spawn E2BIG`

Solution: Link to the image instead. The WTF part about this is that *cough* the author even have mentioned about the image source, and he's using the `background-image` CSS property,  but instead of putting the link in the url wrapper he puts the whole data chunk instead:

```javascript
//why did you do this
<div style="border: 2px solid #fff; position: relative; width: 600px; height: 376px; background-image: url(data:image/jpeg;base64,/*...base64 chunk*/);
/*...*/
html += '<div style="clear: both;"></div></div><p style="font-size: 18px;">Merry X-Mas and don\'t forget to vote for this kata! ;)</p><p style="font-style: italic">image source: http://abstract.desktopnexus.com/wallpaper/1630677/</p>';
//image source here
```

So, just replace that ugly base64 chunk with the link and it'll pass just as fine.

---

### [Custom sort function](https://www.codewars.com/kata/custom-sort-function/)

Issue: Internal check is broken:

```javascript
function check(items, expected){
  var args = Test.inspect(items)
  var actual = Test.inspect(sort(items))
  Test.assertSimilar(actual, expected, 'Called sort(' + args + ')');
//Should be Test.assertSimilar(actual, args, 'Called sort(' + args + ')');
}
```

It's checking a string against an array, so it could never be equal.

Besides this, there are other problems with this kata:

- `Test.assertSimilar` basically calls `Test.assertEquals` but applying `Test.inspect` to both sides first, so calling *both* `Test.assertSimilar` and `Test.inspect` makes no sense
- for some reasons the test cases involves a mixture of arrays and array as string as the expected result

Solution: Mentioned on the comment in the code snippet above.

---

### [Node.js Async I/O](https://www.codewars.com/kata/node-dot-js-async-i-slash-o)

Issue: The test cases try to use `cal` but it doesn't exist on CW docker OS anymore:

```javascript
command: 'cal'
stdout: /bin/sh: 1: cal: not found
error: 
{ Error: Command failed: kbm426p
/bin/sh: 1: kbm426p: not found
   at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket. (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12) killed: false, code: 127, signal: null, cmd: 'kbm426p' }
```

Also, as mentioned in the comments, the test cases doesn't even *require* to call the callback function at all, so it means I can write nothing but an extra success test, and pass the kata.

Solution: Remove that test case. As for the second issue, use Promises to ensure callback return value is resolved.

---

### [Array.isArray](https://www.codewars.com/kata/array-dot-isarray)

Issue: Test fixture implicitly calls `Array.isArray` (which is disabled). This causes the *test itself* to throw an error, which prematurely ends the test with zero passes (which counts as a failure), but if you add any passing tests before it, the kata will be solved automatically.

Solution: Here is an idea for an overly convoluted fix:

```javascript
//preloaded
const container = (function() {
  let _isArray = Array.isArray; 
  return (function*() {
    yield _isArray;
    throw new Error("I've already given out my secret");
  })();
})();

//actual test
let _isArray = container.next().value;
const dummy = ()=>Test.expect(false, "Array.isArray() is not available, sorry.");
for(let i=0; i<100; i++) {
  Array.isArray = dummy; //destroys the function. Putting undefined is okay too
  let arg = { __proto__ : Array.prototype };
  let res = isArray(arg);
  Array.isArray = _isArray; //puts it back for the actual test
  Test.assertEquals(res, Array.isArray(arg));
}
```

Basically, we're moving the crucial function we need in a container that can only be acquired once, and we'll be trying to acquire it in the test code, so if the user tries to get the function, the tests will fail with an error before anything. (Also, I used `const` to declare the container to prevent tampering)  
Then in the tests, we destroy the crucial functions before running user solution, and put it back before calling the tests. We do this every iteration.

---

### [Sqrt approximation](https://www.codewars.com/kata/sqrt-approximation)

Issue:  `Test.randomNumber` implicitly calls `Math.floor` (which is disabled). This causes the function call to throw an error and boots the code out of the test code with an error:

```
TypeError: Math.floor is not a function
   at Object.randomNumber
        at begin
    at it
        at /runner/frameworks/javascript/cw-2.js:159:11
    at Promise._execute
    at Promise._resolveFromExecutor
    at new Promise
    at describe
            at Object.handleError
        at ContextifyScript.Script.runInThisContext
    at Object.exports.runInThisContext
```

Solution: Use `require('lodash').random(0,100);` instead. They're entirely the same in behaviour (for some reason `Test.randomNumber` doesn't accept any arguments and only returns an integer between 0 to 100), and lodash doesn't depend on `Math.floor` for some reason.

**Comment by Voileexperiments** [comment]
Q: What about other languages?
A: I can't even begin to list the broken translations from other languages, there are just too many of them: Python has a lot of katas that use `xrange` instead of `range` so Python 3 is unusable for the kata; Ruby, C# and Java versions have their own great shares of brokenness as well. **It'd be better if we can sort katas by number of open issues**.

But still (to the reader), feel free to drop them in if you happen to stumble upon one. I've stumbled on too many broken translations and I didn't take note of them, and I don't think I'd be likely to meet them again in near future.

**Comment by Voileexperiments** [comment]
Bump.

This should also be a low-hanging fruit issue for @jhoffner to solve :)

**Comment by jhoffner** [comment]
I'm not 100% clear what my action item is here. 

Please remind me what is stopping users such as yourself from making these updates yourself. Is it because there are too many solutions?

**Comment by Voileexperiments** [comment]
@jhoffner Published katas can't be edited even by 6k users unless they're a contributor (has re-published the kata during beta process), and the original authors of the above-listed katas have been disappeared for a long time already. (There were two broken ones by @slothpie and @DonaldKellett which they have taken action to fix them.)

Some of them have >1k solutions so they might not be able to be edited (in which case retiring might be a good idea), but for those that can be done it'd be good if they're fixed. Of course, a more scalable solution would be if power users can do it as well, but how was the progress of it going? IIRC it was proposed a long time ago and is still WIP.

**Comment by kazk** [comment]
> Node.js Async I/O
>
> Issue: The test cases try to use cal but it doesn't exist on CW docker OS anymore:

The test also uses `exec-sync` module which doesn't exist (the module itself is deprecated because `child_process` has `execSync` now).
This error is not apparent because the thrown error is ignored by the test framework due to the bug I mentioned during the BF PR and included in the cleaned up PR (https://github.com/Codewars/codewars-runner-cli/pull/434).

To see the error, wrap the test case with `try...catch`:

![image](https://user-images.githubusercontent.com/639336/27208532-0aabf212-51fb-11e7-9e70-1b1940e811f1.png)
![image](https://user-images.githubusercontent.com/639336/27208497-e10d86f0-51fa-11e7-8b23-73d71f412391.png)

**Comment by jhoffner** [comment]
> a more scalable solution would be if power users can do it as well, but how was the progress of it going? IIRC it was proposed a long time ago and is still WIP.

Yeah this fell off my radar, I'm actually not sure at the moment why that would be a big change. I think that is the action item here for me. I will prioritize this.

**Comment by anter69** [comment]
https://www.codewars.com/kata/range-extraction -- python validating function is broken.

Solution: replace `if s:` with `if s == None:` in the `solver()` function.

**Comment by Voileexperiments** [comment]
I forgot about this kata which is also broken: [Fizz Buzz](https://www.codewars.com/kata/5300901726d12b80e8000498/)

The exact cause of the issue has been mentioned at the discourse.

**Comment by jhoffner** [comment]
I'm closing since #1010 is not implemented.
