### ISSUE TITLE
Codewars Red streak stats misbehaving again

### ISSUE THREAD

**Issue by tachyonlabs** [Codewars/codewars.com#945]
For some days now my profile has said this --
![image](https://cloud.githubusercontent.com/assets/2389786/25725987/f42fa0f0-30d6-11e7-99a3-9b0ed9ce29e5.png)
-- even though I did some katas on the mornings (California time) of April 30, May 1, etc.

**Comment by jhoffner** [comment]
I'm about to go on vacation for 2 weeks, if I don't get to this by next Friday it may have to wait. I have a lot of things on my plate before I leave. 

The streaks should also allow for 8 hours of padding (to compensate for some timezone issues) so its odd this is happening. Its also odd that your current streaks isnt showing up. If your streak high really had ended then it should also be showing you the status on your current streak.

**Comment by tachyonlabs** [comment]
No problem -- have a great vacation! My profile is https://www.codewars.com/users/tachyonlabs BTW.

**Comment by tachyonlabs** [comment]
Looks good now, thanks!

**Comment by tachyonlabs** [comment]
This is happening for me again ... my profile says
![image](https://user-images.githubusercontent.com/2389786/31279838-5b1a3792-aa5f-11e7-819f-8a69e28672b1.png)
Even though I had done katas on October 4 in the early afternoon (California time) and evening. It seems to me that you're on UTC and therefore during daylight savings time here any katas I do after 5pm will be counted for what is for me the following day, but the early-afternoon one should have been counted as October 4.
