### ISSUE TITLE
White Output screen when attempting to solve puzzle.

### ISSUE THREAD

**Issue by Fusomeister** [Codewars/codewars.com#948]
Hi, I am trying to solve any of the exercises, but running either "Run Sample Tests" or "Attempt" just leaves the Output section of the page all white without responding. I've tried jumping through a few of them, but they all do the same. Am I missing something to run them? I have solved one puzzle before, that I could complete.
- Chris.

**Comment by Voileexperiments** [comment]
It's basically #928.

The fix is only pushed to preview.codewars.com and not deployed to the main site yet, so it might take a few more days before the fix is applied.

**Comment by Fusomeister** [comment]
Thanks for responding.
