### ISSUE TITLE
Rank breakdown torus bar is not accurate

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#950]
It's been bugging me since I was 2kyu, but the rank breakdown torus bar is not aligned correctly:

![image](https://cloud.githubusercontent.com/assets/14909989/25729435/ea18b200-3167-11e7-9536-4ba0b31e5a55.png)

![image](https://cloud.githubusercontent.com/assets/14909989/25730010/020b4fae-316c-11e7-9d3e-911281b3a262.png)

1. The beginning of the bar is actually a bit further than the center y axis.

2. The bar goes a bit further than it should be. My progress is 71%, and I took my protractor and measured the span of the torus to be ~260 degrees, which is about ~72.5%. In fact, it becomes pretty obvious when one reaches 99-100% progress because then the bar overflows into itself into the second lap (which I happened to have noticed when I was about to become 1kyu).

Edit: the bar now reaches 75%, which makes the discrepancy very obvious:

![image](https://cloud.githubusercontent.com/assets/14909989/25847603/58a88518-34e9-11e7-8fad-cfb6b67bc12d.png)

**Comment by Voileexperiments** [comment]
Uhm, have more definitive pics?

![image](https://user-images.githubusercontent.com/14909989/27012297-c69c278e-4eff-11e7-9c02-7da198d801e4.png)
![image](https://user-images.githubusercontent.com/14909989/27012299-ca82d956-4eff-11e7-9197-bbdb5dea0d77.png)

**Comment by kazk** [comment]
For some reason, it was offset by `4.75` instead of `1.5 * Math.PI` (about `4.71`, 3/4 of a circle).
