### ISSUE TITLE
Solution comments on some katas are not loaded properly at solution pages

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#953]
For example, see the top three solutions of this kata:

https://www.codewars.com/kata/jaden-casing-strings/solutions/javascript

They have comments in it, but clicking on the comment button will reveal nothing. Not even the text box for you to type comments:

![image](https://cloud.githubusercontent.com/assets/14909989/25734471/d5079fce-3195-11e7-96cc-f43d90b94081.png)

They can only be revealed by clicking into said solution, e.g:

https://www.codewars.com/kata/reviews/5390bac547d09b7da40006fd/groups/5390c944cd51b6514b000b3d

Some brief testing (and from my experience) seems to suggest that it's a kata-bound problem and not a solution-bound problem.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1fj8) by [Unito](https://www.unito.io)

**Comment by Voileexperiments** [comment]
@kazk Looking into this a further bit it seems to be yet another cache issue: the solution comments are not loaded if the solution page is (presumably) not accessed for some time, and after a refresh a few seconds later it's loaded again.

**Comment by kazk** [comment]
Let me know if this is still happening.
