### ISSUE TITLE
Spoiler comments are visible?

### ISSUE THREAD

**Issue by dinglemouse2250** [codewars/codewars.com#957]
I was looking at some of the discussion for this Kata 
https://www.codewars.com/kata/590adadea658017d90000039/discuss#590d9789ebc52b6d8b000062

There are a couple of comment with code (from recent user Boumbap/B4B discussion). Those comments ARE flagged as containing spoilers but I can still SEE it despite having never trained on this Kata (let alone solved it).

**Comment by docgunthrop** [comment]
In the Discourse section of a kata (https://www.codewars.com/kata/mystery-function/discuss/), I had replied to a comment thread where the last posted comment was marked with the Spoiler tag and was, therefore, hidden.

After posting my comment to the chain, the hidden comment was revealed. After refreshing the page, the hidden comment became hidden again. This appears to be an unintended bug.

**Comment by Voileexperiments** [comment]
It was always like that, even on normal discourse.
