### ISSUE TITLE
Using UTF-8 or other encoding in Ruby

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#96]
More than a bug it is probably a fault on the side of my ignorance, but is there a way to force a kata to work with an encoding other than US-ASCII? I tried a bunch of tricks and commands I found online, but could not manage to do it and I would need it to translate a kata that requires the greek alphabet.

If it is somehow blocked, it is ok; otherwise, any help or tip is welcome :)

**Comment by GiacomoSorbi** [comment]
Bump! Anyone having an idea on how to implement it on CW? Magic comments and the like do not seem to apply.

**Comment by giamir** [comment]
I have the same problem. Did you find a solution?

**Comment by GiacomoSorbi** [comment]
Nope :(

**Comment by Katbow** [comment]
There is a workaround for this. If you were using the character ϴ, for example, you can use "\u03F4" in your code and tests.

**Comment by GiacomoSorbi** [comment]
Tried something like that, but if I save and reload the kata with, say &#ASCIICODEHERE;, I get it replaced by the forbidden characters and we are in the same starting condition...

**Comment by jhoffner** [comment]
@GiacomoSorbi see #844 for more details. I believe these are the related issues, though without a specific challenge I can't test. I've fixed the issue where the server sometimes tries to re-encode already encoded characters. 

I will be releasing the changes to production today, preview is ready for testing.
