### ISSUE TITLE
Emailing me on my old email...

### ISSUE THREAD

**Issue by abdekker** [Codewars/codewars.com#961]
My account email is BLAH@gmail.com. It used to be BLAH@fsmail.net but I recently had to change it because Orange is closing down fsmail. The first part of the account is the same.

If I select my profile picture (upper right in the browser) then Account Settings the email is correct (the new one). Under Preferences > Email notifications my selection is "Send me digest emails once a day".

Problem is that emails are being sent faithfully once-a-day to BLAH@fsmail.net...and nothing gets sent to BLAH@gmail.com. You have a stale email in your system somewhere and a bug in the "Email update" procedure.

Thanks,
user = abdekker

**Comment by brogrammerray** [comment]
I'm also having this problem. Switched from gmx.com -> mail.com, shows as changed under account settings, but weekly coding challenges still go to old email.

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there with your account information.
