### ISSUE TITLE
JS Test.assertApproxEquals: Does not work if expected value is 0

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#962]
![image](https://cloud.githubusercontent.com/assets/14909989/26024199/94782b20-37ff-11e7-95c9-8702b711b14f.png)

**Comment by kazk** [comment]
Probably better to open this on Codewars/codewars-runner-cli.

@DonaldKellett I haven't looked into this yet, but I think `actual == 0` needs to be handled like how you did for `expected`.

**Comment by DonaldKellett** [comment]
@Voileexperiments This issue has now been addressed by Codewars/codewars-runner-cli#435 so please close this Issue once that PR is merged.

**Comment by Voileexperiments** [comment]
@DonaldKellett No problem.

Incidentally, are you free to get around to fix this kata of yours?

https://www.codewars.com/kata/strings-strings-strings-hard/javascript

I've enlisted the proposed fix in the kata comments.

**Comment by DonaldKellett** [comment]
@Voileexperiments Thanks for notifying me with regards to that broken Kata, it should be fixed now :smile:  Would you mind testing it for me to check for any other potential Issues?
