### ISSUE TITLE
Some profiles show a Twitter icon even though a Twitter account is not connected

### ISSUE THREAD

**Issue by connorkendrick** [Codewars/codewars.com#964]
Some profiles on the website show a Twitter icon even if they have not linked their Twitter account to their profile. The icon leads to Twitter's login page if no account is connected. This is a little confusing if you are expecting it to lead to the user's personal Twitter page.

This issue does not seem to occur for the GitHub icon.

[Here's a link to my account as an example of the problem](https://www.codewars.com/users/connorkendrick)

[Some profiles do not have this issue](https://www.codewars.com/users/iRayan7)

**Comment by PilgrimShadow** [comment]
My account is one of these. After unlinking my twitter account, the icon remained.

**Comment by e-mihaylin** [comment]
same issue for me:
https://www.codewars.com/users/e.mihaylin

**Comment by kazk** [comment]
Found the cause and fixed it. I'll close this when it's deployed.

**Comment by kazk** [comment]
Fixed. Note that it might take some time for the cache to invalidate.
