### ISSUE TITLE
Allowing 'fork' kata?

### ISSUE THREAD

**Issue by MarisaKirisame** [codewars/codewars.com#966]
So once a kata is published, only the author can renew it.

This is somewhat troublesome if problems are later founded, or worse, backward incompatibility of language makes it impossible to pass, as in the case of https://www.codewars.com/kata/data-types-a-la-carte/haskell

It will be good if there are some process to fix a kata (with the author being away)

some method to do this is: 
allowing to publish 'unoriginal' content under some circumstances: we can then make a new Data Types a La Carte
forking a kata: this is basically the above, but with ability to reuse kata (by forking and/or pull requesting). Diff/Merge conflict is a non issue since kata is < 1000 loc.

there should also be some similarity measure, so a user will not see similar kata too much, and a user can only gain honor once per 'similar group' of kata.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1fjn) by [Unito](https://www.unito.io)

**Comment by Voileexperiments** [comment]
Editing published katas is an *cough* open problem.

Currently the proposed solution is to open up a new privilege tier that allows editing published katas, but it's still not implemented yet.

Forking a kata is currently doable by, well, just publishing a new kata and saying said kata is inspired by the original kata or something.

Incidentally, speaking about broken kata, I've published a list of all broken JS katas (#940), and AFAIK there are *lots* of broken Python (usually range/xrange stuff)/Ruby/C#/Java translations as well. So it's a long-standing problem right now.
