### ISSUE TITLE
BUG - Invert Value

### ISSUE THREAD

**Issue by adrianoresende** [Codewars/codewars.com#970]
Train: https://www.codewars.com/kata/invert-values/train/javascript

Solution correct code:
```
function invert(array) {
   if (array == 0) { return array }
   for (var i = 0; i < array.length; i++) {
     (Math.abs(array[i]) == array[i]) ? array[i] = -Math.abs(array[i]) : array[i] = Math.abs(array[i])
   }
   return array
}
```

I got error:
![image](https://cloud.githubusercontent.com/assets/798755/26264210/59e14f52-3cb2-11e7-8855-1886f03893c4.png)

**Comment by kazk** [comment]
Please read the issue template:

> A few things to check first:
>
> Is the issue you are filing related to a specific kata?
>
> If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

---

I was able to complete the shown kata right now and found no issues.
Make sure that you're not modifying the given `array`.
The error you're getting is from assignment inside the loop, `array[i] = ...`.
I do think the kata should be more clear about this in the description, but you should suggest that on the kata [discourse](https://www.codewars.com/kata/invert-values/discuss/javascript).
