### ISSUE TITLE
Cursor on the solution section went bold and green. Can't Type!!!

### ISSUE THREAD

**Issue by ArunavaDW** [Codewars/codewars.com#971]
So, that's pretty much it. I opened up the console for solving a kata and bam! Can't type! [Key Presses aren't displaying any output]
It was working fine yesterday at 01:00AM IST.
Is it just me? Or is there some issue?
![screenshot from 2017-05-20 07-45-10](https://cloud.githubusercontent.com/assets/25316930/26272191/4b0c88f6-3d30-11e7-8b2e-807802d87183.png)

**Comment by kazk** [comment]
Looks like vim's "normal" mode.  Typing `i` should allow you to start typing.
There's a "VIM"/"EMACS" switch above the editor. Select "EMACS" if you don't like vim.
![image](https://cloud.githubusercontent.com/assets/639336/26272204/d6025a94-3cc7-11e7-9052-29c932eae891.png)

**Comment by ArunavaDW** [comment]
Oh, the vim and emacs modes, yeah I knew about it and yes it was in vim mode. I love vim. Its just that every other time I started up a kata, It was by default in the emacs mode(which I didn't even noticed) and I started typing. But, this time it somehow was in vim mode and I didn't noticed that either. 
Anyway, thank you! :) 
Sorry to open a issue so naive.
