### ISSUE TITLE
/users/:user/completed_solutions returns 500 error "undefined method `code_challenge_review' for nil:NilClass"

### ISSUE THREAD

**Issue by kkorus** [Codewars/codewars.com#973]
Hello,

I can't see my submitted solutions, each time I enter page I keep getting:

![image](https://cloud.githubusercontent.com/assets/2054009/26284134/fc17468a-3e2b-11e7-9c5c-5b477b646139.png)

**Comment by kkorus** [comment]
@jhoffner  Will this going to be fix soon?

**Comment by kazk** [comment]
@kkorus he's on vacation right now.

By "submitted solutions", do you mean <https://www.codewars.com/users/kkorus/completed_solutions>?

---

Possibly related #944

**Comment by kkorus** [comment]
@kazk 
Yep, thats it, keep getting this error.

**Comment by kazk** [comment]
Ok, then this is the same issue as #944 which seems to have resolved itself :/

**Comment by kkorus** [comment]
I think it can be closed.

**Comment by kazk** [comment]
@kkorus thanks!
