### ISSUE TITLE
Modularize 'create kata'

### ISSUE THREAD

**Issue by MarisaKirisame** [Codewars/codewars.com#975]
So, there are a lot of copy/pasting inside a kata.
For example, copying the solution/initial solution
test case/example test case
they can be modularized, by using some kind of block to indicate 'initial solution'/'example solution'
maybe in the form as
x = {INITIAL: undefined, 42}
I am really bad at giving syntax, but I think you get what I mean.

**Comment by kazk** [comment]
Closing because this will require major rework and we don't have any extra resources at the moment. Thanks for the suggestion.
