### ISSUE TITLE
Feature request: Complexity requirement in challenges

### ISSUE THREAD

**Issue by damondouglas** [Codewars/codewars.com#977]
I would like to request that challenges contain complexity requirements.  An example is shown below from [codality](https://codility.com/programmers/lessons).

```
Complexity:

expected worst-case time complexity is O(N);
expected worst-case space complexity is O(1), beyond input storage (not counting the storage required for input arguments).
```

**Comment by Voileexperiments** [comment]
You can usually implement such requirement by doing stress tests using lots of tests/tests with huge sizes.

If your solution is too bad in complexity then it timeouts :) And if it uses too much memory, it uses up all the memory and halts, so that's also a timeout.

**Comment by kazk** [comment]
> Use of time complexity makes it easy to estimate the running time of a program. Performing
an accurate calculation of a program’s operation time is a very labour-intensive process
(it depends on the compiler and the type of computer or speed of the processor). Therefore, we
will not make an accurate measurement; just a measurement of a certain order of magnitude
> https://codility.com/media/train/1-TimeComplexity.pdf

I'm *guessing* Codility estimates by providing sets of tests with varying sizes and observing the relationship between the input size and the execution time (maybe average memory usage for space complexity).
This requires controlled input and stable machine performance.
Code challenges on Codewars are community driven and it's not possible to enforce this for every challenge.
If the author wants to make this a requirement, s/he can provide tests like @Voileexperiments described. I've seen some challenges doing this, e.g., solution timeouts unless it's `O(log n)`.
