### ISSUE TITLE
Unable to contribute translation

### ISSUE THREAD

**Issue by ChristianECooper** [Codewars/codewars.com#98]
I added a Python translation [here](http://www.codewars.com/kata/5514e5b77e6b2f38e0000ca9/edit/python) for the ["+1 Array"](http://www.codewars.com/kata/plus-1-array) kata, but when I hit publish I get the validation popup, but then nothing after, it just hangs.

I haven't completed the kata in either of the two existing languages (JavaScript & C#), but the kata is flagged to allow contributions, and I have the priv for contributing to kata marked that way.

**Comment by GiacomoSorbi** [comment]
It may be due to the fact that there is already a Python translation of mine?

If I published it first, AFAIK you can only fork mine, not put another one. In case someone is interested, I didn't get any notification about your work on that kata.

**Comment by jhoffner** [comment]
Anyone know if this is still an issue? I haven't heard anything about it in a while it seems like it might have resolved itself.
