### ISSUE TITLE
CW API: Completed code challenges JSON is too big for power users

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#981]
So, @ice1000 was making an android CW app. We were wondering yesterday why it has problems loading my completed kata list, and it turns out the list is so big even 10 seconds is far from enough to fetch the whole JSON. In fact, not even Chrome can successfully fetch the whole JSON! (My rough estimate on the size of the JSON file would be around 50MB.)

Every power user who has solved at least 1-1.5k katas will have this problem.

Is it possible to enable paging for the API so that it only returns, like, 100 results at a time, like how most other APIs do? Fetching the whole list becomes infeasible and resource-consuming for anyone who has solved enough katas.

(also, completed katas list fetches deleted katas and katas with a slug of `null` as well (see #947). The latter is probably minor, but the former is really annoying for people who want to deal with CW API data.)

**Comment by kazk** [comment]
That endpoint used to return error page in HTML (!) when the requested user had completed more than ~1.2k. I reported it last month and it's nice to know it's now returning JSON :)

**Comment by kazk** [comment]
@Voileexperiments 

> the API says that score is 31364 but the honor is only 21057 then what does the score even mean?

As far as I know, `score` determines your `rank` (`dan` and `kyu`). That's why there're scores for `overall` and for each `language`.

**Comment by Voileexperiments** [comment]
Wait, apparently it's still giving a server error page.

Though it also spends like half a minute to respo nd for any sizable queries, which is a lot of waiting and may cause timeouts.

**Comment by Voileexperiments** [comment]
> As far as I know, score determines your rank (dan and kyu). That's why there're scores for overall and for each language.

How are they related to each other then? I have 30k score in JS but only 18k honor for completing JS katas.

**Comment by kazk** [comment]
> Wait, apparently it's still giving a server error page.

Looks like it's not fixed, I just tried and got same result.

> My rough estimate on the size of the JSON file would be around 50MB.

The largest successful response I had last month was `331 KB` and this user had `1383` completions.

---

> How are they related to each other then?

`score` and `honor` are unrelated. `score` is purely based on how much kata you did.
You earn `score` for each completed kata depending on the `rank` (not color) of the kata.

For example, when you complete a `6 kyu` kata in JavaScript, `ranks.overall.score` and `ranks.languages.javascript` increases by `8`. When you complete the same kata again in Python, `ranks.languages.python` increases by `8`. For `5 kyu`, the `score` increases by `21`.

**Comment by ice1000** [comment]
It's not only an Android App, it's an app based on Fuchsia's UI framework flutter.
So if I have a MacOS computer with Xcode environment I can build the iOS app too.
Currently I build apk(for Android) and flx(for Fuchsia) only.

**Comment by ice1000** [comment]
I'm against your estimate on the size of the JSON.
I have 108 completed Katas and the JSON is about 21kb, while you have 3,036 completed katas and it might be about 620kb.

**Comment by 10XL** [comment]
Did you check the response headers?

Related: https://github.com/Codewars/codewars-api-docs/issues/4#issuecomment-283506774

**Comment by kazk** [comment]
Like I wrote above, the issue isn't the size. It's simply taking too much time to respond.
When I mentioned this issue last month, @jhoffner replied:

> The API isn't maintained very well, since its not used that often AFAIK. I didn't realize that was choking so I can take a look. Now that the pre-calculated stats exist I should be able to make that endpoint much faster.

Pagination will be convenient, but that requires breaking changes like new parameters and changing returned JSON to include the offsets.

---

If I was designing the API, I'd also provide filtering and endpoints for some common subsets for convenience.

**Comment by jhoffner** [comment]
I've added pagination to the endpoint, and updated the docs. There are no breaking changes since it only required adding 2 new JSON fields, in addition to the `data` field already given. I've defaulted the result set size to 200 records per page to prevent the server from getting hammered too hard.

**Comment by kazk** [comment]
@jhoffner
Isn't this breaking change?

- Introduced a query parameter `page`, response fields `totalPages` and `totalItems`
- Changed the meaning of `data` field (all completed challenges to sublist)

This, especially the redefinition of `data`, seems backward incompatible to me.

For example, if someone had written a personal tool to keep track of her/his completed challenges and if the number had been small enough to cause no issue, this change will suddenly break the tool.

I just wanted to clarify what I meant by "breaking changes" above.
Thanks for fixing this quickly :)

**Comment by jhoffner** [comment]
@kazk
The query parameter is optional and the `totalPages` & `totalItems` fields are metadata. Ignoring all of these should continue to function as normal. `data` isn't a redefinition, it's the same as before. I had thought for a second about adding a `meta` field instead of putting totalPages/Items at the root level but figured anything that wasn't `data` was meta.

The 200 item limit per page is perhaps a breaking change (though nothing actually hard breaks). I could have made it 1000 and then it would be about the same as it was before, however I wanted to take pressure off of the servers and this is the only way. My comment before of

> Now that the pre-calculated stats exist I should be able to make that endpoint much faster.

didn't turn out to be relevant for this endpoint, so there wasn't much else I can do to speed things up. In the end I figured whether it was 200 or 1000, people should be updating their code at some point to check for pagination either way.

**Comment by kazk** [comment]
@jhoffner thanks for explaining in detail :]

---

Do you still want to keep `codewars-api-docs` separate?
I couldn't tell from your response (https://github.com/Codewars/codewars.com/issues/881#issuecomment-299552355).
I've updated the OpenAPI version to reflect the change and it shows that `page` parameter is optional more clearly.
![image](https://cloud.githubusercontent.com/assets/639336/26612955/11e75db8-456d-11e7-88f6-0af1774dbae6.png)
<https://kazk.github.io/docs.codewars.com/api/#operation/getCompletedCodeChallenges>

I also listed some benefits of using OpenAPI in https://github.com/Codewars/codewars.com/issues/881#issuecomment-299574165.

---

Also, did you change how the error is handled?
If I remember correctly, requesting for non-existent user (for example `foo`)

```sh
curl "https://www.codewars.com/api/v1/users/foo/code-challenges/completed"
```

used to return

```json
{"success": false, "reason": "not found"}
```

with status `404`.
Now that returns `5xx: Server Error` HTML page.

- `/code-challenges/foo` returns JSON error
- `/users/foo` returns JSON error
- `/users/foo/code-challenges/authored` returns HTML error
- `/users/foo/code-challenges/completed` returns HTML error

**Comment by jhoffner** [comment]
> Do you still want to keep codewars-api-docs separate?

The OpenAPI docs you built are much better, I'm all for switching over to these. I guess the next step would be to transfer docs.codewars.com over to the codewars org and then I'll update the CNAME/DNS to point there. I'm still traveling but I can try to get to it ASAP.

> Also, did you change how the error is handled?

This issue is now fixed.

**Comment by kazk** [comment]
> I guess the next step would be to transfer docs.codewars.com over to the codewars org and then I'll update the CNAME/DNS to point there.

Do you mean `Codewars/docs.codewars.com` as a separate repository instead of this repo's `/docs`?

**Comment by jhoffner** [comment]
Ah so just commit the files from that repo into this one. Yeah that makes sense.

Thanks,

--
Jake Hoffner
Sent with Airmail

**Comment by kazk** [comment]
@jhoffner 

I think the workflow will be like:

- Commit contents in `kazk/docs.codewars.com` to `kazk/codewars.com:master` for #900
  - `echo docs.codewars.com > ./docs/CNAME`
- Merge #900
- Setting > Select source: select "master branch /docs folder"
- Setting > Custom domain: enter "docs.codewars.com"
- Configure DNS
  - Enforcing HTTPS on custom domain might require further configuration

[Publishing your GitHub Pages site from a `/docs` folder on your `master` branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)

---

I'll start this in few days, hopefully tomorrow.

Before we start accepting contributions, we need to decide the license.
I usually make my code permissive (MIT/BSD-3-Clause/ISC/Apache-2.0), but I don't have strong opinions. Maybe aligning with codewars.com?

> To promote collaboration and create a living resource, all kata solutions are actively opensourced under the FreeBSD 2-Clause License. All authored kata remain the IP of authors and contributors, with a license granted to Codewars, to maintain and advance the resource.
> https://www.codewars.com/about/terms-of-service

I'm fine with whatever you choose.

**Comment by kazk** [comment]
@jhoffner I'm going to repost above comment in #900 to leave this issue alone :)
