### ISSUE TITLE
Solvers' issues

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#983]
Epic of issues reported by solvers.

---

I realized that "Epic" is confusing for people without [ZenHub](https://www.zenhub.com/). I'm using this to group existing issues:

![image](https://cloud.githubusercontent.com/assets/639336/26690722/399850b8-46af-11e7-91b5-d2b5fe13d59b.png)

**Comment by devhulk** [comment]
`var digitalRoot = (num) => {
  let split = num.toString().split('')
  let sum = 0
  split.forEach((value) => {
    sum = sum + parseInt(value)  
  })
  console.log(sum)
}

digitalRoot(16)`

Is Kata not using es6? this solution works for me when I test individually. I could be stupid though lol

**Comment by kazk** [comment]
@devhulk Please ask kata specific questions on the kata discourse page.

I don't know the details, but most of Codewars katas require you to `return` something. So you usually need to `return sum` and not `console.log(sum)`.
