### ISSUE TITLE
CW backend processing randomly stops working

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#991]
What happens when CW services are dead:

- No notifications
- Published and beta kata search results do not update (new beta katas and approved katas)
- Publish katas keeps timing out

**Comment by jhoffner** [comment]
The backend services went down twice in the last month. I'm back from vacation on Tuesday and will be investigating into why this happened.

**Comment by Voileexperiments** [comment]
It's happening again :(

**Comment by jhoffner** [comment]
The queue seems to be backed up but processing is happening. Just a bunch of low priority tasks that are backlogged. What was it specifically that caused you to notice this?

**Comment by Voileexperiments** [comment]
There are several things that are very noticeable when it happens:

- New replies that should've shown a notification is not shown
- Similar, notification emails are not sent
- When searching beta katas, katas that just got approved remains on the search result
- Publishing becomes slow and sometimes timeouts

**Comment by Voileexperiments** [comment]
Another reminder that it's happening again :(

**Comment by kazk** [comment]
Closing because a lot have changed since this issue was reported.
Please open a new issue if the problem is not fixed.
