### ISSUE TITLE
CW homepage: Discourse randomly returns cached result between reloads

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#992]
Sometimes the discourse section of CW homepage is returning a cached version that can be as far as 1 hour earlier. Sometimes it's real-time, however.

It seems that which result is served to the user is totally random, and if you refresh the page several times, you'll see both occurence.

**Comment by Voileexperiments** [comment]
Apparently it's even worse, as I've encountered 3 cached versions of the discourse content as I refresh the dashboard. Wut? How does the cache even work in the first place?

![image](https://user-images.githubusercontent.com/14909989/53382103-06a3c680-39ae-11e9-8344-3125b252929c.png)

![image](https://user-images.githubusercontent.com/14909989/53382145-35ba3800-39ae-11e9-9020-bff8a0f3212d.png)

![image](https://user-images.githubusercontent.com/14909989/53382151-3a7eec00-39ae-11e9-8a54-02df9f651488.png)

**Comment by kazk** [comment]
We have 3 Memcached servers that was set up by a contractor. To use multiple Memcached servers, we need to have a router in between like [mcrouter](https://github.com/facebook/mcrouter) so he also set that up for us.

Unfortunately, the caching library used by Codewars didn't support it so we couldn't use it. The contractor removed mcrouter and we ended up with an endpoint that just load balances to those 3 servers. So we currently have 3 sets of caches :man_facepalming: 

I've been wanting to fix this for a while, but I've had other things to do.

**Comment by kazk** [comment]
The issue of having 3 sets of caches is fixed. But the original issue might be still there (I just noticed you opened this in 2017).
I haven't seen this happen yet, but it might only happen when the cache becomes large.

Please let me know if this starts to happen again so I can reopen.
