### ISSUE TITLE
Codewars Red - honor points dropped from 1151 to 671

### ISSUE THREAD

**Issue by wenima** [Codewars/codewars.com#995]
Right when I submitted my last kata (https://www.codewars.com/kata/53db96041f1a7d32dc0004d2) my honor points dropped by little less than half. Everything else about my account seems normal. Logging out/back in doesn't solve the issue.

<img width="1195" alt="screen shot 2017-06-10 at 11 41 33 pm" src="https://user-images.githubusercontent.com/22766301/27012460-dc5f1df4-4e84-11e7-8873-35185378100b.png">
<img width="1124" alt="screen shot 2017-06-11 at 9 00 51 am" src="https://user-images.githubusercontent.com/22766301/27012463-e92073da-4e84-11e7-83e4-0e470c219e3a.png">

**Comment by wenima** [comment]
seems like it's not accounting for all yellow code kata as per the events page:

<img width="1108" alt="screen shot 2017-06-11 at 10 05 15 am" src="https://user-images.githubusercontent.com/22766301/27012858-850b9920-4e8d-11e7-92ab-714649dc86f8.png">

**Comment by kazk** [comment]
I don't know what happened, but your profile seems to be fixed now.

![image](https://user-images.githubusercontent.com/639336/27048402-8521d748-4f60-11e7-8105-fa699cd8e74e.png)

**Comment by jhoffner** [comment]
Since this is working again I'm going to close, chalk this up to possibly an issue with the recent background processing issues, or just a random glitch. If this happens again we can reopen and I'll investigate further.

**Comment by wenima** [comment]
thanks for looking into it. yes, it went back to correct points after solving next kata.
