### ISSUE TITLE
HTTP redirects in mailing

### ISSUE THREAD

**Issue by martinek** [Codewars/codewars.com#996]
Hi

I'm not sure where to report this issue, but site referred me here.
I received Weekly Coding Challenges and after clicking on one of the challenges I got redirected to the challenge. The redirect itself was to http version of website.

This in itself would not be problem, but some of sites features do not work on http (XHR requests fail). Looks like `Access-Control-Allow-Origin` header does not have `http://www.codewars.com`. This could be reported as separate issue, I'm not sure if site is supposed to be used on http.

Right now I would expect mailing links to redirect to https.

**Comment by kazk** [comment]
Sorry for the lack of response. This is fixed.
