### ISSUE TITLE
Make kata awaiting approval easy to find

### ISSUE THREAD

**Issue by kazk** [codewars/codewars.com#999]
@smile67 wrote on /topics/feature-requests

> An entry like "Waiting for approval" at "Kata Search -> Sort by:" would be helpful - i think;-).

and https://github.com/Codewars/codewars.com/issues/997#issuecomment-308163232

---

How about "Awaiting Approval" "Status"?

![image](https://user-images.githubusercontent.com/639336/27095670-62851ca4-5023-11e7-9fc5-c026a14d8c8b.png)

**Comment by smile67** [comment]
Perhaps better, doesn't block "sort by";-)... Thanks!

**Comment by jhoffner** [comment]
Workaround is already possible by searching for "needs_approval". I could see this being its own filter once users earn the ability to approve. Leaving as a low priority new feature.

**Comment by Voileexperiments** [comment]
Maybe if we can search for "waiting for approval" we can also search for other beta status? For example, "waiting for issues to be resolved" means the kata is ready for approval but has open issues. Similarly, "ranking needed" and "testing needed" are different kind of status.

**Comment by jhoffner** [comment]
values that should be searchable:

- `needs_testing`
- `needs_ranking_feedback`
- `needs_correction`
- `needs_approval`

**Comment by jhoffner** [comment]
After more thought I think it does make sense to show these in a dropdown for all users. The dropdown would only show if "Status = Beta" is set.

**Comment by smile67** [comment]
Thanks for these infos! Thought there are more katas marked "needs_approval";-)... So there's a big gap between "beta katas" and these ones: more than 1500 betas in my list "solved", but only about 10 needs approval...

**Comment by kazk** [comment]
Added `Beta State` filter that's only shown `Status` is `Beta`.

![image](https://user-images.githubusercontent.com/639336/142815519-65f6a108-62a0-4453-997f-3c88a080f39d.png)
